### ISSUE TITLE
Add initial build for RTD

### ISSUE THREAD

**Issue by willingc** [jupyterhub/zero-to-jupyterhub-k8s#1]
Add initial structure and deployment to RTD.

**Comment by choldgraf** [comment]
hey - I send a message about this a little bit ago on slack, is that not a good place to reach you? it's currently deployed to:

http://zero-to-jupyterhub.readthedocs.io/en/latest/

**Comment by willingc** [comment]
Hey @choldgraf, What channel did you send it to? I didn't get it though I will be the first to admit that I'm not tied to any social media. Gitter is usually better or better yet an issue with an @-mention.

Deployment looks fine. We do need to modify the title on readthedocs to be specific to k8s. There's a few other housekeeping items related to hosting on readthedocs and how we typically structure and build the Jupyter docs.

I'm going to close this and I'll leave some other issues tomorrow as I'm about done for my day ;-)

**Comment by choldgraf** [comment]
sounds good! I sent it to you as a DM on the uc-jupyter slack channel, but I'll use gitter from now on.

Def other updates to make on these docs (also there's the dopey logo that I threw together just because I needed something to put there...that should probably be updated with something official)
