### ISSUE TITLE
Image-Puller failing constantly

### ISSUE THREAD

**Issue by dkipping** [jupyterhub/zero-to-jupyterhub-k8s#1001]
Hello,

Referencing to #726 #735 #477 , we seem to still experience a bug related to this.

We are running a jupyterhub in AKS on Azure and when performing an install or upgrade of the helm chart, one of the image-pullers will always fail and be terminated, resulting in a new image-puller being launched. The other two image-pullers finish pulling the image just fine.

This way, the image-awaiter job will never finish.
A workaround is to delete the hook-image-awaiter job, then the install / upgrade will finish.
![image](https://user-images.githubusercontent.com/11467327/47792049-69949200-dd1b-11e8-95b0-ae1a69120bb2.png)

We are using the helm chart version 0.7.0, so according to @consideRatio 's comments on the other issues, the problem should be fixed.
There is also nothing special the config.yaml:

**Content of `config.yaml`**
```
proxy:
  secretToken: <secret>
  service:
    loadBalancerIP: <myIP>
singleuser:
  # defaultUrl: '/lab'
  image:
    name: <myImage>
    tag: <myTag>
  imagePullSecret:
    registry: '<myRegistry>.azurecr.io'
    username: '<myUser>'
    password: '<myPassword>'
    enabled: true
  storage:
    type: none # turns of persistent storage per user
hub:
  extraConfig: |
    # c.Spawner.cmd = ['jupyter-labhub'] # adds the Hub menu option in JupyterLab
    c.Authenticator.admin_users = {<myAdmins>}
    # c.JupyterHub.allow_named_servers = True

    # following lines for dev purposes deactivating CORS
    c.Spawner.args = [f'--NotebookApp.allow_origin={"*"}']
    c.JupyterHub.tornado_settings = {
        'headers': {
            'Access-Control-Allow-Origin': '*',
        },
    }
    c.NotebookApp.allow_origin = '*'
```

**Comment by consideRatio** [comment]
Oh hmmm perhaps there is a reason, such as missing disk space on the node that has a puller that fails?

If you could find the events listed if you use the kubectl describe command, that would give us more insight i think.

**Comment by dkipping** [comment]
You were absolutely right. Should have thought about that earlier.

```
Events:
  Type     Reason   Age   From                               Message
  ----     ------   ----  ----                               -------
  Warning  Evicted  1s    kubelet, aks-agentpool-4xxx-2  The node was low on resource: [DiskPressure].
```

Strangely enough that's a node nothing is running on, so there are issues on the kubernetes side.
Apologies for the misleading issue filing here.

**Comment by consideRatio** [comment]
Ah no worries, thanks for the followup!
