### ISSUE TITLE
[Question] Both types of image pullers working after scaling up a cluster

### ISSUE THREAD

**Issue by ablekh** [jupyterhub/zero-to-jupyterhub-k8s#1007]
After scaling up one of our clusters, I'm seeing that **both** _continuous_ and _hook_ image pullers are working on deploying relevant image to newly provisioned nodes. I was under the impression that **only a single type** of available image pullers would be working in a particular case, based on a relevant trigger event: _scaling up_ or deployment's _upgrade_ via Helm. So, in this case, I was expecting to see only continuous image puller to work. Is the situation that I'm currently observing normal and, if Yes, what is the rationale for such behavior / implementation?

```
ablekh@mgmt:~/sbdh_jh_v2.2$ kubectl get pods --namespace=sbdh-rstudio-v1
NAME                            READY     STATUS     RESTARTS   AGE
autohttps-5dd788ccfc-j2rd7      2/2       Running    0          9d
continuous-image-puller-2czd5   0/1       Init:0/2   0          2m
continuous-image-puller-5htvh   0/1       Init:0/2   0          1m
continuous-image-puller-8fptm   0/1       Init:0/2   0          2m
continuous-image-puller-9mfrr   0/1       Init:0/2   0          2m
continuous-image-puller-jgnk7   0/1       Init:0/2   0          2m
continuous-image-puller-jpts2   1/1       Running    0          13d
continuous-image-puller-krwnf   0/1       Init:0/2   0          2m
continuous-image-puller-tvckx   0/1       Init:0/2   0          2m
continuous-image-puller-w9rpk   0/1       Init:0/2   0          2m
continuous-image-puller-ztkvq   0/1       Init:0/2   0          2m
hook-image-puller-8s6n7         0/1       Init:0/2   0          2m
hook-image-puller-98qdd         1/1       Running    0          13d
hook-image-puller-fl68k         0/1       Init:0/2   0          2m
hook-image-puller-gghrz         0/1       Init:0/2   0          1m
hook-image-puller-h6r2b         0/1       Init:0/2   0          2m
hook-image-puller-hjchq         0/1       Init:0/2   0          2m
hook-image-puller-hm8xk         0/1       Init:0/2   0          2m
hook-image-puller-rxqkr         0/1       Init:0/2   0          2m
hook-image-puller-v6ktg         0/1       Init:0/2   0          2m
hook-image-puller-vqs9n         0/1       Init:0/2   0          2m
hub-67d454fdb8-79x28            1/1       Running    0          9d
proxy-59fbbf69fd-6cjpg          1/1       Running    0          9d
```

**Comment by consideRatio** [comment]
Hmmmm, so the continiuous will keep running non stop no matter what, and lay dormant and do nothing when it is completed until it gets a new instruction on what images to pull.

The hook puller will pull images to all nodes before letting the upgrade proceed so that when the hub starts spawning pods with the new image, it is available right away.

Hmmm, im not seeing the hook image awaiter pod! it seems like the hook inage awaiter job finished before the hook image pullers were done, this should not happen.

Why did the hook image awaiter job's pod finish ahead of them? I got no immediate guess as to why... hmmm

**Comment by ablekh** [comment]
> ... so the continiuous will keep running non stop no matter what, and lay dormant and do nothing when it is completed until it gets a new instruction on what images to pull.

**Yes.** As to your other questions/comments, I don't know why hook puller was not behaving as expected. It would be great to have in a documentation a very clear description of correct behavior of both types of _z2jh_ image pullers.

Should you or someone else have any ideas, please let me know. I plan to create some other clusters for testing / integrating desired functionality, so I will let everyone know if pullers are IMO misbehaving ...

**Comment by consideRatio** [comment]
I think this issue is almost gone with Helm3 and `--cleanup-on-fail` flag as part of `helm upgrade`, so I'll go ahead and close this issue.
