### ISSUE TITLE
Jupiter hub not accessible after setting the private topology

### ISSUE THREAD

**Issue by tregin** [jupyterhub/zero-to-jupyterhub-k8s#1008]
## Contents of `config.yaml`
```
Hello

I have managed to install the Jupiter hub on the Kubernetes cluster following your article.
I had to us the option for the private topology so the instances are not accessible from outside.
I have used the following command when setting up the cluster...
--topology private 
--networking weave 

The issue I have at the moment is when I deploy the jupiter hub on the master node I'm unable to access the "External IP address" in the browser listed after typing the command:

 kubectl --namespace=jhub get svc proxy-public --output=wide

My question is how to access the Jupiter hub web interface.

Thank you very much

```

**Comment by dkipping** [comment]
Did you check that there were no underlying issues from AWS instead of from the jupyterhub itself?
So maybe the IP has to be whitelisted in a firewall or something like this?

**Comment by tregin** [comment]
Hi 
Thank you for the reply
I have managed to sort it now but now facing a different issue for this exercise.

By default when Jupyter hub in deployed it created the Internet facing Loadbalancer through which the Jupyter hub is accessitble. 
My question is if it is possible to configure a Internal Loadbalancer that would reside in a specific subnet during the setup? The aim is to have Jupyter hub link accessible only internally? 

Hope that makes sense...

**Comment by dkipping** [comment]
I'll refer you to this issue for that: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1014

Than you can try it out like I described there, and we can keep the discussion centralized in that issue.

**Comment by tregin** [comment]
Thanks a lot that was the case!
