### ISSUE TITLE
Breaking change: hub.extraConfig no longer works as a simple string

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/zero-to-jupyterhub-k8s#1009]
In v0.7, the following works:

hub:
  extraConfig: |
    print("hi", flush=True)

In 0.8, this fails with:

```
      File "/srv/jupyterhub_config.py", line 424, in <module>
       for key, config_py in sorted(get_config('hub.extraConfig', {}).items()):
   AttributeError: 'str' object has no attribute 'items'
```

We *should* be backwards compatible, since it's a small check.

**Comment by tjcrone** [comment]
@yuvipanda, is there a workaround for this? What is the new required structure of extraConfig?

**Comment by consideRatio** [comment]
The new structure is:

```
hub:
  extraConfig:
    myConfigName: |
      print("hi", flush=True)
```

**Comment by tjcrone** [comment]
Interesting. Relatively easy fix. And myConfigName (the key) can be anything I want? Does this imply that we can have more than one?

**Comment by consideRatio** [comment]
the key can be anything, you can indeed have multiple ones.

this allows helm to merge multiple extraConfigs, while previous didnt, for example if you wanted to have a file with secret values and one with non-secret values this would be useful.
