### ISSUE TITLE
Decide where reference documentation about helm-chart lives

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/zero-to-jupyterhub-k8s#101]
This document is mostly narrative, but it is also the only reference documentation we have. We should ideally have both - reference talking about each of the individual options you can tweak, and also more generic narrative docs that guide people.

There might also be differences in *who* is best positioned to write these docs. Reference docs should ideally be *extracted* from the code it is documenting, so it is as up to date & accurate as possible, while that doesn't work for narrative docs.

We probably *should* have reference docs for the helm-chart that's different from the narrative docs, and the narrative docs should link liberally to it - this helps us keep the narrative docs not too long and laborious. 

We should figure out:

1. How to write and extract reference docs
2. Where reference docs should live
3. How to link narrative docs to reference docs.

**Comment by yuvipanda** [comment]
I'd personally love to have reference docs & narrative docs in the helm-chart repo, but I also have less experience maintaining docs long term than @willingc or @choldgraf - so shall defer :)

**Comment by willingc** [comment]
My gut reaction @yuvipanda is that some of this (or perhaps ultimately all) will move to the the helm-chart repo but it's important that we consider the overall documentation strategy at jupyter.org as well as JupyterHub (for those that may not use K8 for whatever reason). We'll get to something that makes you happy from a developer/maintainer standpoint as well as the users. It will just take some time to percolate up all of the issues (as you have started here) and make sense of the approach going forward.

**Comment by yuvipanda** [comment]
https://github.com/kubernetes/helm/issues/2431 is a good reference here. I would like us to develop a JSON Schema for the helm chart's reference documentation, and both use it to validate a user's config (so we can provide more useful error messages) and for generating documentatioin.

**Comment by willingc** [comment]
I like this suggestion re: JSON schema and ways to validate and guide user configs w.r.t. documentation.

**Comment by willingc** [comment]
FYI [JupyterHub documentation contents across all repos](https://www.dropbox.com/sh/8als8f8cf0mwjjb/AAC5XKs4kLe3QsxgMEKsTKpCa?dl=0)

**Comment by yuvipanda** [comment]
@willingc and @choldgraf sorted this one out!
