### ISSUE TITLE
Deploying jupyter on Internal IP range

### ISSUE THREAD

**Issue by andregouveiasantana** [jupyterhub/zero-to-jupyterhub-k8s#1014]
Hi guys,

I am trying to deploy Jupyterhub on top of the k8s cluster using my internal IPs ranges. I was able to deploy and the workers and nodes were deployed using the internal IPs. I can ssh to the master with this ips without problems, however after I finished the deployment of the JupyterHub itself and run the command  

$kubectl --namespace=jhub get svc proxy-public --output=wide

NAME           TYPE           CLUSTER-IP     EXTERNAL-IP                                                                 PORT(S)        AGE       SELECTOR
proxy-public   LoadBalancer   100.65.225.7   <string>.eu-central-1.elb.amazonaws.com   					80:32192/TCP   25m       component=proxy,release=jhub

I get an internet facing loadbalancer instead of one with one of the internal IPs.   I was wondering if there is a way to have it only internal.

I have searched for an answer for it without success and I am sorry if I am repeating the question...
Rgds,
Andre

**Comment by dkipping** [comment]
Have you tried allocating internal IPs via an internal load balancer?

Though I have not tried that on AWS yet, it should work similar to AKS on azure.

https://docs.aws.amazon.com/eks/latest/userguide/load-balancing.html

Here it is written, that you'll have to provide 
`service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0` (with a matching IP I guess)
And the cluster has to be configured with a private subnet in your VPC.

The annotation can be added in the `config.yaml` to the `proxy` object like this:

`
proxy:
  secretToken: ''
  service:
    type: LoadBalancer
    annotations: 
      service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
`

**Comment by andregouveiasantana** [comment]
Thanks very much.. that seems to be working for me now... Now to the next issue!! :)

Tks again!
