### ISSUE TITLE
Interactive cost estimator Widget Javascript not detected

### ISSUE THREAD

**Issue by kevbutler** [jupyterhub/zero-to-jupyterhub-k8s#1016]
## Details

* Doc URL: https://zero-to-jupyterhub.readthedocs.io/en/latest/cost.html

## Expected Result

Interactively estimate costs using the linked Binder cost estimator (http://mybinder.org/v2/gh/jupyterhub/zero-to-jupyterhub-k8s/master?filepath=doc/ntbk/draw_function.ipynb)

## Actual Result

The second cell that runs the command `fig = cost_display(n_days=7)` results in the following error:

`Widget Javascript not detected.  It may not be installed or enabled properly.`

**Comment by consideRatio** [comment]
We deleted this notebook as it became outdated and not maintained =/
