### ISSUE TITLE
Jupyter hub pod autoscaler (HPA)

### ISSUE THREAD

**Issue by tregin** [jupyterhub/zero-to-jupyterhub-k8s#1019]
Hello everyone

I'm not sure if this is really and issue or it's related... Please delete the post if you think it doesn't belong here.....
Anyway here's my problem:
I have successfully deployed the Jupyter Hub on Kubernetes Cluster by following your guide and I have also setup the Cluster Autoscaler which takes care of my node autoscaling.

What I would like to setup it the POD autoscaler (HPA) for the jupyter hub pods that are created by users.
The aim is to scale up the pod when user starts doing some heavy compute tasks in his Jupyter hub pod.

Is this even possible?
Any comments appreciated!

Thank you

**Comment by Edward-liang** [comment]
@tregin , I met a similar requirement like you do. But I found the following conclusion in earlier issue:

"Horizontal pod autoscaler - nah...
Will increase the number of pods doing a certain task if needed based on for example CPU utilization. This is relevant if you need more copies of the same pod. Each user should only have one pod, not multiple pods, so scaling up in this way makes little sense for the singleuser pods."

I guess jupyterhub group does not plan to support pod autoscaler.



Refer:
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/503

**Comment by consideRatio** [comment]
Oh hey!
Thanks @Edward-liang for jumping in and helping out!

Long story short, I personally don't know how to technically support this, but could imagine a solution being sustainable in the future.

---

I don't see a possible k8s solution that would have multiple pods for a single user. And the user pods are really hard to work with as they are not typical "cattle" pods that can be moved around and replaced. A vertical pod autoscaler could be considered if it stops requiring restarts of the user pod. But... I recall reading about a vertical-pod-autoscaler that would be able to adjust the resource request on running pods assuming it wasn't limited by the node or similar. Assume there is a k8s version and such controller, then that could be plausible. But, then it should probably be deployed a standalone controller that modified the pods without first wrapping them.

To conclude, I'm not sure if k8s supports doing what we would like on running pods without restarts, but if it does, it may be too invasive and require too much reworks on the _kubespawner_ that normally just creates a pod. The only plausible outcome as I see it, is if there is a k8s controller that modified pod resources matching some labelselector.

**Comment by Edward-liang** [comment]
Hey @consideRatio, thanks for your explanation!
Can I understand your introduction as following:
1. vertical-pod-autoscaler does not support pods with customized "guarantee" or "limit";
2. jupyterhub's pods do not support replacement.

I am a bit confused about the second point: If a user leaves experiment for some time, the corresponding node will die. However, the user's experiment material will be automatically persisted on the host of k8s. And when the user come back and open experiment page again, the persisted data would be loaded by a new pod. 
ID of the new pod is different from the original one, I don't know if this progress can be treated as "replacement". 

I read some tutorial of K8s 1.15(>1.13), in which it mentioned: "Horizontal Pod Autoscaling does not apply to objects that can’t be scaled, for example, DaemonSets.". However the sentence is somehow fuzzy to me. 
https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#how-does-the-horizontal-pod-autoscaler-work

**Comment by consideRatio** [comment]
I'm not an expert on the Vertical Pod Autoscaler (VPA), I've never used it, but the idea is that you have a deployment of some kind that ensures that there is some number of pods always available. A VPA would restart these pods from time to time to update their resource request. This restarting is problematic for user pods. It would be like someone restarting your computer without asking you. Your harddrive is still available, but all your work in memory was lost.
VPA only adjust the guarantee part as far as I remember.

JupyterHub will have mutliple different pods, or docker containers, some pods are created by JupyterHub's kubespawner software. The user pods are the challenge, they cannot be restarted without this "restart computer" issue following. Adjusting the provided resources to the pod, without restarting it, that needs to be resolved.

I think that last sentence about HPA and DaemonSets means that the HPA will not try to add more replicas of a DaemonSet if it finds those pods to need more resources. It can be reasonable, if you consider that a DaemonSet will ensure that there are X number of pods running for every node. So a HPA could only ensure to change this X to a suitable manner, but every change of X could result in hundreds of new pods being created by the smallest possible change of HPA. This would be quite scary to automate perhaps, as compared to changing the replicas values of a Deployment.

---

I've considered trying to resolve resource scaling myself for users, and I would recommend using kubespawner's profile list, that is the only technically viable option to do something similar. You would be able to have a user, before the user get's a server created, make a choice on what to get - perhaps the user would like to request a very big powerful pod with lots of resource requested, or just a typical one?

**Comment by Edward-liang** [comment]
@consideRatio Thank you for your detailed explanation. Now I understand the "restart" problem you mentioned. I don't know how to solve it via kubernetes VPA as well.
I spent some time reading the Kubespawner project. According to your suggestion, maybe I can use two profiles in jupyterhub's config.yaml via guarantee or limit option. That indeed can partly solve my problem, thanks!
--- 
BTW, does "Kubespawner profile" point to jupyterhub_config.py file, please?
And I don't know how to make configs in jupyterhub_config.py work (Till now based on my tests, I only find configs in config.yaml works).

**Comment by consideRatio** [comment]
Im on mobile atm, so it is hard to search the repo, but i think there are examples of using singleuser.profileList in config.yaml that configures kubespawners profile_list accordingly. Check out the configuration reference on z2jh.jupyter.org

**Comment by Edward-liang** [comment]
@consideRatio  Thank you very much for the help. After view the document, I managed to get myself to the profile choosing page.
![image](https://user-images.githubusercontent.com/5849761/61932237-6af6a080-afb5-11e9-91d9-f3fd8414bb5c.png)

Now I am wondering if I can hide this page from common user. I mean, I have a service page for user to login and I want to redirect them to different profile-based pods. Instead of letting users  choose, I want to control the access. Are there any restAPI I can use, please?

**Comment by dkipping** [comment]
A quick and maybe hacky version but without having to alter the existing code would be, to add a redirect in the spawner config page in your config.yaml.

You can do that by changing the `_options_form_default` function of you Spawner to something like this:

```
def _options_form_default(self):
              return """
                  <script type="text/javascript">
                      window.location.replace("<your-page>")
                  </script>
                  <h3>Seems like your browser blocked us from directing you to the correct site. Please click the link below.</h3>
                  <a href="<your-page>"> <your-text> </a>
              """
```
 

On your own page you will probably already trigger the spawning of a jupyter environment.
In this request you can just add the parameters for the profiles in the body as a json dict called `profile_options` or `spawner_options`.

If the spawner does not already have an implementation to consume them, then you can adapt the `start` function of the spawner.

See this issue as a reference:
https://github.com/jupyterhub/kubespawner/issues/284

**Comment by consideRatio** [comment]
The original issue was about using a horisontal pod autoscaler, which is about creating more and more pods as they get busier. This is not plausible for any pod in our Helm chart currently though because we cannot support High Availability =/

Closing this issue!
