### ISSUE TITLE
Update this doc for v0.4 of helm-chart 

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/zero-to-jupyterhub-k8s#102]
O'Reilly is going to publish something about the helm-chart and this guide soon, so we should make sure we update this guide for 0.4. We should also make sure people who are still on 0.3 have a way to access the older code.

Easiest and simplest way would be to tag a 0.3.x version of this repo and make 0.4 changes to master. We can then keep making changes to master to reflect 0.4.

Long term, we should figure out #100 and #101.

**Comment by willingc** [comment]
Completely agree with this approach for the short-term. 👍

**Comment by willingc** [comment]
## Changes needed for 0.4

**Creating Your Own JupyterHub Guide**

- [ ] https://zero-to-jupyterhub.readthedocs.io/en/latest/setup-jupyterhub.html#install-jupyterhub Update version in command

**Customization Guide**

- [ ]  https://zero-to-jupyterhub.readthedocs.io/en/latest/extending-jupyterhub.html#applying-configuration-changes Update version in command (or make it generic for current version)
- [ ] https://zero-to-jupyterhub.readthedocs.io/en/latest/extending-jupyterhub.html#authenticating-with-oauth2 Add a full example for GitHub OAuth

**Administration Guide**

- [ ] No changes identified for 0.4
