### ISSUE TITLE
Sometimes failing to shut down pod

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#1022]
The hub fails to detect pods that have successfully shut down, sometimes. This happens about 25-33% of the time.

## Relevant information
Kubectl does not find the pod any more.

The logs of the proxy sais:
```
14:02:57.164 - info: [ConfigProxy] Removing route /user/jaime.ferrando_huertas
14:02:57.164 - info: [ConfigProxy] 204 DELETE /api/routes/user/jaime.ferrando_huertas 
14:03:33.473 - info: [ConfigProxy] 200 GET /api/routes
```

The logs of the hub sais:
```
# ...
[I 2018-11-14 14:06:15.751 JupyterHub base:1018] jaime is pending stop
[I 2018-11-14 14:06:20.318 JupyterHub base:1018] jaime is pending stop
[I 2018-11-14 14:06:20.833 JupyterHub base:1018] jaime is pending stop
[I 2018-11-14 14:06:25.454 JupyterHub base:1018] jaime is pending stop
[I 2018-11-14 14:06:25.913 JupyterHub base:1018] jaime is pending stop
# ...
```

## Questions raised
- What makes the kubespawner realize that the pending stop has succeeded?
- What could have caused this event to not take place?

/cc: @jiwidi

**Comment by jiwidi** [comment]
My thoughts on why this is happening are that I clicked several times on the STOP MY SERVER red button. When you click it there is no feedback for the user to know the server has started to stop so I thought I didn't click it properly and clicked it again.

Now that I only click once it stops correctly. The problem with this is that It took me 5 times to realize about this and I had to ask @consideRatio to restart my pod every one of them.

**Comment by jahstreet** [comment]
@jiwidi
Cool idea, I've tried to click once, but it hasn't help.
Related to: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/816

**Comment by consideRatio** [comment]
I'm not sure whats wrong, but at this point its a bit too outdated to followup without a clear way to reproduce it again.

**Comment by jahstreet** [comment]
@consideRatio , to update: the issue is fixed with the latest versions of JupyterHub.
