### ISSUE TITLE
Make a roadmap for Z2JH

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/zero-to-jupyterhub-k8s#1026]
As part of an ongoing project to make the governance/directions of the JupyterHub project more transparent, what do people think about creating a roadmap for Zero to JupyterHub for K8S?  I feel that this is a dynamic-enough and well-used enough project that it'd be worth signaling some high-level next steps for the community.

**Here's a template HackMD where we can start building the roadmap**

https://hackmd.io/3-500ujURu-Izinz3JmCHQ

Please feel free to add your own language, items, and comments!

**Comment by consideRatio** [comment]
I really like the idea of hackmd as a WIP area

**Comment by choldgraf** [comment]
ok, I added a link to a hackmd in the TLC (https://hackmd.io/3-500ujURu-Izinz3JmCHQ) and we'll see how it goes from there :-)

**Comment by betatim** [comment]
From my side there is one thing that Z2JH should focus on for the coming months: stability and backwards compatibility.

I can't think of big features or changes I'd like to see beyond that. There will be things that come up but we can take them in our stride as they come up. Ensuring backwards compatibility/upgrade-ability and reducing breakage is not a very popular topic though so I wonder how we can combine it with things that people will get excited about.

**Comment by choldgraf** [comment]
I think that you are under-estimating the perceived value of "stability" :-)

cc @yuvipanda and @minrk as they might have specific wish-list items for k8s deployment of jupyterhub :-)

**Comment by consideRatio** [comment]
I'll close this issue at this point in time as its become stale, feel free to reopen with a concrete action point!
