### ISSUE TITLE
Users removed from whitelist can still access Jupyter

### ISSUE THREAD

**Issue by anton-khodak** [jupyterhub/zero-to-jupyterhub-k8s#1029]
I am using Github authentication for JupyterHub with a whitelist, and users that got expelled from the whitelist can still access JupyterHub. They can still access it when their pod is stopped or when they try from a different browser or when they explicitly log out, the only thing that helps is to remove the user from the database completely (via admin panel).

**Comment by consideRatio** [comment]
Thank you for reporting this @anton-khodak ! What version of JupyterHub is running (or, what version of the zero-to-jupyterhub-k8s helm chart have you installed?).

**Comment by anton-khodak** [comment]
I am using 0.7.0

**Comment by dimm0** [comment]
Is it still not fixed?

**Comment by consideRatio** [comment]
Hmmmm hmmmm okay so I don't know if this is fixed or not, or if it is a jupyterhub/jupyterhub issue in the base class Authenticator, or if it is an issue in jupyterhub/oauthenticator, but I'll go ahead and close this issue within this repository as mislocated, and not move it to jupyterhub/jupyterhub or jupyterhub/oauthenticator as it is quite outdated and I'm not sure where to locate it.
