### ISSUE TITLE
Pod Priority configuration options

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#1032]
# Related
- https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-does-cluster-autoscaler-work-with-pod-priority-and-preemption
- https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-can-i-configure-overprovisioning-with-cluster-autoscaler
- Discussion on Slack:
  K8s developers are are unhappy with forcing all users to increase the global cutoff in order to have a lower priority below the default that can still trigger scale up. This is what we currently do, but we don't need to on GKE as I understand it, because the cutoff is configured to be -10 on their autoscalers.

**Parameter** | **Description** | **Default**
-- | -- | --
expendable-pods-priority-cutoff | Pods with priority below cutoff will be expendable. They can be killed without any consideration during scale down and they don't cause scale up. Pods with null priority (PodPriority disabled) are non expendable | 0

# Discussion on action to take
- Should we do nothing? It would cause activation of pod-priority to evict old pods with the previous priorirty
- Should we make a special case for GKE's CA?
- Should we ask users to configure the CA with a non-default value?

# How?
What kind of values.yaml options should we support for the configurability of priority?

**Comment by minrk** [comment]
Let's investigate other providers. If they, too, have a negative cutoff let's take the GKE behavior as an assumed best practice, and we can get rid of our default priority.

**Comment by minrk** [comment]
If they don't, let's keep doing what we are doing, since overriding autoscaler options is usually not an option available to managed kubernetes users, and keep an eye on a change in the future that would let us simplify.
