### ISSUE TITLE
Certificate experied, had to restart autohttps pod

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#1033]
Apparently a certificate expired on a JupyterHub with letsencrypt setup and a kube-lego container running in the autohttps pod. It had been running for 80 days. I restarted it (before reading logs doh!) and read logs after startup that it noticed an old certificate and made an successful update.

We don't want to require the autohttps pod to be restarted manually =/ I have started using cert-manager for all other tasks right now and that has been working great so far.

### Related
#755 #475

**Comment by betatim** [comment]
Which version of kube-lego is your chart using? Is it before or after  #963 was fixed?

**Comment by consideRatio** [comment]
Before thanks @betatim =)
