### ISSUE TITLE
Prefer versions instead of git hash for docker image tag

### ISSUE THREAD

**Issue by porterde** [jupyterhub/zero-to-jupyterhub-k8s#1038]
Similar to jupyter/docker-stacks#742, it would be helpful if images in docker.io (jupyterhub/k8s-hub, jupyterhub/k8s-image-awaiter, jupyterhub/k8s-network-tools etc) could be tagged with a semantic version instead of / as well as git hash.

For example, the current tags for the hub image are https://hub.docker.com/r/jupyterhub/k8s-hub/tags/. If v0.6 is rebuilt with a change to base image to address a vulnerability it is not easy to work out which is the latest image that is an update to v0.6.

**Comment by minrk** [comment]
Every released version of an image has a versioned tag. All those with hashes are necessarily unreleased versions. If v0.6 gets a new release to address a security vulnerability, all associated images will have associated versioned tags.

**Comment by consideRatio** [comment]
We have improved, our tags look great now I think, here is one image as an example.

```
jupyterhub/k8s-hub:0.9.0-n226.h47f3da5c
```
