### ISSUE TITLE
CI: utilization of helm diff

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#1041]
## CI experience vision
Helm charts render yaml files based on templates given input values. I'd love to see us utilize the [helm diff plugin](https://github.com/databus23/helm-diff) to give us a report on the changes somehow.

**Comment by manics** [comment]
Are you thinking something along the lines of:
1. helm install <last release of z2jh> and/or <latest z2jh git>
2. helm diff upgrade ./current against (1)?
Should be doable in travis, but not sure how best to get the diff output somewhere visible.

**Comment by consideRatio** [comment]
Not sure how we would make use of `helm diff` constructively in the CI system, so I'll go ahead and close this.

**Comment by consideRatio** [comment]
Oh hmmm, perhaps like a bot that updated a comment in a PR with a diff following commits or similar. I'm not sure. Ah, well closing! Not important enough.
