### ISSUE TITLE
Feature: prePulling singleuser.initContainers

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#1046]
We should prePull `singleuser.initContainers` as well.

This is where we should do it:
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/f202306ad49e3883fc55ab89cdb41f64b87c8c86/jupyterhub/templates/image-puller/_daemonset-helper.yaml#L55-L89

**Comment by yuvipanda** [comment]
yes we should!
