### ISSUE TITLE
Pending spawn

### ISSUE THREAD

**Issue by dalonlobo** [jupyterhub/zero-to-jupyterhub-k8s#1047]
Hi Team,

I'm facing an issue with starting the server. Sometimes starting the server takes a very long time.

Following are the logs from the hub:
![image](https://user-images.githubusercontent.com/12654849/49422937-ae4c9680-f7bb-11e8-8e93-076f0080b816.png)

After a few tries it throws the following error, at which point the webpage displays 500 error:
![image](https://user-images.githubusercontent.com/12654849/49422986-db00ae00-f7bb-11e8-95d8-49606b5c5be7.png)

Thank you for your help in advance.

**Comment by consideRatio** [comment]
@dalonlobo to debug this, id like to see two parts:

1. the `kubectl describe pod -n yournamespace yourpodname` and the output in the end under Events:
2. if the pod started running, it is also relevant to see the output of the `logs` rather than `describe` command above.

**Comment by dalonlobo** [comment]
@consideRatio The pod does not start at all. This setup is on AKS, not sure if the azure kubernetes is stable.

**Comment by dalonlobo** [comment]
Can I get anyother logs?

**Comment by dalonlobo** [comment]
Getting the following error:

I changed '-l' flag to '-t', since it was throwing ' unknown shorthand flag: 'l' in -l'

![image](https://user-images.githubusercontent.com/12654849/49461165-12517800-f819-11e8-860b-c99a27bd68e0.png)

**Comment by consideRatio** [comment]
Ah do the following then
```
kubectl exec pod <podname> -n <yournamespace> -- /bin/bash
```

**Comment by dalonlobo** [comment]
Sorry for delayed response, there is an error:

![image](https://user-images.githubusercontent.com/12654849/49491600-e1099400-f87a-11e8-9ec8-f4d5a9e931c9.png)

Thats the hub pod name which I gave, it exists and running.

**Comment by consideRatio** [comment]
then it should be:
```
kubectl exec <podname> -n <yournamespace> -- /bin/bash
```

Doing things out of my head is weak, you could try use the `--help` flag to help me correct my mistakes

**Comment by dalonlobo** [comment]
Closing this issue for now. After upgrading the kubernetes cluster version to 1.11.5 on AKS, I don't notice this issue. Thanks @consideRatio for your help

**Comment by dalonlobo** [comment]
Closing this issue for now. After upgrading the kubernetes cluster version to 1.11.5 on AKS, I don't notice this issue. Thanks @consideRatio for your help

**Comment by dalonlobo** [comment]
Still this issue is not solved with latest version of AKS. This could be due to network issue within the cluster.

**Comment by 01100010011001010110010101110000** [comment]
I'm experiencing this on 1.11.5 on AKS as well. My symptoms are the same, it's intermittent and force restarting the hub pod resolves the issue temporarily

**Comment by consideRatio** [comment]
I'd like to confirm - is the pod never showing up at all when a slow spawn is happening?

```
kubectl get pods -n YOURNAMESPACEHERE
```

**Comment by 01100010011001010110010101110000** [comment]
@consideRatio that is correct, it never appears at all. I ran into this with someone who had never logged into the hub, then a few minutes later it worked fine for a different user who had also never logged into the hub. I had made no changes, had not restarted the hub, etc. 

I am using OAuth2 against AAD for authentication, which may or may not be relevant, since both @dalonlobo  and I are running on AKS, and I assume he would be using the same auth method.

**Comment by consideRatio** [comment]
I would assume then tha the request by kubespawner to AKS kubernetes api-server fails sometimes. This would if so be a concern mainly for AKS, but kubespawner could perhaps be made to retry requests... Hmmm

**Comment by consideRatio** [comment]
It would be interesting to see the logs of the k8s api server if possible on AKS (its not on GKE for example).

It would also be interesting to see if a pod that does various request to the API server, one every second, tend to fail from time to time.

**Comment by 01100010011001010110010101110000** [comment]
It is possible in AKS, but I only enabled it just now. When this happens again I'll pull the logs

**Comment by dkipping** [comment]
Watching this, since we are experiencing the same issue.

Kubernetes Version: 1.11.3
Helm chart version 0.7.0

Already had that issue with people signing on for the first time I think, but mostly with people who already had signed on before (existing users).

I do not know if that might have something to do with it, but after (re)starting the hub, when getting the jupyterhub logs (via `jupyterhub` command) from the hub pod, I am getting a:
```
[E 2019-01-15 17:31:50.995 JupyterHub app:1220] Error adding user xyz already in db
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/app.py", line 1218, in init_users
        await maybe_future(self.authenticator.add_user(user))
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/auth.py", line 525, in add_user
        raise KeyError("User %s does not exist." % user.name)
    KeyError: 'User xyz does not exist.'
```
for every existing user, finally followed by:
```
[E 2019-01-15 17:31:51.054 JupyterHub app:1853] Failed to bind hub to http://127.0.0.1:8081/hub/
[E 2019-01-15 17:31:51.054 JupyterHub app:1952]
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/app.py", line 1950, in launch_instance_async
        await self.start()
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/app.py", line 1848, in start
        self.http_server.listen(port, address=ip)
      File "/usr/local/lib/python3.6/dist-packages/tornado/tcpserver.py", line 143, in listen
        sockets = bind_sockets(port, address=address)
      File "/usr/local/lib/python3.6/dist-packages/tornado/netutil.py", line 168, in bind_sockets
        sock.bind(sockaddr)
    OSError: [Errno 98] Address already in use
```

Might be, that at least the last portion is indicating problems in setting up the connection properly. (Might also just be the proxy before killing the old existing proxy and replacing it with the new one.)

**Comment by dalonlobo** [comment]
> 
> 
> @consideRatio that is correct, it never appears at all. I ran into this with someone who had never logged into the hub, then a few minutes later it worked fine for a different user who had also never logged into the hub. I had made no changes, had not restarted the hub, etc.
> 
> I am using OAuth2 against AAD for authentication, which may or may not be relevant, since both @dalonlobo and I are running on AKS, and I assume he would be using the same auth method.

Hi @01100010011001010110010101110000, I'm using firstuseauthenticator
https://github.com/jupyterhub/firstuseauthenticator

**Comment by 01100010011001010110010101110000** [comment]
@consideRatio It seems when this happens to a user they're unable to get a notebook pod spawned until we bounce the hub pod. In `kubectl get events` in the namespace, I don't see an attempt to spawn the missing user pod.

I've emailed you a link to the api server logs. I'm also not seeing events for the missing user pod in there, but that's just me grepping for their username.

**Comment by consideRatio** [comment]
I'm closing this as I know there have been improvements to make KubeSpawner more reliable, which has been important especially on AKS. These improvements are now part of the Helm chart, if you use a very very new version, such as `0.9.0-n311.ha2c3ef80` (WARNING: 0.9.1 is older, its weird I know).
