### ISSUE TITLE
Latest changelog for "alex blackwell" doesn't have any feature list

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/zero-to-jupyterhub-k8s#1052]
I was just looking through the [latest changelog for z2jh](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/CHANGELOG.md#070---alex-blackwell---2018-09-03) and realized that it has no features in it, only instructions for upgrading the cluster. Is there another place that we've put lists of new features for the release?

**Comment by minrk** [comment]
I swear I remember writing and reviewing changelog entries, but I can't find them. That's not good. I'll make sure they are added for 0.7 while we are doing the 0.8 notes.

**Comment by consideRatio** [comment]
Most of the work was actually related to stability if i recall correctly.

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/838#issuecomment-413537256

**Comment by consideRatio** [comment]
I figure we write summaries of features manually given the PRs we have merged.
