### ISSUE TITLE
Releasing 0.8

### ISSUE THREAD

**Issue by minrk** [jupyterhub/zero-to-jupyterhub-k8s#1054]
It's time to start getting ready to release v0.8 of the chart. Most of the new functionality is tested and working well in various deployments, including mybinder.org, so it's time to be making a release.

The main thing in 0.8 is the new scheduling-related work, including the user-scheduler and user-placeholders. This needs lots of new documentation to be written before we can make a release.

Things to do:

- [x] document the new scheduling options (#503, being closed by: #1074)
- [x] fill out the changelog
- [x] make sure other new features and changes are documented
- [x] run upgrade tests from 0.7 (@choldgraf made tests with Helm 2.11 and 2.12 and the result were :tada:) #1140

edit from @choldgraf:

- [x] Wait for feedback from the v0.8-beta.1 and
- [x] Release the stable v0.8

**Comment by consideRatio** [comment]
I'd like to see a transition to JupyterLab as default for 0.8 as well - thoughts on this?

I'll create a PR.

**Comment by choldgraf** [comment]
Just a note that we are almost done with the milestone issues for this one! All that is left is updating the changelog + making sure new features are documented.

What are the new features that we need to check if they're documented or not?

Wooo 0.8!

**Comment by consideRatio** [comment]
## Our docs on how to make a release
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/CONTRIBUTING.md#releasing-a-new-version-of-the-helm-chart

**Comment by jspc** [comment]
Hi @minrk, @consideRatio, can I help in anyway to get this over the line and out?

**Comment by choldgraf** [comment]
@consideRatio I can help with this this week as well, @jspc would you like to try the upgrade steps above and I can work on something else, maybe finalizing the changelog?

**Comment by consideRatio** [comment]
Have we documented new features and stuff? A lot the autoscaling aspects resides in: https://z2jh.jupyter.org/en/latest/optimization.html

- User Scheduler
- User Placeholders
- Pod Priority
- matchNodePurpose

**Comment by choldgraf** [comment]
Another friendly ping that it'd be really helpful if people could help fill out the changelog that I've started here! https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1114

**Comment by minrk** [comment]
working on the changelog today. Let's do 0.8b1 tomorrow and final next week or so if it goes smoothly.

@consideRatio I think the autoscaling and scheduler docs are well covered now. I'll look through for other new things that need updating.

**Comment by choldgraf** [comment]
@minrk +1 to that!

**Comment by minrk** [comment]
Beta published: `0.8.0-beta.1`

**Comment by minrk** [comment]
I have to run, but if folks in a further-west timezone want to advertise the beta, we can get some testing done over the next week

Reminder to add to the docs for release process: `0.8.0b1` is not a valid version according to helm, must use `-beta.1`.

**Comment by choldgraf** [comment]
cc @jhamman who was interested in v0.8 - It'd be great if you could give this a whirl Joe!

**Comment by minrk** [comment]
I think we're all set and can make 0.8 final now. Shall we 🚢  it?

**Comment by choldgraf** [comment]
+1 from me! what's on the to-do list for releasing a stable version?

**Comment by minrk** [comment]
> what's on the to-do list for releasing a stable version?

Last step:

- update version in install commands in docs from 0.8.0-beta.1 to 0.8.0
- Create the tag and push:

      chartpress --tag 0.8.0 --push
- Commit and tag in git

Publishing now...

**Comment by minrk** [comment]
0.8 is published. 🎉
