### ISSUE TITLE
CI improvement - multiple configs

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#1060]
It could make sense to have multiple helm chart value configurations running. We currently only the `minikube-config.yaml` set of values, but I think it could make sense to override this with additional changes so we test our configuration more thoroughly.

If A is strictly bigger than B, we test A. But sometimes you have that A and B cover different ground, then we would want to have a config for both A and B.

**Comment by manics** [comment]
I started it in https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1053 😃. In https://github.com/jupyterhub/zero-to-jupyterhub-k8s/tree/8f6c2a20e409494562a4d6a003031185ee04372f/ci there are three minikube environment files:
- minikube-1.9.4.env
- minikube-1.10.0.env
- minikube-1.12.3.env

The suffixes correspond to the [`env.matrix` in `.travis.yml`](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/8f6c2a20e409494562a4d6a003031185ee04372f/.travis.yml#L16).

Currently `minikube-1.9.4.env` and `minikube-1.10.0.env` have the same effect as before #1053. `minikube-1.12.3.env` uses different/additional environment values to enable calico for network policies in minikube, and to pass an additional helm config file to configure network policies in Z2JH:

[`minikube-1.10.0.env`](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/8f6c2a20e409494562a4d6a003031185ee04372f/ci/minikube-1.10.0.env):
```
export MINIKUBE_VERSION=0.30.0
export HELM_VERSION=2.9.1
export KUBEVAL_VERSION=0.7.1
export PATH="$PWD/bin:$PATH"
export MINIKUBE_ARGS="--vm-driver=none --kubernetes-version=v${KUBE_VERSION}"
export Z2JH_HELM_ARGS="-f minikube-config.yaml"
export DISABLE_TEST_NETPOL=1
```
[`minikube-1.12.3.env`](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/8f6c2a20e409494562a4d6a003031185ee04372f/ci/minikube-1.12.3.env):
```
export MINIKUBE_VERSION=0.30.0
export HELM_VERSION=2.9.1
export KUBEVAL_VERSION=0.7.1
export PATH="$PWD/bin:$PATH"
export MINIKUBE_ARGS="--vm-driver=none --kubernetes-version v$KUBE_VERSION --network-plugin cni --extra-config=kubelet.network-plugin=cni"
export INSTALL_CALICO=1
export Z2JH_HELM_ARGS="-f minikube-config.yaml -f minikube-netpol.yaml"
```

I think it would make sense to rename the suffixes to something other than versions when you start adding more test scenarios, but I left that out of my PR to reduce the number of changes.
