### ISSUE TITLE
Creation of GKE production ready k8s clusters

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#1069]
For to-be production clusters, I would recommend some settings that cannot be changed at a later time during cluster creation. Sadly GKE has not made their CLI mirror their Web UI so well sadly, and some things cannot be done with the CLI afaik.

1. One can only make a regional GKE cluster as recommended practice (with three master servers) with only one zone in active use (chosen in advanced section). This is not vital, its only nice to avoid downtime of the kubernetes-api during random times when they make updates without notice.
  ![image](https://user-images.githubusercontent.com/3837114/50048596-c8964680-00d0-11e9-939d-69d159a9905f.png)
  **In the advanced section:**
  ![image](https://user-images.githubusercontent.com/3837114/50048589-a7cdf100-00d0-11e9-8d0d-be35d80778b8.png)

1. Having ip-alias enabled is recommended and has no drawback afaik.
  ![image](https://user-images.githubusercontent.com/3837114/50048612-317dbe80-00d1-11e9-89d2-063dbd8ca787.png)

Anyhow, I'm struggling with what we should suggest in the docs regarding this. Complicate things for us and z2jh-guide readers, or leave this out and risk the group users, like me, that perhaps care too much these details me ending up disappointed at some later stage?

I think a reasonable solution is to convey:
- for to-be production clusters, do this in the console
- regional clusteres are good, disable certain zones
- ip-alias is good

**Comment by yuvipanda** [comment]
I think we should make a new page with this, and not put this in the default startup. VPC-Native will become the default soon enough, and it doesn't affect most users. I agree regional masters is an easy win.

However, for a 'real' production use case, I'd argue there are more things that you should consider anyway:

1. Using shared storage (best for most use long term cases, I'd say) vs individual disks as the default
2. Some kinda monitoring
3. Reserve your public IP address so it doesn't change

There are probably a bunch more that you might or might not want (like networkpolicy, staging clusters, hubploy, etc). I think we should have a separate page that explains and lists these things instead.

**Comment by yuvipanda** [comment]
I think creating a label for the default node-pool also comes under this category, since we don't have to explain node-pools when creating the original cluster, and so we shouldn't. Node pool labels are only useful when you have multiple node pools + autoscaling.

**Comment by consideRatio** [comment]
![giphy](https://user-images.githubusercontent.com/3837114/50057750-2e391000-016f-11e9-81db-d2bc6e272620.gif)

It is so nice to have a clear path instead of doubt what to do ;D This is the best choice, I agree!

**Comment by consideRatio** [comment]
To maintain this kind of configuration details is a bit too much work, at least without locking in too tight in a cloud provider. Closing.

**Comment by yuvipanda** [comment]
https://github.com/2i2c-org/pilot-hubs/tree/master/terraform I've this, might be useful for folks :)
