### ISSUE TITLE
profileList only mentioned in the configuration reference (schema.yaml)

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#1085]
We should add some narrative surrounding the use of profileList in the documentation, and perhaps not only have it in the reference section without mentioning it anywhere else.

(Idea by @yuvipanda, and I'm writing it down as an issue to not loose track of it)

**Comment by maxious** [comment]
Specifically as a first time user, I would expect to see this mentioned in https://zero-to-jupyterhub.readthedocs.io/en/latest/user-environment.html#choose-and-use-an-existing-docker-image that you can now have multiple images (but I'm sure knowing even more about the power of profileList elsewhere would be good!)

**Comment by choldgraf** [comment]
I started working on this, but then ran into this (I think) bug:

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1097

IMO we should try to use the passthrough config with this, though if we can't figure out that bug then perhaps I should just use the `extraConfig` approach?
