### ISSUE TITLE
config flag to jupyterhub helm points to a non-existant config file

### ISSUE THREAD

**Issue by ev1lm0nk3y** [jupyterhub/zero-to-jupyterhub-k8s#1088]
When using the default jupyterhub helm chart, it looks like the `--config` flag is hard coded to `/srv/jupyterhub_config.py` which isn't provided by default. All of my configuration options are set in a configMap in my gke cluster, but none of them seem to be getting loaded. All I see being loaded are the default options.

Do I need to provide, into my custom built jupyterhub container, a custom `jupyterhub_config.py` file which has all the config options I want? If so, what's the point of configuring them via the `config.yaml` file passed to helm?

## Contents of `config.yaml`
```
auth:
  state:
    enabled: true
    cryptoKey: ''
  type: google
  google:
    clientId: ''
    clientSecret: ''
    callbackUrl: https://custom.domain.com/hub/oauth_callback
    hostedDomain: domain.com
    loginService: "Jupyterhub"
  admin:
    users:
      - "me@domain.com"

singleuser:
  image:
    name: [custom repo image]
    tag: latest
  defaultUrl: "/lab"
  lifecycleHooks:
    postStart:
      exec:
        command:
          - "gitpuller"
          - "https://github.com/domain.com/repo"
          - "master"
          - "work"
  memory:
    guarantee: 2G
    limit: 8G
  cpu:
    guarantee: 2
    limit: 4
  storage:
    capacity: 24Gi
    extraVolumes:
      - name: ssh-key
        secret:
          secretName: ssh-key
      - name: github-token
        secret:
          secretName: github-token
    extraVolumeMounts:
      - mountPath: /home/jovyan/.ssh
        name: ssh-key
      - mountPath: /home/jovyan/.config/github
        name: github-token

hub:
  image:
    name: [custom repo image]
    tag: latest
  publicUrl: https://custom.domain.com
  extraConfig: |-
    c.JupyterHub.authenticator_class = GoogleOAuthenticator

proxy:
  secretToken: ''
  https:
    hosts:
      - custom.domain.com
    letsencrypt:
      contactEmail: team@domain.com

debug:
  enabled: true
```

Contents of custom hub docker image:
```
FROM jupyterhub/jupyterhub

RUN apt-get update && apt-get upgrade -yq && apt-get clean -y

RUN pip install --upgrade \
  oauthenticator \
  pip
```

**Comment by consideRatio** [comment]
We are mounting the config through the Helm chart in order to not rebuild the hub image every time we make a small change to the config. So, perhaps you ended up with a version of the image where it was removed, but not the version of the helm chart where it becomes mounted?

Closing as outdated.
