### ISSUE TITLE
Stagger image pulls?

### ISSUE THREAD

**Issue by vilhelmen** [jupyterhub/zero-to-jupyterhub-k8s#1089]
Hey everyone, is it currently possible to stagger image pulls by the awaiter? it seems that when all our cluster nodes try to pull all our images at once we DDoS ourselves. The ability to stagger pulls to x nodes at a time might be useful, but I'm not sure of the potential complexity behind it, I'm still very bad at k8s.

**Comment by consideRatio** [comment]
Ah to throttle the pulling, hmmm, not a quick and easy way as far as I can tell. Thanks for raising the question @vilhelmen !

**Comment by consideRatio** [comment]
I'm not aware of an easy resolution for this =/
