### ISSUE TITLE
Complete section on customizing environment of users & resources available to them.

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/zero-to-jupyterhub-k8s#109]
This is currently the `extending-jupyterhub.rst`, which we should split up and re-format.

Following ToC (adapted from #67):
- [x] User environment
  - [x] Using an existing docker image
  - [x] Creating a new image (repo2docker)
  - [x] Setting environment variables
- [x] User resources
  - [x] Memory limits & guarantees
  - [x] CPU limits & guarantees
  - [x] Storage
    - [x] Enabling & disabling
    - [x] Changing size available
    - [x] SSD vs HDD

**Comment by choldgraf** [comment]
we've now got an extensive section on user storage, so closing this! http://zero-to-jupyterhub.readthedocs.io/en/latest/user-storage.html
