### ISSUE TITLE
Pull Images on Schedule

### ISSUE THREAD

**Issue by vilhelmen** [jupyterhub/zero-to-jupyterhub-k8s#1091]
How feasible would it be to add the ability to have the image puller run on a schedule? The later singleuser images can get pretty large, and if containers are being built in a pipeline or just updated frequently, it could be useful to have them update automatically instead of waiting and holding up a user spawn.

**Comment by consideRatio** [comment]
@vilhelmen hmmm, the image pullers will pull instantly when they have information about a new image. With some new features added already but only available in 0.8-development releases so far you can accomplish a situation where the users never needs to wait for an image to be pulled.

- the hook image puller, will pull images before the hub is upgraded to let new users utilize the new image
- the continuous image puller will pull images instantly when new nodes are added, combined with user-placeholders and pod priority, new nodes can be added before they are needed, allowing the image pullers the time needed to pull images to the new nodes that were added by an cluster autoscaler.

See #1074 for documentation about user-placeholders etc, this is available in the 0.8-development releases.

**Comment by yuvipanda** [comment]
IMO, you should use explicit tags for each image you are building. This means you have to let the hub know which specific image you wanna use, and that requires a `helm upgrade` - which will also pull in the images you seek. Scheduling pulls only works if you're not using explicit tags for each build, and that isn't something we recommend doing...

**Comment by vilhelmen** [comment]
That's fair, I was mostly looking to get it working for a dev server. I still haven't pinned down why our progress bar stopped working (#1090), and this would have helped a little.
