### ISSUE TITLE
Links in search results are broken

### ISSUE THREAD

**Issue by cbjuan** [jupyterhub/zero-to-jupyterhub-k8s#1093]
While searching using the sphinx docs, the links shown in the results many times are broken. I reviewed similar issues in GitHub, but I didn't find a clear solution:
* https://github.com/rtfd/readthedocs.org/issues/2708
* https://github.com/sphinx-doc/sphinx/issues/3203
* https://github.com/sphinx-doc/sphinx/issues/4929
* https://github.com/reahl/reahl/issues/146 

Might it be a solved by re-compiling the docs again and submitting the new ones to readthedocs?

**Comment by cbjuan** [comment]
An example:

If I search for `https` in https://zero-to-jupyterhub.readthedocs.io/en/stable/index.html I obtain these results: https://zero-to-jupyterhub.readthedocs.io/en/stable/search.html?q=https&check_keywords=yes&area=default 

If I click on the result ([CHANGELOG](https://zero-to-jupyterhub.readthedocs.io/en/stable/CHANGELOG.html?highlight=https)), it raises the following 404 error:
![screen shot 2019-01-04 at 18 35 22](https://user-images.githubusercontent.com/2938045/50701915-89b03c80-104f-11e9-90ec-09e687f5134f.png)

**Comment by consideRatio** [comment]
Oh, hmmm i fixed a lot of broken links but they are only fixed in latest rather than stable.

**Comment by cbjuan** [comment]
ok! I will try again in [latest](https://zero-to-jupyterhub.readthedocs.io/en/latest/index.html)

**Comment by cbjuan** [comment]
Working as expected in latest. Closing this issue.

**Comment by consideRatio** [comment]
Thanks for the followup and for investigating this @cbjuan !
