### ISSUE TITLE
Update documentation with link to Helm chart dependencies mapping

### ISSUE THREAD

**Issue by ablekh** [jupyterhub/zero-to-jupyterhub-k8s#1094]
I think that it would be beneficial to include in _Z2JH documentation_ a link to a **mapping table**, indicating which versions/releases of JupyterHub Helm chart’s components - such as JupyterHub application per se - correspond to which versions/releases of the Helm chart. The mapping table itself should likely belong to _Z2JH Helm chart documentation_ (since it is a separate repo, I assume that it has a separate documentation).

**Comment by consideRatio** [comment]
The helm chart is published in a separate repo, but this is where it is developed.

Perhaps we could have this in the README even?

**Comment by ablekh** [comment]
@consideRatio I think that the optimal setup would be to have the mapping table in the chart repo's README (as you suggested) and/or the chart's documentation, if any, **plus** a mention and a link to that info in Z2JH documentation.

**Comment by choldgraf** [comment]
Just a note that I opened up https://github.com/jupyterhub/helm-chart/pull/94 to add a list of jupyterhub versions to that README. Would that be enough?

**Comment by ablekh** [comment]
@choldgraf Great first step, thank you! As I've said earlier, I think that versioning should be documented in **both** Z2JH and Helm chart projects: with a mapping table in the former **and** a relevant link (with a very brief explanatory text) in the latter.

**Comment by choldgraf** [comment]
@ablekh I believe this was hammered out in #1106 and also here: https://github.com/jupyterhub/helm-chart#versions-coupled-to-each-chart-release

what do you think? is this issue resolved? :-)

**Comment by ablekh** [comment]
@choldgraf Looks good to me. Thank you for making it a reality. One thing that I would add, though, is a column for versions of JupyterLab since it is bundled with JupyterHub and Z2JH chart. And I would remove "v." from column titles as IMO it's redundant. :-)

**Comment by choldgraf** [comment]
sounds good - and thanks for the tip! I'm gonna close this issue since I think the original problem is now resolved, though please feel free to open another to discuss making the table a bit better!
