### ISSUE TITLE
Add a "howto" section with short, actionable pages

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/zero-to-jupyterhub-k8s#1096]
The TLJH documentation has a [howto section](http://tljh.jupyter.org/en/latest/#how-to-guides) that has proven quite useful for getting people to find answers to their questions. I think we should add a section like this to z2jh, and pull out some of the more concrete and bite-sized pieces of information into howto pages in z2jh. This might also make it easier for people to see how they can add new things to the documentation (e.g. "how to set up a shared folder for all users on a JupyterHub").

How do folks feel about this?

**Comment by consideRatio** [comment]
I like anything that makes it more useful while not breaking the DRY principle too much.

**Comment by minrk** [comment]
I think it sounds great. I wouldn't worry too much about DRY in docs, as good documentation often repeats itself as the same information may show up as part of the answer to a variety of different questions. There are also FAQ/tutorial/reference ways of presenting the same information, all of which can be valid and useful depending on reader goals.

**Comment by consideRatio** [comment]
I'd like to see concrete suggestions of items to have in the howto section to make this issue more concrete. Ideas?

Let's close this issue if no new ideas have surfaced after a while.

**Comment by choldgraf** [comment]
let's close it :-)
