### ISSUE TITLE
Document how to manage the users on an existing jupyterhub

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/zero-to-jupyterhub-k8s#11]
E.g., information about how to list the people currently using the jupyterhub , resources being used, etc

**Comment by yuvipanda** [comment]
I think we should close this in favor of something more concretely actionable. As is, I'm unsure if this talks about the JupyterHub admin panel, something like prometheus/grafana or what not.

**Comment by willingc** [comment]
Closing this issue. Feel free to open a new issue if needed.
