### ISSUE TITLE
Enabling man pages in container

### ISSUE THREAD

**Issue by vilhelmen** [jupyterhub/zero-to-jupyterhub-k8s#1124]
Hey there, this is more of a note than anything, though I can wrap up a PR if it's of interest. It always bugged me that the containers lack man pages and I've dug through everything required to get it to work, including talking to the man-db maintainer about a problem with directory scanning.

Here's the short of it: Ubuntu blocks the man pages to save space, which is fair. What you need to do is remove this block and then reinstall **every package**. Conda is weird (shocker!), and the current version of man-db won't pickup all conda man pages properly, so you need to manually edit the manpath config file.

Since you have to reinstall **every**. **single**. **package**. it's best to do it before any more are installed. In our system, I've created a substrate layer that sits between the stock ubuntu and the base container which does this and adds a few other package (come on, we don't have less?!?). Here's what to do:

```dockerfile
# If it hasn't been set yet
ENV DEBIAN_FRONTEND noninteractive
USER root

RUN rm /etc/dpkg/dpkg.cfg.d/excludes \
	&& apt-get update \
    && dpkg -l | grep ^ii | cut -d' ' -f3 | xargs apt-get install -yq --no-install-recommends --reinstall man \
	&& apt-get clean \
	&& rm -rf /var/lib/apt/lists/*
```

Then, to fix the man path issues, you need to do the following:

```dockerfile
USER root

RUN echo "MANPATH_MAP ${CONDA_DIR}/bin ${CONDA_DIR}/man" >> /etc/manpath.config \
	&& echo "MANPATH_MAP ${CONDA_DIR}/bin ${CONDA_DIR}/share/man" >> /etc/manpath.config \
	&& mandb
```

Hope this helps!

**Comment by minrk** [comment]
This is likely belongs as a tip for configuring the user environment in building user images, and possibly as an issue on the jupyter/docker-stacks repo to improve the default situation

**Comment by vilhelmen** [comment]
Should said tip go in this repo's docs or docker-stacks? I'll open an issue to discuss enabling it there and get some info on how much extra disk space it takes.
