### ISSUE TITLE
Rename CI matrix versions

### ISSUE THREAD

**Issue by manics** [jupyterhub/zero-to-jupyterhub-k8s#1126]
Follow-up to https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1053

That PR added network-policy tests to one of the three K8s versions that were tested in the Travis matrix, but the variable name `KUBE_VERSION` was unchanged:
```
env:
  matrix:
    - KUBE_VERSION=1.12.3
    - KUBE_VERSION=1.10.0
    - KUBE_VERSION=1.9.4
```
Since `KUBE_VERSION` is now overloaded to mean K8s version + some other test factor(s) I think it'd be clearer to rename it:
- supported K8s versions may change https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1122 and a new maintainer may not realise some versions also included other tests
- other z2jh configuration tests will be added at in future: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1060

How about something like (using versions from https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1122)
```
env:
  matrix:
    - SCENARIO=1.13.2-netpol
    - SCENARIO=1.12.5-default
    - SCENARIO=1.11.7-default
```

**Comment by consideRatio** [comment]
Good point, I'll update #1122!

**Comment by manics** [comment]
I was thinking of leaving it for a cleanup after the release, but now is fine too 😀
