### ISSUE TITLE
Addition to 'Additional Resources' section - blog post and ansible play.

### ISSUE THREAD

**Issue by jmatuskey** [jupyterhub/zero-to-jupyterhub-k8s#1141]
Hello, we at Space Telescope Science Institute (STScI) created an Ansible playbook which automates everything for a basic JupyterHub setup on AWS. This tracks exactly with the instructions here in this fantastic project, the difference is that it is all automated.

We have an accompanying blog post: https://mast-labs.stsci.io/2019/02/zero-to-jupyterhub-with-ansible

Here is the repo: https://github.com/spacetelescope/z2jh-aws-ansible

**Comment by consideRatio** [comment]
Awesome @jmatuskey thanks for sharing this!! :D

Do we already have a "additional resource" section?

/erik from mobile

**Comment by jmatuskey** [comment]
yes there is - https://zero-to-jupyterhub.readthedocs.io/en/stable/additional-resources.html

i found it by going to the main page https://zero-to-jupyterhub.readthedocs.io/en/stable/ and at the bottom there's 'Community Resources' and in that list is 'Additional Resources'.

Is there a better spot for this blog post and project? What do you think?

**Comment by consideRatio** [comment]
:+1: Do you want to add a PR? I think this should be referenced there, and perhaps also be a note in the setup instructions of AWS clusters.

**Comment by minrk** [comment]
This is super great! Adding a link in Additional Resources sounds perfect.

**Comment by choldgraf** [comment]
see https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1181

I'm not sure it makes sense for that the "additional resources" page to separate repositories and blog posts, since many projects may have one or more of those. But I think that's a conversation for another issue :-)
