### ISSUE TITLE
Error while setting up Z2JH with K8s

### ISSUE THREAD

**Issue by KVSSetty** [jupyterhub/zero-to-jupyterhub-k8s#1147]
unable to install the chart configured by your config.yaml by running this command from the directory that contains your config.yaml:

# Suggested values: advanced users of Kubernetes and Helm should feel
# free to use different values.
RELEASE=jhub
NAMESPACE=jhub

helm upgrade --install $RELEASE jupyterhub/jupyterhub \
  --namespace $NAMESPACE  \
  --version=0.8.0-beta.1 \
  --values config.yaml

Error : 
Release "jhub" does not exist. Installing it now.
Error: render error in "jupyterhub/templates/proxy/autohttps/service.yaml": template: jupyterhub/templates/proxy/autohttps/service.yaml:1:26: executing "jupyterhub/templates/proxy/autohttps/service.yaml" at <.Values.proxy.https....>: can't evaluate field https in type interface {}

Any assistance appreciated

**Comment by consideRatio** [comment]
@KVSSetty can you provide us with your config.yaml file (where you obfuscate your secrets)?

**Comment by KVSSetty** [comment]
my config file contains nothing more than the random hex string representing 32 bytes to use as a security token generated using the command:
 openssl rand -hex 32 , as per the tutorial.
I tried by changing  the version of the Helm chart from 0.8.0 beta to just 0.8.0 and also to 0.7.0 ,but nothing works.

**Comment by consideRatio** [comment]
Can you copy paste it anyhow for me to better conclude details regarding to yaml-syntax?

If you paste it within a block like below, it will show up with spacing etc intact.

    ```yaml
    proxy:
      secretToken: asdfasdfasdf
    ```

**Comment by azbones** [comment]
I am having the same problem when running:

`helm upgrade --install jhub jupyterhub/jupyterhub\
  --namespace jhub\
  --version=0.8.2\
  --values config.yaml`

I get:
`@cloudshell:~ (googleaccountxxxxx)$ helm upgrade --install jhub jupyterhub/jupyterhub   --namespace jhub    --version=0.8.2   --values config.yaml
Release "jhub" does not exist. Installing it now.
Error: render error in "jupyterhub/templates/proxy/autohttps/service.yaml": template: jupyterhub/templates/proxy/autohttps/service.yaml:1:26: executing "jupyterhub/templates/proxy/autohttps/service.ya
ml" at <.Values.proxy.https....>: can't evaluate field https in type interface {}`

config.yaml is just the following as suggested in the z2jh guide:
proxy:
  secretToken: "<hex generated from openssl rand -hex 32>"

I am using Google Kubernetes Engine.  I also tried doing chmod on config.yaml, but same error. I am going to keep trying and will post if I figure it out, but I was following the z2jh recipe, so haven't gotten into the details yet. If anyone figures it out, I would appreciate it!

**Comment by consideRatio** [comment]
@azbones suspect a formatting error in your config.yaml.

```yaml
proxy:
  secretToken: "asdagj023jrlkadjfg92j3rnslkrt2as098asf09sd8gf09i"
```

**Comment by azbones** [comment]
This is the actual file. I changed the token though...

![image](https://user-images.githubusercontent.com/4975596/56827052-929d6780-6812-11e9-913e-79046723086b.png)

**Comment by azbones** [comment]
@consideRatio thanks for taking a look though! Everything was going great until this point. I appreciate all the support.

**Comment by azbones** [comment]
@consideRatio the lack of a space between secretToken: and the hex value seemed to be the problem. Thanks for the help!!

**Comment by consideRatio** [comment]
;D nice your welcome!
