### ISSUE TITLE
prerelease tags aren't sorted correctly

### ISSUE THREAD

**Issue by minrk** [jupyterhub/zero-to-jupyterhub-k8s#1154]
We currently create releases `0.8-abc123` for git commits. These correctly sort before *final* releases, but they do not sort before other prereleases, since `ffccb3` comes after `beta` in the alphabet. For this reason, `helm search` shows the latest prerelease, which finds an effectively random commit, rather than the latest beta.

`git describe --tags` gives output like:

    0.8.0b1-16-g56765dc

which means 16 commits since the last tag (0.8.0b1), current commit is `g56765dc`. 

We could use this to get more correctly sortable releases, e.g.

    `0.8.0-0.4.g56765dc` meaning commit `g56765dc` 4 commits after the last tag

- the leading 0 ensures sorting before alpha releases (or we could just use alpha, or get the first item, be it alpha/beta/etc. from the chart version)
- the 4 ensures commits occur in order
- using dots to separate ensures sorting categorically (i.e. commit is never compared directly to another commit, since the number before the commit is already unique)
- including the commit ensures the same information is preserved as before

The implementation of this really belongs in chartpress. But it does have some strategy implications that are mostly relevant here. e.g. do we care abort ordering commits? Or is the leading 0 forcing sort before betas enough?

**Comment by consideRatio** [comment]
This is fixed!
