### ISSUE TITLE
HTTPS Letsencrypt: Kubernetes Ingress Controller Fake Certificate 

### ISSUE THREAD

**Issue by frouzbeh** [jupyterhub/zero-to-jupyterhub-k8s#1157]
I'm trying to deploy JupyterHub on a private Kubernetes cluster and want to setup the automatic HTTPS using letsencrypt. Based on the documents, I just need to provide host and email address, but everytime I try the url I'm getting this:

```
Your connection is not private
Attackers might be trying to steal your information from <my-domain> (for example, passwords, messages, or credit cards). Learn more

NET::ERR_CERT_AUTHORITY_INVALID
Subject: Kubernetes Ingress Controller Fake Certificate

Issuer: Kubernetes Ingress Controller Fake Certificate

Expires on: Feb 19, 2020

Current date: Feb 19, 2019

PEM encoded chain:
-----BEGIN CERTIFICATE-----
......
-----END CERTIFICATE-----
```

What does it mean?
Any help is appreciated. 
Thanks,

**Comment by consideRatio** [comment]
Some confirming questions first: 
1. Where do you see this?
2. Is this a "private Google Kubernetes Engine (GKE) cluster"?

I guess that the certificate has not been setup as it should, because you have not yet setup a NAT, which is actually very easy to do on Google cloud platform. Just search in GCP for NAT and click some buttons and what you do is probably ending up being the right thing. You need to create some "Cloud Router" along the way and that is as it should be.

Only with Network Address Translation, NAT, can you do outbound traffic. It relates to the IP addresses in use, what IP should the private cluster contact something outside on the internet with. If something is sent back to the IP, how should that packet being sent back find its way back to your specific pod and container? You need a Network Address Translation step along the way to manage this is my understanding.

**Comment by frouzbeh** [comment]
@consideRatio Thanks, It's on Bare metal cluster, and I have public IP for my url. So do you still think I need NAT? I'm not very familiar with its detail though.

**Comment by consideRatio** [comment]
Ah @frouzbeh then I have a lot less insights about this than I hoped,

I figure it is possible to have ingress utilize an IP for incoming traffic, but that is no guarantee that you can do outbound traffic.

I think a good step is to ensure you have outbound connectivity to the internet from pods. For example, you could enter the `hub` pod.

```sh
# written from memory, may certainly contain errors
kubectl exec -n <your-namespace> <hub-pod-name> -it -- bash
```

From within the hub pod, you could do `wget`, `curl` or `ping` commands depending on what is available to see if you can get a response from for example www.google.com.

If you cant, then you should focus on establishing outbound connectivity, perhaps using a NAT somehow, but I'm lacking the knowledge to guide you on how to do this.

Hopefully this could make you actionable towards a solution at least.

**Comment by frouzbeh** [comment]
@consideRatio Well, none of those commands are provided inside the hub pod, but I think it has outbound connectivity, because I can see the login page using the IP, but can't login because I'm using oauth and the call-back url is https again which still has problem.

Thanks for your help, I still hope to get some hints from others.

**Comment by frouzbeh** [comment]
@consideRatio I also see this error in autohttps pod's description:

Readiness probe failed: HTTP probe failed with statuscode: 500

**Comment by consideRatio** [comment]
@frouzbeh ah but the challenge can often be to establish connectivity. I understand it as that you can establish connectivity in one direction even though you cannot establish connectivity the other direction. So being able to communicate at all does not guarantee you can establish connectivity both ways.

And, the pods within the cluster needs to establish connectivity with letsencrypt, while when you access the pods through your ingress, you are establishing connectivity to your pods.

---

Even with the hint of the readiness probe failure I'm unable to figure out whats wrong fully, but I still think it can be an issue with the outbound connectivity.

If `wget` `curl` and `ping` was not installed on the hub pod, you could use `python` to do a webrequest I think. 

```
python -c "import requests; r = requests.get('https://www.google.com'); print(r.status_code); print(r.text)"
```

**Comment by frouzbeh** [comment]
@consideRatio I just understood what you're saying. In my case I guess firewall is the issue. We have very restricted firewall in our cluster, so the outbound traffics are limited.
Do you happen to know how I can have my own https certificate?

**Comment by manics** [comment]
> In my case I guess firewall is the issue. We have very restricted firewall in our cluster, so the outbound traffics are limited.

Does your firewall also restrict inbound traffic? Can you connect to `http://your.public.domain.name/` from outside your network? letsencrypt verifies you own the domain by making a request to `http://your.public.domain.name/<special-url>`

**Comment by frouzbeh** [comment]
@consideRatio I asked the cluster admin, lets see what are our options. Thanks

@manics inbound traffics are also restricted, it's through VPN. Apparently we need to get the certificate another way. Thanks

**Comment by frouzbeh** [comment]
I had to set the certificate manually because of the firewall. So I close this issue.
