### ISSUE TITLE
500: Failed to get username from CILogon

### ISSUE THREAD

**Issue by frouzbeh** [jupyterhub/zero-to-jupyterhub-k8s#1164]
I have been trying to use CILogon for authentication with Purdue identity, but I'm getting the following error in hub pod's log:

`Username claim eppn not found in the response: ['aud', 'iss', 'sub']`

I'm not very familiar with details, but I'm sure I don't want to use email as username. anyone can help me with this?

Thanks,

**Comment by frouzbeh** [comment]
Apparently, I forgot to choose the right scopes for CILogon. So I close the issue.

**Comment by stevenrbrandt** [comment]
@frouzbeh what does it mean to "set the right scopes for CILogon? I'm having the same issue you originally reported. Thanks.

**Comment by frouzbeh** [comment]
@stevenrbrandt [Here](https://www.cilogon.org/oidc) you can find about the scopes.

"JupyterHub users: If you are using the JupyterHub OAuthenticator plugin with CILogon, please request the following three (3) scopes: openid, email, and org.cilogon.userinfo."

Hope this helps.

**Comment by stevenrbrandt** [comment]
@frouzbeh what I can't find is how to do that.

I set this in my jupyterhub config, but it seems to do nothing:
```
c.CILogonOAuthenticator.scope = ['openid','email','profile','org.cilogon.userinfo']
```

**Comment by frouzbeh** [comment]
@stevenrbrandt I think you should do that when you register for CILogon. You can contact them to update your registration.

**Comment by stevenrbrandt** [comment]
@frouzbeh I see. Thanks!
