### ISSUE TITLE
SparkContext creation: java gateway process exited before sending its port number

### ISSUE THREAD

**Issue by frouzbeh** [jupyterhub/zero-to-jupyterhub-k8s#1174]
I have a Kubernetes cluster which is physically in the same cluster as my hadoop cluster. I want to deploy JupyterHub on the Kubernetes and then use the spark on the hadoop cluster. 
To make it local I set the network of the single users to the host. But when I'm trying to create a sparkcontext inside the JupyterLab I'm getting the following error:

`java gateway process exited before sending its port number
`
I don't know which environment variables need to be set. Any help is appreciated.

**Comment by consideRatio** [comment]
This is beyond my ability to help out with, and not really in scope for this github repository =/
