### ISSUE TITLE
sshpiper support

### ISSUE THREAD

**Issue by kfox1111** [jupyterhub/zero-to-jupyterhub-k8s#1177]
Feature request:

Integration with sshpiper would be awesome.
https://github.com/tg123/sshpiper

You could then ssh to your own pod/environment as a user.

**Comment by consideRatio** [comment]
Integration is a quite overloaded word, and I don't know what it would entail in this case. If there is some general function that is required of this project in order to work alongside another, then that specific point can be considered.
