### ISSUE TITLE
enable userScheduler by default

### ISSUE THREAD

**Issue by minrk** [jupyterhub/zero-to-jupyterhub-k8s#1182]
brought up in https://github.com/pangeo-data/helm-chart/issues/58#issuecomment-470268806, the userScheduler is disabled by default in 0.8 as a new experimental feature. That said, we've had such a good experience with it on mybinder.org, I think we should probably enable it by default in 0.9.

Are there reasons not to do this?

**Comment by consideRatio** [comment]
If you are running a fixed number of nodes, it is better to let the users spread out which they wont if it is enabled. But, I would rather have it enabled by default to encourage autoscaling :)

**Comment by consideRatio** [comment]
I also think we may want to make it "replicas: 2" or similar and remove the resources requests for CPU if there are any, to reduce the need to force-remove the lone pod if you want to make a cluster upgrade and need to drain a node etc.

**Comment by bitnik** [comment]
just to reference, this is done in https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1272
