### ISSUE TITLE
Error 400 OAuth state missing from cookies (Google auth)

### ISSUE THREAD

**Issue by abdidarmawan007** [jupyterhub/zero-to-jupyterhub-k8s#1195]
have error with jupyterhub kubernetes in gke use auth google

error :  

after login with email gmail

500 Internal Server Error

and on refresh

400 OAuth state missing from cookies

its haven if pod hub alredy have uptime for 5-7 days, 

i think this problem in container hub with oauth or cookies

**Comment by consideRatio** [comment]
Hi @abdidarmawan007 thanks for reporting this, i think it is a duplicate of #1102.

@joshbode have done excellent work to this issue in #1185 ;D Could you try the latest release and see if that resolve the issue? To do so add --version=0.9-8463734 to your `helm upgrade` command. I'd actually love to see some testing of this, could you report back if it works for you?

**Comment by consideRatio** [comment]
To verify it is a duplicate of #1102, I think you can inspect the logs of the hub pod in kubernetes and look for the error described in #1102 occurring at some point. I think this is what has caused what you are seeing at a later point, even though the symptoms are the same.

```
kubectl logs deploy/hub -n jhub
```

Btw, what version of the helm chart is installed?

**Comment by abdidarmawan007** [comment]
hi thanks for update and replay, 

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1102

**Comment by erniee** [comment]
I seem to still have this issue every 6 hours or so after restarting the hub.
I have upgraded to  --version=0.9-8463734.  BTW is there a way to verify that you are running that version?  
Helm version outputs

```
NAME    	REVISION	UPDATED                 	STATUS  	CHART           	APP VERSION	

pstat131	10      	Mon Apr  8 11:48:05 2019	DEPLOYED	jupyterhub-0.8.0	0.9.4      
```

**Comment by consideRatio** [comment]
> I have upgraded to --version=0.9-8463734. BTW is there a way to verify that you are running that version?

It seems like you are using jupyterhub-0.8.0 rather than the version you specified based on that `helm list` command. Hmmm...

**Comment by erniee** [comment]
Would I need to do an install vs. upgrade?

**Comment by erniee** [comment]
@consideRatio Sorry to waste your time.
I modified my config.yaml 
-    hostedDomain: "ucsb.edu"
+    hostedDomain: [ucsb.edu]
