### ISSUE TITLE
[Question] Sharing notebooks in Jupyterlab

### ISSUE THREAD

**Issue by emirot** [jupyterhub/zero-to-jupyterhub-k8s#1203]
Hi There,

I've deployed jupyterhub  into a k8s cluster in AWS.
However I'm not able to figure out how people can collaborate using jupyterlab ?
They have their own persistent volume so it's obviously not share. 
Is the best way for them to collaborate is to turn off this : https://zero-to-jupyterhub.readthedocs.io/en/latest/user-storage.html?highlight=persistent%20volume#turn-off-per-user-persistent-storage 

Or should I install an jupyterlab extension like github, if so how that is that possible ? 

Thanks

**Comment by manics** [comment]
If a shared directory is enough you could create a shared persistent volume: https://zero-to-jupyterhub.readthedocs.io/en/latest/user-storage.html#additional-storage-volumes. Note you'll have to create volume yourself before you update z2jh.

**Comment by consideRatio** [comment]
There is no easy answer to this, and it's a quite advanced topic, but I assume what's closest is to configure mount read/write storage for the users, but read/write storage for multiple users require certain kinds of storage, such as NFS. So you need a NFS server that you expose storage to as well.
