### ISSUE TITLE
Estimating costs calculator binder errors

### ISSUE THREAD

**Issue by mathieuboudreau** [jupyterhub/zero-to-jupyterhub-k8s#1205]
Clicking the "Launch cost calculator" in this link (https://zero-to-jupyterhub.readthedocs.io/en/stable/cost.html), MyBinder fails to build and errors:

<img width="1175" alt="Capture d’écran 2019-03-28 à 13 29 32" src="https://user-images.githubusercontent.com/1421029/55173193-376a4d80-515e-11e9-9a07-2faf1c48a5b1.png">

**Comment by consideRatio** [comment]
We deleted this because we failed to maintain it =/
