### ISSUE TITLE
development environment with kind

### ISSUE THREAD

**Issue by clkao** [jupyterhub/zero-to-jupyterhub-k8s#1206]
https://github.com/kubernetes-sigs/kind is a way to spawn a kubernetes cluster with docker as the only requirement, and is REALLY fast. it's good for development environment and CI for multiple versions of kubernetes, and is particular useful if you need to test with [local kubernetes changes](https://github.com/kubernetes-sigs/kind#installation-and-usage).  This should be more favourable than a minikube setup for most people, and should get documented.

so, I've managed get fresh z2jh running within 3 minutes:

```
%  kind create cluster --name z2jh
Creating cluster "z2jh" ...
 ✓ Ensuring node image (kindest/node:v1.13.4) 🖼
 ✓ Preparing nodes 📦 
 ✓ Creating kubeadm config 📜 
 ✓ Starting control-plane 🕹️ 
Cluster creation complete. You can now use the cluster with:

export KUBECONFIG="$(kind get kubeconfig-path --name="z2jh")"
kubectl cluster-info

% export KUBECONFIG="$(kind get kubeconfig-path --name="z2jh")"
kubectl cluster-info

Kubernetes master is running at https://localhost:63027
KubeDNS is running at https://localhost:63027/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy

% kubectl --namespace kube-system create sa tiller
% kubectl create clusterrolebinding tiller \
       --clusterrole cluster-admin \
       --serviceaccount=kube-system:tiller
% helm init --service-account tiller

% helm upgrade --wait --install --namespace=hub hub jupyterhub/ -f minikube-config.yaml 

% kubectl port-forward -n hub svc/proxy-public 8080:80
```

and viola, you've got z2jh running on localhost:8080

If you wish to use sqlite-pvc, install the local-path provisioner as the builtin host path provisioner doesn't set directory permission right:
```
kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/master/deploy/local-path-storage.yaml
```

and change minikube-config.yaml:

```
hub:
  db:
    type: sqlite-pvc
    pvc:
      storageClassName: local-path
```

For ingress (as I am testing keycloak auth which requires a proper domain name), I add the nginx-ingress:

```
helm install --namespace nginx-ingress -n nginx-ingress stable/nginx-ingress --set controller.hostNetwork=true
```

and edit minikube-config.yaml:

```
ingress:
  enabled: true
  hosts:
    - hub.127.0.0.1.xip.io
```

helm upgrade again, and `kubectl port-forward -n nginx-ingress svc/nginx-ingress-controller 8080:80` gets you a working `http://hub.127.0.0.1.xip.io:8080/`

**Comment by manics** [comment]
I've just (today!) been playing with https://k3s.io/ so far it's also been quite easy to setup.

**Comment by minrk** [comment]
This sounds awesome! We should definitely investigate using this for local dev and CI if it's lower overhead than minikube. k3s also sounds super cool, but requiring linux doesn't work for local development. Anyone want to take a stab at what our CI/local contributing docs would look like with kind?

**Comment by consideRatio** [comment]
@clkao :heart: :tada: :sunflower: !!! Thanks for documenting this!

Another point, we need to use `kind load docker-image <image name:tag>` on locally built images if access them as well.

**Comment by clkao** [comment]
@consideRatio do you have the recipe for loading locally built z2jh images into kind dev env? (with either/both jupyterhub and kubespawner changes)

**Comment by consideRatio** [comment]
In #1422 you can see a script in the `ci` folder that I created. It's not flawless yet, it inspects the locally available image using the tags in values.yaml, and loads those with kind load. Kind load fails if you try load something not locally available. I'm just about to debug why kind load crashed non stop without a good error message or something I realized was an issue when using `--loglevel trace` with the command. Until yesterday night everything has been ok with the script though.

**Comment by clkao** [comment]
hmm I wonder if there's a minikube-equivalent setup close to https://github.com/jupyterhub/kubespawner/blob/master/SETUP.md

This means jupyterhub/kubespawner is running on host:
- it talks to kubernetes api endpoint within kind (port-froward control-plane)
- the spawned user pods can talk to HUB_CONNECT_IP that is the host

**Comment by consideRatio** [comment]
hmmmm @clkao I'm struggling to understand many things, to the extent I fail to even formulate questions, but:

- $(minikube ip) seem to give you the IP of the VM that minikube starts up and boots the kubernetes cluster within: https://kubernetes.io/docs/setup/learning-environment/minikube/#networking
- With this IP at hand, and minikube being a single node cluster always, you have the single nodes IP, and can use that in combination with nodePort's to access in-cluster services etc.
- Is there an equivalent for kind? Can we port-forward to one of the kind nodes and get a response? Hmmm! Reading in the docs about `kubectl port-forward` i saw nothing about forwarding to a node, but only about to a pod (which could be indirectly found through a deployment or service).

**Comment by consideRatio** [comment]
We have went from minikube to kind (and a crappy script i made) to k3s. Thank you soo much @clkao for your work :heart:!
