### ISSUE TITLE
[Question] Jupyter Hub WITHOUT proxy

### ISSUE THREAD

**Issue by ramkrishnan8994** [jupyterhub/zero-to-jupyterhub-k8s#1207]
I'm using v0.7 of Jupyterhub.
There is a proxy pod that gets created with the 'configurable-http-proxy' image. 
Can we deploy Jupyterhub **without the** Proxy pod.

Our whole cluster is already secure and resides in a private network.
We also have a nginx ingress controller and kube-proxy running. If the chp pod is essential, is there anyway the existing components can be leveraged?

**Comment by consideRatio** [comment]
The proxy is essential, jupyterhub speaks with it specifically to make it route users to the correct user server or to the hub if they have not logged in for example.

While outside the scope of the z2jh repo, something *may* be done but i estimate it is a big challenge that requires a lot of knowledge and work.

**Comment by ramkrishnan8994** [comment]
Thanks @consideRatio
