### ISSUE TITLE
Service name not hard-coded

### ISSUE THREAD

**Issue by Jdavid7x** [jupyterhub/zero-to-jupyterhub-k8s#1208]
Hi,

We need to deploy your services with a different name. But now, i saw that is hard-coded on the template/service.yaml.

Is possible to have the name with some function like '_helpers.tpl/fullname'?

I will create a MR for that.

Regards,
JD.

**Comment by consideRatio** [comment]
Thanks for being an active member of this project @Jdavid7x!

As this is a popular topic that has been discussed and considered in many places without clear resolution for a long time, I've decided to close all existing issues and PRs relating to it and refer to a central issue. In this central issue I've done my best to provide a clear and actionable path towards progress.
