### ISSUE TITLE
[Question] Single user storage options

### ISSUE THREAD

**Issue by ramkrishnan8994** [jupyterhub/zero-to-jupyterhub-k8s#1211]
Jupyterhub version - v0.7

Are there any options for User storage apart from 'No storage' or 'Dynamic PVCs'.
Is it possible to create only one PV and link it to one claim. And each user has his/her own directories inside the volume (with appropriate permissions that is).

Can this storage be linked to gitlab anyhow? 
Each time the pod is restarted/created there's a pull that brings the notebooks to local.
Something bery similar to nbgitpuller, but different for each user

**Comment by consideRatio** [comment]
I felt that this question was a bit outdated to investigate at this point during my issue triage, so I'm going ahead and closing it. Note there is an issue to document storage options further (https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1211), and an issue about improving the authentication config system etc.
