### ISSUE TITLE
Use pipfile.lock for more reproducible image builds

### ISSUE THREAD

**Issue by minrk** [jupyterhub/zero-to-jupyterhub-k8s#1221]
Right now we have pinned some direct dependencies in our images, e.g. [here](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/0.8.2/images/hub/requirements.txt). This style is vulnerable to upgraded dependencies, e.g. tornado 6.

We should consider switching to using Pipfile.lock to only use a fully specified environment in our images and explicitly upgrade from a 'loose' Pipfile (or requirements.txt). The main thing this will require is a nice automated freeze step for generating the new Pipfile.lock files.

**Comment by consideRatio** [comment]
Ah I like that, I also like pipenv ;) I've had a good learning experience with that as compared to other virtual environments.

**Comment by consideRatio** [comment]
We now have a system solving this very well. As an example of it in use, see https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1768.
