### ISSUE TITLE
Shareable Link doesn't work if user specified in link has his pod running

### ISSUE THREAD

**Issue by manycoding** [jupyterhub/zero-to-jupyterhub-k8s#1227]
It was fun to figure this one out:

If you `copy shareable link` from a shared folder:
1. If username specified in the link has his pod (jupiter instance) running, it won’t be redirected and you will have an error:
```
Cannot find template: "403.html"

In "/opt/conda/share/jupyter/lab/static"
```

2. Otherwise it will be redirected and opened
A current workaround - use any name in the link except real users - e.g.
https://jupyter.s.com/user/a/lab/tree/shared/qa/com.ipynb

The only change I did in config.yaml which might be relevant - this attached shared folder.

Helm chart version 0.8.2

**Comment by josibake** [comment]
Any suggestions on where to start for fixing this? I have a shared volume attached on my JupyterHub instance and allowing users to link to shared notebooks would be awesome. Having a user manually edit the link each time seems like a pretty bad experience

**Comment by josibake** [comment]
Looks like this is solved in `JupyterLab 2.0` : https://github.com/jupyterlab/jupyterlab/pull/7906. Is it possible to specify jupyterlab 2.0 when deploying my helm chart in my values.yaml? or is this a change that needs to be made upstream ?

**Comment by manics** [comment]
@josibake JupyterLab is part of the single-user image. Z2JH bundles a minimal one, but you'll most likely want to specify your own. Are you using the default one at the moment?

**Comment by manics** [comment]
There's some docs on https://zero-to-jupyterhub.readthedocs.io/en/latest/customizing/user-environment.html
For example could write your own Dockerfile using one of the standard images mentioned in that link and upgrade JupyterLab, as well as installing any other custom packages.

**Comment by josibake** [comment]
thanks @manics ! I was struggling to find where to update JupyterLab (think it was in hub). I am using a custom single-user image , so this is perfect.

**Comment by manycoding** [comment]
Solved in https://github.com/jupyterlab/jupyterlab/pull/7906

**Comment by manics** [comment]
Thanks for updating the issue!
