### ISSUE TITLE
Add namespace support to helm charts

### ISSUE THREAD

**Issue by mingfang** [jupyterhub/zero-to-jupyterhub-k8s#1228]
All Kubernetes template files are missing the namespace field

For example,
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/03215dd4d65c13c84494df02a90a83d3a7c02023/jupyterhub/templates/hub/deployment.yaml#L4

**Comment by manics** [comment]
helm automatically sets the namespace (pass `--namespace <NAMESPACE>`), see the discussion on https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1084

**Comment by mingfang** [comment]
Not everyone uses or want to use helm.  I don't.
I have to use helm template to generate regular yaml but that does not generate the namespace field even when I pass in `--namespace <ns>`

**Comment by betatim** [comment]
> Not everyone uses or want to use helm.

That is fine. This project is about a helm chart and not a general kubernetes deployment solution. From the discussion in #1084 it seems like you can achieve what you want by adding `--namespace foo` to your `kubectl` command when you apply the rendered output of this helm chart.

Is there new information on helm chart best practices that wasn't considered in #1084? Without that it is unlikely that the outcome of the decision will change.
