### ISSUE TITLE
Clarification to Autoscaling Docs RE: multiple node pools

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/zero-to-jupyterhub-k8s#1229]
Hello!

[These docs on auto-scaling](https://zero-to-jupyterhub.readthedocs.io/en/latest/optimization.html#scaling-down-efficiently) should clarify that the labelling method described for efficiently scaling down is only useful if the Cloud provider supports multiple node pools with different labels in a single Kubernetes cluster. For instance, multiple node pools are not presently supported by Azure (though see https://github.com/Azure/AKS/issues/287) so Azure users would need to be mindful that their cluster is scaling down efficiently.

**Comment by consideRatio** [comment]
@sgibson91 it seems like AKS now supports multiple node pools as of november 2019 - https://github.com/Azure/AKS/issues/287#issuecomment-549436121. I'll go ahead and close this.

**Comment by sgibson91** [comment]
Yes, I can bring these docs across here if you like? https://alan-turing-institute.github.io/hub23-deploy/deploy-k8s-cluster-multiple-nodepools/

**Comment by consideRatio** [comment]
;D wow what a resource! Well if updating this documentation, that resource could be referenced perhaps? Awesome documentation btw, I really appreciate it is public :heart:

**Comment by sgibson91** [comment]
Closed by #1850

**Comment by consideRatio** [comment]
Another closed issue!!!! Wieeee!!! :tada:
