### ISSUE TITLE
Dynamic profile_list options and actions following the user choice

### ISSUE THREAD

**Issue by akoripelly** [jupyterhub/zero-to-jupyterhub-k8s#1233]
## Summary by @consideRatio

While we have [documentation on c.KubeSpawner.profile_list](https://zero-to-jupyterhub.readthedocs.io/en/latest/customizing/user-environment.html#using-multiple-profiles-to-let-users-select-their-environment), It would be good to have documentation on how to dynamically configure this (https://github.com/jupyterhub/kubespawner/issues/414#issuecomment-680228242), for example depending if the user is a lecturer or a student.

It would also be good to document how to take action following the user choice of an entry in the profile_list (https://github.com/jupyterhub/kubespawner/pull/393#issuecomment-703309234).

## Original issue

Can someone help me with the below scenario:

We have integrated Jupyter notebooks in a web application with Jupyterhub-k8s.  One of the requirements we have is to provide a list of custom images to the user in the application and once the user selects the desired image, we are looking to spawn the selected image on the k8s cluster.  I know there is a profile configuration that provides hardcoded options to select pre-defined images, However is there a way to pass it dynamically outside of Jupyterhub.  Many thanks for any help or guidance on how to go about this.

**Comment by rkdarst** [comment]
https://github.com/jupyterhub/kubespawner/pull/393#issuecomment-703317048 could be relevant, discusses wrapspawner and how the profile list could be moved to wrapspawner.

**Comment by npapapietro** [comment]
Late to the game here, but my config is using Keycloak with jupyterhub (which is now supported in the helm chart). We use oidc groups to dynamically define the profile list in the helm chart using `hub.extraConfig`

```yaml
spec:
  values:
    hub:
      extraConfig:
        01-profilelist: | 
          async def custom_options_form(self):
              auth_state = await self.user.get_auth_state()
              user_groups = auth_state.get("oauth_user",{}).get("member",[])
              profile_list = []
              if 'jupyter_basic' in user_groups:
                  profile_list += base_profile
              if 'jupyter_gpu_user' in user_groups:
                  profile_list +=gpu_images
              self.profile_list = profile_list
              return self._options_form_default()
          c.KubeSpawner.options_form = custom_options_form
```

**Comment by consideRatio** [comment]
Thanks for sharing @npapapietro!

I wrote a discourse post about how to dynamically configure KubeSpawner's profile_list that can be of relevance as well: https://discourse.jupyter.org/t/tailoring-spawn-options-and-server-configuration-to-certain-users/8449
