### ISSUE TITLE
Error running example command in zero to jupyterhub tutorial

### ISSUE THREAD

**Issue by michelp** [jupyterhub/zero-to-jupyterhub-k8s#1249]
Running the optional step 7 on:

https://zero-to-jupyterhub.readthedocs.io/en/latest/google/step-zero-gcp.html

produces an error in google cloud shell:

```
gcloud beta container node-pools create user-pool \
   --machine-type n1-standard-2 \
   --num-nodes 0 \
   --enable-autoscaling \
   --min-nodes 0 \
   --max-nodes 3 \
   --node-labels hub.jupyter.org/node-purpose=user \
   --node-taints hub.jupyter.org_dedicated=user:NoSchedule
ERROR: (gcloud.beta.container.node-pools.create) One of [--zone, --region] must be supplied: Please specify location.
```

**Comment by michelp** [comment]
To follow up, after adding --zone, it then complained about needing --cluster, which when provided then succeeded.

**Comment by consideRatio** [comment]
Thanks for reporting this @michelp !

**Comment by consideRatio** [comment]
Resolved it seems!

![image](https://user-images.githubusercontent.com/3837114/95271454-3a0f2e00-083e-11eb-88d3-baf27e0d1674.png)
