### ISSUE TITLE
Restrict proxy access to certain IP addresses

### ISSUE THREAD

**Issue by itssimon** [jupyterhub/zero-to-jupyterhub-k8s#1253]
We're running JupyterHub on Azure Kubernetes Service using the z2jh Helm chart and would like to restrict inbound traffic to company IP addresses only. As far as I know this would have to be specified in the NetworkPolicy for the proxy service. Currently this cannot be customised using the values.yaml.

Is there any way for me to achieve this while still using the z2jh Helm chart, or would I have to create my own?

**Comment by manics** [comment]
z2jh supports NetworkPolicies https://zero-to-jupyterhub.readthedocs.io/en/latest/security.html#kubernetes-network-policies

If it doesn't work can you share your config?

**Comment by itssimon** [comment]
It supports custom egress rules, but unfortunately the same is not true for ingress. See [netpol.yaml](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/jupyterhub/templates/proxy/netpol.yaml).

**Comment by manics** [comment]
I see. The main problem with restricting ingress to the proxy is you still need to allow access from the kubernetes cluster (for example for health checks or pod-pod comunications), and there isn't a standard K8S IP range that could be whitelisted. Does anyone know if there's a standard internal namespace that could be whitelisted?

The alternative would be to allow the proxy ingress netpol to be fully overridden, i.e. you'd have to include the "default" allow rules in your config. Would that work?

Is access to the proxy managed with an ingress controller, or load balancer? In the ingress case the netpol might have to apply to the ingress controller pods instead of jupyterhub, this would require investigation.

**Comment by GergelyKalmar** [comment]
Being able to define ingress rules would certainly be very useful, it could also help with resolving issue #1247 by restricting access to port 443 (not very elegant but at least you don't serve through http).

Simply allowing one to override the entire ingress section in [netpol.yaml](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/jupyterhub/templates/proxy/netpol.yaml) would be probably okay. The standard implementation through AWS EKS sets up a Kubernetes cluster in its own VPC, therefore I believe it might be enough to allow traffic from IP ranges within this VPC to enable communication between cluster nodes.

**Comment by betatim** [comment]
I think a PR that adds the ability for users to define additional ingress rules for the proxy in their `values.yaml` would be a good next step here. If someone wants to make a PR please go ahead.

**Comment by GergelyKalmar** [comment]
Actually a much better place to define this would be in [proxy/service.yaml](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/jupyterhub/templates/proxy/service.yaml) using the `loadBalancerSourceRanges` field (see https://kubernetes.io/docs/tasks/access-application-cluster/configure-cloud-provider-firewall/).

For those looking for a workaround in the meantime you can do this to patch the load balancer:
```
kubectl patch service proxy-public --patch '{"spec": {"loadBalancerSourceRanges": ["111.222.333.444/32"]}}' --namespace jupyter
```
Where the IP address and namespace should be adapted according to your needs. On AWS EKS this seems to change the security group of the load balancer nicely. Keep in mind though that you will need to probably apply the patch after every re-configuration.

I think making this configurable with a default value of 0.0.0.0/0 would be a perfect solution.

**Comment by itssimon** [comment]
100% agree with @GergelyKalmar! This is the workaround I've been using on both Azure and AWS and it works exactly as expected. Making this configurable via config.yaml would be easy and very helpful.

**Comment by consideRatio** [comment]
It is now possible to configure both the ingress part of NetworkPolicy resources (`proxy.networkPolicy.ingress`), as well as the loadBalancerSourceRanges (`proxy.service.loadBalancerSourceRanges`). Closing!
