### ISSUE TITLE
multi-stage CI

### ISSUE THREAD

**Issue by clkao** [jupyterhub/zero-to-jupyterhub-k8s#1260]
While working on #1259, i found that every PR's env matrix is rebuilding all images using chartpress.  To make things run faster, we should probably use [multi-stage travis](https://docs.travis-ci.com/user/build-stages/) to do the following:

1. tools/templates/lint-and-validate.py
2. chartpress and publish
3. setup k8s env and run tests

Note that only stage 3 should do matrix expansion into multiple jobs for different k8s version/config. and it needs to run chartpress render without building the image, since all stage 3 jobs can pull images built by stage 2.

For stage 2, we might be able to pull images before the current COMMIT_SHA, and this should avoid doing unnecessary image builds if nothing changed in the image subdirectories.

**Comment by consideRatio** [comment]
Wieeee awesome ideas @clkao ;D

**Comment by manics** [comment]
Where are you pushing the images to in stage 2?

**Comment by clkao** [comment]
I'd image some separate docker repo for intermediate PR builds.  the main problem is the credentials for pushing shouldn't be used by just any random PR. For kubernetes there's prow (the CI infra) running only trusted PR, or those been /ok-to-test'ed by trusted members.

But I think we can start with pulling the latest chartpress-built images of previous commit, so most of the time images aren't rebuilt. when there are changes to `images/`, they are built by all job variants.  For this to work I think we need something like `chartpress --render-only --list-images`

**Comment by clkao** [comment]
apparently chartpress has the logic checking if images already exist on registry and would skip build. in a local dev env, i see `Skipping build for jupyterhub/k8s-hub:0.9-c9f80ce, it already exists` when running chartpress. but this is somehow not the case on travis, for example: https://travis-ci.org/jupyterhub/zero-to-jupyterhub-k8s/jobs/526434320#L536
