### ISSUE TITLE
k8s nodes suddenly disconnect from k8s cluster

### ISSUE THREAD

**Issue by wierzba3** [jupyterhub/zero-to-jupyterhub-k8s#1262]
I have a kubernetes cluster (v1.10) running on AWS (EKS).

I have deployed jupyterhub helm chart on this cluster.

It has been operational for about 3 months, no issues.

This morning, the worker nodes became disconnected with k8s cluster. 

When investigating, my first finding is that the proxy-public ELB was marking the worker nodes as unhealthy. This made me suspect network traffic issue...

I looked at the security group associated with the worker nodes and discovered that it was not accepting traffic from the proxy-public ELB. (It originally had a rule to allow traffic coming from the security group associated with the proxy-public ELB).

It is not clear at this time how the rule was removed. But, I added it back. However, the ELB is still not marking the nodes as healthy, despite the fact the nodes are running.

Some diagnostic info I was able to get via kubectl:
```
kubectl describe svc proxy-public --namespace jhub

Events:
Type     Reason                   Age   From                Message
----     ------                   ----  ----                -------
Warning  UnAvailableLoadBalancer  1h    service-controller  There are no available nodes for LoadBalancer service jhub/proxy-public
```

and

```
kubectl get nodes --namespace jhub

No resources found
```

Note: I have an identical cluster, created with the same exact configuration, which is currently running just fine. This might help diagnose this issue by comparing the two cluster environments.

Not sure what the next best course of action is. I'm thinking that I should somehow try to get the nodes to re-join the cluster.

Ideally, I want to get the cluster back to running without losing any data.

**Comment by manics** [comment]
This sounds like an EKS problem unrelated to JupyterHub, you might be better off asking on an AWS developer/sysadmin forum?

**Comment by wierzba3** [comment]
@manics  -- yep .. I plan to contact AWS support. Just wanted to cover all bases in the hopes that someone here has encountered this issue before ...

**Comment by consideRatio** [comment]
Closing this issue as unrelated to the Helm chart, I hope it turned out okay @wierzba3!
