### ISSUE TITLE
Cost Estimator Data Source

### ISSUE THREAD

**Issue by noahbjohnson** [jupyterhub/zero-to-jupyterhub-k8s#1265]
Steps to reproduce:

- Launch the cost estimator https://mybinder.org/v2/gh/jupyterhub/zero-to-jupyterhub-k8s/master?filepath=doc/ntbk/draw_function.ipynb

- Run the notebook

- An error like this one will occur: `AssertionError: x columns passed, passed data had y columns`

It seems like there needs to be an overhaul of the way the cost information is collected. The current page is dynamic and presents a number of challenges for scraping. This results in recurring issues like #1145 

[There is an API available for gcp costs.](https://cloud.google.com/billing/v1/how-tos/catalog-api) It requires an API key for use, but there's a [more centralized page] than the one currently being scraped that could solve some of these challenges.

**Comment by consideRatio** [comment]
We have deleted this cost estimator notebook as we couldn't maintain it and it was assuming a fixed amount of nodes which probably isn't a common setup anyhow.
