### ISSUE TITLE
Add initContainers to hub configuration

### ISSUE THREAD

**Issue by scottyhq** [jupyterhub/zero-to-jupyterhub-k8s#1270]
Cross posting https://github.com/pangeo-data/pangeo-cloud-federation/issues/189

For pangeo clusters we are currently using a gitRepo volume to mount pangeo styling templates for custom jupyterhub login pages. We're having trouble getting this to work on AWS due to lack of write permissions at /usr/local/share/jupyterhub/, and it seems that gitRepo is deprecated according to kubernetes docs -https://kubernetes.io/docs/concepts/storage/volumes/#gitrepo.

It seems like the recommended approach would be to use initContainers under our hub (currently it is only available under singleuser): configuration, here is a nice example of that approach:
https://gist.github.com/tallclair/849601a16cebeee581ef2be50c351841

But... As far as I can tell, this would require adding the initContainers configuration option under hub:
https://zero-to-jupyterhub.readthedocs.io/en/latest/reference.html#hub

**Comment by minrk** [comment]
Makes sense. A PR adding this config would be welcome!

Doing so should:

1. add the `hub.initContainers` list in `jupyterhub/values.yaml`
2. pass the resulting value through to the deployment template in `jupyterhub/templates/hub/deployment.yaml`
3. add the new config value in `jupyterhub/schema.yaml`
