### ISSUE TITLE
release 0.9

### ISSUE THREAD

**Issue by minrk** [jupyterhub/zero-to-jupyterhub-k8s#1273]
We intend to make relatively frequent small releases of this chart, but the last release was a big one that took quite a while. We now include jupyterhub 1.0 in master and it's been about 3 months since 0.8, so it would probably be a good idea to try to make an 0.9 release soon.

What milestones to folks want to hit before we make another release? Remember, there's always release X+1!

**Comment by consideRatio** [comment]
I'd love to see the JupyterLab by default. but it is not a super trivial change so I'm happy to wait, but if there is preparation that needs doing for such change in the 0.10 release then I'd love to see that.

**Comment by oulydna** [comment]
hey folks, have we got an expected date yet?

**Comment by SolarisYan** [comment]
Hi @minrk , how is the progress?

**Comment by aliasmrchips** [comment]
Do the 0.9 dev releases include JupyterHub 1.0?

I have an upgraded singleuser image that I can't seem to use with the  0.8.2 chart. Not sure if it is a version mismatch, but that is my current theory.

**Comment by albertmichaelj** [comment]
I'd just would like to say a release that include JupyterHub 1.0 would be really helpful for me. I'm trying to get everything nailed down for my class infrastructure for the fall, and it would be good to go ahead and update JupyterHub.

Thanks for all the work on this!

**Comment by consideRatio** [comment]
We have released 0.9. Now it's 0.10.0 next!
