### ISSUE TITLE
Server Connection Error 503 service unavailable

### ISSUE THREAD

**Issue by jyipks** [jupyterhub/zero-to-jupyterhub-k8s#1284]
We are using helm chart v0.8.0 - When we update the helm chart while users have their notebooks running. There is a chance they receive this error. During the time of the helm chart upgrade, the hub pod is recreated, in that timeframe if the jupyternotebook webpage notices the hub is unavailable the error pops up.

The python jobs with long running time will get reset if that error pops up. For example, if i run the code below, and scale down the hub deployment to 0, within a minute the notebook will pop up with the error. 
```
import time
time.sleep(300.0)
print("hi")
```
Bringing up the hub pod back up allows for access again to the notebook but the code looks like its not running anymore.

What can we do to keep the notebook page fully accessible while the hub goes down for maintenance?

**Comment by consideRatio** [comment]
I think this has become more robust over time, a hub that restarts briefly for example will still allow users to keep working, and if the proxy pod restarts the hub pod will eventually update it.
