### ISSUE TITLE
HUB: Redirection to login page with error as invalid or expired cookie in hub logs

### ISSUE THREAD

**Issue by divyavprabhu** [jupyterhub/zero-to-jupyterhub-k8s#1286]
Hi All

After the hub and proxy pods are up, we are getting a login page. However, after entering a valid user, there is redirection happening back to the login page.

The hub logs throws the following error -  Invalid or expired cookie token. To address the same as mentioned in various issues, we have tried the following:
1. Have created a new token with "openssl rand -hex 32" and updated the cookieSecret in values.yaml
2. Have set the cookieSecret to null in values.yaml and letting the HUB create cookies in /srv/jupyterhub/jupyterhub_cookie_secret.

After trying all these options also we still see the same error in hub logs. Attached are the hub logs ,values.yaml and for your reference.

Jupyter hub version: 0.9.6
jupyterhub_config.py: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/0.8.2/images/hub/jupyterhub_config.py
[hub_logs.txt](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/files/3187316/hub_logs.txt)

[values_yaml.txt](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/files/3187329/values_yaml.txt)

**Comment by suryag10** [comment]
Solved this issue as ingress controller was filtering out the cookies.

**Comment by consideRatio** [comment]
Thank you so much for following up with the resolution @suryag10, that makes a big difference to me right now when issue triaging! :heart: :tada:
