### ISSUE TITLE
Use {username} for NB_USER

### ISSUE THREAD

**Issue by albertmichaelj** [jupyterhub/zero-to-jupyterhub-k8s#1292]
I am trying to set up what I assume is a reasonably common configuration. I want to change the username of the users in the docker containers. I thought I would be able to do something like:

```
singleuser:
  extraEnv:
    NB_USER: {username}
```

However, I get errors on launching the pod. I’m guessing that the environmental variables doesn’t expand {username}. Is this intended behavior or a bug? If it is intended behavior, is there another way to achieve my goal?

**Comment by consideRatio** [comment]
For a z2jh to change the username, more needs to be done, but I don't overview it all myself. But for example, the storage we mount to the container would need to be mounted specifically for the username and that is done even before there is an environment variable to be read.

In my mind, this is a very complicated challenge, and my best guess on how to best go about it if insisting on doing it would be to have some script to symlink the /home/jovyan directory with another user directory that one creates early on etc. But hmmm, it is certainly outside my knowledge domain to get this done right.

**Comment by manics** [comment]
You can use `pre_spawn_start` to set `NB_UID` and `NB_USER` after authnetication. If you run the singleuser container as root it should automatically rename the switch to the new username. See https://discourse.jupyter.org/t/starting-single-user-notebook-with-our-custom-ldap-docker-image/881/4

**Comment by albertmichaelj** [comment]
Yeah, that’s what I ended up doing. I’m happy to mark this issue as closed.

**Comment by sampathkethineedi** [comment]
Hi, I need help changing jovyan to {username} at all places. What worked for you?

**Comment by snickell** [comment]
Anyone have an example of how to do this for z2jh?

**Comment by snickell** [comment]
This example config from https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/990#issuecomment-432609082 might help others:

```singleuser:
  uid: 0

hub:
  extraConfig: |
    class CustomGitHubOAuthenticator(GitHubOAuthenticator):
        @gen.coroutine
        def pre_spawn_start(self, user, spawner):
            auth_state = yield user.get_auth_state()
            self.log.info('pre_spawn_start auth_state:%s' % auth_state)
            if not auth_state:
                return

            # setup environment
            spawner.environment['NB_USER'] = auth_state['github_user']

    c.JupyterHub.authenticator_class = LDAPAuthenticatorInfoUID

auth:
  state:
    enabled: True
    cryptoKey: SECRET-KEY
```
