### ISSUE TITLE
GKE setup docs: Zone / Region

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#1296]
As of #1290 we have a hardcoded example of using us-central-1, this should be made generic. But we may also consider writing about zonal vs regional clusters as a note.

It is good practice to use regional clusters with two inactivated zones. That way one can avoid having any k8s api server downtime because they will be Highly Available (HA) for free without any downside other than slower k8s upgrades of the master itself as far as I know.

/ Erik on vacation

**Comment by metonymic-smokey** [comment]
@consideRatio first time contributor to jupyterhub here.
If this issue is still open, could I make an attempt at changing the documentation to refer to zones generically and later, about zonal vs regional clusters?
Thanks!

**Comment by consideRatio** [comment]
@metonymic-smokey welcome!! Absolutely fire away a PR, I'll review it! :heart: :sunflower:

**Comment by consideRatio** [comment]
@metonymic-smokey closed this with #1431! Thank you for your work @metonymic-smokey :heart: :tada:!
