### ISSUE TITLE
Native authenticator by default

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#1297]
We are currently using the dummy authenticator by default (whatever user will work), but now we have the excellent native-authenticator at our disposal thanks to @leportella, perhaps we should make it the new default?

To learn more about the native authenticator, see https://blog.jupyter.org/simpler-authentication-for-small-scale-jupyterhubs-with-nativeauthenticator-999534c77a09.

I think it could reduce the amount of complexity needed to get started using a clean z2jh deployment by A LOT for teachers etc.

**Comment by dazzag24** [comment]
I'd love to see an example of how to configure this in the config.yaml.

**Comment by consideRatio** [comment]
Closed in favor of #1398
