### ISSUE TITLE
Add a different logo?

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/zero-to-jupyterhub-k8s#13]
Should we change the logo? I just threw that one together quickly because I needed to put something there...is there any "official" jupyterhub logo? And if not, we should have one! :)

**Comment by willingc** [comment]
Yes there are official logos. All goodness can be found in the Design repo https://github.com/jupyter/design. The presentation templates are outstanding as are the brand guidelines.

**Comment by choldgraf** [comment]
That's a helpful document! I was wondering specifically if there was a JupyterHub logo, as opposed to the standard Jupyter logo (I don't see any logos for jupyter derivatives specified in there, unless maybe I'm missing something).

The logo that's up there now is just the standard jupyter logo multiplied by 3 and arranged in a triangle (minus the planets). Think I should just replace it with the standard jupyter logo? I was thinking it'd be good to have a design specifically for JupyterHub, but this choice is definitely above my permissions level ;-)

**Comment by choldgraf** [comment]
I will use this one:

http://jupyter.org/assets/hublogo.svg

PR coming

**Comment by willingc** [comment]
Closed by #18
