### ISSUE TITLE
[Question] Is there a way to initialize a Persistant Volume with some files when the Claim is first issued

### ISSUE THREAD

**Issue by liuben10** [jupyterhub/zero-to-jupyterhub-k8s#1303]
Context:
I want to provide some sample analysis notebooks already loaded into their volume when a user is logging in to Jupyterhub for the first time (if it's deleted, I don't want to re-load the sample. I assume in this instance the User felt that it was not needed).

It seems like there should be a way to have some trigger that gets invoked when a PVC is created, but I'm kind of a newb and I don't see where I can configure this hook. Is it a deployment setting? A storage class setting? Is there someway to trigger via Events?

This is using Kubernetes 1.10 which was suggested through the zero-to-jupyterhub-k8s tutorial. Also using Docker 18.09.2.

EDIT: I realize there probably is a way if we can listen to Control Plane logs for PVC claim creation events and detect the user that is issuing the claim and then figure out to push a sample for them. But I was wondering if there was a native way in k8s.

**Comment by manics** [comment]
Have you looked at [nbgitpuller](https://github.com/jupyterhub/nbgitpuller)?

**Comment by consideRatio** [comment]
I use a k8s post-start-hook where i write code to download the latest README notebook to my users from a git repo.

That took a while to get right =\
