### ISSUE TITLE
Usage of c.KubeSpawner.pod_name_template - a malfunction?

### ISSUE THREAD

**Issue by Yiadh** [jupyterhub/zero-to-jupyterhub-k8s#1306]
Hello,

According to the official documentation, all user pods will begin with "jupyter-"
We need to have custom prefix for user pods. Is this possible?

We have already add "c.KubeSpawner.pod_name_template = 'jupyter-1-{username}' in jupyterhub_config.py file and it did not work.

By the way, I took into consideration this PR https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1144 and it did not work for me.

Thank you

**Comment by consideRatio** [comment]
@Yiadh I'd like to followup on this issue, but I'd like a clarification of what you mean with "it did not work". Are you saying that the user pods created after that configuration was applied, did not get created with the configured, or are you saying that that worked but something else didn't work?

**Comment by consideRatio** [comment]
Closing as stale and not reproduced. I have not tried it myself though.
