### ISSUE TITLE
Ambiguous instructions in helm setup

### ISSUE THREAD

**Issue by arokem** [jupyterhub/zero-to-jupyterhub-k8s#131]
Where is this line supposed to be executed? 

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blame/master/doc/source/setup-helm.rst#L31

Are you supposed to log into your cluster to do this? Into the head node? Into each of the worker nodes? Or do you do this on your local machine?

**Comment by willingc** [comment]
@arokem I run it locally.

**Comment by willingc** [comment]
Marking as "Help Wanted" for JupyterCon sprint. Add a clarifying statement that the `helm init` command is entered in the terminal of your local machine (similar to the terminal used for `kubectl`).
