### ISSUE TITLE
External services not being passed to hub configuration

### ISSUE THREAD

**Issue by rschroll** [jupyterhub/zero-to-jupyterhub-k8s#1310]
We've just moved from version 0.7.0 of the chart to version 0.8.2.  With this version, JupyterHub does not acknowledge any external services listed in the configuration file.  They are missing from `api/services` and the proxy is not set up to route to them.  Checking the helm manifest, these services are missing.

The problem seems to be commit 4af57f1, from #970.  Charts prior to this commit include the external services in the manifest; charts after it do not.

To test this, I created a short configuration file, `test.yaml`:
```yaml
hub:
  services:
    grader:
      admin: true
      api_token: "secret token"
      url: 'http://grader.namespace.svc.cluster.local:8082'

proxy:
  secretToken: "secret token"
```

Then I ran dry-run helm installs and looked for the grader service in the manifest that was output.  Here are the results:
```
$ helm install --dry-run --debug https://jupyterhub.github.io/helm-chart/jupyterhub-0.7.0.tgz -f test.yaml | sed -e '1,/MANIFEST/d' | grep -A 4 services
  hub.services: |
    grader:
      admin: true
      api_token: "secret token"
      url: "http://grader.namespace.svc.cluster.local:8082"
$ # This is the parent commit of 4af57f1:
$ helm install --dry-run --debug https://jupyterhub.github.io/helm-chart/jupyterhub-0.8-517c356.tgz -f test.yaml | sed -e '1,/MANIFEST/d' | grep -A 4 services
      services:
        grader:
          admin: true
          api_token: secret token
          url: http://grader.namespace.svc.cluster.local:8082
$ helm install --dry-run --debug https://jupyterhub.github.io/helm-chart/jupyterhub-0.8-4af57f1.tgz -f test.yaml | sed -e '1,/MANIFEST/d' | grep -A 4 services
      services: {}
      uid: 1000
    scheduling:
      corePods:
        nodeAffinity:
$ helm install --dry-run --debug https://jupyterhub.github.io/helm-chart/jupyterhub-0.8.2.tgz -f test.yaml | sed -e '1,/MANIFEST/d' | grep -A 4 services
      services: {}
      uid: 1000
    scheduling:
      corePods:
        nodeAffinity:
$ # Most recent chart:
$ helm install --dry-run --debug https://jupyterhub.github.io/helm-chart/jupyterhub-0.9-065e939.tgz -f test.yaml | sed -e '1,/MANIFEST/d' | grep -A 4 services
      services: {}
      uid: 1000
    scheduling:
      corePods:
        nodeAffinity:
```

To confirm that this is indeed the problem, I manually reverted 4af57f1 in a chart based on 0.8.2.  This included the service in the manifest, and indeed set it up properly on a real deploy.

The solution may be as simple as reverting 4af57f1, but I suspect that was trying to do something important.  I don't know enough about helm to understand what, so I'll an expert work that out.

All of this is assuming the format for specifying external services hasn't changed.  I didn't see anything in the changelog about such a change, but if it did change, just let me know and I'll be appropriately embarrassed.

**Comment by rschroll** [comment]
In case it matters:
```
$ helm version
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```

**Comment by manics** [comment]
The CI tests include a service API token: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/5bc1c2cc2ae594811695b2a62986cc3f1e8e1571/minikube-config.yaml#L21-L24

That is used in the tests: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/5bc1c2cc2ae594811695b2a62986cc3f1e8e1571/tests/conftest.py#L11-L13

The oldest version of Helm tested is 2.12.3: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/5bc1c2cc2ae594811695b2a62986cc3f1e8e1571/ci/minikube-1.11-default.env#L3

**Comment by rschroll** [comment]
I'm not convinced that this is an issue with helm versions:
```
$ ./helm2.12.3 template ~/.helm/cache/archive/jupyterhub-0.7.0.tgz -f test.yaml | grep -A 4 services
  hub.services: |
    grader:
      admin: true
      api_token: "secret token"
      url: "http://grader.namespace.svc.cluster.local:8082"
$ ./helm2.12.3 template ~/.helm/cache/archive/jupyterhub-0.8.2.tgz -f test.yaml | grep -A 4 services
      services: {}
      uid: 1000
    scheduling:
      corePods:
        nodeAffinity:
$ ./helm2.14.1 template ~/.helm/cache/archive/jupyterhub-0.7.0.tgz -f test.yaml | grep -A 4 services
  hub.services: |
    grader:
      admin: true
      api_token: "secret token"
      url: "http://grader.namespace.svc.cluster.local:8082"
$ ./helm2.14.1 template ~/.helm/cache/archive/jupyterhub-0.8.2.tgz -f test.yaml | grep -A 4 services
      services: {}
      uid: 1000
    scheduling:
      corePods:
        nodeAffinity:
```

(I'm using `helm template` instead of `install --dry-run` so that I don't get version errors with the server.  I think it's telling us the same information here, but I'm not 100% sure of that.)

**Comment by manics** [comment]
It looks like changing `api_token` to `apiToken` makes the service appear:
```yaml
hub:
  services:
    test1:
      admin: true
      api_token: test1test1test1test1test1test1test1test1test1test1test1test1test1test1test1test1
    test2:
      admin: true
      apiToken: test2test2test2test2test2test2test2test2test2test2test2test2test2test2test2test2
```
`test2` is picked up but `test1` isn't:
```
$ kubectl get cm -o yaml 
...
        services:
          test2:
            admin: true
...
```
There was some work done for 0.8.0 to rationalise the names of some properties, e.g. https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/CHANGELOG.md#breaking-changes-1 so maybe this change crept in? Though it's not clear to me how https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/970 affects it. @consideRatio ?

**Comment by consideRatio** [comment]
Hmmm, well, the configmap is not meant to contain the `apiToken`, but to be passed within the hub secret instead. Since k8s secrets will be base64 encoded you didn't spot it I think.

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/445a953d3ac385a01901a0711a892010818ef623/jupyterhub/templates/hub/secret.yaml#L29-L34

The hub, assuming we use the new image, should be able to read the value though as the secret should have mounted it instead now.

#### This is a helper function to get the relevant configuration passed by a mix of the configmap and secret that are mounted on the hub pod.
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/445a953d3ac385a01901a0711a892010818ef623/images/hub/z2jh.py#L15-L30



---

@manics :heart: you are an angel, I find you to be all over the place helping out!

**Comment by rschroll** [comment]
@manics Thanks for figuring this one out! I've just created a new JupyterHub deploy with the stock 0.8.2 chart and that change to the config file.  The service came up just fine, and the hub found and routed it correctly.

I couldn't find any current documentation that uses `api_token`, so I'll go ahead and close the bug.  Thanks again for your help!
