### ISSUE TITLE
How to set env variable after the server has started?

### ISSUE THREAD

**Issue by frouzbeh** [jupyterhub/zero-to-jupyterhub-k8s#1311]
I need to set some env variables after the single server has started, because the value would depend on another env variable which is different for each user. For example if I have env X which is different for each user, then I want to set env Y using this command to get a part of env X:

export Y=$(echo $X | cut -d'@' -f 1)

How can I do that? 
I tried CMD and ENTRYPOINT in Dockerfile, but it doesn't work. I wanted to know if there is any way to do that in config.yaml?

Thanks,

**Comment by consideRatio** [comment]
Hmmm... Idea overview: start a script, set an environment variable, and then start what was previously started by default.

Note that this is written from memory, I mainly doubt the `jupyter-labhub` command to start the singleuser server, I think that may be wrong, and perhaps one need to pass some arguments that came to the script onwards to the `jupyter-labhub` command as well.

```python
c.Spawner.cmd = "my-startup-script"
```

```bash
# my-startup-script
export Y=$(echo $X | cut -d'@' -f 1)
exec jupyter-labhub
``

**Comment by frouzbeh** [comment]
@consideRatio Thanks, I tried your solution but the env var Y is still empty. The problem is that env X will be set after a user logged in and I think in all ways that I tried X is not set yet.

**Comment by frouzbeh** [comment]
@consideRatio  Your solution worked, I was doing it wrong last time. Thank you :)

**Comment by consideRatio** [comment]
@frouzbeh wiee excellent :D :tada:
