### ISSUE TITLE
Release 0.9

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#1313]
This issue will be used to coordinate the next release of the helm
chart, {{release-name}}. Instructions for creating the release can be found in
[CONTRIBUTING.md](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/CONTRIBUTING.md#releasing-a-new-version-of-the-helm-chart).
Below is the checklist for this release.

- [x] Code, tests, and documentation to support a release are stable.
- [ ] Make a CHANGELOG
- [ ] Generate and add the list of contributors
- [ ] Build and push a new Docker image to DockerHub
- [ ] Commit version bump in `Chart.yaml` and `values.yaml`
- [ ] Update references in documentation to the new version (note: documentation should be stable and there should be no anticipated major changes to content).
- [ ] Confirm that a new deployment using the updated instructions works
- [ ] Create and push a new tag for this release
- [ ] Create and publish a new GitHub release
- [ ] Write / publish a blog post based largely off of the CHANGELOG
- [ ] Set ReadTheDocs to begin using `latest` by default
- [ ] Celebrate!

**Comment by stevegore** [comment]
> Code, tests, and documentation to support a release are stable.
You've indicated that the current 0.9-dev release is stable. Wondering if I should wait for a release, or just use the current chart as is. Is there a timeframe for release?

**Comment by hnykda** [comment]
@consideRatio Hi! Any updates on when we could expect another release? It has been some time since the last release and there seems to be a lot of new stuff in master now. Is there at least some ETA so users can plan accordingly?

xref https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1273

Thanks for great work!

**Comment by consideRatio** [comment]
@hnykda thank you for the encouragement!

I've decided to focus on making improvements so that the releases can follow quicker and easier in the long term, but that focus makes it a lot slower in the short term. I'm currently working hard towards a release though.

**Stuff I'm working on currently**
1. Release documentation rework (#1422)
2. Some automation regarding making changelogs (https://github.com/choldgraf/github-activity)
3. CI testing pipeline rework with `kind` and Python script, and bumping JupyterHub for a stability fix (#1422, https://github.com/jupyterhub/jupyterhub/issues/2745)
4. CI upgrade tests (#1427)
5. CD pipeline for tagged releases (#1422)

**Comment by hnykda** [comment]
Awesome, that definitely makes sense. Do you have any estimates when that can be done? Weeks/months/years? :grin:

**Comment by consideRatio** [comment]
@hnykda I'm aiming for one month :package:

**Comment by hnykda** [comment]
Hello :wave: . Any updates :grin: ? We are still stuck on quite low versions of ipython/jupyterlab/jupyter as there hasn't been any new release for quite a long time.

**Comment by consideRatio** [comment]
I'm working very hard on this, but it is a lot of work to bump dependency packages. To help out, check out this issue. There are some PRs that could very much benefit from review so we can make a release so we can bump the dependency packages so we can release this helm chart updated.

**Comment by hnykda** [comment]
Hey. https://github.com/jupyterhub/team-compass/issues/228 looks really promising, any updates?

**Comment by consideRatio** [comment]
0.9.0-beta.2 is out, 0.9.0 perhaps end of january? I aim to have jupyterhub 1.1.0 in the release of z2jh 0.9.0 which is also released as beta now

**Comment by hnykda** [comment]
:clap: That's awesome, thanks.

**Comment by hnykda** [comment]
![image](https://user-images.githubusercontent.com/2741256/74153857-c286f180-4c11-11ea-866d-c890c5a6a503.png)
Hey :wave: . Trying to orient in what's left. If this the only thing ^ or do you want to have something else in 0.9 as well?

**Comment by consideRatio** [comment]
There comes 0.9.0-beta.4 soon, including a bump of ldapauthenticator and oauthenticator. I figure leaving smarter environment variables out is reasonable because I fail to push towards fixing/reviewing such solution myself at the moment.

**Comment by hnykda** [comment]
Hey. I know I am annoying... But are there any pending issues for 0.9.

**Comment by manics** [comment]
The only significant issue I can think of is upgrading lets-encrypt certificates: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1594

Perhaps that could go into a "known issues" section of the release notes? [The original PR](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1539) was tested sucessfully, and as indicated in that PR the old lets-encrypt support in 0.8.2 is deprecated/broken, so even with known issues it's still an improvement over the current release.

**Comment by consideRatio** [comment]
We just need to get a changelog, and ensure to have some debugging steps for the upgrade at this point. I can try find time doing this on the weekend.

Quick summary about the upgrade steps out of my head:
- I think using --atomic --force make sense for the upgrade both in helm2 and helm3, the key is that we need to use --force in helm2 at least, and --atomic is there to help getting back to a OK state if something goes bad.
- We may need to delete the autohttps deployment also, it has not been tested so well as we don't have a test suite to work with TLS certificate acquisitions.

**Comment by ablekh** [comment]
Please clarify whether v0.9.0-beta.4 is usable for the non-upgrade (that is, clean install) option. Does the documentation reflect all required steps?

**Comment by consideRatio** [comment]
@ablekh it is very usable for non-upgrade situations, but a struggle is to figure out what to recommend for an upgrade from pre 0.9.0-beta.3 with automatic https enabled.

**Comment by ablekh** [comment]
@consideRatio Understood. Thank you very much for prompt clarification.

**Comment by consideRatio** [comment]
Released! Don't miss the upgrade instructions, they are important to avoid issues: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/CHANGELOG.md#090---2020-04-15

**Comment by ablekh** [comment]
@consideRatio That's great news. All the hard work of the core team and project contributors is much appreciated. Stay safe and well, everyone!

**Comment by consideRatio** [comment]
@ablekh for a kubernetes cluster that houses many helm charts, i'd probably install nginx-ingress + cert-manager. That setup would provide a highy available proxy entrypoint with TLS termination for all things in the k8s cluster.

But, for just a z2jh deployment, or just a z2jh with something more etc, I'd not complicate things by adding nginx-ingress + cert-manager, it would be too much overhead that just burdens the k8s cluster.

**Comment by ablekh** [comment]
@consideRatio Got it. Thank you very much for a very clear and prompt feedback!

**Comment by hnykda** [comment]
Yes! Excellent, Thank you very much!
