### ISSUE TITLE
hub pod stuck in pending

### ISSUE THREAD

**Issue by Dreeseaw** [jupyterhub/zero-to-jupyterhub-k8s#1315]
Hello,

I am trying to set up jhub on a 3-node cluster. Once I install it using a clean config file (only the proxyToken), the hub pod stays in pending 

```
tme@r504-s66:~$ kubectl -n jhub get pods
NAME                     READY   STATUS    RESTARTS   AGE
hub-5544fbbd76-84s2n     0/1     Pending   0          16m
proxy-7c44b9cc6c-zvmxm   1/1     Running   0          16m
```

When I investigate, I see that my nodes can not find any persistent volumes to bind, via

```
tme@r504-s66:~$ kubectl -n jhub describe pods
Events:
  Type     Reason            Age                 From               Message
  ----     ------            ----                ----               -------
  Warning  FailedScheduling  16s (x18 over 17m)  default-scheduler  0/3 nodes are available: 1 node(s) had taints that the pod didn't tolerate, 2 node(s) didn't find available persistent volumes to bind.
```

When I describe the persistent volume claim, it says that hub-dr-dir is waiting for first consumer to be created. However, I can not access the cluster as the external IP is still in the pending.

```
tme@r504-s66:~$ kubectl -n jhub get svc proxy-public
NAME           TYPE           CLUSTER-IP    EXTERNAL-IP   PORT(S)                      AGE
proxy-public   LoadBalancer   10.104.8.50   <pending>     80:31667/TCP,443:31083/TCP   21m
tme@r504-s66:~$ kubectl -n jhub describe svc proxy-public
Name:                     proxy-public
Namespace:                jhub
Labels:                   app=jupyterhub
                          chart=jupyterhub-0.8.2
                          component=proxy-public
                          heritage=Tiller
                          release=jhub
Annotations:              <none>
Selector:                 component=proxy,release=jhub
Type:                     LoadBalancer
IP:                       10.104.8.50
Port:                     http  80/TCP
TargetPort:               8000/TCP
NodePort:                 http  31667/TCP
Endpoints:                10.244.2.34:8000
Port:                     https  443/TCP
TargetPort:               443/TCP
NodePort:                 https  31083/TCP
Endpoints:                10.244.2.34:443
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>
```

Thanks for any help!

**Comment by consideRatio** [comment]
The Hub pod id requesting storage, but fails to get it. This is typically a cloud provider related issue.

"2 node(s) didn't find available persistent volumes to bind."

**Comment by Dreeseaw** [comment]
These nodes are a part of a VPN, I'm not using a cloud provider (using my org's own machines). Do you think being behind a VPN is affecting me getting an external IP?

**Comment by consideRatio** [comment]
Hmmm I'm not confident about what that will influence if anything, but no matter what, I'm quite confident that your kubernetes cluster cannot provision storage yet as it needs to, and that is the issue your facing now.

You probably lack a default "storageclass" or at least a functional one. I have not done this myself. I think these issues has been discussed in this repo before, but they are not related to this helm chart itself though.

**Comment by consideRatio** [comment]
I think you ran into the two key issues of setting up Kubernetes clusters, both the ExternalIP thing and the PV/PVC/StorageClass thing. I'm trying to prepare for us to document these parts are prerequisites with pointers on how to go about it.
