### ISSUE TITLE
Build a cloud provider test suite

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/zero-to-jupyterhub-k8s#1318]
Similar to https://github.com/Kubedex/dolos but with less snark, I think it'll be useful to have a test suite / benchmark for various cloud providers that does the following:

1. Create a cluster
2. Install master of z2jh
3. Start a user, run some code
4. (Optional) Start enough users to trigger an autoscaling scale-up
5. Make a change to the hub config, and upgrade the hub chart
6. Delete the cluster

This would let us pick up the following metrics:

1. Cluster create times & success rates
2. PVC attach times / success rates (for hub pod's sqlite db)
3. External Network IP availability (for proxy pod's LoadBalancer service)
4. Autoscaling latency & success rates
5. PVC re-attach times / success rates
6. Cluster deletion times

We should record metrics (success / failure rates & latencies) on all these activities, and make graphs out of these. This way we can (as much as possible) objectively measure the state of hub deployments in various cloud providers, and also work as a test suite for z2jh itself. We can also use this to figure out ideal configurations for various clouds. These tests should run multiple times so we get statistically significant numbers - consistency is important.

This costs money, so we probably won't be able to run it on CI or anything. Some institution (or the cloud providers themselves) would need to provide resources to keep this up to date.

**Comment by yuvipanda** [comment]
https://docs.datahub.berkeley.edu/en/latest/topic/cluster-config.html has info on how UC Berkeley's k8s clusters are set up on Google Cloud & Azure.

**Comment by consideRatio** [comment]
I appreciate how concrete you make the ideas @yuvipanda! :heart:

This would be very good to have, then for example we could have a easy time to verify upgrades before a chart release is tagged.

**Comment by yuvipanda** [comment]
Borrowing some terminology from https://landing.google.com/sre/sre-book/chapters/service-level-objectives/, it would be useful to define some general Service Level Indicators. These should be useful to decision makers, and provide general overview towards direct user behavior affected by each metric.

1. **Time to deploy**

   This counts time taken for a script to go from nothing to having a single user execute '2+2' in a Python kernel. 

2. **Time to autoscale up**

   This counts time taken for N+1 user to start up, where N users completely fill up the cluster. This generally counts for new node spin up time and image pulling time.

3. **100 users startup**

   This starts up 100 users over a 1 minute period, randomly distributed, and execute '2+2' in a Python kernel. This indicator should have several sub-indicators around latency, throughput and success rates.

4. **1000 users over 10 minutes**

   This starts up 1000 users over ten minutes, has them constantly executing code in a loop. Each user should continue doing this for a random amount of time, and then stop. This lets us test a more realistic workflow, where students come and go over time.

Outside of this, it might be useful to do:

1. Cost-based benchmarking (although modeling this is difficult)
2. Storage benchmarking

**Comment by consideRatio** [comment]
@yuvipanda while I agree this would be nice, I don't think it can go under the z2jh open source project so easily, it would require funding etc for cloud providers and I imagine it would be more work than we have maintainer capacity for.

What is your take on this? Perhaps something for 2i2c-org?

**Comment by yuvipanda** [comment]
Yeah, I agree - not something that z2jh can support by itself. Hopefully some cloud providers can take this on.
