### ISSUE TITLE
Inconsistent behavior while setting up HTTPS with letsencrypt

### ISSUE THREAD

**Issue by lakshaykc** [jupyterhub/zero-to-jupyterhub-k8s#1319]
I'm following this [security guide](https://zero-to-jupyterhub.readthedocs.io/en/latest/security.html) to enable HTTPS for jupyterhub using **letsencrypt**.

I have a domain and I'd like to setup notebooks.mydomain.com for jupyterhub server. Following the above process, HTTPS does not get enabled. I tried to confirm if notebooks.acubeir.com is running HTTPS using [Qualys SSL Labs](http://ssllabs.com/ssltest/analyze.html?d=<YOUR-DOMAIN>) (suggested in the documentation) and get a `certificate mismatch error`. The snapshot is attached.

Any ideas how can I diagnose if letsencrypt is working or not and where might be the breakpoint. Is it possible to see what certificate is being issued by letsencrypt? 

From the `certificate mismatch error`, it seems like the certificate doesn't contain the domain `notebooks.mydomain.com`. 

The behavior is inconsistent. The procedure has enabled HTTPS twice in the past but I have tried this multiple times on different kubernetes clusters and different variations of the domain (notebooks.mydomain.com, notebooks.mydomain.com, ntbooks.mydomain.com) but none of them seem to work. 

![image](https://user-images.githubusercontent.com/29871062/60370911-bf622c80-99c5-11e9-953b-d291c87015d7.png)

I'm running on google kubernetes engine with the following helm's config.yaml:

```
proxy:
  secretToken: <openssl rand -hex 32 token>
  https:
    hosts:
      - notebooks.mydomain.com
    enabled: true
    type: letsencrypt
    letsencrypt:
      contactEmail: 'email@gmail.com'

hub:
  extraEnv:
    OAUTH2_TOKEN_URL: "https://mydomain.com/o/token/"
    OAUTH2_AUTHORIZE_URL: "https://mydomain.com/o/authorize/"

  extraConfig:
    myConfig.py: |
      from oauthenticator.generic import GenericOAuthenticator
      c.JupyterHub.authenticator_class = GenericOAuthenticator
      c.OAuthenticator.client_id = 'dummy_id'
      c.OAuthenticator.client_secret = 'dummy_secret'
      c.GenericOAuthenticator.token_url = 'https://mydomain.com/o/token/'
      c.GenericOAuthenticator.userdata_url = 'https://mydomain.com/whoami/'
      c.GenericOAuthenticator.userdata_method = 'GET'
      c.GenericOAuthenticator.userdata_params = {"state":"random_state_string"}
      c.GenericOAuthenticator.username_key = "username"


singleuser:
  storage:
    capacity: 2Gi
```

**Comment by kramstrom** [comment]
I experienced a similar issue and for me the problem was that I had reached the rate limit for Let's Encrypt certifications for the week (https://letsencrypt.org/docs/rate-limits/). Trying it with a different domain (different subdomain is not enough) solved the issue.

**Comment by consideRatio** [comment]
There has been some issues when Let's Encrypt deprecated protocol used (ACMEv1), and we have since then also patched various details to make sure everything works robustly, so using the latest development release, I think we are good!
