### ISSUE TITLE
GenericOAuthenticator error : HTTP 599: gnutls_handshake() failed

### ISSUE THREAD

**Issue by lakshaykc** [jupyterhub/zero-to-jupyterhub-k8s#1321]
This error is exactly the same as seen in #1102 with the exception that I am using GenericOAuthenticator.

After a couple of hours of restarting JupyterHub, I see `HTTP 599: gnutls_handshake() failed` error in the JupyterHub logs and `500 : Internal Server Error` on the webpage. Restarting JupyterHub makes it work again.

I am using @joshbode's commit `--version=0.9-8463734` in config.yaml where **openssl** is used for pycurl which supposedly fixed the issue. #1185 explains the fix.

It doesn't seem to be cookie related as I see the same error if I clear out the cookies. 

@joshbode @consideRatio, you have looked into this in detail, any ideas how to diagnose this?

I can reproduce it but I don't know the exact time after the restart when it happens. Does the notebook server shut itself down if it's idle for a while and then trying to boot it up, it faces this issue?!

Here are the complete logs.
```
[E 2019-07-02 01:32:59.497 JupyterHub web:1788] Uncaught exception GET /hub/oauth_callback?code=2SYrirlHjMxGGDKhL4d5zJObEfRHa9&state=eyJzdGF0ZV9pZCI6ICJhMmE3YTA5YTM1ODc0NGJiODA3YWMwYjlkMmZkOWNmYSIsICJuZXh0X3VybCI6ICIvaHViL3VzZXIvdGVzdF91c2VyIn0%3D (10.128.0.9)
    HTTPServerRequest(protocol='https', host='notebooks.example.com', method='GET', uri='/hub/oauth_callback?code=2SYrirlHjMxGGDKhL4d5zJObEfRHa9&state=eyJzdGF0ZV9pZCI6ICJhMmE3YTA5YTM1ODc0NGJiODA3YWMwYjlkMmZkOWNmYSIsICJuZXh0X3VybCI6ICIvaHViL3VzZXIvdGVzdF91c2VyIn0%3D', version='HTTP/1.1', remote_ip='10.128.0.9')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1699, in _execute
        result = await result
      File "/usr/local/lib/python3.6/dist-packages/oauthenticator/oauth2.py", line 182, in get
        user = yield self.login_user()
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py", line 483, in login_user
        authenticated = await self.authenticate(data)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/auth.py", line 257, in get_authenticated_user
        authenticated = await maybe_future(self.authenticate(handler, data))
      File "/usr/local/lib/python3.6/dist-packages/oauthenticator/generic.py", line 116, in authenticate
        resp = yield http_client.fetch(req)
    tornado.curl_httpclient.CurlError: HTTP 599: gnutls_handshake() failed: An unexpected TLS packet was received.

[E 2019-07-02 01:32:59.507 JupyterHub log:150] {
      "Cookie": "oauthenticator-state=\"2|1:0|10:1562031179|20:oauthenticator-state|152:ZXlKemRHRjBaVjlwWkNJNklDSmhNbUUzWVRBNVlUTTFPRGMwTkdKaU9EQTNZV013WWpsa01tWmtPV05tWVNJc0lDSnVaWGgwWDNWeWJDSTZJQ0l2YUhWaUwzVnpaWEl2ZEdWemRGOTFjMlZ5SW4wPQ==|d02f07407251abab8149831a5af21e943aa5e164e54d51d263cf95c0d7e5e13e\"",
      "Accept-Encoding": "gzip, deflate",
      "Accept-Language": "en-US,en;q=0.9",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36",
      "Upgrade-Insecure-Requests": "1",
      "X-Scheme": "https",
      "X-Original-Uri": "/hub/oauth_callback?code=2SYrirlHjMxGGDKhL4d5zJObEfRHa9&state=eyJzdGF0ZV9pZCI6ICJhMmE3YTA5YTM1ODc0NGJiODA3YWMwYjlkMmZkOWNmYSIsICJuZXh0X3VybCI6ICIvaHViL3VzZXIvdGVzdF91c2VyIn0%3D",
      "X-Forwarded-Proto": "https,http",
      "X-Forwarded-Port": "443,80",
      "X-Forwarded-Host": "notebooks.example.com",
      "X-Forwarded-For": "10.128.0.9,10.24.0.10",
      "X-Real-Ip": "10.128.0.9",
      "X-Request-Id": "7fd4c09a50aa7c5ce270a6dab11466e9",
      "Connection": "close",
      "Host": "notebooks.example.com"
```

Also, can someone explain how the docker file and helm chart are related to each other? When I look at one of the [helm chart repos](https://jupyterhub.github.io/helm-chart/), there are the following files/directories:
```
\templates
Chart.yaml
schema.yaml
validate.py
values.yaml
```

Where are the changes in docker file reflected in the helm chart? When we [install JupyterHub](https://zero-to-jupyterhub.readthedocs.io/en/latest/setup-jupyterhub.html) with `helm upgrade --install $RELEASE jupyterhub/jupyterhub  --namespace $NAMESPACE  --version=0.9-8463734 --values config.yaml`,
we never reference the docker file. The reason I want to do this is to check that I am indeed using the changes made in #1185 with the aforementioned version.

Any reference documentation that would help me understand the moving parts between the docker file, docker image, and helm chart is greatly appreciated!

**Comment by joshbode** [comment]
I'm using `--version=v0.9-9c580a1`

I'm not sure, but I seem to remember some lag that meant the `k8s-hub` image wasn't rebuilt for that commit
(I don't see `0.9-8463734` in https://hub.docker.com/r/jupyterhub/k8s-hub/tags/)

**Comment by joshbode** [comment]
Interestingly, though - this f56b92b is my commit:

Looking at `values.yaml` in https://jupyterhub.github.io/helm-chart/jupyterhub-0.9-8463734.tgz: 
```
...
  image:
    name: jupyterhub/k8s-hub
    tag: '0.9-f56b92b'
...
```

**Comment by joshbode** [comment]
Though 8463734 is the _merge_ commit - so the builds may be off-by-one...

**Comment by consideRatio** [comment]
Thanks @joshbode for looking into this, interesting find about the version of the helm chart. Perhaps the difference is the merge commit vs the commit pre merge?

@lakshaykc im not sure what commit is when now that im writing from mobile, i suspect that this error would not show unless the docker image was older than it should within your deployment.

Why could that have happened? Hmmm... manually configured image, too old helm chart, or just fresh enough helm chart but with a wierd thing described by josh above.

I will try find time to give an overview of what you ask later, it is too complicated to motivate the time required to figure it out by yourself i think.

**Comment by lakshaykc** [comment]
I was going  by @consideRatio's [comment](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1028#issuecomment-474725189) which mentions `--version=0.9-8463734`.  If that's not the correct one, maybe we should mention it there as well.

The tags on k8s-hub and helm chart repo versions are the same right?

Let me try `--version=v0.9-9c580a1` as @joshbode suggested.

@consideRatio, I look forward to the overview. It'll make my understanding of this issue much better once I know how the helm chart and docker interact with each other. Thanks!

**Comment by consideRatio** [comment]
@lakshaykc I recommend using the latest helm chart release, which you can find on z2jhs github readme in a badge

/ erik - on mobile, on my way home from work on a train

**Comment by lakshaykc** [comment]
Ok, great. Let me try that.

**Comment by lakshaykc** [comment]
So, since I started using the version `0.9-9c580a1`, I haven't seen the issue.  This isn't the latest like @consideRatio suggested but it's close. However, the version (`0.9-8463734`) that we were thinking fixed the issue is misleading. 

I'm closing this issue.
