### ISSUE TITLE
Adding shared volume to multiple nodes in google cloud doesn't work

### ISSUE THREAD

**Issue by lakshaykc** [jupyterhub/zero-to-jupyterhub-k8s#1324]
This is more of a google cloud issue than JupyterHub but I'm adding it here for anyone interested in trying to have a shared volume for all the users on GKE.

Google cloud allows the addition of persistent volumes to be attached to multiple nodes if the volume has "ReadOnlyMany" access. See this [documentation](https://cloud.google.com/kubernetes-engine/docs/concepts/persistent-volumes). If the user servers are launched on the same node, the process works fine i.e a persistent-volume-claim (pvc) is shared by all users. The yaml config for mounting extra volume is described [here](https://zero-to-jupyterhub.readthedocs.io/en/latest/user-storage.html).

The problem arises when the user serves are launched on different nodes. The pvc gets attached to the first node and the second node throws off the an error saying the pvc is already being used by the other node.
```
2019-07-04 02:40:48+00:00 [Warning] AttachVolume.Attach failed for volume "pvc-demo" : googleapi: Error 400: RESOURCE_IN_USE_BY_ANOTHER_RESOURCE - The disk resource 'projects/example/zones/us-central1-b/disks/gke-cluster-xxx-xxx-pvc-xxx' is already being used by 'projects/example/zones/us-central1-b/instances/gke-cluster-b09-default-pool-xxx'
```

I also tried using persistent disks following this [documentation](https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/readonlymany-disks) and [pre-existing persistent disks](https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/preexisting-pd). I get the same error.

I'm in touch with google cloud support and will post if I get a solution. If anyone has any ideas that'll be great.

**Comment by lakshaykc** [comment]
Here is what I did to successfully attach a shared volume:

1. Create a persistent disk
2. Attach the disk a compute instance and mount it
3. Add data to the disk
4. Unmount the disk
5. Detach the disk
6. Follow the instructions for using [pre-existing persistent disks](https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/preexisting-pd) 

I was not unmounting the disk in step 4 which was causing attachment issues for JupyterHub. This method is only good for serving static files across different users.

**Comment by consideRatio** [comment]
@lakshaykc I'm a bit confused interested in learning a bit about this. Do you know if `ReadOnlyMany` is only supposed to be able to be consumed by multiple pods on different nodes, or only by multiple pods on the same node?

**Comment by lakshaykc** [comment]
Yes, you are correct. Earlier I was attaching it to a pod for transferring files to the disk and then I would try to attach it to other pods as `ReadOnlyMany` without unmounting it.

`ReadOnlyMany` is supposed to work with multiple pods on different nodes. However, it is recommended only for static files. Google cloud support suggested using Filestore is one needs to write and read from multiple pods. I haven't tried it though.
