### ISSUE TITLE
EKS - Help on Auto Scaling

### ISSUE THREAD

**Issue by asimb123** [jupyterhub/zero-to-jupyterhub-k8s#1325]
Hello Team,

I am trying to setup JupyterHub on ESK. All the things worked as documented except auto scaling. I am sure that there is something I am missing. 

Following is my part of  `config.xml` related to auto scaling

```
scheduling:
  userScheduler:
    enabled: true
  podPriority:
    enabled: true
  userPlaceholder:
    enabled: true
    replicas: 4
  userPods:
    nodeAffinity:
      matchNodePurpose: require
cull:
  enabled: true
  timeout: 3600
  every: 300
```

As per this [link](https://zero-to-jupyterhub.readthedocs.io/en/latest/optimization.html#id1), I tried to setup tags to my auto scaling group but nothing worked. Auto scaler logs as below

```
I0705 01:47:10.532266       1 utils.go:208] Pod user-placeholder-0 can't be scheduled on jupyter-eks-workernodes-NodeGroup-, predicate failed: GeneralPredicates predicate mismatch, reason: node(s) didn't match node selector

I0705 01:47:10.532311       1 utils.go:208] Pod user-placeholder-1 can't be scheduled on jupyter-eks-workernodes-NodeGroup-, predicate failed: GeneralPredicates predicate mismatch, reason: node(s) didn't match node selector

I0705 01:47:10.532360       1 utils.go:208] Pod user-placeholder-2 can't be scheduled on jupyter-eks-workernodes-NodeGroup-, predicate failed: GeneralPredicates predicate mismatch, reason: node(s) didn't match node selector

I0705 01:47:10.532409       1 utils.go:208] Pod user-placeholder-3 can't be scheduled on jupyter-eks-workernodes-NodeGroup-, predicate failed: GeneralPredicates predicate mismatch, reason: node(s) didn't match node selector
```

I tried to set tags as follow

```
Key: hub.jupyter.org/node-purpose
Value: user
Key: hub.jupyter.org/dedicated
value: user:NoSchedule
```

I have done Auto-Discovery Setup of CA following this [link](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md)

Any help would be really appreciated. This is last pending thing for me and I am struggling to get it working.

Thanks in advance!

Regards,
Asim

**Comment by asimb123** [comment]
I was able to resolve this by creating two auto scaling group. One for core system and one for worker node with label and taint.

**Comment by consideRatio** [comment]
Thanks for following up with the resolution @asimb123, I've often been helped by these kinds of followups! :heart:
