### ISSUE TITLE
postStart hook for hub pod itself

### ISSUE THREAD

**Issue by ahmedanis03** [jupyterhub/zero-to-jupyterhub-k8s#1329]
Can we add a postStart hook feature against the hub pod itself, or if you can guide me how to do it?

**Comment by consideRatio** [comment]
Hmmm...

Looking in the [hub's deployment yaml](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/jupyterhub/templates/hub/deployment.yaml) I don't see a hatch to set that.

I guess it would be reasonable to make it configurable through the helm chart values. It strains me a bit that I think we have ended up creating so many small hatches to do specific things like this also would be, but I think it is reasonable to continue doing it and do a proper rework for example when Helm 3 comes instead.

Input regarding potential PR made for this:
- Make it configurable with values in the hub's deployment.yaml
- Put a placeholder for the configurable value in values.yaml
- When naming helm value configurations, mimic the kubernetes APIs names

**Comment by consideRatio** [comment]
It is a reasonable feature, if someone wants to implement this, follow the guidelines i provide above and submit one. I'm closing this as this issue became stale.
