### ISSUE TITLE
How to set hub to ephemeral storage?

### ISSUE THREAD

**Issue by Boes-man** [jupyterhub/zero-to-jupyterhub-k8s#1332]
Hello,  i dont want to use persistent storage with my pangeo deployment. I am not sure but it looks like its only required for the hub db? i can see [topics about this](https://zero-to-jupyterhub.readthedocs.io/en/latest/reference.html#helm-chart-configuration-reference) but dont know which values to change? Potentially hub.db.type and/or sqlite-pvc and/or hub.db.pvc? What should those values be?

Looks like I need to pass values via config.yaml, [as per this link](https://zero-to-jupyterhub.readthedocs.io/en/latest/extending-jupyterhub.html) So I just need to launch an ephemeral hub each time?

Thanks

**Comment by manics** [comment]
Setting [`hub.db.type: sqlite-memory`](https://zero-to-jupyterhub.readthedocs.io/en/latest/reference.html#hub-db-type) removes the need for a hub persistent storage.

To disable persistent storage for the spawned singleuser servers set [`singleuser.storage.type: none`](https://zero-to-jupyterhub.readthedocs.io/en/latest/user-storage.html#turn-off-per-user-persistent-storage)

**Comment by consideRatio** [comment]
I think @manics is spot on!

**Comment by Boes-man** [comment]
Thanks @manics , that is indeed spot on. The singleuser link to doc makes it easy to implement, for the hub.db.type i have included my snippet as used in my vaules.yaml

`   hub:`
 `      db:`
  `        type: sqlite-memory`
