### ISSUE TITLE
Error running Cost Projection Tool Linked from Docs 

### ISSUE THREAD

**Issue by psychemedia** [jupyterhub/zero-to-jupyterhub-k8s#1334]
The docs' [Appendix: Projecting deployment costs](https://zero-to-jupyterhub.readthedocs.io/en/latest/cost.html) links out to a [cost estimation notebook](http://mybinder.org/v2/gh/jupyterhub/zero-to-jupyterhub-k8s/master?filepath=doc/ntbk/draw_function.ipynb) that throws the following error when run:

```
from z2jh import cost_display, disk, machines
machines

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-de8d1e48d121> in <module>
----> 1 from z2jh import cost_display, disk, machines
      2 machines

~/doc/ntbk/z2jh/__init__.py in <module>
      1 """Helper functions to calculate cost."""
      2 
----> 3 from .cost import cost_display, disk
      4 from .cost import machines_list as machines

~/doc/ntbk/z2jh/cost.py in <module>
     34 all_dfs = []
     35 for table in html.find_all('table'):
---> 36     header = table.find('thead').find_all('th')
     37     header = [item.text for item in header]
     38 

AttributeError: 'NoneType' object has no attribute 'find_all'
```

I'm guessing a scraped page has changed...

**Comment by antoniokaust** [comment]
I get the same error. Any idea on how to move forward? I could give it a try if somebody points me in the right direction.

**Comment by consideRatio** [comment]
We deleted this tool, it was too hard to keep maintained, and it was also quite limited in use because it assume a fixed amount of nodes while we probably automatically scale up and down.
