### ISSUE TITLE
Get logs for file download activity?

### ISSUE THREAD

**Issue by wierzba3** [jupyterhub/zero-to-jupyterhub-k8s#1336]
I have JupyterHub 0.7.0 deployed to AWS managed kubernetes (EKS)

I need to collect metrics for users that are downloading files from their individual user notebook servers.

Questions:
1. Are there any logs that are emitted from JupyterHub that will show file download activity? I need to see which user (or which pod) the file download happened from.
2. Where are these logs and how can I consume them?

Note: By "file download" I am referring to the "Download" button that is available on the Jupyter home page (see the provided screenshot)

![Screen Shot 2019-07-22 at 5 27 59 PM](https://user-images.githubusercontent.com/3789407/61673868-1cd85900-aca6-11e9-979d-8fbbb278fed8.png)

**Comment by BertR** [comment]
Are you using the AWS Elastic Loadbalancer in front of your Jupyterhub installation?
You can collect your access logs (after enabling them) https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/access-log-collection.html

The log line will look similar to `/user/my_user/files/Untitled.ipynb?download=1`

**Comment by wierzba3** [comment]
> Are you using the AWS Elastic Loadbalancer in front of your Jupyterhub installation?
> You can collect your access logs (after enabling them) https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/access-log-collection.html
> 
> The log line will look similar to `/user/my_user/files/Untitled.ipynb?download=1`

We are indeed using ELB and do indeed have ELB access logs enabled. Thanks for this tip I will test this out

**Comment by wierzba3** [comment]
@BertR  -- I enabled ELB access logs. I tested downloading a file but do not see any log properties that include the path you described. Which property of the ELB access log is supposed to have this path? I assume it is the "request" property? This field is empty for all of my ELB access logs ... :(

**Comment by BertR** [comment]
Are you using a TCP listener or an HTTP listener? The TCP listener will not have the request path filled out.

In that case, you can look at the access logs of the actual HTTP service (configurable-http-proxy). You will have to set the log-level to debug. Either using `debug.enabled=true` in the Helm file or by manually changing the `proxy` deployment resource.

**Comment by wierzba3** [comment]
@BertR  -- The ELB is using SSL listener (secure TCP)

Are you saying that the alternative method to get these logs is to get the logs for the kubernetes service (configurable-http-proxy) ? (e.g. "kubectl get logs ...")

Can you expand a little more on the helm config setting `debug.enabled=true` ? I am not seeing this setting in any of the documentation. Where does this setting go?

**Comment by BertR** [comment]
The setting goes in the helm chart values (https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/jupyterhub/values.yaml#L294-L295) 
So you can set it when you `helm install` or `helm upgrade`.

This in turn sets the log-level on the proxy to debug.
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/jupyterhub/values.yaml#L294-L295

Which should then allow you to `kubectl logs deployment/proxy` to tail the logs

**Comment by wierzba3** [comment]
I was able to get the data I need from AWS ELB access logs.

This required me to change a configuration setting. Specifically, the "proxy-public" ELB listener must be listening for HTTP traffic, not TCP traffic. (The "proxy-public" ELB listener is created implicitly with the JupyterHub helm application install)

The ELB access logs have a property for request. For a file download, the request property is formatted like so:

GET https://{DOMAIN}:443/user/{USERNAME}/files/{FILENAME}?download=1 HTTP/1.1

Where DOMAIN is the hosted domain for JupyterHub

Where USERNAME is the JupyterHub user

Where FILENAME is the file that was downloaded

**Comment by shreeishitagupta** [comment]
I am not using aws still i need these logs from jupyter lab being run on jupyterhub like downloads which happened on the single user server. There is logging for upload and delete but not for download...How to achieve that?

[I 2020-11-30 07:36:31.806 SingleUserNotebookApp handlers:153] Creating new directory in /
[I 2020-11-30 07:36:31.807 SingleUserNotebookApp log:181] 201 POST /user/fkuser/api/contents/?1606721791668 (fkuser@::ffff:114.69.240.166) 2.45ms
[I 2020-11-30 07:36:31.930 SingleUserNotebookApp log:181] 200 GET /user/fkuser/api/contents/?content=1&1606721791821 (fkuser@::ffff:114.69.240.166) 3.07ms
[I 2020-11-30 07:36:33.155 SingleUserNotebookApp log:181] 200 GET /user/fkuser/api/kernelspecs?1606721793048 (fkuser@::ffff:114.69.240.166) 2.99ms
[I 2020-11-30 07:36:33.422 SingleUserNotebookApp log:181] 200 GET /user/fkuser/metrics?1606721793311 (fkuser@::ffff:114.69.240.166) 8.87ms
[I 2020-11-30 07:36:37.665 SingleUserNotebookApp log:181] 200 PATCH /user/fkuser/api/contents/Untitled%20Folder?1606721797540 (fkuser@::ffff:114.69.240.166) 3.99ms
[I 2020-11-30 07:36:37.784 SingleUserNotebookApp log:181] 200 GET /user/fkuser/api/contents/?content=1&1606721797679 (fkuser@::ffff:114.69.240.166) 3.33ms
[I 2020-11-30 07:36:39.450 SingleUserNotebookApp log:181] 200 GET /user/fkuser/api/sessions?1606721799338 (fkuser@::ffff:114.69.240.166) 2.10ms
[I 2020-11-30 07:36:39.453 SingleUserNotebookApp log:181] 200 GET /user/fkuser/api/terminals?1606721799339 (fkuser@::ffff:114.69.240.166) 1.56ms
[I 2020-11-30 07:36:58.187 SingleUserNotebookApp log:181] 200 GET /user/fkuser/api/contents/?content=1&1606721818080 (fkuser@::ffff:114.69.240.166) 4.64ms
[I 2020-11-30 07:37:00.173 SingleUserNotebookApp log:181] 200 GET /user/fkuser/api/sessions?1606721820068 (fkuser@::ffff:114.69.240.166) 2.24ms
[I 2020-11-30 07:37:00.174 SingleUserNotebookApp log:181] 200 GET /user/fkuser/api/terminals?1606721820069 (fkuser@::ffff:114.69.240.166) 2.16ms
[I 2020-11-30 07:37:00.340 SingleUserNotebookApp log:181] 200 GET /user/fkuser/metrics?1606721820233 (fkuser@::ffff:114.69.240.166) 8.32ms
[I 2020-11-30 07:37:01.514 SingleUserNotebookApp log:181] 200 GET /user/fkuser/api/sessions?1606721821372 (fkuser@::ffff:114.69.240.166) 1.99ms
[W 2020-11-30 07:37:01.632 SingleUserNotebookApp handlers:236] delete /test.py
[I 2020-11-30 07:37:01.634 SingleUserNotebookApp log:181] 204 DELETE /user/fkuser/api/contents/test.py?1606721821526 (fkuser@::ffff:114.69.240.166) 2.56ms
[I 2020-11-30 07:37:01.750 SingleUserNotebookApp log:181] 200 GET /user/fkuser/api/contents/?content=1&1606721821646 (fkuser@::ffff:114.69.240.166) 4.19ms
[D 2020-11-30 07:38:14.406 JupyterHub proxy:766] Proxy: Fetching GET http://127.0.0.1:8001/api/routes
