### ISSUE TITLE
helm init with "--history-max" setting

### ISSUE THREAD

**Issue by bitnik** [jupyterhub/zero-to-jupyterhub-k8s#1339]
Helm documentation recommends initializing helm and tiller with `--history-max` setting: https://v2.helm.sh/docs/using_helm/#initialize-helm-and-install-tiller

> TIP: Setting --history-max on helm init is recommended as configmaps and other objects in helm history can grow large in number if not purged by max limit. Without a max history set the history is kept indefinitely, leaving a large number of records for helm and tiller to maintain.

What do you think, should we update the z2jh documentaion?

**Comment by consideRatio** [comment]
100% Kenan! Let's follow their suggestion by going for some default that people can change if they know what they are doing.
