### ISSUE TITLE
prepuller documentation is repeated

### ISSUE THREAD

**Issue by bitnik** [jupyterhub/zero-to-jupyterhub-k8s#1340]
`prepuller` is documented 2 times in [Advanced Topics](https://zero-to-jupyterhub.readthedocs.io/en/latest/advanced.html#pre-pulling-images-for-faster-startup) and [Optimizations](https://zero-to-jupyterhub.readthedocs.io/en/latest/optimization.html#pulling-images-before-users-arrive). And in `Advanced Topics` it is not up-to-date (e.g., continuous-image-puller is documented as it is disabled by default).

I would suggest to delete `prepuller` documentation in `Advanced Topics` page. What do you think? If you aggre, I can make a PR.

**Comment by consideRatio** [comment]
Thanks @bitnik !
