### ISSUE TITLE
cull_idle_servers issue with base_url: resolved by setting hub.baseUrl in config.yaml

### ISSUE THREAD

**Issue by Rothmanberger** [jupyterhub/zero-to-jupyterhub-k8s#1343]
I'm having an issue using the culling option with my JupyterHub.

Apologies I can't paste in all of my code as I don't have it right now, but I'll do my best to explain the situation

I am using an Nginx proxy from a seperate server using a `location` block and a `proxy_pass`
```nginx
location /jupyter {
    ...
}
```

In my custom helm chart I am setting:
```yaml
hub:
  extraConfig:
    baseUrl: |
      c.JupyterHub.base_url = '/jupyter'
```

This works fine as a user on the front end. I can access https://mydomain/jupyter and it will redirect me to login and everything works as normal.

When I turn on culling,
```yaml
cull:
  maxAge: 3600
  cullEvery: 60
```

Everything on the front end still works fine, but in the kubectl logs for the hub pod I can see I'm getting an error whenever it tries to do the culling check. There's a line that has (forgive me, this is off the top of my head) `302: /hub/api/users -> /jupyter/hub/hub/api/users`

This then throws some other errors which I can't completely remember but I'm pretty sure the cause is that it can't get to `/jupyter/hub/hub/api/users` as there is an extra `/hub` in there.

Any suggestions as to what is going here? Has anyone else used a `base_url` and Nginx as a reverse proxy with a matching `location` block?

Thanks.

**Comment by mschroering** [comment]
I am seeing this too. I think it has to do with the fact that the cull options are applied in jupyterhub_config.py before the `extraConfig` options are.  The culling service is configured without the `base_url` setting.  I was able to work around it by manually adding the cull service in the `extraConfig`. In my case the `base_url` is `/notebooks`

` cull: |
      c.JupyterHub.services.append({
        'name': 'cull-idle',
        'admin': True,
        'command': [
            'python3',
            '/usr/local/bin/cull_idle_servers.py',
            '--url=http://127.0.0.1:8081/notebooks/hub/api',
            '--timeout=3600',
            '--cull-every=300'
        ]
      })`

**Comment by bitnik** [comment]
You don't need `extraConfig` to set base url. You can do:

```yaml
hub:
  baseUrl: /jupyter
```

**Comment by consideRatio** [comment]
@mschroering excellent catch and excellent suggestion @bitnik. I'm not sure what makes the most sense to do about this. I lean towards thinking that things that startup should be done after extra config is considered, such as JupyterHub and the culler script, so I'll move the culler script startup to a later point.

**Comment by consideRatio** [comment]
Thanks for a clearly written issue @Rothmanberger, that makes a big difference! :heart:
