### ISSUE TITLE
Possible to allocate more than 10GB for storage?

### ISSUE THREAD

**Issue by wierzba3** [jupyterhub/zero-to-jupyterhub-k8s#1346]
I have JupyterHub 0.7.0 deployed on amazon EKS cluster (v1.11)

I'm using this default config for my storage in JupyterHub:
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
  name: gp2
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  encrypted: "true"
reclaimPolicy: Retain
mountOptions:
  - debug
```

This gives each user a 10GB volume for storage. I have a requirement to provide at least 15GB storage, so I want to know how I can configure a higher size?

**Comment by manics** [comment]
Use `singleuser.storage.capacity` in your z2jh config:
https://zero-to-jupyterhub.readthedocs.io/en/stable/user-storage.html#size-of-storage-provisioned

**Comment by wierzba3** [comment]
@manics I tried updating this value in my config and running a helm upgrade, however the enforced limit is still 10GB, even after restarting notebook server.

```
singleuser:
  storage:
    capacity: 16Gi
```

Any thoughts?

**Comment by wierzba3** [comment]
Hmm, in reading that documentation site more closely, it looks like updating PVC configuration will only affect new users? 

> Note that this will only affect new users who are logging in. We recommend you do this before users start heavily using your cluster.

**Comment by wierzba3** [comment]
I tested with a new user, and can verify

**Comment by consideRatio** [comment]
Note that there is a somewhat recent k8s feature allowing for expansion of storage claims that only required a pod restart.

Here is some trace of that idea, ive tried it myself once successfully. Dont remember much about the details now though, so just to complement this closed issue for someone looking at it later.

https://kubernetes.io/blog/2018/07/12/resizing-persistent-volumes-using-kubernetes/
