### ISSUE TITLE
Is it possible to skip the images selection progress in multi-profile condition, and start user server with customized image and resource directly?

### ISSUE THREAD

**Issue by Edward-liang** [jupyterhub/zero-to-jupyterhub-k8s#1347]
I configured several profiles in my values.yaml file. And when I register with a username, I'll be redirected to a profile-choosing page.
![image](https://user-images.githubusercontent.com/5849761/62269722-830f6980-b466-11e9-9209-c16fc369f8af.png)

However, considering some automation requirements, I want to find some way to directly choose different images from backend, which are already configured in values.yaml. I mean, customize the image and resource specifications of these servers on creation.

Till now, I have found some clues about this case.
1. In doc of JupyterHub, it says :
> With the named-server functionality, it’s now possible to launch more than one specifically named servers against a given user. This could be used, for instance, to launch each server based on a different image.
https://jupyterhub.readthedocs.io/en/stable/reference/rest.html

I don't know how to "to launch each server based on a different image". Could anyone give me some hint, please？

---
2. In https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1178 , pre_spawn_hook is used to use user_details to do customized action, so emm maybe it's possible to do the same thing according to different named-server param.

**Comment by consideRatio** [comment]
I updated this issue to represent additional documentation about configuring c.KubeSpawner.profile_list , and through it I also provided examples on dynamically configuring the profiles for users.

1. Hmmm, if you have enabled the named servers feature, I assume you can get to choose from the profile_list for each server you start in addition to the first. I've not used named servers myself, but that is a feature that you enable before you can use. See the JupyterHub docs for named servers.

2. I'm not fully clear what you want, but I do believe that you can accomplish everything by configuring hooks, and that https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1233 will provide you with examples on doing that.
