### ISSUE TITLE
[feature request] Allow namespace override

### ISSUE THREAD

**Issue by reevejd** [jupyterhub/zero-to-jupyterhub-k8s#1351]
I'm creating a helm chart that deploys several instances of JupyterHub by using several instances of the _zero-to-jupyterhub-k8s_ chart as subcharts. Helm typically deploys all releases to the same namespace. In a perfect world (for me anyway), multiple deployments of _zero-to-jupyterhub-k8s_ to the same namespace would be supported. [There’s some discussion of supporting same-namespace deployments here](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/615), but it seems for the moment it isn’t happening. 

If _zero-to-jupyterhub-k8s_ is not going to support multiple namespaces in the near future, I would like the option to override the default namespace so that I can deploy multiple instances via the same chart. [Here’s an example of a PR that added this same functionality to the official jenkins chart](https://github.com/helm/charts/pull/15202).

I'm happy to work on this feature myself, I just thought I would float the idea here to see if there are any objections before I start.

**Comment by manics** [comment]
FYI I'm using [helmfile](https://github.com/roboll/helmfile) to manage [multiple jupyterhubs on the same cluster](https://github.com/IDR/k8s-analysis-deploy/blob/master/helmfile.yaml)

**Comment by consideRatio** [comment]
It [seems like](https://github.com/helm/helm/issues/5358#issuecomment-628920908) the `helm` project doesn't intend to add support for specifying the namespace of a subchart, and that they suggest the use of `helmfile` just like @manics helped us learn about.

I think for this Helm chart, it's adds a bit too much complexity for this project to motivate the benefit as I perceive it. It is something that we wouldn't be able to test easily, and would therefore also be quite hard to maintain over time.

I'll close this feature request, if someone shows up needing this to, feel free to drop a comment as an indication of that.
