### ISSUE TITLE
nodePort access to proxy-public failed to redirect to /hub/login

### ISSUE THREAD

**Issue by LayneSadler** [jupyterhub/zero-to-jupyterhub-k8s#1354]
In this documentation, it should be made clear that you have to navigate to `/hub/login` at the `EXTERNAL-IP`.
> https://zero-to-jupyterhub.readthedocs.io/en/latest/setup-jupyterhub.html

`$ kubectl --namespace=jhub get svc proxy-public`
```
NAME           TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)                     
proxy-public   LoadBalancer   10.97.128.83   localhost     80:32753/TCP,443:31254/TCP  
```

I spent a while trying to nav to `localhost:32753` and `localhost:31254`

**Comment by consideRatio** [comment]
Hmmm... this is generally not true at least, and I don't know what made it so for you, but if you can debug this for example by inspecting your browsers network responses from visiting these paths it would be helpful.

The deployment should of course be accessible without specifying /hub/login, and typically is, so I'll close this as an issue I don't know how to reproduce, and if we don't understand it better I don't want us to document something being confused as I am at the moment.

Thank you for reporting your experience, let me know if you could realize what happened!
