### ISSUE TITLE
Readiness/Liveness setup challenge

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#1357]
I recently merged #1004 that had successful CI tests but then reverted the merge in #1356 after concluding my upgrade failed.

I'm not confident on what goes on. My hub and proxy pod wasn't entering a Ready state after this PR was merged by me. So I'll investigate things further but for now I figure I'll revert the PR so it does not cause disruptions for others like me.

```
Events:
  Type     Reason     Age                From                                         Message
  ----     ------     ----               ----                                         -------
  Normal   Scheduled  78s                default-scheduler                            Successfully assigned jupyterhub/proxy-7d4dcc5c64-pqv9w to gke-ds-platform-core-4d566784-54l4
  Normal   Pulled     76s                kubelet, gke-ds-platform-core-4d566784-54l4  Container image "jupyterhub/configurable-http-proxy:4.1.0" already present on machine
  Normal   Created    76s                kubelet, gke-ds-platform-core-4d566784-54l4  Created container
  Normal   Started    76s                kubelet, gke-ds-platform-core-4d566784-54l4  Started container
  Warning  Unhealthy  10s (x7 over 70s)  kubelet, gke-ds-platform-core-4d566784-54l4  Readiness probe failed: Get http://10.72.0.84:8000/health: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

```
Events:
  Type     Reason     Age               From                                         Message
  ----     ------     ----              ----                                         -------
  Normal   Scheduled  31s               default-scheduler                            Successfully assigned jupyterhub/hub-b9dccf7f7-htrxq to gke-ds-platform-core-4d566784-lspf
  Normal   Pulled     29s               kubelet, gke-ds-platform-core-4d566784-lspf  Container image "jupyterhub/k8s-hub:0.9-dcde99a" already present on machine
  Normal   Created    29s               kubelet, gke-ds-platform-core-4d566784-lspf  Created container
  Normal   Started    29s               kubelet, gke-ds-platform-core-4d566784-lspf  Started container
  Warning  Unhealthy  6s (x3 over 26s)  kubelet, gke-ds-platform-core-4d566784-lspf  Liveness probe failed: Get http://10.72.2.185:8081/health: dial tcp 10.72.2.185:8081: connect: connection refused
  Warning  Unhealthy  1s (x3 over 21s)  kubelet, gke-ds-platform-core-4d566784-lspf  Readiness probe failed: Get http://10.72.2.185:8081/health: dial tcp 10.72.2.185:8081: connect: connection refused
```

I wonder if this is related to:
1. Require use of HTTPS, and potential need to configure the liveness/readiness probe with `scheme: HTTPS`.
   __UPDATE:__ No I'm quite confident this isn't it after trying to access the endpoints from another pod. Using http should be fine.
2. My nginx-ingress-controller that routes traffic, but then... why? This request should be coming from kubelet which runs on a node, and it is directly asking for the pod IP, so why would the nginx-ingress-controller be used to route traffic? Related to this, providing a `Host:` header, as this controller routes based on web-request's host header.
3. Something about redirect in the response?
   __UPDATE:__ No I think k8s should approve any response between 200 and <400, also it sais timeout.
4. My hub pod could perhaps be stuck in an unresponsive state by getting stuck waiting for singleuser-server pods and not letting that wait timeout fast enough etc?

**Comment by consideRatio** [comment]
I think the issue is the readiness probe of the proxy that redirects to the hub readiness and checks, and the hub pod's liveness/readiness check are problematic.

**Comment by consideRatio** [comment]
Hmmmm yes okay so I got it to work again later now... Why? I think my hub pod failed to enter a responsive state because it got stuck waiting for response from singleuser servers, thereby restarting due to failed liveness checks, and got stuck again etc. So why does it get stuck waiting for the singleuser servers like this etc?

I figure a good option for now could perhaps be to enable these liveness probes optionally or at least have a flag to disable them.

**Comment by manics** [comment]
Do you know if your hub was completely unresponsive, so even if the health checks were disabled it'd still be unuseable, or if the health check was giving an incorrect response?

**Comment by consideRatio** [comment]
I'm not sure yet @manics, it is a bit hard to reproduce and will probably cause some user disruptions trying to do it. I'll live test these probes further.

**Comment by consideRatio** [comment]
# Questions in my mind
### Q1 - can users with started singleuser servers work with the hub pod down?
If we couple the proxy to the hub, that makes the proxy-public service return "service unavailable" if the hub pod isn't responding. Do we really want this? Is it possible for the proxy to let users work on with a hub pod being down?

# Fixes in my mind
### Fix 1 - /health should go to /hub/health
If we don't, we end up with lots of redirects. I think this is fine no matter what, but it is no point in bouncing around. I've also learned that if the redirect is to the same pod, it will be followed, but if the redirect is to another pod, it won't be followed after k8s 1.14.1 I think. This could cause issues in the future, I'm not 100%, anyhow, lets avoid it by directly requesting /hub/health instead of /health.

### Fix 2 - adjust liveness check params
Details about liveness / readiness probes in the docs can be found [here](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/). I think the failure I ended up with relates to quite hard constraints on these. That the failure was caused by not having a ready hub pod within 30 seconds, (3 failure periods * 10 second / period + 0 initial seconds).

I think increasing the value to 5 for the liveness probe's failure threshold may be enough to resolve my issue.

The default values for the liveness/readiness probes are...
```go
	epectedProbe := v1.Probe{
		InitialDelaySeconds: 0,
		TimeoutSeconds:      1,
		PeriodSeconds:       10,
		SuccessThreshold:    1,
		FailureThreshold:    3,
	}
```

**Comment by manics** [comment]
https://jupyterhub.readthedocs.io/en/stable/reference/separate-proxy.html implies the proxy will allow access to a singleuser pod if the hub subsequently goes down. I guess they problem is the proxy service is actually two services, one for the hub and one for the servers.

I think `/hub` needs to have the `base_url` prefix if set, since this is defined in Jupyterhub (as opposed to some other apps where the service always runs under the same prefix and the proxy takes care of mapping URLs)

**Comment by manics** [comment]
The other way to look at it is the proxy is "just a proxy": each individual singleuser server and hub pod are all separate services, so the proxy health check should reflect only whether the proxy is available regardless of the backend services. This means it should present a nice error page to the user if the hub isn't available.

**Comment by consideRatio** [comment]
# Current suggestion
- We let the hub have a /hub/health http liveness and readiness probe, and the proxy have a /_chp_healthz liveness and readiness probe. This is a simple PR that looks very much like #1004.
- We ensure we don't get stuck too long within `init_spawners()` somehow, which currently can take 30 seconds, or we increase add `initialDelaySeconds: 30` or similar to the hub's livenessProbe.

# Long term suggestions
We ensure to configure the proxy pods more reliably. They should be configured even though they are more than one, and they should be able to configure without being ready and not yet accepting traffic from a service. They could for example be ready whenever they have read from a configmap about what routes are available or similar.

**Comment by consideRatio** [comment]
> I think /hub needs to have the base_url prefix if set, since this is defined in Jupyterhub (as opposed to some other apps where the service always runs under the same prefix and the proxy takes care of mapping URLs)

I'm not confident on what goes on here, but the default helm value we provide has a `hub.baseUrl: /`, and that configures `c.JupyterHub.base_url`. In a service template for the hub, I notice an annotation like this: `prometheus.io/path: {{ .Values.hub.baseUrl }}hub/metrics`.

With this in mind, I guess we should configure the probes to not specifically visit the path /hub/health but instead `{{ .Values.hub.baseUrl }}hub/metrics`. Do you think that makes sense @manics?

**Comment by manics** [comment]
@consideratio yes, that sounds right!

**Comment by consideRatio** [comment]
This works fine after bumping to latest JupyterHub in #1422
