### ISSUE TITLE
JupyterHub becomes "stale" (unresponsive) after several days (it turns out, actually, hours)

### ISSUE THREAD

**Issue by ablekh** [jupyterhub/zero-to-jupyterhub-k8s#1359]
I have noticed that our current (Z2JH-based) JupyterHub instance becomes unresponsive and single-user server spawn requests disappear in some K8s galaxy "black hole" (that is, never reach the `hub` pod). I assumed (based on `kubectl describe` output that it is because, for some reason, `autohttps` pod (or connectivity to it) becomes broken [liveness tests report 1 success and 3 errors]. To test my assumption, I have deleted relevant `autohttps` pod and, indeed, upon a new pod instantiation, the server responds to user requests as expected and spawns corresponding single-user servers. Have you seen such behavior and what optimal approach (or options) to prevent this issue would you suggest?

**Comment by betatim** [comment]
Closing in favour of the [forum post](https://discourse.jupyter.org/t/server-becomes-stale-in-a-matter-of-days-even-hours/1920) to keep the discussion in one place. If there is a code/documentation change that comes out of this we can create a new issue.
