### ISSUE TITLE
Move JupyterHub database upgrade to an initContainer

### ISSUE THREAD

**Issue by manics** [jupyterhub/zero-to-jupyterhub-k8s#1372]
Follow-up from https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1361#issuecomment-523369429

The Jupyterhub pod liveness probe is disabled as the automatic database upgrade takes an indeterminate period of time.

Since the probes are applied to the container the database upgrade could be moved to an initContainer. An added benefit, especially if full HA support is added, is it'll give more control over the upgrade process.

**Comment by consideRatio** [comment]
I have not myself, or heard anyone with issues relating to long upgrades, and think that with the addition of `startupProbe` which can help us keep using livenessProbe even if we sometimes have a long startup duration, this is an issue we could close. What do you think @manics ?

**Comment by manics** [comment]
Let's close it!
