### ISSUE TITLE
Instructions for GCP are not working for machine-type = f1-micro

### ISSUE THREAD

**Issue by nscozzaro** [jupyterhub/zero-to-jupyterhub-k8s#1375]
When I follow the Zero to JupyterHub instructions for Google Cloud, they work perfectly for me. However, when I change the machine-type from `n1-standard-2` to the smallest machine type `f1-micro` (https://cloud.google.com/compute/docs/machine-types) with num-nodes=8, the hub is not created and so the setup fails. My motivation, which I think may be shared by others, is to set up the most **cost-efficient** JupyterHub possible, at least for an initial setup. 

The section in the instructions that I'm referring to is (https://zero-to-jupyterhub.readthedocs.io/en/latest/google/step-zero-gcp.html): 

```
gcloud container clusters create \
  --machine-type n1-standard-2 \    # Trying --machine-type f1-micro doesn't work for me
  --num-nodes 2 \                   # For f1-micro it tells me I must have at least 3 nodes, so I set it to 8
  --zone us-central1-b \
  --cluster-version latest \
  <CLUSTERNAME>
```

If someone knows why this may fail, or confirm what I'm experiencing I'd appreciate it, thank you!

**Comment by manics** [comment]
Could it be due to insufficient RAM or some other resource? What does `kubectl describe pod` show?

**Comment by manics** [comment]
```
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource                   Requests        Limits
  --------                   --------        ------
  cpu                        411m (43%)      53m (5%)
  memory                     226680Ki (95%)  288120Ki (121%)
```
Almost all the memory is used, and f1-micro is limited to an average of 0.2 CPU which has been exceeded: https://cloud.google.com/compute/docs/machine-types#sharedcore

**Comment by consideRatio** [comment]
I tried the same once, i concluded that it was a bit of a stretch to go for the micronode.

I settled for a n1-standard-1 for basic jh stuff and then allowing things to autoscale.

Making that single node preemtible could be a good way to reduce cost further i think but that would also allow the service to crash now and then.

When i got the 1 core setup functional, i removed some resource requests i think.

On mobile omw to work, so its hard to provide an example for me now on setting this but i think there are notes about this in the z2jh.jupyter.org guide. Note you want to reduce resource requets for the hub, proxy, and singleuser pod, not only one of these for example.

Also, you may want to trim the requests of system pods like kube-dns etc by going `kubectl edit` on the deployment or what the underlying controll of the pods are.

**Comment by manics** [comment]
> just so I understand, are you suggesting it might not be possible to run kubernetes on f1-micro?

That's what the resource usage and limits suggest. f1-micro is burstable which means you can use more than 0.2 CPU for short periods but it'll then be throttled again, this may explain why things may temporarily work.

**Comment by nscozzaro** [comment]
@consideRatio thank you for those insights... I looked into preemptible nodes, but it seems they only last 24 hours? Since it seems you have some good experience with this, I would be grateful if you would mind sharing the exact steps (commands) to set up the cheapest JupyterHub on GCP/kubernetes that can be permanently running? 

For reference, below is a summary of the instructions from the the z2jh docs that work for me for launching the current site that I have at studyhub.co (I've left out customizing my config.yaml). How would these change to implement your suggestions?

```
gcloud container clusters create --machine-type n1-standard-2 --num-nodes 1 --zone us-central1-b --cluster-version latest studyhub

kubectl create clusterrolebinding cluster-admin-binding --clusterrole=cluster-admin --user=nscozzaro1@gmail.com
kubectl --namespace kube-system create serviceaccount tiller
kubectl create clusterrolebinding tiller --clusterrole cluster-admin --serviceaccount=kube-system:tiller

helm init --service-account tiller --wait

kubectl patch deployment tiller-deploy --namespace=kube-system --type=json --patch='[{"op": "add", "path": "/spec/template/spec/containers/0/command", "value": ["/tiller", "--listen=localhost:44134"]}]'

helm repo add jupyterhub https://jupyterhub.github.io/helm-chart/
helm repo update
helm upgrade --install jhub jupyterhub/jupyterhub --namespace jhub --version=0.9-470ec04 --values config.yaml
```

**Comment by consideRatio** [comment]
@nscozzaro sorry for now following up at the time, I'd say its fully possible to get a 1 CPU deployment. The procedure is pretty much to shut down all not needed containers, and minimize the resource requests on all containers.

While working to do so, its relevant to know that there is sometimes a k8s resource that influence the default requests pods make: the LimitRange resource. `kubectl get limitrange`, see https://kubernetes.io/docs/concepts/policy/limit-range/ for more info.
