### ISSUE TITLE
Limits on volumes per physical node - need a way to increase

### ISSUE THREAD

**Issue by dirkcgrunwald** [jupyterhub/zero-to-jupyterhub-k8s#1385]
Kubernetes apparently has a scheduler limitation that limits the number of PV's that can be associated with a physical computer.  If jupyterhub reaches that limit, users receive a message "X node(s) exceed max volume count." and their notebook fails to launch.

The PV limit is 16 by default ( see e.g. https://kubernetes.io/docs/concepts/storage/storage-limits/ and https://github.com/kubernetes/kubernetes/issues/24317 )

For our departmental jupyterhub cluster, we were using 2 VPU nodes with students having a minimum CPU share of 0.05 (i.e. a 2-VCPU system would have up to 40 notebooks running, but the students are largely running "hello world" programs so it's OK).

We recently switched to using 8-VCPU machines because it causes fewer delays in spinning up nodes when 200+ login at once. The 16-PV limit is now happening a lot and we get complaints.

Is there an option to override the PV-per-node limit in JupyterHub? Is the best practice to just use many small nodes rather than fewer big ones?

**Comment by betatim** [comment]
That limit can't be configured through a helm chart so zero2jupyterhub can't change/configure it for you.

It is a setting of the kubernetes cluster you are using. This means how to change it depends on who is providing the cluster (ring up your admin if bare metal, look in the console of GKE if on GKE, etc). If you find out where exactly it is for your cloud provider and then add a short howto to the docs that would be great.

**Comment by consideRatio** [comment]
It could be good to have some documentation about these kinds of limitations, I recall there already is an issue for that that I currently fail to find. I'll close it for now.
