### ISSUE TITLE
Setting correct time zone for Z2JH logging

### ISSUE THREAD

**Issue by ablekh** [jupyterhub/zero-to-jupyterhub-k8s#1387]
I have recently noticed that, by default, log messages (e.g., on the `hub` pod) contain time stamps without correct time zone (UTC, I think, which is considered local). It would be beneficial to have accurate log output, so I'm wondering about what is the correct / optimal way to configure that ...

I'm thinking about the following potential configuration options (from bad to good/better, IMO):

**A.** Using a custom Docker image with time zone specified via `tzdata` (should be installed, if needed):

```
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=America/New_York
```

I don't like this option, because a) it requires using a custom image instead of a much preferred default one and b) changing time zone [though likely an infrequent need] would require rebuilding the image.

**B.** Using `hub.extraConfig`. Probably bad as well, because those configuration values are likely applicable to JupyterHub only, whereas we need a universal TZ-aware solution for all Z2JH components.

**C.** Using `hub.extraEnv`. Probably better, but I'm not sure whether these configuration values are cluster- or, at least, node-wide. Also not sure whether it requires `tzdata` package to be installed.

Perhaps, I'm wrong on all of the above and this is a solved problem, but I could find any relevant information throughout Z2JH documentation as well as relevant codebases (e.g., `kubespawner`).

**Comment by consideRatio** [comment]
I personally appreciate that most logs are in UTC by default. But, assuming this is something one wanted to configure, I think the best way to go about it is option C - with environment variables. If we need to install some package for this to work, that would be fine I think, but without additional demand for this and incoming PR requests to resolve it for a long time, I'll for now close this issue!

Thanks for your writeup @ablekh! :heart:
