### ISSUE TITLE
"Stop My Server" button (regression?)

### ISSUE THREAD

**Issue by ablekh** [jupyterhub/zero-to-jupyterhub-k8s#1389]
Based on my previous experience with JupyterHub UI, clicking `Stop My Server` button should make it disappear from the `Home` page after relevant server is deleted. However, this is not happening as of recently (can't tell exactly the version/date of regression, but it should be easy to reproduce; such unexpected behavior was not seen in the latest stable Z2JH Helm chart v0.8.2). At the same time, a similar behavior on the `Admin` page (`stop server` button) seems to still be working as expected.

Current environment: recent development version of Z2JH Helm chart, Chrome and Firefox browsers.

P.S. I still would very much appreciate thoughts / advice on https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1373 (unrelated, but very important).

**Comment by ablekh** [comment]
Just to clarify, button `My Server` correctly changes to `Start My Server`. Thus, the issue, as I described above, is that the UI leaves `Stop My Server` button in visible and active (as opposed to disabled) state.

**Comment by consideRatio** [comment]
This have been improved on in JupyterHub i recall, will be noticed with JupyterHub 1.2 I think!
