### ISSUE TITLE
PR Discussion - cert-manager / nginx-ingress

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#1394]
5th-8th September I had the chance to discuss a lot, that led to various ideas of PRs that I now document.

# Transition to cert-manager / nginx-ingress from kube-lego and internal TLS termination
This PR is meant as a transition PR, aiming to move away from our previous system to a new one.

__To be deprecated in this PR__:
- getting TLS certificates from kube-lego
- terminate TLS with these or other certificates ourselves with a custom pod

__The new solution:__
- getting TLS certificates from cert-manager, a helm chart we'll start to optionally depend on
- terminating TLS with nginx-ingress, a helm chart we'll start to optionally depend on

# PR work to be done
- Add the two Helm charts [cert-manager](https://github.com/jetstack/cert-manager/tree/master/deploy/charts/cert-manager) and [nginx-ingress](https://github.com/helm/charts/tree/master/stable/nginx-ingress) as optional dependencies.
- Add an option to create an Issuer or ClusterIssuer as required by cert-manager to be used.
- Document how to use cert-manager together with Ingress objects to get TLS certificates that cert-manager will save as k8s secrets.
- Document how to use and configure nginx-ingress to use the certificates within the k8s secrets created by cert-manager to encrypt/decrypt outgoing/incoming TLS traffic.
- Document for existing users how to migrate to the new setup.
- Document a suitable typical setup for new users.

# Related
- A discourse wiki post: https://discourse.jupyter.org/t/wip-documentation-about-cert-manager/2068
- @clkao's PR #755 to transition away from kube-lego
- While switching to use nginx-ingress, we will make a service go from a LoadBalancer service to a ClusterIP service type. At that point it may complain about nodePort etc. To avoid this, one may need to do something similar as to what is done in https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1404.
- [Helm's best practices regarding chart requirements](https://helm.sh/docs/chart_best_practices/#conditions-and-tags).
- [cert-manager issue on enabling in-chart install of the required CRDs](https://github.com/jetstack/cert-manager/issues/1254)

**Comment by consideRatio** [comment]
Discussion elsewhere summarized: we will not go this path, it adds significant complexity, and it's not deemed worth it.

**Comment by EnziinSystem** [comment]
@consideRatio ,
kube-lego is DEPRECATED.
```
kube-lego is in maintenance mode only. There is no plan to support any new features. The latest Kubernetes release that kube-lego officially supports is 1.8. The officially endorsed successor is cert-manager.

If you are a current user of kube-lego, you can find a migration guide here.
```
That is the message in homepage kube-lego.

**Comment by consideRatio** [comment]
@EnziinSystem yes we are not using kube-lego any more. We are using Traefik v2.3.2 running in the autohttps pod using the Golang library called LEGO.
