### ISSUE TITLE
PR Discussion - Add usage documentation to values.yaml

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#1400]
There are in other helm chart many nice example documentation in comments of values.yaml, we don't have much of that. See for example GitLabs' Helm charts for [GitLab itself](https://gitlab.com/gitlab-org/charts/gitlab/blob/master/values.yaml) or [GitLab runners](https://gitlab.com/gitlab-org/charts/gitlab-runner/blob/master/values.yaml) and note how they use `##` and `#` differently. Also read about the [Helm best practices](https://helm.sh/docs/chart_best_practices/#document-values-yaml).

**Comment by consideRatio** [comment]
We have so far opted to put things in `schema.yaml`, which renders to the z2jh.jupyter.org's configuration reference. I'm not at all sure about what makes the most sense, but I think if we choose one it may be the schema.yaml, and I'm cautious to going for both.

**Comment by manics** [comment]
Definitely avoid maintaining the same documentation in two places, it's guaranteed to get out of sync! It's hard enough keeping one set of docs up to date 😀. One option (a fair bit of work) is to have a script that parses one of the files and outputs the other with added docs, e.g. if `schema.yaml` contains everything include the defaults we could maybe parse it and autogenerate `values.yaml`.

That would be neat, but I don't think it's a high priority given all the other issues.

**Comment by manics** [comment]
Just had a thought, could we have a label for closed issues that indicates `good idea` so we can still track them down?

**Comment by consideRatio** [comment]
Closing this as I've become quite clearly in favor of not adding much comments to the values.yaml file about how configuration options are used. This is what we adopt the configuration reference for. But, for some values, it's nice to have a comment for example pointing to where to see if a image tag has been updated or not - in other words, comments mainly for the maintainers rather than users.

I'll close this issue at this point.
