### ISSUE TITLE
Adding NodeAffinity, Nodeselector, Toleration in JupyterHub Helm chart version 0.7.0

### ISSUE THREAD

**Issue by ramkrishnan8994** [jupyterhub/zero-to-jupyterhub-k8s#1402]
I can't see a proper documentation to add NodeAffinity, Nodeselector, Toleration in the Helm Chart v0.7.0. I read that c.KubeSpawner.singleuser_extra_pod_config is deprecated.

I can see the same in v0.8.2 chart but we have a dependency issue stopping us from using this version.

@consideRatio @yuvipanda

**Comment by consideRatio** [comment]
@ramkrishnan8994 sadly we are too few people working on this project to support augmenting a past release with a selected set of features.

Due to this, I would suggest considering upgrading to the latest helm chart and try resolve the shortcomings of that version.

Note that the deprecation of c.KubeSpawner.singleuser_extra_pod_config is a simple deprecation, where it is simply renamed to c.KubeSpawner.extra_pod_config, so that's an easy transition.

**Comment by ramkrishnan8994** [comment]
@consideRatio - Understand the situation. 
Would be REALLY helpful if you could just let me know how I would set nodeselector, tolerations and nodeaffinity for hub,proxy and singleuser components.

Thanks!

**Comment by consideRatio** [comment]
@ramkrishnan8994 I guess the documentation is a bit spread out, here is some from the jupyterhub helm chart configuration reference:
http://z2jh.jupyter.org/en/latest/reference.html#singleuser-extratolerations

Some additional notes are here on kubespawner itself: https://jupyterhub-kubespawner.readthedocs.io/en/latest/spawner.html

**Comment by ramkrishnan8994** [comment]
> @ramkrishnan8994 I guess the documentation is a bit spread out, here is some from the jupyterhub helm chart configuration reference:
> http://z2jh.jupyter.org/en/latest/reference.html#singleuser-extratolerations
> 
> Some additional notes are here on kubespawner itself: https://jupyterhub-kubespawner.readthedocs.io/en/latest/spawner.html

@consideRatio - I've given the documentation that you've given. But isn't this for v0.8.2? Will it work for v0.7.0?

**Comment by consideRatio** [comment]
@ramkrishnan8994 no, I don't think so, I don't see how that can be resolved, you will need to go towards newer versions of z2jh.

**Comment by ramkrishnan8994** [comment]
@consideRatio - Thanks!
I tried it out with c.KubeSpawner.singleuser_extra_pod_config and it works on v0.7.0!
