### ISSUE TITLE
Jupyterhub terminal user should be configured according to logged-in user

### ISSUE THREAD

**Issue by ramkrishnan8994** [jupyterhub/zero-to-jupyterhub-k8s#1405]
If a user has logged into Jupyterhub, then the terminal should ideally also use the same username. Instead, now it is the default user 'jovyan'.

Can 'fs-gid' be set dynamically? From what I understand, the user has to exist on the underlying system for this to work.
Is this possible?

**Comment by manics** [comment]
You can set the username, UID and GID inside the container dynamically: https://github.com/jupyter/docker-stacks/blob/82d1d0bf0867e410a2abc66862fa77c3e2a8d304/base-notebook/start.sh#L79-L91
You'll need to customise your Authenticator, e.g. see https://discourse.jupyter.org/t/starting-single-user-notebook-with-our-custom-ldap-docker-image/881

I don't think you can set fs-gid dynamically.

**Comment by consideRatio** [comment]
Its out of scope of this repo to resolve this, which greatly depend on the docker image, and will probably also require root privileges etc.

I'll go ahead and close it. c.KubeSpawner.fs_gid or the kubernetes native fsGroup part of the pod's securityContext could be configured dynamically from a pre_spawn_hook depending on the user if that was wanted.
