### ISSUE TITLE
[Feature] Allow to customise Jupyterhub RBAC

### ISSUE THREAD

**Issue by mrow4a** [jupyterhub/zero-to-jupyterhub-k8s#1419]
Would that be useful to allow to customise RBAC defined in https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/jupyterhub/templates/hub/rbac.yaml as part of values.yaml file ? At minimum extend `pod,pvc` with some additional resources? This could become a list of resources JupyterHub can create/modify/delete in the namespace. 

The use case is when as part of spawning process we create some additional **per user - dynamic** secret which is mounted to the container and then cleaned when container is stopped.

The goal is to avoid creating RBAC separately from the JupyterHub chart.

@prasanthkothuri

**Comment by manics** [comment]
Sounds like it could be useful. Do you have a link to your existing deployment or workarounds? That might be helpful to judge how much flexibility is needed- does the whole definition need to be overrideable or is it enough to append to subset of items?

**Comment by mrow4a** [comment]
@manics we plan of refactoring our current setup a little and use upstream chart - this is new development. 

Alternative is to generate the required files as part of dynamically spawned **jupyter pod side-containers** with required software. The drawback of it that each user pod will have this side-container along notebook container, plus some security considerations related to where it is generated (we have opinion that it is better as part of spawn process in jupyterhub and mount).

Many approaches are possible to extend rbac, but I think append of items in https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/jupyterhub/templates/hub/rbac.yaml#L15 will be more useful possibly to support use-cases like this one (if this is what you meant).

**Comment by consideRatio** [comment]
I think it could be a quite clean way to allow for augmentation of the RBAC Role for the Hub. It is also a quite clean option to bind another Role (declares k8s api permissions) to the hub ServiceAccount through a RoleBinding (Grants a ServiceAccount the permissions declared in the Role).

Does the added complexity of introducing, documenting, and maintaining this feature merit the benefits? Perhaps! I don't foresee much trouble from this feature.

If someone would need a ClusterRole and a ClusterRoleBinding, which would be required for any permission outside the scope of a namespace, for example relating to the nodes, the feature would not solve it. For that scenario, the chart user needing those ClusterRole permissions should instead define a parent chart with this helm chart as a dependency and define those resources there.

**Comment by mrow4a** [comment]
@consideRatio @manics let me summarize:
- for basic augumentation with just extending namespace roles, we could just in helm chart extend using values.yaml 
- for something more complex, building separate chart with jupyterhub chart as dependency is recommended

Is that correct?

**Comment by mrow4a** [comment]
I think most of the customisations can be done by wrapping this chart with another chart as dependency

**Comment by consideRatio** [comment]
> - for basic augumentation with just extending namespace roles, we could just in helm chart extend using values.yaml

It is currently not possible to do this, but it would be a plausible feature for the helm chart.

> - for something more complex, building separate chart with jupyterhub chart as dependency is recommended

Yepp, and for many small things I'd recommend wrapping this helm chart with another chart using this helm chart as a dependency (declared in requirements.yaml - ref: [official helm docs](https://helm.sh/docs/developing_charts/#managing-dependencies-with-requirements-yaml)).

:sunflower:
