### ISSUE TITLE
PR Discussion - Tagged releases in the CI/CD Pipeline

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#1429]
After #1422 and in conjunction of making a beta release for 0.9, I'd like to setup CD of tagged releases. If all it takes is to tag a commit and push it, then we could lower the threshold to making releases significantly.

**Comment by stefansedich** [comment]
@consideRatio out of interest when do you see 0.9 being released?

**Comment by consideRatio** [comment]
@stefansedish I dont know :/ But im working hard towards making them come more regularly by setting up better release documentation and testing infrastructure.

For a quite arbritary hopeful estimation: beta in 2 weeks, release in 1 month.

**Comment by consideRatio** [comment]
This may have been solved by #1422 if I got it right, I'll work to verify this right now.

**Comment by consideRatio** [comment]
Closed in favor of #1447
