### ISSUE TITLE
[ENH] Automate set up of config.yaml

### ISSUE THREAD

**Issue by fm75** [jupyterhub/zero-to-jupyterhub-k8s#143]
**Problem statement**: When teaching a workshop/tutorial audience how to deploy z2jh, it's possible that some people would not have a specific code editor (nano or vi) or knowledge of using the particular editor.

**Proposed enhancement**: Consider adding the ability to run a script from the console that will 1) generate the two needed keys and 2) write those keys to config file `config.yaml`.

**Comment by choldgraf** [comment]
Could we make this issue a little bit more specific? I think that until we have some kind of GUI support, it'll be hard to avoid editing a text file in these docs. Is this issue suggesting we add a GUI?

**Comment by fm75** [comment]
Not a GUI. I had written a script to address this, which we discussed briefly at the Jupytercon sprint.

The problem is that in an audience presentation of how to setup kubernetes, it probably is not fair to assume that the audience is all familiar with `nano` or any other single editor. A script that could be copied and pasted into a `console` that eliminated the need for editing `config.yaml` can be done in a few seconds. 

In the current version, constructing the yaml file required putting two keys into the file, which required one to edit the file twice to paste in each key. That takes longer to do even if you know `nano` or use `vi` (which in the middle of the presentation, I was not aware that it was an option).

**Comment by choldgraf** [comment]
right! I remember these conversations now. So you're talking just in the context of following the base z2jh guide (that only assumes you need the keys and no other configuration) right? That should be more doable :-)  I just wanted to get this issue clarified a bit more so that it's more actionable in the future

**Comment by willingc** [comment]
@fm75 @choldgraf I'm going to update the title of this issue. 

To summarize:

**Problem statement**: When teaching a workshop/tutorial audience how to deploy z2jh, it's possible that some people would not have a specific code editor (nano or vi) or knowledge of using the particular editor.

**Proposed enhancement**: Consider adding the ability to run a script from the console that will 1) generate the two needed keys and 2) write those keys to config file `config.yaml`.

**Comment by choldgraf** [comment]
@fm75 can we edit your top-level comment?

**Comment by fm75** [comment]
Absolutely!

**Comment by fm75** [comment]
My "solution" was to change `doc/source/setup-jupyterhub.rst` to just:

1. Create a file called ``config.yaml``. 
       echo "hub:" >config.yaml
       echo "    cookieSecret: \"$(openssl rand -hex 32)" >> config.yaml
       echo " " >> config.yaml
       echo "proxy:" >> config.yaml
       echo "    secretToken: \"$(openssl rand -hex 32)" >> config.yaml

Of course, other solutions would work, too.

**Comment by yuvipanda** [comment]
Unfortunately, I think using a text editor will be core requirement for editing the config.yaml file for some time to come, and I don't think there's any way around that. It's an essential complexity until we / someone builds a GUI.  

However, I think there are are other things we can do here:
1. Remove the need for running the openssl commands and copy pasting them. We've already removed the need for one in master, and the other should go away sometime after JupyterHub 0.8 is released.
2. Re-add instructions on using the Google Cloud Console, which has a real text editor that is web based so you do not have to use nano or vim. Make it clear to folks you can use any text editor you want.

**Comment by choldgraf** [comment]
for sure - I think that @fm75 is *only* talking about the two SSL key commands we currently have in z2jh. I agree that for anything more complex than that you gotta use a text editor.

**Comment by fm75** [comment]
Correct. I am not suggesting that doing real work with `kubernetes` might not require an editor. This only is an issue for making an interactive presentation to an audience and hoping to have it go smoothly with no avoidable interruptions from members of the audience trying to follow along.

**Comment by yuvipanda** [comment]
Awesome! I totally agree :)

I'll try to release a 0.4.1 release later with a lot of improvements, including cutting down openssl commands from 2 to 1.

**Comment by consideRatio** [comment]
@yuvipanda can we actually cut down from 1 to 0 as suggested by the following quote?

> We've already removed the need for one in master, and the other should go away sometime after JupyterHub 0.8 is released.

---

Closing in favor of #876, based on experienced of JupyterCon 2018.
