### ISSUE TITLE
Is this the end of jupyterhub@k8s?

### ISSUE THREAD

**Issue by AnotherCodeArtist** [jupyterhub/zero-to-jupyterhub-k8s#1433]
Hi!

Since Kubernetes 1.16.x kubespawner stopped working (https://github.com/jupyterhub/kubespawner/issues/354#issue-498060336) and there doesn't seem to exist any efforts by the team to fix this.

Are there any alternatives left?

**Comment by betatim** [comment]
Don't think this will lead to a productive, technical conversation so closing this now. For a free form discussion of alternatives and how to contribute to kubespawner the forum (discourse.jupyter.org) is a better place.
