### ISSUE TITLE
Documentation on the Auth0OAuthenticator

### ISSUE THREAD

**Issue by philvarner** [jupyterhub/zero-to-jupyterhub-k8s#1435]
There is currently support for several auth providers in the `auth` part of the config.yaml used by the helm chart. I would like support for Auth0 to be added there. 

An existing configuration for this looks like:
```
hub:
  extraEnv:
    AUTH0_SUBDOMAIN: '${A0_SUBDOMAIN}'
  extraConfig:
    myConfig.py: |
      c.JupyterHub.authenticator_class = 'oauthenticator.auth0.Auth0OAuthenticator'
      c.Auth0OAuthenticator.client_id = '${A0_CLIENT_ID}'
      c.Auth0OAuthenticator.client_secret = '${A0_CLIENT_SECRET}'
      c.Auth0OAuthenticator.oauth_callback_url = 'https://${JHUB_DNS_HOST}/hub/oauth_callback'
      c.Authenticator.admin_users = {
            'foo@example.com'
          }
      c.Authenticator.auto_login = True
```
where i'm processing the file through `envsubst` first to replace the secrets.  Note that (oddly) the only way to set the Auth0 subdomain is through an env var, and there's no support for setting that to a full custom domain.

**Comment by consideRatio** [comment]
Closed with #1871.
