### ISSUE TITLE
letsencrypt now wants ACMEv2

### ISSUE THREAD

**Issue by supern8ent** [jupyterhub/zero-to-jupyterhub-k8s#1448]
I just tried to set up another z2jh and the autohttps pod is reporting the following error:  
```"Error while processing certificate requests: 403 urn:acme:error:unauthorized: Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details." context=kubelego```

At https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 they sent out the following PSA yesterday: "The second production brownout for new ACMEv1 registrations has begun."

**Comment by consideRatio** [comment]
:O Thanks for reporting this!

ping @jupyterhub/mybinder-org-operators and others who this may concern.

**Comment by manics** [comment]
Looks like we need to switch to cert-manager as ACMEv2 isn't supported https://github.com/jetstack/kube-lego/issues/301

Related z2jh issues
- https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/475
- https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/755

**Comment by guzman-raphael** [comment]
+1
Just ran into this provisioning a JupyterHub Demo environment for a conference...
Any idea when could be addressed? Guess I will use a manual config for now.

**Comment by manics** [comment]
There are instructions for using cert-manager in https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/755
The PR needs more work but as far as I know they should work, if not please comment on that PR.

**Comment by yuvipanda** [comment]
I'm working on replacing the current kube-lego based autohttps with something much simpler based on upstream certbot that should help fix this without requiring the super heavy-weight cert-manager. https://gist.github.com/yuvipanda/64756b1bdc34faf1f20175ae5ea0e98e contains a minimal working example. I'm working on a PR to z2jh for this.

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/jupyterhub-upgrade-steps-for-https-acmev2/4029/1
