### ISSUE TITLE
What do the arguments to `helm upgrade` mean?

### ISSUE THREAD

**Issue by arokem** [jupyterhub/zero-to-jupyterhub-k8s#145]
On this line:

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blame/master/doc/source/extending-jupyterhub.rst#L21

Are the `jupyterhub/jupyterhub` and  `--version=v0.4` arguments both necessary? Or are these things that can be omitted/replaced? 

The reason I ask is that when I tried to apply an upgrade to add an image (`jupyter/datascience-notebook`) into the config failed for me, apparently because it was looking for the `jupyter/datascience-notebook:0.4` tag, that doesn't exist (`kubectl describe pod` FTW!)

**Comment by yuvipanda** [comment]
What's your config.yaml file look like? That error probably means that you have something like:

```
   image:
      name: <something>
```

but are *not* setting:

```
image:
   name: <something>
   tag: <something>
```

You must explicitly set the tag of the image you want to use too.

**Comment by yuvipanda** [comment]
And this should be caught in a lot of validation work that we still need to do in the helm chart.

**Comment by arokem** [comment]
The addition of the explicit tag did help!
