### ISSUE TITLE
Update oauthenticator to include GitLab authorization fixes

### ISSUE THREAD

**Issue by vindvaki** [jupyterhub/zero-to-jupyterhub-k8s#1455]
We are eager to see https://github.com/jupyterhub/oauthenticator/pull/283 upstream so we can update the JupyterHub GitLab-managed app. See also https://gitlab.com/gitlab-org/gitlab/issues/31165

I am happy to help in any way I can

**Comment by vindvaki** [comment]
@consideRatio do you think this is something you can help us with?

**Comment by consideRatio** [comment]
Absolutely, i'll work hard towards it whenever i get time to do so! Hard to provide an ETA but i'm doing my best
