### ISSUE TITLE
environment variables problem

### ISSUE THREAD

**Issue by rolinston4** [jupyterhub/zero-to-jupyterhub-k8s#1458]
my config.yaml:
![image](https://user-images.githubusercontent.com/28034434/67643710-4368f880-f955-11e9-9b7b-4129afe31b19.png)

`kubectl -n jhub get pods`
![image](https://user-images.githubusercontent.com/28034434/67643721-6c898900-f955-11e9-8091-b181ed5eda03.png)

image logs
![image](https://user-images.githubusercontent.com/28034434/67643703-2a604780-f955-11e9-95b4-b913111502a7.png)

**Comment by manics** [comment]
You shouldn't need to set `PROXY_API_SERVICE_HOST` and `PROXY_API_SERVICE_PORT`.
Which instructions are you following that tell you to set them?

**Comment by consideRatio** [comment]
(These are set by kubernetes on pods in a namespace with kubernetes services)

**Comment by rolinston4** [comment]
> You shouldn't need to set `PROXY_API_SERVICE_HOST` and `PROXY_API_SERVICE_PORT`.
> Which instructions are you following that tell you to set them?

I guessed the settings...

Then how should I do to solve the error problem in the image logs ?  And why does it happen?

**Comment by rolinston4** [comment]
> (These are set by kubernetes on pods in a namespace with kubernetes services)
Thanks for the hint, I find the place to add environment variables in k8s service.
