### ISSUE TITLE
Ephemeral Storage Problem when Pulling Docker Image

### ISSUE THREAD

**Issue by alexandermichels** [jupyterhub/zero-to-jupyterhub-k8s#1460]
Hello, I've deployed JupyterHub on Kubernetes using two Ubuntu VMs (not a cloud provider), but I'm having a problem when I try to incorporate a specific Docker image. The relevant part of the config is below:

```
singleuser:
  defaultUrl: "/lab"
  memory:
    guarantee: 1G
    limit: 2G
  storage:
    type: dynamic
    capacity: 2Gi
    dynamic:
      storageClass: rook-block
  image:
    name: padmanab/cybergis-notebook
    tag: latest
```

When I deploy this using Helm pods get evicted, disrupting even Helm because the nodes do not have enough "ephemeral storage." Part of the describe can be seen below:

```
Events:
  Type     Reason   Age    From                                 Message
  ----     ------   ----   ----                                 -------
  Warning  Evicted  2m50s  kubelet, <the hostname of a pod>      The node was low on resource: ephemeral-storage. Container hub was using 968Ki, which exceeds its request of 0.
  Normal   Killing  2m50s  kubelet, <the hostname of a pod>      Stopping container hub
```

The image puller describe events can be seen here:

```
Events:
  Type     Reason     Age                  From                                Message
  ----     ------     ----                 ----                                -------
  Normal   Scheduled  3m34s                default-scheduler                   Successfully assigned jup/hook-image-puller-mmqds to <master hostname>
  Warning  Failed     35s                  kubelet, <master hostname>       Failed to pull image "padmanab/cybergis-notebook:latest": rpc error: code = Unknown desc = failed to register layer: Error processing tar file(exit status 1): write /opt/conda/envs/python2/lib/libgdal.a: no space left on device
  Warning  Failed     35s                  kubelet, <master hostname>        Error: ErrImagePull
  Normal   BackOff    35s                  kubelet, <master hostname>        Back-off pulling image "padmanab/cybergis-notebook:latest"
  Warning  Failed     35s                  kubelet, <master hostname>        Error: ImagePullBackOff
```

I tried expanding the allocation of the Hub's ephemeral storage using the advice given in ["Managing Compute Resources for Containers"](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#local-ephemeral-storage) by altering the config in the following way:

```
hub:
  extraConfig:
    jupyterlab: |
      c.Spawner.cmd = ['jupyter-labhub']
  db:
    type: sqlite-pvc
    pvc:
      accessModes:
        - ReadWriteOnce
      storage: 1Gi
      storageClassName: nfs-class
  resources:
    requests:
      ephemeral-storage: "4Gi"
    limits:
      ephemeral-storage: "6Gi"
```

however this didn't solve the problem.

Anyone know how I can increase the cluster/nodes/puller ephemeral-storage allocation to pull this docker image? Thanks so much!

**Comment by alexandermichels** [comment]
I checked the node's ephemeral storage capacity and that is listed at 16GB, so I'm thinking the problem lies with specifying the limit/request for the puller. Anyone know how to do that within the Helm chart?

**Comment by manics** [comment]
How much free disk space do you have in your VMs?

**Comment by alexandermichels** [comment]
@manics thanks so much for the reply!

Here is the output of df -H on master

```
Filesystem                         Size  Used Avail Use% Mounted on
udev                               4.2G     0  4.2G   0% /dev
tmpfs                              834M  2.2M  832M   1% /run
/dev/mapper/ubuntu--vg-ubuntu--lv  8.4G  2.5G  5.6G  31% /
tmpfs                              4.2G     0  4.2G   0% /dev/shm
tmpfs                              5.3M     0  5.3M   0% /run/lock
tmpfs                              4.2G     0  4.2G   0% /sys/fs/cgroup
/dev/sda2                          1.1G  150M  803M  16% /boot
/dev/mapper/ubuntu--vg-lv_home      43G   63M   40G   1% /home
/dev/mapper/ubuntu--vg-lv_var       17G  4.4G   12G  28% /var
/dev/loop1                          94M   94M     0 100% /snap/core/7713
/dev/loop2                          94M   94M     0 100% /snap/core/7917
<ip address>:/var/nfs               22G  487M   20G   3% /mnt
<ip address>:/var/nfs/vm1           22G  487M   20G   3% /rook
tmpfs                              834M     0  834M   0% /run/user/1100619
```

df -H on the worker node
```
Filesystem                         Size  Used Avail Use% Mounted on
udev                               4.2G     0  4.2G   0% /dev
tmpfs                              834M  2.4M  832M   1% /run
/dev/mapper/ubuntu--vg-ubuntu--lv  8.4G  2.4G  5.7G  30% /
tmpfs                              4.2G     0  4.2G   0% /dev/shm
tmpfs                              5.3M     0  5.3M   0% /run/lock
tmpfs                              4.2G     0  4.2G   0% /sys/fs/cgroup
/dev/sda2                          1.1G  150M  803M  16% /boot
/dev/mapper/ubuntu--vg-lv_home     8.4G   39M  8.0G   1% /home
/dev/mapper/ubuntu--vg-lv_var       17G  4.2G   12G  26% /var
/dev/loop0                          94M   94M     0 100% /snap/core/7713
/dev/loop2                          94M   94M     0 100% /snap/core/7917
<ip address>:/var/nfs               22G  487M   20G   3% /mnt
<ip address>:/var/nfs/vm2           22G  487M   20G   3% /rook
tmpfs                              834M     0  834M   0% /run/user/1100619
```

**Comment by manics** [comment]
How big is your Docker image- what does `docker image ls` show?

Note that the size displayed on Docker Hub is misleading, as it's the size of the compressed layers.

**Comment by consideRatio** [comment]
Im on a mobile and cannot look into things as much as id like, but i suggest verifying if our helm chart config supporting configuration of resources in this way for the hub deployment pod.

If it doesnt, its time we fix it. One way to check is to run kubectl describe on the pod to see that you got the requested ephemeral storage

**Comment by alexandermichels** [comment]
@manics Good suggestion, it's 14.5GB compared to Jupyter/datascience-notebook which is 4.71GB. When the Helm 2.16.1 is released I will try redeploying with higher ephemeral storage limits and get back to you.

@consideRatio Thank you for the reply, I will get back to you with outputs when Helm 2.16.1 is released.

**Comment by manics** [comment]
You'll always be limited by the disk space available on your VM. Assuming you're using Docker the images will be somewhere under `/var/lib/` which is a 17GB partition (or 16GB depending on how you round things), and you're already using around 4GB of that.

**Comment by alexandermichels** [comment]
@manics So what do you suggest? I am using Docker. Is there an easy way to resize the `/var/lib` partition and/or make VMs with larger `/var/lib` partitions or do I have to choose smaller images?

**Comment by manics** [comment]
You should be able to create a larger VM or resize the existing one, but you'll have to look at the documentation for your hypervisor/virtualisation/storage platform.

**Comment by consideRatio** [comment]
I'm not sure what went wrong, but I'd love to know if you came to a conclusion about this @alexandermichels! It is a bit out of scope to try resolve this in this repo further though, because its unrelated to the Helm chart I believe.

## Related
- [k8s docs on ephemeral-storage is probably very relevant](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#setting-requests-and-limits-for-local-ephemeral-storage)
- > - you have set up the node using one of the supported configurations for local ephemeral storage.
