### ISSUE TITLE
Error when running 0.9.0-alpha

### ISSUE THREAD

**Issue by cometta** [jupyterhub/zero-to-jupyterhub-k8s#1463]
I get below error when with prebuilt images 0.9.0-alpha.** for jupyterhub

> 
> I 2019-10-29 07:02:35.841 JupyterHub app:2337] Hub API listening on http://127.0.0.1:8081/hub/
> [W 2019-10-29 07:02:35.842 JupyterHub proxy:642] Running JupyterHub without SSL.  I hope there is SSL termination happening somewhere else...
> [I 2019-10-29 07:02:35.842 JupyterHub proxy:645] Starting proxy @ http://:8000
> [E 2019-10-29 07:02:35.846 JupyterHub proxy:658] Failed to find proxy ['configurable-http-proxy']
>     The proxy can be installed with `npm install -g configurable-http-proxy`.To install `npm`, install nodejs which includes `npm`.If you see an `EACCES` error or permissions error, refer to the `npm` documentation on How To Prevent Permissions Errors.
> [C 2019-10-29 07:02:35.846 JupyterHub app:2349] Failed to start proxy
>     Traceback (most recent call last):
>       File "/usr/local/lib/python3.6/dist-packages/jupyterhub/app.py", line 2347, in start
>         await self.proxy.start()
>       File "/usr/local/lib/python3.6/dist-packages/jupyterhub/proxy.py", line 650, in start
>         cmd, env=env, start_new_session=True, shell=shell
>       File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
>         restore_signals, start_new_session)
>       File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
>         raise child_exception_type(errno_num, err_msg, err_filename)
>     FileNotFoundError: [Errno 2] No such file or directory: 'configurable-http-proxy': 'configurable-http-proxy'
> 
> ERROR:asyncio:Task exception was never retrieved
> future: <Task finished coro=<JupyterHub.launch_instance_async() done, defined at /usr/local/lib/python3.6/dist-packages/jupyterhub/app.py:2477> exception=SystemExit(1,)>
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/dist-packages/jupyterhub/app.py", line 2347, in start
>     await self.proxy.start()
>   File "/usr/local/lib/python3.6/dist-packages/jupyterhub/proxy.py", line 650, in start
>     cmd, env=env, start_new_session=True, shell=shell
>   File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
>     restore_signals, start_new_session)
>   File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
>     raise child_exception_type(errno_num, err_msg, err_filename)
> FileNotFoundError: [Errno 2] No such file or directory: 'configurable-http-proxy': 'configurable-http-proxy'
>

**Comment by consideRatio** [comment]
prebuilt hub image? It is not properly documented what you need to consider in 0.9.0 for that, but i could benefit from input.

How is your image built? Is it using FROM our k8s-hub image or from scratch mimicing our past image?

**Comment by cometta** [comment]
@consideRatio i use image directly from https://hub.docker.com/r/jupyterhub/k8s-hub/tags

**Comment by consideRatio** [comment]
The image needs to go alongside the helm chart, in 0.9.0-alpha will inject configuration. I'm very low on time, but briefly I suggest: use the same helm chart version as the image foundation, and if you get into additional trouble, await the next beta release.

**Comment by cometta** [comment]
I did another testing. I'm using helm 0.8.2 , git checkout ec3b97df3f758ce69102a77502622c3be4b53e77   (same image like 0.9-ec3b97d , not the 0.9alpha), then docker built the hub. Still i get the error.

**Comment by consideRatio** [comment]
use exactly the same hub image version as the chart version, check this repos readme that has a badge eith info about latest bleeding edge version and use the fresh 0.9.0-alpha.1.014.something for both chart and image
