### ISSUE TITLE
Putting z2jh.py next to jupyterhub_config.py in the hub image

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#1464]
@mrow4a came with excellent input and a concrete suggestion in https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1407#issuecomment-538936442 on how to make the ability to customize the hub image more reliable. I like this proposal, it just needs to be implemented.

You are very welcome to contribute with the implementation as well @mrow4a! :sunflower:

**Comment by mrow4a** [comment]
Yes, I will have a look next days.

**Comment by mkjpryor-stfc** [comment]
+1

Putting `z2jh.py` in the `WORKDIR` is important when the hub image in use does not use the exact same OS and Python version as the reference implementation. At the moment, if you are not using Python 3.6 with `dist-packages` under `/usr/local/lib`, `z2jh.py` cannot be found!
