### ISSUE TITLE
proxy-public never gets an external-ip

### ISSUE THREAD

**Issue by kumarasenthil** [jupyterhub/zero-to-jupyterhub-k8s#1477]
Everything seems to work until the last step that is mentioned in the Z2JH guide:
kubectl --namespace=jhub get svc 

![image](https://user-images.githubusercontent.com/55604143/68649381-7cd76180-051a-11ea-9fba-83dfbde5669c.png)

The proxy-public node never gets an external-ip.

The config.yaml file is clean just containing the secret token and nothing else.

Any help?

**Comment by kumarasenthil** [comment]
cloud provider: AWS
EKS Cluster and Worker nodes created through Terraform

Running the kubectl command from within the instance that created the EKS cluster and worker nodes.

**Comment by consideRatio** [comment]
This relates to your Kubernetes setup, my initial feeling was to think of things in #1428, but if you are using EKS i figure that should be setup for you. I'm not sure. Look for help generally on this issue of not being provisioned a external IP for a LoadBalancer service on EKS.

**Comment by mrachakonda** [comment]
@consideRatio  I followed your comments. So you are saying proxy-public will never get external ip for load balancer. Is that right? If yes there is any work around?

**Comment by BertR** [comment]
@kumarasenthil which Ingress controller do you have installed on your EKS cluster?

**Comment by consideRatio** [comment]
@mrachakonda I only know that you are supposed to get one, and if you don't, it relates to your Kubernetes setup. And I assumed EKS would mean that you got it setup automatically to a good functional state with this functionality included, but apparently not, so I'm a bit surprised about that.

It does not relate specifically to this Helm chart or JupyterHub though.

**Comment by chicocvenancio** [comment]
I have successfully deployed jupyterhub in eks and it does provision ELB for LoadBalancer services. `kubectl describe` on the service might give an idea of what is going on. Failing that I would investigate the nodes and the master plane logs (in CloudWatch for EKS).

**Comment by kumarasenthil** [comment]
Thanks guys! I followed what was mentioned by @BertR and got the below
![image](https://user-images.githubusercontent.com/55604143/68739783-942d5200-05e1-11ea-88fb-a53aaa230dbd.png)

Still I dont get the external-ip for proxy-public:
![image](https://user-images.githubusercontent.com/55604143/68739830-b2934d80-05e1-11ea-930b-155ceab7bd49.png)

@consideRatio  I second you! When I created my EKS cluster on AWS I thought it should set up ALB automatically, but looks like it didnt!

@chicocvenancio  Can you please help here? How did you create the EKS cluster - I did it through Terraform.

**Comment by kumarasenthil** [comment]
Also I came across this page on aws documentation: https://docs.aws.amazon.com/eks/latest/userguide/alb-ingress.html

This mentions subnet-tagging and few more steps for ingress controller setup. Should I follow this?

**Comment by kumarasenthil** [comment]
@chicocvenancio 
Here is the output of thekubectl describe service proxy-public -n jhub
![image](https://user-images.githubusercontent.com/55604143/68818126-e1f69880-067b-11ea-888d-cc685e57c0d6.png)

**Comment by chicocvenancio** [comment]
@kumarasenthil there seems to be missing output on the bottom from that screenshot.
From that message, I'm guessing it may be a failure of aws creating the ELB, perhaps https://eksworkshop.com/deploy/servicerole/ might help.

**Comment by chicocvenancio** [comment]
Maybe `kubectl -n jhub get events` can give you the full error messages.

**Comment by salvis2** [comment]
In case others have some problems similar to this, I've found 2 potential causes.

1. You accidentally put the Kubernetes cluster and control plane in private subnets only (no public subnets). This prevents the ELB from getting an external IP. Learned that [here].(https://stackoverflow.com/a/59059504/12771569)

2. Your config.yml file that you deploy the JupyterHub with contains a block like 

```YAML
proxy:
  service:
    loadBalancerIP: "REPLACE"
```

This is from my own testing. The output of `kubectl describe svc proxy-public -n jhub` was

```
Name:                     proxy-public
Namespace:                jhub
Labels:                   app=jupyterhub
                          chart=jupyterhub-0.9.0-beta.3
                          component=proxy-public
                          heritage=Helm
                          release=jhub
Annotations:              <none>
Selector:                 component=proxy,release=jhub
Type:                     LoadBalancer
IP:                       10.100.156.121
IP:                       REPLACE
Port:                     https  443/TCP
TargetPort:               443/TCP
NodePort:                 https  32104/TCP
Endpoints:                192.168.110.123:443
Port:                     http  80/TCP
TargetPort:               8000/TCP
NodePort:                 http  32143/TCP
Endpoints:                192.168.110.123:8000
Session Affinity:         None
External Traffic Policy:  Cluster
Events:
  Type     Reason                      Age                  From                Message
  ----     ------                      ----                 ----                -------
  Normal   EnsuringLoadBalancer        3m59s (x9 over 19m)  service-controller  Ensuring load balancer
  Warning  CreatingLoadBalancerFailed  3m59s (x9 over 19m)  service-controller  Error creating load balancer (will retry): failed to ensure load balancer for service jhub/proxy-public: LoadBalancerIP cannot be specified for AWS ELB
```

The last line indicates the problem. Removing the config block listed above causes the LoadBalancer to get an external IP address just fine.

**Comment by Metagogy** [comment]
root@Kubernetes-jupyter:~# kubectl get service --namespace jhub
NAME           TYPE                  CLUSTER-IP       EXTERNAL-IP      PORT(S)                             AGE
hub                ClusterIP            10.245.138.35       <none>                8081/TCP                           154m
proxy-api       ClusterIP            10.245.174.251      <none>               8001/TCP                           154m
proxy-public   LoadBalancer    10.245.225.9     159.65.211.114  443:30994/TCP,80:30665/TCP 154m

i type the external ip in browser but still it is not happening

Any solutions?

**Comment by consideRatio** [comment]
The original issue of a pending IP relate to the k8s cluster needs a controller that can manage a k8s Service of type: LoadBalancer, which may need to be manually installed. I think MetalLb is such for example.

I'm closing this, but there is a note about the need to help users setting up bare metal clusters lacking a LoadBalancer controller and such.
