### ISSUE TITLE
Make readiness and liveness configurable

### ISSUE THREAD

**Issue by mrow4a** [jupyterhub/zero-to-jupyterhub-k8s#1479]
Currently readiness probe for hub is enabled by default, and liveness probe is disabled. I suggest in this draft commit https://github.com/jupyterhub/zero-to-jupyterhub-k8s/compare/master...mrow4a:fix_probes to make it configurable in the chart, for few reasons:
- to support with chart 0.9.0 JH <1.0.0
- sometimes it might be desirable to enable/disable certain probes (e.g. liveness)
- issues like https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1357
- these probes as part of separate alerting system

@consideRatio any opinion?

**Comment by consideRatio** [comment]
I think I'd like to see them be made configurable as well!
