### ISSUE TITLE
Deleting AWS stacks fails

### ISSUE THREAD

**Issue by arokem** [jupyterhub/zero-to-jupyterhub-k8s#148]
It seems that it might be related to this issue: 

https://stackoverflow.com/questions/19423295/deleting-cloudformation-vpc-stack-without-disassociating-the-elastic-ip-causes-d

IIUC, this might be a bug in the way that Heptio sets up the template we are using (need to specify dependencies between AWS resources, so that they get cleaned up properly on deletion)

**Comment by arokem** [comment]
For the time being, a workaround is to find the network interface(s) associated with the stack (in the EC2 console), and to delete the interfaces manually, before deleting the stack through the Cloudformation interface. 

Under the VPC console => "Subnets" => fine the Public subnet associated with your stack. When you attempt to delete that ("subnet actions" => "delete subnet"), you should see a pop-up that tells you that the subnet cannot be deleted until the public interfaces associated with the subnet are deleted, and it contains a link to these interfaces. Clicking on this link will take you to the EC2 console, where you can detach  these interfaces and then delete them

In total, you will need to the following steps: first detaching these public interfaces, then deleting them, and then detaching/deleting the subnets, and finally deleting the VPC, before you can successfully delete your stack from the cloudformation console.

**Comment by choldgraf** [comment]
Did this ever get resolved?

**Comment by arokem** [comment]
Not as far as I can tell, but thank you for reminding me that I needed to go through this entire thing again for the stack I created for last week!

**Comment by willingc** [comment]
FYI https://github.com/heptio/aws-quickstart/blob/master/troubleshooting.md#quick-start-cloudformation-stack-does-not-delete-properly

**Comment by choldgraf** [comment]
nice catch! @yuvipanda it looks like if you create "extra" resources on top of the heptio basic setup, it causes problems with tearing down the cluster. What kinds of stuff does the helm chart set up that could fall into this category?

**Comment by yuvipanda** [comment]
That would probably be the EBS volumes, where each user gets their own.

**Comment by choldgraf** [comment]
@arokem can you try deleting the persistent volumes and see if that lets you delete the cluster?

**Comment by consideRatio** [comment]
Id like to see a concrete action plan or that we close this issue, say in a week from now?

**Comment by consideRatio** [comment]
Closing this as outdated and too hard too follow up on at this point.
