### ISSUE TITLE
Missing page link - ways to set up a cluster

### ISSUE THREAD

**Issue by raybellwaves** [jupyterhub/zero-to-jupyterhub-k8s#1494]
On https://zero-to-jupyterhub.readthedocs.io/en/latest/create-k8s-cluster.html clicking the link 'ways to set up a cluster' gives a 404 (https://kubernetes.io/docs/setup/pick-right-solution/).

Found a webpage here but it is not up to date https://v1-13.docs.kubernetes.io/docs/setup/pick-right-solution/

The code is here https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/doc/source/create-k8s-cluster.rst

**Comment by choldgraf** [comment]
Hmmm - @consideRatio I don't believe that this comes from the documentation refactor, it's a link out to the official kubernetes docs. That page seems to have moved? I'm not quite sure what'd be the best new version of that page

https://kubernetes.io/docs/setup/pick-right-solution/

**Comment by consideRatio** [comment]
Ah, thanks for helping figure that out, sorry for offloading this on you like that! Ill look into it!

**Comment by consideRatio** [comment]
From https://github.com/kubernetes/website/pull/14468 I learned that https://kubernetes.io/docs/setup/ makes sense to reference instead! A PR to fix it is appreciated! :heart:

**Comment by raybellwaves** [comment]
Will do after the holidays
