### ISSUE TITLE
suggestion of updating docs for az account set -s

### ISSUE THREAD

**Issue by raybellwaves** [jupyterhub/zero-to-jupyterhub-k8s#1495]
Currently going through https://zero-to-jupyterhub.readthedocs.io/en/latest/microsoft/step-zero-azure.html

A (very) small stumbling point for me was https://github.com/Azure/azure-cli/issues/7304#issuecomment-420797466

If you think it is worthwhile I could update this line of the docs (https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/doc/source/microsoft/step-zero-azure.rst#L60) to be

`az account set --subscription "YOUR-CHOSEN-SUBSCRIPTION-NAME"`

**Comment by consideRatio** [comment]
It appears that @sgibson91 has already resolve this in https://github.com/jupyterhub/zero-to-jupyterhub-k8s/commit/ba784d7bfc1143835c19b617b1a2ec67dda9023d :heart: :tada: :sunflower:!! I love when this is how I get to close an issue!
