### ISSUE TITLE
Helm3 compatibility

### ISSUE THREAD

**Issue by scottyhq** [jupyterhub/zero-to-jupyterhub-k8s#1497]
Opening an issue to track compatibility of z2jh chart and deployment instructions with the latest stable release of helm (v3): 

https://github.com/helm/helm/releases/tag/v3.0.0
https://helm.sh/docs/faq/
https://helm.sh/blog/migrate-from-helm-v2-to-helm-v3/

I think the most important things to be aware of are that 1) tiller is no longer part of helm and 2) helm2 support and the stable chart repository is going away on a 6mo to 1yr timeframe (https://helm.sh/blog/2019-10-22-helm-2150-released/#helm-2-support-plan).

This issue also has a corresponding discourse post:
https://discourse.jupyter.org/t/suggestion-to-remove-tiller-pods-on-k8s-clusters-helm3-discussion/2531 

Some specific questions/tasks:
- [] Identify changes in this repository to be compatible with helm3 / chart apiVersion: v2
- [] In the meantime should probably restate requirements on the documentation landing page:
"This version of the chart requires kubernetes ≥1.11 and helm ≥2.11"

**Comment by manics** [comment]
I've been deploying BinderHub (which depends on this project) using Helm 3 without issues, no changes were needed to the charts. Main change when it comes to deployment is creating the namespace in advance.

I think the hardest part will be testing upgrades from Helm 2 to 3.

**Comment by consideRatio** [comment]
there is an issue in chartpress as well relating to helm 3. The versions with .005. etc in it has leading zero and is a fully numeric version, snd that is invalid SemVer, and helm3 sometime complains, for example when using the chart as a dependency.

I have a PR to fix solve it.

**Comment by KLdivergence** [comment]
According to [helm blog](https://helm.sh/blog/helm-v3-beta/). If user are using helm v3, the "helm init" steps in the [doc](https://zero-to-jupyterhub.readthedocs.io/en/latest/setup-jupyterhub/setup-helm.html) will no longer be needed. I can adding notes to that steps if you think that is necessary.

**Comment by manics** [comment]
We've got a Helm 3 doc: https://zero-to-jupyterhub.readthedocs.io/en/latest/setup-jupyterhub/setup-helm3.html
PRs to improve that or any other doc are always welcome!
