### ISSUE TITLE
add gcloud free tier limitations

### ISSUE THREAD

**Issue by aculich** [jupyterhub/zero-to-jupyterhub-k8s#150]
When mentioning the free credits here: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/doc/source/create-k8s-cluster.rst

We should also mention the free tier limitations (which limits the total number of users the cluster can support using purely the free $300 credits, depending on the configs in the `config.yaml`).

https://cloud.google.com/free/docs/frequently-asked-questions#limitations

> What limitations does the free trial have?
> 
> Google Compute Engine limitations
> 
> During the free trial, your project can have no more than 8 cores (or virtual CPUs) running at the same time.
> 
> For example, you can launch eight n1-standard-1 machines, or two n1-standard-4 machines, but you cannot launch a n1-standard-16 machine because the machine would have 16 vCPUs, which is more than 8 vCPUs. Similarly, you cannot launch an n1-standard-1 and an n1-standard-8 machine, because that would mean 9 vCPUs in the project. To run more than 8 vCPUs at a time, you must upgrade your account.
> 
> For more information about the types of virtual machines available and the number of cores they use, see Machine type pricing.

https://cloud.google.com/container-engine/pricing#a_note_about_kubernetes_master_nodes

> 
> A note about Kubernetes master nodes
> 
> If you're coming to us from the open-source Kubernetes project, you're used to the master node running on an additional machine instance. Google Container Engine abstracts away the existence of the master; it doesn't count as an instance for the purpose of pricing.

**Comment by willingc** [comment]
> We should also mention the free tier limitations

An excellent suggestion. Thanks @aculich.
