### ISSUE TITLE
Missing page link for methods to install Helm

### ISSUE THREAD

**Issue by raybellwaves** [jupyterhub/zero-to-jupyterhub-k8s#1507]
On the site https://zero-to-jupyterhub.readthedocs.io/en/latest/setup-jupyterhub/setup-helm.html

The text 'While several methods to install Helm exists,' points to https://github.com/helm/helm/blob/master/docs/install.md which is missing

Should it be https://github.com/helm/helm#install? or perhaps better https://helm.sh/docs/intro/install/

doc source: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/doc/source/setup-jupyterhub/setup-helm.rst#L28

**Comment by consideRatio** [comment]
Thanks! It should be https://helm.sh/docs/intro/install/ - want to help close this excellent clearly described issue with a PR fixing it? :heart: :sunflower:

**Comment by consideRatio** [comment]
Wieee two issues in a row that I can close happily saying they are resolved already! Thank you @GeorgianaElena for your work on this so that we now recommend Helm 3 by default! :heart: :tada: :sunflower:!!!
