### ISSUE TITLE
Missing page link for our RBAC documentation

### ISSUE THREAD

**Issue by raybellwaves** [jupyterhub/zero-to-jupyterhub-k8s#1508]
On
https://zero-to-jupyterhub.readthedocs.io/en/latest/setup-jupyterhub/setup-helm.html#initialization
Step 2 says '...See our RBAC documentation for more information'. The page points to https://zero-to-jupyterhub.readthedocs.io/en/latest/setup-jupyterhub/security.html#use-role-based-access-control-rbac
which is missing.

doc source: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/doc/source/setup-jupyterhub/setup-helm.rst#L63

**Comment by consideRatio** [comment]
It should be pointing to https://zero-to-jupyterhub.readthedocs.io/en/latest/administrator/security.html#use-role-based-access-control-rbac ! Thanks for catching and reporting these issues!
