### ISSUE TITLE
Feature request: update docs for helm3

### ISSUE THREAD

**Issue by raybellwaves** [jupyterhub/zero-to-jupyterhub-k8s#1509]
https://zero-to-jupyterhub.readthedocs.io/en/latest/setup-jupyterhub/setup-helm.html

https://v3.helm.sh/docs/topics/v2_v3_migration/

**Comment by manics** [comment]
Helm 3 docs were added in https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1543
