### ISSUE TITLE
Links in z2jh "customizing/user-management" documentation points to empty resource

### ISSUE THREAD

**Issue by n3o-Bhushan** [jupyterhub/zero-to-jupyterhub-k8s#1511]
Link in https://zero-to-jupyterhub.readthedocs.io/en/latest/customizing/user-management.html#authenticating-users documentation is broken.

**Comment by n3o-Bhushan** [comment]
Fixed in #1510

**Comment by consideRatio** [comment]
Awww... We failed :p .html is missing.

Crap ;§

**Comment by n3o-Bhushan** [comment]
Lol, I will push new changes

**Comment by n3o-Bhushan** [comment]
@consideRatio There you go  #1512

**Comment by n3o-Bhushan** [comment]
I think this can be closed now.
