### ISSUE TITLE
 Redirect loop detected. Notebook has jupyterhub version 1.0.1dev, but the Hub expects 1.0.0.

### ISSUE THREAD

**Issue by chaoyangfan-lgi** [jupyterhub/zero-to-jupyterhub-k8s#1521]
Help!

I deployed Jupyterhub as a container. After the following setting, when I start the single user server I got the error. I check the version.

The JupyterHub image: jupyterhub/jupyterhub 1.0.0

In the image it generates: jupyterhub/singleuser:1.0

```
./jupyterhub --version 
1.0.1dev
```

I can not access the single use server.

### My configuration

```python
# This is the address on which the proxy will bind. Sets protocol, ip, base_url
c.JupyterHub.bind_url = 'http://$IP'
# use LDAP as the authenticator
c.JupyterHub.authenticator_class = 'ldapauthenticator.LDAPAuthenticator'
c.LDAPAuthenticator.server_address = '@URL'
c.LDAPAuthenticator.server_port = 636
c.LDAPAuthenticator.bind_dn_template = 'uid={username},ou=People,dc=**,dc=**'
c.JupyterHub.spawner_class = 'dockerspawner.DockerSpawner'
```

**Comment by consideRatio** [comment]
I think the images you are using are unrelated to this Helm chart, and that cause issues. The images we use in this Helm chart are identified here:

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/5df3b123894bff4751684fdb91e7a719eda2268c/jupyterhub/values.yaml#L48-L50

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/5df3b123894bff4751684fdb91e7a719eda2268c/jupyterhub/values.yaml#L296-L298
