### ISSUE TITLE
Deploying k8s to Azure does not automatically obey Network Policies

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/zero-to-jupyterhub-k8s#1526]
As we have discovered in https://github.com/jupyterhub/mybinder.org-deploy/issues/1154#issuecomment-564277002, network policies defined in helm charts won't automatically be obeyed as expected when using a k8s cluster on Azure.

To enforce this, the k8s cluster needs to be deployed into a vnet with network policies enabled. Currently, this must be done at the deployment stage and cannot be retroactively applied to existing clusters.

I can contribute some documentation on how to set up a vnet with network policies and deploy the cluster into it 🙂

**Comment by consideRatio** [comment]
@sgibson91 yepp!

Kubernetes does not by default come with something, called a controller, that enforces what is described in k8s networkpolicy resources. On GKE you can get that automatically installed if you press something similar in the k8s cluster setup.

For the documentation, it should be a general note about this alongside specific cloud provider implementation details on how to go about setting up a controller that can enforce the policies.
