### ISSUE TITLE
503: service unavailable

### ISSUE THREAD

**Issue by cslovell** [jupyterhub/zero-to-jupyterhub-k8s#1528]
Jupyterhub is configured and working nicely for all users. Occasionally though, one of the users will reach the following error: 

![503-service-unavailable](https://user-images.githubusercontent.com/6457695/71259714-11e22d00-2307-11ea-9379-a7f7489fe24d.PNG)

His pod is not running, and there are no errors in the pods. It is unclear how we can clear this error and restart his notebook. 

![status](https://user-images.githubusercontent.com/6457695/71259713-11e22d00-2307-11ea-80f4-b719dc578fde.jpg)

**Comment by consideRatio** [comment]
Try capture the logs of the hub when you notice this happening. Also a question right away, did this happen in conjunction with a long time of inactivity, or by doing something very compute intensive that may have caused a out-of-memory kind of eviction of the pod?

**Comment by cslovell** [comment]
Thanks for the fast reply. Here is the logs for this user over the two hours where things seemed to be working, then weren't anymore.

I've reached out to the user to see what s/he was doing when this happened--will update. Thanks again.

[james-bond-logdump.txt](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/files/3988763/james-bond-logdump.txt)

**Comment by cslovell** [comment]
If I wanted to get this started for him again, would it simply be enough to restart the hub?

**Comment by consideRatio** [comment]
@cslovell I know too little about what version is used, but yes that is a good measure in 0.8.2 for example, while in the latest development release you may not need to do anything.

From the logs, it seems you the hub cull's the user for being inactive after 24 something minutes. This is configurable, I'd make it a longer duration for most deployments of a jupyterhub I can imagine. 1 hour perhaps ? Aside from that, there seemed to be an issue on shutting the pod down, I don't know why, and the hub entered a problematic state, I'm not 100% about this.

If you are using an old version of the chart though, I think various parts are resolved. Please use the latest development version of the chart (https://jupyterhub.github.io/helm-chart/) and report back if issues persist. I don't think there should be an issue to upgrade from 0.8.2 - we test for that to some degree at least.

**Comment by cslovell** [comment]
Excellent, I'll give that a shot. I'm on 0.9-03215dd for the moment. I'll look into 0.9.0-alpha.1.095.3e95dc3 as it's the latest version. Definitely will look into configuring the culling to at least one hour.

**Comment by cslovell** [comment]
Got it working - upgrading seemed to have worked. I've upped the culling to be a bit longer than an hour. I'll try to work with the analyst to see what happened. And by the way, great job with this project--we're all very grateful for it.

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/weve-been-seeing-503s-occasionally-for-user-servers/3824/2

**Comment by cameronraysmith** [comment]
> This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:
> 
> https://discourse.jupyter.org/t/weve-been-seeing-503s-occasionally-for-user-servers/3824/2

Yes in particular the attached log.

[jamesbond-inactive-to-503-hub-interface.txt](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/files/4908032/jamesbond-inactive-to-503-hub-interface.txt)

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/gke-503-service-unavailable-your-server-appears-to-be-down-try-restarting-it-from-the-hub/13465/1

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/gke-503-service-unavailable-your-server-appears-to-be-down-try-restarting-it-from-the-hub/13465/1
