### ISSUE TITLE
Document usage of multiple replicas of hub/proxy pod not yet supported

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#1537]
In #1536 it became clear that we should make it more clear that it wont work reliably to use more than one hub or more than one proxy pod. Im not sure how, for starters the values.yaml should have some note about it i think. If the schema.yaml dont mention it and it is documented there, that should be fixed also.

**Comment by metonymic-smokey** [comment]
@consideRatio wanted to try and take a crack at this issue.
Some brief pointers on where in the docs to add the information would be helpful!

Thanks!

**Comment by consideRatio** [comment]
Summarized in the issue triage report.
