### ISSUE TITLE
How to install/update package for the default environment?

### ISSUE THREAD

**Issue by moriwang** [jupyterhub/zero-to-jupyterhub-k8s#1538]
Hello, I'am a python TA and a former The littlest jupyerhub(TLJH) user. I used to install package in the default environment  using `sudo -E `, then students have the same environment. That's really convenient.

Recently, I install the Z2JH system in my k8s cluster to server more students. But I have no idea about how to install package in Z2JH's default environment. 
* I have a admin user in Z2JH
* The cluster use a NFS storageclass for PVC. 

First I installed package as the old way `sudo -E`, it ask me a password for jovyan like this
```
[sudo] password for jovyan:
```
I didn't find this mentioned in document anywhere. 

So I could only install package with the normal way `pip install & conda install`, everything I installed will gone when I reopen the workspace.

I'm asking a way to install packages for the default environment, thus the new system can act like old one. Besides, the version of jupyterlab is also too old(0.34), I wonder if I can upgrade it.

Thanks a lot.

**Comment by moriwang** [comment]
Oh, I see. I need to create a Dockerfile with my desired packages, and use helm command to update. Is that right?
But is that meaning I need to update the manually, or it can upgrade automatically when I update my Dockerfile?

**Comment by consideRatio** [comment]
> Oh, I see. I need to create a Dockerfile with my desired packages, and use helm command to update. Is that right?

You need to build and make a docker image available for kubernetes. You can do it by creating a new Dockerfile that you `build` and `push` and then update the config.yaml file under singleuser.image with the new image location, if it is a private image registry additional stuff needs doing as well.

> But is that meaning I need to update the manually, or it can upgrade automatically when I update my Dockerfile?

You can manually automate that, but it isnt something in the scope of the z2jh-guide to help with other than perhaps on a concept level. Doing this requires some insight about  Git, CI/CD, docker, kubernetes, and helm, all together.

**Comment by moriwang** [comment]
> You need to build and make a docker image available for kubernetes. You can do it by creating a new Dockerfile that you `build` and `push` and then update the config.yaml file under singleuser.image with the new image location, if it is a private image registry additional stuff needs doing as well.

It works, thanks for your reply.

Kubernetes is really a new technology for me. I deployed z2jh on my own pc k8s cluster, not gcp or aws etc, things is much harder without mannual. I stuck on how to deploy a nfs storage as a storageclass for a long time, and finally I did it. I suggest that the z2jh document can be more helpful if it contains more detail on nfs storageclass even deploy on bare metal.

**Comment by consideRatio** [comment]
I agree, it is very hard to maintain it all though so it is up to date. Anything added ought to be maintained to some degree. I like the idea of having some pointers on bare metal clusters and storage option overview perhaps, without going into the details. 

Personally i dont have experience up a bare metal cluster or my own NFS server yet.

**Comment by erinfry6** [comment]
I'm having the same problem. I understand how to create a new Docker image with the additional libraries, but I'll be deploying JupyterHub to a large group of people, at least some of which I would like to be able to install their own python packages and not have to go through me! Do we know the jovyan password? Is there a less maintenance-heavy solution? 

Thanks!

**Comment by consideRatio** [comment]
Users will need to install it in their home directories for their dependencies to persist in a z2jh deployment.

The z2jh has some documentation about conda environments and nb_conda_kernels etc, try find it! I write from mobile so i have a hard time browsing it for you. Note that this has now stopped being a programmer language agnostic discussion, as conda environments wont solve everything etc!

**Comment by consideRatio** [comment]
If you want to have sudo to install packages with apt-get, they also wont persist unless they reside in the user home directory as i dont think they will. So, there is no easy fix in general here.

**Comment by jtlz2** [comment]
@consideRatio I am trying to install dependent packages in a singleuser instance but in order to run `sudo apt-get` (there does not seem an easy way without sudo) I need a root password (there does not seem an easy way with sudo). Is there a way to do this post-hoc? Or must everything be baked in to the image/helm chart, and if so how? Thanks!

**Comment by consideRatio** [comment]
Closing this but have added the request for documentation on NFS, storageClass, and bare metal clusters in my issue triage report.
