### ISSUE TITLE
Broken links in installation guides

### ISSUE THREAD

**Issue by metonymic-smokey** [jupyterhub/zero-to-jupyterhub-k8s#1547]
There are a few broken Edit this Page links, which on clicking lead to a 404 error.

The ones I've found till now are:
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/edit/master//index.rst
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/edit/master//google/step-zero-gcp.rst
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/edit/master//microsoft/step-zero-azure-autoscale.rst
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/edit/master//amazon/step-zero-aws.rst
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/edit/master//amazon/step-zero-aws-eks.rst
and a few more on the same setup page.

As far as I know, these should redirect to a page similar to [this](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/edit/master/doc/source/google/step-zero-gcp.rst).

**Comment by metonymic-smokey** [comment]
@consideRatio @willingc is this a documentation issue that you would like fixed shortly?
If so, could I send in a PR for the same?

New to z2jh so would appreciate any pointers for the same!
Thanks!

**Comment by consideRatio** [comment]
@metonymic-smokey I like all issues to be fixed shortly haha, if you can help out with this that would be great :heart:

Hey I remember now reading your question on Gitter about contributing but I forgot to answer at that time! Looking back at my journey, I think I have got myself onboarded into various repositories in the JupyterHub realm by reviewing others code in PRs. Sometimes I review PRs even though I don't know enough to do it efficiently, but it often leads to me learning a lot and when I someone ask a question in a PR regarding the code changes etc, it often leads to a better implementation in the end, it also tends to help the person submitting the PR to get it merged.

I've recently spent time considering #1539 quite a lot, and while doing so I learned more useful knowledge as I often end up doing reviewing PRs! This repo has been a goldmine of learning for me, it has felt very meaningful to contribute to this project as it is used for education/research etc that I care deeply about.

I greatly appreciate your work @metonymic-smokey! Perhaps I could request your eyes on a PR here and there going onwards?

:heart: :tada:

**Comment by willingc** [comment]
Thanks for the report @metonymic-smokey and offer to work on a PR. Looking at the links you provided, I see a `//` in the URL after the `master` directory. This leads me to believe that it may be an issue with the URL parser in Sphinx or the theme. cc/ @choldgraf just in case you have seen this before.

**Comment by choldgraf** [comment]
Ah good question, let me look at the theme a bit and see if that could be the issue

**Comment by metonymic-smokey** [comment]
@consideRatio thanks a lot! Will keep your tips in mind in future!

**Comment by choldgraf** [comment]
Hey all - I think I figured out what was going wrong with this theme, and I've opened an issue about it here:

https://github.com/pandas-dev/pydata-bootstrap-sphinx-theme/issues/76

In the mean-time, we could fix the problem by adding the configuration for the 'edit this page' button, following the instructions here: https://pandas-sphinx-theme.readthedocs.io/en/latest/user_guide/configuring.html#add-an-edit-this-page-button

If we *don't* want that button, we'll need to wait until a patch makes its way into the theme docs to disable the button by default.

**Comment by metonymic-smokey** [comment]
@choldgraf thanks a lot for your inputs!

I've tinkered around a bit and fixed the broken links by : 
* changing my conf.py according to the fix you have linked above.
* changing the `__init__.py` file in the pandas_sphinx_theme folder by removing the extra `/` and adding `source` after the documentation path.

This struck me as quick solution(if I may call it) when I compared the 2 URLs.
Wanted to know your take on the same.

Thanks!

**Comment by choldgraf** [comment]
I believe that all we'd need to do is add the proper configuration values to the `conf.py` file (in this case, the `doc_path` keyword). Then the "edit this page" URLs would be properly created...

**Comment by metonymic-smokey** [comment]
@choldgraf agreed, what I'd tried was just a stop-gap for a short term fix(and admittedly a convoluted one).

Regarding changing `doc_path` in `conf.py`, changing it to `doc/source` in `html_ context` also fixes the links. 

Thanks!

**Comment by consideRatio** [comment]
Thank you @metonymic-smokey for your work on #1564! :heart: :tada:!
