### ISSUE TITLE
Develop a Z2JH Grafana dashboard for use with prometheus

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#1566]
## A primer of the situation

Grafana is a tool to visualize data in graphs and organize them into dashboards.

![image](https://user-images.githubusercontent.com/3837114/73722830-b5589700-4727-11ea-862f-07eab1a54a54.png)

Grafana reads from various types of data sources, and among them is a Prometheus data source.

Prometheus has the job to repeatedly ask the question "hello, you indicated you have numbers for me, what are the numbers right now?". And this is how we help Prometheus know JupyterHub in our z2jh deployment has such numbers.

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/63a3bf9679ce3cb231d7f1808e1b1ef5bcc7cb65/jupyterhub/templates/hub/service.yaml#L8-L13

And this is how the typical endpoint at /hub/metrics responds when asked:

```
...
# HELP running_servers the number of user servers currently running
# TYPE running_servers gauge
running_servers 1.0
# HELP total_users total number of users
# TYPE total_users gauge
total_users 413.0
# HELP check_routes_duration_seconds Time taken to validate all routes in proxy
# TYPE check_routes_duration_seconds histogram
check_routes_duration_seconds_bucket{le="0.005"} 19712.0
check_routes_duration_seconds_bucket{le="0.01"} 19718.0
check_routes_duration_seconds_bucket{le="0.025"} 19718.0
check_routes_duration_seconds_bucket{le="0.05"} 19719.0
check_routes_duration_seconds_bucket{le="0.075"} 19719.0
check_routes_duration_seconds_bucket{le="0.1"} 19719.0
check_routes_duration_seconds_bucket{le="0.25"} 19719.0
...
```

## My suggestion
We develop a dashboard that relies on this kind of information, and publish it on Grafana Labs, allowing anyone that want a dashboard of metrics for their Z2JH JupyterHub deployment get one if they also install grafana + prometheus and import this dashboard, which only describes what data to use etc.

Just like [@manics has done here](https://grafana.com/grafana/dashboards?search=jupyterhub), but by relying on the kubernetes api-server for information rather than JupyterHub itself.

**Comment by cslocum** [comment]
This is a great idea!  Would love to see this happen.

**Comment by mohammedi-haroune** [comment]
I came from google, I was looking for graphana dashboards but just found the one linked above that uses Kubernetes while we using the TLJH instead. I would love to see this happen.

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/towards-jupyterhub-deployment-insights/3836/1

**Comment by consideRatio** [comment]
I'll close this following @yuvipanda's excellent work which I think we should join with.

- https://discourse.jupyter.org/t/announce-grafana-dashboards-for-jupyterhub-on-kubernetes/7320
- https://github.com/yuvipanda/jupyterhub-grafana
