### ISSUE TITLE
Can we deploy jupyterhub in k8s without using helm chart?

### ISSUE THREAD

**Issue by saurav-bhagat** [jupyterhub/zero-to-jupyterhub-k8s#1568]
Inside my premise, I can't access the helm chart mentioned in the tutorial. Also, I can't download its zip. Is there any other way I can deploy jupyterhub to k8s?

**Comment by consideRatio** [comment]
Are you not able to access this file for example? https://jupyterhub.github.io/helm-chart/jupyterhub-0.9.0-beta.3.n023.h6a2b994.tgz

That the latest helm chart from https://jupyterhub.github.io/helm-chart/, which represents what you can get from following the tutorial on z2jh.jupyter.org. With Helm 3, you don't need `tiller` on the k8s cluster, and it can be as if you were only using `kubectl`. It is quite common to not be able to use `tiller` which is a part of Helm 2. If that is the blocker, your path should be Helm 3.

**Comment by saurav-bhagat** [comment]
I went through the helm chart and internally it's using some docker images which are also not accessible, I can only use internal repository. Is there any reference on how can I make this from scratch?  Using very basic jupyterhub image, nginx, kube spawnner and other tools?

**Comment by consideRatio** [comment]
You could build them yourself and then upload them, but that requires internet, or you can download and transfer them.

**Comment by saurav-bhagat** [comment]
Thanks you and Yes, I can upload it in my internal repository. But the thing is there is no dockerfile present in hub for images like jupyterhub/k8s and some other to take reference from. There should be some other way? No?

**Comment by consideRatio** [comment]
To build your own images for everything, you can use `chartpress` the CLI from within this repository, and that way you will also have updated some configuration of relevance of the chart automatically.

I don't have time to help you much further than this at the moment, but, I recommend the following:

1. Download this z2jh repository, and use `chartpress` within it to build the needed docker images and update the helm charts values.yaml file with references to these images. You may want to update the configuration file of chartpress called chartpress.yaml
2. Consider using jupyter/docker-stacks images, such as the jupyter/datascience-notebook image for individual user environments
3. If you have issues using `tiller` that is part of Helm 2 in your k8s cluster for privileges reasons, use Helm 3 instead.

**Comment by saurav-bhagat** [comment]
Okay. I'll try this. Thanks
