### ISSUE TITLE
Add gitlab_url trait to the chart

### ISSUE THREAD

**Issue by rprimet** [jupyterhub/zero-to-jupyterhub-k8s#1569]
Looking at the gitlab-specific configuration section in the chart ( https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/f14134c7ccfbb369333c2f44532d5af94c4423c6/jupyterhub/files/hub/jupyterhub_config.py#L287-L295 ), it seems that the `gitlab_url` trait is missing from the list of configurable gitlab-specific traits.

Adding it would allow configuring a custom gitlab instance without resorting to python snippets.

**Comment by metonymic-smokey** [comment]
@rprimet I'll make an attempt to figure this out.
From what I understood, you want the `gitlab_url` trait to be added to the existing traits like `gitlab_group_whitelist` and `gitlab_project_id_whitelist` right?
Is there anything I've missed?

**Comment by rprimet** [comment]
@metonymic-smokey Yes that's it!

**Comment by metonymic-smokey** [comment]
@rprimet I have a query about this issue.
In this WIP PR, I have used `None` as the `cfg_key` for the `gitlab_url` trait. I am not exactly sure if that's right/what value I should be using there.
Would love your inputs on the same!

Thanks!

**Comment by consideRatio** [comment]
Thanks @rprimet and @metonymic-smokey for reporting and fixing this!
