### ISSUE TITLE
Not able to downgrade helm chart version

### ISSUE THREAD

**Issue by naveenkatlle** [jupyterhub/zero-to-jupyterhub-k8s#1573]
Hi Team,

We have done JupyterHub setup by following Zero-to-JupyterHub steps (https://zero-to-jupyterhub.readthedocs.io/en/latest/setup-jupyterhub/index.html)

Now, we want to downgrade JupyterHub version to 0.8.2. For that, we executed Helm Upgrade command, with chart version v0.6.0. But we are getting below issue.

**CMD:**  helm upgrade jhub jupyterhub/jupyterhub  --namespace jhub   --version=v0.6.0   --values secret-config.yaml   --values config.yaml

`UPGRADE FAILED`
`Error: [unable to recognize "": no matches for kind "DaemonSet" in version "extensions/v1beta1", unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"]`
`Error: UPGRADE FAILED: [unable to recognize "": no matches for kind "DaemonSet" in version "extensions/v1beta1", unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"]`

Could you please help us in downgrading the JupyterHub version to 0.8

**Comment by manics** [comment]
Hi @naveenkatlle 
What version of K8s are you using? The kubernetes API can change between versions, so the 0.6.0 chart would've been developed against an older K8s version.
`DaemonSet` was dropped from `extensions/v1beta1` in 1.16: https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

**Comment by consideRatio** [comment]
Not sure how to help =/ Upgrading one minor version at the time is probably to be recommended in our docs regarding upgrades.
