### ISSUE TITLE
 TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by marcreyesph** [jupyterhub/zero-to-jupyterhub-k8s#1578]
I've used LDAP authenticator with the following configuration:
```yaml
ldap: 
  server:
    address: {ip_address}:{port}
  dn:
    lookup: True
    search:
      filter: '({login_attr}={login})'
      user: 'cn=readonly,dc=site,dc=com'
      password: '{password}'
      dnAttribute: 'cn'
    templates:
      - 'uid={uid},ou=people,dc=site,dc=com'
      - 'username={uid},ou=people,dc=site,dc=com'
      - 'cn={uid},ou=people,dc=site,dc=com'
    user:
      searchBase: 'o=<org_name>,dc=site,dc=com'
      escape: False
      attribute: 'uid'
      dnAttribute: 'cn'
```

Upon logging in got the following in log: 
```
[E 2020-02-19 11:28:30.821 JupyterHub web:1788] Uncaught exception POST /hub/login?next= (10.14.3.133)
    HTTPServerRequest(protocol='https', host='site.com', method='POST', uri='/hub/login?next=', version='HTTP/1.1', remote_ip='10.14.3.133')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1699, in _execute
        result = await result
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/login.py", line 81, in post
        user = await self.login_user(data)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py", line 483, in login_user
        authenticated = await self.authenticate(data)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/auth.py", line 257, in get_authenticated_user
        authenticated = await maybe_future(self.authenticate(handler, data))
      File "/usr/local/lib/python3.6/dist-packages/ldapauthenticator/ldapauthenticator.py", line 308, in authenticate
        resolved_username = re.subn(r"([^\\]),", r"\1\,", resolved_username)[0]
      File "/usr/lib/python3.6/re.py", line 202, in subn
        return _compile(pattern, flags).subn(repl, string, count)
    TypeError: expected string or bytes-like object
```

I tried logging in with the config above using [ldap3](https://ldap3.readthedocs.io/) and was able to successfully login. Would like to know what could possibly I have done incorrectly. Thanks!

**Comment by consideRatio** [comment]
What version of the z2jh helm chart did you install? It ships with different versions of the ldapauthenticator.

Could you install and try the helm chart version: `0.9.0-beta.3.n030.h796379e` ? It is the latest version with the latest LDAP authenticator that was recently bumped, and it is a lot more useful to debug the latest version.

**Comment by marcreyesph** [comment]
Thanks @consideRatio. Used the helm chart `0.9.0-beta.3.n030.h796379e` and got the following from the log:
```
I 2020-02-20 05:32:48.917 JupyterHub log:174] 200 GET /hub/health (@172.18.16.168) 0.71ms
[W 2020-02-20 05:32:49.223 JupyterHub ldapauthenticator:398] Invalid password for user 'Marc Anthony Reyes'
[W 2020-02-20 05:32:49.224 JupyterHub base:714] Failed login for marc.reyes
[I 2020-02-20 05:32:49.225 JupyterHub log:174] 200 POST /hub/login?next= (@127.0.0.1) 67.29ms
```

I'm pretty sure that my password is correct. What could possibly have I done incorrectly? Thanks.

**Comment by marcreyesph** [comment]
So I removed all the templates and was able to sign in (doesn't work if password is incorrect), however, the url of the spawner uses my full name not my username.

**Comment by consideRatio** [comment]
@marcreyesph, I know very little about LDAP, but the crux is probably to configure the ldapauthenticator correctly. Inspect this documentation: https://github.com/jupyterhub/ldapauthenticator

Sadly, to configure this in the helm chart isn't trivial at all due to lots of logic here: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/d7181a6cd03d88b7f91f5d4f1b60c10524970b39/jupyterhub/files/hub/jupyterhub_config.py#L334-L349

**Comment by marcreyesph** [comment]
Anyway, finally figured it guys. Thanks for all the help!
