### ISSUE TITLE
Option to always start the singleuser server when required

### ISSUE THREAD

**Issue by stevegore** [jupyterhub/zero-to-jupyterhub-k8s#1579]
Hi, we host a JupyterHub instance with a custom JWT authenticator that handles the `/login` endpoint and creates the user etc. 

However, we have users accessing direct links to notebooks. When they do so, no instance is spawned, and they are presented with the question: 

```
Server not running
Your server is not running. Would you like to start it?
```

They then have to click "Launch Server" before spawning begins.

We would like to avoid this happening. Ideally, the server would always start when required, without the user having to ever hit "Launch Server". Is this possible?

**Comment by betatim** [comment]
Closing because #2924 is probably the better place for this.
