### ISSUE TITLE
jupyterlab - HiveQL kernel shows No Kernel/Unknown on NFS mount

### ISSUE THREAD

**Issue by rajaharish79** [jupyterhub/zero-to-jupyterhub-k8s#1581]
We have deployed **jupyterhub on K8s** and successfully integrate HiveQL kernel to jupyterhub. But while we do NFS mount /home/jovyan files get **masked/overridden** by NFS mount. Due to which we are not able to see HiveQL in the launcher. But when we copied the files to different folder we are able to get HiveQL in the launcher. But on opening the HiveQL kernel, it says No Kernel and changes to Unknown in the status. We are not able to execute any queries in Hive QL kernel.

Any help or suggestion in this regard much appreciated,  

I have attached screen shot below.
![image](https://user-images.githubusercontent.com/46083216/75008745-d696e280-549e-11ea-8b97-9d718a991478.png)

**Comment by manics** [comment]
Hi @rajaharish79 
As you suggested it sounds like some files are being masked by the home directory mount. You could try mounting the NFS directory in a subdirectory such as `/home/jovyan/data`? Alternatively are you able to show us how you've created your single-user image, e.g. a link to a repo or Dockerfile- someone might be able to suggest a change.

**Comment by rajaharish79** [comment]
When I tried to do as manics suggested. By changing the mount path in jupyter yaml file. The pod home path changes but I am not able to see the files of NFS.
