### ISSUE TITLE
0.9.0-beta4

### ISSUE THREAD

**Issue by manics** [jupyterhub/zero-to-jupyterhub-k8s#1582]
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1561 and https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1563 are closed. Is there anything else required before `0.9.0-beta4` is tagged?
@consideRatio If you want I can have a go at tagging next week following your guide https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/RELEASE.md

**Comment by consideRatio** [comment]
Please have a go! Note the tag should be `0.9.0-beta.4`!

**Comment by hnykda** [comment]
Is it still true that if `0.9.0-beta.4` works fine we can get stable `0.9.0` :eyes: ? How long do you think it would take in the ideal scenario?

**Comment by manics** [comment]
Done! https://github.com/jupyterhub/zero-to-jupyterhub-k8s/releases/tag/0.9.0-beta.4

**Comment by consideRatio** [comment]
Thanks @manics !! ❤️
