### ISSUE TITLE
admin user ldap

### ISSUE THREAD

**Issue by astrajohn** [jupyterhub/zero-to-jupyterhub-k8s#1593]
If I try to set an admin user using ldap autheticator in the latest beta using:

name: 'auth.admin.users[0]'
value: id

traitlets.traitlets.TraitError: The 'admin_users' trait of a LDAPAuthenticator instance must be a set,
but a value of class 'str' (i.e. 'id') was specified.

worked in 0.9-ec3b97d, not sure where the regression comes from.

**Comment by manics** [comment]
Thanks for reporting this. Are you able to share your full z2jh configuration (with secrets redacted)? This will help us figure out what's changed since there are a number of interacting components that can affect auth handling.

**Comment by astrajohn** [comment]
Apologies. This actually works with standard config. I have been managing the installation with argocd and the errors relate to trying to set auth.admin.users[0] in the config. I think it may be more related to the values file of the helm chart or yaml parsing in argocd. Anyway, not a jupyterhub issue, closing.
