### ISSUE TITLE
which jupyterhub version is being pulled

### ISSUE THREAD

**Issue by henchc** [jupyterhub/zero-to-jupyterhub-k8s#160]
can we clarify here: https://zero-to-jupyterhub.readthedocs.io/en/latest/setup-jupyterhub.html#install-jupyterhub

That the `--version=v0.4 \` is the helm chart version and not the version for JupyterHub, and which version of JupyterHub is being pulled?

**Comment by choldgraf** [comment]
we should also clarify where in the helm chart it defines which version of jupyterhub to use. Esp since we tell people they need to use an image that corresponds to the jhub version used for that helm chart

**Comment by consideRatio** [comment]
Solved!

![image](https://user-images.githubusercontent.com/3837114/45002302-935c6180-afd5-11e8-90d1-9819a68a0025.png)
