### ISSUE TITLE
Add information on how to set up and access persistent logging

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/zero-to-jupyterhub-k8s#161]
Currently, with kubectl logs, you can see the logs of running pods. However, when the pod dies (because of a helm update, or user's pod is killed, etc) we can no longer access logs. This makes debugging very difficult on any reasonably sized system.

On most cloud providers, there's a managed service that stores and aggregates logs for searching. On Google, that is stackdriver (https://cloud.google.com/logging/docs/view/logs_viewer_v2). On AWS, that's CloudWatch. You can configure Kubernetes to send logs to these places, and many do by default - GKE sends them to stackdriver by default, for example. 

We need to:

1. Figure out how much of this detail we need to tell people
2. Figure out what to do for AWS, since the quickstart we are using does not seem to come with cloudwatch configured
3. Figure out where to put cloud specific info like this.

**Comment by yuvipanda** [comment]
@rdodev I couldn't really find any info on logging to cloudwatch from the quickstart based AWS stack. Most things on the internet recommend setting it via docker's logging driver, but that's not very easy to do across an autoscaling group of instances... What do you suggest we recommend people?

**Comment by danroliver** [comment]
kops seems to have it: https://github.com/kubernetes/kops/blob/master/vendor/github.com/docker/docker/docs/admin/logging/awslogs.md

I'll keep digging.

**Comment by yuvipanda** [comment]
I think temporarily, we might add a note to our docs suggesting people use kops if they want a fully productionized cluster, since I think it also supports upgrades.

**Comment by willingc** [comment]
PR #184 addressed the documentation of kops for production. Thanks @yuvipanda.

**Comment by rdodev** [comment]
As I've already mentioned in this thread, Quickstart is not supposed to be
used for production workloads. It's just not designed for anything other
than testing/evaluation.

**Comment by choldgraf** [comment]
cool - we appreciate the info! Just making sure what expectations to set for people using these guides!

**Comment by consideRatio** [comment]
Bump

**Comment by consideRatio** [comment]
Closing this as I consider it out of scope to maintain such documentation.
