### ISSUE TITLE
Update a python package for in the jupyterhub/k8s-hub:0.8.2 image

### ISSUE THREAD

**Issue by jchomarat** [jupyterhub/zero-to-jupyterhub-k8s#1613]
Hello,

I am perfectly happy with the latest stable hub container (version 0.8.2), the only thing I need is to update the library oauthenticator from version 0.8.0 to 0.11.*.

Do I need to create my own docker image, or can I run a pip install somehow from the config.yaml file used to create my K8S cluster (I am on AKS).

Thanks for your help!

**Comment by betatim** [comment]
I don't think you can trigger a command from `values.yaml`. I'd go with creating your own image.

**Comment by consideRatio** [comment]
0.9.0-beta.4 has it, I'd suggest to upgrade to that instead. If you do upgrade, and have https enabled, manually delete the deployment named autohttps first.

```
kubectl delete -n myjhnamespace deployment autohttps
```

**Comment by consideRatio** [comment]
To update the version manually, you have to rebuild the image, because there is no easy way provided to do something like installing a new version of oauthenticator before starting up jupyterhub itself.

**Comment by jchomarat** [comment]
Thanks for your answers!
@consideRatio, do you have a rough idea on when version 0.9 will become not beta?

**Comment by consideRatio** [comment]
I consider current beta stable enough for a release, so when me or someone else I find time to write changelog and upgrade instructions we can release. I'm aiming for this weekend, but I'm a bit overloaded with things to spend time on at the moment so no promises.

**Comment by jchomarat** [comment]
Sounds great, and I totally understand!
I am closing this then.
Thanks for your support
