### ISSUE TITLE
Cannot run as argocd application, hook-image-awaiter needs annotations

### ISSUE THREAD

**Issue by DanielLenzCS** [jupyterhub/zero-to-jupyterhub-k8s#1621]
Hi!

Thanks for making jupyterhub available on k8s, I've been really enjoying working with this package.

I've had no issues to do the direct `helm install` as described in the docs. However, when trying to run this as an app in argocd, the hook-image-awaiter fails with `Error creating: pods "hook-image-awaiter-" is forbidden: error looking up service account jupyterhub/hook-image-awaiter: serviceaccount "hook-image-awaiter" not found`.

I assume this is because of the way argocd converts helm hooks to argo hooks, as [they also recommend](https://argoproj.github.io/argo-cd/user-guide/helm/#helm-hooks) to:
- Annotate pre-install and post-install with hook-weight: "-1". This will make sure it runs to success before any upgrade hooks.
- Annotate pre-upgrade and post-upgrade with hook-delete-policy: before-hook-creation to make sure it runs on every sync.

Below is the live-manifest for the hook-image-awaiter; I'm not sure where the best place would be to add the configuration, and how to split the configuration for `pre-install` and for `pre-upgrade`.

Thanks for your help!

```
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: 'pre-install,pre-upgrade'
    helm.sh/hook-delete-policy: 'before-hook-creation,hook-succeeded'
    helm.sh/hook-weight: '10'
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"batch/v1","kind":"Job","metadata":{"annotations":{"helm.sh/hook":"pre-install,pre-upgrade","helm.sh/hook-delete-policy":"before-hook-creation,hook-succeeded","helm.sh/hook-weight":"10"},"labels":{"app":"jupyterhub","app.kubernetes.io/instance":"jupyterhub","chart":"jupyterhub-0.9.0-beta.4","component":"image-puller","heritage":"Tiller","hub.jupyter.org/deletable":"true","release":"jupyterhub"},"name":"hook-image-awaiter","namespace":"jupyterhub"},"spec":{"template":{"metadata":{"labels":{"app":"jupyterhub","component":"image-puller","release":"jupyterhub"}},"spec":{"containers":[{"command":["/image-awaiter","-ca-path=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt","-auth-token-path=/var/run/secrets/kubernetes.io/serviceaccount/token","-api-server-address=https://$(KUBERNETES_SERVICE_HOST):$(KUBERNETES_SERVICE_PORT)","-namespace=jupyterhub","-daemonset=hook-image-puller"],"image":"jupyterhub/k8s-image-awaiter:0.9.0-beta.4","imagePullPolicy":"IfNotPresent","name":"hook-image-awaiter"}],"restartPolicy":"Never","serviceAccountName":"hook-image-awaiter"}}}}
  creationTimestamp: '2020-04-09T15:12:27Z'
  labels:
    app: jupyterhub
    app.kubernetes.io/instance: jupyterhub
    chart: jupyterhub-0.9.0-beta.4
    component: image-puller
    heritage: Tiller
    hub.jupyter.org/deletable: 'true'
    release: jupyterhub
  name: hook-image-awaiter
  namespace: jupyterhub
  resourceVersion: '519666'
  selfLink: /apis/batch/v1/namespaces/jupyterhub/jobs/hook-image-awaiter
  uid: 22d91f72-122e-43fe-8842-94b1c554697b
```

**Comment by DanielLenzCS** [comment]
Just a quick update: I solved this simply by disabling the the prePuller in the values.yaml:

```
prePuller:
  hook:
    enabled:
        false
```

**Comment by chancez** [comment]
Id guess this is because argocd is ordering the hooks to run first and the service account doesn't have the same hook annotations so the SA is ordered after the hook which won't work if the hook is using the SA.

**Comment by DanielLenzCS** [comment]
I agree, it appears to come down to that.

I'm not sure whether a fix should be implemented on the jupyterhub or on the argoCD side. What's your take on that @chancez ? 

If this should be addressed by the argoCD team, then I'll close this issue and re-open it on their end.

Thanks!

**Comment by chancez** [comment]
You could probably just add the appropriate sync-wave/hook annotation to the serviceaccount such that it's created before the job.

**Comment by consideRatio** [comment]
It sounds like the need is to configure the applied annotations, rather than add custom annotations. I'll go ahead and close this issue as that seems like too much of an edge case. If we would implement it, I would suggest to let all the annotations be set in values.yaml, allowing users to override annotation keys with new values.

**Comment by richardotis** [comment]
I also ran into this issue and spent some time playing with the hook priorities. I had some luck getting the prepuller to work on ArgoCD by having all the resources associated with the image-puller set to a common hook priority of 10. You can see here: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/compare/jupyterhub:8d5503d...richardotis:2a71c21
You can play with it by setting your Argo App CR for jupyterhub like this:
```
  source:
    repoURL: https://github.com/richardotis/zero-to-jupyterhub-k8s.git
    path: jupyterhub
    targetRevision: fix-argocd
```

I hard-coded the chart version in that branch so I wouldn't have to run chartpress, but an actual PR wouldn't include those changes. I haven't tested to ensure that `helm install` of the chart still works, but I just wanted to point out we may be talking about a very small change needed here.

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/proxy-error-599-when-i-try-to-make-an-offline-installation/7003/1
