### ISSUE TITLE
Annotate image puller and awaiter

### ISSUE THREAD

**Issue by myelinproj** [jupyterhub/zero-to-jupyterhub-k8s#1627]
### Proposed change
It is not possible to add annotation to the image puller deployments.

### Who would use this feature?
This is useful for example deploying jupyterhub to an istio enabled namespace (where all pods are auto injected unless they are annotated)

Happy to submit a PR on this.

**Comment by consideRatio** [comment]
@myelinproj thanks for describing the use case! It was great to have when considering the PR @duongnt just created.

Thanks for your contributions to this project :heart:
