### ISSUE TITLE
build.py only builds jupyterhub, not binderhub

### ISSUE THREAD

**Issue by minrk** [jupyterhub/zero-to-jupyterhub-k8s#163]
build.py only builds the juptyerhub chart, not the binder one, which has independent versioning. Should we fix the two to the same version since they are in the same repo?

**Comment by yuvipanda** [comment]
Per https://github.com/jupyterhub/binderhub/pull/110#issuecomment-330628529 we should move all the binder related stuff out of here I think.

**Comment by choldgraf** [comment]
I think that's a good idea

**Comment by minrk** [comment]
👍
