### ISSUE TITLE
Allow external sources of secrets such as AWS Secrets Manager

### ISSUE THREAD

**Issue by witchbutter** [jupyterhub/zero-to-jupyterhub-k8s#1656]
### Proposed change

Several secrets are expected to be placed in the values.yaml file when using this chart, which means if you are using it as a dependency chart you would have to store plaintext secrets in your custom.yaml because helm cannot interpolate anything in the values.yaml file.

### Alternative options

Several wrapper plugins are being used with Helm to avoid secrets, but I would rather not use a wrapper on the helm binary and use instead the built in Kubernetes secrets resources.  In particular my implementation extends secrets with an  externalSecret resource allowing the use of external 3rd party secrets in the same format as built in Kubernetes secrets. -> https://github.com/godaddy/kubernetes-external-secrets

### Who would use this feature?

Everyone using external secrets tools like AWS Secrets Manager or Hashicorp Vault

### (Optional): Suggest a solution

I believe all we need is to extract certain secret objects so they can be included in a parent chart where the jupyterhub chart is a dependency chart.  Or maybe values.yaml could specify the name of a secret object that you have entered using kubectl or other means prior to the helm install of jupyterhub

**Comment by manics** [comment]
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1142 added support for an `existingSecret` in `hub`. Do you also need this in other components of the chart?

**Comment by witchbutter** [comment]
That addresses most of my issue.  It does not deal with the very strange secret that obfuscates the github secretkey when you use github auth, because AWS secrets manager cannot store a snippet of a yaml file as a secret.

If you run `kubectl get secrets hub-secret -o yaml` you find that hub-secrets contains a piece of the values yaml that decodes to something like this (I've replaced the value with a series of 0s):

```
user@host> echo $VALUES_YAML | base64 --decode
auth:
  github:
    clientSecret: 0000000000000000000000000000000000000000
hub:
  services: {}%
user@host>
```
The code that does this is in template > hub > secret.yaml.  It is the one thing I was not able to bypass.

**Comment by pachchigarsnehi** [comment]
I Had the same issue while I was setting up stuff on jupyterhub. What workaround we used is
in `values.yaml`  I placed something like this for secret values:
```
github:
     client: "XXX"
```
and when using `helm upgrade`
I used the command like - 
```
helm upgrade --install ......
-f values.yaml
--set `python getSecrets.py`
```
With `values.yaml` initially, the secrets will be `"XXX"`, but `-set` will override these values.
In the `python getSecrets.py` it will fetch secrets from `AWS secrets manager` and generate string in a way `auth.github.clientid=<fetched secret>`
This way, we avoid storing secrets and fetch it on the fly.
Not a native solution, but works well!

**Comment by consideRatio** [comment]
@witchbutter are you saying that you would like the K8s Secret resources rendered in templates by this Helm chart, to be rendered once, then installed, and then referenced by name in the future?

**Comment by consideRatio** [comment]
I understand the wish to not work with secret contents to be passed during helm template rendering, but instead reference something in the k8s cluster for example.

Here are a few of the ideas available to mitigate the issue:
1. hub.existingSecret - I think this tackles everything, but also include a compromise that isn't great because it can get out of sync as the Helm chart upgrades.
2. In the future with #1017 we can manual avoid management of a few secrets entirely.
3. `helm upgrade --reuse-values` is also available to rely on the previously passed values, that way you can set proxy.secretToken once for example.

I'll go ahead and close this issue now without a followup response and my own inability to translate this into a more concrete action point of something to change in the repo.
