### ISSUE TITLE
Ability to install packages/SUDO access or package injection

### ISSUE THREAD

**Issue by DarkBlaez** [jupyterhub/zero-to-jupyterhub-k8s#1672]
I'm going to call this out since many want to keep closing issues such as this. The work around is to rebuild a docker container to account for this ever changing requirement of installing packages. As you are aware that even "pip install <some package> might lead to a gcc rebuild being required. You have not accounted for such by locking down the container used omitting sudo capability. In essence the the rush to containerize and move to Kubernetes did not take in to consideration this standard use case. As such you are requiring a rebuild to include the packages in the base container. However, this is not an acceptable workaround. This precludes providing a level of flexibility which containers are to afford and deployment to Kubernetes. For each point that was mentioned I can easily address why the point is mute.

Simon Li you rushed to close the issue and divert me to https://discourse.jupyter.org/
This is not an end user issue so do not assume my level of experience or skills. As a seasoned developer and architect I am calling out the lack of consideration for an obvious use case for moving this to Kubernetes.

The base architecture is flawed but could easily allow the injection of packages without having to rebuild the container. 

I suppose I'll have to fork this and build out the solution since I suspect this will be swiftly closed

DB

**Comment by manics** [comment]
> In essence the the rush to containerize and move to Kubernetes did not take in to consideration this standard use case. 

This project is dedicated to running JupyterHub on Kubernetes. There are plenty of other ways to run JupyterHub, for example https://tljh.jupyter.org/en/latest/. In addition you can simply pip install JupyterHub in your own virtualenv with whatever spawner you want, or even extend your own spawner. If you're talking about something else can you please explain?

**Comment by consideRatio** [comment]
@DarkBlaezI I find you to not follow [Jupyter's code of conduct](https://github.com/jupyter/governance/blob/master/conduct/code_of_conduct.md).

We are a community of people trying to help each other out, if you want to be an active part of it you need to consider how your words influence others.

Here is my response that I gave before I saw this, it may be helpful to you: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1021#issuecomment-629468352
