### ISSUE TITLE
Microk8s 1.18 stable issues with zero-to-jupyterhub-k8s

### ISSUE THREAD

**Issue by goal86sg** [jupyterhub/zero-to-jupyterhub-k8s#1694]
Microk8s enabled with metallb registry dns storage
used helm3 to deploy --version 0.90 and --version 0.8.2 to isolate the issue both came with this error.. Any idea what i need to tweak on the cluster policy? The Microk8s is default out of the box setup

Upon hitting the url the server cant seem to startup
![Capture](https://user-images.githubusercontent.com/60381871/84482608-9fa54080-acca-11ea-9dea-e60038418413.PNG)
Your server is starting up.

You will be redirected automatically when it's ready for you.

100% Complete
Spawn failed: (422) Reason: error HTTP response headers: HTTPHeaderDict({'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Fri, 12 Jun 2020 16:30:26 GMT', 'Content-Length': '440'}) HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Pod \"jupyter-admin\" is invalid: spec.initContainers[0].securityContext.privileged: Forbidden: disallowed by cluster policy","reason":"Invalid","details":{"name":"jupyter-admin","kind":"Pod","causes":[{"reason":"FieldValueForbidden","message":"Forbidden: disallowed by cluster policy","field":"spec.initContainers[0].securityContext.privileged"}]},"code":422}

Event log
Spawn failed: (422) Reason: error HTTP response headers: HTTPHeaderDict({'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Fri, 12 Jun 2020 16:30:26 GMT', 'Content-Length': '440'}) HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Pod \"jupyter-admin\" is invalid: spec.initContainers[0].securityContext.privileged: Forbidden: disallowed by cluster policy","reason":"Invalid","details":{"name":"jupyter-admin","kind":"Pod","causes":[{"reason":"FieldValueForbidden","message":"Forbidden: disallowed by cluster policy","field":"spec.initContainers[0].securityContext.privileged"}]},"code":422}

**Comment by consideRatio** [comment]
Quick notes, but insufficient time time to follow up with you on it.
- I think you run into an issue because the cluster has a `podsecuritypolicy` defined forbidding it, try `kubectl get podsecuritypolicy`.
- I think you can disable that part by:
   ```yaml
   singleuser:
     cloudMetadata:
       # True means that we don't start a container in privileged mode
       # to actively block it.
       enabled: true
   ```
- I think we have other issues with 1.16+ on 0.8.2, but not on 0.9.0
