### ISSUE TITLE
Do more robust testing on Azure

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/zero-to-jupyterhub-k8s#170]
Partially moving https://github.com/jupyterhub/helm-chart/issues/8 but also other issues that need to be addressed before we can consider Azure a first class citizen.

1. Figure out recommended solution for persistent storage on Azure. Managed Disks? File storage?
2. Make sure that our recommendations with `az` tool actually do work

**Comment by yuvipanda** [comment]
https://azure.microsoft.com/en-us/blog/introducing-azure-container-service-aks-managed-kubernetes-and-azure-container-registry-geo-replication/?cdn=disable got announced today, and we should switch to it ASAP!

**Comment by pedroteixeira** [comment]
Hi, I get "PersistentVolumeClaim is not bound: "hub-db-dir" (repeated 2 times)" using v0.4
is there any current workaround?

**Comment by yuvipanda** [comment]
Are you using ACS or AKS? We haven't had much luck getting persistent volume claims to work on ACS when we tried, and we haven't tried on AKS yet since it was having capacity problems when we had time :(

**Comment by pedroteixeira** [comment]
I'm testing with AKS, had also to execute:
az provider register -n Microsoft.ContainerService
az provider register -n Microsoft.Compute
az provider register -n Microsoft.Compute

helm install required the following flag to work:
    --set prePuller.enabled=false

I'm reading on the issue.. I was using a Free Trial subscription, it might be related, going to try upgrade do "Pay as You Go" account type

**Comment by yuvipanda** [comment]
what's the output from `kubectl --namespace=<your-namespace> describe pvc`?

**Comment by pedroteixeira** [comment]
`kubectl --namespace=<namespace> get pvc`
NAME         STATUS    VOLUME    CAPACITY   ACCESS MODES   STORAGECLASS   AGE
hub-db-dir   Pending                                                      28m

**Comment by yuvipanda** [comment]
@pedroteixeira can you do `describe pvc` rather than `get`? Thanks.

**Comment by pedroteixeira** [comment]
sorry, I'm just learning about kubernetes today :)

```
kubectl --namespace=<namespace> describe pvc
Name:          hub-db-dir
StorageClass:  
Status:        Pending
Volume:        
Labels:        <none>
Annotations:   <none>
Capacity:      
Access Modes:  
Events:
  Type    Reason         Age                 From                         Message
  ----    ------         ----                ----                         -------
  Normal  FailedBinding  4m (x102 over 30m)  persistentvolume-controller  no persistent volumes available for this claim and no storage class is set
```

It's probably an disk quota/limit thing.. I'm upgrading the subscription type, let's see if that will fix it.
Thanks for the support :+1:

**Comment by yuvipanda** [comment]
@pedroteixeira no worries, and glad we were able to help!

**Comment by choldgraf** [comment]
@yuvipanda shall we keep iterating on this issue for Azure, or use a new one with the upcoming move to AKS, as I assume that'll spawn off a bunch of new issues

**Comment by yuvipanda** [comment]
Going to close this in favor of https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/410, which is more directly actionable!
