### ISSUE TITLE
Configuration of gcloud credentials

### ISSUE THREAD

**Issue by chrisroat** [jupyterhub/zero-to-jupyterhub-k8s#1705]
I have jupyterhub running on K8s, which has a service account json key file loaded from a K8s secret. The env var GOOGLE_APPLICATION_CREDENTIALS is set to point to the file.

I find that in order for gsutil to work properly (via `subprocess.run`), I have to execute the following command:

```
gcloud auth activate-service-account --key-file=${GOOGLE_APPLICATION_CREDENTIALS}
```

What is the proper config/hook to setup in order that this is done automatically for a singleuser?

Thanks!

**Comment by consideRatio** [comment]
Hi @chrisroat,

- You have a k8s option of using a postStart lifecycleHook, which is going to run some code just after the container starts in parallel to the actual container code.
- You also have the option of manipulating the startup command to do something else before starting up the jupyter notebook server. By setting `c.KubeSpawner.lifecycle_hooks` in a python configuration file such as from hub.extraConfig, or by using the Helm chart configuration `singleuser.lifecycleHooks`. Whatever you set this to, should match the k8s official specification, which you can google to find a reference about. I think you will find examples in the z2jh.jupyter.org documentation somewhere as well.

I'm not sure what makes the most sense or what would work well, but I'd try the postStart lifecycleHook first.

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/gcloud-service-account-activation-on-zero-to-jupyterhub/4816/2

**Comment by chrisroat** [comment]
@consideRatio Thanks for the tip.  For the record, in order to pick up the environmental var, I needed

```
  lifecycleHooks:
    postStart:
      exec:
        command:
          - 'sh'
          - '-c'
          - "gcloud auth activate-service-account --key-file=${GOOGLE_APPLICATION_CREDENTIALS}"
```
