### ISSUE TITLE
Broken link in user placeholder docs

### ISSUE THREAD

**Issue by mriedem** [jupyterhub/zero-to-jupyterhub-k8s#1717]
In this section of the docs [1] the last paragraph:

> IMPORTANT: Further settings may be required for successful use of the pod priority depending on how your cluster autoscaler is configured. This is known to work on GKE, but we don’t know how it works on other cloud providers or kubernetes. See the configuration reference for more details.

Has a link to [2] which doesn't exist. It looks like that should be going to [3] instead.

[1] https://zero-to-jupyterhub.readthedocs.io/en/latest/administrator/optimization.html?#scaling-up-in-time-user-placeholders
[2] https://zero-to-jupyterhub.readthedocs.io/reference/reference.html#scheduling-podpriority
[3] https://zero-to-jupyterhub.readthedocs.io/en/latest/reference/reference.html?#scheduling-podpriority

**Comment by mriedem** [comment]
Same issue here:

https://zero-to-jupyterhub.readthedocs.io/en/latest/administrator/advanced.html#specifying-suitable-hub-storage

**Comment by consideRatio** [comment]
I'm not sure how to resolve these broken links. @choldgraf perhaps you can help us? The crux is that we want to link to our configuration reference, and i guess it will be possible using relative paths, but is there a way to not do that and rely on the docs build system to reference an absolute path without hardcoding /en/latest or similarly?

```
# leads to /en/latest/some-relative-root-path/reference/reference.html...
[my config reference link 1](reference/reference.html#hub-db-type)
# leads to /reference/reference.html...
[my config reference link 2](reference/reference.html#hub-db-type)
# leads to /en/latest/reference/reference.html...
[my config reference link 3](????)
```

**Comment by manics** [comment]
In Sphinx/RST you can define labels and cross-reference them, so presumably we can do that with `myst_parser` if you know how ....

**Comment by choldgraf** [comment]
lemme see if I can figure it out 👍

**Comment by choldgraf** [comment]
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1823
