### ISSUE TITLE
Do better CI for the helm chart

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/zero-to-jupyterhub-k8s#172]
We should do the following on CI:

- Run minikube (with --provider=none)
- Install helm (pin version?)
- Install chart with various configs
- Make sure that with dummy authenticator we can get a pod running.

**Comment by manics** [comment]
`ci/test.sh` only checks JupyterHub is running, it doesn't check singleuser servers can be started. That's arguably covered by https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/639 though.

**Comment by choldgraf** [comment]
ah nice catch @manics ! I'm re-opening this, and we should cross-close it when a fix for #639 comes in

**Comment by jgerardsimcock** [comment]
What is the status of this issue? We'd like to start running CI for our deployment and its not clear how to implement this.

**Comment by manics** [comment]
As mentioned on https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/639#issuecomment-380049228 I haven't had time to look at automatically testing servers after deployment.

**Comment by betatim** [comment]
@manics made a god suggestion in https://github.com/jupyterhub/mybinder.org-deploy/pull/663: adding more extensive tests on a real k8s cluster.

I think more extensive testing with a "real" k8s setup is a great idea! Donating or providing the resources for doing this would be an easy way for some of the many users of the z2jh guide to help out with making the guide better and more stable.

**Comment by consideRatio** [comment]
Working towards this in #846.

**Comment by consideRatio** [comment]
We may not have solved the "various configs" parts of this issue, right?

I'm closing this for now and opening a new about "various configs" as I find this to be relevant as well.
