### ISSUE TITLE
User-specific IAM Role Assumption

### ISSUE THREAD

**Issue by droctothorpe** [jupyterhub/zero-to-jupyterhub-k8s#1724]
Is there a way to grant users the ability to assume specific IAM roles in their hub-provisioned notebook containers? I want to use Kube2IAM, so on the K8s side, it's just a matter of making sure the pod has the appropriate annotation, but that can't be global, it needs to be specific to individual users / notebooks. Thanks for the advice!

**Comment by consideRatio** [comment]
@droctothorpe you would need to run custom logic to modify the user pod's annotations before spawning them. This is an example on how to do something like that that you would put in hub.extraConfig.whateverNameHere as a long string, see:

https://github.com/neurohackademy/nh2020-jupyterhub/blob/6224d081cf7effb88ac4ca8c1d5e0819a66a3c91/deployments/hub-neurohackademy-org/config/prod.yaml#L176-L208

**Comment by droctothorpe** [comment]
Thank you for the pointer and reference @consideRatio! Would a workflow like this require a related update to the web gui so that users can pass in the input?

**Comment by consideRatio** [comment]
> Would a workflow like this require a related update to the web gui so that users can pass in the input?

It's not involving the user, it's only involving the JupyterHub admin that based on username etc runs python code that programmatically without input from the user sets the annotation. For user input, you should do something with JupyterHub's options_form of the Spawner.

> We use GitHub issues for specific discussions related to changing a repository's content

Please help by posting questions on discourse.jupyter.org so our GitHub issue list is centered around things to work on in the repo!

**Comment by droctothorpe** [comment]
Sounds good. Thank you so much for pointing me in the right direction!
