### ISSUE TITLE
schema.yaml: concurrentSpawnLimit not documented

### ISSUE THREAD

**Issue by mriedem** [jupyterhub/zero-to-jupyterhub-k8s#1725]
### Bug description

The `concurrentSpawnLimit` config is not shown in the config reference docs:

https://zero-to-jupyterhub.readthedocs.io/en/latest/reference/reference.html

If I understand how that config reference doc is built, it's because `concurrentSpawnLimit` is not in [jupyterhub/schema.yaml](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/jupyterhub/schema.yaml).

#### Expected behaviour
I expect configurable items to be shown in the config reference docs. In this case I would expect an entry for `concurrentSpawnLimit` with a description that is similar to what's in the jupyterhub config docs:

https://jupyterhub.readthedocs.io/en/stable/api/app.html#jupyterhub.app.JupyterHub.concurrent_spawn_limit

#### Actual behaviour
The `concurrentSpawnLimit` config is not in the docs.

### How to reproduce
Go to the page, search for the option, it's not there.

### Your personal set up
n/a

**Comment by consideRatio** [comment]
Closed in favor of #1792
