### ISSUE TITLE
Cannot install on AWS EKS using Fargate only cluster

### ISSUE THREAD

**Issue by DarkmatterVale** [jupyterhub/zero-to-jupyterhub-k8s#1726]
### Bug description
I am unable to launch a JupyterHub installation on AWS EKS using the Fargate compute profile.

#### Expected behaviour
JupyterHub is successfully installed on an EKS cluster regardless of underlying compute profile (Fargate or EC2).

#### Actual behaviour
When I attempt to install the Jupyterhub helm chart on an EKS cluster that uses a fargate-only compute, the hook-image-awaiter pods fail to stabilize, leading to a failed install.

Output of ```kubectl get pod -A```:
```
NAMESPACE     NAME                       READY   STATUS    RESTARTS   AGE
jhub          hook-image-awaiter-*****   0/1     Error     0          3h12m
jhub          hook-image-awaiter-*****   0/1     Error     0          3h9m
jhub          hook-image-awaiter-*****   0/1     Error     0          172m
jhub          hook-image-awaiter-*****   0/1     Error     0          178m
jhub          hook-image-awaiter-*****   0/1     Error     0          3h15m
jhub          hook-image-awaiter-*****   0/1     Error     0          3h2m
jhub          hook-image-awaiter-*****   0/1     Error     0          3h6m
kube-system   coredns-**********-*****   1/1     Running   0          12d
kube-system   coredns-**********-*****   1/1     Running   0          12d
```
(note I ran this a few hours ago which is why the age is high)

Output of ```kubectl logs hook-image-awaiter-***** -n jhub``` (all of them fail on the same error):
```
2020/07/21 13:57:38 Get https://10.100.0.1:443/apis/apps/v1/namespaces/jhub/daemonsets/hook-image-puller: dial tcp 10.100.0.1:443: getsockopt: connection timed out
``` 

I confirmed that the endpoint that causes the connection time out error is reachable from a Fargate pod running in the jhub namespace. To verify this (instructions on how to get an api token can be found [here](https://kubernetes.io/docs/tasks/administer-cluster/access-cluster-api/)):
1. Start up a ubuntu pod: ```kubectl run -i --tty ubuntu --image=ubuntu -n jhub -- sh```
2. ```apt update && apt install curl```
3. ```curl -X GET https://10.100.0.1:443/apis/apps/v1/namespaces/jhub/daemonsets/hook-image-puller --header "Authorization: Bearer $TOKEN" --insecure```

### How to reproduce
1. Create a new Fargate EKS cluster using eksctl (```eksctl create cluster --name my-jupyterhub-cluster --version 1.16 --fargate --region us-east-2```)
2. Add a fargate profile for JupyterHub's namespace ("jhub")
3. Add Jupyterhub repository to helm (```helm repo add jupyterhub https://jupyterhub.github.io/helm-chart/ && helm repo update```)
4. Create ```config.yaml```:
```
proxy:
  secretToken: .........................................................
```
5. Install JupyterHub helm chart:
```
RELEASE=jhub
NAMESPACE=jhub

helm upgrade --install $RELEASE jupyterhub/jupyterhub \
  --namespace $NAMESPACE \
  --version=0.9.0 \
  --values config.yaml \
  --create-namespace
```

### Your personal set up
 - OS: OSX, 10.15.6
 - Helm version: v3.2.3
 - Kubectl version:
    - Client version: 1.18.2
    - Server version: 1.16.8

Other information to know: I am happily running a JupyterHub cluster on EKS using EC2 instances as the compute. This issue seems to only appear when using Fargate.

**Comment by DarkmatterVale** [comment]
I've done some more research and identified a few potential issues associated with running JupyterHub in production on EKS with Fargate (see [here](https://docs.aws.amazon.com/eks/latest/userguide/fargate.html) for more information on Fargate + EKS):
1) Daemonsets are not supported.
2) Classic load balancers are not supported for ingress

I'm wondering if my issue is caused due to the fact that Fargate doesn't support daemonsets?

**Comment by Arash-Afshar** [comment]
Any update on this one @DarkmatterVale? I am hitting the same issue.

**Comment by filippo82** [comment]
Hi @DarkmatterVale, I have a question for you [here](https://github.com/jupyterhub/kubespawner/issues/410) :)

**Comment by consideRatio** [comment]
I'm going to close this issue to indicate there is no concrete action point identified with regards to this github repo's content.

Feel free to keep using this issue as a communication channel to help each other stay updated about potential progress though, or request that we open it if an action point is identified.
