### ISSUE TITLE
Add support for LDAPAuthenticator

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/zero-to-jupyterhub-k8s#173]
Can already be done with a bit of hacks, as in https://github.com/jupyterhub/helm-chart/issues/55

But we should support it natively!

**Comment by choldgraf** [comment]
@yuvipanda I'm gonna close this in lieu of https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/264 since it's got more movement on it, and it's already tagged as v0.6

feel free to re-open if you like!
