### ISSUE TITLE
A blank singleuser.fsGid configuration is the same as setting it to 0 - which it shouldn't be

### ISSUE THREAD

**Issue by 24hours** [jupyterhub/zero-to-jupyterhub-k8s#1733]
### How to reproduce

in config.yaml 
define the setting as 
```
singleuser:
  fsGid: null
```

spawn a jupyter notebook, inspect pod yaml configuration 
you will see 
```
spec
  securityContext:
    fsGroup: 0
```

obviously securityContext should not be defined as `fsGid=None`. 

### Your personal set up

I'm setting up jupyterhub-k8s in my local environment using PVC for each user. However, if user stored too many file into their volume, their subsequent session become very slow to the point where timeout frequently occur. 

the issue can be traced back to several issue across Kubernetes ecosystem. 
Longhorn: https://github.com/longhorn/longhorn/issues/1221
Azure ACS: https://github.com/Azure/acs-engine/issues/2989#issuecomment-414933515

I have even reported the bug here:
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1252

the culprit is 
```
 securityContext:
    fsGroup: 0
```

work around is proposed in this issue, dont set fsGroup on pod configuration.
https://github.com/kubernetes/kubernetes/issues/69699#issuecomment-558861917

which is equivalent to 
config.yaml 
```
singleuser:
  fsGid: null
```
as default is set to fsGid=100

The bug related to both jupyterhub-k8s and [Kubespawner](https://github.com/jupyterhub/kubespawner)

In kubespawner, 
```python
spawner = KubeSpawner(fs_gid=1000)
print(spawner.fs_gid) # 1000
# this is the expected result 

spawner = KubeSpawner(fs_gid=None)
print(spawner.fs_gid) # None
# this will spawn a container with no securityContext defined. 

spawner = KubeSpawner()
print(spawner.fs_gid) # 0
# Due to how fs_gid is defined in traitlets, undefined will default to 0.
# One solution is to force define trailets with the default value = None. 
```

This is the location where fs_gid is defined in jupyter_config.py
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/jupyterhub/files/hub/jupyterhub_config.py#L118

Due to how `set_config_if_not_none` is defined:
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/jupyterhub/files/hub/z2jh.py#L78
the value is not defined if `value = None`

finally causing arguments passed to KubeSpawner to be missing fs_gid thus defaulting to 0

The resulting bug is the combination of Kubespawner and juputerhub-k8s error.

**Comment by atsai1220** [comment]
We are running into the same issue with slow volume mounts. We commented out these lines then mounted the `objects.py` to `/opt/kubespawner/` in the `hub` container for the time being and it worked for us. 
```
    pod_security_context = V1PodSecurityContext()
#    if fs_gid is not None:
#       pod_security_context.fs_group = int(fs_gid)
    if supplemental_gids is not None and supplemental_gids:
       pod_security_context.supplemental_groups = [int(gid) for gid in supplemental_gids]
    # Only clutter pod spec with actual content
    if not all([e is None for e in pod_security_context.to_dict().values()]):
        pod.spec.security_context = pod_security_context
```
https://github.com/jupyterhub/kubespawner/blob/0eecad35d8829d8d599be876ee26c192d622e442/kubespawner/objects.py#L258-L259

**Comment by consideRatio** [comment]
@24hours woooooooooooooooo thank you for a really awesome description of this issue! You nailed it! :heart: :tada:

## Summary of the issues described
- [ ] KubeSpawner's default value of fs_gid is `0` rather than `None` or perhaps `100` which has been commonly used with jupyter/docker-stacks based docker images.
- [ ] Z2JH is unable to explicitly pass `None` to override the default value of `0`.

**Comment by chancez** [comment]
I was able to set it to `None` in `hub.extraConfig`:

```
hub:
  extraConfig:
   myConfig: |
     c.KubeSpawner.fs_gid = None
```

**Comment by consideRatio** [comment]
## Bugs to be fixed
1. KubeSpawner should default to None rather than 0 for uid, gid, and fs_gid
2. Z2JH should be able to set various fields that are allowed to be none, to none, i guess.

I'll create a PR for KubeSpawner to start with.
