### ISSUE TITLE
upload button in jupyterhub does not react for large files

### ISSUE THREAD

**Issue by tank113** [jupyterhub/zero-to-jupyterhub-k8s#1748]
### Bug description
I have Jupyterhub running in which the user-pods are mounted to GCS Bucket. The upload button in the jupyterhub works fine for the small files but does not react while uploading even not so large files (>10 MB) files. It doesn't upload the files and clicking upload button again has no effect.

#### Expected behaviour
The upload button should work correctly even for large files

#### Actual behaviour
Upload button doesn't react for large files

### How to reproduce
Deploy JupyterHub using Helm, mount the user pods to GCS Bucket and upload large files

### Your personal set up
Below is my config.yaml

```hub:
  baseUrl: /jupyterhub
  extraConfig: |
    from kubernetes import client
    def modify_pod_hook(spawner, pod):
        pod.spec.containers[0].security_context = client.V1SecurityContext(
            privileged=True,
            capabilities=client.V1Capabilities(
                add=['SYS_ADMIN']
            )
          )
        return pod
    c.KubeSpawner.modify_pod_hook = modify_pod_hook

proxy:
  secretToken: "set-token"
  service:
    type: NodePort

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - my-web.com
  tls:
    - hosts:
       - my-web.com
      secretName: jhub-tls

auth:
  admin:
    users:
      - admin
  type: dummy
  dummy:
    password: 'password'
  whitelist:
    users:
      - usr1
      - usr2

singleuser:
  storage:
    extraVolumes:
      - name: gcp-secret
        secret:
          secretName: jhub-gcp-secret
    extraVolumeMounts:
      - name: gcp-secret
        mountPath: /etc/secret
        readOnly: true
  extraEnv:
    GOOGLE_APPLICATIONS_CREDENTIALS: /etc/secret/key.json
    GCS_BUCKET: "my-bucket"
    GCS_BUCKET_FOLDER: "shared-data"
  lifecycleHooks:
    postStart:
      exec:
        command: ["/bin/sh", "-c", "gcsfuse -o nonempty --implicit-dirs --key-file ${GOOGLE_APPLICATIONS_CREDENTIALS} ${GCS_BUCKET} /home/jovyan/"]
    preStop:
      exec:
        command: ["fusermount", "-u", "/home/jovyan/"]
  image:
    name: gcr.io/my-prj/base-images/jhub-k8s-singleuser
    tag: 1.1.11
    pullPolicy: Always
```

**Comment by consideRatio** [comment]
@tank113 note that as a JupyterHub developer I don't understand what the Upload button refers to, but I assume it is some user interface in the user server you started up with JupyterHub.

Note I just verified on that I could drag and drop upload files to my Jupyter server running Jupyter Notebook server with a JupyterLab as a user interface. The file i uploaded was 19MB.

**Comment by tank113** [comment]
Yes it is the user interface of the minimal jupyter notebook that I started with the JupyterHub and it is mounted to the GCS Bucket as shown in the config.yaml above.

Seems to be an UI issue but just wanted to be sure whether mounting it with GCS has any effect on it? or may be some "max_file_size" param I am missing in the config?

**Comment by consideRatio** [comment]
I'm not sure what causes this for you. I wish that you raise the question at the forum to let this be a place to report reproducible bugs closely relating to the repository. This repo is about the Helm chart to deploy JupyterHub on the cloud. Please refer to the forum for a general ask for help.

Also note that if you ask this in the forum, do include more specific error message, or a gif animation of how it looks in the user interface, or a screenshot etc. That is the starting point of the debugging for you and others willing to help, so it needs to be very clear.
