### ISSUE TITLE
Add docs on how to do local development

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/zero-to-jupyterhub-k8s#175]
Moving https://github.com/jupyterhub/helm-chart/issues/71 and other related issues here.

We don't have much docs on how to use helm + minikube to develop this locally. We should add those!

**Comment by yuvipanda** [comment]
We have https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/CONTRIBUTING.md now!

**Comment by jhamman** [comment]
@yuvipanda - The jupyterhub minikube documentation in CONTRIBUTING.MD is primarily targeting the jupyterhub developer. Would it be possible to add a section in the main documentation that lays out instructions for non-developers on how to use minikube with jupyterhub? This would look similar to an AWS/GCP deployment, albeit much simpler. 

xref: https://github.com/pangeo-data/pangeo/issues/137
