### ISSUE TITLE
Rename 'singleuser' to 'user' in values.yaml

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/zero-to-jupyterhub-k8s#176]
A lot of people expressed confusion at the fact that all these properties called 'singleuser' exist, but JupyterHub is a multi user deployment. I think this warrants us renaming all the 'singleuser' properties to just 'user'.

We should also make sure this is backwards compatible. YAML references might help!

Moved from https://github.com/jupyterhub/helm-chart/issues/34

**Comment by choldgraf** [comment]
@yuvipanda given that we're close on 0.7 and that most everybody thought this was a good idea, think we should add this to v0.8 of the helm chart?

**Comment by betatim** [comment]
Would we also rename things in the jupyterhub docs? I would value consistency between juypterhub lingo and helm chart lingo.

**Comment by yuvipanda** [comment]
Yeah, I think we should be consistent inside JupyterHub. Not sure if we wanna do this, it's a lot of effort.

**Comment by choldgraf** [comment]
I'm +1 on deciding not to do this, since we've already got some historical baggage, and since we can clarify what `singleuser` means in documentation etc.

**Comment by consideRatio** [comment]
I've considered this a while, but now that I recently looked inside the kubespawner code I'm thinking we should not switch out the usage of `singleuser`. I reason that it would mean that the kubespawner project should start deprecating settings containing `singleuser` in the name for example. I think it would give rise to quite a bit of work and perhaps more confusion than it would resolve.

__Suggested resolution__
We attempt to combat the confusion about `singleuser` by improving documentation.
