### ISSUE TITLE
Possibility to have resource requests/limits set on all our containers

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#1761]
To specify resource quotas on all our containers or provide an ability to do so. There are multiple reasons for this.

1. If we don't do it, we may end up with 100m CPU for a pause pod for example, which is a waste.
2. If we don't allow configuration of the resources, someone using a resourcequota may fail to use the Helm chart involving these pods because its may be required to have them explicitly set, see https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1251.

**Comment by tirumerla** [comment]
Hi @consideRatio I see that `job/hook-image-awaiter` is not configured with resource requests. This is the error i'm running into when i deploy using helm chart version `0.10.2`.
```
jupyterhub   4m49s       Warning   FailedCreate              job/hook-image-awaiter                 (combined from similar events): Error creating: pods "hook-image-awaiter-6mvsc" is forbidden: failed quota: jupyterhub-resourcequota: must specify limits.cpu,limits.memory,requests.cpu,requests.memory
```
**Fix:** 
* Add resources in [image-puller job.yaml](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/jupyterhub/templates/image-puller/job.yaml).

Appreciate your help.

**Comment by consideRatio** [comment]
@tirumerla oh you are right! I'll fix this right away!

**Comment by tirumerla** [comment]
> @tirumerla oh you are right! I'll fix this right away! For my own knowledge and such, could you let me know what resourcequota you have installed in the namespace where you try to install the JupyterHub Helm chart?
> 
> ```shell
> # what is the name of your resourcequota?
> kubectl get resourcequota -n <your jupyterhub namespace>
> 
> # this is what I'm curious to see
> kubectl get resourcequota -n <your jupyterhub namespace> -o yaml <name found>
> ```
`$ kubectl get resourcequota -n jupyterhub`
```
NAME                       CREATED AT
jupyterhub-resourcequota   2020-11-10T03:52:08Z
```
`$ kubectl get resourcequota -n jupyterhub -o yaml jupyterhub-resourcequota`
```
apiVersion: v1
kind: ResourceQuota
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ResourceQuota","metadata":{"annotations":{},"name":"jupyterhub-resourcequota","namespace":"jupyterhub"},"spec":{"hard":{"limits.cpu":"1.0","limits.memory":"1.5Gi","requests.cpu":"0.3","requests.memory":"0.75Gi"}}}
  creationTimestamp: "2020-11-10T03:52:08Z"
  name: jupyterhub-resourcequota
  namespace: jupyterhub
  resourceVersion: "20140815"
  selfLink: /api/v1/namespaces/jupyterhub/resourcequotas/jupyterhub-resourcequota
spec:
  hard:
    limits.cpu: "1"
    limits.memory: 1536Mi
    requests.cpu: 300m
    requests.memory: 768Mi
status:
  hard:
    limits.cpu: "1"
    limits.memory: 1536Mi
    requests.cpu: 300m
    requests.memory: 768Mi
  used:
    limits.cpu: 810m
    limits.memory: 1290Mi
    requests.cpu: 250m
    requests.memory: 640Mi
```
