### ISSUE TITLE
Add instructions for deploying on OpenShift

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/zero-to-jupyterhub-k8s#177]
OpenShift has stricter security set up by default, and would need some amount of additional wrangling. https://github.com/jupyterhub/helm-chart/issues/26 has a lot of useful info about how to do this, so let's make it work and add it to the doc.

**Comment by willingc** [comment]
Add link to https://www.youtube.com/watch?v=buOl6WGa8x4 JupyterHub on OpenShift
