### ISSUE TITLE
Question on how to use jupyter-server-proxy with a Z2JH deployment

### ISSUE THREAD

**Issue by singhabhinav** [jupyterhub/zero-to-jupyterhub-k8s#1771]
I have installed the jupyterhub on Kubernetes on GCP by following the guide.

I am running various services on notebook like Tensorboard and Spark UI. These services are running on port inside the pods. And of course, these ports are not reachable from my hub IP.

I tried to use jupyter-server-proxy for the same. I did the below steps. I opened the terminal and ran below steps

```
1. mkdir www
2. cd www
3. echo "hi" >> index.html
4. python -m http.server 9000
```
![Screenshot 2020-09-04 at 5 09 57 PM](https://user-images.githubusercontent.com/10808722/92235735-ccd04c00-eed1-11ea-90a0-8e790164b768.png)

Now I went to this URL - http://my-hub-ip/user/my-user-name/proxy/9000/

I got a 404 error.  Any suggestions on how should I fix it. I have verified that jupyter_server_proxy is enabled.

![Screenshot 2020-09-04 at 5 13 12 PM](https://user-images.githubusercontent.com/10808722/92235821-f4271900-eed1-11ea-9357-43e6ddaed240.png)

I have noticed one thing that whenever I try to access http://my-hub-ip/user/my-user-name/proxy/9000/ my browser automatically redirects me to http://my-hub-ip/user/my-user-name/proxy/9000

**Comment by consideRatio** [comment]
Hi @singhabhinav just as a quick input, note that you get a 404 from JupyterHub's webserver rather than the Jupyter server representing the individual user. I would expect you to get an 404 from your user server rather than the JupyterHub server if you had an issue with using jupyter-server-proxy.

I have used jupyter-server-proxy successfully on a z2jh based jupyterhub, so I without a clearer indication of this being a bug with the JupyterHub Helm chart, I close this as a support question we lack maintainer capacity to tackle.

**Comment by singhabhinav** [comment]
@consideRatio Thanks for your inputs.  Any pointers on where should I try to fix it. I have followed the documentation of jupyter-server-proxy and I could not boil down the problem. Since the hub is redirecting the proxy, I assumed the problem might be there.

**Comment by consideRatio** [comment]
I think its weird that you can visit your user pod but not get a 404 from the user pod's jupyter-notebook server, but instead end up with the JupyterHub 404 error code. That make me suspect that your URL didnt just modify /user/username/lab or similar to /user/username/jupyterserverproxyrouting etc.

But I don't know, but as a parting advice, double check your URLs and ensure they align with jupyter-server-proxy instructions and check the logs of the hub pod, proxy pod, and user pod. Also, enable `debug: true` in your Helm chart configuration.

Good luck!

**Comment by singhabhinav** [comment]
Hi @consideRatio,

I just checked the logs of the user pod. The error 404 is there

![Screenshot 2020-09-04 at 9 12 35 PM](https://user-images.githubusercontent.com/10808722/92257859-855ab780-eef3-11ea-9c1c-5dd31bfba1d8.png)

**Comment by kevinevelasco** [comment]
> Hi [@consideRatio](https://github.com/consideRatio),
> 
> I just checked the logs of the user pod. The error 404 is there
> 
> ![Screenshot 2020-09-04 at 9 15 12 PM](https://user-images.githubusercontent.com/10808722/92257995-c3f07200-eef3-11ea-996e-ed1027617cbf.png)

Hey, I know it's been a long time, but I just wanted to know if you managed to fix this problem.
@manics or @consideRatio I'm sorry, has this issue been resolved before?
