### ISSUE TITLE
Make helm resources release specific

### ISSUE THREAD

**Issue by kristofmartens** [jupyterhub/zero-to-jupyterhub-k8s#1774]
### Proposed change
For various (security) reasons there is a need for us to set up multiple jupyterhub setups in the same kubernetes namespace. We use this to achieve "project based access" to users where AWS credentials are automatically added to the jupyter notebook pods. Currently there is no release based naming convention implemented in the helm charts. This makes it impossible to install multiple helm charts in the same namespace due to resource naming conflicts.

Our suggestion is to add the release name to named kubernetes resources: ie. {{ .Release.Name }}-configmap
This is also the proposed way of addressing this issue in most helm chart templates. This change will however impact all existing resources and could have an impact when upgrading your helm chart to the updated version.

### Alternative options
An alternative option would be to create a specific namespace for each notebook instance

### Who would use this feature?
Companies that want to run mulitple jupyterhub setups in a per project based setup

### (Optional): Suggest a solution
As mentioned in the proposed change, basically this means adding the {{ .Release.Name }}- macro for each named resource and reference to these resources.

**Comment by kristofmartens** [comment]
I am willing to submit a PR to address this issue myself if this change would be accepted

**Comment by manics** [comment]
There's already a PR open: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1740
Please see if it covers your requirements, and feel free to make suggestions.

**Comment by consideRatio** [comment]
Thanks for being an active member of this project @kristofmartens!

As this is a popular topic that has been discussed and considered in many places without clear resolution for a long time, I've decided to close all existing issues and PRs relating to it and refer to a single issue: #1791. In this issue I've done my best to provide a clear and actionable path towards progress.
