### ISSUE TITLE
Always roll deployments when using an existing secret

### ISSUE THREAD

**Issue by ableuler** [jupyterhub/zero-to-jupyterhub-k8s#1779]
### Proposed change

After merging https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1142, Jupyterhub can use an existing secret. When this option is used, the regular way of deciding if deployments (like the hub or the proxy) have to be redeployed through adding a checksum of the secret to the annotation does not work. A solution for this scenario would be to always recreate all pods with secret checksum annotations on helm upgrade when an existing secret is used.

### Alternative options

People who modify an existing secret which is used by Jupyterhub will have to manually recreate the necessary pods.

### Who would use this feature?

Everyone who makes use of the existing secret option wanting to modify those secrets, either manually or through a helm upgrade of a chart which uses Jupyterhub as a dependency.

### (Optional): Suggest a solution

The implementation would be quite straight forward. All the deployments which have a checksum of a secret in their annotation would receive a randomly generated number as annotation if an existing secret is provided through the values. 

What do people think about this? Would a PR implementing this change be accepted?

**Comment by consideRatio** [comment]
I don't want us to change the default to always restart the hub, but if you want to force this, you could...

## 1. Adjust an annotation on `helm upgrade`
```
helm upgrade ..... --set hub.annotations.timestamp=$(date '+%s')
```

## 2. Use Helm 3.1 `lookup` function (when all have migrated)

When we assume everyone use Helm 3.1+, we could use a `lookup` function to actually calculate the hash of the k8s currently installed k8s Secret from the Helm templates when the templates render as the first step of a `helm upgrade`.
