### ISSUE TITLE
Create new user storage and change nb user

### ISSUE THREAD

**Issue by ashvinnihalani** [jupyterhub/zero-to-jupyterhub-k8s#1785]
I am having trouble with what I assume is a common deployment. I need to change the NB User to what the username that Google Authenticator provides. 

I also want to create a new PvC, based on an existing VC when a new user logs in and if a previous user logs in it already grabs it.

**Comment by manics** [comment]
In general we ask that JupyterHub GitHub issues are used for bugs and development discussions, with support being handled on the [community forum](https://discourse.jupyter.org/) where more people hang out, and the rest of the community can benefit from these discussions. Hope you understand 😀.
