### ISSUE TITLE
Allow specifying a custom jupyterhub_config.py snippet along with values.yaml when installing

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/zero-to-jupyterhub-k8s#179]
From @minrk:
> Writing Python in yaml is pretty painful for nontrivial content. Is there a way to get a standalone jupyterhub_config.py file that is loaded the same as hub.extraConfig in yaml?

From @yuvipanda:
> Unfortunately that's not a feature we can use. The accessing_files.md documentation is for accessing files inside the packaged chart, rather than for users using helm install / upgrade. I agree it would be much better, but helm doesn't have that feature right now.

From https://github.com/jupyterhub/helm-chart/issues/76

**Comment by consideRatio** [comment]
Solved with the extraConfig entry already =D
