### ISSUE TITLE
Incomplete reference documentation in schema.yaml

### ISSUE THREAD

**Issue by ronlut** [jupyterhub/zero-to-jupyterhub-k8s#1792]
### Bug description
There are configuration options that doesn't appear in the documentation, although they are referenced multiple times across the different guides.
What I noticed missing:
`singleuser.defaultUrl`
`singleuser.storage` (and everything underneath)

Practically, I wanted to know what other configuration I can supply to `extraVolumes` and `extraVolumeMounts`. 

#### Expected behaviour
Documentation should exist for those entries.

#### Actual behaviour
No Documentation.

### How to reproduce
https://zero-to-jupyterhub.readthedocs.io/en/latest/reference/reference.html#singleuser

Thanks!

**Comment by NerdSec** [comment]
I would be happy to pick this up, along with the security documentation that was discussed [here](https://discourse.jupyter.org/t/restricted-psp-z2jh-fails-in-local-gitlab-oauth-workflow/6202/3).

However, I could not find the template used by the singleuser pod [here](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/tree/master/jupyterhub/templates). Generally speaking, there is no block diagram that explains the roles of the individual components too. Would it make sense to add something like an Architectural diagram in the docs too?

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/restricted-psp-z2jh-fails-in-local-gitlab-oauth-workflow/6202/5

**Comment by consideRatio** [comment]
@NerdSec there is no Helm chart template for the singleuser pods, because these resources are dynamically created by the KubeSpawner Python class running as part of the JupyterHub server in the hub pod. KubeSpawner sends REST API requests to the k8s api-server to create pods just like a `kubectl create` command does.

@NerdSec I opened https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1801 to reflect the idea of documenting the components better.

Welcome :heart:

**Comment by consideRatio** [comment]
Another piece not documented in schema.yaml: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1725

**Comment by NerdSec** [comment]
> multiple times across the different guides

Hi @ronlut ,

Can you please provide a link/ref to where exactly this is referred?

**Comment by ronlut** [comment]
@NerdSec Sure, basically all over this page:
https://zero-to-jupyterhub.readthedocs.io/en/latest/customizing/user-storage.html

Regarding defaultUrl: [here](https://zero-to-jupyterhub.readthedocs.io/en/latest/customizing/user-environment.html#use-jupyterlab-by-default).

Thanks!

**Comment by consideRatio** [comment]
Closing this in favor of #1725
