### ISSUE TITLE
The username (JUPYTERHUB_USER env variable) when using ldap authorization changed between 0.8 to 0.9 versions

### ISSUE THREAD

**Issue by ransoor2** [jupyterhub/zero-to-jupyterhub-k8s#1809]
Hello,
We are upgrading from the 0.8 version to the 0.9.1 version. 
Our deployment is creating the user's workarea after the user logs in.
We used to build it based on the username variable JUPYTERHUB_USER, however, now it contains 
"lastname\\, firstname"
So for example, if previously a user named John Doe with a username of jdoe logged in, JUPYTERHUB_USER would be jdoe.
Now, at 0.9.1 we get JUPYTERHUB_USER=doe\\, john
What caused this change and is there alternative to get the right username before starting the notebook?

**Comment by consideRatio** [comment]
It probably relates to the change in version of jupyterhub/ldapauthenticator, check out [the changelog](https://github.com/jupyterhub/ldapauthenticator/blob/master/CHANGELOG.md) of that repository and see what's updated in the documentation etc.

Z2JH 0.9.0 used jupyterhub-ldapauthenticator==1.3.0

If you specify to use the absolute latest version, `0.9.0-n311.ha2c3ef80`, then you will get version 1.3.2 with potential bugfixes.
