### ISSUE TITLE
 After scaling cluster from 0 to x, external IP address times out  

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/zero-to-jupyterhub-k8s#181]
From @philwinder (https://github.com/jupyterhub/helm-chart/issues/73):

I was following the recommendations to scale the cluster to 0, the scale up on the day as per: https://zero-to-jupyterhub.readthedocs.io/en/latest/extending-jupyterhub.html#expanding-and-contracting-the-size-of-your-cluster

But when scaling back up, the main external IP address just times out.

I can't quite seem to find the problem. The LB is pointing to the service. The service is pointing to the proxy. The proxy is pointing to the Hub. It's almost like the hub is binding to the wrong IP address.

I'll add more information if I find it.

**Recreate**:

Standard instructions to create a cluster, add helm, install jupyter hub.

Then resize to zero nodes:
```
gcloud container clusters resize ${CLUSTER_NAME} --size 0 --zone ${ZONE}
```
Wait for that to finish. Then scale back up. I made the size different to the original size. Not sure if that made any difference.
```
gcloud container clusters resize ${CLUSTER_NAME} --size 5 --zone ${ZONE}
```

**Workaround**
Don't scale down your cluster to zero. Always make sure you have at least one node running.

**Edit 1**
This only occurs if you resize to a number of nodes that was NOT your original size.

In fact, I can fix a broken cluster by scaling from 5 (not original) to 3 (original).

**Edit 2**
Scaling from the original size, to another larger size works. This implies that there is some dependence on the hub running in the same place, or at least one of the original nodes. I'm not sure.

**Comment by yuvipanda** [comment]
From @yuvipanda:

hmm, I've had scaling up and down work very well in the past. Let's try to debug this :)

1. Can you provide output of `kubectl --namespace=<your-namespace> get pod -o yaml`? 
2. Can you provide output of `kubectl --namespace=<your-namespace> describe pod`?

Based on these, we can tell if the pods are running or not, and what stage they're in. We can then go from there.

**Comment by choldgraf** [comment]
it doesn't look like there's a ton of movement on this, and I haven't seen any reported problems of 0 to x causing this problem. I'm gonna close this, but if anybody thinks it should stay open, or has heard of similar problems in recent history, please do reopen!
