### ISSUE TITLE
Run hook-image-puller only if an image has changed

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#1814]
If we start to assume that users have Helm 3.1 or perhaps Helm 3.2, then we can make use of [the `lookup` function](https://helm.sh/docs/chart_template_guide/functions_and_pipelines/). This function allows us to inspect the currently installed resources. This in turn allows us to be smart and only run the `hook-image-puller` logic conditionally if something has changed.

In practice I think we would do the following to accomplish this.

1. We create a new ConfigMap resource that contains things we may want to lookup, so it becomes easy to find that specific information. We could name the ConfigMap `latest-state` or similarly, and we could render a hash of an augmented list of images that we pull into a key there.
2. We only render the `hook-image-awaiter` Job resource in templates/image-puller/job.yaml and the hook DaemonSet if we evaluate this:

   ```yaml
   {{- $latest_state := lookup "v1" "ConfigMap" .Release.Namespace "latest-state" }}
   {{- $image_hash := $latest_state.data.prePullerImagesHash }}
   {{- if $image_hash is not equal to the new hash }}
   # render image-awaiter Job resource
   {{- end }}
   ```

## Action points
- [x] Decide if it's worth adding this complexity to reduce the delay caused by this step during `helm upgrade`, or it's just better for this project to skip it.
- [x] Develop and triel this experimentally
- [x] Decide when to require Helm 3 of a version that has the lookup function

## Related
- Another case to use the Helm3 `lookup` function: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1017

**Comment by manics** [comment]
If someone's keen to try this out (or anything else that requires a more recent Helm/K8S) could we hide it behind a feature flag, e.g.`.Values.preview.<featurename>`?

**Comment by consideRatio** [comment]
I think it could be worth the complexity addition so I went for a opt-in flag. The idea used is just to hash the hook-image-puller daemonset and see if it changes. See #2066.
