### ISSUE TITLE
docs: cleanup of large unused file

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#1822]
I think #1704 introduced an unwanted file, [doc/source/reference.md](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/doc/source/reference.md), which seem to be an artifact of [jupyterhub/schema.yaml](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/jupyterhub/schema.yaml), and possibly [doc/source/reference.txt](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/doc/source/reference/reference.txt).

@jtpio this wasn't intentional, right?

**Comment by jtpio** [comment]
Oh no it wasn't, we can definitely remove it.

Probably as part of #1704 I must have run something like `git add doc` while working on the docs, and didn't notice the extra file.

Should it be part of the `.gitignore` too? (not sure where this file is coming from).

Thanks for catching that!
