### ISSUE TITLE
Jupyterhub unpredictably fails to start new notebook

### ISSUE THREAD

**Issue by MikkelSchubert** [jupyterhub/zero-to-jupyterhub-k8s#1838]
### Bug description

Jupyterhub unpredictably fails to start a new notebook on otherwise idle cluster. No pods are created and no errors appear to be reported in the logs.

#### Expected behaviour

User logs in, a user pod is created, and the notebook is started.

#### Actual behaviour

Upon logging in, the user is presented with the messages:

    Your server is starting up.

    You will be redirected automatically when it's ready for you.

    Server requested

No further messages are displayed until the server startup times out and no new pods are spawned prior to the timeout. Refreshing the page after the timeout typically results in a normal startup, but may also result in the same failure again.

Jupyterhub logs and kubectl events during a failed and during a successful login are attached as `logs.txt`.

### Your personal set up
Kubernetes v1.17.11 on Azure using Helm chart v0.9.1. Settings are attached as `config.txt`.

[config.txt](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/files/5383467/config.txt)
[logs.txt](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/files/5383468/logs.txt)

**Comment by consideRatio** [comment]
Upgrade to the latest debelopment release, named 0.9.0-n3##..... it is 300+ commits newer and has a stability fix needed for azures k8s clusters.
