### ISSUE TITLE
wrong persistentvolume ressource, 's' is missing

### ISSUE THREAD

**Issue by tuxtof** [jupyterhub/zero-to-jupyterhub-k8s#1843]
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/38e50c71130fcf56655685f0992f4f125bef3879/jupyterhub/templates/scheduling/user-scheduler/rbac.yaml#L45

persistentvolume is missing a 's' at the end, so break on the k8s cluster using localpath-provisionner

**Comment by consideRatio** [comment]
This is [resolved in current master](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/jupyterhub/templates/scheduling/user-scheduler/rbac.yaml#L133).

**Comment by tuxtof** [comment]
@consideRatio when is plan the next helm release with this correction ?
