### ISSUE TITLE
Kubespawner doesn't allocate jupyter-notebook evenly 

### ISSUE THREAD

**Issue by nnbaokhang** [jupyterhub/zero-to-jupyterhub-k8s#1845]
### Bug description

![image](https://user-images.githubusercontent.com/11141804/96357019-2c19a280-10b3-11eb-9550-4ad549928c25.png)

#### Expected behaviour

Jupyter-notebook should be allocated evenly between nodes

#### Actual behaviour

Jupyter-notebooks are allocated in the main node. 
Main node usage: 
CPU requests (cores) : 750.00m (9.38%)
CPU limits (cores):      100.00m (1.25%)
Memory requests (bytes): 9.64Gi (30.86%)
Memory limits (bytes):     38.05Gi (121.84%)
Node 3 usage:
CPU requests (cores): 200.00m (2.50%)
CPU limits (cores):  100.00m (1.25%)
Memory requests (bytes): 120.00Mi (0.38%)
Memory limits (bytes):  220.00Mi (0.69%)
Node5 usage:
CPU requests (cores): 812.00m (10.15%)
CPU limits (cores):  100.00m (1.25%)
Memory requests (bytes): 1.55Gi (4.96%)
Memory limits (bytes):  50.00Mi (0.16%)
Node6:
CPU requests (cores): 712.00m (8.90%)
CPU limits (cores):  100.00m (1.25%)
Memory requests (bytes): 1.12Gi (3.58%)
Memory limits (bytes): 220.00Mi (0.69%)

### Your personal set up

Kubernetes self-hosting bare-metal cluster.
 - OS:
 
Linux 5.4.0-48-generic
 - Version:
 
Jupyterhub 0.9.0
 - Configuration:
 
I installed Jupyterhub based of this folder  https://github.com/jupyterhub/zero-to-jupyterhub-k8s/tree/master/jupyterhub

**Comment by consideRatio** [comment]
Set scheduling.userScheduler.enabled to false if you dont want that. It is intentional to help autoacaling down more efficiently.
