### ISSUE TITLE
Add template comparisons for rendered K8S manifests to compare changes

### ISSUE THREAD

**Issue by manics** [jupyterhub/zero-to-jupyterhub-k8s#1849]
Problem: We're unable to test many configurations due to regular testing being limited to a virtual cluster that can run on CI platforms, (currently K3S). For example, it's not possible to test public cloud loadbalancers https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1811.

One thing I've used in other projects involving templates is to have a set of "reference outputs" that are updated whenever something changes. As part of CI tests checks a `diff` is done to compare the templates output from the test with those reference ones, and CI fails if there's a difference.

For example: https://github.com/ome/ansible-role-nginx-proxy/tree/1.13.0
- Templates: https://github.com/ome/ansible-role-nginx-proxy/tree/master/templates
- References for the test: https://github.com/ome/ansible-role-nginx-proxy/tree/master/molecule/default/files/etc-nginx
- Example PR that changed a template and therefore the references were updated: https://github.com/ome/ansible-role-nginx-proxy/pull/29/files

For Z2JH this would mean running `helm template` for multiple values files with corresponding references and looking at the differences. Although this isn't a real test it's a lot easier to see and review changes with reference to the previous "known good" output than it is to reason about logic changes in templates. This is also helpful for reviewing changes that impact current CI tests.

The big downside is it increases the effort required to make changes to the templates.

What do you think? Or can you think of a way to achieve something like this with a smaller burden?

**Comment by consideRatio** [comment]
I'm afraid of anything that increase maintenance burden, but I think it would be a _very nice_ feature to be able to be informed about changes in the rendered output, similarly to codecov reports for example, for example using the lint-and-validate-values.yaml file under tools/templates/.

One could also consider the option of for example having `rendered-helm-templates` branch part of the repo that is automatically updated with the latest master chart template renderings. Then, as part of PR one could render the templates and output a `git diff` report which is converted to something markdown friendly perhaps.

The simpler to implement option is to always commit updated renderings of the templates, but hmmm, is it worth it? I lean towards no atm.

**Comment by consideRatio** [comment]
This was closed by https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1978
