### ISSUE TITLE
[DOCS] Move "Setup Helm" page so it's linked with k8s rather than JupyterHub

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/zero-to-jupyterhub-k8s#1861]
I always thought it a touch strange that the "Setup Helm" page was nested under "Setup JupyterHub" when I think it _really_ should be under "Setup Kubernetes". That being said, in terms of the file structure/organisation of the docs, I'm not sure where I should physically move the file to that would create my desired change on the website while still making sense in the repo 🤔 

<img width="770" alt="Screenshot 2020-10-21 at 16 09 32" src="https://user-images.githubusercontent.com/44771837/96739568-d5181400-13b7-11eb-8103-1e82903d458a.png">

**Comment by consideRatio** [comment]
@nerdsec may have done just this in the pr #1825 i think, if you think it is good i think we should go for a merge. It would be nice to have redirects to not break old links when the structure now change, but i dont have willpower to get it done myself.

**Comment by sgibson91** [comment]
Yes you're right, they have! Unfortunately, I have no experience with RTD redirects 😕

**Comment by consideRatio** [comment]
Closed by #1825
