### ISSUE TITLE
Manage redirects following docs restructures with sphinxext-rediraffe instead of RTD

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#1865]
As introduced in https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1825#issuecomment-713759673, and suggested in https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1825#issuecomment-714587547, we can use a tool called [sphinxext-rediraffe](https://github.com/wpilibsuite/sphinxext-rediraffe) to redirect.

Recently I added redirects [in RTD's admin section](https://readthedocs.org/dashboard/zero-to-jupyterhub/redirects/) which also work, but...
- only on the published site has redirects when using RTD's redirect system
- only RTD admins can view and configure the redirects
- the redirects won't be version controlled

So, having rediraffe do it for us as part of the built website comes with quite a bit of benefits. Anyone wanting to help us solve this would be appreciated. Currently, we have the following redirects on RTD that can be migrated.

RTD redirects this path... | to this path...
-|-
/customizing/user-management.html | /jupyterhub/customizing/user-management.html
/customizing/user-storage.html | /jupyterhub/customizing/user-storage.html
/customizing/user-resources.html | /jupyterhub/customizing/user-resources.html
/customizing/user-environment.html | /jupyterhub/customizing/user-environment.html
/customizing/extending-jupyterhub.html | /jupyterhub/customizing/extending-jupyterhub.html
/reference/glossary.html | /resources/glossary.html
/reference/tools.html | /resources/tools.html
/reference/reference-docs.html | /resources/reference-docs.html
/reference/reference.html | /resources/reference.html
/community/additional-resources.html | /resources/community.html
/community/users-list.html | /resources/community.html
/community/tips.html | /resources/community.html
/setup-jupyterhub/turn-off.html | /jupyterhub/uninstall.html
/setup-jupyterhub/setup-jupyterhub.html | /jupyterhub/installation.html
/setup-jupyterhub/setup-helm.html | /kubernetes/setup-helm.html
/ovh/step-zero-ovh.html | /kubernetes/ovh/step-zero-ovh.html
/digital-ocean/step-zero-digital-ocean.html | /kubernetes/digital-ocean/step-zero-digital-ocean.html
/ibm/step-zero-ibm.html | /kubernetes/ibm/step-zero-ibm.html
/redhat/step-zero-openshift.html | /kubernetes/redhat/step-zero-openshift.html
/amazon/step-zero-aws-eks.html | /kubernetes/amazon/step-zero-aws-eks.html
/amazon/step-zero-aws.html | /kubernetes/amazon/step-zero-aws.html
/microsoft/step-zero-azure-autoscale.html | /kubernetes/microsoft/step-zero-azure-autoscale.html
/microsoft/step-zero-azure.html | /kubernetes/microsoft/step-zero-azure.html
/google/step-zero-gcp.html | /kubernetes/google/step-zero-gcp.html
/create-k8s-cluster.html | /kubernetes/setup-kubernetes.html
/turn-off.html | /setup-jupyterhub/turn-off.html
/setup-jupyterhub.html | /setup-jupyterhub/setup-jupyterhub.html
/setup-helm.html | /setup-jupyterhub/setup-helm.html
/index-setup-jupyterhub.html | /setup-jupyterhub/index.html
/tools.html | /reference/tools.html
/reference-docs.html | /reference/reference-docs.html
/index-reference.html | /reference/index.html
/glossary.html | /reference/glossary.html
/user-storage.html | /customizing/user-storage.html
/user-resources.html | /customizing/user-resources.html
/user-management.html | /customizing/user-management.html
/user-environment.html | /customizing/user-environment.html
/index-customization-guide.html | /customizing/index.html
/extending-jupyterhub.html | /customizing/extending-jupyterhub.html
/users-list.html | /community/users-list.html
/tips.html | /community/tips.html
/index-community-resources.html | /community/index.html
/additional-resources.html | /community/additional-resources.html
/upgrading.html | /administrator/upgrading.html
/troubleshooting.html | /administrator/troubleshooting.html
/security.html | /administrator/security.html
/optimization.html | /administrator/optimization.html
/index-administrator-guide.html | /administrator/index.html
/debug.html | /administrator/debug.html
/cost.html | /administrator/cost.html
/authentication.html | /administrator/authentication.html
/architecture.html | /administrator/architecture.html
/advanced.html | /administrator/advanced.html

Note that when RTD does these redirects, it will redirect /en/latest/reference/reference.html to /en/latest/resources/reference.html, where the point I'm trying to make is that it is making the redirects relative to the base path of `/en/latest` or whatever base path we have, which also the new redirection system should.

**Comment by NerdSec** [comment]
I was wondering why we would need another plugin to do this.

> * only on the published site has redirects when using RTD's redirect system
> 
> * only RTD admins can view and configure the redirects
> 
> * the redirects won't be version controlled

This cleared it up!

**Comment by consideRatio** [comment]
This was closed by @NerdSec's excellent work in #1876 :heart: :tada:!!!

It helped my overcome the initial barrier of fear to use some new tech, it turned out to be a great tool that worked and did what we wanted without much or any issues. Thank you @choldgraf for suggesting it! :heart:
