### ISSUE TITLE
generic.oauthenticator: 500 Internal Server Error / 400 OAuth state missing from cookies

### ISSUE THREAD

**Issue by gunflap** [jupyterhub/zero-to-jupyterhub-k8s#1869]
### Context:
* I'm creating a **Dashboard** service where multiple users can access multiple notebook servers via `JupyterHub`. 
* Users log in using a separate **Authentication** service, and once in **Dashboard**, `JupyterHub` gets rendered inside an `<iframe>`.

### Setup:
* I'm hosting `JupyterHub` in a `Kubernetes` cluster on GCP. These are the relevant portions of my `config.yaml`:

```
...

 # Changes the Jupyter's notebook headers to allow it to be displayed
 # inside of an iframe object.
 c.JupyterHub.tornado_settings = {
        "headers": {
          "Content-Security-Policy": "default-src *  data: blob: filesystem: about: ws: wss: 'unsafe-inline' 'unsafe-eval' 'unsafe-dynamic'; script-src * data: blob: 'unsafe-inline' 'unsafe-eval'; connect-src * data: blob: 'unsafe-inline'; img-src * data: blob: 'unsafe-inline'; frame-src * data: blob: ; style-src * data: blob: 'unsafe-inline'; font-src * data: blob: 'unsafe-inline';",
        }
      }

...

  extraEnv:
    #Endpoints
    OAUTH2_AUTHORIZE_URL: "http://35.232.66.179:8000/o/authorize"
    OAUTH2_TOKEN_URL: "http://35.232.66.179:8000/o/token"

    # Jupyterhub callback (default: https://<host>/hub/oauth_callback)
    OAUTH_CALLBACK_URL: "http://35.196.54.180/hub/oauth_callback"

    # User information is used to name server created by kubespawner.
    OAUTH2_USERDATA_URL: "http://35.232.66.179:8000/userdata"
    OAUTH2_USERNAME_KEY: "username"
    OAUTH2_USERDATA_METHOD: "GET"

    # General settings
    OAUTH2_BASIC_AUTH: "false"
    OAUTH2_TLS_VERIFY: "true"

...

auth:
  type: custom
  custom:
    className: oauthenticator.generic.GenericOAuthenticator
    config:
      login_service: "OpenID" 
      client_id: "<client_id>"
      client_secret: "<client_secret>"
```
### Errors
However, when I try to sign in just via my `JupyterHub` endpoint I get:   **500 Internal Server Error**

**logs:**
```HTTPServerRequest(protocol='http', host='<>', method='GET', uri='/hub/oauth_callback?code=d37de16a855a49dda94fb65c2c2c8ffa&state=eyJzdGF0ZV9pZCI6IC
IwN2YyNzVhNTk0MzM0ZTM5YmIyZTdmZDQzY2U2ZDI3YyIsICJuZXh0X3VybCI6IG51bGx9&session_state=641fb9aca6490d2c3332871d72ee0639b3ed46b8a9f02c363ee8f7bf46f1c989.74e37d534296
cad45421019d1d442153', version='HTTP/1.1', remote_ip='<>')

    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1703, in _execute
        result = await result
      File "/usr/local/lib/python3.6/dist-packages/oauthenticator/oauth2.py", line 213, in get
        user = await self.login_user()
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py", line 699, in login_user
        authenticated = await self.authenticate(data)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/auth.py", line 383, in get_authenticated_user
        authenticated = await maybe_future(self.authenticate(handler, data))
      File "/usr/local/lib/python3.6/dist-packages/oauthenticator/generic.py", line 136, in authenticate
        resp_json = json.loads(resp.body.decode('utf8', 'replace'))
      File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
        return _default_decoder.decode(s)
      File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 5 column 1 (char 4)
```

I know it actually does redirect to the **Authentication Server** and the callback is correct. Even still when I attempt to access via **Dashboard**, within the `<iframe>` I get:

**400 OAuth state missing from cookies**

**logs:**
```
400 GET /hub/oauth_callback?code=d37de16a855a49dda94fb65c2c2c8ffa&state=eyJzdGF0ZV9pZCI6ICIwN2YyNzVhNTk0MzM0ZTM5Ym
IyZTdmZDQzY2U2ZDI3YyIsICJuZXh0X3VybCI6IG51bGx9&session_state=641fb9aca6490d2c3332871d72ee0639b3ed46b8a9f02c363ee8f7bf46f1c989.74e37d534296cad45421019d1d442153

OAuth state missing from cookies
```

###  Reference
I previously used the `Github OAuthenticator` class and registered an OAuth app within Github and got `JupyterHub` to work fine. However, Github does not allow their apps to be used within an `<iframe>` so I had to go the generic route. 

Point is, the setup was very similar and at least had `JupyterHub` working outside of **Dashboard**, so I'm really stumped on what else I could be missing. Any help is appreciated.

 - OS:
 macOS Mojave 
 - Version:
 JupyterHub version 0.9.0
 - Configuration:
 Helm Chart

**Comment by Gungo** [comment]
Apologies in case I misunderstood the way issues are run here @consideRatio, but I don't get exactly why my issue can't be opened. I attempted making a post on the discourse forum but it has not been verified yet. Any information on where I can seek help would be appreciated.

**Comment by consideRatio** [comment]
@Gungo no worries, thanks for bringing the issue of posting on discourse to my attention! Discourse automatically flagged it as suspicious because it was "typed" fast but I've approved it now.

I think that GitHubOAuthenticator as well as GenericOAuthenticator will run into the same issues with regards to being used as part of an IFrame, but I'm in generally quite confused about these matters as I don't really understand the security aspects to consider when using IFrames.

I hope someone can help you with regards to this!
Cheers from Sweden!

**Comment by Gungo** [comment]
@consideRatio Thanks for the update! The iframe issue is a bit worrying but all in all **JupyterHub** should at least be working by itself (as in visiting the ip not on **Dashboard**). I had this working when I used github as the oauthenticator class but like I said github does not allow their apps in an iframe.

 I'm a bit stuck on where to go from here but I'll keep digging, thanks again.

**Comment by Gungo** [comment]
@consideRatio I've yet to receive any feedback via the discourse forum. Is there any where else I can submit this issue to for feedback? I've combed through the other posts both on the forum and here but I've yet to find any posts with similar issues that can help. Thanks in advance for any guidance.

**Comment by manics** [comment]
If no-one's answered on the forum it usually means one of:
- no-one (including us maintainers) have an answer
- people need more time (3 days isn't very long, remember most people are volunteers)
- your issue isn't easily reproducible

**Comment by Gungo** [comment]
@manics No worries, I figured the issue was either very specific or no one got to it yet. I'm just wondering if there's any other resources out there you guys might know about that could steer me in the right direction.

**Comment by consideRatio** [comment]
@Gungo it is a tough question, I know too little about iframing applications to help you. My approach as a novice would be to try learn some foundational pieces of understanding that can be composed to understand the full challenge. So, I would first try learn as much about iframes restrictions related to security. I would then try to learn about GitHub OAuth2 from an iframe application generally. I would then finally try to compose this understanding into some concrete way forward.

But even if I could tell you more about iframes, please understand that it can quickly become unsustainable for maintainers of open source project to help everyone who asks for help. I suggest to try draw from existing resources that are less specific, such as how to iframe ANY webbsite that authenticates with GitHub or similarly.

Good luck @Gungo!
