### ISSUE TITLE
Replace Travis with GitHub workflows

### ISSUE THREAD

**Issue by manics** [jupyterhub/zero-to-jupyterhub-k8s#1872]
### Proposed change
Replace Travis CI with GitHub workflows

### Alternative options
Do nothing

### Who would use this feature?
People who are bored of waiting for Travis to run :smile: See https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1840#issuecomment-715262697
Anecdotally Travis seems to be getting slower and slower.

### (Optional): Suggest a solution
I've previously converted the [K3s and helm setup script from this repository into an action](https://github.com/manics/action-k3s-helm/) (was planning to use it for a different project but never got round to it) and I'm happy to convert this repo to use it.

There are other potential benefits mentioned in https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1840#issuecomment-715286827 but as a first step I suggest just reproducing the existing tests.

**Comment by consideRatio** [comment]
> I've previously converted the K3s and helm setup script from this repository into an action (was planning to use it for a different project but never got round to it) and I'm happy to convert this repo to use it.

This was a good viability demonstration for me! I have not seen any announcement or similar why TravisCI limited their workers as they have done the last days, which has caused the spike of jobs being queued up for too long durations.

![image](https://user-images.githubusercontent.com/3837114/97081220-29620480-1601-11eb-94ab-0dc35bfef614.png)

## Other significant reasons to use GitHub Actions over TravisCI
1. While it becomes a bit more complicated to introduce a composition of scripts to run, it helps us avoid duplicating logic which is common across for example z2jh, binderhub, and kubespawner and other outside org repositories like DaskHub.
2. GitHub Actions have the nice functionality of conditionally being triggered only when certain files change, which means that we don't have to helm chart tests of charts when we update the documentation only.

Overall, I'm in favor of switching to GitHub actions in this repo at least.

**Comment by manics** [comment]
I think your reason 1 is one of the best arguments for it. If there's a K8S/Helm problem in future it'll be a lot easier to debug the self-contained action repo without the rest of Z2JH getting in the way. It also means we have the option of adding tests to verify the base deployment of K8s (e.g. that network policies are functioning) without adding noise in this repo.

**Comment by consideRatio** [comment]
The TravisCI issues were resolved by a .org -> .com migration, but this is still relevant in my mind (https://github.com/jupyterhub/team-compass/issues/348)

**Comment by minrk** [comment]
👍 to migrating when someone feels like putting in the time! The travis-ci.com switch should take some of the pressure off.
