### ISSUE TITLE
What to execute with pre-commit for a good developer experience?

### ISSUE THREAD

**Issue by manics** [jupyterhub/zero-to-jupyterhub-k8s#1899]
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/44a531531a1f6a4a45e86243508a54b183ef56bb/ci/common#L1-L2
has clear instructions to verify the script on https://www.shellcheck.net/ 
It currently shows lots of warnings 😀

Shall we keep it or get rid of it? If we're keeping it we could enforce it's use with pre-commit using https://github.com/shellcheck-py/shellcheck-py#as-a-pre-commit-hook

**Comment by consideRatio** [comment]
I appreciate using it manually to catch things, so +1 for retaining the comment.

But, do we want to do more things with pre-commit that as a whole makes it worth introducing? Hmm...
- spellcheck sh/bash scripts
- helm lint helm chart
- black python scripts
- yamllint values.yaml file

I'd be open to introducing pre-commit, but I'm quite scarred from past installation failures :P I struggled so much to get it to work before, but now I have not had issues with it for a while.

**Comment by minrk** [comment]
I think pre-commit is most useful for auto-formatting. I love it when it fixes issues for me, I get annoyed when it tells me something I need to fix (*especially* style) unless it's a very basic clear error (e.g. invalid syntax, missing import). So I'd be +1 for black, and I've been googling for a bash autoformatter and found https://pypi.org/project/beautysh/ but haven't tried it. The furthest I would probably go on the rest is syntax-checking real yaml files (not templates). If shellcheck has an auto-fix function, I'd probably be for it.

**Comment by consideRatio** [comment]
> If shellcheck has an auto-fix function, I'd probably be for it.

I have used shellcheck a lot on my sh/bash scripts and know they have suggestions, but those suggestions are often not right, and a lot of warnings are not relevant - but, there are errors that so far always have been relevant. I'm +1 for using shellcheck to spot errors, but not to output information about warnings or suggestions due to the too often irrelevant warnings/errors.

**Comment by manics** [comment]
Thanks for your feedback. I'll start by enabling some autoformatters (black, maybe prettier) in a PR, and leave the potentially more controversial style configuration for a follow-up.

**Comment by consideRatio** [comment]
Thank you for your work on this @manics! :heart:

You described #1920 as part one of this issue, what do you consider to be the second part? We currently have `helm lint --strict` and `yamllint` (with associated lint-configuration) in the CI tests even though its not part of pre-commit. `helm lint --strict` is dependent on Helm version, and without using a helm version after ~3.2 or so it will be extremely strict which we don't want to comply with.

**Comment by manics** [comment]
I've been looking into adding shellcheck with exceptions (preview here: https://github.com/manics/zero-to-jupyterhub-k8s/commits/pre-commit-2), and maybe [prettier](https://prettier.io/docs/en/precommit.html#option-3-pre-commithttpsgithubcompre-commitpre-commit).

**Comment by consideRatio** [comment]
What remains to close this issue in my mind, is to deliberate on adding helmlint and/or prettier.

```yaml
  - repo: https://github.com/prettier/prettier
    rev: 2.1.2
    hooks:
      - id: prettier
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.10
    hooks:
      - id: helmlint
```
