### ISSUE TITLE
Instructions for authenticating with gcloud

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/zero-to-jupyterhub-k8s#19]
I'm running into a bunch of problems getting things to create using gcloud...we should add instructions for what to do if people run into these problems.

**Comment by ryanlovett** [comment]
What were the problems?

**Comment by choldgraf** [comment]
Yuvi and I chatted about it - we'll update the docs in the next few days

**Comment by amueller** [comment]
Also I feel like being explicit about all the steps would be good:

- create an gcloud account
- create a project in the gcloud account
- enable sdk for this project
- ``gcloud auth login``
- ``gcloud config set project VALUE``
- ``gcloud container clusters create ...``

**Comment by willingc** [comment]
I agree @amueller. Here's a link to some screenshots that I took about a month ago: https://github.com/willingc/learning_with_jupyterhub/tree/master/source/_static/images

**Comment by choldgraf** [comment]
totally agree as well - it's kind of a big PITA to set all of that up :P

**Comment by amueller** [comment]
I don't think it's that bad and it only took me a couple of minutes (well I'm not done but I think I'm done with the gcloud stuff?). But more explicit instructions mean less friction which is always better :)

**Comment by choldgraf** [comment]
Yeah - I think it's one of those things that is super easy once you know how to do it, but really confusing and opaque for a new user

**Comment by yuvipanda** [comment]
@choldgraf anything more we need to do here?

**Comment by choldgraf** [comment]
not in an actionable way anyway, I'm sure there are more ways to improve the gcloud instructions, but now we've got both gcloud and interactive shell instructions, so I think we should close this in lieu of spot-checking suggestions in their own issues
