### ISSUE TITLE
Old images remain on AWS EKS nodes indefinitely?

### ISSUE THREAD

**Issue by petebachant** [jupyterhub/zero-to-jupyterhub-k8s#1908]
### Bug description

We may have an unusual JupyterHub use case, but we rebuild and deploy images on the order of once per day. Everything works well except the nodes eventually fill up their storage and then fail to start servers.

#### Expected behaviour

Old images should be pruned so long as there are no containers running them.

#### Actual behaviour

Old images seem to persist for the entire node life.

### Your personal set up

We are running JupyterHub Helm chart v0.10.2 on AWS EKS with one user per node. Each node has 30 GB of storage.

**Comment by manics** [comment]
Hi! This is outside the scope of Z2JH. There's no way for Z2JH to know which is an old Jupyter image vs which is an image used by some other application.

If you'd like to discuss this further please use the community forum. Thanks!

**Comment by petebachant** [comment]
> Hi! This is outside the scope of Z2JH. There's no way for Z2JH to know which is an old Jupyter image vs which is an image used by some other application.
> 
> If you'd like to discuss this further please use the community forum. Thanks!

Alright, will do. Thanks!
