### ISSUE TITLE
Feature request: Ability to inject environment variables from a secret

### ISSUE THREAD

**Issue by bbockelm** [jupyterhub/zero-to-jupyterhub-k8s#1915]
### Proposed change
We would like to have the ability to inject secrets into the JupyterHub container as environment variables.

### Alternative options
It looks like it's possible to do this today with mounting the secrets as volumes.  I think doing this via environment variables is more straightforward to reference from the `jupyterhub_config.py` and this feature would provide symmetry to the volume mounts.

### Who would use this feature?

We use flux to deploy our Helm charts and locally have a strict policy of keeping any secrets or private content as a kubernetes secret.  That is, we treat the helm chart as if our git repo was accidentally leaked to the internet.  [Secrets are separately encrypted using bitnami's SealedSecrets operator.]

We've been struggling with adhering to this policy with the Z2JH Helm chart.  The current problem is the client secret for OAuth2 is kept in the helm chart.  We would like to:

1.  Inject this as an environment variable based on a secret.
2. Use `hub.extraConfig` to read the environment variable and configure the authenticator object appropriately.

### (Optional): Suggest a solution

Add a new key to `values.yaml` (`hub.extraEnvYaml`?) that is referenced from the hub's `deployment.yaml` template.

**Comment by manics** [comment]
Does https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1757 cover any of this?

**Comment by consideRatio** [comment]
@manics yepp!

> We would like to have the ability to inject secrets into the JupyterHub container as environment variables.

If you have created the k8s secret, you can reference it on the hub pod or the user pods for example. Here is the reference documentation for the user pods.

https://zero-to-jupyterhub.readthedocs.io/en/latest/resources/reference.html#singleuser-extraenv

**Comment by bbockelm** [comment]
Dang, I overlooked that part when I was examining the code.  I can confirm this was exactly what I'm aiming for!  (Wasn't obvious from the documentation).

Thanks!
