### ISSUE TITLE
travis building needs fixing after repo migration

### ISSUE THREAD

**Issue by minrk** [jupyterhub/zero-to-jupyterhub-k8s#192]
- [x] build.py is still building an index pointing to jupyterhub.github.io/helm-chart
- [x] travis deploy keys probably need to be regenerated for this repo (I think @yuvipanda started this yesterday, but hasn't finished setting it up)

**Comment by choldgraf** [comment]
I saw a few travis PRs merged...did those address these?

**Comment by minrk** [comment]
Yes, this is fixed The pushing is going to helm-chart on purpose. I was just confused. #194 fixed the failing builds on PRs.
