### ISSUE TITLE
Support multiple releases within the same namespace

### ISSUE THREAD

**Issue by janekbaraniewski** [jupyterhub/zero-to-jupyterhub-k8s#1921]
### Proposed change

Currently objects like `hub.deployment`, `proxy.deployment` and many more use hardcoded value for `name` attribute. This makes it pretty much impossible to have multiple jupyterhub releases running within the same k8s namespace.

### Who would use this feature?

Well, I would. And I'm happy to work on PR. 

### (Optional): Suggest a solution

Simple solution is to use Helm ``{{ Release.Name }}`` as a prefix in names of those objects.

**Comment by consideRatio** [comment]
Yes! This is an issue to fix, and it is perhaps one of the most pressing issues in this repo based on user feedback. Along with this, I also want us to support a `fullname` configuration like most Helm chart does as well.

I have created https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1791 to track this need. I would like to implement this specific PR myself as there are quite a bit of details I want implemented in a certain way. I'll ping you when the PR is ready for review in case you have time to help as a reviewer at that point in time. I hope to get down to this before new year.

**Comment by janekbaraniewski** [comment]
Great, thanks for the info :+1:
