### ISSUE TITLE
Cannot modify auth_state

### ISSUE THREAD

**Issue by kyprifog** [jupyterhub/zero-to-jupyterhub-k8s#1929]
Using version 0.10.2

I have a post_auth_hook in which I am attempted to modify the auth_state (or pass it on in any way shape or form):

```
def post_auth_hook(authenticator, handler, authentication):
    log("Running post auth hook")
    log(f"AUTHENTICATION: {authentication}")
    auth_state = authentication["auth_state"] 
    auth_state["monkey"] = "bananans"
    authentication["auth_state"] = auth_state
    log(f"AUTH NOW: {authentication}")
    return authentication
```
Which shows the values you would expect in the authentication hash that is being passed back.
But when I go into the SQL lite database and look it does not appear that the auth state is changing:

```
select * from users where name is  'USERNAME' limit 1;
2|USERNAME|0|2020-11-30 20:11:20.647034|2020-12-04 19:50:01.243342|29b227711e9c4f50ab6294f1f40c406f|{}|
```
Then after logging in I get:
```
2|USERNAME|0|2020-11-30 20:11:20.647034|2020-12-04 19:54:02.656352|29b227711e9c4f50ab6294f1f40c406f|{}|
```

The last active date is changing but the hash for the auth_state does not appear to have changed. As a result when I try to access it in other hooks I am always getting None:

```
async def pre_spawn_hook(spawner):
    auth_state = await spawner.user.get_auth_state()
    log(f"AUTH PRE SPAWN {auth_state}")
    return spawner
```

Results in `None`

I also tried to add an update_auth_state hook (as the documentation was not clear as to whether or not this was required for it to even work, if so should be the default IMO):

```
def userdata_hook(spawner, auth_state):
    log(f"AUTH_STATE FROM HOOK: {auth_state}")
    spawner.userdata = auth_state 
```

```
c.KubeSpawner.auth_state_hook = userdata_hook
```
But it appears that the auth_state in this hook is already `None`

**Comment by rkevin-arch** [comment]
Have you [enabled persisting auth_state](https://zero-to-jupyterhub.readthedocs.io/en/latest/resources/reference.html?highlight=auth_state#auth-state)?

**Comment by kyprifog** [comment]
I had enabled it, however, it was not configured correctly and the error was getting swallowed up.  Closing issue
