### ISSUE TITLE
Release plans - last release before 1.0.0 that will require helm3

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#1940]
I propose that we cut 1.0.0 in not too long time, following 0.11.0 in december. What do you think?

### 0.11.0 - December - [associated milestone](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/milestone/8)
I want to make this quite soon with bug fixes and a bump of JupyterHub to 1.3.0 which was released today.

### 1.0.0 - First release in 2021? - [associated milestone](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/milestone/7)
I want this to start require Helm3 which would allow us to make use of the `lookup` function in our templates to no longer require setting proxy.secretToken and other secrets we manually create.

**Comment by manics** [comment]
Sounds fine to me!

Only thing I'd consider removing from the 1.0.0 milestone is https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1712 since it's marked as `help wanted` and it shouldn't require breaking changes.

**Comment by consideRatio** [comment]
@manics is it possible to make a GitHub milestone track optional parts?

I agree it isn't required to get for the 1.0.0 release as it can be added after as well without any breaking changes! I like having #1712 as a goal towards the 1.0.0 release still though as it improves our security posture a bit which feels sensible to aim for before 1.0.0 as well.

**Comment by manics** [comment]
> is it possible to make a GitHub milestone track optional parts

No, but you could apply a label? Though stating it's optional in this issue is probably good enough.

**Comment by consideRatio** [comment]
0.11.0 released and I have announced that future versions won't require at least k8s 1.16 and helm 3
