### ISSUE TITLE
ci: intermittent k8s 1.19 and 1.20 test failures

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#1962]
I saw this issue in the CI system, it was showing up in a k8s 1.20 test that was just added. I'm not sure what is the cause yet, but it would be nice to print more info than the status code as a first step and then debug further.

```
    @pytest.fixture(scope="function")
    def jupyter_user(api_request):
        """
        A temporary unique JupyterHub user
        """
        username = "testuser-" + str(uuid.uuid4())
        r = api_request.post("/users/" + username)
        assert r.status_code == 201
        yield username
        r = api_request.delete("/users/" + username)
>       assert r.status_code == 204
E       assert 400 == 204
E         +400
E         -204
```

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1961/checks?check_run_id=1594410192

## Update

The failure is intermittent, about 50% of the time in our ci tests. I added some logging and such allowing the failure to be inspected [in this run](https://github.com/consideRatio/zero-to-jupyterhub-k8s/runs/1596599338?check_suite_focus=true).

The conclusion I draw is that there is some pod termination issues in k8s 1.20, and it sais...

```
    State:          Waiting
      Reason:       PodInitializing
    Last State:     Terminated
      Reason:       ContainerStatusUnknown
      Message:      The container could not be located when the pod was deleted.  The container used to be Running
      Exit Code:    137
      Started:      Mon, 01 Jan 0001 00:00:00 +0000
      Finished:     Mon, 01 Jan 0001 00:00:00 +0000
```

To me, this is very confusing, but googling for k8s 1.20 and this message, I ended up in a k8s 1.20 issue. For reference, we are using k3s 1.20.0+k3s2 currently.

https://github.com/kubernetes/kubernetes/issues/97288

**Comment by consideRatio** [comment]
I think this will close with a future patch version of  k8s 1.20, see https://github.com/kubernetes/kubernetes/pull/97998.

**Comment by consideRatio** [comment]
Yikes! Now it is even worse!!!!

At least k8s 1.19 and 1.20 is acting up now. I assume a patch release introduced the same issue in k8s 1.19 also.

**Comment by dhirschfeld** [comment]
I've just started seeing this error too :(

**Comment by consideRatio** [comment]
Unexpected shutdowns could be a different error than what I observed, which was an _expected_ shutdown that turned bad. If you would do `kubectl describe pod <pod name>` and see the same message, then we have the same error I think.

```
    State:          Waiting
      Reason:       PodInitializing
    Last State:     Terminated
      Reason:       ContainerStatusUnknown
      Message:      The container could not be located when the pod was deleted.  The container used to be Running
      Exit Code:    137
```

Note though that I have not observed these intermittent failures for quite a while now in our CI system, and since the CI system use the latest available k3s distribution of k8s, I think its safe to say that the issue has been patched in a patch version of k8s and have propegated all the way to the k3s distribution of k8s that we are using in the CI system.

The solution in general I think would be to upgrade k8s past the patch version you currently have if you experience these issues. I'll go ahead and close this issue as it is an upstream issue that has been resolved.

**Comment by dhirschfeld** [comment]
I suspect there may be some other issue causing the shutdown but then I run into this one making it hard to debug further:
```
    State:          Waiting
      Reason:       ContainerCreating
    Last State:     Terminated
      Reason:       ContainerStatusUnknown
      Message:      The container could not be located when the pod was deleted.  The container used to be Running
      Exit Code:    137
      Started:      Mon, 01 Jan 0001 00:00:00 +0000
      Finished:     Mon, 01 Jan 0001 00:00:00 +0000
```

**Comment by dhirschfeld** [comment]
AKS has recently released 1.20.5 so I'm going to give that a go. Redeploying our AKS cluster will be a bit painful though :(

**Comment by consideRatio** [comment]
@dhirschfeld does upgrading k8s on AKS means redeploying the entire cluster?!!??!

**Comment by dhirschfeld** [comment]
> @dhirschfeld does upgrading k8s on AKS means redeploying the entire cluster?!!??!

I *thought* so, but it looks like it doesn't! :tada: 😅

**Comment by dhirschfeld** [comment]
...well, that fixed the k8s error:
```
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Sat, 01 May 2021 13:44:02 +1000
      Finished:     Sat, 01 May 2021 13:44:31 +1000
```

I'm still none-the-wiser why it's shutting down (with exit code 0?). More debugging to do...

**Comment by consideRatio** [comment]
singleuser.startTimeout i think, i usually have 300 seconds. Isnt that the default in Z2JH? Hmm...

**Comment by dhirschfeld** [comment]
Turns out it was just user error in my start script 😬

Whilst I did run into this issue it wasn't the *cause* of the unexpected termination.

**Comment by consideRatio** [comment]
Thanks for the followup @dhirschfeld! :heart:

For any AKS users out there, don't use 1.20.2, upgrade to 1.20.5 or I think 1.20.4 may be enough as well.
