### ISSUE TITLE
allow extending jupyterhub_config.py from files

### ISSUE THREAD

**Issue by scauglog** [jupyterhub/zero-to-jupyterhub-k8s#1987]
### Proposed change

It would be nice if we can extend jupyterhub_config by adding file in a folder like https://tljh.jupyter.org/en/latest/topic/escape-hatch.html#extending-jupyterhub-config-py

### Who would use this feature?

This could be used to pass sensitive information like password or token used in jupyter_config.py without setting them during chart installation otherwise the entire values.yaml should be encrypted if we want to persist it in a git repository. It will allow to provide those sensitive value from secret already present in kubernetes that we can mount as folder.

**Comment by consideRatio** [comment]
Hi @scauglog! I agree, this would be useful! I'll go ahead and close this in favor of the issue I just referenced this issue from (see link above this comment).

Thanks for chiming in!
