### ISSUE TITLE
template failure when custom: is empty

### ISSUE THREAD

**Issue by chrisbulgaria** [jupyterhub/zero-to-jupyterhub-k8s#1998]
### Bug description
secrets.yaml fails to render if Values.custom is empty

```
Error: template: jupyter/charts/jupyterhub/templates/proxy/deployment.yaml:28:32: executing "jupyter/charts/jupyterhub/templates/proxy/deployment.yaml" at <include (print $.Template.BasePath "/hub/secret.yaml") .>: error calling include: template: jupyter/charts/jupyterhub/templates/hub/secret.yaml:12:52: executing "jupyter/charts/jupyterhub/templates/hub/secret.yaml" at <$values.custom>: wrong type for value; expected map[string]interface {}; got interface {}
```

Appears to be this line

```
 {{- $_ := set $values "custom" (merge dict $values.custom .Values.hub.extraConfigMap) }}
```

Something like this:

```yaml
custom:
  a: b
```

fixes it (custom: {}  does not) 

### Your personal set up

JH 0.11 , Helm 3.34

**Comment by consideRatio** [comment]
@chrisbulgaria can you provide your passed config?

The default value from the Helm chart is already `{}`, so I'm confused what's going on.

**Comment by chrisbulgaria** [comment]
Hi, yes , must be related to my specific setup (calling helm from terraform , can indeed not reproduce with plain helm). So will investigate there further , certainly not a JH problem :)
Thanks for the quick help, should have investigated myself first further before logging an issue.

**Comment by guillemborrell** [comment]
@chrisbulgaria I've just found the exact same issue deploying JH with Terraform. Thanks for posting the fix here.

**Comment by stephenjones5543** [comment]
I found this issue too, thanks for posting this.

**Comment by consideRatio** [comment]
Are you all using terraform?

Do you have entries with `custom` in your config? If someone has time, I'd appreciate some insights into your issue and what you are doing to fix it. There are some tricks that could be adopted to provide better error message (schema validation #1316), and it's worth considering creating a workaround where `custom` would to accept a blank string being passed as something to ignore.

**Comment by chrisbulgaria** [comment]
I guess its a problem in the terraform helm provider - somewhere translating {} to nil .

If we have no custom in the values file or a custom: {}  (which is anyway the default ) it fails. Fails with an almost empty test case having nothing todo with JH. Plain helm on the same chart works. The workaround is to put something more into the custom , like

custom:
  a :  b

Im digging a bit deeper will raise an issue with the helm provider eventually.

**Comment by echarles** [comment]
Same issue with crossplane (not terraform), which also uses the native go helm client.

The hack did the job, but prolly this desserves a solution in the jupyterhub helm chart.

**Comment by consideRatio** [comment]
@echarles the line causing the issue is removed in latest dev release.

Thw prioeity should be to fix this in terraform or wherever it makes sense to fix to solve it once qnd for all. Anyone have a link to an issue where the issue belongs?

I dont want to workaround anything unless its very clearly motivivated. I believe providing workarounds for other projects issues can be a maintenance burden beyond limit.

**Comment by chrisbulgaria** [comment]
Hi ,
In the terraform helm provider this was fixed , see the issue linked above . Think by upgrading to the latest version of some helm go libraries , so the issue seems to have been there. Maybe crossplane is still on the older versions ?
Chris
