### ISSUE TITLE
"hub" pod is Crashing when installing jupyterhub/k8s-hub:0.9.0  using zero-to-jupyterhub-k8s-0.9.0 helm chart

### ISSUE THREAD

**Issue by Mahi-star-tech** [jupyterhub/zero-to-jupyterhub-k8s#1999]
When installing  jupyterhub/k8s-hub:0.9.0 using helm, the "hub" pod is crashing.

### Bug description
```
(base) [root@kmaster helm]# kubectl --namespace=jupyternew get pod
NAME                                             READY          STATUS             RESTARTS   AGE
hub-5c4ccc5d45-6nmz4                  0/1          CrashLoopBackOff   1          18s
proxy-957878959-t8pxw                  1/1        Running                   0          18s
user-scheduler-59bb4b9f54-kx757   1/1       Running                   0          18s
user-scheduler-59bb4b9f54-wjfgx   1/1        Running                   0          18s
(base) [root@kmaster helm]# kubectl describe pod hub-5c4ccc5d45-6nmz4  --namespace=jupyternew

(base) [root@kmaster helm]# kubectl logs hub-5c4ccc5d45-6nmz4 --namespace=jupyternew
ERROR: Failed to find specified config file: /etc/jupyterhub/jupyterhub_config.py
```

There is no issue however  when installing jupyterhub/k8s-hub: 0.8.2  using zero-to-jupyterhub-k8s- 0.8.2 helm chart.

In  jupyterhub/k8s-hub:0.8.2 , the below statement are present in the Dockerfile: 

`ADD file:c38e09b1901a4bc291728db98153365d747df9c7db774cc173cc7aa1a1653ea2 in /srv/jupyterhub_config.py` 
`CMD ["jupyterhub" "--config" "/srv/jupyterhub_config.py"]`

but in 0.9.0, the ADD/COPY is missing 
`CMD ["jupyterhub" "--config" "/etc/jupyterhub/jupyterhub_config.py"]` 

 

Supported helm version:

Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}

**Comment by consideRatio** [comment]
Are you using a custom docker image? We transitioned away from embedding the jupyterhub_config.py from being built into the image, but instead mounts it from a configmap.

Note that you are using a version of Helm, 2.1.0, which is too outdated also, at least 2.16 is required I think. Upgrade helm to the latest 2.17 version, or migrate to helm 3 directly which will be required for the release after 0.11 of the helm chart.
