### ISSUE TITLE
Instructions for requesting different machine types from the cloud provider

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/zero-to-jupyterhub-k8s#20]
Often we need to request different kinds of computers from the cloud provider. We should document things like:

`--machine-type=n1-highmem-2`

on gcloud and other platforms.

**Comment by yuvipanda** [comment]
I've been thinking more about this, and am wondering if it's something we should take responsibility for. I think if we link to the upstream cloud provider's docs and provide some general guidelines, that should be enough.

**Comment by willingc** [comment]
Closing as it looks like this has been done. See https://zero-to-jupyterhub.readthedocs.io/en/latest/create-k8s-cluster.html#setting-up-kubernetes-on-google-cloud item 5.
