### ISSUE TITLE
Package README.md with Helm chart (for artifactshub.io etc)

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#2011]
Without a README.md in the Helm chart, it won't be presented nicely at https://artifacthub.io/packages/helm/jupyterhub/jupyterhub. What needs to happen is that there is a README.md in the folder next to Chart.yaml when chartpress package the chart during publishing.

## Considerations
- __Do we add a dedicated README file / Do we copy the one from the root folder?__
  I lean towards copying the one from the root folder and if needed updating it to be sensible in both contexts.
  - [ ] Decision
    None.

**Comment by manics** [comment]
Can we make chartpress automatically copy and update the README?

**Comment by consideRatio** [comment]
@manics technically yes, do we want it? Maybe. I'd like to avoid adding assumptions that easily can break.

One broken assumption for example is that README.md references a local image, but the reference was relative within the git repo. It would work on GitHub in the root folder, but break when copied and published with the chart.

**Comment by manics** [comment]
OK. What are your thoughts on the content of the helm-chart README file? If it's just a link to some other documentation I think it makes sense to push it straight to the helm-chart repo.

If it's going to need updating I think it'd be better to have a dedicated file in this repo so we've only got one repo to update. Maybe add a chartpress flag that indicates it should be published in the helm-chart, and default to doing nothing?

**Comment by consideRatio** [comment]
Hmmmm I think lean towards adding a feature in chartpress to import some file before packaging the Helm chart, or perhaps providing a pre-package-hook to execute something that in turn can do whatever before packaging the helm chart repo.

__Such feature would be enabling...__
- Packaging of README.md, some image perhaps, LICENSE file
- A transformation of z2jh's custom schema.yaml into a Helm3 native values.schema.json.

__Readme to package?__
- I think we shouldn't attempt to reuse the jupyterhub/helm-chart (master branch) README.md file, it is not chart specific enough and serves a good purpose as it is.
- I think it's fine to import the z2jh github repo README into the package Helm chart.
