### ISSUE TITLE
netpol: hub pod (kubespawner) requires egress to k8s api-server (reliable fix / documentation needed)

### ISSUE THREAD

**Issue by cyrilcros** [jupyterhub/zero-to-jupyterhub-k8s#2019]
### Proposed change

I had issues getting redirected from the dummy auth login to the hub control panel. The connection would just hang. I realized I needed to disable the hub network policy, maybe because I am using kubernetes ingress-nginx + certmanager with disabled https for the proxy. The other netpols were fine when enabled (single user and chp).
The current documentation doesn’t say anything about network policy configuration for that type of ingress... see https://zero-to-jupyterhub.readthedocs.io/en/latest/administrator/advanced.html#ingress

### Alternative options

- Add documentation for that use case?
- Change the templates to accomodate people who set an ingress?
- Explain what labels should be added to the ingress controller?

### Who would use this feature?

Anyone who uses an ingress external to the chart, for example kubernetes/nginx-ingress. That’s very often the case for bare metal clusters with a loadbalancer like Metallb, I guess, or if you want to have all your ingresses managed by the same controller, or if you want to benefit from your own install of cert-manager.

**Comment by consideRatio** [comment]
@cyrilcros are you directing traffic to the proxy-public k8s Service? Not confident why it wont work.

Oh wait, what parts are installed in the k8s namespace julyterhub is running? Is ingress-nginx installed there too? (May influence network policy rules)

Do you have a parent helm chart depending on jupyterhub and ingress-nginx as well btw? (Influence labels -> may influence network policy rules)

**Comment by cyrilcros** [comment]
In my case, I have different namespaces: a `networking` one for ingress-nginx, who listens to ingress declarations in all other namespaces via ` kubernetes.io/ingress.class` annotations among others. I use this chart without any parents.
In the case of this chart, if an ingress is defined, you could use together:

-  `namespaceSelector: {}` to allow traffic from any namespace if an ingress is defined
- add during templating a common label to the ingress and network policy: you could add the label below to the ingress for example. https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/8b63e21327a8eeab06cc9ce6d743cac9374a2f65/jupyterhub/templates/hub/netpol.yaml#L47
- I don’t know if multiple Jupyterhub installs on the same cluster are a common use case, but you could consider a unique chart release name instead of `true` for the label.

**Comment by consideRatio** [comment]
Hmm... So currently I'm not understanding why this would be an issue in the first place, it was not meant to cause issues at all for these kinds of situations.

What version of the k8s helm chart are you using?

**Comment by cyrilcros** [comment]
0.11.1 for the version. I am not sure what happens when the hub netpol is enabled, because I get the login screen but no correct redirection after authenticating via the dummy auth (I get redirected to the hub but that doesn’t happen).
I can try checking if this is the ingress or egress that’s an issue here...

**Comment by consideRatio** [comment]
Thanks for working to investigate this! It would be helpful for me to reason about this along with you if you provide a redacted z2jh helm chart config and perhaps also logs from the hub and proxy during the time you have issues.

**Comment by cyrilcros** [comment]
I have this pastebin: https://pastebin.com/i0xg0wxA I messed up the CHP copy paste, here it is:

00:15:26.643 [ConfigProxy] info: Adding route / -> http://hub:8081
00:15:26.650 [ConfigProxy] info: Proxying http://:::8000 to http://hub:8081
00:15:26.650 [ConfigProxy] info: Proxy API at http://:::8001/api/routes
00:15:26.654 [ConfigProxy] info: Route added / -> http://hub:8081
00:15:38.857 [ConfigProxy] info: 200 GET /api/routes
00:15:38.899 [ConfigProxy] info: 200 GET /api/routes
00:15:38.902 [ConfigProxy] info: Adding route / -> http://hub:8081
00:15:38.902 [ConfigProxy] info: Route added / -> http://hub:8081
00:15:38.903 [ConfigProxy] info: 201 POST /api/routes/
00:17:02.312 [ConfigProxy] error: 503 GET /hub/ socket hang up
00:17:42.307 [ConfigProxy] error: 503 GET /hub/ socket hang up
00:18:42.630 [ConfigProxy] error: 503 GET /favicon.ico socket hang up
00:19:22.626 [ConfigProxy] error: 503 GET /favicon.ico socket hang up
00:26:07.023 [ConfigProxy] error: Failed to get custom error page: Error: socket hang up
    at connResetException (internal/errors.js:609:14)
    at Socket.socketOnEnd (_http_client.js:459:23)
    at Socket.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1223:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'ECONNRESET'

**Comment by consideRatio** [comment]
@cyrilcros aha! It seems like the hub pod isn't permitted to speak with the k8s api-server, which is required for kubespawner to function properly.

Hmmm hmmm hmmm...

Well, the hub pod must be allowed to communicate with the k8s api-server, but...

- how to allow that using the network policy for all kinds of k8s clusters?
- why does it work for the hub pod to speak with the k8s api-server in our test suite, it would make sense for it to fail there as well without such rule.

### This is the section of relevance

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/8b63e21327a8eeab06cc9ce6d743cac9374a2f65/jupyterhub/templates/hub/netpol.yaml#L62-L90

**Comment by consideRatio** [comment]
@cyrilcros could you verify my diagnosis that the only issue is that the hub pod is unable to speak with the k8s api-server?

```
# is the kubernetes service having an IP of 10.96.0.1 ?
kubectl get svc -A | grep kubernetes
```

```yaml
# will the hub pod (kubespawner) successfully communicate with the k8s api-server
# if we explicitly allow it?
hub:
  networkPolicy:
    egress:
      - ipBlock:
          cidr: 10.96.0.1/32
```

**Comment by consideRatio** [comment]
Btw, just found this video that was a nice intro to the networkpolicy resource in general.

https://www.youtube.com/watch?v=3gGpMmYeEO8

**Comment by consideRatio** [comment]
@cyrilcros oh! Now I see why the hub can communicate in our CI system to the k8s api-server.

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/8b63e21327a8eeab06cc9ce6d743cac9374a2f65/jupyterhub/values.yaml#L100-L109

Then I'm confused in another way instead.

Can you do `kubectl get netpol -o yaml hub`? I'd like to inspect your egress section.

**Comment by cyrilcros** [comment]
Adding that egress rule did not change thing. You were correct about the kubernetes API being assigned the 10.96.0.1 IP. Truncating a bit:

......
  labels:
    app: jupyterhub
    app.kubernetes.io/instance: jupyterhub
    chart: jupyterhub-0.11.1
    component: hub
    heritage: Tiller
    release: jupyter
......
  name: hub
  namespace: bioinfo
  resourceVersion: "18246443"
  uid: e0bb8843-77c1-4460-9253-641b2f2d37be
spec:
  egress:
  - ports:
    - port: 8001
      protocol: TCP
    to:
    - podSelector:
        matchLabels:
          app: jupyterhub
          component: proxy
          release: jupyter
  - ports:
    - port: 8888
      protocol: TCP
    to:
    - podSelector:
        matchLabels:
          app: jupyterhub
          component: singleuser-server
          release: jupyter
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
  ingress:
  - from:
    - podSelector:
        matchLabels:
          hub.jupyter.org/network-access-hub: "true"
    ports:
    - port: http
      protocol: TCP
  podSelector:
    matchLabels:
      app: jupyterhub
      component: hub
      release: jupyter
  policyTypes:
  - Ingress
  - Egress

**Comment by consideRatio** [comment]
Do you happen to be running on Azure AKS? What k8s cluster do you run on, and do you know what network policy controller is used there (the component that enforce the NetworkPolicy resources).

**Comment by cyrilcros** [comment]
This is a 3  node self managed cluster, I use metallb as a loadbalancer, ingress-nginx as my ingress controller. My CNI is [Cilium 1.9.3](https://docs.cilium.io/en/stable/gettingstarted/k8s-install-default/). No IPV6 in use. Kubernetes is version 1.20.
Thank you for taking the time to debug this with me, but I am afraid Cilium is the issue in the end. See https://github.com/cilium/cilium/issues/14239 for example, `Add support for podCIDR in k8s netpol:`

**Comment by consideRatio** [comment]
Thanks for putting in the work to debug it on your end as well, I'm glad we could arrive at a clear conclusion about this! Cheers!
