### ISSUE TITLE
/usr/local/etc/jupyterhub/jupyterhub_config.d subdirectory made jupyterhub fail to start

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#2022]
I mounted extra configuration to the /usr/local/etc/jupyterhub/jupyterhub_config.d folder. Using a k8s configmap without `subPath` in the volumeMount, it meant that I not only added a my_config.py file, but k8s also created a hidden folder as it does.

This led to z2jh's jupyterhub_config.py crashed while loading files from the jupyterhub_config.d folder, as it detected a folder and got upset.

```
      File "/usr/local/etc/jupyterhub/jupyterhub_config.py", line 415, in <module>
        with open(f"{config_dir}/{file_name}") as f:
    IsADirectoryError: [Errno 21] Is a directory: '/usr/local/etc/jupyterhub/jupyterhub_config.d/..2021_02_02_10_04_22.654959900'
```

@minrk @yuvipanda do you think we should ignore or include content within subdirectories of the jupyterhub_config.d folder?

## Action point
- [x] Decide on how to act regarding directories under the jupyterhub_config.d folder - ignore and warn or load files recursively?
- [x] Implement decision

**Comment by minrk** [comment]
I don't think we should iterate recursively. This should be fixed pretty straightforwardly by changing from `os.listdir(config_dir)` to list all files to `glob.glob(f"{config_dir}/*.py")`. We shouldn't ever be `exec`ing any files that aren't .py.

**Comment by minrk** [comment]
Probably `sorted(glob.glob(...))` for good measure, to allow consistent loading in lexicographical order.

**Comment by yuvipanda** [comment]
Agree with @minrk

**Comment by consideRatio** [comment]
Thanks for the input, PR #2023 opened with the implementation!
