### ISSUE TITLE
PVC reclaimPolicy configuration option

### ISSUE THREAD

**Issue by cyrilcros** [jupyterhub/zero-to-jupyterhub-k8s#2026]
With more experience, I now think having a delete reclaimPolicy is a good default, and it is out of scope for this chart to suggest a cluster wide policy change.

_Originally posted by @consideRatio in https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/901#issuecomment-473706839_

I too would like to switch to the `Delete` policy, but currently it seemed to be still set on `Retain` (PVs remain after I delete the PVC) _even if my storage class use_ `Delete`. 
Could we please get an option to change this?

**Comment by manics** [comment]
Hi! This sounds like a configuration issue on your K8S cluster as opposed to something Z2JH can handle.

I don't think there's anything we can do in Z2JH, but if you ask on the [community forum](https://discourse.jupyter.org/) where more people hang out someone might know. Be sure to give as much detail as possible about your deployment and underlying cluster.
