### ISSUE TITLE
serviceMonitor ressource for the chart

### ISSUE THREAD

**Issue by hobertlab** [jupyterhub/zero-to-jupyterhub-k8s#2029]
### Proposed change

Introduce CoreOS `serviceMonitor` ressources to help observe the deployment. Adding (more) some documentation about how to use the metrics endpoint would be nice (ie Prometheus configuration file).

### Who would use this feature?

Anyone interested in  the recent dashboard / observability proposals (ex #1626 ), but you do need Prometheus.

### (Optional): Suggest a solution

See [here for an example use  in a chart](https://github.com/helm/charts/blob/master/stable/metallb/templates/servicemonitor.yaml).

- add a serviceMonitor template
-  add a `prometheus.serviceMonitor.enabled` to the `values.yaml`

**By the way:** I tried to get this to work but I get a 403 forbidden, you may need a service / API token to be added as well to the jupyterhub config?

**Comment by manics** [comment]
I don't think we should add more dependencies directly to this chart due to the maintenance overhead- the more components that are added to the chart the harder it is to keep up to date and test. However if you've got an example repository we could link to it from the docs as an example.

**Comment by consideRatio** [comment]
Yes I align with @manics opinion, we have opted to avoid various third party dependencies that are useful but not required for this Helm chart in the past and I believe this is another such decision.

> Adding (more) some documentation about how to use the metrics endpoint would be nice (ie Prometheus configuration file).

I agree that references on how to setup monitoring with prometheus / grafana would be relevant, but to comply with the scope of this guide it should be limited in scope linking out to external guides on how to do it as it is a big topic all by itself.
