### ISSUE TITLE
Refactor handling of schema page

### ISSUE THREAD

**Issue by willingc** [jupyterhub/zero-to-jupyterhub-k8s#204]
The new schema page build italicizes everything when built on RTD. The theme's rendering of fonts is being overwritten.

**Comment by choldgraf** [comment]
Sorry for slow uptake on this - just got back from being outta the country on a trip. I just checked here:

https://zero-to-jupyterhub.readthedocs.io/en/latest/schema.html

and things seem to render OK. Is this a problem with a different theme we're considering using in the future?

**Comment by willingc** [comment]
I finally found the root cause of this italicizing mystery. It's an issue with the alabaster theme and Safari https://github.com/bitprophet/alabaster/issues/100 when the Goudy font is installed. Uninstall Goudy systemwide and life is good again 👍 

Closing as upstream is working on it. Sorry for the confusion @choldgraf.
