### ISSUE TITLE
[Questions] How to create their own namespace for each user.

### ISSUE THREAD

**Issue by lidongze0629** [jupyterhub/zero-to-jupyterhub-k8s#2053]
### Proposed change

The notebook-server pod run in the same namespace with JupyterHub components (hub/proxy/user-scheduler), I want to know is there any way I can create their own namespace (such as by username) for each user, and server pod running in it.

**Comment by consideRatio** [comment]
Hi @lidongze0629, could you raise this as a question in the discourse.jupyter.org forum?

**Comment by lidongze0629** [comment]
> Hi @lidongze0629, could you raise this as a question in the discourse.jupyter.org forum?

Thanks. I will do that.
