### ISSUE TITLE
User Collobaration

### ISSUE THREAD

**Issue by alpha-nome** [jupyterhub/zero-to-jupyterhub-k8s#2059]
Hi, 

Is there a way to give access to a user lab to multiple users for collaboration? 

Right now, Its a hub for multiple users notebooks. What if users can share edit, read only access to their notebooks. Is something like this coming up? 

If not, any hacky way to handle something like this?

**Comment by manics** [comment]
Hi! This is outside the scope of JupyterHub but is something that's been actively discussed. Please have a look at the [Jupyter community forum](https://discourse.jupyter.org/) if you'd like to find out more.
