### ISSUE TITLE
Upgrading JupyterHub versions documentation

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/zero-to-jupyterhub-k8s#207]
Right now, if you upgrade JupyterHub with the helm chart, the pod goes into a crashloopbackoff:

```
[I 2017-09-27 19:31:11.322 JupyterHub app:837] Loading cookie_secret from env[JPY_COOKIE_SECRET]
hub.concurrent-spawn-limit 64
singleuser.uid 1000
singleuser.fs-gid 1000
singleuser.storage.type none
singleuser.storage.extra-volumes []
singleuser.storage.extra-volume-mounts []
auth.type dummy
admin.access True
cull.enabled True
cull.timeout 3600
cull.every 600
cull.users True
hub.services {'binder': {'admin': True}}
hub.base_url /
hub.db_url sqlite:///jupyterhub.sqlite
singleuser.cmd jupyter-notebook
Found database schema version af4cbdb2d13c != 3ec6993fe20c. Backup your database and run `jupyterhub upgrade-db` to upgrade to the latest schema.
```

We need to either automate the upgrade or provide explicit instructions on how to do so.

**Comment by yuvipanda** [comment]
@minrk how do you feel about automating the upgrade for the default case (sqlite db on a PVC)? We can do the backup + upgrade...

Am happy for us to also not tackle this now and only provide very explicit instructions instead.

**Comment by minrk** [comment]
For sqlite, I think clear backup and upgrade is the way to go. Make sure to document where the backup is and how to rollback.

For 'real' dbs, I don't have enough confidence in how to do a good backup & restore to do it on behalf of people, but maybe someone else who has more experience can tackle this in a robust way.

**Comment by choldgraf** [comment]
we now have this section! https://zero-to-jupyterhub.readthedocs.io/en/latest/upgrading.html
