### ISSUE TITLE
hub.extraFiles not working as expected

### ISSUE THREAD

**Issue by AdrianSanchezLopez** [jupyterhub/zero-to-jupyterhub-k8s#2076]
### Bug description
The new functionality on the lastest version 0.11.1 does not seem to make any effect, as the [docs](https://zero-to-jupyterhub.readthedocs.io/en/latest/resources/reference.html#hub-extrafiles) say

Adding a simple config setup such as:
```
hub:
  extraFiles:
    my_image:
      mountPath: /tmp/test.txt
      stringData: |
        hello world!
```
does not inject it into the Hub's pod (double checked with a simple exec into the pod, and files are not there)

### My personal set up
Using: 
- minikube version: `v1.15.1`
- kubectl:  `Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
`
- helm: `version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}`
- helm chart: `jupyterhub/jupyterhub 0.11.1`

**Comment by consideRatio** [comment]
Hmmmm, if I recall correctly, perhaps you need to use the absolute latest version rather than 0.11.1 to use hub.extraFiles ? Try upgrading to `0.11.1-n270.he08bb7f8`

**Comment by consideRatio** [comment]
Yepp confirmed, that has not been released yet but you can can use it anyhow in the dev release version I linked above.
