### ISSUE TITLE
Upgrade to master causes failure due to user-scheduler pdb

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/zero-to-jupyterhub-k8s#2078]
### Bug description

Since https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/2039, upgrading from a lower version of z2jh to master causes failure with this:

Error: UPGRADE FAILED: cannot patch "user-scheduler" with kind PodDisruptionBudget: PodDisruptionBudget.policy "user-scheduler" is invalid: spec: Invalid value: policy.PodDisruptionBudgetSpec{MinAvailable:(*intstr.IntOrString)(0xc04d3c4be0), Selector:(*v1.LabelSelector)(0xc04d3c4c00), MaxUnavailable:(*intstr.IntOrString)(0xc04d3c4c40)}: minAvailable and maxUnavailable cannot be both set

Instead, the upgrade should happen silently, with the pdbs automatically adjusted.

**Comment by consideRatio** [comment]
Hmmmm ah... I switched to using minAvailable, and you have config that is maxUnavailable explicitly set.

So, this was breaking for anyone with explicit specification of maxUnavailable. Is it correct you have it specified explicitly?

**Comment by yuvipanda** [comment]
I haven't set maxUnavailable explicitly, it looks like maybe helm didn't unset it properly? I'm upgrading other hubs, will report back.

**Comment by yuvipanda** [comment]
I could not reproduce, so closing this for now
