### ISSUE TITLE
Feature request: list secrets to mount into the single user exec

### ISSUE THREAD

**Issue by holdenk** [jupyterhub/zero-to-jupyterhub-k8s#2097]
It would be really useful for my environment to be able to specify additional secrets to be mounted and mapped to env variables in the single user exec (e.g. minio/storage creds etc.).

**Comment by consideRatio** [comment]
To let usrers choose what to mount would be a big security concern unless first curated by the admin. I think this is a feature to specific, and that the current solution would be to use the profile_list feature in KubeSpawner (singleuser.profileList in this chart) or a custom jupyterhub options_form which the profile list really is - HTML to present options to the users as a set of pre-designed choices.

**Comment by consideRatio** [comment]
If you dont want users to choose, but specify them yourself as an admin, you just use singleuser.extraVolumes abd singleuser.extraVolumeMounts btw.

**Comment by holdenk** [comment]
Thanks Erik :) So if I do those two I couldn't figure out how to map the secrets to env variables, I thought we needed something else in the template for that.

**Comment by consideRatio** [comment]
To set env vars from a secret, see the singleuser.extraEnv section in the configuration reference at z2jh.jupyter.org - its also possible

**Comment by consideRatio** [comment]
There is plenty of room for improvements in the docs in general, contributions and feedback on docs structure, sections etc are very welcome!

I hope this nudge helped @holdenk!

**Comment by holdenk** [comment]
Thank you :)
