### ISSUE TITLE
the configurable-http-proxy jump is slowly

### ISSUE THREAD

**Issue by day-code** [jupyterhub/zero-to-jupyterhub-k8s#2098]
![QQ截图20210315180551](https://user-images.githubusercontent.com/69946103/111136852-1d2f1180-85b9-11eb-8c76-937ee3d7dcbc.png)

**Comment by consideRatio** [comment]
This is too vague @day-code, it is unsustainable for open source projects to be maintained with single sentence issues - please add a more context and description.

**Comment by day-code** [comment]
I open /user/admin/notebooks/Untitled3.ipynb very slowly .How to make /notebooks/ pages open faster

**Comment by consideRatio** [comment]
Not sure, but it is probably more a question for jupyterlab or the javascript running in the browser than for this project.
