### ISSUE TITLE
Allow administrators to specify different service accounts for different users

### ISSUE THREAD

**Issue by holdenk** [jupyterhub/zero-to-jupyterhub-k8s#2103]
### Proposed change

It would be useful to have different users associated with different service accounts similar to how different users can have different volumes (e.g. isolation).

### Alternative options

Seperate JupyterHub launchers in different namespaces for each user.

### Who would use this feature?

multi-tenant environments

### (Optional): Suggest a solution

There is already a `service_account` field in kubespawner, we'd have to allow to be configured by user as well.

**Comment by consideRatio** [comment]
Hi @holdenk!

You can get total freedom of the logic that sets a service account of a user pod based on the user identity by configuring a pre_spawn_hook that adjust the settings specifically for that user before spawn. Note that if a user would be free to choose a user account freely, it would be a security concern.

In practice you would set `c.KubeSpawner.pre_spawn_hook` (was it called pre_start_hook? I've forgot) to be a function that would be called with a KubeSpawner instance specific for the server about to spawn that you would modify with arbitrary Python logic.

**Comment by holdenk** [comment]
Oh cool :) I'll look into the pre_spawn_hook to do this :) Thank you :)
