### ISSUE TITLE
pyspark library is missing from jupyter/pyspark-notebook when running with jupyterhub/zero-to-jupyterhub-k8s

### ISSUE THREAD

**Issue by uluzox** [jupyterhub/zero-to-jupyterhub-k8s#2110]
### Bug description
pyspark library is not available in the pyspark-notebook when running on jupyterhub.

When running jupyter/pyspark-notebook locally, I can import pyspark as I would expect:
```
from pyspark import SparkConf, SparkContext
```
-> no errors

When I run jupyter/pyspark-notebook with my jupyterhub/zero-to-jupyterhub-k8s helm installation, the same code returns:
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-ee46be618299> in <module>
----> 1 from pyspark import SparkConf, SparkContext

ModuleNotFoundError: No module named 'pyspark'
```

Running `python -m pip list --format columns`. Does return a lot of installed modules however not the pyspark module.

Having read https://stackoverflow.com/a/31541051/5930295 I tried to update the sys.path because I found that pyspark is installed in the container under the following locations. Running:
```
import sys
sys.path.insert(0, '/usr/local/spark/python')
sys.path.insert(0, '/usr/local/spark/python/lib/py4j-0.10.9-src.zip')

from pyspark import SparkConf, SparkContext
```
-> No errors

### Further information
I thought the issue must be with the image. Therefore I originally opened a ticket with jupyter/docker-stack (https://github.com/jupyter/docker-stacks/issues/1255).

### Your personal set up
jupyterhub/zero-to-jupyterhub-k8s Helm Chart

jupyter/pyspark-notebook:9fe5186aba96 as default image

```
singleuser:
  defaultUrl: "/lab"
  image:
    name: jupyter/pyspark-notebook
    tag: 9fe5186aba96
```

**Comment by manics** [comment]
Hi :wave: This sounds like a configuration problem rather than a bug. Do you mind posting this as a support question on https://discourse.jupyter.org/ instead? Thanks!

**Comment by uluzox** [comment]
ok. I posted my support request. However it needs approval before it to become visible

**Comment by manics** [comment]
@uluzox Unfortunately I don't have permission to see/approve your Discourse post (someone else should though). In the meantime in both the working and non-working environments could you:
- Run `env | sort` in a terminal
- Run a python notebook with
  ```python
  import os
  for k, v in sorted(os.environ.items()):
      print(f'{k}={v}')
  ```
And add all the outputs to your Discourse post?

**Comment by consideRatio** [comment]
@uluzox I've approved you post (was automatically flagged as "typed suspiciously fast").

@manics i made you a moderator in discourse.jupyter.org!

**Comment by uluzox** [comment]
> @uluzox Unfortunately I don't have permission to see/approve your Discourse post (someone else should though). In the meantime in both the working and non-working environments could you:
> 
> * Run `env | sort` in a terminal
> * Run a python notebook with
>   ```python
>   import os
>   for k, v in sorted(os.environ.items()):
>       print(f'{k}={v}')
>   ```
> 
> And add all the outputs to your Discourse post?

done
