### ISSUE TITLE
embedding a jupyterhub into an iframe ，

### ISSUE THREAD

**Issue by day-code** [jupyterhub/zero-to-jupyterhub-k8s#2130]
![QQ截图20210406110357](https://user-images.githubusercontent.com/69946103/113653202-f485cd80-96c7-11eb-861d-90174ebed520.png)
but still it show error while I run
because an ancestor violates the following Content Security Policy directive: "frame-ancestors *".
![QQ截图20210406104655](https://user-images.githubusercontent.com/69946103/113651924-758f9580-96c5-11eb-8f70-9b3357a42c2b.png)
Please help me with this. thanks in advance.

**Comment by day-code** [comment]
@choldgraf ，Please help me

**Comment by sxpsxp12** [comment]
How to solve this problem, please describe it
