### ISSUE TITLE
Unable to set "log_format"

### ISSUE THREAD

**Issue by AdrianSanchezLopez** [jupyterhub/zero-to-jupyterhub-k8s#2147]
### Bug description
I want to set an specific log format to all possible elements in the JupyterHub system for kubernetes. At the moment it does work to set "c.Application.log_format", but that is only for the Hub app. I want to set it to the individual single-user jupyter notebooks too, but all the options I tried failed:  "c.JupyterHub.log_format", "c.NotebookApp.log_format","c.NotebookApp.log_format"

#### Expected behaviour
Setting the one of the c.Application, c.JupyterHub, c.NotebookApp fortmatter should set the specified log format for single users

#### Actual behaviour
the single users still have the default format

### How to reproduce
Try to set the above jupyterhub hub config values

minikube version: v1.15.1
kubectl: Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
helm: version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}
helm chart: jupyterhub/jupyterhub 0.11.1

**Comment by manics** [comment]
Hi! The notebook configuration is separate from the hub configuration file, you should be able to customise it in your notebook Docker image. If you need more help please ask on the [community forum](https://discourse.jupyter.org/)
