### ISSUE TITLE
Support for StorageClass during initial Hub provisioning?

### ISSUE THREAD

**Issue by billabongrob** [jupyterhub/zero-to-jupyterhub-k8s#2149]
### Proposed change
Allow using a storageClass in the hub config for use with hub-db-dir
hub.StorageClass:  <insert your storageclass here>

### Who would use this feature?
Folks who are using Azure Files as their Default storage class.  Permissions errors ensue when using this storage class as your default and we leverage multi-tenant clusters.  The error is that anyone can read the config and similar within the mounted storage.  Perhaps we're approaching this wrong though.  

### (Optional): Suggest a solution
The workaround, so far, is to temporarily change the default storage class on the cluster to use managed disks, and then flip back before anyone does deployments alongside our JupyterHub deployment.

**Comment by manics** [comment]
Hi! This is already supported, and has been for a long time (though it may have been missing from the stable docs): https://zero-to-jupyterhub.readthedocs.io/en/latest/resources/reference.html#hub-db-pvc-storageclassname
relevant schema: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/f085a7b2cc9f8d2d4ada36ddc0e41f00ebd255e9/jupyterhub/schema.yaml#L686-L692

**Comment by mverleg** [comment]
Thanks @manics. For other people running into this, the config is

    hub:
      db:
        pvc:
          storageClassName: $YOUR_CLASS_NAME
