### ISSUE TITLE
Why CHP replicas is 1 and non configurable?

### ISSUE THREAD

**Issue by echarles** [jupyterhub/zero-to-jupyterhub-k8s#2155]
The proxy replicas count is set to 1 and is not configurable

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/5c496bcaeb2cecd2937c4608994e7e4c7fa94cf8/jupyterhub/templates/proxy/deployment.yaml#L10

For a number larger than 1, we would need to enforce HTTP session stickiness, which is available in most cloud providers (at least I use it in gcloud). 

Was that already been discussed?

**Comment by consideRatio** [comment]
CHP is being remotely configured by JupyterHub, unless we have a system for JupyterHub to configure multiple replicas through the REST API requests, we can't support multiple CHP replicas.

- JupyterHub has a `proxy_class` configured: ConfigurableHTTPProxy (Python class to add routes etc)
- ConfigurableHTTPProxy the python class adding routes etc, only works against a single instance of a CHP.

If this should be supported, I think we would need a new class to represent multiple replicas of CHP and to ensure that we can communicate with specific replicas and not just any replica chosen at random by communicating with the k8s Service exposing any one replica running.

There are several discussions about this under the titles of "high availability" already:
- https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1951
- https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1364
- https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/710

**Comment by echarles** [comment]
Thx a lot @consideRatio for the background details. `KubeIngressProxy`sounds to me like a promising option. From what I read in the linked issue, it does not seem to be available today in the zjk helm chart?

**Comment by consideRatio** [comment]
@echarles it actually is available in this helm chart because it is a Python class part of the KubeSpawner Python package that is installed.

Until https://github.com/jupyterhub/kubespawner/issues/496 is resolved and we improve maintenance in general of the project I'm very hesitant to let Z2JH commit to working against it though: https://github.com/jupyterhub/kubespawner/issues/496.

**Comment by echarles** [comment]
> @echarles it actually is available in this helm chart because it is a Python class part of the KubeSpawner Python package that is installed.

It is installed as part of the KubeSpawner python package on the hub pod (if I am not mistaken), but I don't see how to use it with the current helm chart configuration options. I would say it is not "usable" today.

**Comment by consideRatio** [comment]
> It is installed as part of the KubeSpawner python package on the hub pod (if I am not mistaken), but I don't see how to use it with the current helm chart configuration options. I would say it is not "usable" today.

Ah in that regard yes I fully agree, there is no documentation about trying to do so etc and is very much an experimental adventure for anyone who tries.

**Comment by consideRatio** [comment]
@echarles agree to close this issue as a duplicate of discussion in #1951, #1364, #710?

**Comment by echarles** [comment]
Thx for the continuous and very helpful explanation @consideRatio Closing this.
