### ISSUE TITLE
Update documentation to ensure reproducible steps with helm

### ISSUE THREAD

**Issue by wilmeragsgh** [jupyterhub/zero-to-jupyterhub-k8s#2178]
Thanks for this amazing project btw!

### Bug description
In the documentation at: https://zero-to-jupyterhub.readthedocs.io/en/stable/jupyterhub/installation.html
The code snippet for helm upgrade points to version `0.10.6` whereas the stable version is `0.11.1`
This affects, for example, when testing authentication customizations where dummyAuth will overwrite the desired configuration.

#### Expected behavior
With the up-to-date version in the doc, the steps will behave as described in the documentation without any issue.

#### Actual behaviour
Right now the configurations for auth (tested auth0 and github) get overwritten by dummyAuth.

### How to reproduce
Try to follow the current steps on the documentation and test adding auth0 or github.

**Comment by consideRatio** [comment]
Yes that was an unfortunate mistake in the docs. We have not cut a new release just to update the docs and it is a mistake that won't happen again as we have made the version number set dynamically in the docs now.

Hmm... Can one manipulate a read-the-docs build (associated with the 0.11.1 tag) without needing to modify git history or similar?

**Comment by consideRatio** [comment]
Closing as resolved in `latest` version, even though the 0.11.1 version of the documentation has this bug.
