### ISSUE TITLE
Cannot pull jupyterhub/k8s-network-tools from private repo on 0.9

### ISSUE THREAD

**Issue by tfmark** [jupyterhub/zero-to-jupyterhub-k8s#2203]
### Bug description

I've inherited a project that uses 0.9 of `zero-to-jupyterhub-k8s`, I'm trying to deploy but my registry (hosted on port 5000 and proxy on 6000) requires authentication.

I have added namespace-specific secrets, but I'm unable to pull the `k8s-network-tools` image.

I dont believe it's trying to use the `pullSecrets` that is configured, but I don't want to upgrade to the latest version without some level of confidence that this will solve my problem.

Alternatively, I could be doing something completely wrong, but considering that the `singleuser` image pulls down successfully, I think I'm mostly on the right track.

I had a quick browse of the code/templates but can't see anything specific for secrets for `networkTools`...

```
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  4m36s                  default-scheduler  Successfully assigned jupyter-018-tradefeedr/hook-image-puller-ft4pv to jupyter-vm-1
  Normal   Pulling    4m36s                  kubelet            Pulling image "<private_repo>:5000/tradefeedr/jupyter-singleuser-k8s:1.0.1"
  Normal   Pulled     4m36s                  kubelet            Successfully pulled image "<private_repo>:5000/tradefeedr/jupyter-singleuser-k8s:1.0.1" in 544.700731ms
  Normal   Created    4m36s                  kubelet            Created container image-pull-singleuser
  Normal   Started    4m36s                  kubelet            Started container image-pull-singleuser
  Warning  Failed     3m54s (x3 over 4m35s)  kubelet            Error: ErrImagePull
  Normal   BackOff    3m14s (x5 over 4m34s)  kubelet            Back-off pulling image "<private_repo>:6000/jupyterhub/k8s-network-tools:0.9.0"
  Warning  Failed     3m14s (x5 over 4m34s)  kubelet            Error: ImagePullBackOff
  Normal   Pulling    3m1s (x4 over 4m35s)   kubelet            Pulling image "<private_repo>:6000/jupyterhub/k8s-network-tools:0.9.0"
  Warning  Failed     3m1s (x4 over 4m35s)   kubelet            Failed to pull image "<private_repo>:6000/jupyterhub/k8s-network-tools:0.9.0": rpc error: code = Unknown desc = failed to pull and unpack image "<private_repo>:6000/jupyterhub/k8s-network-tools:0.9.0": failed to resolve reference "<private_repo>:6000/jupyterhub/k8s-network-tools:0.9.0": unexpected status code [manifests 0.9.0]: 401 Unauthorized
```
**NOTE:** disabling authentication/enabling anonymous pulling for the registry makes everything work. but that's not what I want...

**NOTE 2:** I merged my secrets into 1 (as it's just a `.docker/config.json` file bas64 encoded) and this allowed me to pull `k8s-network-tools`, which suggests that the parent secret was overriding the child? however the next issue was pulling `jupyterhub/k8s-image-awaiter:0.9.0` which failed with 401.

#### Expected behaviour
`jupyterhub/k8s-network-tools:0.9.0` pulled correctly

#### Actual behaviour
Image cannot be pulled; 401 unauthorized error

### How to reproduce

Try pulling `jupyterhub/k8s-network-tools` from a private repository with credentials using 0.9

### Your personal set up
values.yaml snippet:
```yaml
singleuser:
  image:
    name: "<private_repo>:5000/tradefeedr/jupyter-singleuser-k8s"
    tag: "1.0.1"
    pullSecrets:
    - "docker-registry-login"
  networkTools:
    image:
      name: "<private_repo>:6000/jupyterhub/k8s-network-tools"
      tag: "0.9.0"
      pullSecrets:
      - "docker-proxy-login"
```

```
$ microk8s kubectl get secret/docker-proxy-login --namespace jupyter-018-tradefeedr
NAME                 TYPE                             DATA   AGE
docker-proxy-login   kubernetes.io/dockerconfigjson   1      17h
```

 - OS:
Ubuntu 20.04
 - Version(s):
n/a
- <details><summary>Full environment</summary>
n/a

</details>

- <details><summary>Configuration</summary>

```python
# jupyterhub_config.py
```
</details>

- <details><summary>Logs</summary>

```
# paste relevant logs here, if any
```
</details>

**Comment by consideRatio** [comment]
> I dont believe it's trying to use the pullSecrets that is configured, but I don't want to upgrade to the latest version without some level of confidence that this will solve my problem.

I'm confident the documentation about setting `imagePullSecrets` on k8s Pods has improved, and this this isn't a problem in the most recent version of the Helm chart. Do try your luck, there isn't capacity from me and other maintainers to answer questions in detail on old versions.

Related old documentation
- https://zero-to-jupyterhub.readthedocs.io/en/0.9.1/reference/reference.html#singleuser-image-pullsecrets
- https://zero-to-jupyterhub.readthedocs.io/en/0.9.1/reference/reference.html#singleuser-imagepullsecret
- `singleuser.cloudMetadata.enabled=true` (to disable the initContainer blocking access to a specific IP)

To debug, you should inspect if your pod got `imagePullSecrets` set on its pod specification. If it didn't, it is a Helm chart configuration issue, if it did, it is an issue with your credentials. If it is an issue with the Helm chart at version 0.9.0 or 0.9.1, you should update to 0.11.1.

**Comment by tfmark** [comment]
Updating to 0.11.1 resolved the issue with pulling from private repo with auth 👍
