### ISSUE TITLE
Links to Traverse z2jh Tutorial 

### ISSUE THREAD

**Issue by jzf2101** [jupyterhub/zero-to-jupyterhub-k8s#221]
@yuvipanda @choldgraf looking at the tutorial at the in person tutorial, I don't see links to go forward and backward through the content in z2jh 

See: 

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/doc/source/getting-started.rst

and 

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/doc/source/index.rst

**Comment by choldgraf** [comment]
yeah - the z2jh started out as a purely linear guide but has morphed into a combination of linear guide + a bunch of other related information. I think sometime soon it's worth refactoring this documentation so that it's easier to follow (and so that your concerns here are addressed).

**Comment by willingc** [comment]
Closed by https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/266
