### ISSUE TITLE
Move changelog to docs website

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#2221]
I suggest we make the changelog become part of the rendered documentation instead of a dedicated markdown file to be read from GitHub, and that we let CHANGELOG.md point to this rendered view.

Note for reference that jupyterhub/jupyterhub repo only has rendered website documentation currently, [see it here](https://jupyterhub.readthedocs.io/en/stable/changelog.html).

![image](https://user-images.githubusercontent.com/3837114/119242003-c4e93280-bb5a-11eb-9fdf-c951204624bc.png)

---

I think there are two key benefits of this:
1. We can get navigation assistance out of the box
2. We can make use of myst formatting, such as note/warning callouts

**Comment by minrk** [comment]
I think this is a good idea.
