### ISSUE TITLE
can JupyterHub spin up without nfs mount ?

### ISSUE THREAD

**Issue by jino-varghese** [jupyterhub/zero-to-jupyterhub-k8s#2241]
Hello Team,

I would like to go without NFS mount and can spin up with local mount point.

i have tried  - https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1188,    But does not work. 

Could you please help. 

Thank you.

**Comment by consideRatio** [comment]
If you configure the hubs db to be in-memory or external, then the hub pod wont mount a k8s PVC requesting storage from the cluster.
