### ISSUE TITLE
Change policy/v1beta1 to policy/v1 to resolve newer K8 issues

### ISSUE THREAD

**Issue by Bltzz** [jupyterhub/zero-to-jupyterhub-k8s#2242]
### Bug description
When I run: helm upgrade --cleanup-on-fail --install jupyter jupyterhub/jupyterhub --namespace jhub --create-namespace --version=0.11.1 --values config.yaml

I get the following error:

W0607 11:59:34.173526 3606783 warnings.go:70] policy/v1beta1 PodDisruptionBudget                                                 is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudg                                                et

I assume, the

zero-to-jupyterhub-k8s/jupyterhub/templates/proxy/pdb.yaml 

and 

zero-to-jupyterhub-k8s/jupyterhub/templates/scheduling/user-placeholder/pdb.yaml 

needs to be changed

#### Expected behaviour
Run through installation process (as in the tutorial)
https://zero-to-jupyterhub.readthedocs.io/en/latest/jupyterhub/installation.html

#### Actual behaviour
Error mentioned above

### How to reproduce
use K8 Verison mentioned below and follow tutorial

### Your personal set up
K8: Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCom                                                mit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:                                                "2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd                                                64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCom                                                mit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:                                                "2021-05-12T14:12:29Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd                                                64"}

 - OS:
Red Hat Enterprise Linux release 8.2 (Ootpa)

 - Version(s):
 python 3.8 
jhub: latest, stable

**Comment by consideRatio** [comment]
We should absolutely fix this, thanks for reporting!

**Comment by consideRatio** [comment]
To be clear, this didn't break the installation for you, but you simply got a warning about it - right?

**Comment by Bltzz** [comment]
No, it breaks the installation...

**Comment by Bltzz** [comment]
At least it breaks with this:

Error: failed pre-install: timed out waiting for the condition

**Comment by consideRatio** [comment]
@Bltzz ah okay, it is probably a different error. I'm enabling tests of this helm chart against k8s 1.21 and fixing that warning in #2243.

**Comment by Bltzz** [comment]
Oh okay. Well... now for me the question is how to troubleshoot this installation...

**Comment by consideRatio** [comment]
@Bltzz the warning should be fixed by #2243, and i could confirm via tests now that it should work in k8s 1.21 as well.

So, how to troubleshoot?

I would say:
1. After having done `helm install` that failed with a timeout, it is all about inspecting what have happened in the k8s cluster.
2. What pods do you see, are they pending and failed to be scheduled, are they stuck in ContainerCreating, are they starting and crashing?
   - If they are pending on stuck in ContainerCreating, use `kubectl describe pod <name>`.
   - If they are crashing, use `kubectl logs <pod name>` or `kubectl logs deploy/<deployment-name>` (`kubectl logs deploy/hub`).

**Comment by consideRatio** [comment]
@Bltzz if you are installing this Helm chart for the first time, also go straight ahead and use the latest version rather than 0.11.1 for example.

The latest version which will be available in 10 minutes, with the warning you experience fixed, is `1.0.0-beta.1.n006.h61a1fe91`.

**Comment by Bltzz** [comment]
That is what kubectl describe pod returns

 kubectl get pods
NAME                       READY   STATUS    RESTARTS   AGE
hook-image-awaiter-ls8nb   0/1     Pending   0          60m
[bltzz@rhel ~]$ kubectl describe pod hook-image-awaiter-ls8nb
Name:           hook-image-awaiter-ls8nb
Namespace:      jhub
Priority:       0
Node:           <none>
Labels:         app=jupyterhub
                component=image-puller
                controller-uid=cdda59dd-1f4d-418c-930a-631734998301
                job-name=hook-image-awaiter
                release=jupyterhub
Annotations:    <none>
Status:         Pending
IP:
IPs:            <none>
Controlled By:  Job/hook-image-awaiter
Containers:
  hook-image-awaiter:
    Image:      jupyterhub/k8s-image-awaiter:0.11.1
    Port:       <none>
    Host Port:  <none>
    Command:
      /image-awaiter
      -ca-path=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      -auth-token-path=/var/run/secrets/kubernetes.io/serviceaccount/token
      -api-server-address=https://kubernetes.default.svc:$(KUBERNETES_SERVICE_PORT)
      -namespace=jhub
      -daemonset=hook-image-puller
      -pod-scheduling-wait-duration=10
    Requests:
      cpu:        0
      memory:     0
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-dkvdw (ro)
Conditions:
  Type           Status
  PodScheduled   False
Volumes:
  kube-api-access-dkvdw:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age                From               Message
  ----     ------            ----               ----               -------
  Warning  FailedScheduling  1s (x62 over 60m)  default-scheduler  0/1 nodes are available: 1 node(s) had taint {node-role.kubernetes.io/master: }, that the pod didn't tolerate.

**Comment by Bltzz** [comment]
Thats the result for the new version with debug flag

helm upgrade --cleanup-on-fail --install jupyter jupyterhub/jupyterhub --namespace jhub --create-namespace --version=1.0.0-beta.1.n006.h61a1fe91 --values config.yaml --debug
history.go:56: [debug] getting history for release jupyter
upgrade.go:123: [debug] preparing upgrade for jupyter
upgrade.go:131: [debug] performing update for jupyter
upgrade.go:303: [debug] creating upgraded release for jupyter
client.go:284: [debug] Starting delete for "hook-image-puller" DaemonSet
client.go:122: [debug] creating 1 resource(s)
client.go:284: [debug] Starting delete for "hook-image-awaiter" ServiceAccount
client.go:122: [debug] creating 1 resource(s)
client.go:284: [debug] Starting delete for "hook-image-awaiter" Role
client.go:122: [debug] creating 1 resource(s)
client.go:284: [debug] Starting delete for "hook-image-awaiter" RoleBinding
client.go:122: [debug] creating 1 resource(s)
client.go:284: [debug] Starting delete for "hook-image-awaiter" Job
client.go:122: [debug] creating 1 resource(s)
client.go:493: [debug] Watching for changes to Job hook-image-awaiter with timeout of 5m0s
client.go:521: [debug] Add/Modify event for hook-image-awaiter: ADDED
client.go:560: [debug] hook-image-awaiter: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
client.go:521: [debug] Add/Modify event for hook-image-awaiter: MODIFIED
client.go:560: [debug] hook-image-awaiter: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
upgrade.go:369: [debug] warning: Upgrade "jupyter" failed: pre-upgrade hooks failed: timed out waiting for the condition
Error: UPGRADE FAILED: pre-upgrade hooks failed: timed out waiting for the condition
helm.go:81: [debug] pre-upgrade hooks failed: timed out waiting for the condition
UPGRADE FAILED
main.newUpgradeCmd.func2
        helm.sh/helm/v3/cmd/helm/upgrade.go:157
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.1.3/command.go:852
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.1.3/command.go:960
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.1.3/command.go:897
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:80
runtime.main
        runtime/proc.go:225
runtime.goexit
        runtime/asm_amd64.s:1371
