### ISSUE TITLE
Proxy pod fail to start when IPv6 is disabled (listen EAFNOSUPPORT: address family not supported)

### ISSUE THREAD

**Issue by JamesCarscadden** [jupyterhub/zero-to-jupyterhub-k8s#2254]
### Bug description
I am attempting to set up the Z2JH chart on a Raspberry PI (arm64) based cluster and am encountering some problems with the proxy (chp) pod. Specifically I am getting the following error:

Uncaught Exception: listen EAFNOSUPPORT: address family not supported :::8000

#### Expected behaviour
Proxy pod should start up correctly

#### Actual behaviour
Uncaught Exception: listen EAFNOSUPPORT: address family not supported :::8000

### How to reproduce
Use base Z2JH chart (v1.0.0) on an arm64 based cluster node using proxy service type of ClusterIP

### Your personal set up
Kubernetes v1.21.1 running on Raspberry PI 4 (8Gb) 4 node cluster.
Base OS is current version of Raspbian arm64 distribution
Cluster is using current versions of MetalLb and Flannel CNI
Using Helm to deploy the jupyterhub chart from https://jupyterhub.github.io/helm-chart/

Full output from the proxy pod chp container:

```
15:00:24.322 [ConfigProxy] [32minfo[39m: Adding route / -> http://hub:8081
15:00:24.343 [ConfigProxy] [32minfo[39m: Proxying http://:::8000 to http://hub:8081
15:00:24.343 [ConfigProxy] [32minfo[39m: Proxy API at http://:::8001/api/routes
15:00:24.361 [ConfigProxy] [31merror[39m: Uncaught Exception: listen EAFNOSUPPORT: address family not supported :::8000
15:00:24.363 [ConfigProxy] [31merror[39m: Error: listen EAFNOSUPPORT: address family not supported :::8000
at Server.setupListenHandle [as _listen2] (net.js:1301:21)
at listenInCluster (net.js:1366:12)
at doListen (net.js:1503:7)
at processTicksAndRejections (internal/process/task_queues.js:83:21)
15:00:24.363 [ConfigProxy] [31merror[39m: Uncaught Exception: listen EAFNOSUPPORT: address family not supported :::8001
15:00:24.364 [ConfigProxy] [31merror[39m: Error: listen EAFNOSUPPORT: address family not supported :::8001
at Server.setupListenHandle [as _listen2] (net.js:1301:21)
at listenInCluster (net.js:1366:12)
at doListen (net.js:1503:7)
at processTicksAndRejections (internal/process/task_queues.js:83:21)
15:00:24.365 [ConfigProxy] [32minfo[39m: Route added / -> http://hub:8081
```

The pod ends up stuck in a CrashLoopBackoff

I am using the following values for my helm deployment (using nginx-ingress, external-dns, and cert-manager for the ingress):

```yaml
ingress:
  enabled: true
  hosts:
    - jupyter.pi.<myhostname>
  annotations:
    kunernetes.io/ingress.class: nginx
    external-dns.alpha.kubernetes.io/target: "<my public IP address>"
  tls:
    - hosts:
      - jupyter.pi.<myhostname>
      secretName: web-cert-wildcard
proxy:
  secretToken: <big ugly random value>
  service:
    type: ClusterIP
```

**Comment by manics** [comment]
K8s 1.21 turns on ipv6 by default: https://kubernetes.io/docs/concepts/services-networking/dual-stack/
We test 1.21 in our GitHub workflow
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/1a2ff6816303a9843e1a0e26da51e26d7bc9eff8/.github/workflows/test-chart.yaml#L122
but it's possible ipv6 isn't activated. From https://github.com/k3s-io/k3s/issues/284 it's unclear whether we can activate it ourselves, or whether it requires core K3s changes.

Are you able to test with ipv6 disabled on your K8S cluster? This will help to determine whether the problem is a generic ipv6 issue, or something specific to ARM64.

**Comment by consideRatio** [comment]
@JamesCarscadden :heart: :tada: thank you so much for reporting these issues clearly! I'm very excited about getting these reports as it enables development to support bleeding edge tech!

**Comment by JamesCarscadden** [comment]
If this is an IPv6 issue then I would say this is a 'generic' IPv6 issue rather than something specific to arm64, as I specifically have IPv6 disabled on the underlying hosts (on raspi this is accomplished by setting 'ipv6.disable=1' in /boot/cmdline.txt)

I can attempt to turn off the IPv6 dual stack on Kubernetes itself if someone can offer advice on how to go about it (found this related, but I have no idea where I go about setting the feature flag command line options -- I don't see systemctl entries for anything other than Kubelet for instance): https://kubernetes.io/docs/concepts/services-networking/dual-stack/)

I seem to recall that disabling ipv6 on the host was a requirement a long while ago when I first built this cluster, as was using iptables-legacy) -- looking at some more recent discussions, it would appear this may no longer be necessary so I may just try rebooting the cluster with ipv6 enabled on the host and see if that helps (won't have time to do that until the weekend).

**Comment by manics** [comment]
There's a discussion here https://discourse.jupyter.org/t/ipv6-related-issue-in-configurable-http-proxy/8292
which suggests enabling ipv6 may fix things. I won't pretend to understand why though.

**Comment by JamesCarscadden** [comment]
I had a chance last night to re-enable IPv6 on my cluster. That appears to have resolved the problem. Proxy is up and running and I can log into my hub. Thanks for the help.

**Comment by consideRatio** [comment]
Thanks @manics and @JamesCarscadden for verifying this!

I'm not sure I want to suggest we add configuration option and the associated complexity to run in contexts where IPv6 is disabled, but maybe... Let's keep this issue open for now.

**Comment by consideRatio** [comment]
I assume the issue stems from z2jh configuring CHP like this, and that this issue would go away for situations where IPv6 is disabled by using 0.0.0.0 instead, but, then it would not support IPv6 out of the box.

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/adda42a2766e823473554a105baf3c37d55c9208/jupyterhub/templates/proxy/deployment.yaml#L72-L75

**Comment by dietmar** [comment]
I came across this problem in our PKS cluster with IPv6 disabled.

This workaround from https://discourse.jupyter.org/t/ipv6-related-issue-in-configurable-http-proxy/8292/12 makes it work:

Appending `--post-renderer ./ipv6-patch.sh` to helm upgrade / helm install.
Content of `./ipv6-patch.sh`:
```
#!/bin/bash

sed -e "s/-ip=::/-ip=0.0.0.0/g"
```

I guess this confirms your assumptions, @consideRatio?
It would be great if the z2jh chart could deal with this situation more elegantly. I'm afraid I'm not proficient enouth in K8s to propose a solution.

**Comment by consideRatio** [comment]
### Action points

- [x] Update CHP and cut a release, (https://github.com/jupyterhub/configurable-http-proxy/pull/333, CHP 4.5.0 released, https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/2321)
- [x] Update Z2JH to set blank strings for `--ip` and `--api-ip` (https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/2318)
- [ ] Test if chart now works in a IPv4 only context __- Help with this wanted!__
- [ ] Test if chart now works in a IPv6 context __- Help with this wanted!__
- [ ] Release Z2JH 1.1.0 (@consideRatio)

@dietmar, @g-braeunlich, @stv0g, @alex-vmw or others, could you help verify that the recent changes work for you in either a ipv4 only ora ipv6 only contexts? The helm chart version where things are supposed to work is: `1.0.1-n065.hcc544c15`

**Comment by dietmar** [comment]
Thanks for your work on this, @consideRatio!

My environment does not fulfill `kubeVersion: ">=1.17.0-0"` (https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/main/jupyterhub/Chart.yaml#L11), and I can't change that.
So I need to use `jupyterhub-0.11.1`, which has `kubeVersion: '>=1.14.0-0'`. Therefore, I cannot directly test your helm chart.

However, when I manually apply your changes from https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/2318/files as follows, it works in my IPv4-only environment, without the `--post-renderer` hack from above.

```
$ diff -r jupyterhub-0.11.1/ jupyterhub-0.11.1-dietmar/
diff -r jupyterhub-0.11.1/jupyterhub/templates/proxy/deployment.yaml jupyterhub-0.11.1-dietmar/jupyterhub/templates/proxy/deployment.yaml
60,61c60,61
<             - "--ip=::"
<             - "--api-ip=::"
---
>             - "--ip="
>             - "--api-ip="
diff -r jupyterhub-0.11.1/jupyterhub/values.yaml jupyterhub-0.11.1-dietmar/jupyterhub/values.yaml
190c190
<       tag: 4.2.2
---
>       tag: 4.5.0
```

```
tar -czf jupyterhub-0.11.1-dietmar.tgz jupyterhub/
helm upgrade jhub jupyterhub-0.11.1-dietmar.tgz [...]
```

**Comment by consideRatio** [comment]
Thanks dietmar! What remain is to know we don't break things where IPv6 traffic needs to be accepted as well.

**Comment by consideRatio** [comment]
This issue is fixed, and hopefully it didn't break deployment relying on IPv6 which isn't verified yet. I'm cutting z2jh 1.1.0 now.
