### ISSUE TITLE
Helm installed jupyterhub config ldap auth failed

### ISSUE THREAD

**Issue by zouchengli** [jupyterhub/zero-to-jupyterhub-k8s#2266]
`helm install jupyterhub jupyterhub/jupyterhub \
--set proxy.secretToken=ProxySecretTokenStr,ingress.enabled=true,ingress.hosts\[0\]=jupyterhub-k8s.docker.internal \
--set hub.config.JupyterHub.authenticator_class=ldapauthenticator.LDAPAuthenticator \
--set hub.config.JupyterHub.LDAPAuthenticator.server_address='ldap://192.168.168.201' \
--set hub.config.JupyterHub.LDAPAuthenticator.bind_dn_template\[0\]='uid\={username}\,ou\=users\,dc\=xxx\,dc\=com'`

---------------------------------------------------------------------------------------------------------------------------------------------

`[I 2021-06-21 10:43:39.042 JupyterHub app:2853] JupyterHub is now running at http://:8000 [I 2021-06-21 10:43:39.123 JupyterHub log:189] 200 GET /hub/api/users (cull-idle@127.0.0.1) 12.54ms [I 2021-06-21 10:44:08.824 JupyterHub log:189] 200 GET /hub/login (@192.168.65.3) 23.05ms [I 2021-06-21 10:44:09.390 JupyterHub log:189] 200 GET /hub/login (@192.168.65.3) 1.60ms [I 2021-06-21 10:44:09.548 JupyterHub log:189] 200 GET /hub/login (@192.168.65.3) 1.37ms [I 2021-06-21 10:44:09.716 JupyterHub log:189] 200 GET /hub/login (@192.168.65.3) 1.43ms [I 2021-06-21 10:44:09.855 JupyterHub log:189] 200 GET /hub/login (@192.168.65.3) 1.88ms [E 2021-06-21 10:46:19.792 JupyterHub web:1789] Uncaught exception POST /hub/login?next= (192.168.65.3) HTTPServerRequest(protocol='https', host='jupyterhub-k8s.docker.internal', method='POST', uri='/hub/login?next=', version='HTTP/1.1', remote_ip='192.168.65.3') Traceback (most recent call last): File "/usr/local/lib/python3.8/dist-packages/tornado/web.py", line 1704, in _execute result = await result File "/usr/local/lib/python3.8/dist-packages/jupyterhub/handlers/login.py", line 151, in post user = await self.login_user(data) File "/usr/local/lib/python3.8/dist-packages/jupyterhub/handlers/base.py", line 754, in login_user authenticated = await self.authenticate(data) File "/usr/local/lib/python3.8/dist-packages/jupyterhub/auth.py", line 469, in get_authenticated_user authenticated = await maybe_future(self.authenticate(handler, data)) File "/usr/local/lib/python3.8/dist-packages/ldapauthenticator/ldapauthenticator.py", line 382, in authenticate conn = self.get_connection(userdn, password) File "/usr/local/lib/python3.8/dist-packages/ldapauthenticator/ldapauthenticator.py", line 314, in get_connection conn = ldap3.Connection( File "/usr/local/lib/python3.8/dist-packages/ldap3/core/connection.py", line 363, in __init__ self._do_auto_bind() File "/usr/local/lib/python3.8/dist-packages/ldap3/core/connection.py", line 391, in _do_auto_bind if self.start_tls(read_server_info=False): File "/usr/local/lib/python3.8/dist-packages/ldap3/core/connection.py", line 1314, in start_tls if self.server.tls.start_tls(self) and self.strategy.sync: # for asynchronous connections _start_tls is run by the strategy File "/usr/local/lib/python3.8/dist-packages/ldap3/core/tls.py", line 259, in start_tls result = connection.extended('1.3.6.1.4.1.1466.20037') File "/usr/local/lib/python3.8/dist-packages/ldap3/core/connection.py", line 1275, in extended response = self.post_send_single_response(self.send('extendedReq', request, controls)) File "/usr/local/lib/python3.8/dist-packages/ldap3/strategy/sync.py", line 160, in post_send_single_response responses, result = self.get_response(message_id) File "/usr/local/lib/python3.8/dist-packages/ldap3/strategy/base.py", line 370, in get_response raise LDAPSessionTerminatedByServerError(self.connection.last_error) ldap3.core.exceptions.LDAPSessionTerminatedByServerError: session terminated by server [E 2021-06-21 10:46:19.834 JupyterHub log:181] { "Accept-Language": "en-US,en;q=0.9", "Accept-Encoding": "gzip, deflate, br", "Referer": "https://jupyterhub-k8s.docker.internal/hub/login", "Sec-Fetch-Dest": "document", "Sec-Fetch-User": "?1", "Sec-Fetch-Mode": "navigate", "Sec-Fetch-Site": "same-origin", "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9", "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36", "Content-Type": "application/x-www-form-urlencoded", "Origin": "https://jupyterhub-k8s.docker.internal", "Upgrade-Insecure-Requests": "1", "Sec-Ch-Ua-Mobile": "?0", "Sec-Ch-Ua": "\" Not;A Brand\";v=\"99\", \"Google Chrome\";v=\"91\", \"Chromium\";v=\"91\"", "Cache-Control": "max-age=0", "Content-Length": "35", "X-Scheme": "https", "X-Forwarded-Scheme": "https", "X-Forwarded-Proto": "https,http", "X-Forwarded-Port": "443,80", "X-Forwarded-Host": "jupyterhub-k8s.docker.internal", "X-Forwarded-For": "192.168.65.3,::ffff:10.1.0.1", "X-Real-Ip": "192.168.65.3", "X-Request-Id": "a3e343ac62be85031f2c8ee699d26ce2", "Host": "jupyterhub-k8s.docker.internal", "Connection": "close" } [E 2021-06-21 10:46:19.834 JupyterHub log:189] 500 POST /hub/login?next= (@192.168.65.3) 120114.89ms [I 2021-06-21 10:46:19.870 JupyterHub log:189] 200 GET /hub/error/503?url=%2Fhub%2Flogin%3Fnext%3D (@10.1.0.240) 22.99ms [I 2021-06-21 10:46:19.878 JupyterHub log:189] 200 GET /hub/error/503?url=%2Ffavicon.ico (@10.1.0.240) 19.68ms [I 2021-06-21 10:46:19.882 JupyterHub proxy:347] Checking routes [I 2021-06-21 10:46:39.048 JupyterHub proxy:347] Checking routes [I 2021-06-21 10:47:39.049 JupyterHub proxy:347] Checking routes [I 2021-06-21 10:48:39.046 JupyterHub proxy:347] Checking routes [I 2021-06-21 10:49:08.571 JupyterHub log:189] 200 GET /hub/login?next= (@192.168.65.3) 1.42ms`

**Comment by consideRatio** [comment]
@zouchengli can you update your report by using triple backticks (```) before and after you paste your command and log output? 

This is too hard to read atm.

**Comment by zouchengli** [comment]
> 
> 
> @zouchengli can you update your report by using triple backticks (```) before and after you paste your command and log output? This is too hard to read atm.

`
<html><body>


  | 2021-06-24 13:36:24 | [E 2021-06-24 05:36:24.953 JupyterHub log:181] {
-- | -- | --
  |  


</body>
</html>`
