### ISSUE TITLE
Add Globus authenticator support

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/zero-to-jupyterhub-k8s#227]
Just a small PR + docs on how to use it!

/cc @NickolausDS

**Comment by yuvipanda** [comment]
I'd love to get this in for v0.5!

**Comment by NickolausDS** [comment]
Thanks! I will try to get this in soon, likely by tomorrow.

**Comment by zonca** [comment]
@NickolausDS I need this for a project, do you have any update?

**Comment by NickolausDS** [comment]
Last time I worked on this I ran into a couple issues, one was HTTPS support, which [has an open pull request](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/229), and another issue with docker not rebuilding changes when updated with helm, which I'm sure is something I'm missing. 

I'm currently very busy, but I would really like to get this done!

**Comment by choldgraf** [comment]
re: Docker not rebuilding changes. I wonder if that's similar to the problem that @ellisonbg mentioned with upgrading JupyterLab (though I seem to remember that being on Binder)

**Comment by rpwagner** [comment]
@zonca are you trying to use Globus Auth with part of a z2jh tutorial, or for a somewhat persistent deployment? If it's the latter we might be able to try something using a load balancer as an HTTPS proxy.

**Comment by zonca** [comment]
Thanks @rpwagner,
No worries, I can wait for this to be implemented

Il lun 30 ott 2017, 21:39 Rick Wagner <notifications@github.com> ha scritto:

**Comment by yuvipanda** [comment]
I've started on the CHANGELOG for v0.5 (https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/249). Just a quick bump to try to get this in for 0.5 :)

**Comment by yuvipanda** [comment]
This has been done. Thanks @NickolausDS and @rpwagner
