### ISSUE TITLE
Allow configuring zero-to-jupyterhub authentication through secrets

### ISSUE THREAD

**Issue by holdenk** [jupyterhub/zero-to-jupyterhub-k8s#2270]
### Proposed change

Rather than in-lining oauth secret tokens inside of the config allow users to specify a secret.

### Alternative options

in-line oauth secret tokens inside of the config.

### Who would use this feature?

People deploying in multi-user envs

### (Optional): Suggest a solution

Add "secret_config" field to the base oauth class which then pulls the config from that secret? Maybe?

**Comment by consideRatio** [comment]
hub.existingSecret can help you accomplish this. I think an example using it could be relevant in the chart config reference though.

What you put there is merged like helm merge values.
