### ISSUE TITLE
Add support for multiple ingresses

### ISSUE THREAD

**Issue by holdenk** [jupyterhub/zero-to-jupyterhub-k8s#2271]
### Proposed change
Add support for multiple ingresses

### Alternative options
Users manually create additional ingresses.

### Who would use this feature?
Users on traefik 2.2+ who want to terminate both HTTPS & HTTP to JupyterHub launcher

### (Optional): Suggest a solution

Make ingress an array in the ztj config?

**Comment by consideRatio** [comment]
I dont understand the use case yet or what two does that one Ingress resource can't already. Do you want the chart to be able to create multiple Ingress resources pointing to the same k8s service backend - the k8# Service named proxy-public?

- The ingress resource accepts both http and https i think
- Why not use one Ingress resource but with multiple hostnames if you have that?

**Comment by consideRatio** [comment]
I'll close this as a too vague issue to resolve with a change in this repo @holdenk, feel free to respond and we can reopen if you think it makes sense.
