### ISSUE TITLE
Switch from ClusterRole/ClusterRoleBinding to Role/RoleBinding for scheduler rbac

### ISSUE THREAD

**Issue by abinet** [jupyterhub/zero-to-jupyterhub-k8s#2274]
Hi all,

currently usage of cluster wide resources prevents multiple installation on same cluster with rbac enabled.
Does it make sense to switch to Role/RoleBinding for
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/main/jupyterhub/templates/scheduling/user-scheduler/rbac.yaml
?

**Comment by consideRatio** [comment]
@abinet no it would not work. The kube-scheduler binary that the user-scheduler pod is running needs permission to inspect nodes, and nodes can't be inspected with permissions from a Role as nodes are not namespaced resources.

I think you won't have an issue with conflicting resource names as long as you don't name your Helm release that you install in some namespace exactly the same. You could also use the fullnameOverride option that is introduced in version 1.0.0 and it may start working for you.
