### ISSUE TITLE
Accessing user groups via pre_spawn_hook

### ISSUE THREAD

**Issue by AidanAbd** [jupyterhub/zero-to-jupyterhub-k8s#2277]
### Proposed change
I would like to access a user's groups in the spawner (in the `pre_spawn_hook`)
=
### Reasoning
I am using the REST API to assign users to groups based on their compute requirements through my front end. Through this API, I can assign users to the appropriate group (small, medium, or large). However, I am having trouble accessing the groups in the `pre_spawn_hook`.

### Who would use this feature?
Anyone who wants to dynamically set spawner options based on group membership.

### (Optional): Suggest a solution
I think this might be possible as is, but I am having trouble finding the mechanism to do so.

**Comment by consideRatio** [comment]
You can configure a pre spawn hook from hub.extraConfig, and you have examples of that in the discourse forum if you search for them i believe.

I closed this issue directly here as i see no action point to take.

**Comment by AidanAbd** [comment]
Right -- I have this current preSpawnHook
```
 async def set_resources_hook(spawner):
              #groups = [group['name'] in spawner.user.groups]
              groups = ["small"]
              if "small" in groups:
                      spawner.cpu_limit = 2.0
                      spawner.cpu_guarantee = 1.0
                      spawner.mem_limit = "2G"
                      spawner.mem_guarantee = "1G"
c.KubeSpawner.pre_spawn_hook = set_resources_hook
```

I want to be able to grab the user's groups as set by the API. However, while looking at the src, I was unable to figure out how to get them.

**Comment by AidanAbd** [comment]
https://discourse.jupyter.org/t/accessing-user-groups-from-pre-spawn-hook/9723?u=aidan
