### ISSUE TITLE
add java support in jupyterhub

### ISSUE THREAD

**Issue by sajanraj** [jupyterhub/zero-to-jupyterhub-k8s#2291]
### Proposed change

Adding java support jupyterhubs pod at the time of creating user pod

### Alternative options

The spak context initialization can be obtained.

### Who would use this feature?

The error in pyspark 'java gateway process exited before sending its port number' can be eliminated
issue #1174 

### (Optional): Suggest a solution

Add to jupyterhub's docker image or execute apt-get install openjdk-8-jdk in jupyterhub user pod creation time.

**Comment by consideRatio** [comment]
Hmmmm I'm quite clear that I believe it would be out of scope for Java to be installed in the jupyterhub/k8s-hub image for Helm chart users who want to run Java applications via a some JupyterHub or KubeSpawner hook where custom logic can be executed.

If you want Java available in that image, you should build and maintain a new docker image that you configure via `hub.image.[name|tag]`. Note if you do this, you should be careful to not upgrade the Helm chart without also rebuilding your Dockerfile using a `FROM` statement that relies on the upgraded Helm chart's version.

---

Below is a snippet that can be useful if you want to automate something related to building such custom Dockerfile...

```
# install helm
curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
# install yq
sudo snap install yq
# get latest non pre-release jupyterhub Helm chart version's referenced hub.image.tag config value
helm show values --repo https://jupyterhub.github.io/helm-chart/ jupyterhub | yq e '.hub.image.tag' -
```
