### ISSUE TITLE
EFS without root privileges

### ISSUE THREAD

**Issue by droctothorpe** [jupyterhub/zero-to-jupyterhub-k8s#2299]
### Proposed change
According to https://zero-to-jupyterhub.readthedocs.io/en/latest/kubernetes/amazon/efs_storage.html:
> The UID/fsGID is necessary to force the container to run the start-singleuser.sh as root. Once start-singleuser.sh has properly changed the ownership of the directory, it su’s to the jupyterhub user.

Is it possible to mount an EFS volume to the home directory without running the container as root?

I understand that the startup script immediately deescalates, however, (1) we had to override our `runAsNonRoot` PSP to support this, and (2) we want to provide a custom image field in the options form, but there's no way for us to guarantee deescalation in that context, which is a show-stopper. 

### Who would use this feature?
Everyone who uses EFS with JH and wants improved security.

**Comment by manics** [comment]
EFS is an Amazon service, so Z2JH is limited to whatever features the service provides. If you do find a better way to configure EFS please feel free to update our docs! In the meantime if you need more help please post on the [Jupyter Community Forum](https://discourse.jupyter.org/).

**Comment by droctothorpe** [comment]
Hm. I don't think that this is an EFS issue. The problem lies with how the Jupyter [start.sh](https://github.com/jupyter/docker-stacks/blob/master/base-notebook/start.sh#L67) script requires root privileges to mount NFS. Even though the zero-to-jupyterhub docs recommend using root when mounting EFS, I guess that's a downstream problem that originates in the docker-stacks repo. I'll post the issue there.

**Comment by droctothorpe** [comment]
I found a solution for this! It's totally possible to use EFS without running the container as root. I'll write up some documentation / submit a PR next week.
