### ISSUE TITLE
hub ssl verify error

### ISSUE THREAD

**Issue by Proger666** [jupyterhub/zero-to-jupyterhub-k8s#2301]
### Bug description

After fresh helm install of jupyterhub v1.0.1, i got an SSL error because hub could not verify self-signed certificate from k8s API:

`WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get issuer certificate (_ssl.c:1123)'))': /api/v1/namespaces/jupiter/pods?fieldSelector=&labelSelector=component%3Dsingleuser-server`

 
#### Expected behaviour

This should be ignored.

**Comment by consideRatio** [comment]
If you can install another Helm chart that speaks with the k8s api-server, and doesn't have these issues in your environment - then I'd be inclined to think that it is in scope for this Helm chart to do something.

If not, then I consider this as an issue with how your k8s cluster is configured or that it is your responsibility to provide the self signed certificates to the pods that relies on secure communicate to accept those certificates.

I'm fairly confident it wouldn't be correct to ignore and accept communication with a non-trusted certificate though as it would be a false illusion of security.
