### ISSUE TITLE
add handling of init_containers to the default jupyterhub_config.py

### ISSUE THREAD

**Issue by Analect** [jupyterhub/zero-to-jupyterhub-k8s#232]
While experimenting a bit with lifecycle hooks and init containers with kubespawner, I noticed that while lifecycle hooks are captured in the jupyterhub_config.py [here](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/images/hub/jupyterhub_config.py#L111-L113), there's not out-of-the-box handling for init-containers.

Does it make sense to add this to jupyterhub_config.py?
```
init_containers = get_config('singleuser.init-containers')
if init_containers:
    c.KubeSpawner.singleuser_init_containers = init_containers
```
Let me know and I can send a PR.

**Comment by yuvipanda** [comment]
Yup, go for it!
