### ISSUE TITLE
Kubernetes Autopilot and privileged mode

### ISSUE THREAD

**Issue by fortierq** [jupyterhub/zero-to-jupyterhub-k8s#2354]
### Bug description
I successfully installed JupyterHub with Kubernetes "standard" on GCP. However, after trying to do the same with the Autopilot mode (https://cloud.google.com/kubernetes-engine/docs/concepts/autopilot-overview), server is not starting properly: 
![k8_autopilot](https://user-images.githubusercontent.com/49362475/129776662-17b21a59-34be-48d0-95b2-c4e3a8649205.png)
The important is apparently: container \u003cblock-cloud-metadata\u003e is privileged; not allowed in Autopilot

Is it a known issue? How could I fix it?

**Comment by consideRatio** [comment]
This issue doesn't involve a clear action point of improvement in this repo, so I see it more like a request for help to make it work with autopilot - to me a not yet known third party service of some kind. I'll go ahead and close it and refer to the discourse forum for future aspects.

You can disable the privileged pod meant to improve security by blocking users to have access to a server that can be misused by software in the user pods. To do so, `--set singleuser.cloudMetadata.blockWithIptables=false` and that sidecar container won't block access to the server.
