### ISSUE TITLE
Non-local storage classes cause user-scheduler to schedule all user pods on the same node

### ISSUE THREAD

**Issue by jlphillipsphd** [jupyterhub/zero-to-jupyterhub-k8s#2388]
### Bug description

Non-local storage classes cause the default user-scheduler rules to schedule all user pods on the same node.

#### Expected behaviour

I use nfs-subdir-external-provisioner (https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner) as my default storage class so that the dynamic storage requested by z2jh is not local to any particular node. When new pods are scheduled by the default user-scheduler rule with z2jh, I would expect all pods to be distributed across nodes in the cluster.

#### Actual behaviour

The user-scheduler appears to cycle through all nodes, checking for ones that comply with the storage needs. Since **all nodes** can meet the requirement, the user-scheduler just schedules **the last node** in the list that matches the storage requirement. This ends up always scheduling user pods on the same node since it always seems to check the nodes in the same order (in my experiments).

### How to reproduce

1. Deploy nfs-subdir-external-provisioner on a multi-node k8s cluster
2. Configure k8s to use nfs-subdir-external-provisioner as the default storage class for PVCs
3. Deploy z2jh (should use default storage class for dynamic PVCs)
4. When users log in, all pods are allocated the the "last" node, and no other nodes are scheduled to service user pods

### Your personal set up

 
 - OS Version(s): debian 10, ubuntu-20.04, ubuntu-18.04
 
 - z2jh chart version 1.1.3
 - k3s bare metal

**As a current work-around**, I just turn off the user-scheduler (which results in using the default k8s scheduler - user pods are then distributed across the cluster).

Does it make sense to change user-scheduler to handle this situation? Maybe at least include this information in the docs (suggest turning off user-scheduler for these kinds of storage classes)?

**Comment by consideRatio** [comment]
> When new pods are scheduled by the default user-scheduler rule with z2jh, I would expect all pods to be distributed across nodes in the cluster.

The user-scheduler is designed to pack user pods on a single node. This makes sense in a k8s cluster where nodes are automatically added/removed based on load, but it does not make sense if you have a k8s cluster with a fixed number of nodes.

For some discussion about this, see https://zero-to-jupyterhub.readthedocs.io/en/latest/administrator/optimization.html#using-available-nodes-efficiently-the-user-scheduler.

---

Since what you describe is the expected and preferred behaviour, I consider this issue as resolved or that it could pivot to improve something in the documentation. What do you think?

**Comment by consideRatio** [comment]
> and ends up heavily over-subscribing the node

In k8s, a pod gets scheduled or it remain pending because it didn't properly fit. The user-scheduler is meant to push as much pods into a single node that it can. If you have pods that requests 0 CPU and limits CPU to 100, then it will never stop scheduling pods on a node because they would all fit (ignoring limitations of RAM for a simpler discussion).

If you want to get into the weeds of the details, this info is relevant:
1. what requests/limits on cpu/memory do your user pods make?
2. what allocated capacity do nodes have (use `kubectl describe node <node-name>`)
3. what k8s version do your k8s cluster's api-server have? The user-scheduler is using a k8s official binary called kube-scheduler, but is configured differently. If you are using the absolute latest k8s version, like k8s 1.22, there may be a bug with our user-scheduler that hasn't been fixed yet. With this said though, we are using the official k8s kube-scheduler binary - and our configuration of it is quite simply to ask that it squeeze as much pods into one node that it can before it tries to schedule on other nodes

**Comment by jlphillipsphd** [comment]
Good points, thank you - I think I may be asking for something in the end which is a pretty specific then. Still, here is some info from my side:

1. I make no memory requests, but I do set memory limits (mainly just to ensure that no individual user pod can push the node into denial of service - it would take a large simultaneous group effort and I serve only trusted users - of course, DoS can still happen in this environment as well in the worst case). I don't request or limit CPU so that users can push interactive work through quickly using multicore computation - the CPUs will be shared and I just make my users aware of the sharing and it's potential impacts. I am concerned about setting limits because I want to prioritize access to the service over the user experience. So, soft limits, not hard ones, where I can still bring up a pod for a new user even if the limit was reached? QoS would degrade under heavy load, but users would be advised that this could happen.
2. I worry about posting too much about my nodes publicly, but I've parsed out the relevant allocation stuff here:
```
  Kubelet Version:            v1.21.3+k3s1
  Kube-Proxy Version:         v1.21.3+k3s1
Capacity:
  cpu:                64
  ephemeral-storage:  132715360Ki
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             528344448Ki
  pods:               110
Allocatable:
  cpu:                64
  ephemeral-storage:  129105502107
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             528344448Ki
  pods:               110
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests           Limits
  --------           --------           ------
  cpu                0 (0%)             0 (0%)
  memory             91917287424 (16%)  957353197568 (176%)
  ephemeral-storage  0 (0%)             0 (0%)
  hugepages-1Gi      0 (0%)             0 (0%)
  hugepages-2Mi      0 (0%)             0 (0%)
```
3. As shown above, I am on v1.21.3+k3s1. If the bug doesn't apply, then it's pretty clear that the focus on a single node is probably what's happening, so I am getting the expected behavior. I also completely understand the reasons for that behaviour: cloud deployments don't want to add new nodes unless necessary and so this should therefore be the default situation that user-scheduler tries to deliver.

Looking back through the docs (link you posted above), I see a note in the documentation which already basically indicates that my work-around is the advised solution:
> NOTE: If you don’t want to scale down the nodes you have, it would make more sense to let the users spread out and utilize all available nodes. Only activate the user scheduler if you have an autoscaling node pool.

Like I said in my OP, just turning user-scheduler -off- seems to do what I want and the documentation does make this suggestion (in the negative: turn user-scheduler off if you don't want to autoscale).

I think I was just surprised because I had been using the k3s local-storage provisioner before the summer, and users were being spread out over all of the nodes. So, when I started using the new storage-class this summer, I was anticipating the same behavior but user-scheduler was doing something different from what it had before. (My main motivation was due to losing a disk on one of the nodes and needed to perform maintenance - users with local storage on that node were unfairly impacted and I was trying to find a way to mitigate that issue.)

Looking at the logs, the previous deployments could only match on nodes where the local-storage had been allocated, and the new one (nfs-based) was always pushing pods to the same node. It appeared to me that the policy was somewhat two-tiered: 1) match storage then 2) match other resources. Looking through the rules for the scheduler, I didn't find much about matching storage (maybe I just don't understand what some of those rules are doing). So, it looks like step 1) is being performed before step 2) and so step 2) is effectively ignored with local-storage provisioner? Why would using local-storage result in spreading out pods? Isn't it supposed to result in sending pods to fill one node at a time (due to user-scheduler), regardless of the chosen storage class?

**Comment by jlphillipsphd** [comment]
Maybe I should change the title then: "User-scheduler does not fill one node at a time with local-storage"? Maybe my prior experience was the "bug" and this my current deployments are actually more behaving as expected?

**Comment by jlphillipsphd** [comment]
I think the above behavior was indeed due to k3s local-storage provisioner. That provisioner was using the default k8s scheduling rules, and distributing storage across the node (which it's supposed to do). However, this forces user-scheduler to schedule the pod where the storage was actually allocated, and must be observed.

So, the previous spreading behavior was actually specific to my (prior) storage provisioner (local-storage) provided by k3s and has nothing to do with z2jh in the end.

OK, I am closing this now that I finally understand what happened... :smile:

**Comment by consideRatio** [comment]
Thank you for working it out and following up!
