### ISSUE TITLE
JupyterHub template customization; hub vs simpleuser logo and favicon images

### ISSUE THREAD

**Issue by sunkararp** [jupyterhub/zero-to-jupyterhub-k8s#2389]
We followed instructions #1266 to customize templates, it works great with few unpleasant surprises!!!

- Admin page doesn't work, we are getting 404 for https://wjh.mydomain.com/hub/static/js/admin-react.js
- We see our custom logo and favicon as long as the signed-in user stays in https://jh.mydomain.com/hub/... area
- We see default logo and favicon when the signed-in user navigates to https://js.mydomain.truveta.com/user/... area

A. How do we fix the Admin page?

B.  How do we fix this behaviour? We want to have our logo and favicon to be displayed all the time.

C.  Below is one alternate solution we tried for custom logo, this works great for both /hub/... vs /user/... areas. Is there such thing for favicon as well?
```
hub:
  extraConfig:
    logoConfig: |
      import urllib.request
      urllib.request.urlretrieve("https://externalsource/logo.png", "logo.png")
      c.JupyterHub.logo_file = '/srv/jupyterhub/logo.png'
```

**Comment by consideRatio** [comment]
Look into z2jh.jupyter.org's configuration reference under hub.extraFilea and singleuser.extraFiles

The /user is served by an entirely different server based on docker images you configure in singleuser.image - it it out of scope to say how to customize it as it can be a lot of things running there, how you customize the UI you startup relate to that specific UI (jupyterlab, rstudio, etc.)

With regards to the hub admin react 404, please open a dedicated issue about it and make sure to detail your helm chart config, and if you have overridden the hub image - test by not doing that or not re-installing jupyterhub etc.
