### ISSUE TITLE
proxy.chp.readinessProbe.failureThreshold is not used

### ISSUE THREAD

**Issue by mriedem** [jupyterhub/zero-to-jupyterhub-k8s#2415]
### Bug description

We're using z2jh 0.11.1 and I was noticing chp probe failures in our deployment. One thing I noticed was the readiness probe config on the proxy pod does not match the failure threshold from the values file:

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/0.11.1/jupyterhub/values.yaml#L202

This is from the pod:

>Readiness:  http-get http://:http/_chp_healthz delay=0s timeout=1s period=2s #success=1 #failure=3

It looks like this is because `failureThreshold` isn't used in the `proxy` deployment template:

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/0.11.1/jupyterhub/templates/proxy/deployment.yaml#L127-L140

#### Expected behaviour

I expected the failure threshold from the values file to be set on the readiness probe in the proxy (if the readiness probe is enabled, which it is by default).

#### Actual behaviour

The failure threshold is the default 3 from k8s.

### How to reproduce

Deploy z2jh 0.11.1 with the chp proxy (default); looks like this is also an issue on the latest `main` branch commit.

### Your personal set up

Shouldn't really matter for this issue, but we're running on IBM Cloud Container Service.

----

Having said this, like the hub `readinessProbe`, since the proxy is a singleton having the readiness probe enabled is probably unnecessary and I'm guessing that's why the default `failureThreshold` is so high - because taking the proxy out of service doesn't help since it's the only one. So our workaround will likely just be to disable the chp proxy readiness probe (we also disable the hub readiness probe for the same reason).

**Comment by consideRatio** [comment]
Ah! Nice catch @mriedem! I'll get this fixed (for version 2.0.0 of the Helm chart).

Note that you should update to 1.X before going to 2.X if you upgrade.
