### ISSUE TITLE
ci: automated updates of traefik and chp images

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#2419]
We sometimes update CHP and traefik as external images, and this can be automated!

The strategy for automating these can be like this.

1. Identify a latest version somehow
   This strategy needs to be reliable. The latest git tag in a repo part of the default branch may work, but it can absolutely fail. Git tags can be made on different branches missing commits, or backported tags can be newer in date on separate branches.
2. Verify if the docker image is available
   Sometimes a docker image is slow to publish after the git tag has been created. This is especially true for traefik, so before creating a PR, we should check that the image is actually available still.

**Comment by manics** [comment]
Copying my comment from https://github.com/jupyterhub/binderhub/pull/1391#discussion_r719407073

> Do you need to go via a git tag? Can you use the tags from the container registry directly?
> https://github.com/henchbot/mybinder.org-upgrades/blob/d84971953cdc3efecca7c2bdd408de80835afc4e/src/mybinder-upgrades/henchbot.py#L345-L355

If git tags are always standard and docker tags aren't then using a git tag may make sense, otherwise going straight to the Docker tag avoids the problem of the git tag and docker build happening asynchronously. In both cases you have the problem of ordering tags.

**Comment by yuvipanda** [comment]
dependabot lists 'docker' as an available option for automatic version upgrades (https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/about-dependabot-version-updates). Can we not use that?

**Comment by manics** [comment]
AFAIK Dependabot only bumps the `FROM` statement in a `Dockerfile`

**Comment by yuvipanda** [comment]
aaaah makes sense!

**Comment by consideRatio** [comment]
Even if dependabot would correctly identify the latest version (not just latest date) of a docker image pushed to a repo, it could not update our values.yaml file correctly.

**Comment by sgibson91** [comment]
Ok, so I'm currently writing an action to bump the docker tags of user environments in JupyterHub configs! https://github.com/sgibson91/bump-jhub-image-action While this is a very different use-case and the action won't be able to be ported directly (it's hard coded to look for "singleuser.image" and "singleuser.profileList[*].kubespawner_override"), I imagine a lot of the logic you'd need is already implemented. Currently the action also only checks images on Docker Hub, but I'd love a check for quay.io too!
