### ISSUE TITLE
Switch to recommending kops for AWS installation

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/zero-to-jupyterhub-k8s#243]
kops no longer requires that we use route53 + DNS, and is generally more robust + production worthy than the current quickstart we're using.

https://github.com/kubernetes/kops/blob/master/docs/aws.md is the doc for using it. we should use the 'k8s.local' option for DNS and change our instructions to use kops!

**Comment by choldgraf** [comment]
I think the way to do this is similar to how we ran Heptio - by getting a non-expert to follow their instructions in setting it up and making sure it's not super annoyingly hard :-)

If you agree then I can spend some time trying to figure out the docs etc if you point me in the right direction.

**Comment by yuvipanda** [comment]
Yes! Just follow https://github.com/kubernetes/kops/blob/master/docs/aws.md but skip the sections called 'configure DNS' and see how that is like!

**Comment by choldgraf** [comment]
Closing in favor of #299

**Comment by cam72cam** [comment]
@yuvipanda After watching an EKS presentation from AWS, I plan to stick with Kops for quite a while.  It is simpler to understand and deploy IMO.

Could you re-open this ticket and assign it to me?

**Comment by choldgraf** [comment]
I'd be curious to here what makes (in your opinion) kops easier than EKS for them...is it just that EKS is still half-baked? Think you could comment on this over at #299 and we can decide what's the best path forward? I think that if it'll be quite some time for EKS to be ready for action (or if EKS will be significantly more complex) then an improvement to the docs suggesting `kops` would definitely be welcome

**Comment by yuvipanda** [comment]
@cam72cam I can't seem to assign you, but have re-opened!

@choldgraf I think EKS won't be generally available for another 6 months at least I think. So having kops instructions instead of heptio instructions here is useful IMO.

**Comment by choldgraf** [comment]
ok sounds great - in that case I am all for it :-) looks like you can only "assign" things to project contributors...hey @cam72cam want us to add you as a contributor on the project? ;-)

**Comment by cam72cam** [comment]
@choldgraf sure :+1:

**Comment by choldgraf** [comment]
ok - invitation sent!

also note that we recently merged @willingc refactor of the first step of z2jh, so the amazon docs you'll want to update are now here: https://zero-to-jupyterhub.readthedocs.io/en/latest/amazon/step-zero-aws.html#amazon-aws

**Comment by willingc** [comment]
Yes @yuvipanda and @cam72cam are correct. @choldgraf EKS call a few days ago was very short on timeframes, pricing, details for rollout. I expect 6+ months.

**Comment by cam72cam** [comment]
I'll be working over the next couple of days to take our internal kops based guide and put together an initial PR for review.  I am still learning about some of the security steps that need to be taken, but I already have comments for most of the unknown or probably insecure areas.

**Comment by cam72cam** [comment]
PR created.  Would really like some feedback on the kops settings I used by default.  I have not dove into the security settings much and this configuration might leave some security holes.

**Comment by choldgraf** [comment]
that's excellent @cam72cam !! Thanks! It may be a couple days (a bunch of deadlines coming up soon for us) but we will most definitely take a look!

**Comment by posix4e** [comment]
What about stating a new issue where we suggest kops or eks?

**Comment by choldgraf** [comment]
I believe #299 is there to discuss EKS instructions - thus far it hasn't made sense to switch over the documentation yet but perhaps one day it will!
