### ISSUE TITLE
Injecting config files into /usr/local/etc/jupyterhub/jupyterhub_config.d does not work for all configs

### ISSUE THREAD

**Issue by ihleonard-c3** [jupyterhub/zero-to-jupyterhub-k8s#2448]
I recently updated my chart dependency from 0.11 to 1.1.3. As part of this, I tried moving my jupyterhub_config python code, which had previously been in `extraConfig` to `extraFiles` and mounting it in /usr/local/etc/jupyterhub/jupyterhub_config.d. However, this resulted in my custom authenticator not being used as the authenticator for my hub. I believe that this is because you

1. exec code in /usr/local/etc/jupyterhub/jupyterhub_config.d (https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/main/jupyterhub/files/hub/jupyterhub_config.py#L439)
2. update the main `c` config with values from `hub.config` (https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/main/jupyterhub/files/hub/jupyterhub_config.py#L459)
3. exec `extraConfig`.

The problem is that your values yaml specifies the authenticator_class (https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/main/jupyterhub/values.yaml#L32). Is there a reason that the config in /usr/local/etc/jupyterhub/jupyterhub_config.d isn't executed after reading `hub.config`?

**Comment by consideRatio** [comment]
Hmmm, the current order of executing things is:

1. JupyterHub Helm chart configuration
2. Any file mounted to jupyterhub_config.d folder
3. Any `hub.extraConfig` helm chart config entry

This can be seen from:

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/c54f903c895156483000643b834ef5d1c72f47a4/jupyterhub/files/hub/jupyterhub_config.py#L459-L473

Ah, this was changed in https://github.com/jupyterhub/zero-to-jupyterhub-k8s/commit/36dbf1cefa3f419c578e9e141106294ed9684e08, which was a week after you opened this issue. I'll close this as resolved.

**Comment by ihleonard-c3** [comment]
@consideRatio that PR seems to have been orphaned. It didn't make it into 1.1.4 or 1.2.0

**Comment by consideRatio** [comment]
It is in main i presume and the other releases to be security backports pending 2.0.0

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/2457#issuecomment-953677894
