### ISSUE TITLE
Docs - Markdown is all sorts of messed up in customizing/user-environment.html

### ISSUE THREAD

**Issue by brsolomon-deloitte** [jupyterhub/zero-to-jupyterhub-k8s#2460]
From https://zero-to-jupyterhub.readthedocs.io/en/latest/jupyterhub/customizing/user-environment.html

<img width="751" alt="Screen Shot 2021-10-28 at 11 36 08 AM" src="https://user-images.githubusercontent.com/81818815/139306698-3fb1fc9e-7422-46f3-b5b7-46b5d7d24a5a.png">
<img width="788" alt="Screen Shot 2021-10-28 at 11 35 57 AM" src="https://user-images.githubusercontent.com/81818815/139306699-08b5649d-07d0-4638-8e05-bbf5d7256e89.png">

**Comment by consideRatio** [comment]
![image](https://user-images.githubusercontent.com/3837114/167180963-37e39226-2002-404d-a15b-6d4457eb17cd.png)

Seems resolved!
