### ISSUE TITLE
Existing PVCs keep old chart labels after upgrade

### ISSUE THREAD

**Issue by aloifolia** [jupyterhub/zero-to-jupyterhub-k8s#2481]
### Bug description
When you upgrade your jupyterhub installation to a new helm chart via
["helm upgrade" command](https://zero-to-jupyterhub.readthedocs.io/en/latest/jupyterhub/installation.html), the labels of existing PVCs are not accordingly changed. 

E.g., suppose you first install version 1.1.4. On the first login of a new user, a new PVC with label "chart: jupyterhub-1.1.3" will be created. If you then upgrade to version 1.2.0, the existing PVC will keep its label. However, any subsequently initialized PVCs will have the label "chart: jupyterhub-1.2.0".

#### Expected behaviour
Existing PVCs should be relabeled if necessary. Alternatively, if the current behavior is actually a feature, the documentation should say so explicitly.

**Comment by consideRatio** [comment]
The PVCs for users are not managed by the Helm chart, but by KubeSpawner. For KubeSpawner to start checking and modifying the labels on the PVCs would be a quite significant addition of complexity.

I consider this something we won't fix, and I think it's also documented in some places that changing details on the KubeSpawner created resources is only influencing them during creation.
