### ISSUE TITLE
How to use ssh to connect my notebook in k8s dynamic pod

### ISSUE THREAD

**Issue by zhuzeyu22** [jupyterhub/zero-to-jupyterhub-k8s#2495]
I wanna use ssh to connect my notebook in k8s pod

### Proposed change

I wanna use jupyterhub-ssh to ssh to connect my notebook

### Alternative options

I wanna use ssh to connect my notebook in k8s pod

### Who would use this feature?

every user ， we need to remote connected to coding.

### (Optional): Suggest a solution

I wanna use ssh to connect my notebook in k8s pod

**Comment by consideRatio** [comment]
This can be done with yuvipanda/jupyterhub-ssh, see https://github.com/yuvipanda/jupyterhub-ssh#kubernetes-based-deployment-jupyterhub-ssh-andor-sftp for information and refer to discourse.jupyter.org for followup questions.

**Comment by zhuzeyu22** [comment]
Great, the issues have the answer.  And I got it.
