### ISSUE TITLE
Use cert manager to support TLS 

### ISSUE THREAD

**Issue by zhuzeyu22** [jupyterhub/zero-to-jupyterhub-k8s#2498]
![image](https://user-images.githubusercontent.com/13432873/143392837-1779d7fc-6435-4abf-985a-e4c86abdb687.png)

### Proposed change

I wanna use cert-manager manage my certs , use k8s secret instead of use letsencrypt make certs.
I think it's the standard way to manage cert.

### Alternative options

Support k8s  cert-manager & secret
Make it sample , do not be ugly .

### Who would use this feature?

Every k8s user will use it.  

### (Optional): Suggest a solution

 I don't know  ,  maybe opt some config ?

**Comment by consideRatio** [comment]
I cant respond on all issues you open, this is already supported - so you are in practice asking for support/help rather than reporting bugs/enhancements requests. PLEASE refer to discourse.jupyter.org from now. This is not a help channel.
