### ISSUE TITLE
Need to set both NB_USER and NB_UID 

### ISSUE THREAD

**Issue by hokiegeek2** [jupyterhub/zero-to-jupyterhub-k8s#2504]
### Proposed change
My use case is launching slurm jobs from Juptyterhub on Kubernetes. When launching a slurm job, the uid corresponding to the user must correspond to a user on a slurm cluster. I am able to launch a Jupyterhub singleuser server with the following code:

```
 extraConfig:
      preSpawnHook: |
          from pip._internal import main as pipmain

          # pip install and configure the Authenticator
          pipmain(['install', 'jupyterhub-nativeauthenticator'])

          from nativeauthenticator import NativeAuthenticator

          class GBRMAuthenticator(NativeAuthenticator):
            from tornado import gen
            @gen.coroutine
            def pre_spawn_start(self, user, spawner):
                auth_state = yield user.get_auth_state()
                spawner.environment = {'NB_USER':spawner.user.name, 'NB_UID':'1000'}

          c.JupyterHub.authenticator_class = GBRMAuthenticator
          c.KubeSpawner.args = ['--allow-root']
          c.Spawner.cmd = ['start.sh','jupyterhub-singleuser','--allow-root']

          # if true, users are able to signup
          c.GBRMAuthenticator.enable_signup=True
          # if true, users are added without auth check from admin
          c.GBRMAuthenticator.open_signup=False
          # set of users who are able to administer user accounts
          c.GBRMAuthenticator.admin_users={'admin'}

```
However, when I attempt to set the NB_UID value, I get the following permission error:

```
PermissionError: [Errno 13] Permission denied: '/home/jovyan/.local/share/jupyter/runtime/nbserver-48-open.html'
```

I need for Jupyterhub to accept NB_USER and NB_UID to configure the user to spawn the singleuser pod

### Who would use this feature?
Anyone who is using Jupyterhub as a Slurm client

**Comment by manics** [comment]
You need to run your singleuser pod as UID 0:
https://zero-to-jupyterhub.readthedocs.io/en/latest/resources/reference.html?highlight=singleuser#singleuser-uid

If you need more help please post on the community forum instead https://discourse.jupyter.org/. Thanks!

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/jupyterhub-on-kubernetes-setting-nb-user-and-nb-uid/11934/2
