### ISSUE TITLE
Update versions in readthedocs config 

### ISSUE THREAD

**Issue by willingc** [jupyterhub/zero-to-jupyterhub-k8s#253]
Currently stable and 0.4 point to `5bdece88` which displays:

http://zero-to-jupyterhub.readthedocs.io/en/v0.4/

<img width="1287" alt="screenshot 2017-11-06 08 26 03" src="https://user-images.githubusercontent.com/2680980/32451648-32795928-c2cc-11e7-9412-7cb7ce0f1d82.png">

Unless there is a good reason to have this rendered, we should change stable to point to v0.4-doc and disable display of v0.4.

**Comment by willingc** [comment]
@choldgraf Do you want me to make the change for this in the RTD interface?

**Comment by yuvipanda** [comment]
+1, it should point to v0.4-doc!

**Comment by willingc** [comment]
Thanks @yuvipanda. I'll update @choldgraf.

**Comment by choldgraf** [comment]
gah - man I must really be misunderstanding how RTD works haha. I've tried changing this to point to v0.4-doc twice now, and thought it had worked (e.g. it was auto-directing there on my machine), but it seems I have not done this correctly :-/

**Comment by willingc** [comment]
http://docs.readthedocs.io/en/latest/versions.html#versions Stable is always set to the latest release. I'm going to disable stable for now.

**Comment by willingc** [comment]
Here's what it looks like now with v0.4-doc as the default.

<img width="392" alt="screenshot 2017-11-06 08 41 26" src="https://user-images.githubusercontent.com/2680980/32452445-64cb03e8-c2ce-11e7-80ee-0a49ef3d08b9.png">
