### ISSUE TITLE
Oracle Cloud Jupyterhub & Kubernetes OAuth with GitHub - OAuth Not Being Used.

### ISSUE THREAD

**Issue by MattPChoy** [jupyterhub/zero-to-jupyterhub-k8s#2537]
### Bug description

I've set up GitHub OAuth2 with my JuPyTerHub server running on the Oracle Cloud. I can use any username/password pair to log in and create a new environment for each unique username. I essentially want to create (at least) ONE admin account to view the users that have been created.

#### Expected behaviour

Redirect to GitHub for OAuth2 login / validation?

#### Actual behaviour

Can log into Jupyterhub server using any username/password pair

### How to reproduce

1. Go to Jupyterhub IP address
2. type in username and password
3. am logged into jupyterhub but as a standard user, even when logging in using my GitHub credentials.

### Your personal set up

This is my config.yaml
```bash
hub:
  config:
    GitHubOAuthenticator:
      client_id: MY_CLIENT_ID
      client_secret: MY_CLIENT_SECRET
      oauth_callback_url: http://JUPYTERHUB_IP_ADDR/hub/oauth_callback
    JupyterHub:
      authenticator_class: github
```

 - OS:
 
Oracle Linux 
 - Version(s):
 

- <details><summary>Full environment</summary>

```
# paste output of `pip freeze` or `conda list` here
```
</details>

- <details><summary>Configuration</summary>

```python
# jupyterhub_config.py
```
</details>

- <details><summary>Logs</summary>

```
# paste relevant logs here, if any
```
</details>

**Comment by manics** [comment]
You can specify the usernames of admins in your Z2JH configuration:
https://zero-to-jupyterhub.readthedocs.io/en/latest/jupyterhub/customizing/user-management.html#admin-users

Since this is a configuration issue please post on https://discourse.jupyter.org if you need more help. Thanks!
