### ISSUE TITLE
Support more than 1 proxy or hub replicas

### ISSUE THREAD

**Issue by elgalu** [jupyterhub/zero-to-jupyterhub-k8s#254]
What would be needed to support more than 1 proxy or hub replicas?

The proxy seems to store the route table in memory, so more than 1 proxy replica doesn't seem possible.

The hub seems to store state in sqlite but can be switched to psql, which means it can support more than 1 hub replica?

My use case is load balancing and zero downtime for a long running JupyterHub.

**Comment by yuvipanda** [comment]
Heya! 

https://github.com/jupyterhub/kubespawner/pull/64 should allow switching to a setup with HA proxies, so proxy pod going down wouldn't cause problems.

Unfortunately the hub also stores state in memory, so using psql doesn't let you have HA hubs yet. Right now when the hub process dies, only new logins / spawns are unavailable - users already logged in continue to be able to access. While this isn't good enough super long term, it sortof works ok right now... We have a long running ~3000 user Hub at UC Berkeley that we have continuous deployment for, and it works ok.

**Comment by elgalu** [comment]
Thanks!!

**Comment by elgalu** [comment]
Thanks for the prompt answer!

In our current K8s setup, pods or nodes get killed 1 to 3 times per day for reasons that are not under my control. The answer I get is that I should deploy services with minimum 3 replicas to avoid disruptions.

So if the pending in-memory state gets moved to the DB please let me know! thanks again.
