### ISSUE TITLE
Redirect loop detected. Notebook has jupyterhub version 1.4.2, but the Hub expects 1.5.0

### ISSUE THREAD

**Issue by maver1ck** [jupyterhub/zero-to-jupyterhub-k8s#2549]
### Bug description
When running helm chart version 1.2.0 I'm getting following error message:
```
500 : Internal Server Error
Redirect loop detected. Notebook has jupyterhub version 1.4.2, but the Hub expects 1.5.0. Try installing jupyterhub==1.5.0 in the user environment if you continue to have problems.
```

### How to reproduce
Install jupyterhub helm chart and login into jupyterhub.

### Your personal set up
Minikube 1.24.0
K8s v1.22.3

**Comment by manics** [comment]
Hi :wave: This sounds like a configuration problem rather than a bug. Do you mind posting this as a support question on https://discourse.jupyter.org/ instead? Please include full details of your setup and configuration, ideally enough for someone to reproduce your problem from scratch. Thanks!

**Comment by farazoman** [comment]
I'm having the same issue, using the default parameters only disabling ingress as a custom value. I'd assume with helm the referenced image in the charts should match up in terms of versions. Any hints as to what you did you resolve it?
@maver1ck

**Comment by bergkvist** [comment]
I have this problem as well, using an **empty `config.yaml`** helm-config.

> As of version 1.0.0, you don’t need any configuration to get started so you can just create a config.yaml file with some helpful comments. [(Quote from documentation)](https://zero-to-jupyterhub.readthedocs.io/en/latest/jupyterhub/installation.html)

```sh
helm upgrade --cleanup-on-fail \
  --install jhub-helm-v1 jupyterhub/jupyterhub \
  --namespace jupyterhub --create-namespace \
  --version=1.2.0 \
  --values config.yaml
```

I would definitely consider this a bug with the helm chart version [1.2.0](https://jupyterhub.github.io/helm-chart/). If I downgrade to 1.1.4, I no longer get this error message.

**Comment by stichiboi** [comment]
Had the same issue, found a solution on the [jupyter forums](https://discourse.jupyter.org/t/jupyterhub-on-k8s-not-running-redirect-loop-detected-500-internal-server-error/8197/2)

**Solution:**
I was connecting to `hub:8081` instead of `proxy-public:80`

**Comment by bohemia420** [comment]
extending @bergkvist 's answer above, here are more concrete steps:
```
helm repo add jupyterhub https://hub.jupyter.org/helm-chart/
helm repo update
helm upgrade --cleanup-on-fail --install jupyterhub jupyterhub/jupyterhub --namespace analytics --version=3.3.7 # optional add: --values config.yaml
```
version`3.3.7` is the latest at time of writing.
