### ISSUE TITLE
Improve discoverability of the latest build of the helm chart

### ISSUE THREAD

**Issue by willingc** [jupyterhub/zero-to-jupyterhub-k8s#256]
Based on discussion around #255, the longer term solution for individuals that wish to run 'the latest' master would be to improve discoverability of the latest build of the helm chart:
- tag for jupyterhub/k8s-hub
- tag for jupyterhub/k8s-singleuser-sample

**Comment by yuvipanda** [comment]
The way I think we should do this is have a HTML page at jupyterhub.github.io/helm-chart that has a table of all versions, with prominent text on how to use the latest.

**Comment by willingc** [comment]
That makes sense @yuvipanda. We probably should 'un-deprecate` the helm chart repo since that is  what is being used to generate jupyterhub.github.io/helm-chart. Correct?

**Comment by yuvipanda** [comment]
@willingc yup! we now  use it to host built charts in gh-pages repo.

**Comment by yuvipanda** [comment]
I looked into this earlier today, and dicovered a small rabbit hole!

1. https://github.com/jupyterhub/helm-chart/blob/gh-pages/index.yaml doesn't actually have useful dates! All the dates are being overwritten by build.py each time helm repo publish is run. So from that file, we can not actually tell which tag is newer than another!!!!
2. git checkout doesn't seem to preserve mtimes (at least on my machine right now), so we can't just sort by mtime
3. git preserves the time a file was added, so we'll just have to use that to determine 'latestness'. This kinda sucks.

Other than that, it should be a simple .py script that generates a simple .html file and live in the helm-chart repo's gh-pages branch. As part of CI here and in the binderhub repo, we would invoke this script before committing + pushing the tarball.

**Comment by yuvipanda** [comment]
@willingc @choldgraf @betatim @minrk I think this is sortof a 'beginner friendly' task, but it's highly possible that my sense of that is very skewed. I'll leave it to one of you to tag this as such if you think it is appropriate.

**Comment by willingc** [comment]
Down the road we may want to look at the detail page view similar to what [monocular](https://github.com/kubernetes-helm/monocular) does (you can see it in the GIF).

**Comment by zonca** [comment]
@willingc @yuvipanda I am testing a solution to this, using Jekyll,

https://zonca.github.io/helm-chart/

unfortunately cannot find a way to add dates, the `modified_date` property of the static files is always the current date

**Comment by willingc** [comment]
@zonca Nice! cc/ @minrk

**Comment by willingc** [comment]
@yuvipanda I'm going to close this issue now that https://jupyterhub.github.io/helm-chart/ exists. Let's open a new issue for any additional functionality or details that you wish to still do. Thanks again @zonca
