### ISSUE TITLE
I am unable to create a gitlab integration with the recommended jupyterhub config

### ISSUE THREAD

**Issue by floormind** [jupyterhub/zero-to-jupyterhub-k8s#2567]
### Bug description
I am trying to install jupyterhub into my GKE cluster, i currently have gitlab ee running on there. I have created a OAuth application in my running Gitlab instance and i also have an ingress created. The last thing to do is to install jupyterhub with a config values. Mine does not seem to work. 

#### Expected behaviour
I expect that when i run helm install, that i should have jupyterhub running and integrated with Gitlab

See my config below

ingress:
   enabled: true
   hosts:
     - http://jupyter.GKE-EXTERNAL-IP.nip.io/
   # tls:
   #    - hosts:
   #       - <JupyterHostanme>
   #         secretName: jupyter-cert
   # annotations:
   #    kubernetes.io/ingress.class: "nginx"
   #    kubernetes.io/tls-acme: "true"

#-----------------------------------------------------------------------------
# NO MODIFICATIONS REQUIRED BEYOND THIS POINT
#-----------------------------------------------------------------------------

hub:
  config:
    Authenticator:
      enable_auth_state: true
    GitLabOAuthenticator:
      client_id: <my client id>
      client_secret: <my client secret>
      oauth_callback_url: <http://jupyter.GKE-EXTERNAL-IP.nip.io/hub/oauth_callback>
    JupyterHub:
      authenticator_class: gitlab
    extraEnv:
      JUPYTER_ENABLE_LAB: 1
    extraConfig:
      jupyterlab: |
        c.KubeSpawner.cmd = ['jupyter-labhub']
        c.GitLabOAuthenticator.scope = ['api read_repository write_repository']

        async def add_auth_env(spawner):
           '''
           We set user's id, login and access token on single user image to
           enable repository integration for JupyterHub.
           See: https://gitlab.com/gitlab-org/gitlab-foss/issues/47138#note_154294790
           '''
           auth_state = await spawner.user.get_auth_state()

           if not auth_state:
              spawner.log.warning("No auth state for %s", spawner.user)
              return

           spawner.environment['GITLAB_ACCESS_TOKEN'] = auth_state['access_token']
           spawner.environment['GITLAB_USER_LOGIN'] = auth_state['gitlab_user']['username']
           spawner.environment['GITLAB_USER_ID'] = str(auth_state['gitlab_user']['id'])
           spawner.environment['GITLAB_USER_EMAIL'] = auth_state['gitlab_user']['email']
           spawner.environment['GITLAB_USER_NAME'] = auth_state['gitlab_user']['name']
        c.KubeSpawner.pre_spawn_hook = add_auth_env

auth:
   type: gitlab
   state:
      enabled: true

singleuser:
   defaultUrl: "/lab"
   image:
      name: registry.gitlab.com/gitlab-org/jupyterhub-user-image
      tag: latest
   lifecycleHooks:
      postStart:
         exec:
         command:
            - "sh"
            - "-c"
            - >
               git clone https://gitlab.com/gitlab-org/nurtch-demo.git DevOps-Runbook-Demo || true;
               echo "https://oauth2:${GITLAB_ACCESS_TOKEN}@${GITLAB_HOST}" > ~/.git-credentials;
               git config --global credential.helper store;
               git config --global user.email "${GITLAB_USER_EMAIL}";
               git config --global user.name "${GITLAB_USER_NAME}";
               jupyter serverextension enable --py jupyterlab_git

proxy:
   service:
      type: ClusterIP

#### Actual behaviour
upon running the helm install i get error bellow

The JupyterHub Helm chart's auth config has been reworked and requires changes.

The new way to configure authentication in chart version 0.11.0+ is printed
below for your convenience. The values are not shown by default to ensure no
secrets are exposed, run helm upgrade with --set global.safeToShowValues=true
to show them.

hub:
  config:
    Authenticator:
      enable_auth_state: '***'
    JupyterHub:
      authenticator_class: gitlab

**Comment by manics** [comment]
Hi :wave: This sounds like a configuration problem rather than a bug. Do you mind posting this as a support question on https://discourse.jupyter.org/ instead?

Please include your logs with debugging turned on. Thanks!
