### ISSUE TITLE
Readiness probe of hub pod fails (/hub/health), connection refused

### ISSUE THREAD

**Issue by nkratzke** [jupyterhub/zero-to-jupyterhub-k8s#2571]
### Bug description

After installation with this helm command:

```
helm upgrade --cleanup-on-fail \
  --install jhub jupyterhub/jupyterhub \
  --namespace jhub \
  --create-namespace \
  --values config.yaml
```

Jupyterhub is installed but the hub pod is not coming alive due to an unsuccessful readiness probe reporting a connection refused error.

#### Expected behaviour

All necessary pods and services start successfully.

#### Actual behaviour

The hub pod produces this error (readiness probe)

```
Readiness probe failed: Get "http://10.1.12.153:8081/hub/health": dial tcp 10.1.12.153:8081: connect: connection refused
```

### How to reproduce

My config.yaml looks like that:

```
debug:
  enabled: true

proxy:
  chp:
    networkPolicy:
      enabled: false
  service:
    type: ClusterIP

hub:
  networkPolicy:
    enabled: false

singleuser:
  networkPolicy:
    enabled: false
```

I assumed network policy problems, so I deactivated the network policies for debugging. But that does not change a thing.

### Your personal set up

 - OS: Ubuntu 20.04
 - Kubernetes: Microk8s (Kubernetes Version v1.23.3-2+d441060727c463, kubelet) It is a single node install.
 - zero-to-jupyterhub: 1.2.0 (Helm Chart), App-Version: 1.5.0
 
The logs of the hub pod look like:

```
[D 2022-02-06 11:38:06.674 JupyterHub application:730] Looking for /usr/local/etc/jupyterhub/jupyterhub_config in /srv/jupyterhub
Loading /usr/local/etc/jupyterhub/secret/values.yaml
No config at /usr/local/etc/jupyterhub/existing-secret/values.yaml
[D 2022-02-06 11:38:06.894 JupyterHub application:752] Loaded config file: /usr/local/etc/jupyterhub/jupyterhub_config.py
[I 2022-02-06 11:38:06.912 JupyterHub app:2479] Running JupyterHub version 1.5.0
[I 2022-02-06 11:38:06.912 JupyterHub app:2509] Using Authenticator: jupyterhub.auth.DummyAuthenticator-1.5.0
[I 2022-02-06 11:38:06.912 JupyterHub app:2509] Using Spawner: kubespawner.spawner.KubeSpawner-1.1.0
[I 2022-02-06 11:38:06.912 JupyterHub app:2509] Using Proxy: jupyterhub.proxy.ConfigurableHTTPProxy-1.5.0
[D 2022-02-06 11:38:06.913 JupyterHub app:1721] Connecting to db: sqlite:///jupyterhub.sqlite
```

The hub pod bound successfully to an NFS provided PVC. An `ls` on the volume returns:

```
jovyan@hub-6df7cdb8b9-zpsbf:/srv/jupyterhub$ ls -la
total 8
drwxrwxrwx 2 root   root   4096 Feb  6 11:15 .
drwxr-xr-x 1 root   root   4096 Nov  4 13:41 ..
-rw-r--r-- 1 jovyan jovyan    0 Feb  6 11:15 jupyterhub.sqlite
```

Which seems reasonable to me. Finally, I am a bit lost, especially because the readiness probe of the proxy pod works perfectly. And I do not see a substantial difference between the hub and the proxy readiness probe.

So, I assume somehow a bug in the hub?

**Comment by consideRatio** [comment]
It seems there is a failure to connect to the sqlite database, as there are no further logs. I suspect this is an issue about the storage you have in your k8s cluster. I see this as a "what is wrong with my k8s cluster setup" rather than "this is a bug in the helm chart we should fix". Due to that, I'd like to ask that you post this question on discourse.jupyter.org where we look to have the community overall help each other.

Please also link back to this issue from the discourse post you create, it allows anyone to find their way back and forth if they end up here and want to follow up.
