### ISSUE TITLE
svclb-proxy-public port take up

### ISSUE THREAD

**Issue by guoziqin** [jupyterhub/zero-to-jupyterhub-k8s#2575]
### Bug description
I have modified pause mirror to pause-arm64 and Kube-Schduler mirror to kube-scheduler-arm64 because I am a master and slave K3S cluster. svclb-proxy-public is displayed in hostport mode How do I do if my port is occupied? I tried to find the YAML configuration file for this Daemonset but did not find it.

#### Expected behaviour

svclb-proxy-public Daemonset failed to be scheduled due to pendding
![image](https://user-images.githubusercontent.com/37041136/153359165-cf151647-5f53-419e-aab4-543b6b7861ae.png)

### Your personal set up

 - OS:
 
 - Version(s):
helm repo jupyterhub/jupyterhub 1.2.0

- <details><summary>Full environment</summary>

```
# paste output of `pip freeze` or `conda list` here
```
</details>

- <details><summary>Configuration</summary>

```python
# jupyterhub_config.py
```
</details>

- <details><summary>Logs</summary>

```
# paste relevant logs here, if any
```
</details>

**Comment by manics** [comment]
In general we ask that JupyterHub GitHub issues are used for bugs and development discussions, with support being handled on the [community forum](https://discourse.jupyter.org/). However you may be better off asking on a Kubernetes forum, `svclb-*` isn't a Z2JH pod.

**Comment by guoziqin** [comment]
So now the scheduling is successful and it's running but the login create user will create the corresponding POD and PVC but I have timeout

**Comment by guoziqin** [comment]
![image](https://user-images.githubusercontent.com/37041136/154635099-4818f008-a0f2-4157-b036-75d04f98f541.png)
The following is a log error message for the POD of the hub
![image](https://user-images.githubusercontent.com/37041136/154635144-6f1025a8-871f-47d5-8a03-1566da890dd8.png)
The following is the user-Scheduler log information
![image](https://user-images.githubusercontent.com/37041136/154635299-71d931fa-c260-4326-912b-2aba5ca2cdf9.png)

**Comment by guoziqin** [comment]
The PVC based on the name of the created user is also in a pending state I wonder what the problem is

**Comment by guoziqin** [comment]
This is my value.yaml file that I installed through helm
![image](https://user-images.githubusercontent.com/37041136/154636421-d4bdcd13-f928-4ab2-9ae2-999da65b544e.png)

**Comment by guoziqin** [comment]
I changed the default Pause mirror to arm architecture
