### ISSUE TITLE
Default homeMountPoint is hardcoded to /home/jovyan and introduces storage ephemerality when a different NB_USER is set

### ISSUE THREAD

**Issue by muonmax** [jupyterhub/zero-to-jupyterhub-k8s#2579]
### Bug description
Official notebook images have support for changing the default user from `jovyan` using either the `-e` flag when starting the container (e.g. `docker run <...> -e NB_USER=romain <...>. jupyter/base-notebook`) or by building a new image overriding the `ARG NB_USER=jovyan` command.

However, the default `homeMountPoint` [set in the JupyterHub Helm chart](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/2d03a133eb2253e25891f3bbd59f9124cfdbdde6/jupyterhub/values.yaml#L369) is set to `/home/jovyan`. This means that although the user is correctly changed, a home folder is created, etc. anything stored outside of the folder `/home/jovyan` is not persisted.

Because the `WORKDIR` is set to `${HOME}`, and `${HOME}` is defined as `"/home/${NB_USER}"` [in the Dockerfiles](https://github.com/jupyter/docker-stacks/blob/48a41e5da58e1e3ade46309fe6bc7d7c1c48e3cc/base-notebook/Dockerfile#L58) and/or is redefined in [`start.sh`](https://github.com/jupyter/docker-stacks/blob/48a41e5da58e1e3ade46309fe6bc7d7c1c48e3cc/base-notebook/start.sh#L84), anything saved by the user will be deleted after the node shuts down, even if the storage configuration is correct.

#### Expected behaviour
When a different `NB_USER` is specified, the default `homeMountPoint` is dynamically set to be `/home/${NB_USER}` and files saved through the Jupyter interface persist between start ups.

#### Actual behaviour
When a different `NB_USER` is specified, the default `homeMountPoint` remains `/home/jovyan` and files saved through the Jupyter interface are not persisted.

### How to reproduce
1. Make a custom Docker image changing `ARG NB_USER=jovyan` to something else, or specify a different username in the hub Helm chart like:
```
singleuser:
  extraEnv:
    NB_USER: some_user
```

2. Install Helm chart and log-in to the JupyterHub. Note that the user will have changed to `some_user` and the working dir of the Jupyter instance will be `/home/some_user`

3. Save a file in the Jupyter instance.

4. Restart the node to observe file deletion.

5. Open a terminal and create a file in `/home/jovyan`. Restart node, and observe file persists.

6. Modify Helm chart to observe that changing this will now allow files to be correctly retained.
```
singleuser:
<...>
  storage:
    homeMountPath: /home/some_user
```

I suspect that there is no way to cleanly get the value of `NB_USER` into the Helm chart? Maybe the default behaviour should be to mount the `/home` directory instead of `/home/jovyan`?

### Your personal set up

 - OS:
 
 - Version(s):
 

- <details><summary>Full environment</summary>

```
# paste output of `pip freeze` or `conda list` here
```
</details>

- <details><summary>Configuration</summary>

```python
# jupyterhub_config.py
```
</details>

- <details><summary>Logs</summary>

```
# paste relevant logs here, if any
```
</details>

**Comment by manics** [comment]
As you've pointed out it's impossible to know the value of `NB_USER` from the Helm chart. There's also no requirement for `NB_USER` to be set, that's just a feature of the docker-stacks images.

Using `/home` would be a big breaking change and still isn't always correct, e.g. you might decide home directories should be under `/users/`. If you want a variable home directory the `{username}` template should be expanded:
https://github.com/jupyterhub/kubespawner/blob/2.0.0/kubespawner/spawner.py#L1031-L1052

If you need more help please post on the community forum instead https://discourse.jupyter.org/ instead.
