### ISSUE TITLE
Jupyterhub kubernetes deployment does not work with recent versions of nginx reverse proxy

### ISSUE THREAD

**Issue by brunzefb** [jupyterhub/zero-to-jupyterhub-k8s#2580]
### Bug description

We have a successful installation of Jupyter hub running on Amazon EKS (Kubernetes). We enabled ingress and are running helm chart version 1.6.16 and nginx app version 0.24.1.  Ingress with this setup works fine.  The ELB forward traffic to the nginx reverse proxy, which in turn forwards the traffic to the proxy-http component of Jupyter, life is good.  I then tried to upgrade the version of nginx to a more modern one -- chart version 3.29.0, app version 0.45 (from about March 2021).  After installing, ingress still worked, but you could not run python scripts in notebooks -- failure to connect to kernal.  Reinstalled the hub helm chart -- which resulted in the ingress being broken -- 504 error when you hit the endpoint with the browser.  After wasting a long time trying to configure nginx, I reverted back to the old nginx version, which made everything work again.

#### Expected behaviour

I expect jupyterhub to work with modern (LTS) versions of the nginx reverse proxy on k8s.

#### Actual behaviour
Ingress is broken with a recent version of nginx reverse proxy.

### How to reproduce

Deploy nginx reverse proxy on your cluster, setting appropriate ingress class.
Deploy jupyterhub, after enabling ingress, specifying the same ingress class as above
After a few minutes, hit the endpoint.  You get a 504 error.

### Your personal set up

 - OS:
 
 - Version(s):
 

- <details><summary>Full environment</summary>

```
# paste output of `pip freeze` or `conda list` here
```
</details>

- <details><summary>Configuration</summary>

```python
# jupyterhub_config.py
```
</details>

- <details><summary>Logs</summary>

```
# paste relevant logs here, if any
```
</details>

**Comment by brunzefb** [comment]
@manics - Did not know Z2JH maintains a separate issues list, I can certainly raise the issue on https://discourse.jupyter.org/  or does it belong on Z2JH? Can you provide the new link to the moved issue?   I will attempt to reproduce the issue with a vanilla jupyterhub install + nginx on AWS EKS, put all the charts, values and configuration in a github repo, so that it becomes readily reproducible for someone with an AWS account.  I'll make it all scripted, so that it brings up the cluster and installs the two helm charts.  Because of ingress, the AWS account should have a linked Route53 zone too, so that you can access it via a name with TLS.

**Comment by manics** [comment]
I've already moved the issue, this is it :smile: 

I think the best approach is to close this issue and post on https://discourse.jupyter.org/ to see if anyone else in the community has come across this problem. If you identify an actual bug then open an issue here (or on the repo corresponding to the problematic component).

**Comment by consideRatio** [comment]
Hey @brunzefb! I gave a look on this issue and couldn't translate it into an action point of something to fix in this projects documentation or helm chart, or a clear path forward.

I couldn't find a discourse.jupyter.org topic created about this yet, if one is created, please link back to this issue for reference.
