### ISSUE TITLE
jupyterhub/k8s-hub:0f87fa7 has files in /home that are owned by root

### ISSUE THREAD

**Issue by MarkusTeufelberger** [jupyterhub/zero-to-jupyterhub-k8s#259]
````
docker run --rm jupyterhub/k8s-hub:0f87fa7 ls -la /home/jovyan/
total 36
drwxr-xr-x  6 jovyan jovyan 4096 Nov  6 15:00 .
drwxr-xr-x  4 root   root   4096 Nov  6 15:00 ..
-rw-r--r--  1 jovyan jovyan  220 Nov  6 15:00 .bash_logout
-rw-r--r--  1 jovyan jovyan 3771 Nov  6 15:00 .bashrc
drwxr-xr-x  3 root   root   4096 Nov  6 15:00 .cache
drwx------  3 root   root   4096 Nov  6 15:00 .config
drwxr-xr-x  3 root   root   4096 Nov  6 15:00 .local
drwxr-xr-x 71 jovyan jovyan 4096 Nov  6 15:00 .npm
-rw-r--r--  1 jovyan jovyan  675 Nov  6 15:00 .profile
````

This makes it harder than necessary to install jupyterhub-ldapauthenticator in there because the user is not allowed to write to ~/.local

**Comment by minrk** [comment]
This doesn't appear to be the case with the current version of the image:

```bash
$ docker run --rm -it jupyterhub/k8s-hub:a27db6f ls -la /home/jovyan
total 20
drwxr-xr-x 2 jovyan jovyan 4096 Nov  7 16:23 .
drwxr-xr-x 1 root   root   4096 Nov  7 16:23 ..
-rw-r--r-- 1 jovyan jovyan  220 Nov  7 16:23 .bash_logout
-rw-r--r-- 1 jovyan jovyan 3771 Nov  7 16:23 .bashrc
-rw-r--r-- 1 jovyan jovyan  675 Nov  7 16:23 .profile
```

Have you done an extra install in an inheriting Dockerfile? Can you share it? Make sure to include `--no-cache-dir` in your `pip install` commands.

**Comment by MarkusTeufelberger** [comment]
As you see, I did execute this on the upstream docker image, you can try the command (`docker run --rm jupyterhub/k8s-hub:0f87fa7 ls -la /home/jovyan/`) to verify.

I don't find the current tag (`35b2ab6`) from https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/260 on dockerhub by the way: https://hub.docker.com/r/jupyterhub/k8s-hub/tags/ - where is this image?

**Comment by yuvipanda** [comment]
Good catch, @MarkusTeufelberger. I've fixed the current tag (which was wrong, snuck in manually since that is how we are doing this now) in https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/268
