### ISSUE TITLE
Spawn failed for named servers

### ISSUE THREAD

**Issue by prathamjagga** [jupyterhub/zero-to-jupyterhub-k8s#2598]
I have setup zero-to-jupyterhub deployment on kubernetes.
My config.yaml looks like:
![image](https://user-images.githubusercontent.com/30550632/155477657-de7620c2-9feb-49b6-b746-fab9cce3db4d.png)

Now when I open my control panel a try to start a named server, its spawn fails, I have my pod running on one of my 3 fixed nodes having the following resources: 1.8 cores of allocatable CPU and 3.1 GB allocatable RAM. And it can autoscale to 5 nodes (other nodes will also have the same resources).

See the screenshots below:

Named servers I have:
![image](https://user-images.githubusercontent.com/30550632/155478440-54e752af-02ed-4b99-becd-54c806991545.png)

Now when I start named server 1:

![image](https://user-images.githubusercontent.com/30550632/155479645-69c28c57-c703-4590-9667-5e61444fbc72.png)

Then the spawn for server 1 fails. You can see the event log in the image.

**Comment by manics** [comment]
In general we ask that JupyterHub GitHub issues are used for bugs and development discussions, with support being handled on the [community forum](https://discourse.jupyter.org/) where more people hang out, and the rest of the community can benefit from these discussions.

When you post there please include details of your Kubernetes deployment, your full Z2JH configuration, version(s) of components, and debug logs. Please also include the output of `kubectl describe pods`
