### ISSUE TITLE
hublogo.svg part of this repo - but not of built documentation

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#2599]
In #2544 @manics embedded a hublogo.svg image to this repo so we could reference it from our Chart.yaml file without depending on for example jupyter.org's website to have it in a certain location.

But, the idea was that it should be part of the rendered static content. I think though that sphinx didn't include it as it was never referenced.

I think we may be required to trick sphinx into including it, but it would be nice to not need to visitors of the website to download it. Ideas?

**Comment by manics** [comment]
Yeah, I noticed that too .... I was going to move the logo to https://github.com/jupyterhub/helm-chart/tree/gh-pages instead so it's part of the GitHub page and we don't need to mess with Sphinx or coordinate repo, didn't get round to it!
