### ISSUE TITLE
nodeSelector support

### ISSUE THREAD

**Issue by brooksambrose** [jupyterhub/zero-to-jupyterhub-k8s#263]
I'd like to use node pools on GKE to have a cheaper nodes like `n1-standard-1` host hub related pods and a more expensive nodes host user pods. Is there support for `nodeSelect` pod configuration for the hub and singleuser pods?

https://kubernetes.io/docs/concepts/configuration/assign-pod-node/

My use case is a cluster for long term student projects over the course of the semester, and I'd like to use autoscaler on the expensive node pool to go make it go to zero noes when no students are using the cluster, while leaving the hub up on something cheaper while waiting for a user to log in.

**Comment by choldgraf** [comment]
Looks like the answer is "it's coming" @brooksambrose, just in case you didn't see #270
