### ISSUE TITLE
AKS Documentation outdated?

### ISSUE THREAD

**Issue by AlexChung1995** [jupyterhub/zero-to-jupyterhub-k8s#2631]
### Bug description

Recently had to upgrade our running JupyterHub deployment on AKS. Found that the public IP for the existing deployment was no longer accessible from the internet. Have tried to redeploy a completely fresh install, fresh resource group etc. following the documentation. Still unable to access the new public ip.

#### Expected behaviour

Access base jupyterhub image at AKS public IP.

#### Actual behaviour

IP address is unavailable, browser times out when trying to access IP.

### How to reproduce

Follow documentation for deploying jupyterhub on AKS, navigate to public IP.

### Your personal set up

 - OS:
 
 - Version(s):
 

- <details><summary>Full environment</summary>

```
# paste output of `pip freeze` or `conda list` here
```
</details>

- <details><summary>Configuration</summary>

```python
# jupyterhub_config.py
```
</details>

- <details><summary>Logs</summary>

```
# paste relevant logs here, if any
```
</details>

**Comment by consideRatio** [comment]
Not sure what has changed, but knowing if you have ingress configured in the helm chart is relevant, and knowing what `kubectl describe service proxy-public` is very relevant as well.

The describe command lists associated events: events will become old and go away though, so if this is a service created a long time ago and you have no events etc, it could be helpful if it is recreated. You would do a `kubectl delete service public-proxy` and then re-deploy the helm chart with `helm upgrade ....` for that.

**Comment by AlexChung1995** [comment]
Hi @consideRatio, thanks for the response. I have no custom ingress configured in the helm chart, I've actually tried to deploy an empty config.yaml to a new cluster which is also failing. The weirdest thing is the logs/describe commands seem to mention no issues.

I do see an issue with the readiness probe to the hub pod but it seems to have likely resolved itself as it hasnt repeated.
I think this has something to do with the vnets that are created but not sure atm.

----------------------------------------------------------
kubectl describe pod hub-5bfd456c-9bf6m --namespace=jhub


Events:
  Type     Reason                  Age    From                     Message
  ----     ------                  ----   ----                     -------
  Normal   Scheduled               4m28s  default-scheduler        Successfully assigned jhub/hub-5bfd456c-9bf6m to aks-nodepool1-56243621-vmss00000c
  Normal   SuccessfulAttachVolume  4m13s  attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-b8db7579-cd04-48a2-8128-046d7b6c924d"
  Normal   Pulling                 4m10s  kubelet                  Pulling image "jupyterhub/k8s-hub:1.0.0"
  Normal   Pulled                  3m53s  kubelet                  Successfully pulled image "jupyterhub/k8s-hub:1.0.0" in 17.087627689s
  Normal   Created                 3m51s  kubelet                  Created container hub
  Normal   Started                 3m51s  kubelet                  Started container hub
  Warning  Unhealthy               3m50s  kubelet                  Readiness probe failed: Get "http://10.244.2.101:8081/hub/health": dial tcp 10.244.2.101:8081: connect: connection refused


----------------------------------------------------------------
kubectl describe service proxy-public --namespace=jhub


Name:                     proxy-public
Namespace:                jhub
Labels:                   app=jupyterhub
                          app.kubernetes.io/managed-by=Helm
                          chart=jupyterhub-1.0.0
                          component=proxy-public
                          heritage=Helm
                          release=wintermute
Annotations:              meta.helm.sh/release-name: wintermute
                          meta.helm.sh/release-namespace: jhub
Selector:                 component=proxy,release=wintermute
Type:                     LoadBalancer
IP Families:              <none>
IP:                       10.0.134.121
IPs:                      10.0.134.121
LoadBalancer Ingress:     xx.xx.xxx.xxx
Port:                     http  80/TCP
TargetPort:               http/TCP
NodePort:                 http  32586/TCP
Endpoints:                10.244.1.77:8000
Session Affinity:         None
External Traffic Policy:  Cluster
Events:
  Type    Reason                Age    From                Message
  ----    ------                ----   ----                -------
  Normal  EnsuringLoadBalancer  3m1s   service-controller  Ensuring load balancer
  Normal  EnsuredLoadBalancer   2m51s  service-controller  Ensured load balancer

**Comment by AlexChung1995** [comment]
could this possibly have something to do with netpols of the proxy pod?

**Comment by consideRatio** [comment]
If your hub pod isnt ready, check its logs with `kubectl logs deploy/hub` - if you want to verify, disable the one for the hub, i think it would be `hub.networkPolicy.enabled`

Btw you can use markdown code blocks when posting logs etc to improve readability!

**Comment by AlexChung1995** [comment]
ok looks like the netpols are ok, unless im misunderstanding this its accepting http tcp and https tcp connections

`- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    annotations:
      meta.helm.sh/release-name: wintermute
      meta.helm.sh/release-namespace: default
    creationTimestamp: "2022-03-22T22:16:31Z"
    generation: 1
    labels:
      app: jupyterhub
      app.kubernetes.io/managed-by: Helm
      chart: jupyterhub-1.2.0
      component: proxy
      heritage: Helm
      release: wintermute
    name: proxy
    namespace: default
    resourceVersion: "269433"
    uid: xxx
  spec:
    egress:
    - ports:
      - port: 8081
        protocol: TCP
      to:
      - podSelector:
          matchLabels:
            app: jupyterhub
            component: hub
            release: wintermute
    - ports:
      - port: 8888
        protocol: TCP
      to:
      - podSelector:
          matchLabels:
            app: jupyterhub
            component: singleuser-server
            release: wintermute
    - ports:
      - port: 53
        protocol: UDP
      - port: 53
        protocol: TCP
    - to:
      - ipBlock:
          cidr: 0.0.0.0/0
    ingress:
    - ports:
      - port: http
        protocol: TCP
      - port: https
        protocol: TCP
    - from:
      - podSelector:
          matchLabels:
            hub.jupyter.org/network-access-proxy-http: "true"
      ports:
      - port: http
        protocol: TCP
    - from:
      - podSelector:
          matchLabels:
            hub.jupyter.org/network-access-proxy-api: "true"
      ports:
      - port: api
        protocol: TCP
    podSelector:
      matchLabels:
        app: jupyterhub
        component: proxy
        release: wintermute
    policyTypes:
    - Ingress
    - Egress`

**Comment by AlexChung1995** [comment]
do you have any other idea what might limit incoming http connections from the jupyterhub side?

**Comment by consideRatio** [comment]
Logs for the hub pod please, and stay with 1.2.0.

**Comment by AlexChung1995** [comment]
Here are the hub logs:
`Loading /usr/local/etc/jupyterhub/secret/values.yaml
No config at /usr/local/etc/jupyterhub/existing-secret/values.yaml
[I 2022-03-22 22:17:21.920 JupyterHub app:2479] Running JupyterHub version 1.5.0
[I 2022-03-22 22:17:21.921 JupyterHub app:2509] Using Authenticator: jupyterhub.auth.DummyAuthenticator-1.5.0
[I 2022-03-22 22:17:21.921 JupyterHub app:2509] Using Spawner: kubespawner.spawner.KubeSpawner-1.1.0
[I 2022-03-22 22:17:21.921 JupyterHub app:2509] Using Proxy: jupyterhub.proxy.ConfigurableHTTPProxy-1.5.0
[I 2022-03-22 22:17:21.944 alembic.runtime.migration migration:164] Context impl SQLiteImpl.
[I 2022-03-22 22:17:21.944 alembic.runtime.migration migration:167] Will assume non-transactional DDL.
[I 2022-03-22 22:17:21.965 alembic.runtime.migration migration:556] Running stamp_revision  -> 4dc2d5a8c53c
[I 2022-03-22 22:17:21.981 alembic.runtime.migration migration:164] Context impl SQLiteImpl.
[I 2022-03-22 22:17:21.982 alembic.runtime.migration migration:167] Will assume non-transactional DDL.
[W 2022-03-22 22:17:22.139 JupyterHub app:1828] No admin users, admin interface will be unavailable.
[W 2022-03-22 22:17:22.140 JupyterHub app:1829] Add any administrative users to `c.Authenticator.admin_users` in config.
[I 2022-03-22 22:17:22.140 JupyterHub app:1858] Not using allowed_users. Any authenticated user will be allowed.
[I 2022-03-22 22:17:22.215 JupyterHub app:2546] Initialized 0 spawners in 0.002 seconds
[I 2022-03-22 22:17:22.219 JupyterHub app:2758] Not starting proxy
[I 2022-03-22 22:17:22.233 JupyterHub app:2794] Hub API listening on http://:8081/hub/
[I 2022-03-22 22:17:22.233 JupyterHub app:2796] Private Hub API connect url http://hub:8081/hub/
[I 2022-03-22 22:17:22.233 JupyterHub app:2809] Starting managed service cull-idle
[I 2022-03-22 22:17:22.233 JupyterHub service:339] Starting service 'cull-idle': ['python3', '-m', 'jupyterhub_idle_culler', '--url=http://localhost:8081/hub/api', '--timeout=3600', '--cull-every=600', '--concurrency=10']
[I 2022-03-22 22:17:22.236 JupyterHub service:121] Spawning python3 -m jupyterhub_idle_culler --url=http://localhost:8081/hub/api --timeout=3600 --cull-every=600 --concurrency=10
[I 2022-03-22 22:17:22.248 JupyterHub proxy:347] Checking routes
[I 2022-03-22 22:17:22.248 JupyterHub proxy:432] Adding route for Hub: / => http://hub:8081
[I 2022-03-22 22:17:22.252 JupyterHub app:2869] JupyterHub is now running at http://:8000
[I 2022-03-22 22:17:22.391 JupyterHub log:189] 200 GET /hub/api/users (cull-idle@::1) 17.20ms
[I 2022-03-22 22:18:22.258 JupyterHub proxy:347] Checking routes
[I 2022-03-22 22:19:22.262 JupyterHub proxy:347] Checking routes
[I 2022-03-22 22:20:22.258 JupyterHub proxy:347] Checking routes
[I 2022-03-22 22:21:22.259 JupyterHub proxy:347] Checking routes
[I 2022-03-22 22:22:22.258 JupyterHub proxy:347] Checking routes
[I 2022-03-22 22:23:22.260 JupyterHub proxy:347] Checking routes
[I 2022-03-22 22:24:22.259 JupyterHub proxy:347] Checking routes
[I 2022-03-22 22:25:22.261 JupyterHub proxy:347] Checking routes
[I 2022-03-22 22:26:22.258 JupyterHub proxy:347] Checking routes
[I 2022-03-22 22:27:22.259 JupyterHub proxy:347] Checking routes
[I 2022-03-22 22:27:22.386 JupyterHub log:189] 200 GET /hub/api/users (cull-idle@::1) 13.13ms
[I 2022-03-22 22:28:22.258 JupyterHub proxy:347] Checking routes
[I 2022-03-22 22:29:22.260 JupyterHub proxy:347] Checking routes
[I 2022-03-22 22:30:22.257 JupyterHub proxy:347] Checking routes
[I 2022-03-22 22:31:22.258 JupyterHub proxy:347] Checking routes
[I 2022-03-22 22:32:22.260 JupyterHub proxy:347] Checking routes
[I 2022-03-22 22:33:22.258 JupyterHub proxy:347] Checking routes
[I 2022-03-22 22:34:22.258 JupyterHub proxy:347] Checking routes
[I 2022-03-22 22:35:22.258 JupyterHub proxy:347] Checking routes
[I 2022-03-22 22:36:22.259 JupyterHub proxy:347] Checking routes
[I 2022-03-22 22:37:22.259 JupyterHub proxy:347] Checking routes
[I 2022-03-22 22:37:22.386 JupyterHub log:189] 200 GET /hub/api/users (cull-idle@::1) 13.02ms
[I 2022-03-22 22:38:22.259 JupyterHub proxy:347] Checking routes
[I 2022-03-22 22:39:22.258 JupyterHub proxy:347] Checking routes
[I 2022-03-22 22:40:22.258 JupyterHub proxy:347] Checking routes
[I 2022-03-22 22:41:22.259 JupyterHub proxy:347] Checking routes
[I 2022-03-22 22:42:22.259 JupyterHub proxy:347] Checking routes
[I 2022-03-22 22:43:22.259 JupyterHub proxy:347] Checking routes
[I 2022-03-22 22:44:22.259 JupyterHub proxy:347] Checking routes
[I 2022-03-22 22:45:22.258 JupyterHub proxy:347] Checking routes
[I 2022-03-22 22:46:22.258 JupyterHub proxy:347] Checking routes
[I 2022-03-22 22:47:22.258 JupyterHub proxy:347] Checking routes
[I 2022-03-22 22:47:22.387 JupyterHub log:189] 200 GET /hub/api/users (cull-idle@::1) 12.84ms
[I 2022-03-22 22:48:22.258 JupyterHub proxy:347] Checking routes
[I 2022-03-22 22:49:22.258 JupyterHub proxy:347] Checking routes
[I 2022-03-22 22:50:22.258 JupyterHub proxy:347] Checking routes
[I 2022-03-22 22:51:22.258 JupyterHub proxy:347] Checking routes
[I 2022-03-22 22:52:22.258 JupyterHub proxy:347] Checking routes
[I 2022-03-22 22:53:22.259 JupyterHub proxy:347] Checking routes
[I 2022-03-22 22:54:22.258 JupyterHub proxy:347] Checking routes
[I 2022-03-22 22:55:22.257 JupyterHub proxy:347] Checking routes
[I 2022-03-22 22:56:22.258 JupyterHub proxy:347] Checking routes
[I 2022-03-22 22:57:22.258 JupyterHub proxy:347] Checking routes
[I 2022-03-22 22:57:22.385 JupyterHub log:189] 200 GET /hub/api/users (cull-idle@::1) 12.29ms`

> Did you upgrade the helm chart, or the k8s cluster version, or both, etc? And from and to what versions?

I just upgraded the helm chart, I don't remember what the previous version was unfortunately, most likely 0.11.1 upgraded to 1.2.0.

**Comment by AlexChung1995** [comment]
based on the proxy logs, it seems traffic is fine inter cluster, but nothings coming in from outside 

- 18:59:22.258 [ConfigProxy] ←[32minfo←[39m: 200 GET /api/routes
- 19:00:22.259 [ConfigProxy] ←[32minfo←[39m: 200 GET /api/routes
- 19:01:22.259 [ConfigProxy] ←[32minfo←[39m: 200 GET /api/routes
- 19:02:22.262 [ConfigProxy] ←[32minfo←[39m: 200 GET /api/routes
- 19:03:22.257 [ConfigProxy] ←[32minfo←[39m: 200 GET /api/routes
- 19:04:22.257 [ConfigProxy] ←[32minfo←[39m: 200 GET /api/routes
- 19:05:22.259 [ConfigProxy] ←[32minfo←[39m: 200 GET /api/routes
- 19:06:22.257 [ConfigProxy] ←[32minfo←[39m: 200 GET /api/routes
- 19:07:22.259 [ConfigProxy] ←[32minfo←[39m: 200 GET /api/routes
- 19:08:22.259 [ConfigProxy] ←[32minfo←[39m: 200 GET /api/routes
- 19:09:22.259 [ConfigProxy] ←[32minfo←[39m: 200 GET /api/routes
- 19:10:22.257 [ConfigProxy] ←[32minfo←[39m: 200 GET /api/routes
- 19:11:22.258 [ConfigProxy] ←[32minfo←[39m: 200 GET /api/routes
- 19:12:22.257 [ConfigProxy] ←[32minfo←[39m: 200 GET /api/routes
- 19:13:22.259 [ConfigProxy] ←[32minfo←[39m: 200 GET /api/routes
- 19:14:22.258 [ConfigProxy] ←[32minfo←[39m: 200 GET /api/routes
- 19:15:22.265 [ConfigProxy] ←[32minfo←[39m: 200 GET /api/routes
- 19:16:22.258 [ConfigProxy] ←[32minfo←[39m: 200 GET /api/routes
- 19:17:22.260 [ConfigProxy] ←[32minfo←[39m: 200 GET /api/routes
- 19:18:22.257 [ConfigProxy] ←[32minfo←[39m: 200 GET /api/routes
- 19:19:22.261 [ConfigProxy] ←[32minfo←[39m: 200 GET /api/routes
- 19:20:22.262 [ConfigProxy] ←[32minfo←[39m: 200 GET /api/routes
- 19:21:22.257 [ConfigProxy] ←[32minfo←[39m: 200 GET /api/routes
- 19:22:22.257 [ConfigProxy] ←[32minfo←[39m: 200 GET /api/routes
- 19:23:22.257 [ConfigProxy] ←[32minfo←[39m: 200 GET /api/routes
- 19:24:22.259 [ConfigProxy] ←[32minfo←[39m: 200 GET /api/routes
- 19:25:22.258 [ConfigProxy] ←[32minfo←[39m: 200 GET /api/routes
- 19:26:22.259 [ConfigProxy] ←[32minfo←[39m: 200 GET /api/routes
- 19:27:22.258 [ConfigProxy] ←[32minfo←[39m: 200 GET /api/routes
- 19:28:22.257 [ConfigProxy] ←[32minfo←[39m: 200 GET /api/routes
- 19:29:22.258 [ConfigProxy] ←[32minfo←[39m: 200 GET /api/routes
- 19:30:22.257 [ConfigProxy] ←[32minfo←[39m: 200 GET /api/routes
- 19:31:22.259 [ConfigProxy] ←[32minfo←[39m: 200 GET /api/routes
- 19:32:22.259 [ConfigProxy] ←[32minfo←[39m: 200 GET /api/routes
- 19:33:22.258 [ConfigProxy] ←[32minfo←[39m: 200 GET /api/routes
- 19:34:22.259 [ConfigProxy] ←[32minfo←[39m: 200 GET /api/routes
- 19:35:22.263 [ConfigProxy] ←[32minfo←[39m: 200 GET /api/routes
- 19:36:22.258 [ConfigProxy] ←[32minfo←[39m: 200 GET /api/routes
- 19:37:22.257 [ConfigProxy] ←[32minfo←[39m: 200 GET /api/routes
- 19:38:22.257 [ConfigProxy] ←[32minfo←[39m: 200 GET /api/routes
- 19:39:22.259 [ConfigProxy] ←[32minfo←[39m: 200 GET /api/routes
- 19:40:22.257 [ConfigProxy] ←[32minfo←[39m: 200 GET /api/routes
- 19:41:22.258 [ConfigProxy] ←[32minfo←[39m: 200 GET /api/routes
- 19:42:22.260 [ConfigProxy] ←[32minfo←[39m: 200 GET /api/routes

you can see theres a regularly scheduled ping every minute, during this time im trying to access jhub from the internet also

**Comment by consideRatio** [comment]
And what is your current helm chart config? (Redact secret stuff)

**Comment by AlexChung1995** [comment]
is there any way to debug the proxy pod itself? can i tell if its successfully bound to the external ip of the k8s service?

**Comment by consideRatio** [comment]
Use `debug: true` in a config, and you get more detailed logs. Use `kubectl port-forward ....` to access the proxy-public service in another way than via its public ip and see if that matters.

**Comment by AlexChung1995** [comment]
port forwarding failed to port 80 but succeeded to port 8000, i thought proxy supposed to be listening on port 80?

```kubectl port-forward --address localhost pod/proxy-xxx 8888:80
Forwarding from 127.0.0.1:8888 -> 80
Forwarding from [::1]:8888 -> 80
Handling connection for 8888
Handling connection for 8888
E0323 15:26:41.242999   21348 portforward.go:400] an error occurred forwarding 8888 -> 80: error forwarding port 80 to pod xxx, uid : failed to execute portforward in network namespace "/var/run/netns/cni-xxx": failed to dial 80: dial tcp4 127.0.0.1:80: connect: connection refused
E0323 15:26:41.246976   21348 portforward.go:400] an error occurred forwarding 8888 -> 80: error forwarding port 80 to pod xxx, uid : failed to execute portforward in network namespace "/var/run/netns/cni-xxx": failed to dial 80: dial tcp4 127.0.0.1:80: connect: connection refused
Handling connection for 8888
E0323 15:26:41.309436   21348 portforward.go:400] an error occurred forwarding 8888 -> 80: error forwarding port 80 to pod xxx, uid : failed to execute portforward in network namespace "/var/run/netns/cni-xxx": failed to dial 80: dial tcp4 127.0.0.1:80: connect: connection refused
Handling connection for 8888
Handling connection for 8888
E0323 15:26:42.549323   21348 portforward.go:400] an error occurred forwarding 8888 -> 80: error forwarding port 80 to pod xxx, uid : failed to execute portforward in network namespace "/var/run/netns/cni-xxx": failed to dial 80: dial tcp4 127.0.0.1:80: connect: connection refused
E0323 15:27:12.520781   21348 portforward.go:362] error creating forwarding stream for port 8888 -> 80: Timeout occurred

kubectl port-forward --namespace=jhub --address localhost pod/proxy-7d44f4c799-btnm5 8888:8000
Forwarding from 127.0.0.1:8888 -> 8000
Forwarding from [::1]:8888 -> 8000
Handling connection for 8888
Handling connection for 8888
Handling connection for 8888
Handling connection for 8888
Handling connection for 8888
Handling connection for 8888
Handling connection for 8888
Handling connection for 8888
Handling connection for 8888

**Comment by AlexChung1995** [comment]
thanks alot for the port-forwarding suggestion btw, helping to narrow it down alot

**Comment by AlexChung1995** [comment]
from the netpol im only seeing 

```ingress:
    - ports:
      - port: http
        protocol: TCP
      - port: https
        protocol: TCP```

from

```kubectl exec --namespace=jhub proxy-xxx -- netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 :::8000                 :::*                    LISTEN      1/node
tcp        0      0 :::8001                 :::*                    LISTEN      1/node```

**Comment by consideRatio** [comment]
If you now have port forwarded, you can visit localhost:8888 and see what happens in your browser, then what happens in the proxy pods logs and hub pod logs.

Disable all network policys i suggest so we can ignore considering them for a while, and then enable them all if you get things to work and see if it still works. Thinking about one thing at the time reduces complexity and helps narrow the issue faster.

**Comment by AlexChung1995** [comment]
looks like this was an azure side bug. Hard to narrow everything down with so many SAAS component black boxes. Much thanks to you @consideRatio for your help. Was a kub noob before this issue and learned alot!

**Comment by consideRatio** [comment]
@AlexChung1995 thanks for following up!

Can you explain a bit about the Azure bug? If you followed the instructions and ended up with this, it will be a problem for many other people as well. Also if you made a small mistake, it would be good to know what small mistake led to this kind of issue.
