### ISSUE TITLE
Not able to unset fsGid & containerSecurityContext values to let the (k8s) platform configure this automatically.

### ISSUE THREAD

**Issue by BlueCog** [jupyterhub/zero-to-jupyterhub-k8s#2651]
### Proposed change
Because my team is deploying zero-to-jupyterhub-k8s to a OpenShift platform i'd would like to be able to unset **fsGid** and **containerSecurityContext** values for all deployments/containers. So that OpenShift can define them automatically in the range that is configured at the platform level. 

You would think that setting a `null` value would unset the value. But this is not possible wilt Helm v3 at the moment (when using nesterd charts). Background: https://github.com/helm/helm/issues/9136. A proposed solution would be to se an _if statement_ in the templating. 

Examples in code:
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/main/jupyterhub/templates/hub/deployment.yaml#L82
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/main/jupyterhub/templates/hub/deployment.yaml#L176
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/main/jupyterhub/templates/proxy/deployment.yaml#L170

### Alternative options
- Downloading the zero-to-jupyterhub Helm template and editing it myself: I want to avoid this
- Defining values in the allowed OpenShift range: i'd to like to let OpenShift decide this (what if the range changes?)

### Who would use this feature?
At least every OpenShift user or any other platform what needs to set these ID's automatically

### (Optional): Suggest a solution

Adding some templating to be able to enable or disable fsGid & containerSecurityContext values. 

Proposed Helm solution:

Templating (hub as example):
```
{{- if .Values.hub.fsGid.enabled }}
      securityContext:
        fsGroup: {{ .Values.hub.fsGid.id }}
{{- end }}  
 
{{- if .Values.hub.containerSecurityContext.enabled }}
{{- with .Values.hub.containerSecurityContext }}
       securityContext:
        {{- . | toYaml | nindent 12 }}
{{- end }}
{{- end }}
 
```
Override:
```
hub:
  fsGid: 
     id: 
     enabled: false
  containerSecurityContext:
    runAsUser: 
    runAsGroup: 
    allowPrivilegeEscalation: 
    enabled: false
```

**Comment by consideRatio** [comment]
```yaml
# this configuration will do the trick i think
hub:
  podSecurityContext:
  containerSecurityContext:
```

**Comment by consideRatio** [comment]
You need a not yet released version of the chart =/ You can use a development release if you want and a drafted changelog.

See https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/2528 and https://jupyterhub.github.io/helm-chart/#development-releases-jupyterhub

**Comment by lucianolacurcia** [comment]
Do you know how I can choose a specific development release for deploying using helm?

**Comment by consideRatio** [comment]
@lucianolacurcia yepp just pass `--version=<the development version>` rather than omitting that flag or similar. If you have it omitted, you will end up with the latest non-development version of the form x.y.z.

**Comment by BlueCog** [comment]
> ```yaml
> # this configuration will do the trick i think
> hub:
>   podSecurityContext:
>   containerSecurityContext:
> ```

Hello @consideRatio  

It seems that (looking at you PR) that it is still not possible to disable the `podSecurityContext` setting ?

As i stated in my startpost:

"You would think that setting a null value would unset the value. But this is not possible wilt Helm v3 at the moment (when using nesterd charts). Background: https://github.com/helm/helm/issues/9136. A proposed solution would be to se an if statement in the templating." 

Disabling this setting is needed to let OpenShift decide this on it's own...

Greets BlueCog

**Comment by consideRatio** [comment]
It should work, the with statement is a if conditional statement + setter of the . scope all at once. Try helm template to verify it works.

**Comment by consideRatio** [comment]
Now at my computer and not mobile, I look and see the following default value.

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/548111f1b7d716b744c3abaa414b76c03b7eeed9/jupyterhub/values.yaml#L86-L87

Are you saying that this does not work for any user or chart that depends on the jupyterhub chart to override?

```yaml
hub:
  podSecurityContext:
  containerSecurityContext:
```

**Comment by BlueCog** [comment]
Hey @consideRatio 

Thanks for the time to dive into this and for your proposed workaround!

I'll try deploying with your workaround and see what happends.

About your second option (via --values) this won't work in our siutation because we use ArgoCD te deploy the Helm chart (which uses helm template together with an optional override file)
