### ISSUE TITLE
Latest image (jupyterhub/k8s-hub:1.1.3-n416.h2541a732) fails with "ModuleNotFoundError: No module named 'kubernetes"

### ISSUE THREAD

**Issue by mohanrajdtv** [jupyterhub/zero-to-jupyterhub-k8s#2666]
### Bug description

Upgrading to latest image jupyterhub/k8s-hub:1.1.3-n416.h2541a732 image fails during startup with error "ModuleNotFoundError: No module named 'kubernetes'"

(https://hub.docker.com/layers/k8s-hub/jupyterhub/k8s-hub/1.1.3-n416.h2541a732/images/sha256-d91df3934a6b87260810c655638c2c33fa08fbb99063e9143ae72bb26bf13c37?context=explore)

#### Expected behaviour

Hub pod should start up

#### Actual behaviour

![image](https://user-images.githubusercontent.com/92185605/163311678-70a109e4-4c33-44cd-836b-cf1a5f15e7ac.png)

### How to reproduce

We are deploying in Azure Kubernetes 
Deploy hub using the latest image (https://hub.docker.com/layers/k8s-hub/jupyterhub/k8s-hub/1.1.3-n416.h2541a732/images/sha256-d91df3934a6b87260810c655638c2c33fa08fbb99063e9143ae72bb26bf13c37?context=explore)

### Your personal set up

zero-to-jupyterhub in azure kubernetes
 - OS:
 
 - Version(s):
 
latest jupyterhub version

<details><summary>Full environment</summary>

n/a
```
# paste output of `pip freeze` or `conda list` here
```
</details>

<details><summary>Configuration</summary>

n/a
```python
# jupyterhub_config.py
```
</details>

<details><summary>Logs</summary>

![image](https://user-images.githubusercontent.com/92185605/163312005-dc903ac7-14ed-44b6-82f0-37f323fbcca1.png)

```
# paste relevant logs here, if any
```
</details>

**Comment by consideRatio** [comment]
We dropped it in favor of kubernetes_asyncio, switch to using that library!

**Comment by consideRatio** [comment]
If you have a custom hub image, rebuild it from our latest hub image. If you had code written using kubernetes client, switch to kubernetes_asyncio client.

**Comment by mohanrajdtv** [comment]
> If you have a custom hub image, rebuild it from our latest hub image. If you had code written using kubernetes client, switch to kubernetes_asyncio client.

I am using latest hub image. Here is the docker file contents. For some reason, juypyterhub_config.py refers to kubernetes instead of kubernetes_asyncio when hub starts up

FROM jupyterhub/k8s-hub:1.1.3-n416.h2541a732

ENV \
    OAUTH2_USERNAME_KEY=https://<dns>/normalized_email

USER root

COPY deploy/sandbox/assets/templates/logo.png /usr/local/share/jupyter/hub/static/images/
COPY deploy/sandbox/assets/templates/* /etc/jupyterhub/custom/jupyterhub/templates/

USER ${NB_USER}

For completeness, I want mention under hub section in helm, I have

extraConfig:
    authConfig: |
      from oauthenticator.auth0 import Auth0OAuthenticator      
      from tornado.httpclient import HTTPRequest
      ...
      ...

**Comment by consideRatio** [comment]
Are you using the latest helm chart, and the version it reference on the hub image? I suspect you have failed to rebuild the hub image based on the latest official hub image.

Note that if you just have an image and some templates, you could manage to mount them to the hub pod avd avoid having a custom image. hub.extraFiles is a relevant config to know about, an alternative to hub.extraFiles is to do changes to hub.extraVolumes and hub.extraVolumeMounts and create a k8s configmap where you embed the templates and image etc.

See the z2jh configuration reference on hub.extraFiles.

If you can reproduce your issue without adjusting the hub image or adding extra config, it is a bug, but i think it is because of an outdated image as our tests pass without trouble.

**Comment by mohanrajdtv** [comment]
Thanks! Seeing the same error - helm config values below : 

hub:

    cookieSecret: "#{JH_COOKIESECRET}#"
    image:
      name: "jupyterhub/k8s-hub" 
      tag: "1.1.3-n416.h2541a732" 
  
    extraEnv:
      JUPYTERHUB_CRYPT_KEY: "#{JH_CRYPTKEY}#"
  
    db:
      upgrade: true
      type: postgres
      url: "#{DB_CONNECTION_STRING}#"

**Helm deployment command: helm upgrade --namespace jhub --install --values jupyterhub-helm-config.yaml --wait --version 1.2.0** 

![image](https://user-images.githubusercontent.com/92185605/163367253-7b9766ef-a2d0-40bc-a7f6-fce78a6d355d.png)

![image](https://user-images.githubusercontent.com/92185605/163367509-998f14bc-b1fa-4dc1-9684-82edec8fa062.png)

**Comment by consideRatio** [comment]
Oh but you are pinning the version of the hub image to a new image, but not using the associated Helm chart. That is why you have issues.

Note also, that you don't need to set JUPYTERHUB_CRYPT_KEY with a modern version of the Helm chart.

**Comment by mohanrajdtv** [comment]
> Oh but you are pinning the version of the hub image to a new image, but not using the associated Helm chart. That is why you have issues.
>  **Can you please explain how "to associate helm chart"? What is missing?**
> Note also, that you don't need to set JUPYTERHUB_CRYPT_KEY or cookieSecret with a modern version of the Helm chart: they are generated automatically for you.
> If we don't set these these "JUPYTERHUB_CRYPT_KEY or cookieSecret", don't we need to restart all single user pods after every deployment because keys changed. 
> Having set it as an environment variable though, you may run into some trouble if you change it at this point perhaps, not sure.
"#{JH_CRYPTKEY}# and #{JH_COOKIESECRET}" are not env variables - they are placeholders and get replaced with correct values as part of deployment.

**Comment by consideRatio** [comment]
You specified version 1.2.0, instead of the latest development version of the helm chart (weirdly enough called 1.1.3-n416.h2541a732 or similar, see https://jupyterhub.github.io/helm-chart/#development-releases-jupyterhub).

```
helm upgrade --namespace jhub --install --values jupyterhub-helm-config.yaml --wait --version 1.2.0
```

**Comment by consideRatio** [comment]
> If we don't set these these "JUPYTERHUB_CRYPT_KEY or cookieSecret", don't we need to restart all single user pods after every deployment because keys changed.

Hmmm, well, with modern versions of the Helm chart, you wont need to restart over and over at least even if maybe you had to quite a while back in time using this helm chart - I'm not sure.

> "#{JH_CRYPTKEY}# and #{JH_COOKIESECRET}" are not env variables - they are placeholders and get replaced with correct values (from azure key vault) as part of deployment.

I didn't understand this, but if it works go for it.

---

I hope this helps, please see discourse.jupyter.org for further questions and avoid setting a jupyterhub version that isn't the default, and if you do, make that image be the one that would be used by default as a base image to avoid issues.

**Comment by mohanrajdtv** [comment]
Thanks and final questions
`helm upgrade --namespace jhub --install --values config.yaml --wait --version 1.1.3-n416.he2332122` worked. Helm version in https://jupyterhub.github.io/helm-chart/#development-releases-jupyterhub does not match exactly with https://hub.docker.com/r/jupyterhub/k8s-hub/tags/ I am matching n416 between helm version and image - what is the right approach?

Can you please explain "_avoid setting a jupyterhub version that isn't the default_"?

**Comment by consideRatio** [comment]
If you inspect the helm chart, you can see its default values. Unless the hub image has changed - the chart may use an older version as a rebuild wasnt merited. So, chart/image version doesnt need to match - but they should be coupled by a chart referencing it. I think there is a `helm show` command or similar showing its default values so you can see what image version is used for a certain helm chart version.

**Comment by consideRatio** [comment]
Foe further questions, open a post in the discourse.jupyter.org forum please!
