### ISSUE TITLE
New contributor-friendly issues?

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/zero-to-jupyterhub-k8s#267]
Hey all - every now and then we get people that ask how they can contribute to JupyterHub / BinderHub / etc. They often don't have super strong technical skills, or they do but just don't have familiarity with things like kubernetes etc. How do y'all feel about a "new contributor friendly" tag that people can use to point 'em in the right direction?

**Comment by willingc** [comment]
Sounds great and very timely given https://github.com/jupyter/governance/issues/40. I've added "good first issue" to the labels to be consistent with GitHub.
