### ISSUE TITLE
Add option for extra init containers for Traefik

### ISSUE THREAD

**Issue by gregingenii** [jupyterhub/zero-to-jupyterhub-k8s#2671]
### Proposed change
Bourne out of race conditions with deploying other resources at the same time, a solution for us has been to run an init container to delay the traefik container. Currently we can't define any extra init containers (some already exist), so this change will allow users to define this, or any other, extra init containers.

### Alternative options
- Manual restarting of the traefik container after deployment, which is cumbersome
- Manual change of the chart locally, requiring us to manage the sync between the repository and our deployment

### Who would use this feature?
Anyone running into similar race conditions, or indeed any problem that could be solved with another init container for traefik

### (Optional): Suggest a solution
I have opened a PR with a potential solution: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/2670

**Comment by consideRatio** [comment]
Closed by #2670
