### ISSUE TITLE
Allow provisioning service account and not rbac resources

### ISSUE THREAD

**Issue by dingobar** [jupyterhub/zero-to-jupyterhub-k8s#2691]
### Proposed change

This somewhat relates to https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/2680.

It would be nice to split the creation of `Role` and `RoleBinding` out from `ServiceAccount`. In our cluster, we provision some default roles for each namespace and don't allow users to create their own roles. The reason for this is to keep complexity somewhat in check and try to standardize a bit across all namespaces.

The problem as I see it: Currently, the service account is always named `hub` afaict, and if `rbac.enabled=false` no account is created at all. This is blocking me from using the chart.

I think it is intuitive that the setting `rbac.enable` would only have an effect on the actual rbac API (currently `rbac.authorization.k8s.io/v1`), ie. just `Role` and `RoleBinding` in this case. We could introduce `hub.serviceAccount.create` separate from `rbac.enable`. This pattern is the one used in [apache/airflow](https://github.com/apache/airflow/blob/main/chart/templates/rbac/pod-launcher-role.yaml), and I find it quite intuitive. It would be a breaking change, though. We could expand this pattern to all service accounts, all defaulting to `true`.

Alternatively, it could be possible to let `hub.serviceAccount.create` overrule `rbac.enabled` so that if the former is set and true the `ServiceAccount` resource is created no matter what the value of `rbac.enabled` is. The default could be `null` or `""`  so that if `hub.serviceAccount.create` is not set, the old behavior with `rbac.enabled` determining the creation of `ServiceAccount` resources is used. I don't like this approach so much because it adds complexity on behalf of backwards compatibility which is probably not something we want to do too much of. Most users will pin the chart version too, if running production workloads.

Alternative three is to allow setting a service account name, something like `hub.serviceAccount.name`, that is heeded no matter the value of `rbac.enabled`, allowing a 3rd-party provisioned `ServiceAccount` with an arbitrary name.

~~In any case, currently setting `rbac.enabled=false` only supports a very specific pattern where a service account named `hub` must be manually created on the side.~~

What do you think?

**I don't mind taking a stab at implementing the a change here!**

### Alternative options
I want to avoid having to fork this repository to use the chart. I want to avoid having to manually deploy jupyterhub without helm.

### Who would use this feature?
Users of kubernetes clusters where the creation of `rbac` resources is limited but `ServiceAccount` resources are user-managed.

**Comment by consideRatio** [comment]
@dingobar thanks for thinking about this!

### Part 1

> In our cluster, we provision some default roles for each namespace and don't allow users to create their own roles.

What did you mean with "users" above? Using a terminology of a) cluster admins, b) cluster users installing helm charts, c) end users using services provided by installed helm charts. Are you saying that only cluster admins (a) can create Role and RoleBinding resources, while users installing helm charts (b) can and should create service accounts?

> The problem as I see it: Currently, the service account is always named hub afaict, and if rbac.enabled=false no account is created at all. This is blocking me from using the chart.

Ah, but the key part isn't that no account is created (you could have created that yourself as a cluster user), but that no account is referenced by the pods if you set `rbac.enabled=false` to disable creation of Role/RoleBinding resources - right?

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/c54f903c895156483000643b834ef5d1c72f47a4/jupyterhub/templates/hub/deployment.yaml#L78-L80

### Part 2

Is this a correct summary of what you propose or would like to have?

1. Let `rbac.enable` (commonly named `rbac.create` in other charts) be a toggle for creating Role and RoleBinding resources.
2. Let `hub.serviceAccount.create` be a toggle for creating a ServiceAccount
3. Let `hub.serviceAccount.name` configure the service account name referenced by a) the hub pod, b) the RoleBinding that is optionally created, and c) the ServiceAccount that is optionally created.

**Comment by dingobar** [comment]
Hi, I have some time to spare in the very near future, I think I'll take a stab at this one.

**Comment by consideRatio** [comment]
Thank you @dingobar for your work into this! I think you must do all three segments described in https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/2691#issuecomment-1126895493. I think `1` makes us need `2`, and `2` makes us need `3`.

I've tried to overview the changes I think would make sense to have in the PR addressing this issue, they are:

1. Refactoring preparations: split `rbac.yaml` template into `rbac.yaml` and `serviceaccount.yaml` for all `rbac.yaml` files
2. Let `rbac.enable` toggle creation of Role, RoleBinding, ClusterRole, and ClusterRoleBinding resources, but not the creation of the ServiceAccount resources or if pod's reference them.
3. Define and let `<path>.serviceAccount.create` toggle the creation of ServiceAccount resources for all ServiceAccount resources we define.
4. Define and let `<path>.serviceAccount.name` default to null
5. Let the logic of declaring a serviceAccountName or not in a pod spec be influenced by `<path>.serviceAccount.name` and `rbac.enable` where serviceAccount.name takes precedence, and `rbac.enable` determines if a fallback to the is to be used.
6. Documentation is updated where needed, searching for `rbac.enable` and `rbac` along the docs.
7. The `schema.yaml` file is updated to include entries for `create` and `name`, where `create must be the type boolean and `name` must be the type null or string.
8. `lint-and-validate-values.yaml` is updated to test the various ways we may configure `<path>.serviceAccount` for the 4 `<path>` options we have (`hub`, `prePuller.hook`, `scheduling.userScheduler`, `proxy.traefik`).

What do you think about this overview, did I miss something of relevance and do you think the changes as described make sense as they are described? Also, are you interested in working to make a PR with those changes? Sorry for not being able to provide quicker feedback for you.

### Off topic for now: deprecate or change `rbac.enable` to `rbac.create`

In a separate PR following this, I think we should also rename `rbac.enabled` to `rbac.create` as we have introduced a change of behavior in `rbac.enable` now seems like a good time to also do `rbac.enable` -> `rbac.create` then. I can do this later, but let's have that be a separate PR to avoid increasing the complexity of the work above that can't easily be broken apart in further pieces so easily.

**Comment by dingobar** [comment]
> Sorry for not being able to provide quicker feedback for you.

2 hours is decent for a community project :grin: 

> What do you think about this overview, did I miss something of relevance and do you think the changes as described make sense as they are described? 

Yeah, makes sense, and good to get some feedback from someone with a better overview of the project than me. I'll get to it.

**Comment by consideRatio** [comment]
@dingobar wieee thank you for your work on this!
