### ISSUE TITLE
Release v1.0 of this guide

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/zero-to-jupyterhub-k8s#27]
Tracking ticket for all the things we need to do before we can mark this release as v1

- [ ] Add some info on setting up DNS #15 
- [ ] Add info about Google, Tmp and Dummy Authenticators
- [ ] Capacity planning guidelines (how to figure out how many nodes you need)
- [ ] Discuss memory and CPU limits, and how to determine what's right for your use case
- [ ] Proper setup and tear down instructions for Google Cloud that are fully 100% tested
- [ ] Instructions about monitoring resource usage (kube dashboard, probably)
- [ ] Test the workflow with several people who aren't sysadmins to see what parts trip them up

What else?

**Comment by willingc** [comment]
- [ ] Complete grammar, spelling, link check and review of text :-)

**Comment by yuvipanda** [comment]
Actually going to close this, since this is GitHub (not phabricator!) and we can use milestones instead.
