### ISSUE TITLE
hub.image currenlty based on ubuntu:20.04 - switch to python:3.9-slim-bullseye (Debian 11)?

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#2731]
`binderhub` use a `python:3.9-slim-bullseye` image, and I've come to find a few benefits of that making me think that perhaps we should make a switch here as well for our hub image.

1. We would get Python pre-installed in our base image (ubuntu:20.04 / ubuntu:22.04 images doesn't have it pre-installed), and choose a Python version like `3.9` instead of Py38 or Py310 that are available via apt in ubuntu:20.04 and ubuntu:22.04 respectively.
2. I think we can get rid of the hub/image/dependencies script as done in binderhub https://github.com/jupyterhub/binderhub/pull/1433 easier because the base image has python pre-installed, as we can then just start a base-image container and install `pip install pip-tools && pip-compile ...`.
3. ubuntu and debian are similar, so we hopefully won't break things for end users.

Overall though, I lack experience of Debian, and have only used Ubuntu on my local computer. Maybe @minrk @yuvipanda has some linux experience of relevance?

**Comment by consideRatio** [comment]
I've trialed this more in depth in #2733, and is very happy about it so far.

**Comment by manics** [comment]
Z2JH admins are most likely to customise or debug the singleuser image based on Ubuntu 20.04 [(soon to be 22.04)](https://github.com/jupyter/docker-stacks/pull/1689), followed by the hub image (either building on top of the default hub image, or debugging weird problems).

If we switch Z2JH to Debian this means admins have to understand two operating systems. Are they similar enough that this isn't a problem?

**Comment by consideRatio** [comment]
> most likely to customise or debug the singleuser image based on Ubuntu 20.04

I think so to, because jupyter/docker-stacks have been using `ubuntu` rather than because the z2jh hub image is based on `ubuntu`. But debian and ubuntu are very similar. I didn't have to change anything related to ubuntu/debian differences in the hub image. Whoever use a `ubuntu` image for user environments can absolutely keep doing so.

To build the user environment image based on the hub image doesn't make much sense to me for someone to do. There is little  overlap between hub image and user image besides the jupyterhub version - right?

**Comment by manics** [comment]
Sorry if I wasn't clear. This isn't about building the singleuser image on top of the hub or vice-versa, it's about understanding the underlying operating system if you need to customise it, or if you need to debug some difficult problems.

If we switch the hub to Debian then admins need to understand two operating systems- Debian for the hub, and Ubuntu for the singleuser image. My question is how much extra work does that put on an admin (or on us if someone runs into problems)?

**Comment by consideRatio** [comment]
Ah yepp, excellent point of concern @manics!

I think typically you don't need to understand the hub image's operating system in detail, but if you do some customizations etc, I think those will work fine no matter what if it is ubuntu or debian. Both share `apt` as a package manager, but I don't know so well what other differences there may be that people could have issues with.

In my mind at the moment, I think admins will manage well even if they do actively build on top of the hub image. Let's consider for example [this image building on top of the hub image](https://github.com/2i2c-org/infrastructure/blob/master/helm-charts/images/hub/Dockerfile). It would keep functioning without any difference I think.

**Comment by minrk** [comment]
The hub image is pretty self-contained. While the singleuser image is _meant_ to be customized, customizing the hub image beyond a `pip install` is pretty wild-west.  I'm fine either way. The difference between debian and ubuntu for the kinds of things folks are likely to do in the hub image is pretty minimal.

Alpine is more likely to be a significant win (size-wise at least) _and_ significant cost, since it has lots of idiosyncrasies. I think we tried to do alpine some time ago, but backed off because of some compatibility issues I don't recall. However, the `musllinux` wheel work may mean that's more feasible now.
