### ISSUE TITLE
Update profile_list dynamically

### ISSUE THREAD

**Issue by oitTim** [jupyterhub/zero-to-jupyterhub-k8s#2738]
We are are attempting to make our profile_list dynamic.  We are trying to automate and avoid the 'helm update'  when we create, update or delete a profile. 

The end goal is to have an interface a user can create profiles and then submit it to Kubernetes or KubeSpawner? 

Is this currently possible? If so any explanations / examples would be greatly appreciated. 

Thanks in advance!
-Tim

**Comment by consideRatio** [comment]
I think if you combine insights from this post: https://discourse.jupyter.org/t/tailoring-spawn-options-and-server-configuration-to-certain-users/8449, then you can provide fixed Python code that doesn't change, but by interacting with something else remotely that does change - can influence the profiles.

You could for example mount an extra k8s configmap you first create into the hub pod, which can provide a yaml file your Python script would read and provide profile based on. Or, you Python script could make a REST API call to some other server, etc.

This is not a question with an actionable item to track in this repo, so it would be a question belonging to discourse.jupyter.org, for followup questions please use that forum.
