### ISSUE TITLE
namespaces forbidden error while deploying in baremetal environment

### ISSUE THREAD

**Issue by aculich** [jupyterhub/zero-to-jupyterhub-k8s#277]
---------- Forwarded message ----------
From: Tony Cricelli <tony@haas.berkeley.edu>
Date: Thu, Nov 16, 2017 at 8:11 AM
Subject: Deploying Jupyterhub on Bare Metal Kubernetes at Haas
To: @ryanlovett @yuvipanda @aculich

Hi everyone,

I am following the guide at https://zero-to-jupyterhub.readthedocs.io/en/v0.4-doc/setup-jupyterhub.html

On the part that says to do use the same name and namespace to install jupyterhub I do:
```helm install jupyterhub/jupyterhub --version=v0.4  --name=haas-ds --namespace=haas-ds -f config.yaml```

```
Error: namespaces "haas-ds" is forbidden: User "system:serviceaccount:kube-system:default" cannot get namespaces in the namespace "haas-ds"
```

So then I do `kubectl create namespace haas-ds` and retry the help command, but it still does not work.

What do you recommend I look at next?

Debug info:

```bash
$ helm version
Client: &version.Version{SemVer:"v2.7.1", GitCommit:"4aef7fddc8335e0b7b00d9168c04955d903fdbee", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.1", GitCommit:"4aef7fddc8335e0b7b00d9168c04955d903fdbee", GitTreeState:"clean"}

$ kubectl get nodes
NAME      STATUS    ROLES     AGE       VERSION
doc-10    Ready     master    18h       v1.8.3
doc-11    Ready     <none>    18h       v1.8.3
doc-12    Ready     <none>    18h       v1.8.3
doc-14    Ready     <none>    18h       v1.8.3
```

**Comment by aculich** [comment]
---------- Forwarded message ----------
From: @ryanlovett 
Date: Thu, Nov 16, 2017 at 9:52 AM
Subject: Re: Deploying Jupyterhub on Bare Metal Kubernetes at Haas
To: Tony Cricelli
Cc: @yuvipanda @aculich

Wait until Yuvi chimes in, but I think this voodoo gives the service account broad permissions:

```
# https://kubernetes.io/docs/admin/authorization/rbac/#permissive-rbac-permissions
kubectl create clusterrolebinding permissive-binding \
  --clusterrole=cluster-admin \
  --user=admin \
  --user=kubelet \
  --group=system:serviceaccounts
```

I'd try to swing-and-a-miss with this first: 

```
kubectl create rolebinding haas-ds-view \
  --clusterrole=view \
  --serviceaccount=kube-system:default \
  --namespace=haas-ds
```

but let's wait to see what the answer at the back of the book is. :)

**Comment by aculich** [comment]
---------- Forwarded message ----------
From: Tony Cricelli
Date: Thu, Nov 16, 2017 at 10:14 AM
Subject: Re: Deploying Jupyterhub on Bare Metal Kubernetes at Haas
To: @ryanlovett @yuvipanda @aculich

Hi Ryan,

I read that while waiting. I issued the following command:
```
kubectl create clusterrolebinding add-on-cluster-admin --clusterrole=cluster-admin --serviceaccount=kube-system:default
```

and helm list worked.

Then I did I  was confident enough to do this:

```
kubectl create namespace haas-ds 
```

and finally:

```
helm install jupyterhub/jupyterhub --version=v0.4  --name=haas-ds --namespace=haas-ds -f config.yaml
```

The command is just hanging, no errors, no messages on screen.

Sorry, sent that too soon the output was: `Error: timed out waiting for the condition `

**Comment by aculich** [comment]
---------- Forwarded message ----------
From: @ryanlovett 
Date: Thu, Nov 16, 2017 at 10:35 AM
Subject: Re: Deploying Jupyterhub on Bare Metal Kubernetes at Haas
To: Tony Cricelli
Cc: @yuvipanda @aculich

That command should take a while since it pulls down docker images as part of the process. You can add a timeout to helm as in the note in the docs (`--timeout=SOME-LARGE-NUMBER`), or add this to your config.yaml:

prePuller:
  enabled: False

**Comment by Montereytony** [comment]
I started over and completely documented every step of the k8s install on Ubuntu with the same results.   I did add the --timeout

helm install jupyterhub/jupyterhub     --version=v0.4     --name=haas-ds     --namespace=haas-ds     -f config.yaml  --timeout=900000

and get this message:

Error: Job failed: BackoffLimitExceeded

**Comment by aculich** [comment]
@Montereytony @ushamanandhar looks like @ryanlovett suggestion of Permissive RBAC Permissions is indeed the solution:

https://kubernetes.io/docs/admin/authorization/rbac/#permissive-rbac-permissions

```
kubectl create clusterrolebinding permissive-binding \
  --clusterrole=cluster-admin \
  --user=admin \
  --user=kubelet \
  --group=system:serviceaccounts
```

**Comment by yuvipanda** [comment]
We're fixing this with direct support for RBAC in 0.5

**Comment by Montereytony** [comment]
Thanks everyone!  You are all awesome! My  jupyterhub is up and running on the cluster. Now to ingress/egress and authentication :)

**Comment by yuvipanda** [comment]
This should be all sorted out in 0.5 - 0.6 with RBAC support on by default. Going to close this now, but feel free to re-open if you run into it again!
