### ISSUE TITLE
PEARC tutorial(s)

### ISSUE THREAD

**Issue by aculich** [jupyterhub/zero-to-jupyterhub-k8s#282]
We intend to present a hands-on z2j tutorial at [PEARC18](https://www.pearc18.pearc.org/) that will build from the PyCon tutorials currently in preparation: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/271

**Comment by yuvipanda** [comment]
I'm interested in helping with this tutorial!

**Comment by aculich** [comment]
@yuvipanda will definitely keep you in the loop along with @choldgraf and @henchc as this develops— I expect this to build heavily from what you're already doing in #271 and will deviate as little as possible, except where we might introduce material that provides more context for HPC admins who may be less familiar with this style of deployment.

**Comment by choldgraf** [comment]
Likewise I'm happy to help too! Not sure if I can make it or not (will be
in the middle of wedding planning frenzy).
--

**Comment by aculich** [comment]
@henchc @choldgraf @yuvipanda I will respond to the [PEARC18 call for participation](https://www.pearc18.pearc.org/call-for-participation) by submitting a Tutorial proposal by the **Fri 12/1 10pm EST DEADLINE** that will include answers to this requested info:

**Abstract (Maximum 250 words)**

- Summarize the proposed topic: 
- Describe the proposed organizational format: 
- Who is the intended audience?: 
- Are there any special technical requirements (A/V, network, power etc.)?: 
- Reference(s): If there has been a prior instance of the proposed (or similar) activity, provide the URL: 

Any progress on #271 ? I see @betatim pointed to [his own earlier workshop proposal](https://public.etherpad-mozilla.org/p/tim-trams-sps17). I'll borrow from that and/or whatever ya'll have been working on before I submit this one on Friday.

**Comment by betatim** [comment]
(n.b. that is a proposal for a talk not a whole workshop ... but now that you mention it, maybe it could be repurposed)

**Comment by aculich** [comment]
@jzf2101 also says that this [cft](https://fatconference.org/2018/cftutorials.html) is also useful

**Comment by aculich** [comment]
Here's a draft [google doc](https://docs.google.com/document/d/1kYHwETN5a5knWMaPWx33r_0Aj9tgr8bZM52KNwGiDxY/edit).

The abstract needs to be 250 words or less.

It is due on **Friday (today!) at 5pm Pacific Time**.

I am thinking that we have enough material to do a day-long workshop if they'll allow it.... or squeeze a lot into a half-day workshop if we can't get a whole day.

If for some reason you don't want to be (or can't be) on the submission, please let me know— or if I forgot to include anyone who wants to be part of this, then please add them to this thread.

Thanks,
 Aaron

**Comment by jzf2101** [comment]
yay! can we close this?

**Comment by aculich** [comment]
@jzf2101 thanks for the reminder and yes, we can close now that the draft has been officially submitted:

**Tutorial Organizing Committee (in alphabetical order)**
- Aaron Culich, UC Berkeley
- Jessica Forde, Project Jupyter
- Félix-Antoine Fortin, Compute Canada
- Chris Hench, UC Berkeley
- Chris Holdgraf, UC Berkeley
- M Pacer, Project Jupyter / UC Berkeley
- Carol Willing, Project Jupyter / Cal Poly San Luis Obispo
- Yuvi Panda, Project Jupyter / UC Berkeley
- Min Ragan-Kelley, Project Jupyter

**Abstract (Maximum 250 words)**

JupyterHub connects custom computational environments to multiple users via the cloud. It is a flexible, rapidly-growing technology that has proven useful in both pedagogy and research. For example, it has been used for single- and multi-day workshops as well as a 1000 student class at UC Berkeley. Building upon JupyterHub, BinderHub enables users to easily share reproducible computational environments with others. For an example of a public BinderHub service, see mybinder.org.

This day-long workshop will cover setting up BinderHub and JupyterHub in the cloud. By the end, you will have your own public-facing BinderHub deployment that allows users at your own institution to share computational environments with a public link. 

We will begin by deploying a bare JupyterHub on a commercial cloud platform using Kubernetes, a popular technology for robustly managing cloud resources. We'll cover best-practices in debugging, managing, and customizing your Kubernetes deployment, complete with hands-on exercises. We’ll show how to customize the environment your JupyterHub provides to users by using a Docker image of your choice. Next, we’ll cover how to set up a BinderHub service that allows users to automatically create their own computational environments. . We will also deploy the same infrastructure on XSEDE resources to demonstrate how easily this can be generalized to other cloud platforms. 

We’ll close the workshop with a discussion about future directions of the technology and the community, as well as an open question: How can we federate BinderHub instances with support at national and institutional levels?

**Summarize the proposed topic:** Hands-on tutorial to train researchers and instructors how to do self-service deployment of JupyterHub and BinderHub systems, as well as to train librarians, research computing staff, and others at the institutional level to install, run, and provide support to researchers and instructors who wish to go beyond the self-service, self-supported option. Additionally, we wish to use part of the workshop to strategize how we might federate the technology across campuses and at the national centers.

**Describe the proposed organizational format:** day-long hands-on workshop, software carpentry-style

**Who is the intended audience?:** This workshop will be useful for educators, researchers, librarians, or research computing staff who are interested in deploying a BinderHub + JupyterHub. That could be for their own purposes (either in teaching or in research) or at their institution. This workshop doesn't require any specific technical skills - we step you through everything that is needed from start to finish. It does require a laptop to participate in the hand-on parts of the workshop as well as a google account to participate in the Kubernetes portion of the tutorial. Familiarity with the shell, editing text files, and a general knowledge of what we mean by "the cloud" will be helpful.

**Are there any special technical requirements (A/V, network, power etc.)?:** Power strips with sufficient access for all participants for full duration, wifi, projection equipment. Prefer desk/tables that participants can work at during tutorial.

**Reference(s):** If there has been a prior instance of the proposed (or similar) activity, provide the URL:
[JupyterCon 2017: Deploying JupyterHub for students and researchers](https://conferences.oreilly.com/jupyter/jup-ny/public/schedule/detail/60075)
[2017 Binder Workshop](http://ivory.idyll.org/blog/2017-binder-workshop.html) (and [github repo](https://github.com/ctb/2017-binder-workshop-notes/))
[Zero to JupyterHub](https://zero-to-jupyterhub-with-kubernetes.readthedocs.io/en/latest/)
[PEARC17: Portable learning environments for hands-on computational instruction: Using container- and cloud-based technology to teach data science](http://sched.co/Aq90)


and we have confirmation:


---------- Forwarded message ----------
From: PEARC18 Submissions <do_not_reply@linklings.com>
Date: Fri, Dec 8, 2017 at 5:22 PM
Subject: PEARC18 Tutorials Submission Confirmation
To: aculich@berkeley.edu



Dear Aaron Culich,

Your submission, "Hands-on Tutorial Deploying Portable Research and Learning Environments on Commercial Clouds and XSEDE" (tut149s1),
to PEARC18 (PEARC18), has been received.

You can update this submission until the deadline: 10pm (EST) Dec 8, 2017.

The one and only URL you need for all things pertaining to your submission is:

https://ssl.linklings.net/conferences/pearc/

You can and should verify that the information you submitted was properly
received by signing into the submission web site. If you have forgotten your
password, use the 'forgot password?' link on the submission web site front
page. After signing into the web site you may also modify or withdraw your
submission (until submissions close).

Thank you for your submission!

Sincerely,
        Sergiu Sanielevici
        sergiu@psc.edu
        https://ssl.linklings.net/conferences/pearc/
```
