### ISSUE TITLE
Single-user pods and other associated resources should have ownerReferences set to the jupyter-hub

### ISSUE THREAD

**Issue by TomHellier** [jupyterhub/zero-to-jupyterhub-k8s#2837]
### Proposed change

I use argocd to manage kubernetes clusters, and therefore rarely look at the kubernetes dashboard.

I have recently started using jupyter notebooks using zero-to-jupyterhub running inside a kubernetes cluster. I was expecting to be able to see the single-user pods using the Argocd ui.

I believe the ownerReference of the single-user pods should be the Hub deployment. I suspect that this would require changes to zero-to-jupyterhub helm charts as well, but from what I can see, there is no way to set the ownerReference using the API provided by this project.

### Alternative options

N/A - Owner references should clearly show the ownership of resources in kubernetes, and as the jupyter-hub is the application responsible for the lifecycle of single user components, it should own those resources.

### Who would use this feature?

It would help render the ownership of the jupyter resources in the argocd view, but it is also best practise to ensure the relationship between resources are known by kubernetes.

The drawback of this, is a deletion of the JupyterHub deployment would force a deletion of all of the single user pods and associated pvc's etc.

### (Optional): Suggest a solution

I suspect if any changes were to be made, they would need to be done here to support adding ownerReferences:
https://github.com/jupyterhub/kubespawner/issues/628

**Comment by consideRatio** [comment]
Closing here and replying in https://github.com/jupyterhub/kubespawner/issues/628
