### ISSUE TITLE
jupyter/docker-stacks no longer provide multiplatform images - that influences our singleuser-sample image on arm

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#2844]
We have relied on jupyter/docker-stacks to provide amd64/arm64 multiplatform images, but they are no longer around but they are meant to be around. We can follow https://github.com/jupyter/docker-stacks/issues/1737 for progress and help out there.

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/6fc3d41fc8032b04f2ad1fd8da7ed15827cc3812/images/singleuser-sample/Dockerfile#L1

**Comment by minrk** [comment]
I wonder if we should simplify our singleuser-sample to not build on docker-stacks? It can be a pretty basic:

1. `FROM python:3.10`
2. create a `jovyan` user
3. requirements.txt (managed by `pip-compile` like hub)

_almost_ all 'real' deployments need to specify a user image, so this should really be basic. That is, unless we want to change the scope of our single-user-sample image to be more of a for-production image (in which case, I think sticking with docker-stacks is the right choice).

**Comment by mathbunnyru** [comment]
I'm sorry for breaking your use case.
I would like to propose another solution (it will work if you don't use multi-platform building yourself):

Instead of using:
```
FROM jupyter/base-notebook:latest 
```

you can use:
```
ARG BASE_IMAGE= jupyter/base-notebook:latest
FROM $BASE_IMAGE 
```
and then set BASE_IMAGE for `aarch64`.

This way you will still use docker-stacks and everything will work for `aarch64`.

And then, when the mentioned issue is fixed, there will be a small revert for this change.

**Comment by consideRatio** [comment]
This helm chart provides a multi-platform image as well, so working around it became tricky =/

Overall though, this is just meant to be influencing:
1. What we test against in our CI system
2. What users maybe verify functionality against when they have just installed this Helm chart

**Comment by mathbunnyru** [comment]
Now jupyter docker stacks are multi-arch.
So, if you would like to switch back, I think it's gonna be easy.
