### ISSUE TITLE
Remove old GitHub Releases for this project?

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#2861]
We currently don't rely on [GitHub Releases](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/releases), but instead on git tags to declare new versions etc. If someone relied on GitHub Releases, for example because they use a github api to access the latest GitHub release, they can do so with `helm show chart` from the helm chart repo directly instead.

The situation is that whenever we now make a new release by pushing a git tag, we end up also needing to create a GitHub Release to avoid that the github UI showing us an old version.

![image](https://user-images.githubusercontent.com/3837114/188832336-2b154425-31c7-424f-9119-d0c96a0f5770.png)

So, should we simply remove all old github releases?

**Comment by minrk** [comment]
I'd vote for yes, though the first few releases have actual release notes. We should double-check that they are in the changelog in the docs before deleting (I think they are)

**Comment by manics** [comment]
A few people have reacted to the last two GitHub Releases, so someone's obviously watching them!
![image](https://user-images.githubusercontent.com/1644105/190922684-0b668db3-2772-4aaf-bf04-cec8653f506a.png)

Could we use a GitHub action to automatically create a release when a tag is created, and just link to the changelog as at present?
