### ISSUE TITLE
Security Vulnerability ? Can admin see all my files using `kubectl exec` to my container?

### ISSUE THREAD

**Issue by datlife** [jupyterhub/zero-to-jupyterhub-k8s#2873]
### Bug description

As a hub user, I have a need to store sensitive data (.ssh configs and other key information). In my helm setup, I intentionally leave the `admin_access` False so that I hope admin cannot access my files.

#### Expected behaviour

Only users logged in through Jupyterhub can only access local files in a PVC.

#### Actual behaviour

However, as a K8s admin, one can simply run do a `kubectl exect -it <container> /bin/bash` to login and read all my files

### Your personal set up

On-prem K8s using K3s
 - OS: Ubuntu 20.04
 - Version(s): jupyterhub 3.0

**Comment by manics** [comment]
JupyterHub or Z2JH run on top of your base infrastructure, whether that's K8s, a virtual machine on public cloud, a physical server in your datacentre, on a HPC cluster, etc. In all cases an infrastructure admin can potentially access almost anything. If you don't trust your infrastructure admins you shouldn't run anything sensitive there.
