### ISSUE TITLE
Replace microk8s doc with a generic k8s bare metal overview

### ISSUE THREAD

**Issue by manics** [jupyterhub/zero-to-jupyterhub-k8s#2880]
### Proposed change
Someone's reported having problems with Microk8s in https://discourse.jupyter.org/t/jupyterhub-spawns-not-actually-launching/15652
https://zero-to-jupyterhub.readthedocs.io/en/stable/kubernetes/other-infrastructure/step-zero-microk8s.html

We don't have the experience or capacity to check the Z2JH Microk8s instructions. What do you think about removing it, and instead having a high-level self-managed Kubernetes guide? Something along the lines of "If you are installing your own Kubernetes cluster you should ensure it supports dynamic volume provisioning, network policies, etc.", along with caveats about how support is limited? Optionally with links to some k8s distributions such as k3s, microk8s.

### Alternative options
Do nothing.

### Who would use this feature?
Users planning to run Z2JH on their own self-managed infrastructure. This would make it clear that it's not as straightforward as installing on public cloud.

### (Optional): Suggest a solution
Replace the microk8s doc with a high level general k8s doc.

**Comment by DeepSkyWonder** [comment]
I think the microk8s instructions are a really important part of the documentation. They offer a straight forward pathway to a bare metal install especially on Ubuntu. This is important to research groups doing there own devops. It offers them a simple clean pathway to JupyterHub cluster.

**Comment by DeepSkyWonder** [comment]
Also just to confirm, there definitely is an issue with MicroK8s, the spawner and PVCs as wesley burr described. The notebooks simply do not spawn, they stay in pending state, and there is nothing in the pod logs.

**Comment by minrk** [comment]
My opinion is that if you're using self-managed/microk8s, you ought to be a kubernetes expert, and are mostly on your own. That doesn't mean it doesn't work, but it does mean it's not _supported_ (i.e. we can't help you if you have problems). We can add some notes about specific caveats as you mentioned (volumes, network policies, services, etc.), but I think that's as far as we should go.

I think we should only aim to support _managed_ kubernetes with this tutorial. k3s/etc. are in-scope to the degree that we can get whatever we use for CI / local testing working, but I wouldn't consider any roll-your-own or on-metal kubernetes something we should cover in these docs.

And the tutorial/chart are fully valid with any kubernetes, once you start from "I have a cluster," if it really is a fully working kubernetes, which many self-hosted clusters are not.

**Comment by ebebpl** [comment]
We are planning on deploying Z2JH on microk8s since we have a VMware Centos VM to work with. Microk8s instructions are useful and needed for local deployments of k8s and we will report any issues we find in the docs.

**Comment by manics** [comment]
@ebebpl Have you thought about publishing your own instructions on GitHub pages, your website, or as an article on [the Jupyter community forum](https://discourse.jupyter.org/)? We can then link to it from the Z2JH docs, and also link to any other platforms that people have written instructions for. I think this is a more sustainable option than trying to bundle everything in this repository.

**Comment by ebebpl** [comment]
@manics yes very good idea, will try and write simple steps and issues encountered as we go through the install steps on Centos/microk8s.
