### ISSUE TITLE
Replace `vim` with `nano` in the hub image

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#2916]
Our `hub` image installs the apt package `vim` to provide one text editor, but by doing so have included a lot of unfixable known vulnerabilities that has been around for a very long time now without being fixed. The purpose of having an terminal based text editor in the hub image is just to make our life as admins easier when debugging things, and for this purpose `nano` also works.

Due to this, I'm proposing that we replace `vim` with `nano` which is as I understand the default editor for Debian Linux that we use. Due to this, and being lightweight, I expect it to result in less unpatched known vulnerabilities.

This investigationg was prompted by @fifofonix mentioning that many vulnerabilities stems from `vim` in https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/2586#issuecomment-1290389415.

```
# python:3.9-slim-bullseye after apt-get upgrade
Total: 84 (UNKNOWN: 0, LOW: 12, MEDIUM: 31, HIGH: 37, CRITICAL: 4)

# python:3.9-slim-bullseye after apt-get upgrade and nano installed (no change)
Total: 84 (UNKNOWN: 0, LOW: 12, MEDIUM: 31, HIGH: 37, CRITICAL: 4)

# python:3.9-slim-bullseye after apt-get upgrade and install vim (16 more critical, 300+ more high)
Total: 576 (UNKNOWN: 0, LOW: 16, MEDIUM: 111, HIGH: 429, CRITICAL: 20)
```

---

Note that artifacthub.io provides automated scanning of our Helm chart's images: https://artifacthub.io/packages/helm/jupyterhub/jupyterhub?modal=security-report

**Comment by consideRatio** [comment]
@fifofonix do you want to go for a PR replacing vim with nano? =)

**Comment by fifofonix** [comment]
@consideRatio I would like to but it is going to take me a couple of months to get to this given prior commitments.  Note, I still think that the vulnerabilities are high compared to jupyterhub/jupyterhub and I wonder whether more image convergence is possible?

**Comment by consideRatio** [comment]
I found 0 vulnerabilities in a fresh build of the jupyterhub/jupyterhub provided Dockerfile.

@fifofonix it seems that use of `ubuntu:22.04` + installing Python instead of using `python:3.9-slim-bullseye` is the key difference. I'm not ready to switch away from `python` images atm without further motivation.

**Comment by consideRatio** [comment]
Got hooked to investigate a bit further and conclude that `debian:bullseye` based images have more vulnerabilites than `ubuntu:22.04` - for unknown reason.

**Comment by consideRatio** [comment]
We decided to not remove it, but work is underway to reduce known vulnerabilities by switching to ubuntu:22.04 from debian:slim-bullseye (via python:3.9-bullseye-slim).
