### ISSUE TITLE
publish workflow can't push to `jupyterhub/k8s-hub-slim`

### ISSUE THREAD

**Issue by manics** [jupyterhub/zero-to-jupyterhub-k8s#2928]
### Bug description

I've just merged #2920 from @consideratio but the publish workflow failed. Presumably the repo needs to be created and a token added/updated?
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/actions/runs/3399825278

**Comment by consideRatio** [comment]
Thanks for following up and investigating that! I'm quite confident you are right and I've created such hub.docker.org repository now with permissions to the "bots" team just like the jupyterhub/k8s-hub image is configured.

**Comment by consideRatio** [comment]
Resolved!
