### ISSUE TITLE
Eliminate the need to hardcode admin_user on the config for sso users. Is there a way to make a sso user admin_user based on the role claim received from the oauth token? 

### ISSUE THREAD

**Issue by npandeya** [jupyterhub/zero-to-jupyterhub-k8s#2947]

**Comment by consideRatio** [comment]
I think the [notes here are critical](https://github.com/jupyterhub/jupyterhub/blob/730fe5a44690dbae73309361f4be20672118fb07/jupyterhub/auth.py#L399-408):

```
            authentication (dict): User authentication data dictionary. Contains the
                username ('name'), admin status ('admin'), and auth state dictionary ('auth_state').
```

And, that you can resolve this by using an [`post_auth_hook` documented here](https://jupyterhub.readthedocs.io/en/stable/api/auth.html#jupyterhub.auth.Authenticator.post_auth_hook).
