### ISSUE TITLE
Ingress rules

### ISSUE THREAD

**Issue by rgherta** [jupyterhub/zero-to-jupyterhub-k8s#2958]
### Bug description

When using the helm chart with the following config

```
ingress:
  enabled: true
  ingressClassName: haproxy
  pathSuffix: hub
  pathType: Prefix

```

The following ingress is created

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    meta.helm.sh/release-name: kt-jupyterhub
    meta.helm.sh/release-namespace: development
  creationTimestamp: "2022-11-24T11:43:18Z"
  generation: 1
  labels:
    app: jupyterhub
    app.kubernetes.io/managed-by: Helm
    chart: jupyterhub-2.0.0
    component: ingress
    heritage: Helm
    release: kt-jupyterhub
  name: jupyterhub
  namespace: development
  resourceVersion: "43593852"
  uid: d55d1bbf-840e-4cff-a8bf-00a903e53905
spec:
  ingressClassName: haproxy
  rules:
  - http:
      paths:
      - backend:
          service:
            name: proxy-public
            port:
              name: http
        path: /hub
        pathType: Prefix

```

#### Expected behaviour

I expect the ingress rule to have botrh /hub and /user in order to properly work

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    meta.helm.sh/release-name: kt-jupyterhub
    meta.helm.sh/release-namespace: development
  creationTimestamp: "2022-11-24T11:43:18Z"
  generation: 1
  labels:
    app: jupyterhub
    app.kubernetes.io/managed-by: Helm
    chart: jupyterhub-2.0.0
    component: ingress
    heritage: Helm
    release: kt-jupyterhub
  name: jupyterhub
  namespace: development
  resourceVersion: "43593852"
  uid: d55d1bbf-840e-4cff-a8bf-00a903e53905
spec:
  ingressClassName: haproxy
  rules:
  - http:
      paths:
      - backend:
          service:
            name: proxy-public
            port:
              name: http
        path: /hub
        pathType: Prefix
      - backend:
          service:
            name: proxy-public
            port:
              name: http
        path: /user
        pathType: Prefix

```

#### Actual behaviour

The Ingress resource has a single rule for /hub . When creating a new jupyterlab instance the user is redirected to /user that is not accessible because ingress does not contain that rule. When manually adding the rule, everything works as expected. It could be that I misread the documentation or missed a helm config option, in this case, thank your help.

**Comment by consideRatio** [comment]
The ingress routes traffic to a proxy pod, which in turn routes traffic onwards based on /hub and /user etc. This proxy pod is remote controlled by JupyterHub in the `hub` pod to route traffic to user servers if user servers are started etc.

There are other implementations of the "proxy" part that JupyterHub controls. JupyterHub could use KubeIngressProxy where it instead creates Ingress resources for users starting servers etc, but this helm chart doesn't support that and its a very advanced use case.
