### ISSUE TITLE
Cannot use generic ephemeral volume in extraVolumes

### ISSUE THREAD

**Issue by jpolchlo** [jupyterhub/zero-to-jupyterhub-k8s#2977]
### Bug description

I am attempting to use `singleuser.storage.extraVolumes` and `extraVolumeMounts` to create a scratch volume on the singleuser pod.  Documentation [suggests](https://z2jh.jupyter.org/en/latest/resources/reference.html#singleuser-storage-extravolumes) that I should be able to use normal k8s syntax for creating this volume, so I am using the [syntax for a generic ephemeral volume](https://kubernetes.io/docs/concepts/storage/ephemeral-volumes/#generic-ephemeral-volumes) as follows:
```yaml
  storage:
    extraVolumeMounts:
      - mountPath: "/scratch"
        name: scratch-volume
    extraVolumes:
      - name: scratch-volume
        ephemeral:
          volumeClaimTemplate:
            metadata:
              labels:
                type: jupyter-singleuser-scratch
            spec:
              accessModes: ["ReadWriteOnce"]
              storageClassName: gp2
              volumeMode: Filesystem
              resources:
                requests:
                  storage: 256Gi
```

#### Expected behaviour

I would expect this setup to create a generic ephemeral volume.

#### Actual behaviour

In the logs, I then observe the following error:
```
      File "/usr/local/lib/python3.8/dist-packages/kubespawner/spawner.py", line 1867, in get_pod_manifest
        return make_pod(
      File "/usr/local/lib/python3.8/dist-packages/kubespawner/objects.py", line 571, in make_pod
        pod.spec.volumes = [get_k8s_model(V1Volume, obj) for obj in volumes]
      File "/usr/local/lib/python3.8/dist-packages/kubespawner/objects.py", line 571, in <listcomp>
        pod.spec.volumes = [get_k8s_model(V1Volume, obj) for obj in volumes]
      File "/usr/local/lib/python3.8/dist-packages/kubespawner/utils.py", line 94, in get_k8s_model
        model_dict = _map_dict_keys_to_model_attributes(model_type, model_dict)
      File "/usr/local/lib/python3.8/dist-packages/kubespawner/utils.py", line 132, in _map_dict_keys_to_model_attributes
        new_dict[_get_k8s_model_attribute(model_type, key)] = value
      File "/usr/local/lib/python3.8/dist-packages/kubespawner/utils.py", line 184, in _get_k8s_model_attribute
        raise ValueError(
    ValueError: 'V1Volume' did not have an attribute matching 'ephemeral'
```
### How to reproduce

Add the above YAML to the JupyterHub chart values.

### Your personal set up

This is deployed on EKS using the Helm chart with the extra volume configurations given above.

**Comment by manics** [comment]
Which versions of Kubernetes and Z2JH are you using? `/usr/local/lib/python3.8/` implies you're using an outdated version of the hub image.

**Comment by jpolchlo** [comment]
Kubernetes 1.23 on EKS.  JupyterHub chart version 1.2.0, app version 1.5.0.

**Comment by consideRatio** [comment]
@jpolchlo the issue you experience is related to the version of https://github.com/kubernetes-client/python as used by jupyterhub/kubespawner, and that is older in the z2jh version 1.2.0 image than in the 2.0.0 image I think.

## 1.2.0 - k8s 1.17 features are supported

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/5c0d0c5c74bc97bf403844ced6b8e79cc089498d/images/hub/requirements.txt#L81-L82

## 2.0.0 - k8s 1.24 features are supported

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/cf3f00a7ee4beaea12df86693721d93f3f6b13a9/images/hub/requirements.txt#L91-L92

Note that z2jh 2.0.0 use kubernetes-asyncio which is a kubernetes api-server client just like the other but using async/await logic, which should influence you as a user unless you have written custom code. Whats important is that z2jh 2.0.0 has a far more modern k8s client it relies on, which should resolve your issue.

**Comment by jpolchlo** [comment]
Oh, rad.  It's been on my list to move to JH 2.0.0, so I'll give that a whirl.  I'll let you know!
