### ISSUE TITLE
New release with changes updating jupyterhub to 3.1.0?

### ISSUE THREAD

**Issue by gongomgra** [jupyterhub/zero-to-jupyterhub-k8s#2978]
### Proposed change
I see [a commit](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/commit/f0327067c41b9689e18777d522e318bffe4fe239) was recently merged into main branch updating jupyterhub version from `3.0.0` to `3.1.0`. However, there isn't a new version including this changes, and latest [`2.0.0` tag](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/tree/2.0.0) includes `jupyterhub==3.0.0`. Do you plan to perform a new release including the updated requirements?

### (Optional): Suggest a solution
Perform an official release.

**Comment by consideRatio** [comment]
These breaking changes are currently merged into the main branch:

- https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/2936
- https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/2919

I'd like to get a new release of KubeSpawner with some breaking changes to land as well:
- https://github.com/jupyterhub/kubespawner/pull/650

An option to releasing z2jh 3.0.0 is to backport a release, z2jh 2.1.0 with jh 3.1.0, but I'm not very comfortable doing that technically - but that would be acceptable as well.

I can't give a time estimate.

**Comment by manics** [comment]
I can't see anything in 3.1.0 that justifies the effort of a backport.

@gongomgra what are the features in 3.1.0 that you require?

**Comment by manics** [comment]
We're going straight to JupyterHub 4.0.0 (currently in beta)
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/3045
