### ISSUE TITLE
Integrating jupyter-scheduler

### ISSUE THREAD

**Issue by jabbera** [jupyterhub/zero-to-jupyterhub-k8s#2980]
### Proposed change
I'd love some official guidance on how to integrate: https://github.com/jupyter-server/jupyter-scheduler

### Who would use this feature?
EVERYONE!:-)

**Comment by manics** [comment]
That's a good question! Would you mind asking this on the [community forum](https://discourse.jupyter.org/) where more people hang out, and the rest of the community can benefit from these discussions?
