### ISSUE TITLE
Download files from blob using hub.services (fastAPI) to user pod

### ISSUE THREAD

**Issue by harisanwar64** [jupyterhub/zero-to-jupyterhub-k8s#2986]
I'm would like to download files from blob storage to user's pod space. I have deployed fastAPI hub services to download files from blob using 'azcopy' in restAPI POST endpoint using:

hub:
  services:
    myapp:
      url: http://hub:8181
      command:
        - /home/jovyan/.local/bin/uvicorn
        - app:app
        - --port
        - "8181"
        - --host
        - "0.0.0.0"
        - --app-dir
        - /usr/src/myapputils
      oauth_redirect_uri: http://10.134.197.222:8080/services/myapp/oauth_callback
      environment:
        PUBLIC_HOST: http://10.134.197.222:8080
       
Python code in POST endpoint (azcopy) deployed to hub pod:

subprocess.call(["azcopy", "sync", "https://" + BLOB_ACCOUNT_NAME + ".blob.core.windows.net/" + CONTAINER_FOLDER + "/" + ZIP_ON_BLOB + CONTAINER_SAS, LOCAL_FOLDER + ZIP_ON_BLOB], cwd="/")
  
 File is successfully downloaded to hub pod /home/jovyan directory. However, i want to download files in user pod space instead of hub. As single user pod won't support 'services' feature in Z2JH, is there any better approach to download files from blob directly to user pod?
 
Thanks in advance!

**Comment by manics** [comment]
Hi! This sounds like the sort of question that would benefit from community input. If you post it on the community forum https://discourse.jupyter.org/ you might get more ideas, or at least inspire other people to think about it.
