### ISSUE TITLE
Scope problems on upgrade

### ISSUE THREAD

**Issue by vivian-rook** [jupyterhub/zero-to-jupyterhub-k8s#2996]
Since upgrading to the 2.0.0 chart (and k8s-hub 2.0.0) in https://github.com/toolforge/paws/pull/236 we've been having some issues, the initial loading page doesn't complete and one has to manually reload the page after login to get to their server. Additionally the admin page is blank, and stop server gives: 
```API request failed (403): Action is not authorized with current scopes; requires any of [delete:servers]```
With notes in the hub pod logs like:
```
[W 2023-01-13 15:05:59.897 JupyterHub base:89] Blocking Cross Origin API request.  Referer: https://hub.paws-dev.codfw1dev.wmcloud.org/hub/home, Host: hub.paws-dev.codfw1dev.wmcloud.org, Host URL: http://hub.paws-dev.codfw1dev.wmcloud.org/hub/
[W 2023-01-13 15:05:59.907 JupyterHub scopes:804] Not authorizing access to /hub/api/users/VRook_(WMF)/server. Requires any of [delete:servers], not derived from scopes []
[W 2023-01-13 15:05:59.907 JupyterHub web:1796] 403 DELETE /hub/api/users/VRook_(WMF)/server (10.100.0.0): Action is not authorized with current scopes; requires any of [delete:servers]
[W 2023-01-13 15:05:59.911 JupyterHub log:186] 403 DELETE /hub/api/users/VRook_(WMF)/server (@10.100.0.0) 24.62ms
```

Requests in our setup are routed through haproxy which terminates tls. If I disable tls the issue is resolved, alternatively adding:
```
    http-request set-header REFERER http://hub.paws-dev.codfw1dev.wmcloud.org/hub/
```
to the haproxy configs also gets this working.

It seems like this is due to jupyter comparing 'http' to 'https' Rather than the domain to the referrer domain?

https://github.com/jupyterhub/jupyterhub/issues/3780 seems related

#### Expected behaviour

login page should show loading status, and then redirect to server. Admin page should show, and server can be stopped by user.

some more information at:
https://phabricator.wikimedia.org/T326217

**Comment by manics** [comment]
This usually means your front-end proxy/load-balancer is missing or incorrectly setting some headers, which means JupyterHub doesn't know you're using https on the front end. This leads to the cross-site error, since http and https are different origin.
