### ISSUE TITLE
Do a spelling consistency check for JupyterHub

### ISSUE THREAD

**Issue by willingc** [jupyterhub/zero-to-jupyterhub-k8s#3]
JupyterHub should have the 'H' in caps.

**Comment by parente** [comment]
I'm giving a short talk tomorrow to a capstone class at RPI about contributing to open source. Mind if I grab this one as a live example of how contributions can come in many forms, not just code?

**Comment by willingc** [comment]
Go for it! Good luck on the talk @parente.

**Comment by parente** [comment]
Well, screen share failed me during the talk, but I'll still tackle this tonight and take a video for the attendees to see what I was going to do.
