### ISSUE TITLE
singleuser.image.name does nothing?

### ISSUE THREAD

**Issue by DylanAlloy** [jupyterhub/zero-to-jupyterhub-k8s#3001]
### Bug description

If I fill out a secret's worth of metadata in 

```
imagePullSecret:
  create: true
  registry: 
  email:
  username: ""
  password: ""
```

and adding an image from a private repository to the singleuser block:

```
image:
    name: private/private/jupyter-single-user
    tag: "latest"
    pullPolicy: "Always"
    pullSecrets: "image-pull-secret"
```

I can redeploy my changes yet the `hub` secret still contains a values.yaml key where in the value is this:

![Screen Shot 2023-01-24 at 8 28 12 AM](https://user-images.githubusercontent.com/12659763/214328696-a4ec047f-94df-4de7-86cf-6ce96555c3b7.png)

#### Expected behaviour

Thought by changing my `imagePullSecret` chunk and by referencing a different image in my values.yaml that when logging in as a user in the hub UI, it would spin up the image I newly configured and referenced, so long as I had upgraded the deployment before hand with `helm upgrade`

#### Actual behaviour

Nothing seems to change at all. No secret is added per https://z2jh.jupyter.org/en/latest/resources/reference.html#imagepullsecret

And the repo I reference in my singleuser.image block has no effect on the configuration files provisioned 

### How to reproduce

1. Add metadata to `imagePullSecret` correlated to a private docker registry, set `imagePullSecret.create` to `true`
2. Change `singleuser.image.name`, `singleuser.image.tag`, `singleuser.image.pullPolicy` to values correlated to your desired image (which should already be present in the above registry)
3. Upgrade the helm deployment
4. Attempt to log in & assess the image used by `continuous-image-puller`
5. (optional) check the `hub` Secret, or the DaemonSet manifest for `continuous-image-puller` to see that your changes have not taken any effect
6. (optional) see that no Secret was generated even though you have filled out `imagePullSecret`

### Your personal set up

 - OS:
 Kubernetes
 - Version(s):
v1.20.15

zero-to-jupyterhub

<details><summary>Full environment</summary>
Just using your helm chart with a custom yaml on Kubernetes 1.20.15 with Argo attached to a git repo, the only changes I have made to the values/config are described herein.

</details>

<details><summary>Configuration</summary>

default `jupyterhub_config.py` in the helm chart

</details>

<details><summary>Logs</summary>

Loading /usr/local/etc/jupyterhub/secret/values.yaml 
No config at /usr/local/etc/jupyterhub/existing-secret/values.yaml 
[I 2023-01-24 13:17:34.236 JupyterHub app:2775] Running JupyterHub version 3.0.0 
[I 2023-01-24 13:17:34.236 JupyterHub app:2805] Using Authenticator: jupyterhub.auth.DummyAuthenticator-3.0.0 
[I 2023-01-24 13:17:34.236 JupyterHub app:2805] Using Spawner: kubespawner.spawner.KubeSpawner-4.2.0 
[I 2023-01-24 13:17:34.237 JupyterHub app:2805] Using Proxy: jupyterhub.proxy.ConfigurableHTTPProxy-3.0.0 
[I 2023-01-24 13:17:34.254 alembic.runtime.migration migration:204] Context impl SQLiteImpl. 
[I 2023-01-24 13:17:34.254 alembic.runtime.migration migration:207] Will assume non-transactional DDL. 
[I 2023-01-24 13:17:34.261 alembic.runtime.migration migration:618] Running stamp_revision  -> 651f5419b74d 
[I 2023-01-24 13:17:34.273 alembic.runtime.migration migration:204] Context impl SQLiteImpl. 
[I 2023-01-24 13:17:34.273 alembic.runtime.migration migration:207] Will assume non-transactional DDL. 
[I 2023-01-24 13:17:34.400 JupyterHub roles:173] Role jupyterhub-idle-culler added to database 
[I 2023-01-24 13:17:34.405 JupyterHub app:1934] Not using allowed_users. Any authenticated user will be allowed. 
[I 2023-01-24 13:17:34.454 JupyterHub app:2844] Initialized 0 spawners in 0.002 seconds 
[I 2023-01-24 13:17:34.456 JupyterHub app:3057] Not starting proxy 
[W 2023-01-24 13:17:35.498 JupyterHub proxy:903] api_request to the proxy failed with status code 599, retrying... 
[W 2023-01-24 13:17:36.714 JupyterHub proxy:903] api_request to the proxy failed with status code 599, retrying... 
[I 2023-01-24 13:17:37.933 JupyterHub app:3093] Hub API listening on http://:8081/hub/ 
[I 2023-01-24 13:17:37.933 JupyterHub app:3095] Private Hub API connect url http://hub:8081/hub/ 
[I 2023-01-24 13:17:37.933 JupyterHub app:3104] Starting managed service jupyterhub-idle-culler 
[I 2023-01-24 13:17:37.933 JupyterHub service:385] Starting service 'jupyterhub-idle-culler': ['python3', '-m', 'jupyterhub_idle_culler', '--url=http://localhost:8081/hub/api', '--timeout=3600', '--cull-every=600', '--concurrency=10'] 
[I 2023-01-24 13:17:37.935 JupyterHub service:133] Spawning python3 -m jupyterhub_idle_culler --url=http://localhost:8081/hub/api --timeout=3600 --cull-every=600 --concurrency=10 
[I 2023-01-24 13:17:37.941 JupyterHub proxy:480] Adding route for Hub: / => http://hub:8081 
[I 2023-01-24 13:17:37.943 JupyterHub app:3162] JupyterHub is now running, internal Hub API at http://hub:8081/hub/ 
[I 2023-01-24 13:17:38.054 JupyterHub log:186] 200 GET /hub/api/ (jupyterhub-idle-culler@127.0.0.1) 11.22ms 
[I 2023-01-24 13:17:38.062 JupyterHub log:186] 200 GET /hub/api/users?state=[secret] (jupyterhub-idle-culler@127.0.0.1) 7.21ms 
[I 2023-01-24 13:17:53.674 JupyterHub log:186] 302 GET / -> /hub/ (@165.237.152.143) 0.71ms 
[W 2023-01-24 13:17:53.730 JupyterHub base:387] Invalid or expired cookie token 
[I 2023-01-24 13:17:53.731 JupyterHub log:186] 302 GET /hub/ -> /hub/login?next=%2Fhub%2F (@165.237.152.143) 1.04ms 
[I 2023-01-24 13:17:53.811 JupyterHub log:186] 200 GET /hub/login?next=%2Fhub%2F (@165.237.152.143) 24.25ms 
[I 2023-01-24 13:18:00.196 JupyterHub roles:238] Adding role user for User: dylan 
[I 2023-01-24 13:18:00.214 JupyterHub base:810] User logged in: dylan 
[I 2023-01-24 13:18:00.214 JupyterHub log:186] 302 POST /hub/login?next=%2Fhub%2F -> /hub/ (dylan@165.237.152.143) 27.35ms 
[I 2023-01-24 13:18:00.295 JupyterHub log:186] 302 GET /hub/ -> /hub/spawn (dylan@165.237.152.143) 15.97ms 
[I 2023-01-24 13:18:00.310 JupyterHub reflector:274] watching for pods with label selector='component=singleuser-server' in namespace argo-spark 
[I 2023-01-24 13:18:00.343 JupyterHub reflector:274] watching for events with field selector='involvedObject.kind=Pod' in namespace argo-spark 
[I 2023-01-24 13:18:00.375 JupyterHub provider:651] Creating oauth client jupyterhub-user-dylan 
[I 2023-01-24 13:18:00.396 JupyterHub spawner:2509] Attempting to create pvc claim-dylan, with timeout 3 
[I 2023-01-24 13:18:00.399 JupyterHub log:186] 302 GET /hub/spawn -> /hub/spawn-pending/dylan (dylan@165.237.152.143) 41.61ms 
[I 2023-01-24 13:18:00.470 JupyterHub pages:394] dylan is pending spawn 
[I 2023-01-24 13:18:00.473 JupyterHub log:186] 200 GET /hub/spawn-pending/dylan (dylan@165.237.152.143) 5.59ms 
[I 2023-01-24 13:18:00.473 JupyterHub spawner:2525] PVC claim-dylan already exists, so did not create new pvc. 
[I 2023-01-24 13:18:00.478 JupyterHub spawner:2469] Attempting to create pod jupyter-dylan, with timeout 3 
[W 2023-01-24 13:18:00.559 JupyterHub base:89] Blocking Cross Origin API request.  Referer: https://jupyterhub.wst.k8s.qa.infra.spctrm.net/hub/spawn-pending/dylan, Host: jupyterhub.wst.k8s.qa.infra.spctrm.net, Host URL: http://jupyterhub.wst.k8s.qa.infra.spctrm.net/hub/ 
[W 2023-01-24 13:18:00.559 JupyterHub scopes:804] Not authorizing access to /hub/api/users/dylan/server/progress. Requires any of [read:servers], not derived from scopes [] 
[W 2023-01-24 13:18:00.559 JupyterHub web:1796] 403 GET /hub/api/users/dylan/server/progress (165.237.152.143): Action is not authorized with current scopes; requires any of [read:servers] 
[W 2023-01-24 13:18:00.560 JupyterHub log:186] 403 GET /hub/api/users/dylan/server/progress (@165.237.152.143) 2.38ms 
[I 2023-01-24 13:18:04.248 JupyterHub log:186] 200 GET /hub/api (@100.50.10.174) 0.79ms 
[I 2023-01-24 13:18:04.273 JupyterHub log:186] 200 POST /hub/api/users/dylan/activity (dylan@100.50.10.174) 15.94ms 
[I 2023-01-24 13:18:05.346 JupyterHub base:963] User dylan took 4.987 seconds to start 
[I 2023-01-24 13:18:05.347 JupyterHub proxy:333] Adding user dylan to proxy /user/dylan/ => http://100.50.10.174:8888 
[I 2023-01-24 13:18:11.246 JupyterHub login:44] User logged out: dylan 
[I 2023-01-24 13:18:11.249 JupyterHub log:186] 302 GET /hub/logout -> /hub/login (@165.237.152.143) 5.20ms 
[I 2023-01-24 13:18:11.308 JupyterHub log:186] 200 GET /hub/login (@165.237.152.143) 1.41ms 
[W 2023-01-24 13:18:35.337 JupyterHub base:1127] User dylan server stopped, with exit code: 1 
[I 2023-01-24 13:18:35.337 JupyterHub proxy:359] Removing user dylan from proxy (/user/dylan/) 
[I 2023-01-24 13:27:38.150 JupyterHub log:186] 200 GET /hub/api/ (jupyterhub-idle-culler@127.0.0.1) 14.56ms 
[I 2023-01-24 13:27:38.157 JupyterHub log:186] 200 GET /hub/api/users?state=[secret] (jupyterhub-idle-culler@127.0.0.1) 5.15ms 
[I 2023-01-24 13:37:38.152 JupyterHub log:186] 200 GET /hub/api/ (jupyterhub-idle-culler@127.0.0.1) 15.76ms 
[I 2023-01-24 13:37:38.158 JupyterHub log:186] 200 GET /hub/api/users?state=[secret] (jupyterhub-idle-culler@127.0.0.1) 5.18ms 
[I 2023-01-24 13:47:38.137 JupyterHub log:186] 200 GET /hub/api/ (jupyterhub-idle-culler@127.0.0.1) 15.53ms 
[I 2023-01-24 13:47:38.144 JupyterHub log:186] 200 GET /hub/api/users?state=[secret] (jupyterhub-idle-culler@127.0.0.1) 5.49ms 
[I 2023-01-24 13:57:38.104 JupyterHub log:186] 200 GET /hub/api/ (jupyterhub-idle-culler@127.0.0.1) 15.07ms 
[I 2023-01-24 13:57:38.111 JupyterHub log:186] 200 GET /hub/api/users?state=[secret] (jupyterhub-idle-culler@127.0.0.1) 5.44ms 
[I 2023-01-24 14:07:38.135 JupyterHub log:186] 200 GET /hub/api/ (jupyterhub-idle-culler@127.0.0.1) 14.96ms 
[I 2023-01-24 14:07:38.142 JupyterHub log:186] 200 GET /hub/api/users?state=[secret] (jupyterhub-idle-culler@127.0.0.1) 5.07ms 
[I 2023-01-24 14:10:48.918 JupyterHub log:186] 302 GET / -> /hub/ (@165.237.152.143) 0.72ms 
[I 2023-01-24 14:10:48.981 JupyterHub log:186] 302 GET /hub/ -> /hub/login?next=%2Fhub%2F (@165.237.152.143) 0.61ms 
[I 2023-01-24 14:10:49.052 JupyterHub log:186] 200 GET /hub/login?next=%2Fhub%2F (@165.237.152.143) 1.62ms 
[I 2023-01-24 14:10:52.859 JupyterHub base:810] User logged in: dylan 
[I 2023-01-24 14:10:52.859 JupyterHub log:186] 302 POST /hub/login?next=%2Fhub%2F -> /hub/ (dylan@165.237.152.143) 15.13ms 
[I 2023-01-24 14:10:52.929 JupyterHub log:186] 302 GET /hub/ -> /hub/spawn (dylan@165.237.152.143) 10.43ms 
[I 2023-01-24 14:10:53.004 JupyterHub provider:651] Creating oauth client jupyterhub-user-dylan 
[I 2023-01-24 14:10:53.024 JupyterHub spawner:2509] Attempting to create pvc claim-dylan, with timeout 3 
[I 2023-01-24 14:10:53.026 JupyterHub log:186] 302 GET /hub/spawn -> /hub/spawn-pending/dylan (dylan@165.237.152.143) 37.26ms 
[I 2023-01-24 14:10:53.069 JupyterHub spawner:2525] PVC claim-dylan already exists, so did not create new pvc. 
[I 2023-01-24 14:10:53.074 JupyterHub spawner:2469] Attempting to create pod jupyter-dylan, with timeout 3 
[I 2023-01-24 14:10:53.114 JupyterHub pages:394] dylan is pending spawn 
[I 2023-01-24 14:10:53.115 JupyterHub log:186] 200 GET /hub/spawn-pending/dylan (dylan@165.237.152.143) 3.70ms 
[W 2023-01-24 14:10:53.187 JupyterHub base:89] Blocking Cross Origin API request.  Referer: https://jupyterhub.wst.k8s.qa.infra.spctrm.net/hub/spawn-pending/dylan, Host: jupyterhub.wst.k8s.qa.infra.spctrm.net, Host URL: http://jupyterhub.wst.k8s.qa.infra.spctrm.net/hub/ 
[W 2023-01-24 14:10:53.187 JupyterHub scopes:804] Not authorizing access to /hub/api/users/dylan/server/progress. Requires any of [read:servers], not derived from scopes [] 
[W 2023-01-24 14:10:53.187 JupyterHub web:1796] 403 GET /hub/api/users/dylan/server/progress (165.237.152.143): Action is not authorized with current scopes; requires any of [read:servers] 
[W 2023-01-24 14:10:53.188 JupyterHub log:186] 403 GET /hub/api/users/dylan/server/progress (@165.237.152.143) 1.68ms 
[I 2023-01-24 14:10:53.922 JupyterHub pages:394] dylan is pending spawn 
[I 2023-01-24 14:10:53.923 JupyterHub log:186] 200 GET /hub/spawn-pending/dylan (dylan@165.237.152.143) 2.66ms 
[W 2023-01-24 14:10:53.992 JupyterHub base:89] Blocking Cross Origin API request.  Referer: https://jupyterhub.wst.k8s.qa.infra.spctrm.net/hub/spawn-pending/dylan, Host: jupyterhub.wst.k8s.qa.infra.spctrm.net, Host URL: http://jupyterhub.wst.k8s.qa.infra.spctrm.net/hub/ 
[W 2023-01-24 14:10:53.992 JupyterHub scopes:804] Not authorizing access to /hub/api/users/dylan/server/progress. Requires any of [read:servers], not derived from scopes [] 
[W 2023-01-24 14:10:53.992 JupyterHub web:1796] 403 GET /hub/api/users/dylan/server/progress (165.237.152.143): Action is not authorized with current scopes; requires any of [read:servers] 
[W 2023-01-24 14:10:53.993 JupyterHub log:186] 403 GET /hub/api/users/dylan/server/progress (@165.237.152.143) 1.79ms 
[I 2023-01-24 14:10:55.521 JupyterHub pages:394] dylan is pending spawn 
[I 2023-01-24 14:10:55.522 JupyterHub log:186] 200 GET /hub/spawn-pending/dylan (dylan@165.237.152.143) 2.60ms 
[W 2023-01-24 14:10:55.593 JupyterHub base:89] Blocking Cross Origin API request.  Referer: https://jupyterhub.wst.k8s.qa.infra.spctrm.net/hub/spawn-pending/dylan, Host: jupyterhub.wst.k8s.qa.infra.spctrm.net, Host URL: http://jupyterhub.wst.k8s.qa.infra.spctrm.net/hub/ 
[W 2023-01-24 14:10:55.593 JupyterHub scopes:804] Not authorizing access to /hub/api/users/dylan/server/progress. Requires any of [read:servers], not derived from scopes [] 
[W 2023-01-24 14:10:55.593 JupyterHub web:1796] 403 GET /hub/api/users/dylan/server/progress (165.237.152.143): Action is not authorized with current scopes; requires any of [read:servers] 
[W 2023-01-24 14:10:55.593 JupyterHub log:186] 403 GET /hub/api/users/dylan/server/progress (@165.237.152.143) 1.99ms 
[I 2023-01-24 14:10:55.983 JupyterHub log:186] 200 GET /hub/api (@100.50.10.175) 0.72ms 
[I 2023-01-24 14:10:56.008 JupyterHub log:186] 200 POST /hub/api/users/dylan/activity (dylan@100.50.10.175) 15.41ms 
[I 2023-01-24 14:10:56.295 JupyterHub pages:394] dylan is pending spawn 
[I 2023-01-24 14:10:56.295 JupyterHub log:186] 200 GET /hub/spawn-pending/dylan (dylan@165.237.152.143) 3.16ms 
[W 2023-01-24 14:10:56.367 JupyterHub base:89] Blocking Cross Origin API request.  Referer: https://jupyterhub.wst.k8s.qa.infra.spctrm.net/hub/spawn-pending/dylan, Host: jupyterhub.wst.k8s.qa.infra.spctrm.net, Host URL: http://jupyterhub.wst.k8s.qa.infra.spctrm.net/hub/ 
[W 2023-01-24 14:10:56.368 JupyterHub scopes:804] Not authorizing access to /hub/api/users/dylan/server/progress. Requires any of [read:servers], not derived from scopes [] 
[W 2023-01-24 14:10:56.368 JupyterHub web:1796] 403 GET /hub/api/users/dylan/server/progress (165.237.152.143): Action is not authorized with current scopes; requires any of [read:servers] 
[W 2023-01-24 14:10:56.368 JupyterHub log:186] 403 GET /hub/api/users/dylan/server/progress (@165.237.152.143) 1.62ms 
[I 2023-01-24 14:10:57.079 JupyterHub pages:394] dylan is pending spawn 
[I 2023-01-24 14:10:57.080 JupyterHub log:186] 200 GET /hub/spawn-pending/dylan (dylan@165.237.152.143) 2.80ms 
[W 2023-01-24 14:10:57.152 JupyterHub base:89] Blocking Cross Origin API request.  Referer: https://jupyterhub.wst.k8s.qa.infra.spctrm.net/hub/spawn-pending/dylan, Host: jupyterhub.wst.k8s.qa.infra.spctrm.net, Host URL: http://jupyterhub.wst.k8s.qa.infra.spctrm.net/hub/ 
[W 2023-01-24 14:10:57.153 JupyterHub scopes:804] Not authorizing access to /hub/api/users/dylan/server/progress. Requires any of [read:servers], not derived from scopes [] 
[W 2023-01-24 14:10:57.153 JupyterHub web:1796] 403 GET /hub/api/users/dylan/server/progress (165.237.152.143): Action is not authorized with current scopes; requires any of [read:servers] 
[W 2023-01-24 14:10:57.153 JupyterHub log:186] 403 GET /hub/api/users/dylan/server/progress (@165.237.152.143) 2.06ms 
[I 2023-01-24 14:10:58.713 JupyterHub pages:394] dylan is pending spawn 
[I 2023-01-24 14:10:58.715 JupyterHub log:186] 200 GET /hub/spawn-pending/dylan (dylan@165.237.152.143) 2.94ms 
[W 2023-01-24 14:10:58.782 JupyterHub base:89] Blocking Cross Origin API request.  Referer: https://jupyterhub.wst.k8s.qa.infra.spctrm.net/hub/spawn-pending/dylan, Host: jupyterhub.wst.k8s.qa.infra.spctrm.net, Host URL: http://jupyterhub.wst.k8s.qa.infra.spctrm.net/hub/ 
[W 2023-01-24 14:10:58.782 JupyterHub scopes:804] Not authorizing access to /hub/api/users/dylan/server/progress. Requires any of [read:servers], not derived from scopes [] 
[W 2023-01-24 14:10:58.782 JupyterHub web:1796] 403 GET /hub/api/users/dylan/server/progress (165.237.152.143): Action is not authorized with current scopes; requires any of [read:servers] 
[W 2023-01-24 14:10:58.783 JupyterHub log:186] 403 GET /hub/api/users/dylan/server/progress (@165.237.152.143) 1.87ms 
[I 2023-01-24 14:10:59.997 JupyterHub base:963] User dylan took 7.005 seconds to start 
[I 2023-01-24 14:10:59.997 JupyterHub proxy:333] Adding user dylan to proxy /user/dylan/ => http://100.50.10.175:8888 
[I 2023-01-24 14:11:02.261 JupyterHub log:186] 302 GET /hub/spawn-pending/dylan -> /user/dylan/ (dylan@165.237.152.143) 3.22ms 
[W 2023-01-24 14:11:02.464 JupyterHub auth:298] Service Server at /user/dylan/ requested scopes access:servers!user=dylan,read:users:name!user,read:users:groups!user,access:servers!server=dylan/ for user dylan, granting only read:users:name!user,read:users:groups!user,access:servers!server=dylan/. 
[I 2023-01-24 14:11:02.474 JupyterHub log:186] 302 GET /hub/api/oauth2/authorize?client_id=jupyterhub-user-dylan&redirect_uri=%2Fuser%2Fdylan%2Foauth_callback&response_type=code&state=[secret] -> /user/dylan/oauth_callback?code=[secret]&state=[secret] (dylan@165.237.152.143) 15.15ms 
[I 2023-01-24 14:11:02.564 JupyterHub log:186] 200 POST /hub/api/oauth2/token (dylan@100.50.10.175) 23.08ms 
[I 2023-01-24 14:11:02.574 JupyterHub log:186] 200 GET /hub/api/user (dylan@100.50.10.175) 7.97ms 
[I 2023-01-24 14:15:34.469 JupyterHub log:186] 200 POST /hub/api/users/dylan/activity (dylan@100.50.10.175) 18.61ms 
[I 2023-01-24 14:16:06.970 JupyterHub log:186] 200 GET /hub/api/user (dylan@100.50.10.175) 10.25ms 
[I 2023-01-24 14:17:38.139 JupyterHub log:186] 200 GET /hub/api/ (jupyterhub-idle-culler@127.0.0.1) 7.03ms 
[I 2023-01-24 14:17:38.144 JupyterHub log:186] 200 GET /hub/api/users?state=[secret] (jupyterhub-idle-culler@127.0.0.1) 3.79ms 
[I 2023-01-24 14:20:29.666 JupyterHub log:186] 200 POST /hub/api/users/dylan/activity (dylan@100.50.10.175) 17.86ms 
[I 2023-01-24 14:22:32.645 JupyterHub log:186] 200 GET /hub/api/user (dylan@100.50.10.175) 9.94ms 
[I 2023-01-24 14:25:07.233 JupyterHub log:186] 200 POST /hub/api/users/dylan/activity (dylan@100.50.10.175) 10.37ms 
[I 2023-01-24 14:27:38.132 JupyterHub log:186] 200 GET /hub/api/ (jupyterhub-idle-culler@127.0.0.1) 8.14ms 
[I 2023-01-24 14:27:38.137 JupyterHub log:186] 200 GET /hub/api/users?state=[secret] (jupyterhub-idle-culler@127.0.0.1) 3.60ms 
[I 2023-01-24 14:30:01.078 JupyterHub log:186] 200 POST /hub/api/users/dylan/activity (dylan@100.50.10.175) 10.22ms 
[I 2023-01-24 14:35:15.210 JupyterHub log:186] 200 POST /hub/api/users/dylan/activity (dylan@100.50.10.175) 11.17ms 
[I 2023-01-24 14:37:38.144 JupyterHub log:186] 200 GET /hub/api/ (jupyterhub-idle-culler@127.0.0.1) 7.47ms 
[I 2023-01-24 14:37:38.148 JupyterHub log:186] 200 GET /hub/api/users?state=[secret] (jupyterhub-idle-culler@127.0.0.1) 3.48ms 
[I 2023-01-24 14:40:37.487 JupyterHub log:186] 200 POST /hub/api/users/dylan/activity (dylan@100.50.10.175) 13.01ms 
[I 2023-01-24 14:46:03.780 JupyterHub log:186] 200 POST /hub/api/users/dylan/activity (dylan@100.50.10.175) 11.54ms 
[I 2023-01-24 14:47:38.119 JupyterHub log:186] 200 GET /hub/api/ (jupyterhub-idle-culler@127.0.0.1) 8.63ms 
[I 2023-01-24 14:47:38.125 JupyterHub log:186] 200 GET /hub/api/users?state=[secret] (jupyterhub-idle-culler@127.0.0.1) 4.03ms 
[I 2023-01-24 14:51:22.296 JupyterHub log:186] 200 POST /hub/api/users/dylan/activity (dylan@100.50.10.175) 10.63ms 
[I 2023-01-24 14:56:17.262 JupyterHub log:186] 200 POST /hub/api/users/dylan/activity (dylan@100.50.10.175) 10.63ms 
[I 2023-01-24 14:57:38.143 JupyterHub log:186] 200 GET /hub/api/ (jupyterhub-idle-culler@127.0.0.1) 7.69ms 
[I 2023-01-24 14:57:38.148 JupyterHub log:186] 200 GET /hub/api/users?state=[secret] (jupyterhub-idle-culler@127.0.0.1) 3.77ms 
[I 2023-01-24 14:57:49.688 JupyterHub log:186] 200 GET /hub/api/user (dylan@100.50.10.175) 8.61ms 
[I 2023-01-24 15:01:04.845 JupyterHub log:186] 200 POST /hub/api/users/dylan/activity (dylan@100.50.10.175) 12.01ms 
[I 2023-01-24 15:06:10.496 JupyterHub log:186] 200 POST /hub/api/users/dylan/activity (dylan@100.50.10.175) 10.56ms 
[I 2023-01-24 15:07:38.123 JupyterHub log:186] 200 GET /hub/api/ (jupyterhub-idle-culler@127.0.0.1) 7.73ms 
[I 2023-01-24 15:07:38.128 JupyterHub log:186] 200 GET /hub/api/users?state=[secret] (jupyterhub-idle-culler@127.0.0.1) 3.78ms 
[I 2023-01-24 15:11:29.806 JupyterHub log:186] 200 POST /hub/api/users/dylan/activity (dylan@100.50.10.175) 10.65ms 
[I 2023-01-24 15:16:34.911 JupyterHub log:186] 200 POST /hub/api/users/dylan/activity (dylan@100.50.10.175) 11.93ms 
[I 2023-01-24 15:17:38.145 JupyterHub log:186] 200 GET /hub/api/ (jupyterhub-idle-culler@127.0.0.1) 8.60ms 
[I 2023-01-24 15:17:38.150 JupyterHub log:186] 200 GET /hub/api/users?state=[secret] (jupyterhub-idle-culler@127.0.0.1) 3.82ms 
[W 2023-01-24 15:21:29.994 JupyterHub base:1127] User dylan server stopped, with exit code: 1 
[I 2023-01-24 15:21:29.994 JupyterHub proxy:359] Removing user dylan from proxy (/user/dylan/) 

</details>

**Comment by consideRatio** [comment]
It should be `singleuser`, and you should preferably have been erroring because `singleUser` isn't part of the schema. Maybe you have git cloned this repo and use the chart directly? Then you end up with default values that aren't updated properly and without schema validation that would have caught for example `singleUser` to be an unknown (because it has to be `singleuser`).

```yaml
singleuser:
  image:
    name: <...>
```

**Comment by DylanAlloy** [comment]
Pardon, it is 'singleuser'.

**Comment by DylanAlloy** [comment]
> I couldn't follow what you meant by pointing to a Chart.yaml and values.yaml file. Did you point to the content of this source code directly, or did you point to this helm chart in its published form at the helm chart repository https://jupyterhub.github.io/helm-chart/index.yaml that links to a .tgz file that has a Chart.yaml, values.yaml, and values.schema.json?

For the sake of this troubleshooting effort, I did this basically. https://z2jh.jupyter.org/en/latest/jupyterhub/customizing/extending-jupyterhub.html#applying-configuration-changes

I do not want to belabor the point by explaining what Argo's role is in an k8s deployment, suffice to say I am using the normal helm and merely giving a custom configuration which is deployed to a k8s cluster.

**Comment by manics** [comment]
- Is the singleuser image correctly updated if you use a public image that doesn't require secrets?
- Are you able to reproduce the bug when running Helm directly, without ArgoCD?

**Comment by DylanAlloy** [comment]
1. No
2. Yes.

re: #2, it appears helm is being used in the chart deployment itself as a method to retrieve the single-user-sample image. This makes it opaque to a CI/CD tool like Argo _if the Chart is being proxied by one's own repository._ 

I believe my workaround is to clone the Chart itself and maintain a specific version in my own repository which will result in the behavior being as expected. 

I don't know how much this comes off as an 'edge case' and hopefully you don't have too many issues with people who have similarly convoluted pipelines but suggestions we floated around on my team were: 

- k8s jobs to do the user hub environment spin up
- passing values as a key/value as one might with an .xml or config doc with a deployment i.e.
```
key:
    values.yaml: | 
            <content here>
```

Obviously though this is not your Chart's problem, just a philosophy on how to expose this configuration more for situations where it's not Helm at the cli.
