### ISSUE TITLE
New straightforward way to manage notebooks on Kubernetes 

### ISSUE THREAD

**Issue by machine424** [jupyterhub/zero-to-jupyterhub-k8s#3008]
Hello,

I've already posted on Jupyter discourse https://discourse.jupyter.org/t/a-new-and-simple-way-to-manage-notebooks-on-kubernetes/17655, but I didn't get the feedback I was expecting :)

I'd like to draw your attention to [notebook-on-kube](https://github.com/machine424/notebook-on-kube), a new tool I open sourced that provides a new way of managing notebooks with the bare minimum of extra/new code, re-using existing Kubernetes features (RBAC, Helm, ingress-nginx etc.)

I talk more about my approach in the README https://github.com/machine424/notebook-on-kube#how-and-why. 

Give it a try and let me know what you think about it.

**Comment by machine424** [comment]
Hi @manics 

Would you mind explaining why? Have I done something wrong?

**Comment by manics** [comment]
Hi! We use issues for discussing bugs and proposed features. The work you've done is definitely interesting, but Discourse is the right place to discuss and promote it.

**Comment by machine424** [comment]
We can think of it as a big feature, jocking :)

I was honest, I did that to get feedback, I'll try another time on Discourse in the future.

(Thanks for the explanation and I'm sorry again, I read the Code of Conduct, and there was nothing about that, so I gave it a try)
