### ISSUE TITLE
Binderhub not using prepulled base images in build pod

### ISSUE THREAD

**Issue by jrich100** [jupyterhub/zero-to-jupyterhub-k8s#3009]
### Bug description

Binderhub is fetching base images when building the user image even if the base image was prepulled to the build node.

#### Expected behaviour

The build pod should use the prepulled image on the node instead of fetching it.

#### Actual behaviour

The build pod fetches the base image which takes several minutes.

### How to reproduce

1. Add a base image to `prePuller.extraImages` with `prepuller.hook.enabled` set to true.
2. deploy helm chart
3. verify that the image exists on build node(s): `kubectl get nodes -n <NAMESPACE> -o yaml`
4. Initiate a new build that uses the above prepulled image as the base image
5. The BinderHub build logs show "Fetching base image..." for several minutes

### Your personal set up

Using  zero-to-jupyterhub for k8s, deployed via helm.

 - OS:
ubuntu 20.04

 - Version(s):
BinderHub Chart Version: 0.2.0-n499.h81660eb
Jupyterhub Chart Version: 1.1.3-n329.he588ec17

I can provide more information if needed

**Comment by manics** [comment]
I think this is expected, in general the builder is independent of the host container engine.

If you still think there's a related bug please could you open an issue on the BinderHub repo with _full instructions_ to reproduce? This includes your k8s setup, your BindeHub config, and example repositories which exhibit the problem. Thanks!
