### ISSUE TITLE
Issue template that asks people to paste `config.yaml`?

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/zero-to-jupyterhub-k8s#301]
A lot of the issues people run into invariably end with us asking them to paste the contents of their `config.yaml` file. What if we added a short issue template that said something like "if your JupyterHub isn't working properly, please include the contents of your `config.yaml` file in your issue (don't forget to remove the SSL keys!)"

**Comment by yuvipanda** [comment]
+1, although I'm unsure what you mean by SSL Keys?

**Comment by choldgraf** [comment]
I just meant the output of `openssl etc etc`

**Comment by choldgraf** [comment]
if that's not a problem then I won't mention it tho
