### ISSUE TITLE
proxy blocks requests to other services on the same domain inside the lab pod

### ISSUE THREAD

**Issue by maltegrosse** [jupyterhub/zero-to-jupyterhub-k8s#3023]
### Bug description

When running Jupyterhub on a k8s Cluster, e.g. `hub.test.example.com`, other services hosted under the same subdomain, e.g. `share.test.example.com` are not reachable within the notebook pod.  Curl returns `curl: (7) Failed to connect to share.test.example.com port 443: Connection refused`. By having a closer look, the dns got the correct ip resolved.
running the same command in the hub pod or proxy pod directly works without any issues. I assume it has something to do with configurable-http-proxy (chp). By looking into the ingress proxy access logs (traefik) and proxy pod no requests appear.

Looking at [chp settings](https://github.com/jupyterhub/configurable-http-proxy#host-based-routing), host based routing is possible. It could help but I was not sure how to inject these parameters into the helm chart values and if this causes [additional issues regarding ssl termination ](https://github.com/jupyterhub/configurable-http-proxy/pull/24#issuecomment-95314296)

#### Expected behaviour

The chp should only handle certain requests which are related to the exact hub subdomain.

#### Actual behaviour

The chp handles all requests which causes a "connection refused"

### How to reproduce

1. deploy jupyterhub on a sub subdomain `hub.test.example.com`
2. deploy a second service on another sub subdomain `share.test.example.com`  (e.g. simple nginx)
3. try to curl the https endpoint inside the lab pod (or by using the lab terminal via browser ui)

### Your personal set up

Kubernetes (k0s) 1.25.4, Traefik Ingress 2.9.6

OS:
Ubuntu 22.04
Version(s):
jupyterhub 3.0.0
python: 3.9.14
latest stable Jupyterhub installed via Helmchart

**Comment by manics** [comment]
Hi. CHP only listens (via k8s) on an IP. the IP is linked to the domain by a DNS record you configure, there's no way for the proxy to listen on any other address.

Are you running your second service in the same namespace? Perhaps this is blocked due to network policies?
https://z2jh.jupyter.org/en/stable/administrator/security.html#kubernetes-network-policies

If you need more help please use the community forum https://discourse.jupyter.org/

**Comment by maltegrosse** [comment]
@manics  thank you about the hints regarding the network policies.
`singleuser.networkPolicy.egressAllowRules.privateIPs=false` did the trick.

all other services as described above are in other namespaces.

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/6d3c13984d78791f6c6980a70ddf8cf0648cf723/jupyterhub/templates/_helpers-netpol.tpl#L65

especially the 10.x egress blocks all traffic to any pod in the cluster. As the SingleUser container has only an internal ip, other services within this cluster cant be reached....

I am not sure how to set the network policies properly as its out of my scope..... perhaps adding some labels to the ingress proxy....
