### ISSUE TITLE
hub image's pip packages are installed as root making subsequent installs require root

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#3039]
In https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/3003 @pnasrat concluded that one may need to be root to do `pip` install in a Dockerfile with `FROM jupyterhub/k8s-hub:2.0.0`.

I'm not sure, but I'm thinking that isn't desired.

**Comment by manics** [comment]
Sounds fine to me. It's a production application that shouldn't need to modify itself, so this improves security.

**Comment by consideRatio** [comment]
:+1: deal makes sense to me!
