### ISSUE TITLE
`admin: users` catch-22

### ISSUE THREAD

**Issue by cmoscardi** [jupyterhub/zero-to-jupyterhub-k8s#305]
Trying to pass in this config setup:
```
auth:
  admin:
    access: true
    users:
      - christian
      - robert
```
causes a k8s/helm deployment error.

Here's the specific error:
```
Error: UPGRADE FAILED: render error in "jupyterhub/templates/hub/deployment.yaml": template: jupyterhub/templates/hub/deployment.yaml:19:32: executing
 "jupyterhub/templates/hub/deployment.yaml" at <include (print $.Tem...>: error calling include: template: jupyterhub/templates/hub/configmap.yaml:157
:37: executing "jupyterhub/templates/hub/configmap.yaml" at <4>: wrong type for value; expected string; got []interface {}
```

Then, trying to pass a singleton string causes the hub to fail with a `traitlet` validation error - `admin_users` needs to be a list.

I believe the problem is here, though I'm not clear enough to immediately understand the specific syntactical bug that's probably causing this. https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/jupyterhub/templates/hub/configmap.yaml#L156

Last, a workaround I used
```
hub:
  extraConfig:
    c.Authenticator.admin_users = {"christian", "robert"}
```

**Comment by cmoscardi** [comment]
My rudimentary git skills indicate this may be the source of the bug? Is my syntax bad?

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/commit/5bc6cfaf5b203dc03b28851ccc04ce55ae18a7f1#diff-96a1791deadeccb98a6f334d195c73a7

**Comment by yuvipanda** [comment]
@cmoscardi good catch! https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/307 should fix it!

Once v0.5 is out the door I think the next big task is to just add lots of tests...
