### ISSUE TITLE
Multiple hub server,Server not running

### ISSUE THREAD

**Issue by huleiyu** [jupyterhub/zero-to-jupyterhub-k8s#3053]
when I tried to use Multiple hub server, the server is not running ,it works well when i use only 1 replicas.
how can i add hub service from 1 to 2 or more ? 
the page appears like this:
Server not running
Your server is not running. Would you like to start it?

**Comment by manics** [comment]
This isn't currently supported, see https://github.com/jupyterhub/jupyterhub/issues/1932 for more information
