### ISSUE TITLE
Not all resources support annotations configuration

### ISSUE THREAD

**Issue by dev-dsp** [jupyterhub/zero-to-jupyterhub-k8s#3054]
### Proposed change
Introduce `annotations` in Hub & CHP Deployment

### Alternative options
Introduce global `extraAnnotations ` for all possible  generated resources

### Who would use this feature?
Would be useful for different k8s management solutions that use annotations for searching resources.

**Comment by manics** [comment]
The hub and proxy already support annotations:
- https://z2jh.jupyter.org/en/stable/resources/reference.html#hub-annotations
- https://z2jh.jupyter.org/en/stable/resources/reference.html#proxy-annotations

What additional functionality do you need?

**Comment by dev-dsp** [comment]
Hi @manics . There are no annotations on Deployments: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/main/jupyterhub/templates/proxy/deployment.yaml#L5

**Comment by manics** [comment]
Thanks for elaborating. Please follow this existing issue https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/2949
