### ISSUE TITLE
Write unit tests with helm template

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/zero-to-jupyterhub-k8s#308]
https://github.com/technosophos/helm-template is a helm plugin that renders kubernetes objects from a helm chart + values files. We can use this to write unit tests that validate that a given YAML values file is actually valid & produces configmap / deployment entries as we want.

**Comment by yuvipanda** [comment]
So for each test, we'd have:

1. an input config.yaml file
2. It'll run through helm template
3. It'll parse the output YAML from helm template and validate that a subset of it does the things we want.

We could also only specifically test individual templates, which might be faster and easier.

**Comment by consideRatio** [comment]
I've added this in #758, but currently only for a single config.yaml file.

**Comment by consideRatio** [comment]
Fixed by https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/844, refactored from #758
