### ISSUE TITLE
Planning release for 3.0.0

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#3091]
Is there something we should get done before cutting 3.0.0 of this chart?

### Required before a release

- Release of jupyterhub 4.0.0: https://github.com/jupyterhub/jupyterhub/issues/4350
- Release of kubespawner 5.0.0: https://github.com/jupyterhub/kubespawner/issues/717
- Release of kubespawner 6.0.0: https://github.com/jupyterhub/kubespawner/issues/732
- Release of nativeauthenticator 1.2.0: https://github.com/jupyterhub/nativeauthenticator/issues/241
- Release of tmpauthenticator 1.0.0 https://github.com/jupyterhub/tmpauthenticator/issues/30
- https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/3092
- https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/3113
- Release of oauthenticator 16.0.0: https://github.com/jupyterhub/oauthenticator/issues/585
- #3192

### Related
- https://github.com/jupyterhub/team-compass/issues/650

**Comment by JunaidChaudry** [comment]
@consideRatio Can you please also get this in the release? https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/3104

**Comment by JunaidChaudry** [comment]
Its a small change, but pretty reasonable (and affecting me ;) )

**Comment by c3-viral-lakhani** [comment]
@consideRatio Any updates on the timeline for releasing the new version?

**Comment by manics** [comment]
@c3-viral-lakhani `3.0.0-beta.3` has been out for several days https://hub.jupyter.org/helm-chart/#development-releases-jupyterhub
