### ISSUE TITLE
Adding support for overriding the default [`KubeSpawner.k8s_api_request_timeout`](https://jupyterhub-kubespawner.readthedocs.io/en/latest/spawner.html#kubespawner.KubeSpawner.k8s_api_request_timeout) config parameter

### ISSUE THREAD

**Issue by JunaidChaudry** [jupyterhub/zero-to-jupyterhub-k8s#3105]
### Bug description

The helm chart currently doesn't provide support for overwriting the default value for [`KubeSpawner.k8s_api_request_timeout`](https://jupyterhub-kubespawner.readthedocs.io/en/latest/spawner.html#kubespawner.KubeSpawner.k8s_api_request_timeout). 

The overwrite is needed in usecases where an end-users cluster takes longer than the default `3` seconds to spin up a new user pod. 

#### Expected behaviour

`singleuser.k8sApiRequestTimeout` should allow enduser to overwrite the default value of `KubeSpawner.k8s_api_request_timeout` for jupyterhub_config

#### Actual behaviour

There is currently no support for overwriting the default k8sapiRequestTimeout for the spawner, so the end-user is stuck with the [default value of `3`](https://github.com/jupyterhub/kubespawner/blob/9f31d48569025b7bf58dd9bcfe77984cf204c562/kubespawner/spawner.py#L271)

**Comment by consideRatio** [comment]
Hey I'm om vacation from mobile, but short feedback.

We can't sustainably maintain adding all config option in z2jh for each respective software component's config option. Therefore, please use "hub.config.KubeSpawner.any_kubespawner_config_here = value" to configure the various kubespawner options.

hub.config accepts all kinds of config options, and doesnt require the helm chart to be updated for each new option.

**Comment by JunaidChaudry** [comment]
that worked. However none of the docs show this. Can we update the docs/values to show that `hub.config.KubeSpawner` is also an option, and can take all the config options? 
If they already exist, can you please point me to them? cz I couldn't find that anywhere. 

Thanks in advance!

**Comment by consideRatio** [comment]
Docs to be resolved by #3104, closing!
