### ISSUE TITLE
Jupyterlab fails to render on Tornado Server 6.3 if Content Security Policy is defined in z2jh kubernetes yaml file

### ISSUE THREAD

**Issue by aadil456** [jupyterhub/zero-to-jupyterhub-k8s#3111]
### Bug description

![image](https://user-images.githubusercontent.com/83044233/236969965-cce1b3ee-0268-4b72-9913-4d1f976e9577.png)

I have deployed z2jh in Microsoft Azure and use OAuth for authentication. I use Jupyterlab as the front end and all of this is displayed as an iframe in another website so I have defined the content security policy in my yaml file which is attached. Recently after I updated my docker image which is basically a copy of the base-notebook image from the Jupyter docker stack, I started getting an internal server error on both my host website and iframe so after some investigation I found that tornado server has been upgraded in the recent image and when I downgraded the tornado web server to 6.1 everything started working fine. I also found out that if i take out the cookie-options from my yaml file and applied the latest yaml file on my cluster, the front end loads fine. I am attaching screenshot of the error and the console log of web browser. 

![image](https://user-images.githubusercontent.com/83044233/236970872-e584d00b-e103-4950-bd5b-82e2146522c8.png)
![image](https://user-images.githubusercontent.com/83044233/236971032-790562f1-7883-46ad-8dac-0951d6294b3b.png)
![image](https://user-images.githubusercontent.com/83044233/236971285-0a5fc9a6-d56e-49ca-8a00-da8d25615d93.png)

This issue does not happen if I downgrade Tornado Server  to v 6.1 in my docker image 

#### Expected behaviour

Jupyterlab loads 

#### Actual behaviour

Internal Server Error

### How to reproduce

Use cookie-options in content security policy and use tornado server 6.3 

### Your personal set up

 - OS:
 
 - Version(s):
 

<details><summary>Full environment</summary>

```
# paste output of `pip freeze` or `conda list` here
```
</details>

<details><summary>Configuration</summary>

```python
# jupyterhub_config.py
```
</details>

<details><summary>Logs</summary>

```
# paste relevant logs here, if any
```
</details>

**Comment by manics** [comment]
This sounds like something you'll need to fix in your JupyterLab container, e.g. by configuring Jupyter-Server. It's not something that Z2JH can manage.
