### ISSUE TITLE
Installation on GKE autopilot fails with hub pod in CrashLoopBackoff

### ISSUE THREAD

**Issue by vizeit** [jupyterhub/zero-to-jupyterhub-k8s#3163]
### Bug description
Installation on GKE Autopilot fails with hub pod in CrashLoopBackoff with the log showing following error

api_request to the proxy failed with status code 599, retrying...

#### Expected behaviour
The installation should complete successfully

### How to reproduce
Try to install on GKE Autopilot

### Your personal set up

 - OS:
 
 - Version(s):
 

<details><summary>Full environment</summary>

```
# paste output of `pip freeze` or `conda list` here
```
</details>

<details><summary>Configuration</summary>

```python
# jupyterhub_config.py
```
</details>

<details><summary>Logs</summary>

```
# paste relevant logs here, if any
```
</details>

**Comment by manics** [comment]
There are a few posts on https://discourse.jupyter.org/ about using GKE, try searching through that forum. If you're still stuck please post on that forum, and include enough information for someone to reproduce your problem from scratch.
