### ISSUE TITLE
Jupyterhub stucks at spawn state on specific users

### ISSUE THREAD

**Issue by agelosnm** [jupyterhub/zero-to-jupyterhub-k8s#3177]
I came with an issue that occurs only on two specific users and it is very weird...

What is happening is that when one tries to spawn a new notebook server the status hangs at the below state:

![image](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/assets/28690845/ac9e6cdf-f13e-4e17-bbc5-3a68a54e6114)

...and eventually breaks

![image](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/assets/28690845/934840d5-6292-4f1c-a739-f761e061cb66)

This though is happening only for the profile with the mentioned Docker image. We have other profiles as well with different Docker images and this not an issue at all. Although other users are able to launch a server using the same image.

**Comment by manics** [comment]
Have a look at the debugging guide https://z2jh.jupyter.org/en/stable/administrator/debug.html

If you need more help please post on https://discourse.jupyter.org/ and include enough information to reproduce youre problem, including full details of your configuration, setup, k8s cluster, and logs. Thanks!
