### ISSUE TITLE
Allow multiple extraConfig

### ISSUE THREAD

**Issue by minrk** [jupyterhub/zero-to-jupyterhub-k8s#320]
Binder relies on `hub.extraConfig` to configure the Spawner. If we want to customize a given Binder *deployment* via `hub.extraConfig`, we have to copy/paste the hub.extraConfig from the binderhub chart and add to it.

It would be handy if extraConfig were something that could be added to without having to copy the previous value. Are dicts the only structure that can do this?

**Comment by yuvipanda** [comment]
Dicts I think are the only structure that can do this. We can and should easily add this to the chart.
