### ISSUE TITLE
User specific pod unable to bound to the user specific PVC 

### ISSUE THREAD

**Issue by yash-ghelani-dsw** [jupyterhub/zero-to-jupyterhub-k8s#3221]
### Bug description

hi, I have k8s setup running on a rhel instance along with helm installed. I wanted to to setup jupyterhub on same. Post installation of jupyterhub with zero to jupyterhub k8s (chart version = 3.0.3), when I try to create a user (with dummy authenticator) then User pod is unable to start & goes into init:error. On creation on pod, PVC is generated in the same namespace, but still the user pod is unable to bound to same.

### How to reproduce

1. Go to jupyterhub UI & provided any dummy username & password
2. See Init:error for user specific pod

#### Expected behaviour

- On user creation, PVC should be created & bounded to the User specific pod.  

#### Actual behaviour
- User pod is unable to bound to user PVC

 - OS:
 RHEL == 8.7
 - Version(s):
 jupyterhub == 4.0.2, chart version == 3.0.3

<details><summary>Configuration</summary>
NO specific config.yaml was provided, default config is used
</details>

<details><summary>Logs</summary>
> kubectl describe gives following error:

0/3 nodes are available: c. preemption: 0/3 nodes are available: 3 No preemption victims found for incoming pod..
Successfully assigned z2jh/jupyter-yash to unifyai-dev-main
Container image "jupyterhub/k8s-network-tools:3.0.3" already present on machine
Created container block-cloud-metadata
Started container block-cloud-metadata
Back-off restarting failed container block-cloud-metadata in pod jupyter-yash_z2jh(2af75e14-0085-45

</details>

**Comment by consideRatio** [comment]
This is related to your k8s clusters setup most likely, where it doesnt yet successfully provision storage.

I think there is some help about this in the troubleshooting section on z2jh.jupyter.org on how to diagnose this but thats not the full solution. To find that, you should probably search for more info related to provisioning storage in the kind of k8s cluster you have setup (microk8s, k3s, using kubeadm, etc).
