### ISSUE TITLE
Confused about Google authentication in documentation

### ISSUE THREAD

**Issue by mrocklin** [jupyterhub/zero-to-jupyterhub-k8s#324]
When walking through this documentation, http://zero-to-jupyterhub.readthedocs.io/en/latest/extending-jupyterhub.html#full-example-of-google-oauth2, I reach the following lines:

> Set “Authorized JavaScript origins” to be your hub’s URL.
> Set “Authorized redirect URIs” to be your hub’s URL followed by “/hub/oauth_callback”. For example, http://example.com/hub/oauth_callback.

However at the moment I'm just screwing around, and don't have a proper domain name.  I tried throwing in the public-facing IP address given by google cloud (I'm on Google cloud by the way) but the console said that this was invalid.

**Comment by ryanlovett** [comment]
Unfortunately Google does not permit IPs to be specified. See the comments to https://stackoverflow.com/a/14262443 and the note in the documentation you linked to:

> Google requires that you specify a fully qualified domain name for your hub rather than an IP address.

**Comment by mrocklin** [comment]
Thanks for the prompt response.  Is there a reasonable way to play around with Google authentication prior to obtaining a domain name?

**Comment by ryanlovett** [comment]
Perhaps a service like xip.io, though I've never used it myself. A response in the previously linked stackoverflow question said it worked fine.

Dynamic DNS is another possibility.
