### ISSUE TITLE
Secrets Manager implementation

### ISSUE THREAD

**Issue by dhfherna** [jupyterhub/zero-to-jupyterhub-k8s#3244]
Currently, I'm requiring to implement Secrets Manager in JupyterHub because I use secrets for database connection and Secrets Manager has active rotation.

In the forum I found the following information: https://discourse.jupyter.org/t/fedramp-using-aws-secret-manager-to-improve-security-on-zero-to-jupyterhub-k8s/4943

However, this information is not clear for me and my experience with other type of configuration, I prefer to check here if there is official documentation to activate this implementation (if exist).

Thanks in advance for any help you can give me.

**Comment by manics** [comment]
One of the main strengths of Kubernetes is that it's an abstraction over cloud specific services. As far as I can tell https://discourse.jupyter.org/t/fedramp-using-aws-secret-manager-to-improve-security-on-zero-to-jupyterhub-k8s/4943 is using AWS Secrets as a backend for Kubernetes secrets, so assuming you can securely configure your K8s secrets Z2JH should be able to use them.

There are some potential other issues with automatically rotating secrets, e.g. does it immediately kill any connections using the old secrets, etc. I think this is worth discussing and testing, but given the community interest I think it'd be good to continue the conversation on Discourse. Would you mind adding to the above Discourse thread and closing this issue?
