### ISSUE TITLE
Minikube guide leads to a hub pod crashloop trying to open database file

### ISSUE THREAD

**Issue by ammarar** [jupyterhub/zero-to-jupyterhub-k8s#3310]
### Bug description
Running the Jupyterhub [installation guide](https://z2jh.jupyter.org/en/stable/jupyterhub/installation.html) in minikube produces this error:
[error.txt](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/files/13848200/error.txt)

### How to reproduce

1. Create a minikube kubernetes cluster
2. Run helm upgrade in [this step](https://z2jh.jupyter.org/en/stable/jupyterhub/installation.html#install-jupyterhub)
Example:
```
helm3 upgrade --cleanup-on-fail \
  --install test-1 jupyterhub/jupyterhub \
  --namespace jupyterhub \
  --create-namespace \
  --version=3.2.1 \
  --values config.yaml
```

#### Expected behaviour

Step 4 in [doc](https://z2jh.jupyter.org/en/stable/jupyterhub/installation.html#install-jupyterhub) says that you should have pods in Running state

#### Actual behaviour

The hub pod is in `CrashLoopBackOff` and when I see the logs, it shows the following error:
[error.txt](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/files/13848200/error.txt)

### Your personal set up

 - OS: macOS 13.5 Intel
 
 - Version(s): jupyterhub 3.2.1
 

<details><summary>Full environment</summary>

```
# paste output of `pip freeze` or `conda list` here
```
</details>

<details><summary>Configuration</summary>

```python
# jupyterhub_config.py
```
</details>

<details><summary>Logs</summary>

```
# paste relevant logs here, if any
```
</details>

**Comment by manics** [comment]
Hi, please can you open a support issue on our community forum, as this may be an issue with your config or your minikube setup: https://discourse.jupyter.org/

Please provide enough information to reproduce your issue, including your config and your full debug logs. Thanks!
