### ISSUE TITLE
API 'storage.k8s.io/v1beta1' will be removed in Kubernetes versions >1.26

### ISSUE THREAD

**Issue by GuillermoGarciaF** [jupyterhub/zero-to-jupyterhub-k8s#3311]
### Bug description

Usage of API 'storage.k8s.io/v1beta1' is removed in Kubernetes versions >1.26
As a consequence, the latest stable JupyterHub chart is not compatible with Kubernetes version 1.27 or higher, see [deprecation guide](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#csistoragecapacity-v127)

### How to reproduce

Install Helm Chart in minikube
Helm Chart deployment fails if using Kubernetes versions > 1.26

#### Expected behaviour

Kubernetes already support versions up to 1.32
It is expected that Jupyter is compatible with up until 1.28 if not more.

#### Actual behaviour

JupyterHub is not compatible with Kubernetes version 1.27 or higher

### Your personal set up

OS: ubuntu 20.04
Version(s):
jupyter helm chart 3.2.1
kubernetes: v1.26.7
Docker 24.0.4

```
# paste relevant logs here, if any
```
Original Error: Code="ValidationError" Message="Control Plane upgrade is blocked due to recent usage of a Kubernetes API deprecated in the specified version. Please refer to https://kubernetes.io/docs/reference/using-api/deprecation-guide to migrate the usage. To bypass this error, set forceUpgrade in upgradeSettings.overrideSettings. Bypassing this error without migrating usage will result in the deprecated Kubernetes API calls failing. See details in https://aka.ms/aks/UpgradeAndDeprecatedAPIs. Usage details: 1 error occurred:\n\t* usage has been detected on API storage.k8s.io.csistoragecapacities.v1beta1.watch, and was recently seen at: 2023-12-26 13:53:50 +0000 UTC, which will be removed in 1.27\n\n"

**Comment by manics** [comment]
Storage classes are handled by the k8s admin:
https://kubernetes.io/docs/concepts/storage/storage-classes/

Z2JH uses them, but it doesn't define them.

**Comment by GuillermoGarciaF** [comment]
Hello @manics, thank you for your answer.

You're correct, I cleaned up the Z2JH installation, forced an upgrade to Kubernetes 1.28 and redeployed Z2JH succesfully.
Thank you, we can close the issue
