### ISSUE TITLE
Impossible to deploy in a specific namespace

### ISSUE THREAD

**Issue by juranir** [jupyterhub/zero-to-jupyterhub-k8s#3346]
### Bug description

I would like to implement this Helm chart in a specific namespace, but there is no such option in the chart.

### How to reproduce

Looking at the [file](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/main/jupyterhub/templates/hub/deployment.yaml#L3) as an example, we don't have the namespace parameter set, so it will always be created in the `default` namespace

#### Expected behaviour

Add the namespace as a parameter or use the namespace defined by the Helm (via `.Release.Namespace` variable )

#### Actual behaviour

The resources are being created in the `default` namespace

PS. I'm available to create an RP for that, if it's useful

**Comment by consideRatio** [comment]
Use the flag --namespace=my-namespace and it will work!

A chart installation is called release, and the .Release.Namespace value is populated based on where the helm command installing the chart is instructed to install it, so .Release.Namespace is not controlled as other .Values via chart configuration files.

It could make sense to assume we would see metadata.namespace set in the templates, but that field specifically is populated by helm without it being declared in the temolate.

**Comment by consideRatio** [comment]
More details at https://z2jh.jupyter.org btw!)

**Comment by juranir** [comment]
Thank you very much for your quick reply.

I tried the command below and the output does not have the namespace field.

`helm install --dry-run --debug <REDACTED> --namespace=<REDACTED> --generate-name`

![image](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/assets/6254271/7ba8f063-612d-47d9-b1dc-46592c868be8)


Maybe I'm doing something wrong, but I appreciate any help.

**Comment by consideRatio** [comment]
Ah, I figure the interaction then is like `kubectl apply --namespace my-namespace -f <some resource without metadata.namespace specified>` which would then end up in the right namespace, but the generated resource didn't declare the namespace.
