### ISSUE TITLE
Can I use Email instead of UPN as a login method to the jupyter hub servers

### ISSUE THREAD

**Issue by Stewary-sudo** [jupyterhub/zero-to-jupyterhub-k8s#3358]
We are sing Azure with Jupyterhub. There the authentication method being used is AzureAdOAuthenticator. When we login to the servers it uses our UPN which have other tags attached to it so instead of using UPN we like to use email. I tried adding username_key: ‘email’ into the config file but it did not work.

**Comment by manics** [comment]
It looks like there's a very similar question recently posted on Discourse https://discourse.jupyter.org/t/use-email-instead-of-upn-as-user-login-method/24492
That's the best place for questions like these since they benefit from community input!
