### ISSUE TITLE
JupyterHub 3+ would block internal DNS by default?

### ISSUE THREAD

**Issue by linlol** [jupyterhub/zero-to-jupyterhub-k8s#3398]
I am using JupyterHub with https://github.com/jupyterhub/zero-to-jupyterhub-k8s and I found issue during upgrade.

Currently I am using z2jh **1.2.0** with JupyterHub **1.5.0**, and I am planning to upgrade to z2jh 2.0.0 and hub 3.0.0

looks like after upgrade, I can no longer send internal request thru Service within the same namespace like curl https://${SVC_NAME}/${ENDPOINTS}

Seems like the connection between lab and hub is great, but for other services which is not managed by z2jh helm, JupyterLab cannot access them via internal DNS

Is it something disabled due to the rbac feature?

**Comment by manics** [comment]
Z2JH 2 contained some breaking changes regarding the network policy rules, have a look at
https://z2jh.jupyter.org/en/stable/administrator/upgrading/upgrade-1-to-2.html#upgrade-1-2-security-breaking-change

Note that Z2JH 2 is still very old and unsupported, the most recent release is 3.3.7.

**Comment by linlol** [comment]
> Z2JH 2 contained some breaking changes regarding the network policy rules, have a look at https://z2jh.jupyter.org/en/stable/administrator/upgrading/upgrade-1-to-2.html#upgrade-1-2-security-breaking-change
> 
> Note that Z2JH 2 is still very old and unsupported, the most recent release is 3.3.7.

Thanks @manics, I would check my helm configuration!

**Comment by linlol** [comment]
btw @manics 

Is there any migration guide for z
2jh 2-> 3 (jupyterhub 3->4)? I cannot find similar thing in doc.

Or the change is generally backward compatible except db change

**Comment by consideRatio** [comment]
There isn't a migration guide besides the changelog listing what should be considered for z2jh 2 -> 3
