### ISSUE TITLE
Fails to deploy on RBAC enabled cluster

### ISSUE THREAD

**Issue by avaranovich** [jupyterhub/zero-to-jupyterhub-k8s#344]
`helm install jupyterhub/jupyterhub --version=v0.5.0-aee2160 --name=datalab-jupyterhub --namespace=ox  -f config.yaml --set prePuller.enabled=false`

fails with

`Error: release datalab-jupyterhub failed: clusterroles.rbac.authorization.k8s.io "nginx-datalab-jupyterhub" is forbidden: attempt to grant extra privileges: [PolicyRule{Resources:["configmaps"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["configmaps"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["endpoints"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["endpoints"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["nodes"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["nodes"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["secrets"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["secrets"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["namespaces"], ResourceNames:["ox"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["nodes"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["update"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["ingresses"], APIGroups:["extensions"], Verbs:["get"]} PolicyRule{Resources:["ingresses"], APIGroups:["extensions"], Verbs:["list"]} PolicyRule{Resources:["ingresses"], APIGroups:["extensions"], Verbs:["watch"]} PolicyRule{Resources:["events"], APIGroups:[""], Verbs:["create"]} PolicyRule{Resources:["events"], APIGroups:[""], Verbs:["patch"]} PolicyRule{Resources:["ingresses/status"], APIGroups:["extensions"], Verbs:["update"]}] user=&{system:serviceaccount:kube-system:tiller 2a92a2cb-dbed-11e7-ac49-0a58ac1f0f75 [system:serviceaccounts system:serviceaccounts:kube-system system:authenticated] map[]} ownerrules=[] ruleResolutionErrors=[clusterroles.rbac.authorization.k8s.io "cluster-admin" not found]`

I am using ACS if that matters.

**Comment by cam72cam** [comment]
I am getting the same error and am quite perplexed (still new to k8s).

**Comment by avaranovich** [comment]
I don't use kops, rather Azure Container Service (actually AKS). But it feels the "cluster-admin" role is expected but not found. I am just not sure if this a K8S config issue or the chart expects something which is not necessary present in the cluster.

**Comment by yuvipanda** [comment]
@cam72cam @avaranovich can you both try using v0.5 directly instead o the tagged release?

@avaranovich what's the output of 'kubectl get clusterrole'?

**Comment by cam72cam** [comment]
```
  341  kops create cluster $NAME   --zones $ZONES   --authorization AlwaysAllow   --master-size t2.micro   --master-volume-size 10   --node-size t2.medium   --node-volume-size 10   --yes
  342  kops validate cluster $NAME
  343  kubectl create clusterrolebinding permissive-binding  --clusterrole=cluster-admin  --user=admin  --user=kubelet  --group=system:serviceaccounts
  344  kubectl --namespace kube-system create sa tiller
  345  kubectl create clusterrolebinding tiller --clusterrole cluster-admin --serviceaccount=kube-system:tiller
  346  helm init --service-account tiller
  347  helm version
  348  helm repo add jupyterhub https://jupyterhub.github.io/helm-chart/
  349  helm repo update
  350  helm --debug install jupyterhub/jupyterhub     --version=v0.5     --name=cmesh-foo     --namespace=cmesh-foo -f config.yaml
[debug] Created tunnel using local port: '39653'

[debug] SERVER: "127.0.0.1:39653"

[debug] Original chart version: "v0.5"
[debug] Fetched jupyterhub/jupyterhub to /home/ec2-user/.helm/cache/archive/jupyterhub-v0.5.0.tgz

[debug] CHART PATH: /home/ec2-user/.helm/cache/archive/jupyterhub-v0.5.0.tgz

Error: roles.rbac.authorization.k8s.io "pre-puller-cmesh-foo-1" is forbidden: attempt to grant extra privileges: [PolicyRule{Resources:["jobs"], APIGroups:["batch"], Verbs:["get"]} PolicyRule{Resources:["jobs"], APIGroups:["batch"], Verbs:["list"]} PolicyRule{Resources:["jobs"], APIGroups:["batch"], Verbs:["create"]} PolicyRule{Resources:["jobs"], APIGroups:["batch"], Verbs:["update"]} PolicyRule{Resources:["jobs"], APIGroups:["batch"], Verbs:["delete"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["delete"]}] user=&{system:serviceaccount:kube-system:tiller 5ee65b72-de91-11e7-9d8f-12dfc18c913a [system:serviceaccounts system:serviceaccounts:kube-system system:authenticated] map[]} ownerrules=[] ruleResolutionErrors=[[clusterroles.rbac.authorization.k8s.io "cluster-admin" not found, clusterroles.rbac.authorization.k8s.io "cluster-admin" not found]]
```

**Comment by lelithium** [comment]
Had same issue. As of now, reverted to using k8s v1.7 with kops1.7, and the v0.4 JupyterHub Helm chart with pre-pulling disabled.

Would be very interested by a solution using k8s v1.8 with RBAC :+1:

**Comment by avaranovich** [comment]
@yuvipanda 
`kubectl get clusterrole
`
outputs
`No resources found.`

**Comment by avaranovich** [comment]
turns out, the cluster is not RBAC enabled (which is strange, because its 1.8).
What worked for me is

- delete the helm

- re-init the helm, **without** assigning clusterrolebinding

- deploy the chart with the --set=rbac.enabled=false option

**Comment by cam72cam** [comment]
I've found that the latest docs work as long as I have the following in my config.yaml:
```
prePuller:
  enabled: false
rbac:
  enabled: false
```

**Comment by argoneus** [comment]
I had this issue as well, both with ACS and the new preview AKS.  The workaround suggested by @cam72cam worked for me, thanks!

**Comment by argoneus** [comment]
Also interested in an RBAC-enabled solution.  http://zero-to-jupyterhub.readthedocs.io/en/latest/security.html#use-role-based-access-control-rbac strongly recommends against disabling RBAC, due to security concerns.

**Comment by yuvipanda** [comment]
I'm playing with AKS now, and just setting:

```
rbac:
   enabled: false
```

seems to work. There isn't much we can do but wait for AKS to support RBAC (https://github.com/Azure/AKS/issues/67)

**Comment by yuvipanda** [comment]
Spoke too soon, I needed to disable the prePuller too. Hopefully #399 should help fix that.

**Comment by yuvipanda** [comment]
#399 fixes this on the pre-puller, and for AKS there's now instructions in master on disabling RBAC.

Thanks for reporting and debugging with us! <3
