### ISSUE TITLE
Not possible to add a ServiceAccount to the Prepuller

### ISSUE THREAD

**Issue by samyuh** [jupyterhub/zero-to-jupyterhub-k8s#3442]
### Bug description
Even though `prepuller.hook.serviceaccount` is properly configured, these changes aren't applied in the pods

### How to reproduce
1. Configure `prepuller.hook.serviceaccount` with a service account
2. Apply the changes
3. Check that the pod `image-puller` uses the default service account, even though that was not the service account we defined

#### Expected behaviour
The Service Account should be properly set

#### Actual behaviour
The Service Account used is the default and we have no way to change it

**Comment by samyuh** [comment]
This bug is fixed by https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/3441
Can some mantainer review it? :)

**Comment by consideRatio** [comment]
I made a decision about this with some relevant background discussed in https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/3441#issuecomment-2413342694.

I'm opening https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/3545 to represent discussion about if we should work to make it possible to configure daemonset pods' serviceaccounts.
