### ISSUE TITLE
Jupyterhub stable docker image not working out of the box

### ISSUE THREAD

**Issue by ThomasLabstep** [jupyterhub/zero-to-jupyterhub-k8s#3463]
Hello,

Apologies in advance for polluting this repo with my request but it sounds like it should work out of the box.

I'm trying to do a very basic setup on the latest version of jupyterhub and I'm stuck on something very simple.

But as this is the standard docker image, I'm like what's going on... it should work right?

I'm using minikube on a MacBook Pro M1 with docker image: jupyterhub/k8s-hub:3.3.7

I'm getting this:

```
      File "/usr/local/etc/jupyterhub/jupyterhub_config.py", line 9, in <module>
        from kubernetes import client
    ModuleNotFoundError: No module named 'kubernetes'
```

Now if I add:

```
RUN pip3 install kubernetes
```

in the docker file

I then get:

```
      File "/usr/local/etc/jupyterhub/z2jh.py", line 6, in <module>
        from collections import Mapping
    ImportError: cannot import name 'Mapping' from 'collections' (/usr/local/lib/python3.11/collections/__init__.py)
```

And I'm stuck.

I thought it was a Python version issue but clearly that image specifies Python 3.11 in its configuration.

Let me know if I'm missing something obvious.

Is 3.3.7 the latest stable release? 4.0.0 tags are all dev it seems...

Thank you for your support.

```
python3 --version
Python 3.11.9
```

**Comment by manics** [comment]
3.3.7 is the latest stable release. We switched to the [`kubernetes_asyncio`](https://github.com/tomplus/kubernetes_asyncio#readme) library a while back.
