### ISSUE TITLE
Using storage type "none" creates mysterious "work" directory

### ISSUE THREAD

**Issue by kkapper** [jupyterhub/zero-to-jupyterhub-k8s#3502]
### Bug description

If you are using the "none" storage type for the singleuser pods in a jupyterhub deployment you will have this directory created for you /home/jovyan/work

### How to reproduce

Just use the none type for single user storage and launch a user pod.

```
jupyterhub:
  singleuser:
    storage:
      type: none
```

#### Expected behaviour

There would simply not be any directories created at /home/jovyan other than what extra volumes may be specified.

In the case below I am using storage type: dynamic

![image](https://github.com/user-attachments/assets/706ba347-4690-455c-8318-bae282cf4b6a)

We create shared and private directories, and we get a lost+found directory auto generated (not idea but not this issue)

#### Actual behaviour

In this case, we are using storage type: none

![image](https://github.com/user-attachments/assets/3de87bea-3ef7-4a95-b60d-718e82c8a457)

You can see we get some kind of /home/jovyan/work directory with an odd create date.

### Your personal set up

Using zerotojupyterhubk8s chart version 3.0.3

**Comment by kkapper** [comment]
I can't find any references to that /work directory being created by the chart so I suspect it might be a bug, although this may be intended behavior.

**Comment by manics** [comment]
If you haven't mounted any storage you'll see whatever is in your original container image. Z2JH doesn't provide any files or directories by default.
