### ISSUE TITLE
Document ConfigMap items

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/zero-to-jupyterhub-k8s#351]
In the v0.5 post we mentioned ConfigMap items, but it was a bit too specific to put in the general blog post. Instead we should clearly document this (maybe in the schema?). Here's the text below:

> ConfigMap items can be arbitrary YAML, and you can read them via the get_config function in your hub.extraConfig.

**Comment by yuvipanda** [comment]
It's documented here: http://zero-to-jupyterhub.readthedocs.io/en/latest/advanced.html#arbitrary-code-in-jupyterhub-config-py.

**Comment by choldgraf** [comment]
perfect - adding that link to the blog post and closing this issue!
