### ISSUE TITLE
Create storage documentation

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/zero-to-jupyterhub-k8s#356]
Storage is the most complex part of setting up z2jh, and we need to provide better docs on it.

Things to cover:

1. What the default storage model is (one persistent disk per user), pros and cons of it
2. How to customize storage on public clouds
3. Using your own NFS server
4. When to not use storage

**Comment by choldgraf** [comment]
This is a really important topic - @yuvipanda would it be worth our time for you to give some barebones steps for storage, and I can build some docs around that?

**Comment by yuvipanda** [comment]
Me and @choldgraf had a quick whiteboarding session about this, and he's going to write up a draft soon.

**Comment by yuvipanda** [comment]
https://hackmd.io/CwJgbAxgjArMYFoQQKYGYHAEYoIYIE5gosEAOAExBgjINwDMoHgg?edit is the hackmd for it, thanks @choldgraf!

**Comment by yuvipanda** [comment]
@choldgraf am adding more content now. Will ping here again when am done!

**Comment by yuvipanda** [comment]
@choldgraf I added a bunch more content, and I think it's ready for another pass from you + PR. There's no mention of NFS, but I think we can add those later.

**Comment by yuvipanda** [comment]
I think this is mostly done, we should probably open a separate issue to talk about NFS.

I could add a PR talking about Azure SSD use though!

**Comment by choldgraf** [comment]
+1 - I think we should close this (at least as its spot in the milestone) and iterate on subsequent storage stuff

**Comment by choldgraf** [comment]
also for future people, this as deployed here: http://zero-to-jupyterhub.readthedocs.io/en/latest/user-storage.html#user-storage

**Comment by yuvipanda** [comment]
+1. I filed https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/420 for Azure SSD storage, https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/421 for NFS!
