### ISSUE TITLE
kubectl logs clears during JupyterHub startup

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#357]
I wanted to debug some code in my config files that raised an error, so I used `print()` and found some messages in the `kubectl` logs for the hub as well as the raised error.

When I fixed my error, I realized that my print statements output could no longer be found in the logs. They seem to be removed by some point in the startup of JupyterHub. The first thing I can see in the logs are "Loading cookie_secret from [...]".

Perhaps somewhere along JupyterHub [`initialize`](https://github.com/jupyterhub/jupyterhub/blob/0b4c7defd4568e6afeb1100be28f5da96f95acfd/jupyterhub/app.py#L1371) method, calling [`init_logging`](https://github.com/jupyterhub/jupyterhub/blob/0b4c7defd4568e6afeb1100be28f5da96f95acfd/jupyterhub/app.py#L757), something is done that clears the logs.

@yuvipanda suggested I'll file this as a bug and to mention you @minrk.

**Comment by minrk** [comment]
When the Hub is run in kubernetes, init_logging doesn't do ~anything other than hook things up to stderr. It also has no effect on past logs. Generally when updating jupyterhub in kubernetes, you are getting a new pod and that means starting logs again from scratch, so logs are not preserved across launches unless you are using a separate log aggregator.

**Comment by consideRatio** [comment]
Hmmmm, `init_logging` might not do anything to clear the logs, but something does, and I view the logs of the same pod I'm quite certain. At least, I'm certain I'm looking at the logs of an starting pod, not a terminating pod. I look at the same entry in the `kubectl get pods` list that switch from *ContainerCreating* to *Running*.

My situation:
1. Hub pod is in the state of ContainerCreating
2. Hub pod is in the state of Running, and is running code in the configs.
    - If I write `print("meow!") in the config, I'll see **meow!** in the `kubectl logs` for the hub if I make sure to halt the code execution, for example by dividing by zero.
3. Hub pod is in the state of Running, and has run the code in the configs.
    - I can no longer see **meow** in the `kubectl logs` for the hub. The first line in the logs comes from [this line of code](https://github.com/jupyterhub/jupyterhub/blob/0b4c7defd4568e6afeb1100be28f5da96f95acfd/jupyterhub/app.py#L466).

**Comment by willingc** [comment]
@consideRatio What do you believe the next action should be re: logging?

**Comment by consideRatio** [comment]
@willingc Hmm hmmm I think I currently lack relevant understanding of how the logs travel from print() statements in the config to the response of `kubectl logs`. This could be a z2jh issue, a jupyterhub issue, or perhaps even not an issue...

To summarize
- Logs are cleared during startup of the hub, this made it harder to debug config code
- It isn't a big deal, but I'd say that it is an unwanted behavior

Actionplan
a) ask you for help finding a person to ask that might have relevant background knowledge to guess what might cause the logs to disappear - @willingc do you know someone?
b) wait and get back to this after I've learned more about kubernetes and where `kubectl logs` gets the actual logs from.

**Comment by consideRatio** [comment]
Looked through issues I've created and I figure I'm no longer prioritizing figuring this out.

Should I close it?
