### ISSUE TITLE
Documentation on hub.extra-config.py

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#358]
It took me quite a while to realize there is a difference in what you can put inside `hub.extra-config.py` and `jupyter_config.py`, I still do not comprehend the details - perhaps this could be made clearer in the documentation?

For example, this code will fail silently in `hub.extra-config.py` by using the default authenticator, while it will succeed when I put it in the `jupyterhub_config.py`.

```python
class MyAuthenticator(MicrosoftOAuthenticator):  
    @gen.coroutine
    def pre_spawn_start(self, user, spawner):
        spawner.environment['THIS_CAME_FROM_HUB_EXTRA_CONFIG'] = "OMG WORKING"

c.JupyterHub.authenticator_class = MyAuthenticator
```

I tried to understand why there is a difference, and I figure its related to the inner workings of [`load_config`](https://github.com/ipython/traitlets/blob/4da01bfdd675783ab64a21df015e49378d91cbd2/traitlets/config/loader.py#L190) as well as [`merge`](https://github.com/ipython/traitlets/blob/4da01bfdd675783ab64a21df015e49378d91cbd2/traitlets/config/loader.py#L190) defined in the `traitlets` library and accessibility of python classes defined in the different files or similar.

**Comment by yuvipanda** [comment]
Ideally they should behave the same, and if they don't it's a bug. Did you import MicrosoftAuthenticator and 'gen' in the extra config? What is the error you were getting?

**Comment by consideRatio** [comment]
I get no error. It simply does not utilize my custom Authenticator defined in the hub.extra-config.py. I have verified that things I write in the hub.extra-config.py is actually influencing my JupyterHub at all, I did this by for example defining a user to be admin or not within it --- so I know it is actually utilized in some way.

Perhaps there is some warning message I have missed due to #357?

**Comment by yuvipanda** [comment]
Hmm, interesting. I'm doing something extremely similar at https://github.com/yuvipanda/paws/blob/master/paws/values.yaml#L29 and it totally works.

I guess we need to find a way to produce log statements from inside your authenticator to see what's going on.

**Comment by yuvipanda** [comment]
Do you explicitly enable auth_state anywhere? (I do so in https://github.com/yuvipanda/paws/blob/master/paws/values.yaml#L37). Also can you check inside the hub database if auth_state is actually being recorded?

**Comment by consideRatio** [comment]
Ah, yes I do, in `values.yaml` since I updated for #314.

There is a difference between our situations, you are using the extraConfig in the values file, while I use `hub.extra-config.py`. How is the extraConfig loaded?

**Comment by yuvipanda** [comment]
It's loaded via https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/jupyterhub/templates/hub/configmap.yaml#L93

**Comment by consideRatio** [comment]
I just noticed, but hmm... I'm learning more and more about kubernetes along the way, but isn't this simply setting some variable, named "hub.extra-config.py" inside a "data" field?

I'm a bit confused, I don't see that leading all the way to having a `hub.extra-config.py` file inside `/etc/jupyterhub/config/`

**Comment by consideRatio** [comment]
I'm trying to pin down an answer to the question: Is having text inside /etc/jupyter/config/hub.extra-config.py exactly the same as having it within the `values` file field called `extraConfig`?

I get how the hub.extra-config.py is loaded from /etc/jupyterhub/conifg/ folder by a load_subconfig call in the end jupyterhub_config.py, but I lost track of how `extraConfig` in `values.yaml` through `configmap.yaml`.

I'll read up on configmap.yaml's function.

**Comment by consideRatio** [comment]
@yuvipanda could you give me a pointer on how to look inside the hub database? I'm using the default hub database.

**Comment by consideRatio** [comment]
Will this difference matter?

```python
class MyAuthenticator(MicrosoftOAuthenticator):
    pass


c.JupyterHub.authenticator_class = MyAuthenticator
c.MicrosoftOAuthenticator.client_id = get_config('auth.microsoft.client-id')
```

```python
c.MicrosoftOAuthenticator.client_id = get_config('auth.microsoft.client-id')

class MyAuthenticator(MicrosoftOAuthenticator):
    pass


c.JupyterHub.authenticator_class = MyAuthenticator
```

**Comment by consideRatio** [comment]
I got my own code to work by placing it within extraConfig...

So, now I'm trying to get my code to work within hub.extra-config.py and ensuring that that code is actually run...

**Comment by consideRatio** [comment]
@yuvipanda thanks for your time! Okay... So I probably made a faulty confirmation along the way that code within my by the Dockerfile injected `hub.extra-config.py` file actually ran... The following code in the end of `images/hub/jupyterhub_config.py` resulted in an output of `THE PATH DID NOT EXIST!!!`.

```python
extra_config_path = '/etc/jupyterhub/config/hub.extra-config.py'
if os.path.exists(extra_config_path):
    print("THE PATH EXISTED!!!")
    load_subconfig(extra_config_path)
    print("SUBCONFIG LOADED")
    import io
    file = io.open(extra_config_path)
    print(file.readLine())
    print(file.readLine())
    print(file.readLine())
    file.close()
    print("SUBCONFIG READ")
else:
    print("THE PATH DID NOT EXIST!!!")

# And now, I halt execution in order to be able to read the logs using kubectl logs ...
print(5/0)
```

---

```Dockerfile
# ... the end of images/hub/Dockerfile
RUN pip3 --no-cache-dir install git+https://github.com/jupyterhub/kubespawner@v0.7.1



# -----------------------------------------------------------------------------
# MY PERSONAL EXTENSIONS TO THIS DOCKERFILE
RUN pip3 --no-cache-dir install \
    git+https://github.com/consideRatio/oauthenticator

COPY hub.extra-config.py /etc/jupyterhub/config/hub.extra-config.py
# -----------------------------------------------------------------------------



COPY jupyterhub_config.py /srv/jupyterhub_config.py
COPY cull_idle_servers.py /usr/local/bin/cull_idle_servers.py

WORKDIR /srv/jupyterhub

# So we can actually write a db file here
RUN chown ${NB_USER}:${NB_USER} /srv/jupyterhub

# JupyterHub API port
EXPOSE 8081

USER ${NB_USER}

CMD ["jupyterhub", "--config", "/srv/jupyterhub_config.py"]
```

---

I don't get why my `hub.extra-config.py` isn't found `/etc/jupyterhub/config/hub.extra-config.py` though...

**Comment by consideRatio** [comment]
I'll ask about the above in another issue, and close this, as there probably were no difference.
