### ISSUE TITLE
 recommend using https for github for s2i

### ISSUE THREAD

**Issue by amueller** [jupyterhub/zero-to-jupyterhub-k8s#36]
In 4. in
https://zero-to-jupyterhub-with-kubernetes.readthedocs.io/en/latest/extending-jupyterhub.html#extending-your-software-stack-with-s2i

maybe recommend using the https url. I had issue with the ssh one. Also maybe just giving an example might be helpful. "git-repo-url" could be multiple things maybe?

**Comment by yuvipanda** [comment]
Closing this now, since we don't actually use s2i anymore!
