### ISSUE TITLE
Copying hub.extra-config.py from a Dockerfile?

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#360]
EDIT - SHORT SUMMARY: Why isn't my hub.extra-config.py file available if my Dockerfile copies one to to the correct path?

I disliked the idea of writing my additional code in the extraConfig value in the `values.yaml` file. So I figured I'd insert the `hub.extra-config.py` file manually, instead of letting it be created through `values.yaml` influencing a section in `configmap.yaml`.

Somewhere, I figure I have made a mistake in how I do this. As the following code in the end of `images/hub/jupyterhub_config.py` resulted in an output of `THE PATH DID NOT EXIST!!!`.

I don't get why my `hub.extra-config.py` isn't found in `/etc/jupyterhub/config/hub.extra-config.py` when `jupyterhub_config.py` is running. Anyone can figure out what I've done wrong?

```python
extra_config_path = '/etc/jupyterhub/config/hub.extra-config.py'
if os.path.exists(extra_config_path):
    load_subconfig(extra_config_path)
else:
    print("THE PATH DID NOT EXIST!!!")

# And now, I halt execution in order to be able to read the logs using kubectl logs ...
print(1/0)
```

---

```Dockerfile
# ... the end of images/hub/Dockerfile
RUN pip3 --no-cache-dir install git+https://github.com/jupyterhub/kubespawner@v0.7.1



# -----------------------------------------------------------------------------
# MY PERSONAL EXTENSIONS TO THIS DOCKERFILE
RUN pip3 --no-cache-dir install \
    git+https://github.com/consideRatio/oauthenticator

COPY hub.extra-config.py /etc/jupyterhub/config/hub.extra-config.py
# -----------------------------------------------------------------------------



COPY jupyterhub_config.py /srv/jupyterhub_config.py
COPY cull_idle_servers.py /usr/local/bin/cull_idle_servers.py

WORKDIR /srv/jupyterhub

# So we can actually write a db file here
RUN chown ${NB_USER}:${NB_USER} /srv/jupyterhub

# JupyterHub API port
EXPOSE 8081

USER ${NB_USER}

CMD ["jupyterhub", "--config", "/srv/jupyterhub_config.py"]
```

**Comment by consideRatio** [comment]
Btw, this is how my `values.yaml` looks:

```yaml
  labels: {}
  extraConfig:
  extraConfigMap: {}
```

**Comment by yuvipanda** [comment]
Heya!

We [mount the configmap](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#populate-a-volume-with-data-stored-in-a-configmap) as a volume in the pod (at https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/jupyterhub/templates/hub/deployment.yaml#L28). This means that everything under /etc/jupyterhub/config in the docker image is going to be overwritten by the contents of the ConfigMap, which is why directly modifying the image will not work.

Is there a reason you prefer modifying the image vs using the configmap (via values.yaml)?

**Comment by consideRatio** [comment]
Ah that explains it! Thank you for clarifying this!

I wanted too separate stuff file wise in as I figured it would make it simpler to git rebase when I update my fork. I also wanted to avoid inlining config code inside extraValues as it felt messy.

I'll live with it!

**Comment by yuvipanda** [comment]
I usually use a 'meta chart' (see https://github.com/berkeley-dsep-infra/datahub/) for doing this kinda stuff, instead of forking :) 

Glad you found it useful!
