### ISSUE TITLE
Investigate recent errors and failures in Travis test builds

### ISSUE THREAD

**Issue by willingc** [jupyterhub/zero-to-jupyterhub-k8s#366]
Recent Travis builds have been throwing errors or failing since about #327. The passing PRs since then do not appear to have run the build fully.

Perhaps #365 related??? or `build.py` changes.

**Comment by yuvipanda** [comment]
I'm convinced it's a race condition somewhere, it's hard to investigate because the same script passes on my local machine :'(

**Comment by willingc** [comment]
@yuvipanda Does this line look correct to you in .travis.yml ?
```
- . ci/minikube.env
```

**Comment by yuvipanda** [comment]
yup, it does!

I suspect the problem might be fixed by https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/367, let's see!

**Comment by willingc** [comment]
Why isn't that line `. ./ci/minikube.env` or `source ./ci/minikube.env`?

**Comment by yuvipanda** [comment]
Not sure why @minrk picked the particular style, I think all three variants would be equivalent at that point.

**Comment by willingc** [comment]
Mmm... I don't think @minrk wrote those lines ;-)

**Comment by yuvipanda** [comment]
Ah, it's @manics - apologies for misattributing :)

**Comment by yuvipanda** [comment]
I've actual error messages now (see https://travis-ci.org/jupyterhub/zero-to-jupyterhub-k8s/builds/320458819)!

```
Warning  Failed                 11s               kubelet, travis-job-f9b24008-9030-400d-bec9-cf2c1b1a5746  Failed to pull image "jupyterhub/k8s-hub:8a3d6f2": rpc error: code = Unknown desc = Error response from daemon: manifest for jupyterhub/k8s-hub:8a3d6f2 not found
```

seemst o be the culprit. Investigating more

**Comment by yuvipanda** [comment]
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/350 was the last PR that was successfully merged, and I think that's what broke all succeeding PRs. It looks like the hub image wasn't pushed properly from the deploy step, so all future builds keep looking for a hub image they can't find.

**Comment by yuvipanda** [comment]
I've fixed it now! I think #350 fixed our deploy process, but the merge of #314 happened when it was broken, causing the image pushes to not happen.

So for this case, I could fix it by making sure the image that these PRs are looking for is present. I did so by:

```
git checkout 8a3d6f2
./build.py --push
```

This has made all the PRs work!

**Comment by yuvipanda** [comment]
#365 is still failing, but I'd like to get https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/367 merged so we can debug it more easily.

**Comment by willingc** [comment]
@yuvipanda Just reviewed #367 if you wish to merge.

**Comment by yuvipanda** [comment]
Thank you, @willingc! I rebased https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/365 and it is passing now! Yay we fixed the build! <3

**Comment by yuvipanda** [comment]
I'm closing this now since our builds are good to go :)
