### ISSUE TITLE
Allow making JupyterLab default thing to launch

### ISSUE THREAD

**Issue by mrocklin** [jupyterhub/zero-to-jupyterhub-k8s#375]
Is there a way to make JupyterLab come up by default when new users connect?

Is there a way to get the JupyterHub control panel from JupyterLab?

**Comment by yuvipanda** [comment]
https://github.com/jupyterhub/jupyterlab-hub for accessing JupyterHub control panel from Lab I think.

**Comment by choldgraf** [comment]
We should definitely document how to configure the hub so that lab starts by default

**Comment by choldgraf** [comment]
@mrocklin if you follow the instructions in the repo that @yuvipanda linked, can you report back if it worked? If so I'll make a PR to z2jh to add that in

**Comment by cam72cam** [comment]
I was wondering the same thing.  I followed the instructions there, but it does not have links back to the control panel like JupyterNotebook.

IIRC it is missing something like: https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/singleuser.py#L173

**Comment by yuvipanda** [comment]
I think the way to do this is allow setting default_url in the helm chart, and document that if you want default to be lab you need:

1. Set `singleuser.defaultUrl`
2. Install the jupyterhub-labhub package in your image

**Comment by choldgraf** [comment]
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/403 is going to add a defaulturl config, so I think when that's done the next step is to make a PR that adds JLab instructions in the docs

**Comment by yuvipanda** [comment]
@choldgraf the PR also adds docs :) I've been trying to be a good boy and add docs to all my feature PRs...

**Comment by cam72cam** [comment]
@yuvipanda should I file an issue in jupyterhub-labhub for adding in the top bar control options to lab?  Without that users do not have access to generating their API tokens and starting/stopping their server

**Comment by yuvipanda** [comment]
@cam72cam seems like the right place for it!

**Comment by cam72cam** [comment]
ok, opened: https://github.com/jupyterhub/jupyterlab-hub/issues/34

**Comment by minrk** [comment]
Setting `c.Spawner.cmd = ['jupyterlab-hub']` should do this already, and is the only config needed.

**Comment by choldgraf** [comment]
ah - we should add that to the docs

**Comment by yuvipanda** [comment]
Closed by #403
