### ISSUE TITLE
Document additional authenticators

### ISSUE THREAD

**Issue by minrk** [jupyterhub/zero-to-jupyterhub-k8s#391]
After merging #389, I think we need to think about how and when to add authenticators to the base image. I would have liked to turn down that PR, saying that LTI doesn't meet sufficient criteria that all Hub deployments should install it, but I couldn't point to a good "this is how to use a custom authenticator" reference as an alternative. The problem we have right now:

- only 'officially supported' authenticators work well. This means that ~every authenticator ends up in the base image and getting explicit support in jupyterhub_config.py
- The result is that we need to watch every possible authenticator repo to keep the chart up to date with all of those
- We need to keep our packages up to date, and more packages is more things to keep track of and possibly go stale.

I think we should make an effort to improve support to set up 'custom' (i.e. not in the base image) authenticators, and keep those in the base to a very limited subset. The pressure to add everything to base right now is that the bar for installing a custom authenticator is too high. If we lower that bar, then we can have an easier time keeping lower-volume authenticators out of the base image.

The first step is ensuring that the current process for using a custom authenticator is well documented. After that, we can look for possible ways to improve it, whether in improving the process for building/using a custom image, or installing packages at runtime (probably not), or something else.

**Comment by choldgraf** [comment]
I think this is a good point - sounds like one of those "a medium amount of work now will save a lot of hassle in the future".

Happy to sit down and try to document custom authenticator stuff w/ somebody.

**Comment by consideRatio** [comment]
Extracted this from a deployment of mine, in case it is relevant for the documentation

```python
  extraConfig:
    main: |
      import os
      from z2jh import get_config, get_secret, set_config_if_not_none
      from oauthenticator.generic import GenericOAuthenticator

      # Import auth-information from extraConfigMap set in secret-values.yaml
      c.GenericOAuthenticator.client_id = get_config('custom.client-id')
      c.GenericOAuthenticator.userdata_url = 'https://graph.microsoft.com/v1.0/me'
      c.GenericOAuthenticator.client_secret = get_config('custom.client-secret')
      c.GenericOAuthenticator.oauth_callback_url = get_config('custom.callback-url')
      c.GenericOAuthenticator.hosted_domain = get_config('custom.hosted-domain')
      c.GenericOAuthenticator.login_service = get_config('custom.login-service')

      # Declare custom authenticator:
      # It allows for custom spawn logic as a function of complementary info
      # from Azure AD after the user has logged in but before the user has
      # spawned.
      class MyCustomAuthenticator(GenericOAuthenticator):  
          from tornado import gen

          @gen.coroutine
          def pre_spawn_start(self, user, spawner):
              pass

          @gen.coroutine
          def authenticate(self, handler, data=None):
              """Simplifies usernames from first.last@domain.com to
              first.last."""
              
              # This method is invoked multiple times, only once return_value
              # will by truthy.
              return_value = yield super().authenticate(handler, data)
              if not return_value:
                  return

              # Extract a username from userPrincipalName:
              # First.Last@domain.com -> first.last
              email = return_value['name'].lower()
              return_value['name'] = email.split('@')[0]
              return_value['auth_state']['username'] = return_value['name']
              return return_value

      # Traitlets
      c.JupyterHub.authenticator_class = MyCustomAuthenticator
```

**Comment by consideRatio** [comment]
I don't consider this relevant enough to stay open - I'm on board with doing as much as we can to reference docs in the respective authenticator repo, and not included authenticators we don't maintain in general - this has not become a relevant question for a while now though.
