### ISSUE TITLE
Release v0.6

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/zero-to-jupyterhub-k8s#392]
I want us to try to experiment with time based releases of z2jh, possibly at a 6-8 week cycle. This has several advantages:

1. Forces us to document and automate the release process, so people other than me can do releases
2. Get fixes into the hands of users more quickly
3. Help with a roadmapping process later on.
4. Make upgrades easy and painless for users

To that end, I propose we try to release v0.6 on Jan 24, which is a wednesday close to 6 weeks from when we tagged v0.5 (Dec 13). Whatever makes it by then makes it, and if something doesn't that's ok! 

Objections? I'm going to start tagging things as v0.6 and working on them :)

**Comment by yuvipanda** [comment]
The primary theme I see for 0.6 so far is bug fixes and features that enable autoscalers to work better.

**Comment by yuvipanda** [comment]
As a note, I really like this workflow! Having clear 'what next to work on?' makes it easy to make PRs that have good impact.

**Comment by choldgraf** [comment]
Perhaps at the next meeting we can discuss the primary action-items on the v0.6 milestone?

**Comment by yuvipanda** [comment]
Currently set release date for it is before the next meeting.

**Comment by choldgraf** [comment]
well then for the next release :-)
--

**Comment by yuvipanda** [comment]
I am going to count end of this week as 'feature freeze' date, and then focus only on testing, documentation and polish after that.

**Comment by yuvipanda** [comment]
@choldgraf yes! Can you look at the git log since last release and start a hackmd with changelog? I can edit and pick cricketer (you are also welcome to pick cricketer!)

**Comment by yuvipanda** [comment]
Since we've had two male cricketers so far, I think we should either pick a female cricketer this time.

**Comment by choldgraf** [comment]
I've started putting together pieces for a release here:

https://hackmd.io/BwJghgxgjAnCAsBaYAGeBmR8CmB2GyAbIRIjAEbooAmKEMAZrmOUA===?both

It's currently got a suggested cricketer, a list of the (non merge) commits, and some highlights I pulled outta there. I probably missed some stuff, so please add comments as you think of them!

**Comment by willingc** [comment]
Close #467
