### ISSUE TITLE
How to enable users to create custom environments and use them as notebooks

### ISSUE THREAD

**Issue by mrocklin** [jupyterhub/zero-to-jupyterhub-k8s#393]
Some users (cc @rsignell-usgs) have tried to create new conda environments within their user session (using the terminal from JLab) and have asked about how to start a new notebook with this environment.  It doesn't seem to show up in their kernels list.  Is there something we can do to ease this experience?

**Comment by yuvipanda** [comment]
When you say 'environments' do you specifically mean conda environments? Or something more general?

**Comment by mrocklin** [comment]
Our immediate need is with conda environments, but I expect it to be a
general problem

**Comment by rsignell-usgs** [comment]
I figured it out.  If I add `nb_conda_kernels` to the root environment, then my custom environments show up in the dropdown menu (as long as those environments have `nb_conda_kernels` in them)

**Comment by consideRatio** [comment]
Related to this, is that it could be good knowing about pip's --user flag and condas --prefix flag.

I think using `pip install --quiet --user <package name>` and `conda install --yes --prefix "~/.local" <package name>` will allow the things installed to be available to the user without further setup even after restarting of the container assuming the home directory is persistent.

DISCLAIMER: Currently I don't grasp what condas --prefix flag does, other than I achieved my wish which was to make my users able to one-line install some additional requirement and not have to do it over and over again.

**Comment by rsignell-usgs** [comment]
You can tell conda where to store you custom envs by specifying in `.condarc` thusly:
```
channels:
  - conda-forge
  - defaults
envs_dirs:
  - /home/jovyan/my-conda-envs/
```
check:
```
conda info -e
```
returns
```
# conda environments:
#
h5pyd                    /home/jovyan/my-conda-envs/h5pyd
root                  *  /opt/conda
```

**Comment by choldgraf** [comment]
@mrocklin @rsignell-usgs is this now figured out? And if so, do you have suggestions for where in the documentation we could mention this? I think this may become more common as more people begin to use jlab

**Comment by mrocklin** [comment]
I think that there were two main take-aways

1.  Install `nb_conda_kernels` in the root environment
2.  Decide if you want to install conda packages into user space or not

However I'm not sure that I ever actually got this to work.  @rsignell-usgs is more experienced here.

**Comment by rsignell-usgs** [comment]
IMHO, you can close.   I can create custom conda environments that persist, and also show up in JupterLab so that I can choose specific environments needed by specific notebooks.

**Comment by choldgraf** [comment]
sounds good @rsignell-usgs ... and the solution was to do step 1 from @mrocklin 's post above, and then to specify `evns_dirs`?

**Comment by rsignell-usgs** [comment]
Yes.  And make sure you have `nb_conda_kernels` in each of your custom envs as well.

**Comment by choldgraf** [comment]
cool - thanks for the clarification! Closing now.

**Comment by aurashn** [comment]
@rsignell-usgs how did you add nb_conda_kernels to the root environment? Did you build a new image for your jupyterhub?

**Comment by rsignell-usgs** [comment]
Yes

**Comment by rosenta** [comment]
hi @rsignell-usgs,
I tried steps as mentioned,

- like created docker image with `nb_conda_kernels` Installed through root user
- created `~/.condarc` file with custom env location in persistent storage (home directory)
- created test env with command `conda create -n tenv --yes nb_conda_kernels` (with `nb_conda_kernels` installed for that custom user)

but still, unable to see my custom env `tenv` listed on kernels list. I also restarted notebook, but no luck with tenv in kernel list.
perhaps, I can see and activate custom environment `tenv` via terminal
 `conda info -e`
 results in 
```
 # conda environments:
#
tenv                     /home/jovyan/my-conda-envs/tenv
base                  *  /opt/conda
 ```
<img width="897" alt="Screenshot 2021-02-15 at 7 07 13 PM" src="https://user-images.githubusercontent.com/25467054/107953506-3d22e380-6fc1-11eb-8441-afad24e6f9cf.png">

can you help me with, what possibly could've went wrong?

**Comment by consideRatio** [comment]
@rosenta can you open a post on discourse.jupyter.org about this instead of here? It is out of scope for this github repo.

**Comment by rosenta** [comment]
ohh.  sure. thanks @consideRatio

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/how-to-enable-users-to-create-custom-environments-and-use-them-as-notebooks/7957/1

**Comment by rosenta** [comment]
seems like I missed installing ipykernel on custom environment but after running below command to create environments, it solved my problem,

`conda create -n tenv --yes python=3.8 ipykernel nb_conda_kernels`

so updated steps should be:

- created docker image with `nb_conda_kernels` and `ipykernel` Installed through root user
- created `~/.condarc` file with custom env location in persistent storage (home directory)
- created test env with command `conda create -n tenv --yes python=3.8 ipykernel nb_conda_kernels` (with `nb_conda_kernels` and `ipykernel` installed for that custom user)
- after few seconds, one should be able to see environments in kernels list
