### ISSUE TITLE
Document how to let users create / activate custom conda environments

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/zero-to-jupyterhub-k8s#414]
From https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/393 we figured out how to allow this. We should document this (maybe just in `FAQ`?) somewhere. This comment and the couple below it show the magic incantation to make this happen:

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/393#issuecomment-358108096

**Comment by yuvipanda** [comment]
It mostly looks like a conda specific thing. Is that right? 

I think we should definitely have an entire page (or more!) on constructing your docker image, and the various options you have for it (repo2docker, conda, virtualenv, pyenv, rocker, etc)
