### ISSUE TITLE
Add info about using SSDs on AKS 

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/zero-to-jupyterhub-k8s#420]
Currently we only tell people how to use SSDs on Google Cloud, we should also explain to them how to do it on Azure.

It's more complicated because the type of instance you use when creating the AKS cluster has a bearing on wether you can use SSDs or not, and the naming scheme for the 'type of instance' is super confusing!

This should be an addition here: https://zero-to-jupyterhub.readthedocs.io/en/latest/user-storage.html#google-cloud

**Comment by choldgraf** [comment]
added a link to the TLC so folks know where to add it.

**Comment by consideRatio** [comment]
The ambition of explaining how to do this on Azure, Amazon and Google is quite high since a lot of these things changes quickly - still worth to strive for this?

**Comment by consideRatio** [comment]
I think we've have learned more about what makes sense to have documented as part of z2jh over time. I now consider it unsustainable and out of scope to write about this in this detail for z2jh. To mention it is possible to configure the default storage type using a k8s storageClass makes some sense to me, as well as linking to kubernetes official docs, but not more than that for a maintenance perspective of z2jh.
