### ISSUE TITLE
Include a clipboard icon with code blocks

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/zero-to-jupyterhub-k8s#427]
It'd be really nifty if we could let users click on a button within code blocks and have it copy the text to their clipboard. I looked into it a little bit and I think it'd be possible with a bit of Jinja magic. I think we could:

1. Use [`clipboard.js`](https://clipboardjs.com/) to do the clip magic w/

`<script src="https://cdn.jsdelivr.net/npm/clipboard@1/dist/clipboard.min.js"></script>`

2. Link that script and run 

`<script>new Clipboard('clipboard');</script>`

at the beginning of each page.

3. Figure out the CSS to make the clipboard show up upon hover (maybe with https://github.com/primer/primer/tree/master/modules/primer-tooltips ? That's what the [clipboard home page](https://clipboardjs.com/) uses and it looks nice )

4. Somehow add an ID to each `div.highlight span` block so that we know which span block each clipboard button should point to.

I tried figuring this out but got bogged down in the jinja swamp...anybody see the list above and see a clear-ish path forward to implementing this? If so, we could update both the z2jh and binderhub docs.

Maybe @Carreau ?

Also got some inspiration from this SO post: https://stackoverflow.com/questions/39187220/how-to-add-a-copy-button-in-the-code-blocks-for-rst-read-the-docs

**Comment by consideRatio** [comment]
We have such buttons now =D Someone added a plugin to sphinx if i recall correctly, but forgot whom it was! 

Anyhow forgotten contributor...

![image](https://user-images.githubusercontent.com/3837114/45003113-2057e880-afdf-11e8-9f5d-144d6ab4cc0f.png)
