### ISSUE TITLE
singleuser.cmd does not support using array syntax

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/zero-to-jupyterhub-k8s#431]
It only supports string syntax for specifying values ("start.sh start-singleuser.sh") rather than array syntax (["start.sh", "singleuser.sh"]). It should support both.

**Comment by consideRatio** [comment]
This remains in 0.7.0, right?

@yuvipanda would you still think this is something we should support? Does it solve an issue that could arise?

**Actionplan:**
See where `singleuser.yaml` is referenced, probably in templates/hub/configmap.yaml. We need to ensure we can pass through an array as well as string here somehow. Step one for the template logic would be to verify what case we have, then to act on it in configmap.yaml and how to parse it in jupyterhub_config.py later when the value in configmap.yaml is consumed.

**Comment by metonymic-smokey** [comment]
@yuvipanda @consideRatio is this issue still open? Looking for an easy coding PR to start with in Z2JH.

Thanks!

**Comment by metonymic-smokey** [comment]
@yuvipanda could I work on this issue if it's still up for grabs? Looking for easy coding PRs in Z2JH.

Thanks!

**Comment by consideRatio** [comment]
Z2JH does not manipulate this part, it just sets `c.Spawner.cmd` with the value passed as either string or a list I believe, but, it seems that KubeSpawner overrides this configuration, as can be seen [here](https://github.com/jupyterhub/kubespawner/blob/defdd275aab673942bb3407ef254f9ba94cf71f6/kubespawner/spawner.py#L282), but also JupyterHub's Spawner base class supports it, as can be seen [here](https://github.com/jupyterhub/jupyterhub/blob/032ae2906610b81bfce700bbbfd4291014d81319/jupyterhub/spawner.py#L477).

Closing as resolved.
