### ISSUE TITLE
Add imagePullSecrets

### ISSUE THREAD

**Issue by ZachGlassman** [jupyterhub/zero-to-jupyterhub-k8s#447]
It might be useful to add in `imagePullSecrets` to the base templates so that images can be pulled from private docker repositories.

**Comment by yuvipanda** [comment]
I think the easiest way to do this would be support a default serviceaccount that all user pods are attached to, and set this imagePullSecret on it!

**Comment by ablekh** [comment]
What is the process for secrets for pre-0.7 releases, specifically, for 0.6? In my latest version of our pilot deployment (AKS-based), I'm pulling a custom image from a private Azure CR. I don't remember creating secrets, though. Please advise.

**Comment by consideRatio** [comment]
I'll look into how this can be done, I need to learn some more stuff though. Will aim towards augmenting the namespace's default ServiceAccount with an ImagePullSecret

**Comment by ablekh** [comment]
@consideRatio Thank you. I was struggling most of the night :-( with inability of my AKS cluster to pull a custom single-user server image (which I have pushed to ACR earlier). I was under impression that a simple authentication with ACR is enough (`az acr login`) as long as I use the same terminal session where I authenticated with Azure (`az login`). However, I have recently discovered [this document](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-auth-aks) and tried to apply the first part ("Grant AKS access to ACR") to my environment. However, it doesn't seem to help. Perhaps, I should try the second approach ("Access with Kubernetes secret"), hence my original comment/question.

Other notes:
- since my custom image is large (~6 GB), I used `--timeout=10000000` in `helm install` command
- I stopped the `helm install` process and tried to delete all pods in my cluster at approx. the same time
- I tried to troubleshoot the situation and here are some bits from the relevant logs:

```
ablekh@Control-VM:~/sbdh_jh_v3$ kubectl --namespace=sbdh-jh-v3 get pods
NAME                                       READY     STATUS                  RESTARTS   AGE
pre-pull-sbdh-jh-v3-1-1525424256-kk58m     0/1       Init:ImagePullBackOff   0          25m
pre-pull-sbdh-jh-v3-1-1525424942-2p4kx     0/1       Init:ImagePullBackOff   0          25m
pre-pull-sbdh-jh-v3-1-1525428469-5bqkl     0/1       Init:ImagePullBackOff   0          25m
pre-pull-sbdh-jh-v3-1-1525431462-8q5t6     0/1       Init:ImagePullBackOff   0          25m
pre-pull-sbdh-jh-v3-1-1525432213-xt992     0/1       Init:ImagePullBackOff   0          25m
pre-pull-sbdh-jh-v3-1-1525436735-82hvf     0/1       Init:ImagePullBackOff   0          24m
pre-pull-sbdh-jh-v3-1-1525436817-5zt7t     0/1       Init:ImagePullBackOff   0          24m
pre-puller-1525424256-sbdh-jh-v3-1-btp2v   1/1       Running                 0          25m
pre-puller-1525424942-sbdh-jh-v3-1-6vtv2   1/1       Running                 0          25m
pre-puller-1525428469-sbdh-jh-v3-1-prqr4   1/1       Running                 0          25m
pre-puller-1525431462-sbdh-jh-v3-1-ntfb7   1/1       Running                 0          25m
pre-puller-1525432213-sbdh-jh-v3-1-85784   1/1       Running                 0          25m
pre-puller-1525436735-sbdh-jh-v3-1-xb4wn   1/1       Running                 0          25m
pre-puller-1525436817-sbdh-jh-v3-1-nmt2v   1/1       Running                 0          24m
```
```
ablekh@Control-VM:~/sbdh_jh_v3$ kubectl --namespace=sbdh-jh-v3 describe pod pre-pull-sbdh-jh-v3-1-1525424256-kk58m
Name:           pre-pull-sbdh-jh-v3-1-1525424256-kk58m
Namespace:      sbdh-jh-v3
Node:           aks-nodepool1-40307772-0/10.240.0.4
Start Time:     Fri, 04 May 2018 12:25:59 +0000
Labels:         app=jupyterhub
                component=image-puller
                controller-revision-hash=1906146924
                heritage=Tiller
                pod-template-generation=1
                release=sbdh-jh-v3
Annotations:    <none>
Status:         Pending
IP:             10.244.0.50
Controlled By:  DaemonSet/pre-pull-sbdh-jh-v3-1-1525424256
Init Containers:
  image-pull-singleuser:
    Container ID:
    Image:         sbdh1.azurecr.io/datascience-octave-notebook:v1
    Image ID:
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
      -c
      echo "Pulling complete"
    State:          Waiting
      Reason:       ImagePullBackOff
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:         <none>
  image-pull-metadata-block:
    Container ID:
    Image:         jupyterhub/k8s-network-tools:v0.6
    Image ID:
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
      -c
      echo "Pulling complete"
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:         <none>
Containers:
  pause:
    Container ID:
    Image:          gcr.io/google_containers/pause:3.0
    Image ID:
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:         <none>
Conditions:
  Type           Status
  Initialized    False
  Ready          False
Volumes:         <none>
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/disk-pressure:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute
                 node.kubernetes.io/unreachable:NoExecute
Events:
  Type     Reason   Age                From                               Message
  ----     ------   ----               ----                               -------
  Warning  Failed   12m                kubelet, aks-nodepool1-40307772-0  Failed to pull image "sbdh1.azurecr.io/datascience-octave-notebook:v1": rpc error: code = Canceled desc = context canceled
  Warning  Failed   12m                kubelet, aks-nodepool1-40307772-0  Error: ErrImagePull
  Normal   BackOff  12m                kubelet, aks-nodepool1-40307772-0  Back-off pulling image "sbdh1.azurecr.io/datascience-octave-notebook:v1"
  Warning  Failed   12m                kubelet, aks-nodepool1-40307772-0  Error: ImagePullBackOff
  Normal   Pulling  12m (x2 over 25m)  kubelet, aks-nodepool1-40307772-0  pulling image "sbdh1.azurecr.io/datascience-octave-notebook:v1"
```
```
ablekh@Control-VM:~/sbdh_jh_v3$ kubectl --namespace=sbdh-jh-v3 logs pre-pull-sbdh-jh-v3-1-1525424256-kk58m
Error from server (BadRequest): container "pause" in pod "pre-pull-sbdh-jh-v3-1-1525424256-kk58m" is waiting to start: PodInitializing
```

**Comment by ablekh** [comment]
@ZachGlassman Thank you very much for your advice. Between which _z2jh_ steps these two commands should be executed? What version you refer to in the phrase "newer version of jupyterhub"? We currently use K8s v1.9.6 (AKS), Helm chart v0.6 and JupyterHub v0.8.

**Comment by ZachGlassman** [comment]
I think having a new service account for the `imagePullSecrets` is a great idea and cleaner than using the default service account for the namespace.  My worry is about mounting any service account onto the singleuser pods. These pods have the ability to execute arbitrary bash commands and its pretty easy with misconfigured service accounts to give all your users extensive permissions.

**Comment by consideRatio** [comment]
@ZachGlassman oh my current understanding (just my idea, not based on k8s documentation) is that a ServiceAccount does nothing until you couple it with permissions, and that all pods will have a ServiceAccount coupled with them, the default if it isn't a custom one specified. With that said, providing a custom ServiceAccount to a pod doesn't escalate anything as compared to using the default ServiceAccount. But if we want, perhaps we could isolate the singleuserpods from having a ServiceAccount with the imagePullerSecret field at all, by pulling only on the pre-puller pods, but I think we might run into issues doing this, and I'm not confident it would be helpful.

**Comment by consideRatio** [comment]
@ZachGlassman I'll read up on [Service Account Tokens](https://kubernetes.io/docs/admin/authentication/#service-account-tokens), I know I lack some understanding here that may be relevant.

**Comment by ZachGlassman** [comment]
@consideRatio I think your understanding is correct, however, there are many cases of people creating `clusterrolebinding` which gives effectively all serviceaccounts admin access.  

My understanding of the default zjh settings are that they do not mount a service account on the singleuser pods, see https://github.com/jupyterhub/kubespawner/blob/master/kubespawner/spawner.py#L181

**Comment by consideRatio** [comment]
@ZachGlassman hmmm regarding the ClusterRoleBinding people create. I for example have created such a ClusterRoleBinding, but not to the default ServiceAccount but to my User account rather than to the default ServiceAccount ([Reference: User accounts vs. ServiceAccounts](https://kubernetes.io/docs/admin/service-accounts-admin/)? I did this when I followed [step 7 in the z2jh guide for the GCP cluster setup](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/doc/source/google/step-zero-gcp.rst).

Regarding the kubespawner: Oh... I wonder if that is malfunctioning for me then, I don't think I specify a `singleuser_service_account` on the kubespawner? It seems that the security crux is giving access to the kubernetes API server by mounting a Service Account Token. This token mounting will not be done if specified on the pod it should not be done, or it can fallback to the ServiceAccount's setting. I remember reading this recently, but can't find the text stating this any more.

Related: the kubespawners implementation relating to the `singleuser_service_account` setting.
https://github.com/jupyterhub/kubespawner/blob/cc658f4b289cdd0a658113bfa4fbd6aa741d3b90/kubespawner/objects.py#L184-L206

**Comment by consideRatio** [comment]
@ablekh and @ZachGlassman! Thank you for discussing this with me, I've spent a lot of time as a programmer working on projects alone. Not working alone on this but instead getting a lot of input from you is awesome and I learn a lot thanks to it! :heart:

![happy_7a8505_531184](https://user-images.githubusercontent.com/3837114/39657606-c85da488-5009-11e8-8569-2ba7b61ee0c6.gif)

I'll get some sleep now! Good night!

**Comment by ablekh** [comment]
@gsemet Could you clarify how exactly you have used extraconfig to interact with your registry? As I described in #676 (see for details), I used the following entry in my `config.yaml`, but it it did not work.
```
  extraConfig:
    c.KubeSpawner.singleuser_image_pull_secrets = "ACR_SECRET_NAME"
```
P.S. ACR_SECRET_NAME is a value given in the following command, when setting up AKS access to ACR:

```
kubectl create secret docker-registry ACR_SECRET_NAME --docker-server <REGISTRY_URL> --docker-username <SERVICE_PRINCIPAL> --docker-password <PASSWORD> --docker-email <MY_EMAIL>
```

**Comment by gsemet** [comment]
Hi. I don’t know how AKS works, i just put the name of the secret that holds the pull secret for our docker registry (its a nexus or artifactory registry). Without this secret the spawner cannot connect to the registry (it holds the credentials)

**Comment by ablekh** [comment]
@gsemet Hi, thank you for quick reply. Yes, I realize why the secret is needed :-), but, it it definitely seems to be working somewhat differently on AKS. I have even just tried (after reading some issues on AKS repo) to reconfigure my setup to use _Contributor_ role for ACS (Azure Container Registry) instead of initial _Reader_, but it doesn't seem to be working (I will give it some time, though - perhaps, the effect is far from immediate, and I can get some sleep in the meantime ... I have done a lot tonight).

**Comment by ablekh** [comment]
@gsemet Just wanted to let you know that I finally have figured this out (it was a combination of factors, both JupyterHub-generic and Azure-specific). Thanks!

**Comment by consideRatio** [comment]
@AlexMorreale to the rescue! Alex have in https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/801 implemented what @ZachGlassman suggests in https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/447#issuecomment-386706464 !

It is now possible to have a config.yaml file like this...

```yaml
singleuser:
  image:
    name: ezcater-test.privatereg.docker/jupyterhub-user
    tag: latest
  imagePullSecret:
    registry: ezcater-test.privatereg.docker
    username: alex@test.com
    password: <redacted password>
```

I wonder though, do we need to add an email to this as well? This is suggested in [Kubernetes docs](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/) as well I think, but not in [Helm's tips and tricks section](https://github.com/helm/helm/blob/master/docs/charts_tips_and_tricks.md#creating-image-pull-secrets) on how to this (but perhaps out of date), and it also works for @AlexMorreale 

Ideas about the email part ?

**Comment by AlexMorreale** [comment]
hmmm good point. My private repo does not require an email(in fact my `username` is my email) but others might? maybe we make it an optional field?

**Comment by consideRatio** [comment]
Closing this with @AlexMorreale merged PR #801 and the unmerged #851 that adds some to it.

**Comment by dkipping** [comment]
@ablekh 
> Just wanted to let you know that I have finally figured this out (it was a combination of factors, both JupyterHub-generic and Azure-specific). Thanks!

How did you manage to pull own images out of ACR into single-user notebook server on jhub running on AKS in the end?
Also struggling with this at the moment, as simply adding the imagepullsecret information to my config.yaml does not seem to solve it

**Comment by consideRatio** [comment]
@dkipping, using a recent version of the helm chart, like `0.8-7b2b3cb` and specifying details like below should perhaps do the trick, it is at least meant to do the trick:

https://zero-to-jupyterhub-with-kubernetes.readthedocs.io/en/latest/reference.html#singleuser-imagepullsecret

If this does not resolve your troubles, feel free to create a new issue!

**Comment by ablekh** [comment]
@dkipping Hi! While @consideRatio is correct with the advice above, I can definitely see why things would go wrong, considering that the general - and good - advice is (Kubernetes-) generic. There are some Azure- or, rather, AKS-specific aspects that very well could negatively impact the process of pulling images from ACR. More specifically, I suggest you to pay close attention to the process of authentication with ACR (if needed, check logs from the relevant pod). Unfortunately, I don't remember exact combination of things I had to fix to get a working solution (as I have said above, it was a mix), but, if you can share relevant parts of your `config.yaml` and output from relevant `acr` commands (in YAML format), I will try to help further.

**Comment by dkipping** [comment]
@consideRatio ah thank you, I thought it would already be in the stable releases (i.e. 0.7.0).
Will try with the more recent version and report back.

@ablekh thank you very much for your readiness to help. I'll first give it another round and may come back to it afterwards

**Comment by ablekh** [comment]
@dkipping My pleasure and good luck. By the way, I believe that the advice above by @consideRatio applies as well to the current stable Helm release (v0.7.0), which is the one I'm currently using on AKS.

**Comment by dkipping** [comment]
Got it working by creating a new kubernetes cluster secret as described in the microsoft guide. I also set imagePullSecret.enabled in the config.yaml which I did not do before (seems to have had impact).
Before I also followed step 1 of the microsoft guide @ablekh already mentioned ([Grant AKS access to ACR](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-auth-aks)) but that alone did not work.
And yes, it already works with v0.7.0
Thank you both @consideRatio @ablekh

**Comment by ablekh** [comment]
@dkipping I'm happy to hear that you have figured it out. You're very welcome.

**Comment by yan-v** [comment]
Hello, I am also trying to pull image from harbor, but even setting imagePullSecret under the singleuser as describer above generates an error:  singleuser: Additional property imagePullSecret is not allowed.

Any help will highly appreciated!!!

**Comment by consideRatio** [comment]
Use image.pullSecrets, see z2jh.jupyter.org's configuration reference section and search for pullsecrets for more details!

**Comment by yan-v** [comment]
Hi @consideRatio ! thank you so much for your quick response!
I guess i have a problem because the access to our corporate registry is limited.
Will try to figure it out with our DevOps team.

Thank you,
Yan
