### ISSUE TITLE
How to keep same numeric IP?

### ISSUE THREAD

**Issue by AaronWatters** [jupyterhub/zero-to-jupyterhub-k8s#45]
Please document how to reinstall the software from scratch and keep the current numeric
IP address for the entry point.  This is important for programmers like me who are not allowed
to touch the DNS records but may need to restart the system with extreme prejudice.

**Comment by AaronWatters** [comment]
duplicate sorry

**Comment by aculich** [comment]
note this is a duplicate of #42 in case someone else ends up at this closed dupe.
