### ISSUE TITLE
pre-puller and network-tools have too new tags

### ISSUE THREAD

**Issue by ryanlovett** [jupyterhub/zero-to-jupyterhub-k8s#453]
The latest chart references image tags that do not yet exist. Even though pre-puller and network-tools were not touched during the last CI and so were not built, the tags in the chart are being set to the latest tag for the hub.

(@yuvipanda manually updated the latest images to make things work for me.)

**Comment by yuvipanda** [comment]
This is probably something related to flaky CI, will check.

**Comment by consideRatio** [comment]
I vaguely recall this and it being fixed, anyone with some recollection?

**Comment by manics** [comment]
Was this it?
- https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/612
- https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/621

**Comment by consideRatio** [comment]
I think you are right @manics!! Closing thanks for the backup! :heart:
