### ISSUE TITLE
Support multiple Docker builds?

### ISSUE THREAD

**Issue by AaronWatters** [jupyterhub/zero-to-jupyterhub-k8s#46]
It would be nice to be able to have a choice of several docker images to launch as is done in Docker.
This is probably in the plan since Binder-esque functionality is a goal...
At the moment I'm collecting a fair number of repositories, including some largish data sets
into a single image.  This will eventually break as things get larger.  I would rather not have a separate hub installation for each image, although that is a feasible option.

**Comment by yuvipanda** [comment]
This would need slightly better support for multiple images on kubespawner. I'll try to add it sometime this week

**Comment by consideRatio** [comment]
It is now possible to allow the chart maintainer to setup a choice of images. We should ensure we can support pre-pulling of multiple images better though.

See https://github.com/jupyterhub/kubespawner/pull/137 and https://github.com/jupyterhub/kubespawner/pull/192.
