### ISSUE TITLE
Find and fix performance issue in v0.6 that is spawning too many threads

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/zero-to-jupyterhub-k8s#461]
I was investigating https://github.com/jupyterhub/jupyterhub/issues/1636, and am now convinced there's a major performance regression in current v0.6 related to us spawning way too many threads.

On 0.6, the hub process is at 100+ CPU and 18929 threads. Latency is also through the roof.

On 0.5, the hub process is hardly at any CPU, and has 15 threads.

This needs careful investigation and fixing before we can release 0.6.

**Comment by choldgraf** [comment]
was going to say we should hold off on v0.6 until this is fixed...but it looks like it's already solved once kubespawner gets bumped?
