### ISSUE TITLE
These are the skills you'll need" section

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/zero-to-jupyterhub-k8s#479]
* "
    * Contains information about the general skills that will be needed to do various things in the JupyterHub world.
    * Possibly with links to other pages w/ more information. Maybe under "Reference"?

**Comment by consideRatio** [comment]
"General skills" ? I'm thinking technical skills about for example docker, kubernetes, etc. I have had to learn so much! :D

Hmmm, things to spend time learning about and how to do it
- Python, Docker, YAML, Kubernetes, Helm, Jupyter/JupyterHub, Kubespawner, 

---

Essential: this repos superguide
Docker: A small course + YouTube videos etc...
YAML: Look at a youtube video
Kubernetes: Read through almost all "concepts", YouTube - jupytercon / kubecon
Helm: Read through almost all the documentation - YouTube - kubecon
Jupyter: YouTube, blogs etc
JupyterHub: YouTube
