### ISSUE TITLE
Add a note about getting at least helm version 2.4.1

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/zero-to-jupyterhub-k8s#48]
On kubernetes 1.6.x clusters, it is needed to avoid https://github.com/jupyterhub/helm-chart/issues/4

**Comment by willingc** [comment]
@yuvipanda Since https://github.com/jupyterhub/helm-chart/issues/7 has landed, what guidance do we want to provide in the Install Helm section re: version.
