### ISSUE TITLE
"These are the skills you'll need" section in docs

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/zero-to-jupyterhub-k8s#480]
There are many different kinds of skills useful/needed for working with JupyterHub. It'd be helpful if we gave readers some idea for what these skills are, and links to other documentation for more information on them.

Different kinds of people we could design this around:

* People who wish to deploy their own short-term jupyterhub
* People who wish to run a longer-term jupyterhub

We whiteboarded a couple of ideas:

![](https://user-images.githubusercontent.com/1839645/35761906-4a1df5c2-0843-11e8-82ff-64a4c817ac57.png)

**Comment by ryanlovett** [comment]
systemd (init) and environment issues (e.g. PATH) come up a lot on the jupyter mailing list.

**Comment by yuvipanda** [comment]
@ryanlovett I agree with environment issues! But for at least kubernetes, you do not need systemd anywhere.

**Comment by yuvipanda** [comment]
That's a great set of links, @consideRatio!

**Comment by jzf2101** [comment]
I think we can close for now
