### ISSUE TITLE
Moving the side-bar search to the top

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/zero-to-jupyterhub-k8s#482]
Right now the search bar gets lost if there are lots of sub-sections on the page...e.g.:

![2018-02-05_17-39-34](https://user-images.githubusercontent.com/1839645/35837529-872975e0-0a9b-11e8-94a3-183204a99b06.gif)

I find the search bar quite useful, and it's easy to miss when it's buried like that. Could we move it to the top of the TOC so that it's always visible at the top? What do you think @willingc ?

**Comment by willingc** [comment]
Sure. I might even consider having it at the top and the bottom if the contents are long. @choldgraf

**Comment by choldgraf** [comment]
oo cool idea, LMK make a quick PR to prototype it and we can see how it feels

**Comment by choldgraf** [comment]
huh - I actually can't get the search bar to show up twice...if I copy/paste to the top of the sidebar, then it only shows up on top and not the bottom

**Comment by willingc** [comment]
Move it to the top for now and if folks ask we can investigate both. 👍
