### ISSUE TITLE
Improving the authentication section

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/zero-to-jupyterhub-k8s#483]
- [x] Google Oauth Example - shorten it and link out to other oauth documentation instead of treating google special here.
- [ ] Move authentication section from administrator to the customization section under "user management"
- [ ] Give a better overview of "how documentation works" in general, and make sure we list all possible authenticators. Give an example for one and make sure it's generalizable to the others.
- [ ] Include docs to suggest what to do if people want to use a different authenticator (maybe this just says "we don't support that" but it'd be useful)

**Comment by consideRatio** [comment]
This section has not been reviewed for a long time, I'd love to see it refreshed for 0.8

**Comment by consideRatio** [comment]
@choldgraf should we make a push for this before 0.8 release or let it be as it is?

**Comment by choldgraf** [comment]
IMO we should leave the issue open, but tag it for the next version if we're ready to go on all other fronts. I'm generally +1 on having releases more often anyway, so don't wanna block something if it's close :-)

(sorry for the slow response on this one - I've been in holiday mode!)

**Comment by consideRatio** [comment]
I'll reference this issue from another, trying to triage 300 issues down to a more manageable size!
