### ISSUE TITLE
For Documentation: auto-cutoff? and consequences?

### ISSUE THREAD

**Issue by spmcginnis** [jupyterhub/zero-to-jupyterhub-k8s#49]
In the [documentation](https://zero-to-jupyterhub-with-kubernetes.readthedocs.io/en/latest/create-k8s-cluster.html), it would be helpful to have information about whether one can put an automatic limit on how much their cloud account can be billed.  Also, if that feature is available, what would the consequences be?  What would happen to the system when the shutoff is triggered?

**Comment by willingc** [comment]
Hi @spmcginnis, Good suggestion. If you have the info, pull requests are welcomed :sunny:
