### ISSUE TITLE
repo2docker no longer installs jupyterhub

### ISSUE THREAD

**Issue by minrk** [jupyterhub/zero-to-jupyterhub-k8s#490]
User environment instructions [recommend using repo2docker](http://zero-to-jupyterhub.readthedocs.io/en/v0.6/user-environment.html#build-a-custom-docker-image-with-repo2docker) to build the user image, but repo2docker no longer installs jupyterhub automatically. Updating the example to install jupyterhub explicitly should make it work again.

**Comment by choldgraf** [comment]
There will hopefully be a dockerfile overhaul soon, so this should definitely be a part of it

**Comment by consideRatio** [comment]
I have removed the repo2docker reference, see #484.
