### ISSUE TITLE
JupyterCon Tutorial [CFP due March 6]

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/zero-to-jupyterhub-k8s#491]
I think we should propose a tutorial at JupyterCon *just* for zero to jupyterhub (rather than general JupyterHub deployments). I've given this a few times and it goes pretty well!

**Comment by yuvipanda** [comment]
I put this in the wrong thread (#492), but @consideRatio is interested in being part of the team that's giving a z2jh tutorial :)

Who else is interested in being part of it? @choldgraf @minrk @willingc?

**Comment by choldgraf** [comment]
I'm definitely interested in helping out - still unsure about travel/timing/whether I'll be able to make it since I've got a wedding in France for the week after JupyterCon, but I'll figure that out in the coming month or two...

**Comment by consideRatio** [comment]
Hey! I was swamped with teacher stuff this week, but I'm almost back on track now. I meant to follow up on this thread a lot sooner.

@yuvipanda I bet a few will get it and become enthusiastic about setting up a jupyterhub on k8s, but also that they might end up needing to do it without proper initial support from within their organisation. I imagine you can relate to doing things you believe in.

It would make me really happy if we could help the enthusiastic people aiming to setup a z2jh-k8s hub to gain support from within their organisation. I didn't manage to convey the potential impact properly within my organisation properly and wasn't funded to spend time doing it, but I have learned a lot since then about the impact a JupyterHub can have for both me as a teacher and for my students. It would be fun to communicate about this!

By the way, I'm currently imagining a format similar to the ["Managing a 1,000+ Student JupyterHub..."](https://www.youtube.com/watch?v=ivswAxysfTk) presentation. @yuvipanda Is this the format you have in mind or something else, perhaps like a workshop?

**Comment by willingc** [comment]
Sounds great. I'm in.

**Comment by choldgraf** [comment]
I like @consideRatio 's take on this , +1!

**Comment by consideRatio** [comment]
Perhaps something like this?

## Coarse outline of the talk
### Envision (1/4)
- Summary of potential for teachers, students and researchers
- Listeners get to envision the benefits

### Empower (2/4)
- Tutorial to utilize the z2jh guide, going from zero all the way
- Listeners get to feel empowered

### Support (1/4)
- Listeners get to ask questions
- Listeners could perhaps sign up in some way, we could try start building a community of users

**Comment by consideRatio** [comment]
## Researching notes - JupyterCon 2018
So I'm new on conference participation, so I made some research. Two formats exist, 40 minute talks and 3 hour tutorials.

### Resources
- [Proposal tips](https://conferences.oreilly.com/jupyter/jup-ny/public/cfp/621#tips)
- [Proposal samples](http://www.oreilly.com/conferences/sample_proposals.html)

@willingc @yuvipanda @choldgraf 
- What kind of participation would you like? A 40 min talk vs 3 hour workshop?
- Is the JupyterCon 2017 proposal still around and could I read it?
- I decided I'd make this happen no matter what economically, but perhaps funding is available? How you are planning on funding your trip, accommodation and eventual conference fees? I'm acting as a private person. I'm working for a school with about 350 students, but they have not funded my work on this so far.

### TODO
- [ ] Decide on 40 min talk / 3 hour tutorial
- [ ] Submit proposal - Deadline 11:59 pm EST on March 6.

**Comment by yuvipanda** [comment]
@consideRatio I think this one is specifically for the 3hour tutorial. https://conferences.oreilly.com/jupyter/jup-ny-2017/public/schedule/detail/60075 is from last year. I think last year it was two parts, one was setting up JupyterHub from scratch and another was setting it up with just z2jh. I think this year, we should just do z2jh in the tutorial (unless others object!)

**Comment by consideRatio** [comment]
Ah woo now pieces are falling into place in my mind, I figured there would be only one of something up until now. Awesome do both! =)

One "talk" (40min) and one "tutorial" (3h) is planned, and I'll participate in giving this tutorial!

**Comment by minrk** [comment]
I'm happy to help on this tutorial. I can help on the talk as well. I agree that we should only do the z2jh tutorial and skip manual jupyterhub. Conference wifi was extremely untrustworthy last time, so we shouldn't expect people to be able to download and run *anything* on their laptops during the tutorial.

Just so things don't fall through the cracks, who is planning to submit this one?

**Comment by consideRatio** [comment]
@minrk Awesome!!! =D

I'd certainly appreciate someone else doing it, but I figure we all think like this. I'll make it happen, all help appreciated though. I figure I start by making it easier for us to collaborate about this.

I put up [a HackMD document](https://hackmd.io/r4sKE_mwSm6qu1MGZfWVUQ) with topics of the fields we need to fill about the workshop.

**Comment by consideRatio** [comment]
@choldgraf made a summary regarding previous workshop experiences and material used in #558 !

**Comment by consideRatio** [comment]
@minrk @willingc I did my best to populate the required proposal submission fields but there are quite a bit more to write and perhaps even a short video to produce. If you have time to spare, I'd appreciate if you could review what I've written so far and perhaps even write something in the abstract or similar. I marked the various topics with (HELP), (REVIEW) and (DONE) to indicate some kind of state.

I'll get back to work on this tomorrow evening (I'm in GMT+1), good evening to you, for me it is time to sleep :)

**Comment by willingc** [comment]
@consideRatio Thanks! I'll take a look in the morning. I'm happy to fill in any spots.

Please don't worry about a video since O'Reilly is  familiar with me and Min as speakers.

**Comment by consideRatio** [comment]
@willingc thank you!!
