### ISSUE TITLE
Spin off advanced dockerfile configuration from "customizing your environment"

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/zero-to-jupyterhub-k8s#498]
"Customizing your environment" could be split into two pages: one specifically on creating a minimal Dockerfile that will work with JupyterHub, another that covers more advanced cases (e.g. JupyterLab, pre-populating, etc)

**Comment by willingc** [comment]
Related to #499

**Comment by consideRatio** [comment]
There are many issues relating to these, closing and gathering them. We currently have an relatively easy section now consisting of selection of a pre-built docker image in docker-stacks. Also some notes about how an extension should look.
