### ISSUE TITLE
Factor out advanced dockerfiles in "customizing your environment"

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/zero-to-jupyterhub-k8s#499]
[Customizing your environment](https://zero-to-jupyterhub.readthedocs.io/en/latest/user-environment.html) should have general "minimum viable product" kinds of information on customizing the user environment. As we improve the instructions around `Dockerfile`s, we should split this off into it's own page that covers more advanced cases (e.g. JupyterLab, pre-populating, etc)

**Comment by consideRatio** [comment]
I agree, resolved. There are many issues relating to these, closing and gathering them.
