### ISSUE TITLE
Fix branch builds for this repo

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/zero-to-jupyterhub-k8s#500]
Currently, if you push to a branch in this repo, Travis fails.

We should fix this!

**Comment by willingc** [comment]
@yuvipanda Do you think the latest addition of chartpress and the changes to `.travis.yml` fix this?

**Comment by consideRatio** [comment]
It could be useful for me to test #758 by pushing to a branch, but I need to learn to use chartpress and try this out myself manually still so not I'll survive without it.

@willingc @yuvipanda - got an idea of the current status?

**Comment by consideRatio** [comment]
We currently end up with two builds on travis running, this is not the correct behavior i figure.

**Comment by betatim** [comment]
Why not recommend against having private branches in this repository? We operate via PRs for all change so people have their own fork already and can do what they like there.

My preference for this is part "keeping the master repository tidy" and "only special people can make branches here and I don't like having special people".

**Comment by betatim** [comment]
-> close this issue? Or is there a GitHub setting we can use to enforce this?

**Comment by willingc** [comment]
I don't think that GitHub offers a straightforward way to prevent new branch creation. I'm going to close.
