### ISSUE TITLE
Dependency on K8s 1.9

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#507]
I'd like to use [a Kubernetes API - /apis/apps/v1/namespaces/{namespace}/daemonsets/{name}/status](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.9/#read-status-18) in the pre-puller code released as core within k8s 1.9.

Should we maintain compability or can we ask users to upgrade to k8s 1.9?

**Comment by yuvipanda** [comment]
I think right now, we need to keep supporting 1.8. The URLs that work in 1.8 continue to work in 1.9 too, so we could just keep doing what we're doing now.

We do need an official policy on what we support and when though...

**Comment by consideRatio** [comment]
I found I could use a k8s 1.8 API in beta doing the same thing instead of the k8s 1.9 API, and the beta API will still be available in 1.9 so that's all good now.

I'm closing this and opening an issue about supported versions.
