### ISSUE TITLE
Re-test with google cloud shell

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/zero-to-jupyterhub-k8s#52]
I think with helm 2.4.1 the issues we were running into earlier with the web based terminal might be gone. Verify and then re-insert those instructions.

/cc @choldgraf

**Comment by yuvipanda** [comment]
I tested this with @Carreau just now. It seems to work :) Need to make sure to run get-credentials before doing any helming.

**Comment by Carreau** [comment]
for me: 
```
gcloud container clusters get-credentials <NAMESPACE> --zone=<ZONE>`
```

**Comment by willingc** [comment]
@yuvipanda @Carreau Can this be closed?

**Comment by yuvipanda** [comment]
I think we re-tested it and it works great. We should switch our documentation to refer to google cloud shell now. Not sure if we should repurpose this issue or make a new one.

**Comment by yuvipanda** [comment]
@choldgraf do you think you've time to give this a shot?

**Comment by choldgraf** [comment]
yeah I'll get to it after this data carpentry hackathon

**Comment by yuvipanda** [comment]
There's also https://docs.microsoft.com/en-us/azure/cloud-shell/overview for Azure, which we should also test and offer as an option!

**Comment by willingc** [comment]
Let's finish up that last bit of #433 and then test :-)

**Comment by choldgraf** [comment]
@willingc #433 was the result of me testing this out with the cloud shell, so I can provide at least one confirmation that it does work with those instructions :-)

**Comment by yuvipanda** [comment]
Can this be closed now or do we want one other person to also test?

**Comment by choldgraf** [comment]
IMO we'll get plenty of in-the-wild tests from users in the future, so I'm +1 on closing but will defer

**Comment by willingc** [comment]
Thanks folks :-)
