### ISSUE TITLE
Enable continuous pre-puller by default

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#526]
Continuous image pulling, should we have it enabled by default? I have a hard time imagining someone being upset about minuscule resources lost by a pause container on their fixed amount of nodes.

The main reason for not enabling it afaik is the added complexity, but since the pre-puller hook is enabled by default I don't think it is a big stretch as they rely on the same technique.

**Comment by yuvipanda** [comment]
There's a 100 pod limit by default per node, and enabling the continuous pre-puller eats into that. So at least for now, I don't think we should enable it by default.  We should have better autoscaling docs tho!

I'm going to close this for now, do re-open if you think that's an inadequete answer!

**Comment by consideRatio** [comment]
Makes sense @yuvipanda ! Also one less mechanism that can cause bugs.
