### ISSUE TITLE
Kubernetes dashboards returning

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#529]
# Returning kubernetes dashboard
[In the guide it sais](https://zero-to-jupyterhub.readthedocs.io/en/latest/security.html#delete-the-kubernetes-dashboard) that one could remove the kubernetes dashboard for increased security, but it apparently is a temporary fix as it is returning every time I run a helm upgrade.

```
# 1. Deleting it...
kubectl --namespace=kube-system delete deployment kubernetes-dashboard

# 2. Running a helm upgrade
# ...

# 3. It is back
kubectl --namespace=kube-system describe deployment kubernetes-dashboard
# ... see the output in the end
```

__Report 1__
```
# Got to be related to this configmap I found...
kubectl get configmaps --namespace kube-system
# ...

kubectl edit configmaps --namespace kube-system kubernetes-dashboard-settings
```
![image](https://user-images.githubusercontent.com/3837114/36577699-20c41fc8-1859-11e8-8244-20f14157df29.png)

Googling got me this [documentation about the addon-manager](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/addon-manager/README.md). It seems I need to learn more about the master node and manifest files (.yaml describing k8s objects... ?) on it.

__Report 2__

I deleted the configmap, ran a helm upgrade, and found that the configmap was back, and that that removing the configmap now furiously ensures that the configmap exists even without requiring me to run a `helm deploy`. It probably has to do with me using Kubernetes 1.9.2 now but the previous configmap was created earlier with an older version, I think. In other words, the deletion of the deployment is currently pointless afaik.

I have learned that you can run `kubectl cluster-info` to get some info about the kubernetes master node. I have not figured out how to `ssh` into it and delete the manifest though.

__TODO__
- [ ] Figure out how to delete that manifest file on the kubernetes master node

__Resources__
- [github.com/kubernetes/dashboard](https://github.com/kubernetes/dashboard)
- [github.com/kubernetes/dashboard/wiki](https://github.com/kubernetes/dashboard/wiki)

---

__`kubectl cluster-info`__
```
Kubernetes master is running at https://xxx.xxx.xxx.xxx
GLBCDefaultBackend is running at https://xxx.xxx.xxx.xxx/api/v1/namespaces/kube-system/services/default-http-backend:http/proxy
Heapster is running at https://xxx.xxx.xxx.xxx/api/v1/namespaces/kube-system/services/heapster/proxy
KubeDNS is running at https://xxx.xxx.xxx.xxx/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
kubernetes-dashboard is running at https://xxx.xxx.xxx.xxx/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy
Metrics-server is running at https://xxx.xxx.xxx.xxx/api/v1/namespaces/kube-system/services/https:metrics-server:/proxy
```

---

__`kubectl --namespace=kube-system describe deployment kubernetes-dashboard`__
```
Name:                   kubernetes-dashboard
Namespace:              kube-system
CreationTimestamp:      Fri, 23 Feb 2018 04:49:40 +0100
Labels:                 addonmanager.kubernetes.io/mode=Reconcile
                        k8s-app=kubernetes-dashboard
                        kubernetes.io/cluster-service=true
Annotations:            deployment.kubernetes.io/revision=1
                        kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"apps/v1beta2","kind":"Deployment","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","k8s-app":"kubern...
Selector:               k8s-app=kubernetes-dashboard
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           k8s-app=kubernetes-dashboard
  Annotations:      scheduler.alpha.kubernetes.io/critical-pod=
  Service Account:  kubernetes-dashboard
  Containers:
   kubernetes-dashboard:
    Image:  gcr.io/google_containers/kubernetes-dashboard-amd64:v1.8.0
    Port:   8443/TCP
    Args:
      --auto-generate-certificates
    Limits:
      cpu:     100m
      memory:  300Mi
    Requests:
      cpu:        50m
      memory:     100Mi
    Liveness:     http-get https://:8443/ delay=30s timeout=30s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /certs from kubernetes-dashboard-certs (rw)
      /tmp from tmp-volume (rw)
  Volumes:
   kubernetes-dashboard-certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kubernetes-dashboard-certs
    Optional:    false
   tmp-volume:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:  
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  <none>
NewReplicaSet:   kubernetes-dashboard-775fc9968 (1/1 replicas created)
Events:
  Type    Reason             Age   From                   Message
  ----    ------             ----  ----                   -------
  Normal  ScalingReplicaSet  5m    deployment-controller  Scaled up replica set kubernetes-dashboard-775fc9968 to 1
```

**Comment by yuvipanda** [comment]
on GKE, the only way to do this is to 'disable the addon' (with the `--disable-addon` param to `gcloud container clusters create` or `gcloud container clusters update`. This is going to differ wildly based on how the kubernetes cluster is set up.

**Comment by willingc** [comment]
Add to wiki or perhaps to upgrade documentation.

**Comment by consideRatio** [comment]
GKE has improved, closing.
