### ISSUE TITLE
Notebook should not see service discovery env variables

### ISSUE THREAD

**Issue by clkao** [jupyterhub/zero-to-jupyterhub-k8s#536]
Currently all the services host/port in the same namespace are in the user's environment, which can make `env` output overwhelming.

https://github.com/kubernetes/kubernetes/pull/60206/
https://github.com/kubernetes/kubernetes/issues/60099
https://github.com/kubernetes/community/pull/1249

**Comment by yuvipanda** [comment]
Thanks for opening the issue!

I think as it is now, the environment variables are required to talk to the hub/proxy from the singleuser server. I think maybe setting a whitelist at the notebook level might be a good idea?

**Comment by clkao** [comment]
Actually hub endpoint is defined by kubespawner (via --hub-api-url), but we should use the service discovery env.

Whitelisting sounds reasonable - just that we probably need to do that in the notebook image's startup script.

**Comment by yuvipanda** [comment]
I think the --hub-api-url refers to a env variable, at least in z2jh? I could totally be wrong though, haven't looked at it in ages :)

Closing this, since as you said the right way to do this is filter in your image's startup script.

**Comment by clkao** [comment]
FYI https://github.com/jupyter/docker-stacks/pull/596 should allow adding custom scripts that removes env vars.
