### ISSUE TITLE
Jupyter Lab `@jupyterlab/hub-extension` does not show menu

### ISSUE THREAD

**Issue by jacobtomlinson** [jupyterhub/zero-to-jupyterhub-k8s#539]
Despite having `@jupyterlab/hub-extension` enabled I cannot see the "Hub" menu. 

In my config I have set the `singleuser.defaultUrl` to `/lab` but it also specifies in the [instructions](https://github.com/jupyterhub/jupyterlab-hub#installation) that Jupyter Lab must be launched with `jupyter labhub`. I'm wondering if this is not happening and causing this problem. I've tried changing the `singleuser.cmd` to `jupyter labhub` but I get errors saying `jupyter` cannot be found.

```
jovyan@jupyter-jacobtomlinson:~$ jupyter labextension list
JupyterLab v0.31.8
Known labextensions:
   app dir: /opt/conda/share/jupyter/lab
@jupyter-widgets/jupyterlab-manager
        @jupyter-widgets/jupyterlab-manager v0.33.2  enabled  OK
@jupyterlab/hub-extension
        @jupyterlab/hub-extension v0.8.1  enabled  OK
```

**Comment by consideRatio** [comment]
I got my Hub menu to show, this is my singleuser image:

https://github.com/consideRatio/z2jh-extended/blob/master/images/singleuser/Dockerfile

**Comment by jacobtomlinson** [comment]
We are just using the official images with the [start scripts](https://github.com/jupyter/docker-stacks/blob/master/base-notebook/start-singleuser.sh) and it looks like our start command eventually boils down to `jupyter labhub`.

I am surprised there is a difference between `jupyter-labhub` and `jupyter labhub`, I was under the impression that all the commands with dashes in were aliases for the jupyter subcommands.

**Comment by consideRatio** [comment]
I found that attempting to install a hub-extension that did not work with the current jupyterlab could actually crash ipywidgets for example.

My experience now tells me this is a hub-extension + jupyterlab compability issue, caused by failing extension builds that don't trigger a docker-image build crash
