### ISSUE TITLE
Embed wrapspawner to allow selection of image

### ISSUE THREAD

**Issue by gsemet** [jupyterhub/zero-to-jupyterhub-k8s#545]
Hello

How hard would it be to embed wrapspawner or similar in order to allow user selection of desired profile upon connection.
What I mean by "profile" is a predefined list of "image + cpu number + disk space + memory".

I imagine something like a dropbox where user can select for instance"small datascience notebook", "big memory datascience" or "Python training notebook", and so on, and it would launch the related image and cpu/memory request for kube.

**Comment by yuvipanda** [comment]
Thank you for opening this issue, @gsemet! I agree that it would be very useful to have!

I think adding something like https://github.com/jupyterhub/dockerspawner/pull/219 to github.com/jupyterhub/kubespawner is a better fit! What do you think, @minrk?

**Comment by cam72cam** [comment]
I'd like to help out, even if that is just being a guinea pig on this ticket

**Comment by gsemet** [comment]
Isn’t it easier or better to integrate wrapperspawner in zero to jupyterhub or hack into kubespawner?

**Comment by gsemet** [comment]
@yuvipanda If I follow you proposal to hack into kubewrapper, I would like to propose the following change in kubewrapper:
- New option `c.KubeSpawner.single_user_profile_list` is added and take precedence over `singleuser_image_spec
- this option is a list of dictionnary of form:
```
{
    'display_name': 'Human Readable Profile Title',
    'image_spec': 'image/to_execute:label'
    'cpu_limit': cpu_limit,
    'cpu_guarantee': cpu_guarantee,
    'mem_limit': mem_limit,
    'mem_guarantee': mem_guarantee,
    'lifecycle_hooks': lifecycle_hooks,
    'volume_mounts': volume_mounts,
}
```
Note that `lifecycle_hooks` and `volume_mounts` can be superseeded in this configuration (I propose the following: if key is defined, no matter its value (None or set to a value), the setting is super seeded. If not set, the default value stays `c.KubeSpawner.volume_mounts` for example)

**Comment by minrk** [comment]
indeed, adding wrapperspawner support may be the best way to go.

**Comment by gsemet** [comment]
I have made a proposal in this PR: https://github.com/jupyterhub/kubespawner/pull/137

**Comment by jgerardsimcock** [comment]
Has this functionality been merged into the z2jh deployment yet? If not and we want to implement this, what is the best way to approach this?

**Comment by minrk** [comment]
I think the kubespawner profiles are now in z2jh

**Comment by consideRatio** [comment]
Closed thanks to @gsemet's work on https://github.com/jupyterhub/kubespawner/pull/137!
