### ISSUE TITLE
Rework computation of user email and name 

### ISSUE THREAD

**Issue by gsemet** [jupyterhub/zero-to-jupyterhub-k8s#548]
Currently, user email is built from the following snippet (in `jupyter_config.py`):
```
def generate_user_email(spawner):
    """
    Used as the EMAIL environment variable
    """
    return '{username}@{domain}'.format(
        username=spawner.user.name, domain=email_domain
    )

def generate_user_name(spawner):
    """
    Used as GIT_AUTHOR_NAME and GIT_COMMITTER_NAME environment variables
    """
    return spawner.user.name

c.KubeSpawner.environment = {
    'EMAIL': generate_user_email,
    # git requires these committer attributes
    'GIT_AUTHOR_NAME': generate_user_name,
    'GIT_COMMITTER_NAME': generate_user_name
}
```
This does not render the right email in some cases (ex: Gitlab Oauth, the email is `username@local`). Some auth providers are able to extract the real email address and real name of the logged in user.

Also, there might be a need to distinguish username and user name (myself: on Gitlab I am gsemet but my name is Gaetan Semet). In Jupyterhub against our instance of gitlab, in the admin panel, we see a list of cryptic internal username while I would be interested in also seeing the user email ou real name). But keeping username for folder or unique identifier is also important (username is built in order to avoid collision when two persons have the same name!)

**Comment by choldgraf** [comment]
hey! this seems like an important issue, but I'm a bit unclear as to what is the path forward for resolving it. Could you write out a list of the important changes that you think need to happen for your use-case to be met?

**Comment by gsemet** [comment]
The goal is to leverage authenticator that are able to extract the following 3 values from user profile:
- username: on GitHub: gsemet. It should be unique
- user full name: Gaetan Semet (better for git commit's author). Two persons might have the same full name
- user email (the one registered in the auth system. Normally no collision is possible.

Every authenticator returns at least the username, but some, like GitHub, GitLab are able to return all 3.

Here are some changes I have made in `jupyterhub-config.py` to support **only** value extraction from the Gitlab authenticator:

- Change the authenticator to `GitLabEnvAuthenticator`:
```bash
...
elif auth_type == 'gitlab':
    from oauthenticator.gitlab import GitLabOAuthenticator
    from tornado import gen
    import pprint

    class GitLabEnvAuthenticator(GitLabOAuthenticator):

        @gen.coroutine
        def pre_spawn_start(self, user, spawner):
            auth_state = yield user.get_auth_state()
            pprint.pprint(auth_state)
            if not auth_state:
                # user has no auth state
                return
            # define some environment variables from auth_state
            spawner.environment['GITLAB_TOKEN'] = auth_state['access_token']
            spawner.environment['GITLAB_USERNAME'] = auth_state['gitlab_user'].get('username')
            spawner.environment['GITLAB_FULLNAME'] = auth_state['gitlab_user'].get('name')
            spawner.environment['GITLAB_EMAIL'] = auth_state['gitlab_user'].get('email')
            
    c.JupyterHub.authenticator_class = GitLabEnvAuthenticator
    c.GitLabOAuthenticator.oauth_callback_url = get_config('auth.gitlab.callback-url')
    c.GitLabOAuthenticator.client_id = get_config('auth.gitlab.client-id')
    c.GitLabOAuthenticator.client_secret = get_config('auth.gitlab.client-secret')
```

- change the `c.KubeProfileSpawner.environment` fill in by:
```bash
def generate_user_email(spawner):
    """
    Used as the EMAIL, GIT_AUTHOR_EMAIL and GIT_COMMITTER_EMAIL environment variables
    """
    if spawner.environment.get('GITLAB_EMAIL'):
        return spawner.environment.get('GITLAB_EMAIL')
    return '{username}@{domain}'.format(
        username=spawner.user.name, domain=email_domain
    )

def generate_git_user_name(spawner):
    """
    Used as GIT_AUTHOR_NAME and GIT_COMMITTER_NAME environment variables
    """
    if spawner.environment.get('GITLAB_FULLNAME'):
        return spawner.environment.get('GITLAB_FULLNAME')
    return spawner.user.name

c.KubeProfileSpawner.environment = {
    'EMAIL': generate_user_email,
    # git requires these committer attributes
    'GIT_AUTHOR_NAME': generate_git_user_name,
    'GIT_COMMITTER_NAME': generate_git_user_name,
    'GIT_AUTHOR_EMAIL': generate_user_email,
    'GIT_COMMITTER_EMAIL': generate_user_email,
}
```

Not tested yet, and at the end the solution is ugly, but it should be able to read the real user's email from the gitlab authenticator.

The other change I would like to see is to add a new column in the admin panel of jupyterhub, to have both username and user email (and maybe the user full name).

**Comment by gsemet** [comment]
I validate it works. In my server, users have the following environment variables:
```
GITLAB_EMAIL
GITLAB_FULLNAME
GITLAB_TOKEN
GITLAB_USERNAME
GIT_AUTHOR_NAME
GIT_COMMITTER_NAME
GIT_AUTHOR_EMAIL
GIT_COMMITTER_EMAIL
```
with the right values.

`GITLAB_HOST` is configured in the `extraEnv` of my `config.yaml`

**Comment by choldgraf** [comment]
that's pretty cool! I can take a closer look at this over the week, a lot of the team is traveling right now so things are moving slowly 🐌 

cc @minrk, who may have thoughts on how best to patch the authenticator

**Comment by gsemet** [comment]
I agree my solution is ugly, but i would be happy to have a few pointers on how to implement it better

**Comment by consideRatio** [comment]
I could not translate this into issue into a concrete action point, and is due to that closing it as I'd really like to reduce the hundreds of issues to something more manageable.
