### ISSUE TITLE
Add an example of configuring an external service

### ISSUE THREAD

**Issue by willingc** [jupyterhub/zero-to-jupyterhub-k8s#550]
From gitter channel today: How to set up as an external jupyterhub service in z2jh?

User issue:  I was trying `services: name: <name>` when I should have been doing `services: <name>:`

**Comment by summerswallow** [comment]
Here is my specific example using whoami-flask.py adding my helm chart
`
hub:
  services:
    whoami:
      apiToken: <Secret generated by openssl>
      url: 'https://whoami-test.mydomain.com'
      admin: false
`
This passes helm but I will update this as I get a version working.

**Comment by consideRatio** [comment]
@summerswallow any updates?

**Comment by summerswallow-whi** [comment]
Been away from working on jupyterhub for a while. I guess the question here is whether to add an example to the documentation or an example to the source.

**Comment by snickell** [comment]
I've been struggling with this, I did manage to get an external service defined, but doing auth.... its unclear to me what URL (port, dns, url path) to use from inside the K8S cluster to access the `authorizations/cookie` API.

**Comment by consideRatio** [comment]
Closing in favor of another issue that is meant to capture various documentation wishes. Will soon make sure there is a reference back showing up here.

**Comment by snickell** [comment]
@consideRatio would be great to have a link to the docs, I did figure this out (it was pretty hard ;-), so I might be able to contribute a useful example

**Comment by consideRatio** [comment]
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1810
