### ISSUE TITLE
Update minikube instructions in CONTRIBUTING.md

### ISSUE THREAD

**Issue by willingc** [jupyterhub/zero-to-jupyterhub-k8s#552]
Step 7 for the local minikube CONTRIBUTING.md installation instructions errors when running on MacOS High Sierra. 

I believe that the error is due to RBAC and/or permissions. Perhaps after the switch to chartpress this changed.

**Comment by manics** [comment]
CI uses minikube with RBAC enabled: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/ci/install.sh#L27

If you're updating the instructions to enable RBAC might be worth pointing out this bug: https://github.com/kubernetes/minikube/issues/2510
Fix (for v0.25.0) was `kubectl create clusterrolebinding kube-system-cluster-admin --clusterrole=cluster-admin --serviceaccount=kube-system:default`

**Comment by willingc** [comment]
Closed by #554. Thanks @manics for the additional info :cake:
