### ISSUE TITLE
Improvements to the Z2JH tutorial

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/zero-to-jupyterhub-k8s#558]
These are from the post-mortem on 10/06 (#226). The Latest Z2JH lives here:

https://docs.google.com/presentation/d/1loynWNwsv3lgK5DCe5Ai8GbCyjS2JviaefsygXEhlLU/edit?usp=sharing

**NOTE: Please copy/paste the tutorial into another workshop folder before making edits if you're holding a workshop**

## Specific notes
- [ ]  Improve the tear-down documentation at the end so that it's more complete, and so people aren't worried they'll spend money.
- [ ] Guidelines for how much RAM / CPU you might need with a couple of use-case examples (e.g. what does Data 8 use)
- [ ]  Make sure people don't try to create cloud resources *before* linking a billing account. Have easy way to check if you are good to go!
- [x]  Make sure 'kubectl logs' is in there. We had removed the "debugging" section so it was hidden, but decided that it's actually quite important and should be in there regardless.
- [ ]  Show the diagrams in steps so that it doesn't overwhelm people 
- [ ]  Cover a bit more GUI during the teardown
- [ ]  Link to some example helm charts for various deployments as an example

## General notes
- [ ]  Give better instructions on connecting the billing account + enabling cloud resources before the workshop starts. Things go much more smoothly when people have mostly already done this.
- [ ]  Always show full config.yaml, color new bits for context.
- [x]  Make sure every command is copy-pasteable and runs as pasted (no spaces after line continuing \)
- [ ]  Do better at scoping time - the content we covered was a bit optimistic
- [x]  Make sure the styling is consistent.
- [x]  Make sure all slides belong to the template and modify the template for custom design elements (instead of one-off slides).
- [x]  30 people was exactly the right number of people (full room, but not too overcrowded).

**Comment by consideRatio** [comment]
Bumping this for some attention for the upcoming JupyterHub tutorial.

Regarding tear down, GKE will delete the load balancer along with the ingress resource now.

**Comment by consideRatio** [comment]
@choldgraf should we make a push for this before 0.8 release or let it be as it is?

**Comment by consideRatio** [comment]
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/995 represents the need for some docs about resources and such. I'll go ahead and close this issue as stale at this point with too vague action points given that a lot of time has passed and things has evolved since.
