### ISSUE TITLE
Add guidelines for how much RAM/CPU is a good default for common usecases

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/zero-to-jupyterhub-k8s#559]
At the last Z2JH there was confusion from the audience about how much CPU or RAM they should give users. Some gentle suggestions would be helpful in the docs.

**Comment by consideRatio** [comment]
Paying for my students cloud expenses right out of my own pocked, I have tried very low CPU requirements. I ended up giving them 450m CPU and 1 GB ram. They can still make nice plots and such. I noticed that 200m CPU seemed to cause issues.

**Comment by consideRatio** [comment]
Closing this in favor of #904.
