### ISSUE TITLE
Curate a list of example helm charts

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/zero-to-jupyterhub-k8s#560]
Some folks find it useful to look at other helm charts in production in order to understand how the various k8s pieces fit together. We could create a list of some well-known helm charts for jupyterhub deployments, and link to those for inspiration.

**Comment by consideRatio** [comment]
Yes! I remember looking, and it would certainly help to be suggested 1-3 specific examples to look at.

**Comment by willingc** [comment]
If you are a community member, please let us know if you have an example that you would like to share.

**Comment by yuvipanda** [comment]
Can you explain a bit more what you mean by:

> We could create a list of some well-known helm charts for jupyterhub deployments

?  From the first sentence, I'd imagine something like the charts in https://github.com/kubernetes/charts/, but am confused by the second sentence :)

**Comment by choldgraf** [comment]
By "well-known helm charts" I mean configurations for specific deployments. E.g. "if you want to see the `mybinder.org` deployment helm chart, click here"

**Comment by yuvipanda** [comment]
I'm going to split this into two issues, hope that's ok!

#737 #738
