### ISSUE TITLE
In docs, reference.txt links to non-existing page (user-experience.html)

### ISSUE THREAD

**Issue by tylere** [jupyterhub/zero-to-jupyterhub-k8s#561]
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/3c23fd2860aa885c283b3549fe9d673019c25222/doc/source/reference.txt#L13

**Comment by whosford** [comment]
I'd like to work on this issue if nobody else is

**Comment by choldgraf** [comment]
Please feel free to make a pr!

**Comment by choldgraf** [comment]
just realized that @whosford already fixed this - thanks a bunch!
