### ISSUE TITLE
Document how JupyterHub relates to EU privacy law

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/zero-to-jupyterhub-k8s#564]
Specifically with respect to JupyterLab and persistent state. The short version is that we are probably *not* in violation of this law by default, since the server never sees the cookies that are stored on a user's machine in JupyterLab (they're only used locally). We should document this, and also add a note about this on the Binder user docs.

Here's a relevant comment about this: https://github.com/jupyterlab/jupyterlab/issues/3987#issuecomment-370219668

**Comment by consideRatio** [comment]
Closing this in favor of an issue that summarize and reference a lot of potential documentation improvements.
