### ISSUE TITLE
Documentation about storage type hostPath and homeHostPathTemplate

### ISSUE THREAD

**Issue by gsemet** [jupyterhub/zero-to-jupyterhub-k8s#568]
There is no documentation about storage type "hostPath"

**Comment by yuvipanda** [comment]
I'll try write something up soon! Thanks for the poke!

**Comment by consideRatio** [comment]
Should we still write about this? It is my understanding that hostPath is considered something we should move away from in general in the kubernetes world.

**Comment by consideRatio** [comment]
I think we have deleted this entirely, hostPath is something that requires significant privileges, so I assume that is why.
