### ISSUE TITLE
Jupyterhub with Kubernetes on local cluster, custom hub

### ISSUE THREAD

**Issue by agustaf** [jupyterhub/zero-to-jupyterhub-k8s#591]
Greetings,

I am new to the Kubernetes world, so please forgive my ignorance.  I am helping with a project that is using Jupyterhub to spawn notebooks for data analysis, and the project will likely acquire some hardware in the form of a few nodes.  I am looking into adapting our Jupyterhub setup to use kubespawner in preparation for this.

I have been trying some tests on a small Kubernetes cluster I setup across two VMs.  I've been attempting to follow the Zero to Jupyterhub documentation, to get a vanilla test instance working.

Currently, when I try to follow Zero to Jupyterhub, and deploy a test Jupyterhub + kubespawner setup using helm, I appear to get a volume mount error when it tries to spawn the hub pod.  The VMs in my test kubernetes cluster have only local storage.  Does there need to be some shared storage in order for the hub to function properly?  I tried to turn off persistent user storage by setting singleuser: storagetype: none in the config.yaml file.  I think I am somewhat misunderstanding the storage setup, and would appreciate any advice.

In the future, we will need to replace the hub with a custom hub, which will perform certain custom actions on user login.  Is there a list criteria (other than using kubespawner) that a hub must satisfy in order to work correctly with the Zero to Jupyterhub Kubernetes framework?

Thanks much.

**Comment by manics** [comment]
Try disabling the hub storage?
```
hub:
  db:
    type: sqlite-memory
```

**Comment by willingc** [comment]
Hi @agustaf,

Thanks for opening an issue here. Please let me e-introduce you to @minrk too. Andrew works with the Minnesota Supercomputing center and IIRC has a physics background too. @minrk if you have thoughts on the above issue, it would be appreciated.

**Comment by agustaf** [comment]
Thanks for the information!  Using sqlite-memory for the hub storage does fix the volume mount issue.

Just a couple of follow ups: 

- If we did wish to have some persistent hub storage, I assume we would need to create a persistent volume claim.  Could we do that using local storage on a single physical node, and require the hub pod to run on that node?

- If we wished to use a custom hub, are there any subtleties to worry about other than having it use kubespawner for notebook launch?  

Thanks much for the help as we are learning about Kubernetes.

**Comment by danielmaitre** [comment]
Hi @agustaf ,
you can use nfs-provisioner to create persistent storage on your local disks. See

https://github.com/kubernetes-incubator/external-storage/tree/master/nfs

It worked for me.

**Comment by choldgraf** [comment]
FWIW this is the kind of information I'd love to be able to codify in the jupyterhub community somehow, thanks @danielmaitre for jumping and helping others :-)

**Comment by consideRatio** [comment]
> If we did wish to have some persistent hub storage, I assume we would need to create a persistent volume claim. Could we do that using local storage on a single physical node, and require the hub pod to run on that node?

If you use local storage, you need to ensure the pod is always scheduled on the same node, using a nodeSelector or similar.

---

I think it may be a bit too complex to support you for us relating custom kubernetes + custom hub.

You can ask questions in the gitter chat or create a new issue with a reduced scope so we can get more actionable regarding the issue.
