### ISSUE TITLE
Advise to create/delete gcloud project. 

### ISSUE THREAD

**Issue by Carreau** [jupyterhub/zero-to-jupyterhub-k8s#61]
When using Gcloud, once done, even after deleting cluster all associated network rules, disk...etc are still around. 

I would suggest to create/delete a project to make sure to have a clean slate everytime.

**Comment by willingc** [comment]
Next action: Review current documentation to see if this is now resolved by new docs on deleting a cluster.

**Comment by henchc** [comment]
https://zero-to-jupyterhub-with-kubernetes.readthedocs.io/en/latest/turn-off.html on the turn off page there are currently no specific commands to copy paste.

**Comment by consideRatio** [comment]
The current docs are sufficient and contains mostly redundant double check instruction. If the user manually has pushed images to the image registry, one step is not redundant though.
