### ISSUE TITLE
Allow to provide a service account for user-scheduler, and potentially other pods

### ISSUE THREAD

**Issue by gsemet** [jupyterhub/zero-to-jupyterhub-k8s#616]
Hello,

On our baremetal cluster, our ops teams restrict the creation of service account (more precisely we do not have rights to use `clusterrolebinding`, so we have to request it and it usually ends with the creation by them of a "admin"-like service account, restricted to our namespace.

I have patched the jupyterhub chart so that I provide the RBAC service account instead of letting the chart create it. I would like to propose it to upstream, will you agree with this feature?

Thanks,
Gaetan

**Comment by yuvipanda** [comment]
This seems like a useful feature! We could implement it with the following properties:

1. rbac.createServiceAccount (defaults to true) this will create service accounts as part of the helm chart if set to true (and rbac.enabled is also set to true)
2. hub.serviceAccount, singleuser.serviceAccount, etc - this can specify names of the (user created) service accounts for those services if you wish. singleuser.serviceAccount already exists I believe.

The one wrinkle here is going to be the service account for the nginx component of the proxy. It is no longer required, so it might be ok - but nginx-ingress required a wide range of cluster-wide permissions because of the way it was written. I want us to eventually replace that anyway though.

**Comment by gsemet** [comment]
We don’t have this problem with Traefik we basically just add the ingress and a few annotation and the service is available. Do you know if this difference comes from our implementation (so we may have a security issue?) or from traefik itself?

**Comment by yuvipanda** [comment]
@gsemet I think with traefik it's fine, it's just the nginx-ingress is written poorly. I think you don't have a security issue :) 

I'll open an issue about possibly moving away from the automatic nginx setup.

**Comment by consideRatio** [comment]
This might be relevant, some best practice stuff regarding declaring service accounts I stumbled across.

https://github.com/kubernetes/helm/blob/master/docs/chart_best_practices/rbac.md#yaml-configuration

**Comment by jmabry** [comment]
It would be great if this feature could replace the current step for setting up the authenticator for EKS  in the docs at https://raw.githubusercontent.com/jupyterhub/zero-to-jupyterhub-k8s/a03a07f0d3d7248c3f6fbf86b02f43198847a819/doc/source/amazon/step-zero-aws-eks.rst  The command `kubectl create clusterrolebinding cluster-system-anonymous --clusterrole=cluster-admin --user=system:anonymous` is a known security risk.  See https://github.com/kubernetes-incubator/apiserver-builder/issues/225#issuecomment-395332276

**Comment by gsemet** [comment]
First, I never ever installed Tiller in Kube-system. This means it has permission on ALL your cluster. At least link tiller to a service account with only permission on 1 namespace (1 tiller per namespace).

Now we have switched to tillerless model, were you launch tiller on your local computer (using [tillerless](https://rimusz.net/tillerless-helm)) or in your CI, use a kube config file with service account token to connect to the Kubernetes API. This means there is no more tiller running in your namespace, and you only using the Kube API to deploy. Bonus, with the same config, you can use helm+tillerless, bare kubectl or kustomize, in your CI, to deploy. Safer and actually much easier to maintain.
And compatible helmv3 :)

**Comment by consideRatio** [comment]
Only the user-scheduler is currently using a k8s serviceAccount that has a ClusterRoleBinding bound to it, so if the goal is to avoid ClusterRole and ClusterRoleBindings, then we need to allow configuration of that only at this point.

**Comment by consideRatio** [comment]
Closing this in favor of #1295 2680
