### ISSUE TITLE
Add support to Helm Chart for specifying hostname of GitHub Enterprise / GitLab server

### ISSUE THREAD

**Issue by lambertjosh** [jupyterhub/zero-to-jupyterhub-k8s#644]
For users who have a self-hosted GitHub or GitLab instance, and want to leverage OAuth, they will need to pass along the host name. This looks to be [supported by JupyterHub](https://github.com/jupyterhub/oauthenticator#github-setup), but not by the Helm chart. 

It would be great if this was added, or documentation recommending adding it as an `extraEnv` field.

**Comment by ablekh** [comment]
This feature seems to be supported by **z2jh** Helm chart. See this section in the _Helm Chart Configuration Reference_ page: http://zero-to-jupyterhub.readthedocs.io/en/latest/reference.html#hub-extraenv.

**Comment by lambertjosh** [comment]
@ablekh yes, we have it working, however it's not documented.

You currently have to read here to understand how to configure auth in the charts: https://zero-to-jupyterhub.readthedocs.io/en/latest/authentication.html#github

Then you have to go find the service specific instructions here: https://github.com/jupyterhub/oauthenticator#github-setup

Then you see you can configure the environment variable, at which point you need to know that you can set that using the `extraEnv` parameter as you mentioned. 

It would be great if this was documented a little better within the Helm chart repo, or alternatively these options were added to the chart as they are probably fairly common for enterprise users.

I can take a crack at updating the docs, if that is the path that we want to go down.

**Comment by choldgraf** [comment]
@lambertjosh we'd love to help out on a docs PR if you've got a moment to edit things in a way that'd make sense to you! Do you think you'd have the time to open a PR we can iterate on?

**Comment by consideRatio** [comment]
This is configurable through `auth.gitlab.gitlabUrl`, but I notice there are other things missing, such as `allowed_project_ids`, see [here](https://github.com/jupyterhub/oauthenticator/blob/master/oauthenticator/gitlab.py#L107) and compare with [this](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/a2c3ef80932d4ae45cde562823c76155ccfc8897/jupyterhub/files/hub/jupyterhub_config.py#L295-L304).

In general, we should try finding a more sustainable configuration experience to avoid needing this Helm chart ot keep updated with the changes in configuration of authenticators.

**Comment by consideRatio** [comment]
Closing the issue as gitlab_url is configurable at least, and adding a note to help us get a better system in place where this doesn't happen.
