### ISSUE TITLE
Support for sidecars in single user pod

### ISSUE THREAD

**Issue by lambertjosh** [jupyterhub/zero-to-jupyterhub-k8s#645]
You can add sidecars to the Hub pod, which is great, but it would also be very helpful to allow sidecars in the single user pods as well.

For example if you need to run Cloud SQL Proxy to attach to a database, this would make it a lot easier than maintaining a custom docker image.

**Comment by yuvipanda** [comment]
I think you can do that with `c.KubeSpawner.singleuser_extra_containers` or something like that, in extraConfig. We should probably expose that as a config here directly, so you don't have to use extraConfig.

**Comment by metonymic-smokey** [comment]
@yuvipanda is this issue still up for grabs?

Thanks!

**Comment by consideRatio** [comment]
Configuring `c.KubeSpawner.extra_containers` is the way to go in order to provide a sidecar container to the user pods, or using a kubernetes mutating web hook that updates all pods created to have another container for example.
