### ISSUE TITLE
Clarify HTTPS docs

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#648]
We should make it clear that what an automatic https setup implies.
- Certificate setup and renewals are handled automatically
- Something else?

https://zero-to-jupyterhub.readthedocs.io/en/latest/security.html#https

Why? Because both me and @ablekh has found ourselves asking if we needed something more regarding the renewals after following the guide.

**Comment by consideRatio** [comment]
@jgerardsimcock Oh! I have a lot to learn about HTTPS connection and what is required for the browser to consider the page.

> I am keen to expand and improve docs on this.

:heart: That makes me happy!

I think the only place the z2jh guide has something written about HTTPS is within https://zero-to-jupyterhub.readthedocs.io/en/latest/security.html#https, and the text above I quoted now has a link to a file within the repo next to it.

---

I'm curious to know what your browser say about the certificate required for a HTTPS connection. I presume something has gone bad with issuing a certificate for your domain. This is a screenshot from when I access my domain https://jupyter.se within chrome and press the button left of the address field.

![image](https://user-images.githubusercontent.com/3837114/38963557-d97e33ca-4372-11e8-8416-8b33ec75b79a.png)

**Comment by jgerardsimcock** [comment]
@consideRatio Here are the relevant screenshots. Is there anything obvious I am missing?

![screen shot 2018-04-18 at 1 54 14 pm](https://user-images.githubusercontent.com/6101444/38963943-137a15c0-4310-11e8-9f0a-84705ba7d830.png)
![screen shot 2018-04-18 at 1 54 30 pm](https://user-images.githubusercontent.com/6101444/38963944-139a0d30-4310-11e8-939c-243d24119904.png)

<img width="417" alt="screen shot 2018-04-18 at 1 56 25 pm" src="https://user-images.githubusercontent.com/6101444/38964001-5a77fe4c-4310-11e8-9438-f7d5fc77928f.png">

**Comment by jgerardsimcock** [comment]
Also, we are running our own helm chart that uses the base-notebook as a dependency. For https to work will I need to update my helm chart's chart directory with one of the files in the [autohttp dir](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/tree/master/jupyterhub/templates/proxy/autohttps)?

**Comment by consideRatio** [comment]
@jgerardsimcock to me it is nothing obvious, not sure on how to proceed. Some question I raise that might be relevant for us or someone thinking about this down the line.

- What version of the helm chart are you using? 
- What does the logs say for proxy related pods?
- What pods are running (`kubectl get pods --namespace <your-namespace>`)?

---

Everything is supposed to work if you use a up to date helm chart and provide it with values like you did on top of the default values.

**Comment by jgerardsimcock** [comment]
@consideRatio I think the issue is that we are running a deployment that is not using the z2jh helm chart. Our chart is [here ](https://github.com/RhodiumGroup/rhodium-pangeo/blob/master/rhg-pangeo/values.yml). Its very similar to the [Pangeo](https://github.com/pangeo-data/pangeo) team's deployment but we'd like to have ours on https. I think the issues is that I need to add some additional config to the helm chart from [this] (https://github.com/jupyterhub/zero-to-jupyterhub-k8s/tree/master/jupyterhub/templates/proxy)section of the z2jh deployment. 

What I'd like to do is add documentation around setting up your own secure jhub cluster with slightly modified config. This may be best added to community docs and our deployment can be listed on deployments page.

**Comment by jgerardsimcock** [comment]
@consideRatio Thank you for your help. My issue was that I needed to indent my yaml header. Simple stuff.

**Comment by clkao** [comment]
It seems eeb5d5c cleaned up nginx ingress and lego.  However it used to be possible to use a cluster-wide lego pre-deployed (with `proxy.https.enabled: false` and `ingress.annotations`, probably a misfeature).

Can we have an option to support cluster-wide lego/cert-manager?

**Comment by consideRatio** [comment]
@clkao ah okay! I'm not grasping the situation myself though, can you open a dedicated issue for it? I consider @choldgraf's #672 to close this specific issue.

@jgerardsimcock I lost track of this issue sorry for the late reply! I'm currently lacking oversight about what parts of the z2jh documentation needs most improvement. It would be great to have an additional eyes on the additions / changes in #672 though!
