### ISSUE TITLE
Explain how to debug things stuck in 'Pending'

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/zero-to-jupyterhub-k8s#65]
Use 'describe' (vs logs) to find out why kubernetes isn't doing something (vs your own code not doing something)

**Comment by cmoscardi** [comment]
+1, this just saved me after i tried to set a '500' CPU guarantee ;)

**Comment by choldgraf** [comment]
we've got https://zero-to-jupyterhub.readthedocs.io/en/latest/debug.html now!
