### ISSUE TITLE
Old URL in the repo description

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#659]
The repo description link could be updated from https://zero-to-jupyterhub.readthedocs.io to https://z2jh.jupyter.org.

![image](https://user-images.githubusercontent.com/3837114/38964938-0bd4ff00-437a-11e8-94a8-2fe5a7a2e273.png)

**Comment by choldgraf** [comment]
ask and ye shall receive!

**Comment by consideRatio** [comment]
@choldgraf I can haz thorium molten salt reactor?
