### ISSUE TITLE
Too permissive rbac for hook-image-puller's image-awaiter job?

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#671]
@manics realized that we might be able to narrow the permissions requested by the image-awaiter waiting for the hook-image-puller to finish pulling images!

The previous implementation of image-puller asked questions to the kubernetes api server about available nodes, and that _I think_ required a ClusterRole bound to a ServiceAccount.
- https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/64348a7d7d3c2372c354f1d7c74c4d9635ea874e/jupyterhub/templates/pre-puller/rbac.yaml

The newer implmentation does not require that, and might work well with a Role restricted to the namespace, as it simply speaks with the api server regarding namespaced resources, _I think_...
- https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/jupyterhub/templates/image-puller/rbac.yaml

@manics would you like to fix it and verify the pullers still works? It is the image-awaiter job created by alongside the hook-image-puller daemonset that needs the access the api-server, if that still functions after switching from ClusterRole to Role etc. I think the update is a success!

**Comment by manics** [comment]
Sorry, I'm a bit busy at the moment. I see you've already opened a PR anyway 👍
