### ISSUE TITLE
Document LTI Authenticator

### ISSUE THREAD

**Issue by minrk** [jupyterhub/zero-to-jupyterhub-k8s#673]
We have LTI auth available, but it is not yet documented how to use it

**Comment by sanjaydatasciencedojo** [comment]
I have inserted the following lines inside config.yaml and it worked. Thanks @minrk.
auth:
  type: lti
  lti:
    consumers:
       "consumer_key": "consumer_secret"

**Comment by consideRatio** [comment]
With the authentication rework where there is no z2jh specific knowledge know how to use the LTI authenticator, I'll go ahead and close this issue.
