### ISSUE TITLE
Emit a message when a Docker image is being pulled onto a node

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/zero-to-jupyterhub-k8s#690]
Sometimes it's good to know if a Docker image pull is happening. A good example is in BinderHub, where users don't understand why a session launch is taking much longer than normal (and it's usually because the pull operation takes a while to complete).

One way we could solve this is to have JupyterHub emit a message when a user session is launched for an image that doesn't currently exist on the node. BinderHub could then grab this message and display something to the user so they know it'll take longer than expected. I imagine administrators of JupyterHub also might find this useful as we start supporting cases where people launch a wider variety of Docker images from a JupyterHub deployment.

**Comment by consideRatio** [comment]
Yes!

Should we attempt to make something z2jh specific / kubespawner specific or perhaps make something spawner generic perhaps?

Hmmm, is it possible for the kubespawner to report if the pod is pending or pulling also? That would be nice?

**Comment by choldgraf** [comment]
yeah I was wondering the same thing as I posted this...not sure if Z2JH is the best place for this, so if somebody has opinions about where it should go, feel free to suggest another repo!

**Comment by yuvipanda** [comment]
https://github.com/jupyterhub/kubespawner/pull/153 and related from @clkao is what is needed here :)

**Comment by consideRatio** [comment]
Closed! :D Thanks @clkao I love this feature!
