### ISSUE TITLE
Customize and provide the logo - recommendations?

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#691]
@sanzaypant and me wants to customize the logo used by JupyterHub within the z2jh deployment. Anyone with a recommendation on a suitable way to do that?

```yaml
# For starters, we should probably add this or something similar to the helm chart configuration under `hub.extraConfig`
extraConfig: |
  c.JupyterHub.logo_file = "my_custom_logo.png"
```

But how should we provide the image to the Container within the Pod? We often provide strings / config etc, but not full binary files like a logo image... Hmmm... I'm not very happy with the options...

### Option 1 - External reference
We could reference an externally hosted image (`https://my-file-hosting.com/logo.png`)

### Option 2 - Replace the JupyterHub image
We could instruct the helm chart to use our custom docker image for the hub under `hub.image` and make that simply do one silly thing: add the logo.
```dockerfile
FROM jupyterhub/k8s-hub

COPY my-logo.png /some/destination/folder
```

### Option 3 - Mount templates and files to the hub pod (**UPDATED**)

I suggest the option so mount both templates and files that are in total smaller than 2 MB. An example configuration can be [inspected in this Helm chart](https://github.com/neurohackademy/nh2020-jupyterhub/tree/32ab7bc2d24717a8d732da7e442c2ab6a1bc2daa/chart) that defined z2jh as a chart dependency

**Comment by choldgraf** [comment]
Perhaps it's worth having a conversation about branding/templating/customizability of JupyterHub+BinderHub next week @ the jupyterhub dev meeting. WDYT?

**Comment by sanjaydatasciencedojo** [comment]
I was able to change the logo by  inserting following lines inside config.yaml.
hub:
  extraConfig: |
    import urllib.request
    urllib.request.urlretrieve("url of logo", "logo.png")
    c.JupyterHub.logo_file = 'logo.png'

**Comment by dkipping** [comment]
So the solution of @sanjaydatasciencedojo would still require to host the image right?

Does somebody know if there are any different options to hand in an own image (without hosting it externally) to this date than making an extra docker image for that as described originally by @consideRatio ?

Or did you decide against providing an interface for that because of branding purposes?

Cheers

**Comment by manics** [comment]
How about patch Jupyterhub to accept a [base64 embedded image](https://css-tricks.com/data-uris/)?

**Comment by consideRatio** [comment]
Hmmm @manics based on @sanjaydatasciencedojo's solution, we could simply utilize Python to convert a base64 string to an image, and then use that image - i don't know how to do this but i imagine it would work by googling a bit.

```python
extraConfig:
  myCustomLogoConfig:
    my_base64_encoded_logo = "FJA...NTKJN=="
    # do some python to convert the base_64 stuff to logo.png
    c.JupyterHub.logo_file = 'logo.png'
```

**Comment by manics** [comment]
It might already be possible? Python 3 urllib includes support for data URIs https://stackoverflow.com/a/43677746/8062212

**Comment by dkipping** [comment]
tried that in the extraConfig like this:

```
hub:
  extraConfig: |
    # following lines for the logo in the jupyterhub
    from base64 import decodebytes
    imagestr = b'iVBO...YII='
    with open('my_logo.png','wb') as f:
        f.write(decodebytes(imagestr))
    c.JupyterHub.logo_file = 'my_logo.png'
```

It's not throwing any errors, but it's also just not changing anything.

**Comment by manics** [comment]
Does it work if you use the absolute path to the image inside the container?

**Comment by dkipping** [comment]
when providing the absolute path like:
```
with open('/etc/jupyterhub/config/my_logo.png','wb') as f:
        f.write(decodebytes(imagestr))
    c.JupyterHub.logo_file = '/etc/jupyterhub/config/my_logo.png'
```

I get the following error:
```
with open('/etc/jupyterhub/config/ea_logo.png','wb') as f:
    OSError: [Errno 30] Read-only file system: '/etc/jupyterhub/config/ea_logo.png'
```

This explains also why it didn't change anything beforehand I guess.
I already tried putting the image to another high level location like `/home/`, `/srv/` or `/etc/` but then I get a `Permission denied` error

**Comment by consideRatio** [comment]
I updated the the blank Option 3 with my suggested approach that works quite well unless many MB of static files should be passed to the templates.

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/changing-the-logos-of-zero-to-jupyterhub-k8s/5575/8
