### ISSUE TITLE
Disable image puller

### ISSUE THREAD

**Issue by mrocklin** [jupyterhub/zero-to-jupyterhub-k8s#692]
I believe that JupyterHub is pre-pulling my singleuser notebook images to all of the machines to make the first-login faster for users.  My cluster autoscales pretty aggressively thoughout the day, so I suspect that this has limited value.

Is there an easy way to disable this feature?

**Comment by manics** [comment]
Try `prePuller.hook.enabled: false`: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/3959c87ef18bfff1e90ecfb4ec94f92849dd9aa5/jupyterhub/values.yaml#L183

**Comment by consideRatio** [comment]
Note that there are two types of image-pulling:
1. The one that makes sure images are pulled before a helm upgrade (the hook puller)
2. The one that pulls images whenever a new node is added (the continuous puller)

You can disable either or both.

**Comment by mrocklin** [comment]
Thank you @manics and @consideRatio !  I suspect that this will resolve my problem.  Closing.
