### ISSUE TITLE
Enabling multiple users to upgrade deployment via helm

### ISSUE THREAD

**Issue by jgerardsimcock** [jupyterhub/zero-to-jupyterhub-k8s#693]
I am the main person who administers our k8s cluster on GKE. I want to let others have access to install, upgrade, delete etc on our cluster. Is there an obvious way of granting access/auth to additional users.

**Comment by consideRatio** [comment]
Hmmm, so there are ServiceAccounts, and there are Users. Your User is bound to the predefined ClusterRole "cluster-admin" by a ClusterRoleBinding you created in the z2jh guide I figure.

If you want to allow multiple users to be cluster-administrators, you can add ClusterRoleBindings for them to the preexisting ClusterRole called "cluster-admin".

I suggest you look into this:
https://kubernetes.io/docs/reference/access-authn-authz/rbac/#user-facing-roles

And perhaps look into step 7 in the z2jh-guie:
https://zero-to-jupyterhub.readthedocs.io/en/latest/google/step-zero-gcp.html

And perhaps look into already established ClusterRoleBindings:
````shell
kubectl get clusterrolebinding
```

Hope this helps! / erik

**Comment by jgerardsimcock** [comment]
on gke, the solution to this, for us, is to give cluster permissions to other uses and have them update their credentials. This gives them helm privileges on the cluster.

**Comment by consideRatio** [comment]
@jgerardsimcock ah! Thank you for updating us! It enables us to easier return and improve the documentation based on your findings! :heart:
