### ISSUE TITLE
Document k8s version compatibility with JupyterHub version in README ?

### ISSUE THREAD

**Issue by naineel** [jupyterhub/zero-to-jupyterhub-k8s#709]
Hey Guys i couldn't find a place which told me which version of k8s is compatible with which jupyterhub version.

**Comment by consideRatio** [comment]
Ah, nice catch we can certainly improve, the helm chart file has declared
that 1.8+ is required for k8s and 2.7+ for helm as far as i recall.

**Comment by naineel** [comment]
Yup. Actually had to debug stuff on friday..Was running k8s 1.7 and trying jupyterhub install but it wasn't working because kubectl get nodes structure changes between 1.7 and 1.8..So opened this issue. I upgraded my cluster. its 1.8 now and jupyterhub install was smooth..
Something like a compatibility matrix would be helpful K8s version vs jupyterhub version..
Is k8s before 1.8 not supported ?
