### ISSUE TITLE
When using jupyter-repo2docker + trying to save the image: "exec --user-name=.... failed: No such file or directory"

### ISSUE THREAD

**Issue by UsDAnDreS** [jupyterhub/zero-to-jupyterhub-k8s#719]
## Contents of `config.yaml`
```
CONTENTS HERE.
DON'T FORGET TO REMOVE SENSITIVE INFO!
```

I need to create a specific working environment for the JupyterHub (mostly consisting of various R packages), and followed the steps outlined here:

[](https://zero-to-jupyterhub.readthedocs.io/en/latest/user-environment.html)

1. I created a repo at https://github.com/UsDAnDreS/uh-dsi-workshop
    by literally copying the critical parts of jupyter/docker-stacks/r-notebook at https://github.com/jupyter/docker-stacks/tree/master/r-notebook, and adding some extra R packages in the Dockerfile.

2. Then I ran (trying to completely follow the example of  "jupyter-repo2docker <YOUR-GITHUB-REPOSITORY> --user-name=jovyan --image=gcr.io/[PROJECT-NAME]/[IMAGE-NAME]:[TAG] --no-run"):

   jupyter-repo2docker https://github.com/UsDAnDreS/uh-dsi-workshop --user-name=usdandres --image=gcr.io/uh-dsi-workshop-206823/Workshop1:dcc55f --no-run,
 
   where
        -  usdandres is my Linux machine username,
       -  uh-dsi-workshop-206823 is my Google Cloud project ID (while the NAME is uh-dsi-workshop)
       -  dcc55f are the first 6 digits of the last commit

![command](https://user-images.githubusercontent.com/13762713/41273589-aadc323c-6ddf-11e8-9ca0-4a0f2535f059.png)

 3. It appeared to have successfully built an image:
   
![execution_final_output_and_error](https://user-images.githubusercontent.com/13762713/41273508-641f1ada-6ddf-11e8-9857-75ec32c1eac7.png)

but then fails to save it, giving me a  "user-name=usdandres failed: No such file or directory" error.
  
![error](https://user-images.githubusercontent.com/13762713/41273528-7897356a-6ddf-11e8-8022-9aa4cfa49cbf.png)

  
 4. Meanwhile, when I DIDN'T try and save the image, as in 
  
![no_save](https://user-images.githubusercontent.com/13762713/41273660-fc45577a-6ddf-11e8-9ca4-2713414f47bd.png)

  everything went fine, I could access the given url and all packages were loaded.

 What is the issue with the command where I try to save the image? Why does it bite on 'user-name' argument? Even when I get rid of it - it still doesn't like my path 'gcr.io/uh-dsi-workshop-206823/Workshop1:dcc55f', giving the same 'No such file or directory error.'

**Comment by betatim** [comment]
I think the problem is that `repo2docker` is a bit brittle when it comes to passing command-line arguments in particualr orders. I would try running your command again as `repo2docker --user-naem usdandres --other-option -yet-more-options https://github.com/org/repo`. The important part is putting all the options/flags at the start before the URL of the repository.

**Comment by UsDAnDreS** [comment]
@betatim Yes, worked like a charm, thank you so much!!!
