### ISSUE TITLE
"Init:ImagePullBackOff",  "FailedSync", "Error syncing pod" issues when building from a newly-created Docker image on Google Cloud

### ISSUE THREAD

**Issue by UsDAnDreS** [jupyterhub/zero-to-jupyterhub-k8s#721]
## Contents of `config.yaml`
```
proxy:
  secretToken: ...
singleuser:
  image:
    name: gcr.io/uh-dsi-workshop-206823/workshop1
    tag: b92c23c
```

I was able to use **repo2docker** in order to create an image, and pushed it to Google Cloud:
 
![image_on_google_cloud](https://user-images.githubusercontent.com/13762713/41310832-4882c2ae-6e48-11e8-8942-0d20efebc70b.png)

Then I inserted the image name and tag into the 'config.yaml' file (as can be seen above), ran a helm upgrade, 

![helm_upgrade](https://user-images.githubusercontent.com/13762713/41310937-8f6a7f68-6e48-11e8-9260-21bbbe2ac82b.png)

but it failed and showed "Init : ImagePullBackOff" all around

![imagepullbackoff](https://user-images.githubusercontent.com/13762713/41311009-c495904c-6e48-11e8-9f62-108c8a05972b.png)

I also tried to "diagnose" those pods, but I was probably doing it wrong..

![diagnosis_attempt](https://user-images.githubusercontent.com/13762713/41311099-f7351b80-6e48-11e8-9723-63a1c5b83014.png)

Anyone know why upgrading Helm with this image info didn't quite work out? What might be the reason behind those "ImagePullBackOff"s? 

Thanks in advance!

**Comment by UsDAnDreS** [comment]
Attached is a diagnostic to on of the failed pods (it's the same "Event" for all three of them: FailedSync, Error syncing pod")

![failedsync_1](https://user-images.githubusercontent.com/13762713/41330146-3827c73e-6e97-11e8-82ec-10582ee3059e.png)

![failed_sync_2](https://user-images.githubusercontent.com/13762713/41330147-3b94d9e8-6e97-11e8-91e5-71638e53936f.png)

![failed_sync_3](https://user-images.githubusercontent.com/13762713/41330151-3de98efa-6e97-11e8-84f4-ade705917ccc.png)

**Comment by choldgraf** [comment]
hmmm, does `kubectl logs` show anything from the broken prepullers?

**Comment by UsDAnDreS** [comment]
@choldgraf  The issue has been taken care of by me using Google Cloud console instead of the local machine. As that's where the Image was pushed to (Google Cloud), so I feel like that might've been it, but can't be sure of anything at that point.

**Comment by choldgraf** [comment]
cool - thanks for following up!
