### ISSUE TITLE
LDAP Authenticator w/zero-to-jupyterhub-k8s

### ISSUE THREAD

**Issue by roversne** [jupyterhub/zero-to-jupyterhub-k8s#722]
Hi everyone!

Been trying to get this tested working but with little success. Finding depending on a variety of configurations (mostly those I have found that DO work in other JH deployments) end up with the same results - failed container deployment with either of the two outputs:

ModuleNotFoundError: No module named 'ldapauthenticator'

or

The 'authenticator_class' trait of <jupyterhub.app.JupyterHub object at 0x7fd65c760f60> instance must be a type, but 'ldapauthenticator.LDAPAuthenticator' could not be imported

I am deploying with the v6 HELM chart, but have tried with 04, and 050 as well.

When I remove the configs, the container launches as exected. I can exec the container I can see that the package is deployed to the container vi pip freeze - (jupyterhub-ldapauthenticator==1.2.1)

Ive tried to pair the config down to just the instantiation of the adapter, the ldap server, and the template to try and get even the base config to load but with no luck.

I am supplying the config params via the config yaml in the hub extraconfig section. I am wondering if I have an issue in there with not having the right pathing/logic.

Has anyone gotten this to work with the zero-to-jp deployment path?

Thanks!!

**Comment by manics** [comment]
It's not released yet, it was added in https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/649 with a follow-up fix in https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/703.

You could try one of the 0.7 dev builds? https://jupyterhub.github.io/helm-chart/

**Comment by roversne** [comment]
@manics - Thanks so much! The latest dev release loaded without issue.

**Comment by stevegore** [comment]
I'm trying the same things with the [JWT authenticator](https://github.com/mogthesprog/jwtauthenticator/), and getting the same error. Any pointers? I'll also raise a new issue.

**Comment by consideRatio** [comment]
Please raise a new and reference this if this is still an active issue, this technical issue is fixed atm. Also note that there may be pointers on how to work with that authenticator in its gitrepo. // brief because of on mobile in commute
