### ISSUE TITLE
Run `make linkcheck` in CI

### ISSUE THREAD

**Issue by minrk** [jupyterhub/zero-to-jupyterhub-k8s#724]
There are quite a few broken links in our docs. We can and probably should be running `make linkcheck` in the docs as part of CI.

cc @willingc 

Related to #723

**Comment by willingc** [comment]
Absolutely agree. Thanks @minrk.

**Comment by willingc** [comment]
Just did a make linkcheck. There are about 8 broken links and a number of redirects to new locations. I'm at Cal Poly today and will try to do a cleanup of the links and then add the linkcheck to Travis.

**Comment by choldgraf** [comment]
ah this is a great idea

**Comment by consideRatio** [comment]
:heart:
It may also be good to have `tools/lint.py` run, it is on my long term todo list. Currently I run it manually from time to time.

**Comment by willingc** [comment]
If we run a linter, we should also start using black for Python code for style (over time).

**Comment by consideRatio** [comment]
Ah deal @willingc I'll look into that! It is currently only linting yaml and verifying it makes sense with kubernetes resource specifications.

**Comment by consideRatio** [comment]
In #758 i added tools/lint.py which i should now rename to lint-and-validate-k8s-yaml.py as part of the CI.

@willingc you seem to be *in the know* of how to do this, could you add a `make linkcheck` to the CI?

**Comment by consideRatio** [comment]
Bumping this, I'd love to see this now that we are making additional changes to the docs.

Looked at whats going on in the makefiles etc, but didn't quickly conclude what I needed to do.
https://github.com/jupyterhub/jupyterhub/blob/4d2d677777ef63f466934376d726cd6130df4a34/docs/make.bat

**Comment by choldgraf** [comment]
is this now just a matter of adding `make linkcheck` into one of our travis/circle builds?

**Comment by consideRatio** [comment]
Hmmm, I think it will fail without proper reason due to "missing anchor" stuff that actually works though.

If we make it `make linkcheck || true` then we get the info without the crash on failure. I'm not confident about the make linkcheck as part of the CI though, as it often does not happen as a consequence of a new PR's code itself but simply becoming outdated.

Seems like we should check internal references rather than external, hmmm, perhaps make linkcheck also requires us to first do `make html`, right?

**Comment by choldgraf** [comment]
ah I see - perhaps something to just do as a "team process" kind of thing once in a while? Or is there a way to make the anchor links pass?

**Comment by consideRatio** [comment]
@choldgraf I don't know - I did not investigate it though.

**Comment by manics** [comment]
Could you add a [Travis cron job](https://docs.travis-ci.com/user/cron-jobs/) so you'll know if the master branch breaks?

**Comment by consideRatio** [comment]
Sounds great @manics !!!

**Comment by consideRatio** [comment]
We now have a linkcheck running that provide output on build, it has typically failed almost nonstop, but at the same time I've caught a lot of things thanks to it!

Thanks @manics!
