### ISSUE TITLE
Allow setting location-snippet in nginx configmap

### ISSUE THREAD

**Issue by chicocvenancio** [jupyterhub/zero-to-jupyterhub-k8s#729]
It would be nice if [`location-snippet`](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#location-snippet) inside the ingress-nginx configMap was configurable in values.yml. 

My use case is I have a front-end proxy that handles TLS termination for me, its rules are not fully under my control. The supported way to force redirection in my environment is by sending a redirect based on the `X-Forwarded-Proto` header. Setting `location-snippet` in the configMap is enough, having this automated in the Helm chart would be ideal.

**Comment by chicocvenancio** [comment]
I can send the PR for this, I'd like some feedback if this is a sane idea though.

**Comment by chicocvenancio** [comment]
As I noted in the gitter chat, since 0.6 some changes in how the proxy is configured make this issue pointless how I first framed it. 
My use case is more or less this, I am unsure right now if it is something we should leave as an option in the z2jh chart or leave to advanced user to build their own solution.

> I have a proxy in front of JupyterHub but it only enforces https if I set a redirect based on the X_Forwarded_Proto header. In the current chart for z2jh I can add that to the nginx configmap and it works. Hence I oppened jupyterhub/zero-to-jupyterhub-k8s#729 to set it as a field for the chart.
> 
> Looking at the changes since z2jh 0.6, however, I see nginx is taken out when tls termination in it is not set. So I'm wondering what is the best alternative:
> 
> Keep an nginx container in my own chart and configure it there
> Create a new https type that will keep the nginx alive for deploys that need an nginx that won't terminate tls.
> another option I haven't thought ...

**Comment by consideRatio** [comment]
Thank you for writing this up and reasoning about it @chicocvenancio, I lack foundational knowledge regarding this and won't therefore be able to reason much about this though!

**Comment by chicocvenancio** [comment]
Thanks for the comment @consideRatio.
My main worry is that supporting my use case in z2jh will add complexity to the configuration for all users. And I can solve the issues I have leaving the complexity in my own chart.
In the end, I think that if no else has this problem we should not implement changes on the chart. At best we briefly document this use case and solution.

**Comment by consideRatio** [comment]
We have stopped using nginx as a TLS termination pod, and is instead using traefik, which I've made sure we can configure very extensively if wanted.
