### ISSUE TITLE
Google cloud user / project changing

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/zero-to-jupyterhub-k8s#73]
We should document how to change users / projects within google cloud, as a part of setting up kubernetes with gcloud. Probably many users will have both a gmail and a .edu account. We should add explanations for:

`gcloud config set account <ACCOUNT>`
and
`gcloud config set project <PROJECT-ID>`

Importantly the project id must be the project ID, not just the project name.

**Comment by choldgraf** [comment]
@yuvipanda :)

**Comment by consideRatio** [comment]
This is relevant only if you have multiple clusters that you need to switch in between, I think it is too complex for this guide to support recommendations for.

Feel free to reopen, closing for now.
