### ISSUE TITLE
Note all resource limits in capacity planning

### ISSUE THREAD

**Issue by minrk** [jupyterhub/zero-to-jupyterhub-k8s#732]
Recently, Binder ran into a surprising autoscaling behavior when it hit the 110 pod-per-node limit that we didn't know about. Yesterday, I ran into the fact that GKE [only allows 16 persistent volumes per node](https://github.com/kubernetes/kubernetes/issues/24317). This is a bug that has a planned alpha fix [for kubernetes 1.11](https://github.com/kubernetes/features/issues/554).

We've accounted for CPU and RAM limits in our capacity planning docs, but there are other limits we aren't covering, and should include.

All the exhaustible resources I'm aware of right now:

- CPU
- RAM
- pods (110 by default)
- persistent volumes (16 by default, overridable sometimes, but not managed providers/GKE)

Some deployments may have to account for GPUs, etc.

**Comment by consideRatio** [comment]
This is still relevant, I'm embedding and summarizing this task into another issue though to get down to a manageable size of issues in this repo though.
