### ISSUE TITLE
Regarding JUPYTER_ENABLE_LAB environment variable

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#734]
#### I'm confused about the following section in the documentation.

![image](https://user-images.githubusercontent.com/3837114/41627350-444184f4-7420-11e8-894f-039d4ce534b4.png)

![image](https://user-images.githubusercontent.com/3837114/41627207-9648dbb8-741f-11e8-9e65-f4859052e7d8.png)

---

By inspection of the [`start-singleuser.sh`](https://github.com/jupyter/docker-stacks/commit/94657c261683d86073655ee50d1177428c74b831) script included in the `jupyter/base-notebook` image, it looks like `JUPYTER_ENABLE_LAB` has meaning there but nowhere else. But we ensure to use `jupyter-labhub` by default instead of `start-singleuser.sh` by setting `c.KubeSpawner.cmd = ['jupyter-labhub']`. If we would use `start-singleuser.sh` with `JUPYTER_ENABLE_LAB` the script would execute `jupyter labhub` (*no hyphen*).

__Question__
Is there a difference between `jupyter-labhub` and `jupyter labhub`?

**Comment by manics** [comment]
This confused me a lot when I first tried jupyterlab. At the moment I'm using only `singleuser.cmd: jupyter-labhub`, no extraEnv, defaultUrl or extraConfig.

**Comment by cam72cam** [comment]
https://github.com/jupyter/docker-stacks/pull/622

**Comment by clkao** [comment]
`JUPYTER_ENABLE_LAB` should be all you need for enabling lab, if you are using images based on docker-stacks ones.

**Comment by consideRatio** [comment]
I think so Simon! :heart:
