### ISSUE TITLE
Document known zero to jupyterhub installations in the wild

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/zero-to-jupyterhub-k8s#737]
Zero to JupyterHub is getting good use in a lot of places! We should reach out to people using them, and make a list to feature on the website.

**Comment by consideRatio** [comment]
This issue is a bit hard to get actionable about and is perhaps better suited to bring up in a team meeting or similar? I'll close this issue at this point.

Related, we have the "Used by" section which we can ask people to add themselves to.
