### ISSUE TITLE
Curate list of deployment methods for z2jh

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/zero-to-jupyterhub-k8s#738]
Many users have experimented with many different ways to automate deployment of z2jh. While it's too early for us to have an 'official' solution of any sort, we should collect list of deployments so people can peruse them.

Examples:  

https://github.com/berkeley-dsep-infra/data8xhub
https://github.com/berkeley-dsep-infra/datahub/

etc

**Comment by consideRatio** [comment]
@yuvipanda I'm going through issues from oldest to newer, and the amount is just too great. I think this issue may never be found except for a person issue triaging, and figured if we can close it? I'm a bit conflicted but I think my goal of getting down to a more manageable size of issues feels very important to me.

Goal:
- Triage below 100 issues
- Don't compromise too much to get there for example by removing valid issues etc.

I'll close this and reference the wish to have such list of curated deployments.
