### ISSUE TITLE
Document common hardware extensions

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/zero-to-jupyterhub-k8s#74]
We should have sample helmcharts for common deployments so that users know the parameters for controlling their nodes. E.g., right now I can't find any place that tells users how to turn off persistent storage, even though we reference the existence of persistent storage in the docs.

**Comment by yuvipanda** [comment]
I'm just going to file a separate issue about turning off storage, since this is too broad I think. File individual issues about other things we should have? I just added a PR for changing total number of nodes.
