### ISSUE TITLE
continuous-image-puller not being run in node-pools

### ISSUE THREAD

**Issue by vanpelt** [jupyterhub/zero-to-jupyterhub-k8s#766]
I have a 1.9.7-gke.3 GKE cluster with a default-pool and a couple node pools with GPU's enabled that auto-scale.  Only the default pool is running the DaemonSet, new nodes in the other pools don't get the puller scheduled on them.  Any guidance on what might be limiting the DaemonSet from being scheduled would be greatly appreciated.

**Comment by consideRatio** [comment]
Ah!!!! Yes!

We need to add a toleration to allow them to schedule / execute on the GPU nodes that are tainted to disallow any other pods to show up on them.

Use the kubectl edit command on the contineous image puller daemonset, add a toleration to the pod spec. Got to go sorry I could not be more forthcoming right now, out of time --- I'll fix this in the future by default, but the patch is a quickfix solution.

**Comment by vanpelt** [comment]
Thanks @consideRatio super helpful.

**Comment by vanpelt** [comment]
I ended up adding the following to the spec for the puller:

```yaml
   tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Exists
```

When this is added we may also want to be able to apply nodeAffinity to the image-puller, but it's less important than getting the puller onto the the new nodes.

**Comment by consideRatio** [comment]
ah! there are two kinds of nodeAffinities, a "require" (this is also what nodeSelector is about), and "prefer".

i think you must use require for daemonsets. currently we are pulling user-images for all nodes. in a PR im working on, im adding supprt to consider node labels separating user nodes from core nodes (hub, proxy). one idea ill implement thanks to your suggestion would be to pull the user images only on user nodes if it is required for users to be on user nodes (also configurable in pr).

how do you imagine nodeAffinity on the DS may be useful?

**Comment by consideRatio** [comment]
thank you @vanpelt for taking the time to think and communicate about this! i appreciate it!

btw logic of the two kinds of pullers is almost identical, and they share  lot of the codebase, it will be simple to make them function efficiently onboth at the same time.

oh... ive added support for aetting tolerations on the singleuser pods, ill simply use the same rolerations for the puller pods ^^ (in that pr)
