### ISSUE TITLE
option to remove user along with pvc in admin

### ISSUE THREAD

**Issue by clkao** [jupyterhub/zero-to-jupyterhub-k8s#769]
jupyterhub might not have hooks for account deletion in admin yet.  but admin ui should one day allow removing user along with all resources allocated, including pvc.

**Comment by daldridge-cs** [comment]
I'll add that I'd like to be able to remove the pvc (for a named server) via the hub REST API, not just UI.

**Comment by consideRatio** [comment]
While I agree that would be cool, I think it is a bit too complicated feature to develop and maintain.

1. It would modify JupyterHub templates that change in JupyterHub itself over time.
2. It would need to tackle tricky complexities like attempts to delete the PVC timed out, failed etc, and this is not something we can delegate to KubeSpawner either, so its a lot of logic suddenly making k8s API server request which means we need to write code with the kubernetes/python-client etc

Sorry for the let down =/ If you come up with something that seems sustainable to develop and maintain, please open a new issue with the suggestion!
