### ISSUE TITLE
Azure Installation Issues Related to AKS Upgrades of RBAC

### ISSUE THREAD

**Issue by jkuruzovich** [jupyterhub/zero-to-jupyterhub-k8s#772]
I've been working through the installation process on Azure as part of a tutorial.  There seem to be a few updates related to AKS related to the [general availability](
https://azure.microsoft.com/en-us/blog/azure-kubernetes-service-aks-ga-new-regions-new-features-new-productivity/) that makes changes to the documentation needed.   Here are the things that I changed in order to get it to work:
(1) Removed the specification of Kubernetes version.  I don't think this is necessarily needed but it was one of the changes.
(2) I did have to run the second command on the [Helm documentation related to clusterolebinding](https://zero-to-jupyterhub.readthedocs.io/en/latest/setup-helm.html#helm-rbac). 
(3) I removed the section of the Jupyterhub config file which disabled RBAC. 
```
rbac:
   enabled: false
```
Check out the carme.ai tutorial that installs Jupyterhub on Kubernetes in 2 commands using Azure Cloud Shell! 
[https://carme.ai/blog/installing-jupyterhub-azure-cloudshell/](https://carme.ai/blog/installing-jupyterhub-azure-cloudshell/)

**Comment by consideRatio** [comment]
Wooo!! This is very valuable! Thank you @jkuruzovich for taking the time to write this down in an issue!
