### ISSUE TITLE
The whitelist section of the User Management page is missing the example

### ISSUE THREAD

**Issue by verdurin** [jupyterhub/zero-to-jupyterhub-k8s#773]
The page at:

http://zero-to-jupyterhub.readthedocs.io/en/v0.5-doc/authentication.html#adding-a-whitelist

looks truncated, where the example for adding users to a whitelist should be.

**Comment by consideRatio** [comment]
Hey @verdurin! You are right that is a mistake. If you look at the 0.6 version or the latest version of the documentation, it seems to be fixed. You can select the version of the docs you want too look at in the lower right corner of the webpage.

**Comment by verdurin** [comment]
@consideRatio ah yes, I didn't spot that I was on an older version. Thanks for the quick response.

**Comment by consideRatio** [comment]
You're welcome, glad to be of help =)
