### ISSUE TITLE
DOC: clarify what to do if the clusterrolebinding email address isn't correct

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/zero-to-jupyterhub-k8s#779]
In the GCP instructions, a common problem is that people accidentally use the wrong email address for "clusterrolebinding". We should document how to spot this and what to do if this is the case.

https://zero-to-jupyterhub.readthedocs.io/en/latest/google/step-zero-gcp.html

**Comment by choldgraf** [comment]
```
### If you listed the wrong email account on this step:
kubectl create clusterrolebinding cluster-admin-binding \
    --clusterrole=cluster-admin \
    --user=<WRONG-email>

Run this:
kubectl delete clusterrolebinding cluster-admin-binding

then:
kubectl create clusterrolebinding cluster-admin-binding \
    --clusterrole=cluster-admin \
    --user=<RIGHT-email>
```

**Comment by choldgraf** [comment]
errors like:

Error: namespaces "jhub" is forbidden: User "system:serviceaccount:kube-system:default" cannot get namespaces in the namespace "jhub": Unknown user "system:serviceaccount:kube-system:default"

**Comment by consideRatio** [comment]
I considered options to delete->create. Edit and patch, but dunno, I think create / delete is best. Will update the docs.

## Edit
Will require knowledge about how to save etc in nano/vim, not great...

```
kubectl edit clusterrolebinding cluster-admin-binding
```

![image](https://user-images.githubusercontent.com/3837114/43699713-2a2e0d80-9950-11e8-8f72-405697205e72.png)

## Patch
The patch command can be a one liner, but I did not manage to get it shorter than this, which could been done if we didn't want to change the value of the name field which is special, as it behaves as a way to select what array entry to modify normally.

```
kubectl patch clusterrolebinding cluster-admin-binding --type=json --patch '[{"op":"replace", "path":"/subjects/0/name", "value":"my-correct-email@gmail.com"}]'
```

**Comment by consideRatio** [comment]
Solved
