### ISSUE TITLE
(docs) How to `helm upgrade` after repo2docker?

### ISSUE THREAD

**Issue by superquest** [jupyterhub/zero-to-jupyterhub-k8s#785]
[These directions work beautifully until step 8](http://zero-to-jupyterhub.readthedocs.io/en/latest/user-environment.html#build-a-custom-docker-image-with-repo2docker.)

Step 8 just says "Tell helm to update JupyterHub to use this configuration. Use the standard method to [apply the changes](http://zero-to-jupyterhub.readthedocs.io/en/latest/extending-jupyterhub.html#apply-config-changes) to the config."

Running exactly `helm upgrade <YOUR_RELEASE_NAME> jupyterhub/jupyterhub --version=v0.6 -f config.yaml` as instructed (with my actual release name, of course) doesn't produce any errors, but the contents of the repo I fed `repo2docker` don't show up in the deployed JupyterHub instance. Do I need to change any of the parameters? I tried `gcr.io/<PROJECT-NAME>/<IMAGE-NAME>` but that doesn't work ...

And just for a sanity check, step 4 seems to work because running `jupyter-repo2docker --user-name=jovyan --image=gcr.io/<PROJECT-NAME>/<IMAGE-NAME>:<TAG> <YOUR-GITHUB-REPOSITORY>` does successfully spin up a JupyterHub server accessible locally, and all the notebooks contained in my repo are visible.

Relevant portion of my config.yaml is exactly as instructed during step 6 (of course I have substituted real values for <project-name> & <image-name> & <tab> in my real config).

## Contents of `config.yaml`
```
singleuser:
  image:
    name: gcr.io/<project-name>/<image-name>
    tag: <tag>
```

**Comment by superquest** [comment]
Related to https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/145

**Comment by superquest** [comment]
What does `--version=v0.6` correspond to in the `help upgrade` command above?

**Comment by superquest** [comment]
When I describe the pod in this `Init:ImagePullBackOff` state I get the following:

`$ kubectl --namespace=my-project-namespace describe pod pre-pull-my-project-jupyterhub-10-1532456381-6b2pw`

Name:           pre-pull-my-project-jupyterhub-10-1532456381-6b2pw
Namespace:      my-project-namespace
Node:           gke-corps-default-pool-b69f63f1-0g5l/10.142.0.2
Start Time:     Tue, 24 Jul 2018 13:19:43 -0500
Labels:         app=jupyterhub
                component=image-puller
                controller-revision-hash=4193363156
                heritage=Tiller
                pod-template-generation=1
                release=my-project-jupyterhub
Annotations:    <none>
Status:         Pending
IP:             10.16.1.30
Controlled By:  DaemonSet/pre-pull-my-project-jupyterhub-10-1532456381
Init Containers:
  image-pull-singleuser:
    Container ID:  
    Image:         gcr.io/my-project/foo:6ba7bdd
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
      -c
      echo "Pulling complete"
    State:          Waiting
      Reason:       ImagePullBackOff
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:         <none>
  image-pull-metadata-block:
    Container ID:  
    Image:         jupyterhub/k8s-network-tools:v0.6
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
      -c
      echo "Pulling complete"
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:         <none>
Containers:
  pause:
    Container ID:   
    Image:          gcr.io/google_containers/pause:3.0
    Image ID:       
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:         <none>
Conditions:
  Type           Status
  Initialized    False 
  Ready          False 
  PodScheduled   True 
Volumes:         <none>
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/disk-pressure:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute
                 node.kubernetes.io/unreachable:NoExecute
Events:
  Type     Reason   Age               From                                           Message
  ----     ------   ----              ----                                           -------
  Normal   Pulling  6m (x4 over 8m)   kubelet, gke-corps-default-pool-b69f63f1-0g5l  pulling image "gcr.io/my-project/foo:6ba7bdd"
  Warning  Failed   6m (x4 over 8m)   kubelet, gke-corps-default-pool-b69f63f1-0g5l  Failed to pull image "gcr.io/my-project/foo:6ba7bdd": rpc error: code = Unknown desc = Error: Status 405 trying to pull repository my-project/foo: "v1 Registry API is disabled. If you are not explicitly using the v1 Registry API, it is possible your v2 image could not be found. Verify that your image is available, or retry with `dockerd --disable-legacy-registry`. See https://cloud.google.com/container-registry/docs/support/deprecation-notices"
  Warning  Failed   6m (x4 over 8m)   kubelet, gke-corps-default-pool-b69f63f1-0g5l  Error: ErrImagePull
  Normal   BackOff  6m (x6 over 8m)   kubelet, gke-corps-default-pool-b69f63f1-0g5l  Back-off pulling image "gcr.io/my-project/foo:6ba7bdd"
  Warning  Failed   2m (x21 over 8m)  kubelet, gke-corps-default-pool-b69f63f1-0g5l  Error: ImagePullBackOff

**Comment by consideRatio** [comment]
Ah I bet you are spot on with this analysis.

You must somehow allow your cluster to access your private gcr.io repository, this issue would go away by using a public image repository or by setting up access for the cluster to the image repository somehow. 

I have done so myself *once*, but I've forgot how I did it so I'll let you do the googling - just wanted to let you know I'm confident you are on the right track to solving this.

**Comment by superquest** [comment]
Well I've tried all kinds of things and can't get my notebooks to show up.

**Comment by superquest** [comment]
Well somehow I ended up figuring it out. I think the key was moving from Google's container registry to Docker Registry.

The mysteries of life ...
