### ISSUE TITLE
Consider adding `kubectl edit deployment` to the debug section + presentations

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/zero-to-jupyterhub-k8s#788]
At the PEARC tutorial, @aculich and I stepped through some pieces of `kubectl edit deployment`. I thought that it was a fairly useful way to teach people how the helm config and the helm chart interact with each other (and so that people can see what we mean by the "JupyterHub Helm Chart"). What do folks think about us including a section on this in the z2jh docs, as well as into our tutorial template?

**Comment by choldgraf** [comment]
+1 to à better way of showing the same thing, it's mostly just introspecting the yaml I thought would be useful

**Comment by betatim** [comment]
`kubectl get pod -o yaml jupyter-jupyterlab-2djupyterlab-2ddemo-2doouctp01 ` or `kubectl get deployment -o yaml` does it .

**Comment by consideRatio** [comment]
I'll close this and make a note about a revision of the debug section is wanted with for example `kubectl edit`, and I'll add `kubectl exec` myself which is awesome.
