### ISSUE TITLE
Code blocks in the "Tips and command snippets" section don't render properly

### ISSUE THREAD

**Issue by evertrol** [jupyterhub/zero-to-jupyterhub-k8s#798]
The code blocks in the "Tips and command snippets" section render as indented, but otherwise normal, text; not as code. See https://zero-to-jupyterhub.readthedocs.io/en/latest/tips.html
It looks like this is because of missing double colons `::`, or a `.. code-block:: bash` directive as used elsewhere.

(The potentially most problematic issue is that `--` for long options renders as an n-dash, instead of two dashes, making it not possible to copy-paste the occasional line.)

Funnily enough, when viewed on GitHub directly, it renders better: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/doc/source/tips.rst . I guess GitHub's ReST parser is quite lenient.

I have not found any other pages that have this problem (but I haven't gone through all of them yet).

Since this is a relatively straightforward change, I'd be happy to put in a PR for this.

**Comment by consideRatio** [comment]
@evertrol :heart: :heart: :heart: :D
