### ISSUE TITLE
Per-user (or per-group) custom resources

### ISSUE THREAD

**Issue by prcastro** [jupyterhub/zero-to-jupyterhub-k8s#808]
I was following the tutorial but it's not clear how to specify resources for a specific user. It is mentioned that power users can get more resources, but I'm not sure how.

On our current deployment, each user has an AWS machine associated with the Jupyter Notebook, and this can be customized in a per-user basis. How can I do the same thing using JupyterHub? Or even giving the users the ability to spawn a notebook with custom resources by themselves (like in this setup https://helpdesk.strw.leidenuniv.nl/wiki/doku.php?id=institute_lorentz:institutelorentz_maris_slurm_jupyterhub)?

**Comment by woop** [comment]
Agreed. The documentation states that user requirements may vary in terms of cpu/mem, but how can we actually set that? It's not clear. 

It seems as if all users share the exact same configuration.

**Comment by prcastro** [comment]
Found this: https://github.com/jupyterhub/kubespawner/pull/137
