### ISSUE TITLE
Annotations on single user notebook

### ISSUE THREAD

**Issue by jacobtomlinson** [jupyterhub/zero-to-jupyterhub-k8s#810]
I'm trying to add an annotation to all notebooks which are created, however I can't seem to find where to configure this in the chart config. The hub, proxy and ingress all have annotation options, but the singleuser section doesn't.

Am I missing something or has this not been implemented yet?

_NB if I could do this dynamically based on username that would be even better. But that may be a bigger ask and invoke KubeSpawner._

**Comment by jacobtomlinson** [comment]
@yuvipanda do you have any thoughts on this?

**Comment by manics** [comment]
KubeSpawner has `extra_annotations`: https://github.com/jupyterhub/kubespawner/blob/v0.9.0b2/kubespawner/spawner.py#L379

**Comment by jacobtomlinson** [comment]
@manics that's great. How does that translate through to the `values.yaml` file in here?

**Comment by jacobtomlinson** [comment]
I can't see a way to do it from the chart so I've raised #882.
