### ISSUE TITLE
Nudge jupyter/docker-stacks to use `jupyterhub==0.9.*`

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#818]
I'm writing updated documentation for the upcoming 0.7 release of this Helm chart, and would like to be able to claim that users of this Helm chart can choose from all images within the [jupyter/docker-stacks repo](https://github.com/jupyter/docker-stacks). They currently can't though, as the images install `jupyterhub==0.8.*` instead of `jupyterhub==0.9.*`, so they would need to build and publish their own...

I created a issue to confirm a bump should be fine: https://github.com/jupyter/docker-stacks/issues/692

After bumping the jupyterhub install in the base-notebook image, the derivative images needs to be rebuilt as well. I don't know how all this is done, perhaps *you* feel like helping out and move this along?

:heart:

**Comment by manics** [comment]
`0.8.*` docker-stacks images should be compatible with a `0.9.*` hub: https://gitter.im/jupyterhub/jupyterhub?at=5b48983fc2d95c60f4d6bd37

**Comment by betatim** [comment]
Docker stacks are now on 0.9 https://github.com/jupyter/docker-stacks/pull/694

**Comment by consideRatio** [comment]
Wieee Thanks!
