### ISSUE TITLE
Jupyterhub fails to launch server: 500 Internal Server Error

### ISSUE THREAD

**Issue by vishwesh5** [jupyterhub/zero-to-jupyterhub-k8s#819]
Hi everyone!
Going through the documentation, I setup a default jupyterhub k8 cluster on Google cloud and it worked perfectly fine. Later on, I created my own docker image where I built opencv with opencv_contrib from scratch and pushed the docker image on gcr.io. I then referred to the **extending jupyterhub** section in the documentation and followed the steps specified to revise my `config.yaml` file. I then relaunch my jupyterhub server and after waiting for several minutes for the server to start, I get the following error:

> 500 : Internal Server Error
> Failed to start your server. Please contact admin.
> 
> You can try restarting your server from the home page.

## Contents of `config.yaml`
```
proxy:
    secretToken: "my secret token"
singleuser:
    image:
        name: docker image on gcr.io
        tag: version1
```
I was earlier having a doubt that the docker image I made was somehow screwed up but when I built it on an AWS machine using the [dockerfile](https://github.com/vishwesh5/OpenCV-Docker/blob/master/Dockerfile) and it worked fine.
Another thing is that when I use `jupyter-repo2docker`, the process stops in mid as there is no more space left on the device. Now I don't want to add more nodes as that will be more expensive, I thought maybe I should add SSD but since I first had no clue how to do that and second the docker image on gcr.io was occupying only 5 GB, I thought that maybe more disk space is not required at all.
Here is the output I get from `df -h` on gcloud:
```
Filesystem      Size  Used Avail Use% Mounted on
overlay          31G   24G  7.3G  77% /
tmpfs           848M     0  848M   0% /dev
tmpfs           848M     0  848M   0% /sys/fs/cgroup
/dev/sdb1       4.8G   82M  4.5G   2% /home
overlayfs       1.0M  100K  924K  10% /etc/ssh/keys
tmpfs           848M  712K  847M   1% /run/metrics
/dev/sda1        31G   24G  7.3G  77% /etc/hosts
shm              64M     0   64M   0% /dev/shm
overlayfs       1.0M  100K  924K  10% /etc/ssh/ssh_host_dsa_key
tmpfs           848M     0  848M   0% /run/google/devshell
```
Can someone please help me out with this?
Thanks in advance

**Comment by vishwesh5** [comment]
This is the output I get using `get pod`:
```
kubectl --namespace=test-cv4faces-jupyterhub get pod
NAME                                                   READY     STATUS             RESTARTS   AGE
hub-76cf4d8689-hqjct                                   1/1       Running            0          36m
jupyter-test                                           0/1       CrashLoopBackOff   3          1m
pre-pull-test-cv4faces-jupyterhub-1-1533476982-k2r27   1/1       Running            0          52m
pre-pull-test-cv4faces-jupyterhub-1-1533476982-nq6tv   1/1       Running            0          52m
pre-pull-test-cv4faces-jupyterhub-1-1533476982-tlxxd   1/1       Running            0          52m
pre-pull-test-cv4faces-jupyterhub-2-1533477391-489c4   1/1       Running            0          45m
pre-pull-test-cv4faces-jupyterhub-2-1533477391-cfcgh   1/1       Running            0          45m
pre-pull-test-cv4faces-jupyterhub-2-1533477391-ptqmd   1/1       Running            0          45m
pre-pull-test-cv4faces-jupyterhub-3-1533477757-d94k6   1/1       Running            0          37m
pre-pull-test-cv4faces-jupyterhub-3-1533477757-rzn8h   1/1       Running            0          37m
pre-pull-test-cv4faces-jupyterhub-3-1533477757-tgrvg   1/1       Running            0          37m
proxy-67f48d9997-8zc42                                 2/2       Running            0          51m
```
Anyway related to https://github.com/jupyterhub/helm-chart/issues/62?

**Comment by consideRatio** [comment]
can you look at the logs of jupyter-test that is crashing? or okay it wont have logs but if you run

`kubectl describe pod ...`

**Comment by vishwesh5** [comment]
Thank you for the reply @consideRatio . I am re-building the docker image. Once that is ready I will launch the server and send over the logs. 
Thanks again!
Vishwesh

**Comment by vishwesh5** [comment]
Hi again @consideRatio !
This is what I get from `kubectl describe pod ...`:
`Error from server (NotFound): pods "..." not found`
You can check my [revised Dockerfile](https://github.com/vishwesh5/OpenCV-Docker/blob/master/Dockerfile) as well.
The error the jupyterhub is giving now is:
```
500 : Internal Server Error
Failed to reach your server. Please try again later. Contact admin if the issue persists.

You can try restarting your server from the home page.
```
Also, running `kubectl --namespace=test-cv4faces-jupyterhub get pod` gives:
```
NAME                                                   READY     STATUS        RESTARTS   AGE
hub-775587b746-9wt8k                                   1/1       Running       0          15m
jupyter-test                                           0/1       Terminating   2          1m
pre-pull-test-cv4faces-jupyterhub-1-1533557848-22x7t   1/1       Running       0          25m
pre-pull-test-cv4faces-jupyterhub-1-1533557848-64n6k   1/1       Running       0          25m
pre-pull-test-cv4faces-jupyterhub-1-1533557848-z9vbh   1/1       Running       0          25m
pre-pull-test-cv4faces-jupyterhub-1-1533558279-68t26   1/1       Running       0          17m
pre-pull-test-cv4faces-jupyterhub-1-1533558279-96724   1/1       Running       0          17m
pre-pull-test-cv4faces-jupyterhub-1-1533558279-fxzwg   1/1       Running       0          17m
proxy-6bdf9ff5bc-cww4g                                 2/2       Running       0          15m
```

**Comment by consideRatio** [comment]
@vishwesh5 ah I meant for you to write `kubectl describe pod jupyter-test`

Hey, set the default namespace so you dont have to write it out, and then run the describe command

```
kubectl config set-context $(kubectl config current-context) --namespace test-cv4faces-jupyterhub
kubectl describe pod jupyter-test
```

**Comment by vishwesh5** [comment]
Sorry @consideRatio about that, new to this. Please find the output below:

```
Name:         jupyter-test
Namespace:    test-cv4faces-jupyterhub
Node:         gke-test-cv4faces-cluste-default-pool-7198f95e-hrkp/10.128.0.2
Start Time:   Mon, 06 Aug 2018 12:53:37 +0000
Labels:       app=jupyterhub
              component=singleuser-server
              heritage=jupyterhub
Annotations:  hub.jupyter.org/username=test
Status:       Running
IP:           10.48.2.11
Init Containers:
  block-cloud-metadata:
    Container ID:  docker://50123375a6748a03d93a4d441901ea5bdcb3d660b8c254224826d491f5a16221
    Image:         jupyterhub/k8s-network-tools:v0.6
    Image ID:      docker-pullable://jupyterhub/k8s-network-tools@sha256:271e7f7c9b4aa319788ca1bbce3428cad7b9da852a8c3af49178abcc2cc45b28
    Port:          <none>
    Command:
      iptables
      -A
      OUTPUT
      -d
      169.254.169.254
      -j
      DROP
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Mon, 06 Aug 2018 12:53:55 +0000
      Finished:     Mon, 06 Aug 2018 12:53:55 +0000
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:         <none>
Containers:
  notebook:
    Container ID:  docker://5efb329f6e91d31b71a941281fecf873433abdaf290e71354ee88a0877e62a5d
    Image:         gcr.io/eng-spot-212108/test-cv4faces-image:version2
    Image ID:      docker-pullable://gcr.io/eng-spot-212108/test-cv4faces-image@sha256:e7baf466e96c4865f50b442b49ca91fcb00f3de59c02a43c756e291ffd69161b
    Port:          8888/TCP
    Args:
      jupyterhub-singleuser
      --ip="0.0.0.0"
      --port=8888
    State:          Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Mon, 06 Aug 2018 12:56:50 +0000
      Finished:     Mon, 06 Aug 2018 12:56:50 +0000
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Mon, 06 Aug 2018 12:55:29 +0000
      Finished:     Mon, 06 Aug 2018 12:55:29 +0000
    Ready:          False
    Restart Count:  5
    Requests:
      memory:  1073741824
    Environment:
      EMAIL:                          test@local
      GIT_AUTHOR_NAME:                test
      GIT_COMMITTER_NAME:             test
      JUPYTERHUB_API_TOKEN:           284ac1090eac420f850f94a0a64b79db
      JPY_API_TOKEN:                  284ac1090eac420f850f94a0a64b79db
      JUPYTERHUB_ADMIN_ACCESS:        1
      JUPYTERHUB_CLIENT_ID:           user-test
      JUPYTERHUB_HOST:                
      JUPYTERHUB_OAUTH_CALLBACK_URL:  /user/test/oauth_callback
      JUPYTERHUB_USER:                test
      JUPYTERHUB_API_URL:             http://10.51.246.119:8081/hub/api
      JUPYTERHUB_BASE_URL:            /
      JUPYTERHUB_SERVICE_PREFIX:      /user/test/
      MEM_GUARANTEE:                  1073741824
    Mounts:
      /home/jovyan from volume-test (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from no-api-access-please (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          False 
  PodScheduled   True 
Volumes:
  volume-test:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  claim-test
    ReadOnly:   false
  no-api-access-please:
    Type:        EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:      
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                 Age              From                                                          Message
  ----     ------                 ----             ----                                                          -------
  Normal   Scheduled              3m               default-scheduler                                             Successfully assigned jupyter-test to gke-test-cv4faces-cluste-default-pool-7198f95e-hrkp
  Normal   SuccessfulMountVolume  3m               kubelet, gke-test-cv4faces-cluste-default-pool-7198f95e-hrkp  MountVolume.SetUp succeeded for volume "no-api-access-please"
  Normal   SuccessfulMountVolume  3m               kubelet, gke-test-cv4faces-cluste-default-pool-7198f95e-hrkp  MountVolume.SetUp succeeded for volume "pvc-01c3a951-9976-11e8-b54e-42010a800122"
  Normal   Pulled                 3m               kubelet, gke-test-cv4faces-cluste-default-pool-7198f95e-hrkp  Container image "jupyterhub/k8s-network-tools:v0.6" already present on machine
  Normal   Created                3m               kubelet, gke-test-cv4faces-cluste-default-pool-7198f95e-hrkp  Created container
  Normal   Started                3m               kubelet, gke-test-cv4faces-cluste-default-pool-7198f95e-hrkp  Started container
  Normal   Pulled                 2m (x4 over 3m)  kubelet, gke-test-cv4faces-cluste-default-pool-7198f95e-hrkp  Container image "gcr.io/eng-spot-212108/test-cv4faces-image:version2" already present on machine
  Normal   Created                2m (x4 over 3m)  kubelet, gke-test-cv4faces-cluste-default-pool-7198f95e-hrkp  Created container
  Normal   Started                2m (x4 over 3m)  kubelet, gke-test-cv4faces-cluste-default-pool-7198f95e-hrkp  Started container
  Warning  BackOff                1m (x8 over 3m)  kubelet, gke-test-cv4faces-cluste-default-pool-7198f95e-hrkp  Back-off restarting failed container
```

**Comment by vishwesh5** [comment]
Also, when I build the Docker image from the Dockerfile (`docker build -t test-cv4faces:version6 -f Dockerfile` ), run it (`docker run -it test-cv4faces:version6`)  and then type (`jupyterhub`), it works fine:
```
root@e795ca15db60:/# jupyterhub
[I 2018-08-06 13:01:10.212 JupyterHub app:871] Writing cookie_secret to /jupyterhub_cookie_secret
[I 2018-08-06 13:01:10.253 alembic.runtime.migration migration:117] Context impl SQLiteImpl.
[I 2018-08-06 13:01:10.254 alembic.runtime.migration migration:122] Will assume non-transactional DDL.
[I 2018-08-06 13:01:10.261 alembic.runtime.migration migration:327] Running stamp_revision  -> 3ec6993fe20c
[W 2018-08-06 13:01:10.342 JupyterHub app:955] No admin users, admin interface will be unavailable.
[W 2018-08-06 13:01:10.342 JupyterHub app:956] Add any administrative users to `c.Authenticator.admin_users` in config.
[I 2018-08-06 13:01:10.343 JupyterHub app:983] Not using whitelist. Any authenticated user will be allowed.
[I 2018-08-06 13:01:10.369 JupyterHub app:1528] Hub API listening on http://127.0.0.1:8081/hub/
[W 2018-08-06 13:01:10.369 JupyterHub proxy:415] 
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.
    
[W 2018-08-06 13:01:10.370 JupyterHub proxy:456] Running JupyterHub without SSL.  I hope there is SSL termination happening somewhere else...
[I 2018-08-06 13:01:10.370 JupyterHub proxy:458] Starting proxy @ http://*:8000/
13:01:10.686 - info: [ConfigProxy] Proxying http://*:8000 to (no default)
13:01:10.689 - info: [ConfigProxy] Proxy API at http://127.0.0.1:8001/api/routes
13:01:10.858 - info: [ConfigProxy] 200 GET /api/routes 
[W 2018-08-06 13:01:10.858 JupyterHub proxy:304] Adding missing default route
[I 2018-08-06 13:01:10.859 JupyterHub proxy:370] Adding default route for Hub: / => http://127.0.0.1:8081
13:01:10.867 - info: [ConfigProxy] Adding route / -> http://127.0.0.1:8081
13:01:10.868 - info: [ConfigProxy] 201 POST /api/routes/ 
[I 2018-08-06 13:01:10.869 JupyterHub app:1581] JupyterHub is now running at http://:8000/
```

**Comment by consideRatio** [comment]
@vishwesh5 it seems from `Back-off restarting failed container` that the container starts, but it crashes. Then there will be some logs to find in the pod.

`kubectl logs jupyter-test`

**Comment by vishwesh5** [comment]
Thanks a lot @consideRatio for replying. Here's the output:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/traitlets/traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'runtime_dir'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/jupyterhub-singleuser", line 6, in <module>
    main()
  File "/usr/local/lib/python3.5/dist-packages/jupyterhub/singleuser.py", line 455, in main
    return SingleUserNotebookApp.launch_instance(argv)
  File "/usr/local/lib/python3.5/dist-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/notebook/notebookapp.py", line 1600, in initialize
    self.init_configurables()
  File "/usr/local/lib/python3.5/dist-packages/notebook/notebookapp.py", line 1293, in init_configurables
    connection_dir=self.runtime_dir,
  File "/usr/local/lib/python3.5/dist-packages/traitlets/traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "/usr/local/lib/python3.5/dist-packages/traitlets/traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "/usr/local/lib/python3.5/dist-packages/jupyter_core/application.py", line 99, in _runtime_dir_default
    ensure_dir_exists(rd, mode=0o700)
  File "/usr/local/lib/python3.5/dist-packages/jupyter_core/utils/__init__.py", line 13, in ensure_dir_exists
    os.makedirs(path, mode=mode)
  File "/usr/lib/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/.local'
```

**Comment by vishwesh5** [comment]
I can understand from this that there is an issue with permissions. One obvious solution and a bad one is to give sudo permission but what amazes me is that in docker everything is directly sudo so why should I give sudo permissions separately? Second, let's say that I do use sudo, it's a very insecure solution. Any clue what I should do?
Thanks

**Comment by vishwesh5** [comment]
Hi @consideRatio ! So I modified my dockerfile and shifted my installed files to `opt` directory, now I am getting a new error:
```
container_linux.go:247: starting container process caused "exec: \"jupyterhub-singleuser\": executable file not found in $PATH"
```
I tried deleting and setting up the cluster again but still the same error. When I run the docker image, this is what I get from `echo $PATH`:
```
/opt/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```
Any ideas?

**Comment by consideRatio** [comment]
@vishwesh5 

Ah, well lets stay away from sudo, that caused the issue with "executable not found" and will be a mess.

But, the issue may be that you have some configuration error in general, c.DockerSpawner should not be used for the zero-to-jupyterhub-k8s deployment of jupyterhub, c.KubeSpawner is the spawner that works well here.

Perhaps you can paste your `config.yaml`?
Where did you configure that jupyterhub_config.py ? Are you building a custom hub image and giving the hub that file?

**Comment by vishwesh5** [comment]
So I tested out with the new docker image, and again this time I am facing the same error:
```
 File "/opt/anaconda3/lib/python3.6/site-packages/traitlets/traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'runtime_dir'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/bin/jupyterhub-singleuser", line 6, in <module>
    main()
  File "/opt/anaconda3/lib/python3.6/site-packages/jupyterhub/singleuser.py", line 455, in main
    return SingleUserNotebookApp.launch_instance(argv)
  File "/opt/anaconda3/lib/python3.6/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/opt/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.6/site-packages/notebook/notebookapp.py", line 1535, in initialize
    self.init_configurables()
  File "/opt/anaconda3/lib/python3.6/site-packages/notebook/notebookapp.py", line 1233, in init_configurables
    connection_dir=self.runtime_dir,
  File "/opt/anaconda3/lib/python3.6/site-packages/traitlets/traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "/opt/anaconda3/lib/python3.6/site-packages/traitlets/traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "/opt/anaconda3/lib/python3.6/site-packages/jupyter_core/application.py", line 99, in _runtime_dir_default
    ensure_dir_exists(rd, mode=0o700)
  File "/opt/anaconda3/lib/python3.6/site-packages/jupyter_core/utils/__init__.py", line 13, in ensure_dir_exists
    os.makedirs(path, mode=mode)
  File "/opt/anaconda3/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/opt/anaconda3/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/opt/anaconda3/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/opt/anaconda3/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/.local'
```
I can't figure out where `/.local` is coming from.

**Comment by consideRatio** [comment]
I think this is a bit hard for me to figure this out, I don't know all the ways things can go wrong when building a new image for the user. I'd recommend that you look at the images in the jupyter/docker-stacks and make small changes until it breaks. Or perhaps build from one of those images instead of from Ubuntu 16.04?

Note that no additional configuration of the jupyterhub can be made on the images that will be used for users arriving, such configuration must have been done in advance.

This issue I just created, about needing to document various things, can be useful to read as it gives a primitive intro to how all the configuration is done.
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/826

**Comment by consideRatio** [comment]
Yes for sure this is what I recommend:

Make sure you can run this image, then build on top of it some steps at the time, whenever it breaks you will know better what went wrong: https://github.com/jupyter/docker-stacks/tree/master/base-notebook

**Comment by consideRatio** [comment]
You are very welcome, it was all new to me not so long ago as well =)
I'll close this issue for now as I now consider this a matter where others does not have to get involved. If you write here I'll read and respond though!

Good luck!

**Comment by vishwesh5** [comment]
Hi again @consideRatio !
Good news first, I was able to have the hub up and running. Now for the bad news part, when I login using random credentials in the hub (since there is no authentication part), it directly starts from /opt/ directory and second thing, when I try to create a new notebook, it says permission denied.
```
[I 2018-08-08 07:34:35.321 SingleUserNotebookApp auth:875] Logged-in user {'kind': 'user', 'name': 'test', 'admin': False, 'groups': [], 'server': '/user/test/', 'pending': None, 'last_activity': '2018-08-08T07:34:33.364603'}
[I 2018-08-08 07:34:35.324 SingleUserNotebookApp log:158] 302 GET /user/test/oauth_callback?code=[secret]&state=[secret] -> /user/test/tree?redirects=1 (@10.48.2.1) 57.51ms
[I 2018-08-08 07:34:35.853 SingleUserNotebookApp log:158] 200 GET /user/test/tree?redirects=1 (test@10.48.2.1) 72.77ms
[I 2018-08-08 07:34:37.259 SingleUserNotebookApp log:158] 200 GET /user/test/api/config/tree?_=1533713676671 (test@10.48.2.1) 3.33ms
[I 2018-08-08 07:34:37.271 SingleUserNotebookApp log:158] 200 GET /user/test/api/config/common?_=1533713676672 (test@10.48.2.1) 3.12ms
[I 2018-08-08 07:34:37.273 SingleUserNotebookApp log:158] 200 GET /user/test/api/terminals?_=1533713676673 (test@10.48.2.1) 1.26ms
[I 2018-08-08 07:34:37.278 SingleUserNotebookApp log:158] 200 GET /user/test/api/sessions?_=1533713676674 (test@10.128.0.2) 2.52ms
[I 2018-08-08 07:34:37.281 SingleUserNotebookApp log:158] 200 GET /user/test/api/terminals?_=1533713676675 (test@10.128.0.2) 1.00ms
[I 2018-08-08 07:34:37.702 SingleUserNotebookApp log:158] 200 GET /user/test/api/contents?type=directory&_=1533713676676 (test@10.128.0.2) 4.08ms
[I 2018-08-08 07:34:41.281 SingleUserNotebookApp handlers:153] Creating new notebook in 
[W 2018-08-08 07:34:41.358 SingleUserNotebookApp web:1667] 403 POST /user/test/api/contents (10.128.0.2): Permission denied: Untitled.ipynb
[W 2018-08-08 07:34:41.359 SingleUserNotebookApp handlers:564] Permission denied: Untitled.ipynb
```
Any idea how to resolve both of these things?

**Comment by andrewcheny** [comment]
Same problem on AWS
kubectl --namespace naep get all
NAME                         READY     STATUS             RESTARTS   AGE
pod/hub-7c45d9cff-lsxng      0/1       CrashLoopBackOff   6          6m
pod/proxy-646c7c7847-v9h4w   2/2       Running            0          6m

NAME                   TYPE           CLUSTER-IP      EXTERNAL-IP        PORT(S)                      AGE
service/hub            ClusterIP      10.100.89.96    <none>             8081/TCP                     6m
service/proxy-api      ClusterIP      10.100.6.145    <none>             8001/TCP                     6m
service/proxy-http     ClusterIP      10.100.70.58    <none>             8000/TCP                     6m
service/proxy-public   LoadBalancer   10.100.140.74   a55efa7469b44...   80:31129/TCP,443:30694/TCP   6m

NAME                    DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/hub     1         1         1            0           6m
deployment.apps/proxy   1         1         1            1           6m

NAME                               DESIRED   CURRENT   READY     AGE
replicaset.apps/hub-7c45d9cff      1         1         0         6m
replicaset.apps/proxy-646c7c7847   1         1         1         6m

And the details for the pod:
kubectl --namespace naep describe pod/hub-7c45d9cff-lsxng
Name:           hub-7c45d9cff-lsxng
Namespace:      naep
Node:           ip-192-168-181-114.ec2.internal/192.168.181.114
Start Time:     Wed, 08 Aug 2018 15:50:44 -0400
Labels:         app=jupyterhub
                component=hub
                heritage=Tiller
                name=hub
                pod-template-hash=370185799
                release=devjhub
Annotations:    checksum/config-map=6caa0f2c7126d9a587d53904efc5ca651e1698dc0842436f24e4ea2ea4003058
                checksum/secret=2741b35b2a4a2873e2a4a59d1462c2e6913619b4febffea8cd0d5f93cf5dcfbe
Status:         Running
IP:             192.168.151.192
Controlled By:  ReplicaSet/hub-7c45d9cff
Containers:
  hub-container:
    Container ID:  docker://fca55c8a2d32697c09bdad5a192f7a04819f3f4b169d483f885bae7e2952fa66
    Image:         jupyterhub/k8s-hub:v0.6
    Image ID:      docker-pullable://jupyterhub/k8s-hub@sha256:04dd7d25d348016ec009647399adcea2833fc53a66e66e0c288d333e7c3aabd8
    Port:          8081/TCP
    Host Port:     0/TCP
    Command:
      jupyterhub
      --config
      /srv/jupyterhub_config.py
      --upgrade-db
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Wed, 08 Aug 2018 15:56:44 -0400
      Finished:     Wed, 08 Aug 2018 15:56:45 -0400
    Ready:          False
    Restart Count:  6
    Requests:
      cpu:     200m
      memory:  512Mi
    Environment:
      SINGLEUSER_IMAGE:        jupyterhub/k8s-singleuser-sample:v0.6
      POD_NAMESPACE:           naep (v1:metadata.namespace)
      CONFIGPROXY_AUTH_TOKEN:  <set to the key 'proxy.token' in secret 'hub-secret'>  Optional: false
    Mounts:
      /etc/jupyterhub/config/ from config (rw)
      /etc/jupyterhub/secret/ from secret (rw)
      /srv/jupyterhub from hub-db-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from hub-token-h9n4l (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          False 
  PodScheduled   True 
Volumes:
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      hub-config
    Optional:  false
  secret:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  hub-secret
    Optional:    false
  hub-db-dir:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  hub-db-dir
    ReadOnly:   false
  hub-token-h9n4l:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  hub-token-h9n4l
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                  Age                 From                                      Message
  ----     ------                  ----                ----                                      -------
  Warning  FailedScheduling        10m (x2 over 10m)   default-scheduler                         pod has unbound PersistentVolumeClaims (repeated 3 times)
  Normal   Scheduled               10m                 default-scheduler                         Successfully assigned hub-7c45d9cff-lsxng to ip-192-168-181-114.ec2.internal
  Normal   SuccessfulMountVolume   10m                 kubelet, ip-192-168-181-114.ec2.internal  MountVolume.SetUp succeeded for volume "config"
  Normal   SuccessfulMountVolume   10m                 kubelet, ip-192-168-181-114.ec2.internal  MountVolume.SetUp succeeded for volume "secret"
  Normal   SuccessfulMountVolume   10m                 kubelet, ip-192-168-181-114.ec2.internal  MountVolume.SetUp succeeded for volume "hub-token-h9n4l"
  Warning  FailedAttachVolume      10m (x3 over 10m)   attachdetach-controller                   AttachVolume.Attach failed for volume "pvc-55d4e0e5-9b44-11e8-b4d2-0e32ad42cf0c" : "Error attaching EBS volume \"vol-03d981bb498a679be\"" to instance "i-0d34c62940aa78ad3" since volume is in "creating" state
  Normal   SuccessfulAttachVolume  10m                 attachdetach-controller                   AttachVolume.Attach succeeded for volume "pvc-55d4e0e5-9b44-11e8-b4d2-0e32ad42cf0c"
  Normal   SuccessfulMountVolume   10m                 kubelet, ip-192-168-181-114.ec2.internal  MountVolume.SetUp succeeded for volume "pvc-55d4e0e5-9b44-11e8-b4d2-0e32ad42cf0c"
  Normal   Created                 9m (x4 over 10m)    kubelet, ip-192-168-181-114.ec2.internal  Created container
  Normal   Started                 9m (x4 over 10m)    kubelet, ip-192-168-181-114.ec2.internal  Started container
  Normal   Pulled                  8m (x5 over 10m)    kubelet, ip-192-168-181-114.ec2.internal  Container image "jupyterhub/k8s-hub:v0.6" already present on machine
  Warning  BackOff                 12s (x47 over 10m)  kubelet, ip-192-168-181-114.ec2.internal  Back-off restarting failed container

**Comment by MrwanBaghdad** [comment]
> Thanks a lot @consideRatio for replying. Here's the output:
> 
> ```
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/traitlets/traitlets.py", line 528, in get
>     value = obj._trait_values[self.name]
> KeyError: 'runtime_dir'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/bin/jupyterhub-singleuser", line 6, in <module>
>     main()
>   File "/usr/local/lib/python3.5/dist-packages/jupyterhub/singleuser.py", line 455, in main
>     return SingleUserNotebookApp.launch_instance(argv)
>   File "/usr/local/lib/python3.5/dist-packages/jupyter_core/application.py", line 266, in launch_instance
>     return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
>   File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 657, in launch_instance
>     app.initialize(argv)
>   File "<decorator-gen-7>", line 2, in initialize
>   File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
>     return method(app, *args, **kwargs)
>   File "/usr/local/lib/python3.5/dist-packages/notebook/notebookapp.py", line 1600, in initialize
>     self.init_configurables()
>   File "/usr/local/lib/python3.5/dist-packages/notebook/notebookapp.py", line 1293, in init_configurables
>     connection_dir=self.runtime_dir,
>   File "/usr/local/lib/python3.5/dist-packages/traitlets/traitlets.py", line 556, in __get__
>     return self.get(obj, cls)
>   File "/usr/local/lib/python3.5/dist-packages/traitlets/traitlets.py", line 535, in get
>     value = self._validate(obj, dynamic_default())
>   File "/usr/local/lib/python3.5/dist-packages/jupyter_core/application.py", line 99, in _runtime_dir_default
>     ensure_dir_exists(rd, mode=0o700)
>   File "/usr/local/lib/python3.5/dist-packages/jupyter_core/utils/__init__.py", line 13, in ensure_dir_exists
>     os.makedirs(path, mode=mode)
>   File "/usr/lib/python3.5/os.py", line 231, in makedirs
>     makedirs(head, mode, exist_ok)
>   File "/usr/lib/python3.5/os.py", line 231, in makedirs
>     makedirs(head, mode, exist_ok)
>   File "/usr/lib/python3.5/os.py", line 231, in makedirs
>     makedirs(head, mode, exist_ok)
>   File "/usr/lib/python3.5/os.py", line 241, in makedirs
>     mkdir(name, mode)
> PermissionError: [Errno 13] Permission denied: '/.local'
> ```

I had the same problem with permission denied for the /.local file. 
Why is that happening is part of the jupyterhub assumptions of an existing `uid` with value of 1000. 
If you noticed the images offered throught docker-stack contain a user jonyvan with same uid. 
However, the docker image I was trying to deploy is based on a root user image. 
To set this you have to pass `uid = 0` in the values.yaml files under singleuser.

```
proxy:
    secretToken: 'c4671cde90fedc892b8d64ad66dd2be46c9c7b9879c3e0b2bbf2445f406ef4c4'
    service:    
        type: NodePort
        nodePorts:
                http: 31132
                https: 31133
hub:
    extraConfig: |-
        c.Spawner.cmd = ['jupyter-labhub']
        c.Spawner.args = ['--allow-root']
        c.Spawner.uid = 0
        c.Spawner.gid = 0
        c.Spawner.delete_stopped_pods = False
        c.Spawner.debug = True
        c.JupyterHub.log_level = 'DEBUG'
        c.LocalProcessSpawner.debug = True
singleuser:
    image:
        name: localhost:15000/de-jobs-jupyter
        tag: latest

    uid: 0

**Comment by cbjuan** [comment]
Also, you can fix the permissions by using `chown -R` as part of an `initContainer` recipe. I'm using something like:


```yaml
singleuser:
  initContainers:
    - name: adjust-permissions
      image: alpine:latest
      command: ["/bin/sh", "-c"]
      args:
        - chown -R 1000:100 /home/jovyan;
      volumeMounts:
        - name: volume-{username}
          mountPath: /home/jovyan
      securityContext:
        runAsUser: 0
        allowPrivilegeEscalation: true
image:
    name: dockerUser/image
    tag: v0.1.0
```
