### ISSUE TITLE
Can i use kubernetes taints

### ISSUE THREAD

**Issue by Patafix** [jupyterhub/zero-to-jupyterhub-k8s#828]
Hello,
I want the jupyter pod only on certain node, that i reserved with taints.

Is it possible ?

**Comment by consideRatio** [comment]
Almost, I'm working hard on getting an update of the chart before JupyterCon, hopefully including the PR i list below that would allow this.

- https://github.com/jupyterhub/kubespawner/pull/205 - A PR that allows you to configure KubeSpawner easily to spawn user pods having tolerations for node taints
- #758 - Allows the zero-to-jupyterhub-k8s chart to utilize that KubeSpawner PR.

**Comment by Patafix** [comment]
Thx, i have succed to do it  with this line in the config.yaml

c.KubeSpawner.singleuser_extra_pod_config = {"tolerations": [{"key": "dedicated", "value": "datascience", "effect": "NoExecute"}]}
