### ISSUE TITLE
Build failure - a dependency probably changed - ideas?

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#831]
Chartpress started failing, no recent PR seem to have caused it but it is probably a dependency that has updated. Ideas?

https://travis-ci.org/jupyterhub/zero-to-jupyterhub-k8s/jobs/414321917/config

```
$ chartpress --commit-range ${TRAVIS_COMMIT_RANGE}
Skipping hub, not touched in e60a3837f8780c68a7b78d017751469f085534ec...d87056354c5de037033ec3e7266b67e07c568338
Skipping network-tools, not touched in e60a3837f8780c68a7b78d017751469f085534ec...d87056354c5de037033ec3e7266b67e07c568338
Skipping image-awaiter, not touched in e60a3837f8780c68a7b78d017751469f085534ec...d87056354c5de037033ec3e7266b67e07c568338
Skipping singleuser-sample, not touched in e60a3837f8780c68a7b78d017751469f085534ec...d87056354c5de037033ec3e7266b67e07c568338
Skipping pod-culler, not touched in e60a3837f8780c68a7b78d017751469f085534ec...d87056354c5de037033ec3e7266b67e07c568338
Updating jupyterhub/values.yaml: hub.image: {'repository': 'jupyterhub/k8s-hub', 'tag': 'c0157fc'}
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/bin/chartpress", line 11, in <module>
    sys.exit(main())
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/chartpress.py", line 303, in main
    build_values(chart['name'], value_mods)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/chartpress.py", line 200, in build_values
    f'The key {key} in {values_file} must be a mapping.'
TypeError: The key hub.image in jupyterhub/values.yaml must be a mapping.
```

Probably:
https://pypi.org/project/ruamel.yaml/

**Comment by betatim** [comment]
I'd have a look at what the type of the value really is. The conditional in chartpress that is failing is https://github.com/jupyterhub/chartpress/blob/9fe099952da8db1d85f780c7f563ea0c76074d81/chartpress.py#L187 which checks if the value is an instance of `dict`. From the exception it sure looks like a `dict` but maybe ruamel now uses their own mapping type?

Maybe the right thing is to update the chartpress if statement to use https://docs.python.org/3/library/collections.abc.html#collections.abc.Mapping instead of `dict`. A dict is a kind of mapping, but not all mappings have to be dicts.

**Comment by betatim** [comment]
Loaded some yaml from the mybinder.org repo with:

```python
from ruamel.yaml import YAML
yaml = YAML(type='rt')
yaml.indent(mapping=2, offset=2, sequence=4)
x = yaml.load(open("./mybinder.org-deploy/mybinder/values.yaml"))
```

which gives me lots of `ordereddict`s for which `isinstance(x, dict) == False` but `isinstance(x, collections.abc.Mapping) == True`.

**Comment by consideRatio** [comment]
@betatim ah!

Does this action plan make sense?
1. Verify a change in ruamel.yaml caused trouble by pinning to a previous version
2. Make an update to chartpress like you suggest see that helps

?

**Comment by consideRatio** [comment]
The change happen when I start using `ruamel.yaml==0.15.52` while `ruamel.yaml==0.15.51` is fine with `chartpress==0.2.0`.

**Comment by consideRatio** [comment]
Reopened this until builds work, they got into trouble now because images were not available, as the previous builds failed after being merged.

**Comment by minrk** [comment]
I did a manual push, so the latest chart should be published. Restarting tests so hopefully they will work
