### ISSUE TITLE
travis.pub and github_deploy_key.enc - dead files?

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#836]
Are these files used for something, or are they just staying around past their due date?
- `travis.pub`
- `github_deploy_key.enc`
  The deploy script that sets up git to use a key for pushing the helm chart to the helm-chart repo is using the `travis.enc` file.

**Comment by choldgraf** [comment]
Hmmmm that's a good question - I bet they're stale. It seemsl ike `github_deploy_key.enc` is from an earlier attempt at getting the docs to build with `doctr` ([here's the commit](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/commit/c2768c09030874e24ff02b50afccfb90db321dab) and [I think this is a relevant parent commit](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/commit/97ccf4c6a1e671a289fdea848fb81ceef79ea8e2))
