### ISSUE TITLE
Fontsize on front page

### ISSUE THREAD

**Issue by arokem** [jupyterhub/zero-to-jupyterhub-k8s#847]
The new font is very elegant, but you might want to tune the font-size to avoid this: 
<img width="237" alt="screen shot 2018-08-14 at 8 05 34 pm" src="https://user-images.githubusercontent.com/118582/44129494-8509f5f8-9ffd-11e8-909c-6b94bd78f763.png">

**Comment by choldgraf** [comment]
arggg - thanks for noticing @arokem !! I think this happened because alabaster got updated and the new fonts don't behave quite the same way. Good catch!

**Comment by consideRatio** [comment]
@choldgraf hmmm whats going on here

I'm using master and building the docs with...

```sh
cd doc
make html
```

But what I get does not look like on z2jh.jupyter.org but what it used to look like, I have not changed anything though...

**Comment by willingc** [comment]
I think that sphinx copybutton adds an sccs file somehow that is overwriting some other css settings. If you remove copybutton in conf.py docs render as they did before (minus the copy button).

**Comment by willingc** [comment]
After a bit more investigation, it looks as if copybutton brings in some bootstrap scss in particular _type.scss which is causing a new setting for width

<img width="333" alt="screen shot 2018-08-16 at 3 33 52 pm" src="https://user-images.githubusercontent.com/2680980/44238617-576a7500-a16a-11e8-8708-5972ce25fa83.png">
