### ISSUE TITLE
helm upgrade fail: selector does not match template labels

### ISSUE THREAD

**Issue by ryanlovett** [jupyterhub/zero-to-jupyterhub-k8s#848]
Output from travis:
```
Update Complete. ⎈ Happy Helming!⎈ 
INFO:root:Executing helm upgrade --install --wait staging jupyterhub/jupyterhub --namespace staging --version v0.6 -f hub/config.yaml -f hub/secrets/staging.yaml -f /tmp/tag-4759189.yaml --timeout 3600
Error: UPGRADE FAILED: Deployment.apps "proxy" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"component":"proxy", "heritage":"Tiller", "name":"proxy", "release":"staging"}: `selector` does not match template `labels`
Traceback (most recent call last):
  File "./deploy.py", line 140, in <module>
    main()
  File "./deploy.py", line 138, in main
    deploy(args.release)
  File "./deploy.py", line 109, in deploy
    '--timeout', '3600'
  File "./deploy.py", line 31, in helm
    return subprocess.check_call([arg0] + list(args), **kwargs)
  File "/opt/python/3.6.3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['helm', 'upgrade', '--install', '--wait', 'staging', 'jupyterhub/jupyterhub', '--namespace', 'staging', '--version', 'v0.6', '-f', 'hub/config.yaml', '-f', 'hub/secrets/staging.yaml', '-f', '/tmp/tag-4759189.yaml', '--timeout', '3600']' returned non-zero exit status 1.
```

This is on Azure with a kubernetes cluster deployed via acs-engine.

chart v0.6
helm 2.9.1

**Comment by ryanlovett** [comment]
If I retry the upgrade after deleting the failed configmap, I get
```
Error: UPGRADE FAILED: no Secret with the name "manual-tls-proxy-staging" found
```
which is #466.

**Comment by ryanlovett** [comment]
I'm attempting to upgrade after having defined
```
proxy:
  https:
    hosts:
      - my.host.name
    type: manual
    manual:
      key: ...
      cert: ...
```

**Comment by ryanlovett** [comment]
I had to delete the release to stop this from happening. Normally I wouldn't do this on production, but the semester hasn't started yet.

**Comment by consideRatio** [comment]
Thanks for reporting this @ryanlovett! 

Helm tends to end up in a bad state with multiple Helm chart revisions considered to be Deployed at the same time. This is at least one of the key differences with installing fresh that we must help users handle.

In #638 are some steps one can take to mitigate these issues. I think we end up with multiple Helm revisions of a chart being considered to be Deployed when we fail during an upgrade, some of the times. They have fixed some bugs relating to this, so it will hopefully not be common in the future assuming we run with new Helm versions.

**Comment by ryanlovett** [comment]
Were the deployment selector labels changed because I added something to the helm config?

What are your thoughts on whether I should always add --force to our `helm install --upgrade` process?

I've run into these sorts of helm issues quite a bit, usually (always?) on Azure, but I think I've only ever seen multiple chart revisions in DEPLOYED once and that was at least six months ago.

**Comment by consideRatio** [comment]
If you are using v0.6 before and after the upgrade, you are just making a change to something in the config right? Is this what was done? Hmmm... But I've seen helm give really wierd error messages that were simply misleading.

Hmmm, I think I'd choose to use --force all the time yes (me as an individual person would that is). Too vague of pro/con to make a clear summary, but I'm not confident about the negatives, while I'm confident on the positives - upgrades will not fail as often and helm wont enter wierd states.

**Comment by ryanlovett** [comment]
Yes, v0.6 before and after -- I added manual SSL certs.

I don't plan on adding anything else and hopefully I won't need to, but if I do and run into this I'll try to force it. A failed force upgrade still leaves me with something more functional than a purge! 😄

**Comment by consideRatio** [comment]
@ryanlovett can we close this issue? Related to this btw, is that I've now written down thorough upgrade instructions for 0.7.0 including a lot of cleanup of helm resources etc that could have caused trouble previously.

**Comment by ryanlovett** [comment]
Sure. I haven't tried to do the failing upgrading from 0.6 to 0.6 w/manual ssl certs. If I do I'll use --force and report back.
