### ISSUE TITLE
IFRAME, EMBED: embedding a jupyterhub into an iframe

### ISSUE THREAD

**Issue by odewahn** [jupyterhub/zero-to-jupyterhub-k8s#85]
I'm trying to embed my jupyterhub server (http://jupyterhub.odewahn.com) into an iframe, but am getting this in the browser:

```
Refused to display 'http://jupyterhub.odewahn.com/hub/login' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self'".
```

Is there a way to enable this in the config.yaml file?

**Comment by choldgraf** [comment]
Huh - that's weird. I've gotten this to work myself, see this page for an example (it's my fork of the z2jh docs):

http://predictablynoisy.com/zero-to-jupyterhub-k8s/cost.html#interactive-cost-estimator

that said I think as a general rule we're gonna try and discourage IFrames until we can increase the resources available to Binder (particularly if the page will have a lot of traffic)

**Comment by odewahn** [comment]
That's a really cool example for binder!  Do you have any docs on how you enabled the iframe?  I wasn't able to find the setup for it anywhere.

**Comment by zcesur** [comment]
You have probably fixed this by now, but [this](https://github.com/zcesur/embeddable-jhub-sample) configuration did the trick for me!

**Comment by choldgraf** [comment]
wow - nice workaround :-)

**Comment by consideRatio** [comment]
Thanks @zcesur! :) I tried to make the topic more findable, closing issue hoping anyone will find this issue.
