### ISSUE TITLE
Document enabling required APIs for GCP

### ISSUE THREAD

**Issue by aculich** [jupyterhub/zero-to-jupyterhub-k8s#86]
On GCP 3 APIs need to be enabled:

- Compute Engine API
- Container Engine API
- Container Registry API

![image](https://user-images.githubusercontent.com/118965/27089498-5d050104-500f-11e7-8c06-82874e29dc9c.png)

**Comment by aculich** [comment]
Note that it may take several minutes until APIs are enabled:

![image](https://user-images.githubusercontent.com/118965/27089655-e3e57f00-500f-11e7-9585-e80c49601d04.png)

**Comment by choldgraf** [comment]
Agree this is important for users to know. Think you could add the first image + some simple instructions to the following file in a PR?

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/doc/source/create-k8s-cluster.rst

**Comment by yuvipanda** [comment]
We did this.
