### ISSUE TITLE
Sqlite Error: (sqlite3.OperationalError) database is locked

### ISSUE THREAD

**Issue by abhismvit** [jupyterhub/zero-to-jupyterhub-k8s#872]
Hi Team,

After using the helm guide for zerto to jupyterhub.
I am getting below error while setting up the jupyterhub.
Sqlite Error: (sqlite3.OperationalError) database is locked

https://zero-to-jupyterhub.readthedocs.io/en/latest/setup-jupyterhub.html

```
2018-08-24T16:34:37.126076000Z       File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/default.py", line 509, in do_execute
2018-08-24T16:34:37.126466000Z         cursor.execute(statement, parameters)
2018-08-24T16:34:37.126939000Z     sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked [SQL: '\nCREATE TABLE alembic_version (\n\tversion_num VARCHAR(32) NOT NULL, \n\tCONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)\n)\n\n'] (Background on this error at: http://sqlalche.me/e/e3q8)
2018-08-24T16:34:37.127341000Z   
```

**Comment by minrk** [comment]
You might need to clear out the Hub database. You can do this by deleting the volume that corresponds to the `hub-db-dir` claim:

```
$ kubectl get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS    CLAIM                               STORAGECLASS   REASON    AGE
pvc-5a2122c0-52c4-11e8-bae9-42010a800282   1Gi        RWO            Delete           Bound     staging/hub-db-dir                  standard                 117d <- this one
pvc-5a2434ac-52c4-11e8-bae9-42010a800282   8Gi        RWO            Delete           Bound     staging/staging-prometheus-server   standard                 117d
pvc-fcb04dd8-52c6-11e8-bae9-42010a800282   0          RWO            Delete           Bound     staging/staging-grafana             standard                 117d
$ kubectl delete pv pvc-5a2122c0-52c4-11e8-bae9-42010a800282
```

This will lose any user/authentication state in the Hub. If you haven't successfully launched the Hub yet, this won't matter.

**Comment by consideRatio** [comment]
I'd recommend starting by deleting the PVC called hub-db-dir first instead of deleting the PV. If you do that and wait a minute, the PV should have been deleted by the cloud provider. If not, delete it manually as well.

If you would delete the PV first, the PVC called hub-db-dir will enter a "LOST" state, and it may conflict when you try to upgrade the chart again. I think of a PVC in the LOST state as a Pod that are in FAILED state, blocking the resource name to be reused, but is simply remaining as a trace for debugging.

**Comment by dhirschfeld-shell** [comment]
A bit late to the party but it seems with Azure Files the `nobrl` mount option might be useful:

![image](https://user-images.githubusercontent.com/107382673/180148796-e05084ed-ad97-49a7-b098-fa5e28f8d1af.png)

https://docs.microsoft.com/en-us/troubleshoot/azure/azure-kubernetes/mountoptions-settings-azure-files
