### ISSUE TITLE
Unable to drain node where hub or proxy pods are running

### ISSUE THREAD

**Issue by clkao** [jupyterhub/zero-to-jupyterhub-k8s#873]
It appears the default pdb configuration (min available: 1) makes it impossible to drain nodes running hub or proxy. kubectl drain node -v9 will show 429 too many requests.

**Comment by minrk** [comment]
What's the exact drain command you are using? We have drained nodes with the hub and/or proxy on them on mybinder.org pretty often, with:

```
kubectl drain --force --delete-local-data --ignore-daemonsets --grace-period=0
```

**Comment by clkao** [comment]
yeah this is the exact command i use as well on 1.10.5.  it could be different pdb behaviour though. what version of kubernetes is mybinding running on?

**Comment by consideRatio** [comment]
Hmmm, I wonder why you got a 429 response from the k8s api-server, but if thats your response, then its not the command itself but its rather "hey stop spamming me" right? Did you have a `watch` looping doing something intensively in the background?

Closing as there is no clear thing to do with regards to this repo.
