### ISSUE TITLE
Proxy-public external ip is pending 

### ISSUE THREAD

**Issue by yugushihuang** [jupyterhub/zero-to-jupyterhub-k8s#880]
Hello,

I just follow the "Zero to Jupyter" tutorial on AWS EC2. Everything works fine, but at the last step, the external-ip is pending.

```
NAME           TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
proxy-public   LoadBalancer   100.70.36.147   <pending>     80:31165/TCP   5h
```

**Comment by consideRatio** [comment]
On GKE it takes about a minute or less, this is after a minute or more right?

**Comment by yugushihuang** [comment]
Yes

**Comment by matthiaslee** [comment]
I'm having the same issue, though I'm using minikube on an EC2 instance

**Comment by consideRatio** [comment]
This is cloud-provider related, and I sadly lack experience of solving this issue. I find it similar to how the cloud provider needs to provision PVs when it finds PVCs requesting PVs. In this case though, it is rather the Service named `proxy-public` requesting a LoadBalancer and an IP to it from the cloud-provider.

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/1d835e9a783daa51ced8b581c45be1bb123b46e6/jupyterhub/templates/proxy/service.yaml#L72-L75

**Comment by nikhilsen** [comment]
I am also fasing this issue that external ip of the loadbalancer seems pending

**Comment by nikhilsen** [comment]
I am also facing this issue that external ip of the load balancer seems pending
