### ISSUE TITLE
Be explicit about hardware vs. computational resources

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/zero-to-jupyterhub-k8s#89]
There are a few places where we casually use the word "hardware" when we really mean to say "computational resources", e.g. "you can give your users expanded hardware by ..." .

Since increasing resources to users is technically different from actually using different hardware, we should be more clear on this.

cc @yuvipanda

**Comment by consideRatio** [comment]
I searched through the docs on `hardware` and found it okay.
