### ISSUE TITLE
(repo2docker) Must specify user-id during image build to successfully spawn pods on GKE 

### ISSUE THREAD

**Issue by samuelmanzer** [jupyterhub/zero-to-jupyterhub-k8s#894]
*Note*: I provide versions of all my tools at the end for reference. 

I cannot spawn singleuser pods due to issues with how the `jovyan` user is handled in containers spawned on GKE. For simplicity, I have a repository containing nothing but this `requirements.txt`:

```
numpy==1.14.3
matplotlib==2.2.2
scikit-learn==0.19.1
jupyter==1.0.0
pandas==0.23.3
jupyterhub==0.9.2
pyzmq==17.0.0
tornado==4.5.3
scipy==1.0.0
```

If I then build and push an image as follows: 

```
jupyter-repo2docker --user-name jovyan --image-name test-image --no-run .
docker tag test-image gcr.io/${MY_PROJECT}/test-image
docker push  gcr.io/${MY_PROJECT}/test-image
```

then my singleuser pods will crash upon startup with this error:

```
Traceback (most recent call last):
  File "/srv/venv/bin/jupyterhub-singleuser", line 6, in <module>
    main()
  File "/srv/venv/lib/python3.6/site-packages/jupyterhub/singleuser.py", line 495, in main
    return SingleUserNotebookApp.launch_instance(argv)
  File "/srv/venv/lib/python3.6/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/srv/venv/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "/srv/venv/lib/python3.6/site-packages/jupyterhub/singleuser.py", line 402, in initialize
    return super().initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/srv/venv/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/srv/venv/lib/python3.6/site-packages/notebook/notebookapp.py", line 1366, in initialize
    self.init_configurables()
  File "/srv/venv/lib/python3.6/site-packages/notebook/notebookapp.py", line 1100, in init_configurables
    connection_dir=self.runtime_dir,
  File "/srv/venv/lib/python3.6/site-packages/traitlets/traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "/srv/venv/lib/python3.6/site-packages/traitlets/traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "/srv/venv/lib/python3.6/site-packages/jupyter_core/application.py", line 99, in _runtime_dir_default
    ensure_dir_exists(rd, mode=0o700)
  File "/srv/venv/lib/python3.6/site-packages/jupyter_core/utils/__init__.py", line 13, in ensure_dir_exists
    os.makedirs(path, mode=mode)
  File "/usr/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/jovyan/.local'
```
The error can be fixed by building the image this way instead: 

```
jupyter-repo2docker --user-name jovyan --user-id 1000 --image-name test-image --no-run .
```

Running the built image locally with docker works even when `user-id` is not specified during build, so this is something related to K8s. 

I'm happy to do a PR to update the docs if this is the correct way to build the image, and not compensating for something else I did wrong. 

### Hub Image Version

```
jupyterhub/k8s-hub:0.7.0-beta.2
```

### K8s Version

```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-19T00:05:56Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.7-gke.5", GitCommit:"9b635efce81582e1da13b35a7aa539c0ccb32987", GitTreeState:"clean", BuildDate:"2018-08-02T23:42:40Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

### Contents of `config.yaml`
```
singleuser:
  image:
    name: gcr.io//${MY_PROJECT}/test-image
    tag: "1.0"
    pullPolicy: Always
  storage:
    type: none
```

**Comment by consideRatio** [comment]
@samuelmanzer ah!! We have recently removed the guides step about using repo2docker to build images to be used with a plain jupyerhub from this repo and are now [trying to recommend the practice of building a new image](https://zero-to-jupyterhub.readthedocs.io/en/latest/user-environment.html#customize-an-existing-docker-image) `FROM` some other image in [jupyter/docker-stacks](https://github.com/jupyter/docker-stacks).

I think we should avoid the complexity of asking our users to build images using repo2docker for the purpose of using them with z2jh, but the [section about adding files](https://zero-to-jupyterhub.readthedocs.io/en/latest/user-environment.html#about-user-storage-and-adding-files-to-it) may be relevant to highlight or the usage of `nbgitpuller`.

---

For your specific case, I'd recommend building your image from some image in the docker-stacks, see the section about selecting your image in their docs. But then, how do you get the users their content? Well you could run some command getting it for them in the postStart hook instead.

I see that you are declaring `storage.type: none` which means the users are not getting any storage, in that case I'd recommend using `gitpuller`, which I think will be installed by default in the image coming with the 0.7.0 release of the chart.

See https://github.com/jupyterhub/nbgitpuller and #888 .

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/custom-docker-image-fails-to-run-spawn-failed/10264/2
