### ISSUE TITLE
Docker-stack pyspark-notebook single-user image on kubernetes

### ISSUE THREAD

**Issue by ianalis** [jupyterhub/zero-to-jupyterhub-k8s#895]
I would like to use the [docker-stacks `pyspark-notebook`](http://jupyter-docker-stacks.readthedocs.io/en/latest/using/specifics.html#apache-spark) as the single-user image for my jupyterhub running on kubernetes. According to the image's [documentation](http://jupyter-docker-stacks.readthedocs.io/en/latest/using/specifics.html#connecting-to-a-spark-cluster-in-standalone-mode), I need to run the image on docker with the `--net=host` option so that I can connect to a Spark cluster outside the pod. This corresponds to the `hostNetwork: true` option in the Kubernetes pod spec and I confirmed this by directly creating a pod with this spec using `kubectl`.

I modified `config.yaml` to something like the following but the single-user pod used the virtual node IP instead of the host IP :

```
hub:
  extraConfig: |
    c.KubeSpawner.extra_pod_config = {
        'hostNetwork': True,
        'hostPID': True
    }
```

I also tried using `'true'` instead of `True` but it still didn't work. 

How should I modify `config.yaml` so that I can run the `pyspark-notebook` docker-stack as a single-user image that can connect to an external Spark cluster?

**Comment by minrk** [comment]
It doesn't seem like using host-networking would be the right thing to do on kubernetes. Where/how is the spark cluster deployed? Is it in another pod(s)?

**Comment by ianalis** [comment]
The Spark cluster is in another pod (and namespace). I was able to turn on host networking and run Spark on the pod by changing the attribute from `extra_pod_config` to `singleuser_extra_pod_config`:

```
hub:
  extraConfig: |
    c.KubeSpawner.extra_pod_config = {
        'hostNetwork': True,
        'hostPID': True
    }
```

Unfortunately, I didn't see this attribute name in any documentation and only found about it when I looked at the log. 

Closing this issue now. Thanks.

**Comment by frouzbeh** [comment]
@ianalis Hi, I have a Spark on Yarn cluster and also have a Kubernetes cluster on the same machines, I deployed JupyterHub on Kubernetes, and now want to connect to the Spark, but I'm not sure how should I do that?  I didn't quite understand how you fixed your problem.  Would you care to explain a little bit? Thanks

**Comment by ianalis** [comment]
@frouzbeh I think I've encountered this problem before but I'm not sure where. Have you checked whether the environment variable SPARK_LOCAL_IP is defined in the single-user pod?

**Comment by frouzbeh** [comment]
@ianalis I don't think so, but in my case it should be localhost, right? Do you know what other environment variables I need to defined in the single user pods?

**Comment by wlyu** [comment]
@frouzbeh 
Did you let it work? 
k8s + jupyter/all-spark-notebook + Spark/Yarn

**Comment by frouzbeh** [comment]
@wlyu Yes, it's working.

**Comment by humbledude** [comment]
I found it is working today.
```
hub:
  extraConfig:
    hostNetwork: |
      c.KubeSpawner.extra_pod_config = {
        'hostNetwork': True,
      }
```

reference:
https://github.com/jupyterhub/kubespawner/blob/2530634f0ce683f82ebcf07ddcc2b739ecc5657f/kubespawner/spawner.py#L859
