### ISSUE TITLE
kubespawner.profile_list - image-pulling of multiple images

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#903]
We need to ensure we can pre-pull multiple images efficiently, as it is possible to configure a `profile_list` now in kubespawner.

See https://github.com/jupyterhub/kubespawner/pull/137.

**Comment by clkao** [comment]
prePuller supports multiple `extraImages`

**Comment by consideRatio** [comment]
@clkao awesome thanks for the pointer! Leaving this open a bit longer until I've looked at this further.

**Comment by consideRatio** [comment]
Thats the way to go, now we need an example.
