### ISSUE TITLE
jupyterhub_config.py and values.yaml - duplicated default values 

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#913]
We are setting some default values in both jupyterhub_config.py as well as values.yaml. If both are set, whatever is in jupyterhub_config.py will never trigger due to a value will always be provided thanks to `values.yaml` passing its default value through the hub's configmap to jupyterhub_config.py that will think "oh no need for me to provide a default then!".

**Comment by yuvipanda** [comment]
I left comments about this in #341

**Comment by minrk** [comment]
Closing as duplicate of #341
