### ISSUE TITLE
CHANGELOG.md - Adding entries - how to do it?

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#916]
We should have a practice for adding or not adding these. I recently read about how GitLab works and a new world of ideas is opening up. If someone is experienced about these things already please provide some input :D

## Resources
- https://docs.gitlab.com/ce/development/changelog.html
- https://github.com/github-changelog-generator/github-changelog-generator
- https://keepachangelog.com/en/1.0.0/

**Comment by consideRatio** [comment]
Dumping short entry here to get it out of my head: the singleuser server `EMAIL` environment variable was for the users are removed in between 0.7 and 0.8.

**Comment by willingc** [comment]
@consideRatio What has worked well for us is what we do on jupyterhub: https://github.com/jupyterhub/jupyterhub/blob/master/docs/source/changelog.md

We use the diff between versions as a link for the release number. From there, Min and I typically summarize the key things for minor releases with major releases getting additional subheadings (New; Changed; etc.)

**Comment by consideRatio** [comment]
@willingc thanks for the insight!

**Comment by manics** [comment]
I've just saw https://pypi.org/project/towncrier/ mentioned on another project. Based on the readme it sounds like a nice compromise between dumping everything from the commit or PR descriptions vs everyone updating the same file.

**Comment by consideRatio** [comment]
For our reference:
- https://opensource.com/article/19/3/managing-changes-open-source-projects
- https://keepachangelog.com/en/1.0.0/

**Comment by consideRatio** [comment]
I've started using `github-activity` like this:

1. Use `github-activity` to get a mardown file of all PRs that have merged since last release
2. Visit all these PRs and add a label which is [recognized by github-activity to have a certain meaning](https://github-activity.readthedocs.io/en/latest/#splitting-prs-by-tags-and-prefixes)
3. Use `github-activity` again to get a new markdown file where all PRs are categorized since last release, copy paste that into the CHANGELOG document.
4. Write some complementary notes about breaking changes and such.
