### ISSUE TITLE
Notify JupyterLab when server is stopped

### ISSUE THREAD

**Issue by clkao** [jupyterhub/zero-to-jupyterhub-k8s#918]
(Continued from the discussion from https://github.com/jupyterlab/jupyterlab/issues/4298 as it's more related to hub environment)

Apparently as soon as we remove the chp route for an user, the user's JupyterLab gets unexpected responses (as they are redirected back to hub).

One way is to install a chp route matching those known endpoints of singleuser servers, and mimics a failed server that would allow JupyterLab to temporarily work in disconnected mode.

**Comment by consideRatio** [comment]
AHA!!! Wow thanks for this insight! Hmmmm, I wonder at what end this should be solved. Z2JH / JupyterLab?

**Comment by minrk** [comment]
I think this is a job for some cooperation of JupyterLab and JupyterHub. JupyterHub has [
this patch](https://github.com/jupyterhub/jupyterhub/pull/2001/files) which should get a JSON 404 on any API requests coming from JupyterLab, with jupyterhub >= 0.9.1. I'm not sure if it's catching every case yet, though.

**Comment by consideRatio** [comment]
I don't think i fully understand this issue. It may still be relevant, but as we have not identified a clear suggested path forward I'm closing it until such path forward is suggested.
