### ISSUE TITLE
Include a "things we'd love help with" section

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/zero-to-jupyterhub-k8s#93]
What do you all think about including a section listing some of the high-level things we need help with (e.g., Julia support in repo2docker, Azure / XSEDE support)

**Comment by willingc** [comment]
I think the idea is good. I'm not sure that I would list the items in the document. Instead, I would have a link for the document to the issue tracker and mention that we welcome contributions especially on issues marked "Help wanted".

**Comment by choldgraf** [comment]
That works too - I just wanna make sure that it's clear this is a project where we welcome community input :-)

**Comment by willingc** [comment]
Absolutely! We love community input :-)

**Comment by jzf2101** [comment]
I'd like to follow up on this and add additional details @choldgraf
