### ISSUE TITLE
Add how to turn off persistent storage

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/zero-to-jupyterhub-k8s#94]
We don't do that currently!

**Comment by willingc** [comment]
- [ ] Add functionality
- [ ] Document it

**Comment by choldgraf** [comment]
More specifically, we should also *undocument* it if this won't be ready fairly soon. (e.g., see just above [here](https://zero-to-jupyterhub.readthedocs.io/en/latest/extending-jupyterhub.html#pre-populating-home-directory-with-notebooks-when-using-persistent-volumes))

**Comment by yuvipanda** [comment]
We do have this ability, just not documented yet.

**Comment by choldgraf** [comment]
We should also document how to increase the amount of persistent storage available to users (or if this isn't an explicit thing users need to configure, mention this)

**Comment by yuvipanda** [comment]
Both of these are in the pr I opened a while ago. Need to polish...

**Comment by yuvipanda** [comment]
We have this now.
