### ISSUE TITLE
Using imagePullSecrets for hub

### ISSUE THREAD

**Issue by clancychilds** [jupyterhub/zero-to-jupyterhub-k8s#945]
From what I can see in the charts, there is a imagePullSecrets implemented for singleuser images, but not for the hub itself.
I was hoping to make my own hub image based off of juptyerhub/k8s-hub:0.7.0 and then pull it down from a private gcr.io registry. I have this working for my singleuser image using _jsonkey in the config,yaml, but the same functionality isn't in place for hub images.

**Comment by consideRatio** [comment]
true, quick question, is the private registry in your same google cloud project as you have your cluster? then it works right away without setup

**Comment by clancychilds** [comment]
It would be at some point, but I'm trying to make sure that it also is able to run on minikube, on premise k8s and elsewhere.
I'm actually pulling from the same docker registry as singleuser, so I'm looking to see if I can just inject imagePullSecrets.name.singleuser-image-credentials into the hub Pod spec right now. Might try to make a PR later to "do it right".

**Comment by clancychilds** [comment]
This has been fixed and merged.

**Comment by consideRatio** [comment]
Thank you @clancychilds ! :heart:
