### ISSUE TITLE
Document using nbzip to download a user's session

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/zero-to-jupyterhub-k8s#946]
https://github.com/data-8/nbzip is a nifty project for zipping/downloading files from a notebook server session. Perhaps we should recommend the use of this in Z2JH (or TLJH) somewhere!

**Comment by consideRatio** [comment]
That is a cool tool, I'll go ahead and close this issue without further comment as I failed to figure out a sensible place to document it in the z2jh docs without creating a new section. =/

This is extra relevant for workshops and such.
