### ISSUE TITLE
Add switching between SSD and HDD for user persistent storage

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/zero-to-jupyterhub-k8s#95]
We don't do this either currently.

**Comment by willingc** [comment]
@yuvipanda Just to clarify...the ability to switch between SSD and HDD user persistent storage needs to be supported first and then documented.

**Comment by willingc** [comment]
- [ ] Add functionality
- [ ] Document it

**Comment by yuvipanda** [comment]
Ah, nope - we do currently have the ability in the helm chart to do it, just not documented

**Comment by yuvipanda** [comment]
We have this now as part of #356
