### ISSUE TITLE
User can't access service,when k8s cluster reboot

### ISSUE THREAD

**Issue by moskiGithub** [jupyterhub/zero-to-jupyterhub-k8s#954]
When k8s cluster reboot, User can't access self jupyterlab, but activate pods display on hub page. And Jupyterhub admin role remove user's pods, user can access self jupyterlab. 
## Read the logs: 
```
01:05:32.044 - error: [ConfigProxy] 503 GET /user/test/api/sessions?1537923930532 Error: connect EHOSTUNREACH 10.35.0.193:8888
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
01:05:32.045 - error: [ConfigProxy] 503 GET /user/test/api/sessions?1537923930532 Error: connect EHOSTUNREACH 10.35.0.193:8888
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
```
**According to my understanding, user pods can not communicate with proxy normally, user pods should be removed, will not be displayed 503 error**

**How to solve it** 

My config:
## Contents of `config.yaml`
```
hub:
  extraConfig: |-
    c.Spawner.cmd = ['jupyter-labhub']

proxy:
  secretToken: "a0d5a11ff1498f3a5jonf145bee18b167e17d3d79629526d54abb51a242a8e8d"

singleuser:
  defaultUrl: "/lab"

cull:
  enabled: true
  users: true
  timeout: 172800
  every: 300

prePuller:
  hook:
    enabled: false

debug:
  enabled: true

```

**Comment by moskiGithub** [comment]
Helle @consideRatio
k8s cluster reboot mean the all machines of kubernetes cluster(include master and node) reboot, and all server would restart. When I login in, hub redirect to my lab pods. but I can't come into lab to launch notebook, logs reports:
hub can display active status of my lab server, but I try to connect my lab server, hub and proxy throw 503 error, can't reach my lab server.

**Comment by consideRatio** [comment]
I think if nodes are restarted, JupyterHub will recover properly in current versions, where it actively checks for user pods and if they are accessible on startup and every 30 minute or so.
