### ISSUE TITLE
Amazon provides hostname for external LoadBalancer IP

### ISSUE THREAD

**Issue by ryanlovett** [jupyterhub/zero-to-jupyterhub-k8s#957]
According to the [kubernetes docs](https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/#exposing-the-service), AWS creates an ELB for the external IP and displays a hostname for the external proxy-public IP rather than an IP. Perhaps this should be noted on [setup-jupyterhub.rst](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/c368fb4f6a6a01877c680beaf2084c57dca6ad19/doc/source/setup-jupyterhub.rst) or [security.md](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/doc/source/security.md#set-up-your-domain) where EXTERNAL-IP is referenced, or forewarned on one of the "Step 0" Amazon pages. Otherwise it it may be confusing to people who are expecting an IP (see #953).

**Comment by consideRatio** [comment]
Closing this issue as i included and referenced it as a small item in a issue triage report instead.
