### ISSUE TITLE
"Secure Helm" step is broken with Helm 2.10

### ISSUE THREAD

**Issue by manics** [jupyterhub/zero-to-jupyterhub-k8s#959]
@consideRatio pointed out in Gitter that Helm 2.10 has a bug which means The `Secure Helm` step on https://zero-to-jupyterhub.readthedocs.io/en/stable/setup-helm.html breaks Helm. The doc currently says `Make sure you have at least version 2.9.1`. Should this be updated to 2.11? Or just add a note to avoid 2.10?

**Comment by consideRatio** [comment]
@manics I think we should go with recommending 2.11, as that is also required for k8s 1.11 which is out on various cloud providers - even though GKE is behind :'(

Thanks for helping out with this @manics !!! :heart:
