### ISSUE TITLE
TLS connection error between helm and tiller

### ISSUE THREAD

**Issue by vishal49naik49** [jupyterhub/zero-to-jupyterhub-k8s#965]
Hi,

I am getting below error while running helm commands:

$ helm ls --tls
Error: forwarding ports: error upgrading connection: unable to upgrade connection: Unauthorized

Please advise!

Thanks!

**Comment by consideRatio** [comment]
If you use k8s 1.11, make sure you have helm 2.11.

Other than this, i dont know how to help =\

**Comment by minrk** [comment]
Does `helm ls` work? Can you `kubectl get pod`?

**Comment by consideRatio** [comment]
Version of k8s and helm is also relevant, and how / where the k8s cluster is setup.

**Comment by vishal49naik49** [comment]
Kubectl port-forward command itself gives me same error. I guess it is not related to helm.
Any chance I can get feedback on the port-forward error here in this forum?

Thanks,
Vishal

**Comment by consideRatio** [comment]
@vishal49naik49, this is not related to this repo's Helm chart, but I figured I could help out anyhow briefly. 

My take on the situation though is depending a lot on the answers to both me and @minrk's questions above.

**Comment by vishal49naik49** [comment]
kubectl get pods, get nodes, get svc - work just fine
kubectl port-forward gives me "error: forwarding ports: error upgrading connection: unable to update connection: Unauthorized"

**Comment by consideRatio** [comment]
About the cluster setup then? You may need to do a step like the one here in step 7: https://zero-to-jupyterhub-with-kubernetes.readthedocs.io/en/latest/google/step-zero-gcp.html

**Comment by vishal49naik49** [comment]
Tried binding the User to a role as per the instructions from step7. Still same error.
My masters are behind a load balancer (tried connecting bypassing lb as well) and api server connection is over https.

Thanks,
Vishal

**Comment by vishal49naik49** [comment]
I can see x509: certificate specifies an incompatible key usage in the kubelet logs.

I am trying as an admin user
Please advise

Thanks!

**Comment by vishal49naik49** [comment]
I was able to fix this issue actually. The kubelet client cert supplied to the api service had ‘server auth’. Changed it to client auth and it worked like charm. Closing!

**Comment by seamanjiang** [comment]
> I was able to fix this issue actually. The kubelet client cert supplied to the api service had ‘server auth’. Changed it to client auth and it worked like charm. Closing!

Hi vishal49naik49, i have met the same problem and change kubectl's config ~/kube/config from server auth -> client auth, but it doesn't work... 

Haven u some advice?
Thanks!

ca-config.json
{
  "signing": {
    "default": {
      "expiry": "87600h"
    },
    "profiles": {
      "kubernetes": {
        "usages": [
            "signing",
            "key encipherment",
            "client auth"
        ],
        "expiry": "8760h"
      }
    }
  }
}
