### ISSUE TITLE
Simplify logic to configure the authenticators

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#968]
We are currently hardcoding the passthrough of certain configuration fields for each different authenticator, this is a bit messy and can make us miss out on certain configuration options.

I just found this to have happened in: https://gitlab.com/gitlab-org/gitlab-ce/issues/52536

I think we should generalize this, perhaps we could simply write to the keys the authenticator's traitlet based on what has been provided. If such key isnt defined, I recall the traitlet will warn that no such key was found.

This could be a continuation on @minrk's #941 that makes our code a lot less complex to maintain.

**Comment by minrk** [comment]
There are both positive and negative consequences to this:

1. everything configurable is exposed (good)
2. there need only be one source of documentation for authenticators (good: one source for authenticators; bad: multiple sources for helm chart)
3. directly configuring authenticators looks different from the rest (Python style, not go style, which the rest of helm uses). This requires users to know more about how the chart works in order for things to be clear (not good)

**Comment by consideRatio** [comment]
With the experience gained over two years since this issue was created, I'm now quite confident I'd like to go with a more transparent configuration, where we don't add custom formatting etc.

Added features or renamed configuration options in authenticators etc that doesn't properly reflect the configuration options here have been a hurdle.

**Comment by consideRatio** [comment]
Closed in favor of #1871
