### ISSUE TITLE
Step Zero: Add a chapter on setting up a custom Kubernetes Cluster

### ISSUE THREAD

**Issue by moschlar** [jupyterhub/zero-to-jupyterhub-k8s#976]
Would it be desirable to have an additional chapter for Step Zero about setting up a custom Kubernetes Cluster on "custom" infrastructure e.g. on premises? I successfully accomplished this using [Rancher 2.x](https://rancher.com/docs/rancher/v2.x/en/) as a cluster management software. (I also experimented with an even more manual approach using `kubeadm`, but that was too tedious.)

I'd be happy to write down my experiences for others.

**Comment by manics** [comment]
There's a related discussion on https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/593
Previously I've used kubespray on OpenStack, but recently tried Rancher 2.x and it looks like it might be easier.

**Comment by moschlar** [comment]
Ah, sorry, I missed that.
So Rancher 2.x would be considered bare metal and fall into _Grade C_ from @yuvipanda's grading system:
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/593#issuecomment-378404019

**Comment by betatim** [comment]
Having a documentation on how to do this would definitely be good and I agree on the "grade C" rating. Maybe create a repository with example config and docs and then link to it from the guide?

**Comment by Nujjy** [comment]
> Would it be desirable to have an additional chapter for Step Zero about setting up a custom Kubernetes Cluster on "custom" infrastructure e.g. on premises? I successfully accomplished this using [Rancher 2.x](https://rancher.com/docs/rancher/v2.x/en/) as a cluster management software. (I also experimented with an even more manual approach using `kubeadm`, but that was too tedious.)
> 
> I'd be happy to write down my experiences for others.

Been trying for a while to figure out how to get JupyterHub deployment on Rancher managed Kubernetes. Would really like to know what you did.

**Comment by verdurin** [comment]
Yes, more details would be very useful.

**Comment by consideRatio** [comment]
I've added a remark that its wanted to have some notes about baremetal clusters in my issue triage report!
