### ISSUE TITLE
Improve the imagePullSecrets documentation

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#981]
We are missing an example of working configuration, and could perhaps now avoid duplicating the documentation within the hub's imagePullSecret and the singleuser's imagePullSecret.

**Suggested action:**
- visit schema.yaml and add an example of a working configuration
- update the hub.imagePullSecret to reference the singleuser.imagePullSecret

**The current generated documentation, based on the schema.yaml file:**
https://zero-to-jupyterhub-with-kubernetes.readthedocs.io/en/latest/reference.html#singleuser-imagepullsecret

**Comment by consideRatio** [comment]
See @dkippings comment as well, we should point to Azure / GKE / Amazon guides for doing this perhaps? This can be done manually by referencing the secret manually created following these guides, but no matter what, the input to the helm chart needs to follow their guides even though the helm chart can automate the creation of the secret.

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/447#issuecomment-431310730

**Comment by ablekh** [comment]
@consideRatio  I agree with the idea of pointing to Azure (AKS) / GCP (GKE) / AWS (EKS) guides for this aspect (as well as for other platform-specific aspects). By the way, the _z2jh_ documentation hyperlink above is incorrect; the correct one is without the "-with-kubernetes" part: https://zero-to-jupyterhub.readthedocs.io/en/latest/reference.html#singleuser-imagepullsecret.

**Comment by dkipping** [comment]
@consideRatio just referencing to [this guide](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-auth-aks#access-with-kubernetes-secret) and mentioning that the second step (creating a kubernetes secret) will be needed to reference it in the jupyterhub's `config.yaml` should already help. This might e.g. be done as a note in the jupyterhub doc.

PS: The link is not working, it should be https://zero-to-jupyterhub.readthedocs.io/en/latest/reference.html#singleuser-imagepullsecret

So without the _-with-kubernetes_
