### ISSUE TITLE
Make control panel page fully dynamic

### ISSUE THREAD

**Issue by ablekh** [jupyterhub/zero-to-jupyterhub-k8s#998]
This issue/suggestion is not specific to _z2jh_, but, for now I will leave it here, to get initial feedback. I have noticed that JupyterHub's **control panel** page does not dynamically (not requiring refreshing the page in a browser) update relevant information, except for actions on "start/stop server" button clicks. Since those actions are dynamic, I thought that, for consistency (and common sense), it might be a good idea to implement **dynamic updates** for other relevant pieces of information (off the top of my head now: user status / via start stop buttons and number of active users). Should people accept this idea as feasible, the implementation would need to cover both single-server and newly developed multi-server configurations.

**Comment by consideRatio** [comment]
Hi @ablekh that would be cool indeed, I recall seeing discussion about this in the jupyterhub/jupyterhub where this issue should go, so I'll go ahead and close it instead of transfer it.
